### ISSUE TITLE
Point Sufia and CC users at Hyrax

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1]
As soon as Hyrax is a thing that can be tested and used, add documentation to the Sufia and CC READMEs that clarifies the role between all three gems and the known timeline for any changes (e.g., what are our plans for new Sufia and CC versions?). Point at https://wiki.duraspace.org/pages/viewpage.action?pageId=87461232 for more information, and keep that page updated as we go.

**Comment by anarchivist** [comment]
![Picture of Hyrax](https://i.ytimg.com/vi/MYFa7b8LSHQ/maxresdefault.jpg)

**Comment by mjgiarlo** [comment]
The noble hyrax.

**Comment by escowles** [comment]
![hyrax](https://cloud.githubusercontent.com/assets/856924/20768862/8d93ccf6-b70d-11e6-96cb-07999f4531f7.jpg)
https://www.flickr.com/photos/pamas/19756465613

**Comment by mjgiarlo** [comment]
Thanks for taking this on, @bess!

**Comment by mjgiarlo** [comment]
@bess @dheles Do y'all want to stay assigned to this issue?

**Comment by no-reply** [comment]
Closing this as stale.
