### ISSUE TITLE
License field should be single-valued by default, and overrideable

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#105]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [awead](https://github.com/awead)**
_Thursday Aug 20, 2015 at 01:34 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1287_

----

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Aug 20, 2015 at 14:09 GMT_

----

I'm not sure this is _always_ true. Probably for the 99% though.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Aug 20, 2015 at 17:55 GMT_

----

I suspect it's always true for folks who aren't overriding any of the select values for that field.  And if they're already overriding that... :smile: 

I don't think it makes any sense to let folks select multiple CC licenses, or to select a CC license and "All rights reserved." The default select values suggest single-valued field to me.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Thursday Aug 27, 2015 at 19:41 GMT_

----

The only places I've seen someone assign multiple (CC) licenses to an object, I'm pretty sure they screwed up. I've been racking my brain for the past week trying to think of a case where one could actually assign multiple CC licenses and i've come up with nothing.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Friday Aug 28, 2015 at 01:44 GMT_

----

Yes, my exception case was licenses from the library, not CC licenses.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Aug 31, 2015 at 22:14 GMT_

----

I spent a day or two hacking on this but I need to move onto other things.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Aug 31, 2015 at 22:15 GMT_

----

Hrm. We just made this happen locally.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Aug 31, 2015 at 22:18 GMT_

----

Maybe the magic incantation is in here: https://github.com/osulp/Scholars-Archive/commit/746e02a0e5fccc85217450ae560d0191500900b9

Thanks for the heads-up, @vantuyls 

@straleyb if you want to toss a fix upstream, that'd be great!

**Comment by mjgiarlo** [comment]
<a href="https://github.com/straleyb"><img src="https://avatars.githubusercontent.com/u/6424683?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [straleyb](https://github.com/straleyb)**
_Monday Aug 31, 2015 at 22:20 GMT_

----

Yeah, I'll update and send a PR. If not this afternoon, tomorrow morning. :+1:

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Aug 31, 2015 at 22:20 GMT_

----

INTERNET!

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Aug 31, 2015 at 22:21 GMT_

----

:clap: :fireworks:  @vantuyls @straleyb

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Sep 11, 2015 at 17:18 GMT_

----

Are you still interested in working on this @straleyb?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Dec 14, 2015 at 22:05 GMT_

----

Paging @straleyb and @vantuyls. :)

If you are interested in contributing this work back, please do issue the PR against the `6.x-stable` branch.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/newmanld"><img src="https://avatars.githubusercontent.com/u/3521707?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [newmanld](https://github.com/newmanld)**
_Tuesday Oct 25, 2016 at 15:00 GMT_

----

We're taking a look at making this field single valued in our local implementation.  Multiple rights statements didn't make sense to us, and seemed a good use case for multi-part works.  I'll refer the developer who has taken our local issue to this thread.

**Comment by vantuyls** [comment]
@mjgiarlo do you know if anyone else is working on this right now? we're trying to balance local versus universal changes and dont want to replicate.

**Comment by mjgiarlo** [comment]
@vantuyls Nope, no one is working on this AFAIK. Thanks!

**Comment by no-reply** [comment]
This seems reasonable, but I'd like to close it pending recommendations incoming from @samvera/hyrax-metadataists.
