### ISSUE TITLE
List collections on home page instead of admin sets

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1067]
### Descriptive summary

Promoting user collections as a means of browsing the repository content, instead of admin sets

### Rationale

Admin sets as an organizing mechanism should not be made visible on the public page of the application. User collections -- created by any user permitted to create a collection -- should be used instead. 

### Expected behavior

As a public viewer of the repository, when I go to the home page, I should see user collections, not admin sets, listed under 'Explore Collections' and available in a list after I click on 'View all collections'

### Actual behavior

As a public viewer of the repository, when I go to the home page, I see admin sets when I click on 'Explore Collections" and on the Admin Sets list page after I click on 'View all collections'

**Comment by julesies** [comment]
Curious how one would navigate to ETDs or something that would likely be an admin set? Would facet's include admin sets?

**Comment by ggeisler** [comment]
@julesies I think there are still details that need to be worked out but what @hannahfrost and I discussed is the idea of being able to configure a collection to mirror an admin set (an option only available to collections created by repo admins or admin set managers). So we would still stick to never exposing admin sets to the public, meaning no, facets wouldn't show admin sets, but provide an easy way to have a given collection mirror an admin set, and the collection could be faceted (another issue up to discussion).

Do you think that would work for your use case?

Aside from not exposing the "administrative set" terminology to the public, there are other advantages to this approach, such as the requirement coming from the Display Sets WG for being able to "brand" a collection (e.g., add a collection description, logos), that we don't get from just showing an admin set directly.

**Comment by julesies** [comment]
I definitely like not exposing the term admin set to the public - for sure! but I am curious what Admin Sets use cases there would be that would not be desired to be discovered as such. I can only think of examples that should be. ETDs, Senior Theses, The Center for Highway Safety. I also wonder if it could just be something like: Discover all Admin Sets and Collections as Collections; denote the difference with a visual cue or icon (like to show the difference b/w a user collection and an institutional collection aka Admin Set).

**Comment by ggeisler** [comment]
That certainly could be another way of doing it, @julesies, and would probably make more sense if it is the case that people will always want to expose their admin sets to the public (I don't doubt that, just don't really know enough about what people do with admin sets at different institutions).

**Comment by julesies** [comment]
ah ok. I guess since admin sets are new to Hyrax/Sufia it makes sense we don't know what people are doing, but I'm guessing we could gather what people are planning for implementation. I am out of the loop with display sets, I was just thinking that for us, we will probably turn off "Collections" and want users to discover Admin Sets (not called that of course) and I couldn't figure out how I could do that.

**Comment by hannahfrost** [comment]
@julesies Thanks for your input. I agree that one can envision a set of objects managed as an admin set that are prime for search and discovery as such, which is why we had admin sets discoverable in the first place. But no one (that I know) likes the term "admin set" for the public side of the repository. And we realize that if an admin set has a corresponding user collection that is indexed for search and discovery, that we can leave the terminology as it is and make a cleaner distinction between admin set and collection as two mechanisms for organizing and managing content. Does that make sense? 

You should consider joining the Display Sets working group, since it seems like you would have valuable input to the issues we are addressing there. More input and feedback on these directions is very much welcome!

**Comment by hannahfrost** [comment]
@julesies I understand the impulse to just use Admin Sets and call them something else in the UI. But Admin Sets are limited in their functionality, notably in that a work cannot be a member of more than one Admin Set, and Admin Sets are not nestable. This is a deal breaker for some Hyrax users. So we are looking at Collections as the means to provide the flexibility needed for works on the presentation and discovery side.

Some possible configurable options that I see include:
1. create a collection for every admin set that is created (1:1)
2. disable index and discovery of collections that are not created by administrative users

**Comment by julesies** [comment]
Ok thanks @hannahfrost. You know I've been working for 1.5 years to remove nesting from our repository 😬. We still use it for digital collections but not IR. Those configurations sound good. I also hope to not to have to do nesting 😂.

The other thing I wondered was if these double collections are persistent in fedora or is it higher in the stack? Curious about any potential performance drags....

**Comment by ggeisler** [comment]
@julesies FWIW, the nesting requirement as presented by the Display Set WG would be a configurable option, so it could be turned off by those who don't want it.

**Comment by hannahfrost** [comment]
@julesies That's a good question about performance. @jcoyne and @mjgiarlo should be able to address it.

**Comment by geekscruff** [comment]
+1 to showing collections instead of admin sets on the home page, and for promoting collections to users over admin sets.

**Comment by elrayle** [comment]
This was just brought to my attention.  I see a couple of options that are compatible with the [collection extensions requirements](https://wiki.duraspace.org/x/g402BQ).  The one I favor is taking advantage of the `discoverable` setting.  If `collection_type.discoverable?` AND `collection.visibility=PUBLIC` then include it in the list of collections on the home page.

**Comment by julesies** [comment]
@elrayle thanks for linking the document, it's very helpful. so it sounds like Admin sets are meant to be discoverable by the document but will we have support for that in the first phase? Also, I am wondering if collections extensions is targeted for a specific hyrax release. I think the removal of discovering admin sets in facets and home page is removed in Hyrax 2.0? I'm currently trying to set up Admin Sets and Workflows for our migration, in Hyrax 1 so sorry my knowledge is limited. I'm trying to figure out if work types are the way to do in order to discover "Dissertations" as a collection. At least that would work for facets. 

tagging @samvera/hyrax-repo-managers
