### ISSUE TITLE
Accessing the Works page from Collections has a UI element missing

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#1069]
### Descriptive summary

on the Repository Content - Works page of the dashboard, the page has All Works and Your Works tabs at the top of the page to help the user orient themselves to what works they are looking at in the table below. When accessing this page using the Add Works button on a Collections page, the tabs don't appear.

### Rationale

This is a UI bug that doesn't appear when the Works page is accessed otherwise, and thus should be addressed for consistency and because it helps with user orientation on the page. 

### Expected behavior

From the Add Works button on a Collections page, the Works page should show the tab outlines at the top of the Works page around one of the two view options (All Works or Your Works).

### Actual behavior
Neither All Works or Your Works is highlighted on the page. 

### Steps to reproduce the behavior

1. Go to a collection
2. Select Add Works button
3. Note that the highlight tabs are not highlighted on the Works page
4. For reference - select the Works page directly from the Dashboard and note that the Your Works tab is highlighted 

![screen shot 2017-05-26 at 11 35 34 am](https://cloud.githubusercontent.com/assets/9534576/26507938/7a986302-4207-11e7-9253-ec2dad4e4345.png)

this is what it looks like when coming from Add Works button on Collections page

![screen shot 2017-05-26 at 11 35 24 am](https://cloud.githubusercontent.com/assets/9534576/26507939/7b48820a-4207-11e7-8ea9-84e2092adc70.png)

this is what it looks like when coming to Works from the Dashboard - note the highlighted tab

**Comment by mjgiarlo** [comment]
I can't reproduce in Hyku. Will try again with Hyrax test app.

**Comment by vantuyls** [comment]
hmm. i just confirmed this in hyrax.

**Comment by mjgiarlo** [comment]
okie dokie, @vantuyls.

**Comment by vantuyls** [comment]
[work page wierdsies.zip](https://github.com/samvera-labs/hyrax/files/1032762/work.page.wierdsies.zip)

**Comment by mjgiarlo** [comment]
@vantuyls Hyrax master or 1.x?

**Comment by vantuyls** [comment]
master
