### ISSUE TITLE
lacking or broken default representative icon for audio work

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1074]
I would expect to see a generic audio or media icon to go along with a work that is an audio resource type and features an audio file, but instead I see a broken image icon labeled "default"

![screenshot 2017-05-26 14 20 45](https://cloud.githubusercontent.com/assets/1801076/26513110/a2bcec2e-421e-11e7-85b2-7da847188846.png)

**Comment by jcoyne** [comment]
This may be a hyku issue. Possibly broken when we added UV

**Comment by hannahfrost** [comment]
On a different work containing audio file in a new tenant, the audio icon does appear. In general I am noticing that thumbnails/icons are extremely slow to load

**Comment by atz** [comment]
See also: https://github.com/samvera-labs/hyrax/issues/1095

**Comment by hannahfrost** [comment]
Link to the work pictured above: https://salad.demo.hydrainabox.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=robert+alway

**Comment by hannahfrost** [comment]
Hi @dlpierce, Do you have an update on this ticket and the related one, https://github.com/samvera/hyrax/issues/1095?  We are doing some ticket queue management and wanted to check in. Let us know, if you would please, what you have learned, if anything. Thanks!

**Comment by dlpierce** [comment]
@hannahfrost I believe this would have been fixed by a PR of mine that I didn't realize was still open. I'll aim to resolve this issue this week.

**Comment by hannahfrost** [comment]
Ah, that's great to hear! Thanks @dlpierce. Much appreciated.

**Comment by mjgiarlo** [comment]
@dlpierce What's the status of your PR?

**Comment by dlpierce** [comment]
@mjgiarlo Other projects got in the way, but I'm working on this now and making sure the fix is still valid since it has been sitting a while.

**Comment by mjgiarlo** [comment]
Excellent. Thanks, @dlpierce!

**Comment by vantuyls** [comment]
this has been resolved. work level icon appears (or a streaming interface if appropriate). fileset level icon is for an audio item.
