### ISSUE TITLE
Generated indexer contradicts itself

### ISSUE THREAD

**Issue by atz** [samvera/hyrax#1077]
The [generator](https://github.com/samvera-labs/hyrax/blob/master/lib/generators/hyrax/work/templates/indexer.rb.erb) includes both:
```ruby
  include Hyrax::IndexesBasicMetadata
```
and:
```ruby
  include Hyrax::IndexesLinkedMetadata
```

That is useless, since [IndexesBasicMetadata](https://github.com/samvera-labs/hyrax/blob/master/app/indexers/concerns/hyrax/indexes_basic_metadata.rb#L5-L7) and [IndexesLinkedMetadata](https://github.com/samvera-labs/hyrax/blob/master/app/indexers/concerns/hyrax/indexes_linked_metadata.rb#L5-L7) both override `rdf_service` differently (`BasicMetadataIndexer` vs. `DeepIndexingService`).  And that's ALL they do.  Only the last one "wins", so there is no point including the first one.  

MOREOVER, why is this stuff buried in a module that the user has no understanding of anyway, just to hide the one thing the module actually does?  We should just put this in the generator:
```ruby
def rdf_service
  DeepIndexingService # Unlike BasicMetadataIndexer, fetches remote labels for based_near
end
```

And remove `DeepIndexingService` completely.  (Further work could be done to eradicate `BasicMetadataIndexer`).

**Comment by jcoyne** [comment]
If you don't want to deal with linked metadata, then the procedure is to comment out or remove `include Hyrax::IndexesLinkedMetadata` and then it still works.

**Comment by atz** [comment]
@jcoyne That isn't different than having a commented out redefinition of the method.  Or having it defined twice, which would make more obvious that what we have is backwards.  This is just bad form with obfuscation to hide hit.

**Comment by no-reply** [comment]
This seems fine, and functions to provide the fallback @jcoyne described. Refactors are welcome (especially ones that use more flexible patterns than multiple/module inheritance), but I'm going to close this as a tracked issue.
