### ISSUE TITLE
Unexpected Relationships display

### ISSUE THREAD

**Issue by atz** [samvera/hyrax#1078]
Created a work (via batch), viewed locally at http://localhost:3000/concern/generic_works/gx41mh844?locale=en

- Why is "Rare books/atlas" a type of relationship?
- Why do other relationships get filler text when empty, but Admin Set doesn't?

<img width="518" alt="screen shot 2017-05-26 at 4 55 58 pm" src="https://cloud.githubusercontent.com/assets/109954/26515908/4e532890-4234-11e7-9a31-9ee05e346924.png">

**Comment by mjgiarlo** [comment]
You get one row per generated curation concern, and I guess RareBooks/Atlas is the second generated concern.

Weird that you were able to deposit a work *not* into an Admin Set. That should never be empty.

**Comment by atz** [comment]
Maybe there is an admin set without any label text to display?  idk.  In any case, we should have a fallback like the other rows, perhaps with a more strenuous warning like "Go make an AdminSet ASAP!"
