### ISSUE TITLE
Byte size of a collection should be > 0 if there are fileful works in it

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1080]
On a collection's show page, the size of the collection is listed, and the value is consistently shown as "0 Bytes". I would expect the # of bytes to equal the sum of the files contained within the works in the collection. (Please also keep in mind that works may contain other works.)

**Comment by mjgiarlo** [comment]
@hannahfrost I think the intent here was to add up the sizes of all filesets in all works contained within the collection. It may be worth keeping given the likelihood of big changes coming w/r/t how we use the different collection types in Hyrax?

**Comment by hannahfrost** [comment]
That's fine, @mjgiarlo. In that case, I wonder if byte count is broken

**Comment by mjgiarlo** [comment]
It sure seems like it, @hannahfrost! I'll rework this issue.

**Comment by VivianChu** [comment]
@hannahfrost - It seems like the byte count issue is fixed.  I just updated to the latest Hyrax and it worked fine for me.  Attached is the screen shot.  Could you take a look? Thanks
![collectionview](https://user-images.githubusercontent.com/1864660/40207137-ccc6cbca-59e7-11e8-8bf5-0fcbfac31ff0.png)

**Comment by no-reply** [comment]
This also seems okay on nurax. Closing this as non-reproducible.
