### ISSUE TITLE
Some icons in dashboard menu not showing in Safari

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1084]
The icons intended to appear to the left of three menu items -- Repository activity, Your activity, and Works -- do not appear on Safari 10.1.1

![screenshot 2017-05-28 08 37 05](https://cloud.githubusercontent.com/assets/1801076/26529983/f4b5f2f6-4380-11e7-8eb4-ab4cbc0199f3.png)

**Comment by jcoyne** [comment]
All seem to work for me.
<img width="1007" alt="screen shot 2017-05-31 at 5 00 44 pm" src="https://cloud.githubusercontent.com/assets/92044/26655974/b7d15e1c-4622-11e7-8895-691d30922ab8.png">

I have safari 10.1.2

**Comment by no-reply** [comment]
@samvera/hyrax-ui-ux-advisors Can anyone reproduce this with Nurax?

**Comment by julesies** [comment]
related ticket: https://github.com/curationexperts/nurax/issues/79 I confirmed this issue still exists on nurax.

**Comment by julesies** [comment]
updated from today: 
Safari
![screen shot 2018-07-09 at 3 46 46 pm](https://user-images.githubusercontent.com/4356335/42472459-60595f80-838f-11e8-8609-d4a3592eff84.png)

Chrome
![screen shot 2018-07-09 at 3 47 38 pm](https://user-images.githubusercontent.com/4356335/42472462-63005e14-838f-11e8-99b4-88c2029119bf.png)
