### ISSUE TITLE
Unable to edit file label in file manager

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1085]
### Descriptive Summary 

As a user with the permissions to edit a work, I need to be able to edit the labels of files using the File Manager.

### Rationale
Sometimes a file label needs to be changed, and a user with edit permissions for a work's file should be able to carry out this action and save the change.

### Expected Behavior

Using the File Manager, I expect to click on the edit icon next to the field where the file label is displayed and by doing so, the label field should become an editable field. 

### Actual Behavior

I cannot click the edit icon, so am not able to edit the field.
![screenshot 2017-05-28 11 39 24](https://cloud.githubusercontent.com/assets/1801076/26531366/79b9caf2-439c-11e7-920a-2bb1afe7b400.png)

**Comment by mjgiarlo** [comment]
From @mtribone:
> I think it is because there are so many `float: left` declarations _inside_ of the rectangle. A quick fix is to remove `float: left` from the div with class `panel-heading ui-sortable-handle` that contains the radio buttons. Long term fix would be to address all of the floats inside the rectangle. May not be needed

Looking into this, the `ui-sortable-handle` class appears to be coming from jquery-ui-rails, and it looks like FontAwesome is injecting the `float: left`.

**Comment by mtribone** [comment]
It's how the card is constructed with Bootstrap. The offending class is `panel-heading` and may need to be overridden or rework how the vertical cards are written.

**Comment by mtribone** [comment]
![screen shot 2017-09-25 at 2 47 00 pm](https://user-images.githubusercontent.com/4163828/30825428-f8b735fc-a200-11e7-9869-3980da19bd1c.png)

**Comment by mjgiarlo** [comment]
Thanks, @mtribone! I see we now have https://github.com/samvera/hyrax/pull/1722 to deal with this.
