### ISSUE TITLE
Filter collections on Works dashboard page, instead of admin sets

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1086]
The Works dashboard page currently offers a filter labeled 'Collections' but actually filters on admin sets.
It should filter on collections. 

Given that a work can be in more than one collection, the design of the table view of the filtered works needs to be able to accommodate such scenarios and make it understandable to the user.

I think that could be useful to add an Admin Set filter to the Works page, so that it is possible to drill down to a subset of works based on all available relationships. @ggeisler Do you agree? 

![screenshot 2017-05-28 14 05 27](https://cloud.githubusercontent.com/assets/1801076/26532189/05f10cee-43af-11e7-8b83-b3f9eb26f14d.png)

**Comment by hannahfrost** [comment]
Related to https://github.com/samvera-labs/hyrax/issues/1067

**Comment by mjgiarlo** [comment]
I wonder if this ticket should be "re-label Collections as Admin Sets." (That is, a simple label change.)

**Comment by hannahfrost** [comment]
Right. Well almost. I still think adding a filter for Collections, in addition to Admin Sets, would be useful.

If we agree, then the ticket should be "re-label existing Collections filter as Admin Sets, and add Collections filter"

**Comment by mjgiarlo** [comment]
@hannahfrost We agree! What would you think of making these two tickets?

**Comment by vantuyls** [comment]
work  has been completed. closing issue as no longer relevant.
