### ISSUE TITLE
Replace instructional text on Add New Work descriptions tab

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1087]
This line of text appears near the top of the Descriptions tab on the Add New Work/Image screen:
"The more descriptive information you provide the better we can serve your needs." (shown in attached screenshot)

This instruction is vague and inconsistent in tone with other instructional text in the app. Suggest we replace with the following:
"Completely describe your work using the form below. Use additional fields to increase discovery of your content."

 

![screenshot 2017-05-29 19 55 59](https://cloud.githubusercontent.com/assets/1801076/26566621/8515393c-44a9-11e7-9509-64b0d1af5995.png)

**Comment by atz** [comment]
Is "discovery" a thing that can be "increased"?  Simply by adding more fields?  Note: this is not how Solr relevance works (not that we actually use relevance much).  A larger, "noisier" document will score as **less** relevant for the same number of hits in the same fields.

**Comment by mjgiarlo** [comment]
I believe this means that providing more metadata will make it easier to find a file with more terms. If you only give a work a title, that gives you many fewer terms that will return the work in a result set.

**Comment by mjgiarlo** [comment]
@hannahfrost I'm cool with the text you suggest. What would you think of dropping "Completely"?

**Comment by mjgiarlo** [comment]
:point_up: would like to hear @ggeisler's thoughts too.

**Comment by hannahfrost** [comment]
@mjgiarlo Fine with dropping "completely"
@atz Currently the required fields for Hyku are few, definitely limiting discovery. If you have suggestions for a better word than "increased", I'm open to suggestions.

**Comment by ggeisler** [comment]
@hannahfrost @mjgiarlo I'm definitely in favor of replacing the current text. I agree that removing "Completely" is probably better.

Does this get at the goal of the last sentence?

"Use additional fields to increase the number of ways your content can be discovered."

**Comment by hannahfrost** [comment]
> "Use additional fields to increase the number of ways your content can be discovered."

I like it, @ggeisler

**Comment by mjgiarlo** [comment]
:+1:

**Comment by mjgiarlo** [comment]
OK, great, all! Removed "feedback needed" label, and inclined to push it towards ready. @hannahfrost What priority would you attach to this work?

**Comment by hannahfrost** [comment]
@mjgiarlo Low priority.

**Comment by jcoyne** [comment]
Fixed by #2228?
