### ISSUE TITLE
Edit/delete options and misleading 'unauthorized' message for depositors in mediated workflow

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#1090]
### Descriptive summary

 A depositor does not get the right to edit back after their deposit has been approved, but they still see edit and delete options against their work in the works list. Selecting either option leads to the message:

Unauthorized
The work you have tried to access is private

This message is misleading as it implies that it relates to the access status of the item. Ideally, user shouldn't see the options to edit or delete AND  the error should reflect what they were trying to do, eg. ‘you don’t have permission to edit/delete this item’

[ observed in Hyku v1.0.0.beta1 ]

### Rationale

The message is misleading and implies that the user should have the ability to do those things, but that the software is not functioning properly.

### Expected behavior

1) The user does not see the option to edit or delete in the dropdown.
2) Error messages reflect what the user was trying to do

### Actual behavior

1) User sees edit/delete options
2) Unauthorized message is misleading

### Steps to reproduce the behavior

1. Submit as a 'depositing' user to the mediated worfklow
2. Approver approves the deposit
3. Depositing user returns to their works list and sees 'edit' and 'delete'

### Related work

Related issue described here (re unintuitive messages for workflow steps) #1024

**Comment by mjgiarlo** [comment]
Discuss overlap with #172.

**Comment by mcdowney** [comment]
This has been fixed, closing.
