### ISSUE TITLE
Share My Work redirects to dashboard after login

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#1092]
### Descriptive summary

If a user is not logged in, Share My Work redirects them to login (Good) but then takes them to the dashboard. From here it is not obvious how to create a new work.

### Rationale

As a user when I click on 'Share My Work' I want it to be obvious how to create a new work after login.

**Comment by mjgiarlo** [comment]
I would like input from @samvera-labs/hyrax-ui-ux-advisors on this one.

**Comment by atz** [comment]
100% Agree.  Also, once logged in, if you **return** to the page where there once was an enticingly simple "Share My Work" button... it's no longer there AND there is nothing comparably shiny and simple telling you how to do the thing you were promised.

**Comment by newmanld** [comment]
Seems that the "Share My Work" button - after login - should go to the same place as "Share My Work" goes if already logged in, which is the list where work types are chosen.  In our app (screenshot attached) we have made this a separate page.  

Seems more obvious to have people select a work type than to go to the Dashboard, particularly if they are new contributors.  Our app is currently on Sufia 7.x but we are rapidly changing to Hyrax.  We are in a beta test period - I've asked our product owners if they have an opinion on this but no response as yet.  Pretty confident that they will say it should go to the same place, which is our "What are you uploading?" page where work types are selected.   

![image](https://cloud.githubusercontent.com/assets/3521707/26656472/3c2ac91e-462d-11e7-9f01-c96cf22fddf8.png)

**Comment by hannahfrost** [comment]
Hyrax uses a modal, not a full page like yours, @newmanld , for kicking off the work type selection and subsequent creation flow, 

Is it possible to direct the user to the Works screen on the dashboard after login?

**Comment by newmanld** [comment]
@hannahfrost - Yes we are aware of the modal.  Our product owners had a strong preference for a full page so that is one of our local overrides.  

Our local feedback has confirmed both that the behavior should be consistent - whether logged in or not - and that the destination should be the screen where users select a Work for upload (in our case a page rather than a modal), not the Dashboard.  

In the vanilla version of Hyrax 1.x I have locally implemented, if already logged in, and I return to the home page and select "Share Your Work", I see the modal (overlaying the home page).  But if not logged in, I will be sent to the Dashboard after logging in.

**Comment by hannahfrost** [comment]
@mjgiarlo Did you intend to ping the ux-advisors group for input on this ticket?

**Comment by mjgiarlo** [comment]
@hannahfrost Yep. Updated my comment above (which broke when Hyrax was promoted from the -labs organization). Thanks!

**Comment by julesies** [comment]
Wondering if this might be resolved in the 2.0 milestone.

**Comment by mjgiarlo** [comment]
@julesies Possibly! I'm not sure there's a clear direction yet for what to do here, so the ticket as is may not be actionable.

**Comment by mjgiarlo** [comment]
For now, I am making a small change that redirects users to the My Works page (where they can create works) instead of the Dashboard. Hope that's a "good enough" small change for the time being, so we can get it into the 2.0.0 release.

**Comment by mjgiarlo** [comment]
https://github.com/samvera/hyrax/pull/1635
