### ISSUE TITLE
Thumbnails cannot always be created; default behaviour needed

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#1095]
### Descriptive summary

When a thumbnail can’t be created for a file, the UI still attempts to display the 'default' thumbnail via RIIIF, eg. http://localhost:9292/images/WORK/files/FILESET/full/!150,300/0/default.jpg

But because there is no image in the first place, nothing is retrieved and the a 500 error is logged

Tested on plain text files (eg. json).

### Rationale

It won't always be possible to generate a thumbnail for a deposited file type therefore some default behaviour is needed.

### Expected behavior

A standard thumbnail icon should display.

### Actual behavior

No icon is displayed; a 500 error is logged

### Steps to reproduce the behavior

1. Deposit something that won't get a thumbnail (eg. some json)
2. View the work page and observe the files list

**Comment by mjgiarlo** [comment]
Upload a plain-text file to reproduce this.

**Comment by mjgiarlo** [comment]
See also #1074.

**Comment by dlpierce** [comment]
This should be filed under hyku, but the issue is similar to samvera-labs/hyku#1280 except now it is the `thumbnail?` method that is preventing thumbnail-less filesets from showing the default icon. I'll put up a PR tomorrow.
