### ISSUE TITLE
User profile: highlighted works are not showing

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#1097]
### Descriptive summary

User profile: highlighted works aren’t showing up on profile apart from in the ‘my works’ list

[ observed in Hyku v1.0.0.beta1 ]

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Expected behavior

It should show up somewhere on the user profile

### Actual behavior

Gets a star in the works list for the user, but otherwise isn't shown anywhere else

### Steps to reproduce the behavior

1. Create a work
2. Go to profile and 'highlight it' using the drop down menu at the side of the work

### Related work

Link to related tickets or prior related work here.

**Comment by julesies** [comment]
@geekscruff can you confirm fixed?
