### ISSUE TITLE
Rename 'Technical' in Admin Dashboard

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#1100]
The label for the flip-flop feature in the admin dashboard is called 'Technical', whilst the page itself is called 'Feature'. I suggest aligning the terminology and renaming the dashboard item 'Feature'.

**Comment by hannahfrost** [comment]
@ggeisler Are you cool with this proposal? I am.

**Comment by ggeisler** [comment]
I agree we need some renaming here but want to confirm we're talking about the same thing. From what I see the two labels that need alignment are "Technical" and "Settings" (not "Feature"):

![index_feature____hyrax](https://user-images.githubusercontent.com/101482/27052548-d7f1c5ba-4f6e-11e7-83a0-638c2e99c597.png)

Assuming A and B in the screenshot above are the things we're trying to align, "Features" (plural) seems like a good choice?

**Comment by mjgiarlo** [comment]
Yes, that's what we're talking about and :+1: to your suggestion!

**Comment by hannahfrost** [comment]
👍

**Comment by laritakr** [comment]
Closed via PR #1316
