### ISSUE TITLE
when deposit agreement feature is disabled, vestige of agreement requirement remains in Save Work panel

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1102]
The "Check Deposit Agreement" item in the list of Requirements on Save Work panel should be removed when checking the deposit agreement is not required by the user.

### Rationale

A feature flipper for disabling the the display of the deposit agreement to users creating works was recently introduced to Hyrax. It seems the implementation of the disabled state is incomplete in terms of the UI. The "Save Work" panel reflects a vestige of the original deposit agreement feature which looks odd and makes for a less-than-ideal UX. 

### Expected behavior

If acknowledging the deposit agreement is disabled and therefore a user creating work is not required to see it or know about it, then there should be no reference to the deposit agreement in the UI

### Actual behavior

If the deposit agreement is disabled, the Save Work panel appropriately does not require that the user acknowledge and agree to the agreement language.  However the "Requirements" checklist at the top of the panel still lists the "Check deposit agreement" with it automatically checked. This is misleading and inaccurate, because it is not a requirement in this context and it implies to the user that it has been done. 

![screenshot 2017-05-30 10 29 38](https://cloud.githubusercontent.com/assets/1801076/26596352/4feb4574-4523-11e7-81f0-49433ea77411.png)

**Comment by kdid** [comment]
I just wanted to make sure I understand this. 

The only time I see the Deposit Agreement already checked but still shown to the user is when "Show deposit agreement" is OFF but "Active deposit agreement acceptance" is ON. 

So the idea here is that "Show deposit agreement" setting takes precedence over the active acceptance setting? (A user can't accept it if they aren't shown the acceptance checkbox...)

**Comment by chrisdaaz** [comment]
@kdid that's correct.
