### ISSUE TITLE
Travis build randomly times out

### ISSUE THREAD

**Issue by atz** [samvera/hyrax#1103]
This is a separate issue from Travis randomly failing due to Capybara tests.  

Ever since two weeks ago when[ we expanded the build matrix](https://github.com/samvera-labs/hyrax/commit/26a127a26c71cf25262287d0541d8ad0e03ee413) to include a second rails version, the build time doubled (predictably) to over 90 minutes.  But also individual matrix pieces [now time out](https://travis-ci.org/samvera-labs/hyrax/jobs/236792491#L2515) and are killed by travis, failing builds in spontaneous and uninformative ways.  The limit is 50 minutes per job (no overall limit).

IF we are going to expand the matrix, we still need test execution to fit w/in the timeout.  Alternatively, we could maybe pay travis to let our jobs run for a long time.  But we can't have randomly failing tests AND randomly failing CI (doesn't even complete) AND have it take multiple hours.

**Comment by jcoyne** [comment]
@atz If the jobs are independent, why is adding a second job an important variable in the jobs taking too long?

**Comment by atz** [comment]
I dunno, it may have had to do with our renaming, or just Travis load generally.  The newer version of rails seems slightly slower, but mainly it just seems like there is an X% chance of a job of timing out, and now we have two chances instead of one.

**Comment by mjgiarlo** [comment]
It'd be super useful to reduce the time of the builds -- no idea why they slowed way down earlier this month. Needs further analysis.

**Comment by atz** [comment]
See also #1123

**Comment by mjgiarlo** [comment]
Chatted with @atz. This stopped happening a couple months ago, so we're closing this ticket for now. Re-open if it starts again.
