### ISSUE TITLE
Better error reporting/handling for when no workflow is chosen

### ISSUE THREAD

**Issue by straleyb** [samvera/hyrax#1111]
An issue occurred where a workflow wasn't chosen and it was throwing a rails error saying no workflow existed for permission template. This was very unhelpful since what was supposed to be done was going into the administrative sets/workflow tab and choose a workflow. 

It should re-route users to a page that specifies that no workflow has been chosen.

**Comment by mjgiarlo** [comment]
@straleyb Hmm, how would someone reproduce this?

**Comment by no-reply** [comment]
I'm also wondering how to reproduce.

Shouldn't permission templates fail to save without an `active_workflow`?

**Comment by no-reply** [comment]
Closing this as stale, please provide some description of how to reproduce to re-open.
