### ISSUE TITLE
UI Create _find_collection_widget partial

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#112]
<a href="https://github.com/elrayle"><img src="https://avatars.githubusercontent.com/u/6855473?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [elrayle](https://github.com/elrayle)**
_Friday Feb 12, 2016 at 17:52 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1572_

----

### Wireframes:
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes#mockup_p1-work-new-tab_relationships) - Relationship Tab - section This Work in Collections
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+Tab+-+Phase+1+-+UI+Wireframes) - Relationship Tab - section This Work in Collections
- [in context of Batch Upload](https://wiki.duraspace.org/display/hydra/Batch+New+Works+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationship Tab - sections These New Works in Collections
### Usage:

Used to find and select an existing collections.  Options for finding a collection:
- user begins typing the name of the collection and auto-complete suggests collections
- user chooses to search for collections and can browse a list of all collections with pagination
### Implementation:
- File: app/views/collections/_find_collection_widget.html.erb
- Create a partial for a view that includes the find_collection_widget.
  - need to be able to name the field associated with the widget
  - need to be able to return a value for the field based on the user's selection
- Add class/methods that support auto-complete
- Add class/methods that support browse and select

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Monday Feb 22, 2016 at 19:16 GMT_

----

@elrayle how is the user going to interact with searching for a collection? From the wireframes I can see how auto complete would work.  Is the searching something for another time/ticket?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mtribone"><img src="https://avatars.githubusercontent.com/u/4163828?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mtribone](https://github.com/mtribone)**
_Wednesday Mar 02, 2016 at 15:39 GMT_

----

@cam156 Good question. Searching needs to be addressed.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Mar 31, 2016 at 17:21 GMT_

----

@mjgiarlo I think this can be backlogged. We can use a simple dropdown for 7.0.0

**Comment by no-reply** [comment]
Closing this as stale. I believe it's superseded by the collections work in Hyrax 2.1.
