### ISSUE TITLE
Fix embargo i18 strings

### ISSUE THREAD

**Issue by darrenleeweber** [samvera/hyrax#1126]
### Descriptive summary

From https://github.com/samvera-labs/hyrax/pull/1042#pullrequestreview-41887636

Review strings in embargo views, e.g.:
- app/views/hyrax/embargoes

### Related work

Leases issue is #1325 
PR #1042

**Comment by mjgiarlo** [comment]
Thanks for writing this up, @darrenleeweber. Took the liberty of pre-assigning you. :)
