### ISSUE TITLE
Hyrax::WorkingDirectory puts object in memory as string

### ISSUE THREAD

**Issue by atz** [samvera/hyrax#1128]
`Hyrax::WorkingDirectory` in the line:
```ruby
copy_stream_to_working_directory(id, file.original_name, StringIO.new(file.content))
```
calling `file.content` (potentially) puts the entire file in memory at once.  See [ActiveFedora::File#content](https://github.com/samvera/active_fedora/blob/96e8a63de5a8c1881fd4b40dc3448c7f827c668d/lib/active_fedora/file.rb#L154-L156) and the various behaviors based on different `@content` classes (`local_or_remote_content` and `behaves_like_io?`).  

The point is that `WorkingDirectory` doesn't know whether it is getting in IO-like object, or an internal `@ds_content`, `ldp_source.get.body` or what.  @jcoyne identified this problem in commit 5db7d0c5699e707e9dee2ddfcd6574c8f058cbe1 with the line:
```
TODO: this causes a load into memory, which we'd like to avoid
```

**Comment by atz** [comment]
See: https://github.com/samvera/hydra-derivatives/issues/162

**Comment by no-reply** [comment]
Closing this. We won't do directed work on this unless we can identify a related performance issue.

We're re-instating Skylight on Nurax to help identify performance and memory use issues, but also welcome active feedback from adopters.
