### ISSUE TITLE
Add all characterization terms to SolrDocument

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1129]
### Descriptive summary

Ensure that all terms in `CharacterizationBehavior.characterization_terms` are defined in the SolrDocument. Presently `file_size` is missing, but there are probably others.

See https://github.com/samvera/curation_concerns/issues/1055

**Comment by no-reply** [comment]
closing this since `file_size` is currently indexed.

i'm not sure we want to index terms Hyrax doesn't read back from the index by default. applications should add terms they want to use.
