### ISSUE TITLE
Provide feedback to the user when adding files

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1137]
### Descriptive summary

When creating a work, after you hit "Save" you are directed to the show page but see under files, "This Generic Work has no files associated with it. Click "edit" to add more files."  It would be nice to tell the user that their files are being processed. There is such a statement at the top, but if the page is refreshed, the message goes away, and unless the files have finished being added, they will still the message at the bottom indicated that they don't have any files.

Furthermore, if they've uploaded many files, we should ideally be able to tell them how many are still in process, etc.

### Rationale

Nice user feedback.

### Related work

We implemented a simple solution at Penn State, but this could be expanded and reworked:

https://github.com/psu-stewardship/scholarsphere/commit/922ff2cd3

**Comment by ggeisler** [comment]
@awead Any chance you could take a screenshot of the page with the current Penn State solution? It sounds like you have a nice improvement but seeing the actual UI might save me from creating a different design solution when it isn't really necessary. 

I can generally understand what you're doing by looking at `app/views/curation_concerns/base/_items.html.erb` and related files, but if it isn't too much trouble for you seeing an example of the UI itself would be really helpful.

**Comment by awead** [comment]
@ggeisler see attached. It's pretty simple... ideally we could show a count, or if we wanted to get really display rows in the table representing files that have yet to be uploaded. That may be too much, however.
![screen1](https://user-images.githubusercontent.com/312085/26844814-a9c0c52a-4ac2-11e7-8e4b-db76864fa96e.png)
![screen2](https://user-images.githubusercontent.com/312085/26844815-a9c81a0a-4ac2-11e7-89b8-3d887a2dddf8.png)

**Comment by ggeisler** [comment]
That's great @awead. Thanks for taking the time to provide an example!

**Comment by mcdowney** [comment]
Fixed post Hyrax 2.1
