### ISSUE TITLE
Unable to complete upload with BrowseEverything

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1139]
### Descriptive summary

When creating a work using files uploaded via BrowseEverything, the file is added to the work, but characterization and derivative creation does not take place.

**Comment by atz** [comment]
How large of a file?

**Comment by awead** [comment]
@atz small file. It wasn't the file size, IIRC, it just that it wasn't working. We had to fix it at the controller. I think this is the relevant commit, but I can verify this later:

https://github.com/psu-stewardship/scholarsphere/commit/5529a5027
