### ISSUE TITLE
Create new works: count files

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#114]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Wednesday Mar 30, 2016 at 03:15 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1686_

----

The files tab should show a count of the files uploaded/attached to this work. This should work for create or update.
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Files+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Files+tab+-+Phase+1+-+UI+Wireframes) - Files Tab - contents of tab

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Wednesday Mar 30, 2016 at 21:48 GMT_

----

@mjgiarlo Move this to the backlog?

**Comment by no-reply** [comment]
These mockups appear to be lost.

@vantuyls: can we close?
