### ISSUE TITLE
Cannot batch upload files using BrowseEverything

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1140]
### Descriptive summary

When creating a batch of works, even just one, I am unable to create a work. After supplying the file and metadata, I click Save and am taken to My Works, but nothing ever appears. 

### Related work

https://github.com/psu-stewardship/scholarsphere/commit/5529a5027

**Comment by negon** [comment]
Hoping that this issue could be solved at some point :)

**Comment by mcdowney** [comment]
Can't replicate, closing.

**Comment by jrgriffiniii** [comment]
Thank you for testing this @mcdowney !
