### ISSUE TITLE
Display button for selected collection instead of "Add to Collection"

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1141]
### Descriptive summary

Given I am on the "X Collection" show page
When I click "Add works"
Then I should the button "Add to X Collection"
And I should not see "Add to Collection"

Currently, I have to go through the same process of choosing the collection when I've already come from the collection's page.

### Rationale

Makes for less clicks.

### Related work

https://github.com/psu-stewardship/scholarsphere/commit/387ec247f

**Comment by mcdowney** [comment]
Closing as I believed this has been superseded by the subsequent Collections Extension work
