### ISSUE TITLE
Add related works

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#116]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Wednesday Mar 30, 2016 at 22:00 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1711_

----

### Descriptive summary
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+tab+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab

Question: How are related works stored in the model?

Ref #1577

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Wednesday Mar 30, 2016 at 22:00 GMT_

----

@mjgiarlo can we backlog this?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Wednesday Mar 30, 2016 at 22:00 GMT_

----

@azaroth42 @escowles @no-reply Does PCDM have "related works"?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/azaroth42"><img src="https://avatars.githubusercontent.com/u/871868?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [azaroth42](https://github.com/azaroth42)**
_Wednesday Mar 30, 2016 at 22:02 GMT_

----

Yep. See:  http://pcdm.org/models#hasRelatedObject

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Mar 30, 2016 at 22:24 GMT_

----

Backlogging.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Wednesday Aug 31, 2016 at 12:24 GMT_

----

@mjgiarlo this ticket is linked from #2082, but I don't think it should be.

**Comment by jrochkind** [comment]
Sadly the UX mockups in the original decription now 404. :(

**Comment by no-reply** [comment]
@vantuyls the mockups for this are missing. Can we close, or do we need to push back to the design phase, perhaps as a 3.x series milestone?

**Comment by vantuyls** [comment]
@ggeisler or @hannahfrost do you happen to have these original mockups for review?

**Comment by hannahfrost** [comment]
@vantuyls @ggeisler I quickly found this: https://docs.google.com/document/d/1rOXbsccfkgg2wTRrA5dHOxge3ORMIma1WM6JkU5A15k/edit?usp=sharing

Relevant?

**Comment by hannahfrost** [comment]
There is also this: https://docs.google.com/document/d/1D_pwi06lGsAivueRmbx1n6qu-M32woI2njUVRiz86ok/edit

(Sorry, I haven't looked closely, in a meeting, but wanted to share what I could find right away @vantuyls . Looks like the mock-ups on the wiki didn't get migrated from the hydra space to the samvera space.

**Comment by ggeisler** [comment]
Thanks for tracking down those Google docs @hannahfrost. I would assume, though, that everything in those docs was eventually ticketed and completed (could be an incorrect assumption) so the current application might be a more accurate reference than any 2 year+ mockups. I don't have any mockups stored locally that seem more up-to-date and relevant than those.

Also, I think this ticket dates back to Sufia and may no longer be relevant? It's not entirely clear to me what the concern of the ticket is, and if UX designs are even relevant. If (based on the reference to #1577 in the original comment) the question is about how to relate a work to a collection, I think the work of the Collections Extensions team last fall might have covered whatever the concern of this ticket was. I'm pretty sure we covered how to assign a work to one or more collections in that effort. If not, and that is what the concern here is, I can probably dig up a mockup for that.
