### ISSUE TITLE
Select resources to export using Fedora's export tool

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1168]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Sep 22, 2016 at 18:49 GMT_
_Originally opened as https://github.com/samvera/curation_concerns/issues/1009_

----

_From @awead on September 21, 2016 14:23_

As a repository administrator
I need to select available resources to export
So that I can submit them to different preservation services

Acceptance: I can search for works and collections, select them, and submit them for export.

_Copied from original issue: projecthydra/sufia#2722_

**Comment by rjkati** [comment]
Closing since this functionality is addressed by bulkrax or another import/export tool
