### ISSUE TITLE
Add a last saved status in the sidebar on work edit page.

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#117]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Thursday Mar 31, 2016 at 04:35 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1716_

----

https://wiki.duraspace.org/display/hydra/New+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes#NewWork-MetadataTab-Phase1-UIWireframes-VariantsofSaveWorkwidget

Ref #1562

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Mar 31, 2016 at 04:35 GMT_

----

@mjgiarlo backlog?

**Comment by no-reply** [comment]
More missing mockups.

@vantuyls I'm closing this one. If this is still a desired feature, we can reopen for re-design.
