### ISSUE TITLE
View list of modified resources that were previously exported

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1170]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Sep 22, 2016 at 18:49 GMT_
_Originally opened as https://github.com/samvera/curation_concerns/issues/1011_

----

_From @awead on September 21, 2016 14:31_

As a repository administrator
I need to see a list of exported resources that have been updated after their export
So that I may determine if further actions are necessary

Acceptance: I can see a list of all resources that were modified or otherwise changed after the date on which they were exported.

_Copied from original issue: projecthydra/sufia#2724_

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Sep 22, 2016 at 18:49 GMT_

----

_From @kestlund on September 21, 2016 15:8_

Acceptance criteria needs to also show what profile was used on previous export(s).

**Comment by rjkati** [comment]
Closing since this functionality is addressed by bulkrax or another import/export tool
