### ISSUE TITLE
Exporting bags to preservation services

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1172]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Sep 22, 2016 at 18:50 GMT_
_Originally opened as https://github.com/samvera/curation_concerns/issues/1013_

----

_From @awead on September 21, 2016 14:53_

As a repository administrator
I need to select resources to export as bags with specific profiles
So that I can submit the bags to preservation services

Acceptance: When exporting resources, I can export them as bags with certain profiles that match preservation services such as APTrust.

_Copied from original issue: projecthydra/sufia#2726_

**Comment by rjkati** [comment]
Closing since this functionality is addressed by bulkrax or another import/export tool
