### ISSUE TITLE
Notification of Error on Bag Export/Import

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1173]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Sep 22, 2016 at 18:50 GMT_
_Originally opened as https://github.com/samvera/curation_concerns/issues/1014_

----

_From @kestlund on September 21, 2016 17:29_

As a repository administrator, I want to have notification that a Bag Export or Import has failed and why.

Acceptance criteria:  When logged in on the activity dashboard, I can view the status of bag and if it failed or succeeded. If it failed, I will know if it is due to the selected profile or another system reason.

_Copied from original issue: projecthydra/sufia#2730_

**Comment by no-reply** [comment]
Depends on #1172

**Comment by rjkati** [comment]
Closing since this functionality is addressed by bulkrax or another import/export tool
