### ISSUE TITLE
Create documentation for implementing workflow

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1174]
<a href="https://github.com/jeremyf"><img src="https://avatars1.githubusercontent.com/u/2130?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeremyf](https://github.com/jeremyf)**
_Friday Sep 23, 2016 at 15:20 GMT_
_Originally opened as https://github.com/samvera/curation_concerns/issues/1033_

----

- [x] From a given state machine diagram, what is the resulting configuration
  - Example one https://github.com/projecthydra/curation_concerns/wiki/Defining-a-Workflow
- [ ] Document where to go for workflow configuration
  - [x] Where is the generator that installs the configuration for a workflow
  - [ ] How to write an email notification template
  - [ ] What are the callbacks that were installed and how to make adjustments

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jeremyf"><img src="https://avatars1.githubusercontent.com/u/2130?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeremyf](https://github.com/jeremyf)**
_Friday Sep 30, 2016 at 18:10 GMT_

----

I've been working on this example https://github.com/projecthydra/curation_concerns/wiki/Defining-a-Workflow

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Dec 16, 2016 at 23:20 GMT_

----

@jeremyf might you be inclined to self-assign this issue and take on the unchecked tasks above in the new year?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Jan 10, 2017 at 17:31 GMT_

----

@jeremyf ping re: :arrow_up:!

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jeremyf"><img src="https://avatars1.githubusercontent.com/u/2130?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeremyf](https://github.com/jeremyf)**
_Tuesday Jan 10, 2017 at 17:33 GMT_

----

I'm AFK, but please assign me to this task.

Jeremy Friesen

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Jan 10, 2017 at 18:05 GMT_

----

Done, and I'll make sure to port these docs over to Hyrax when appropriate. Thanks, @jeremyf!

**Comment by elrayle** [comment]
I would recommend putting this documentation in https://github.com/samvera/samvera.github.io, the go to place for community documentation.

**Comment by jcoyne** [comment]
@elrayle I don't know.  That website seems to refer to something called "Project Hydra" I'm looking for "Samvera" documentation (https://github.com/samvera/samvera.github.io/pull/89) :trollface:

**Comment by jlhardes** [comment]
Defining a Workflow documentation is on the samvera GitHub wiki: https://github.com/samvera/hyrax/wiki/Defining-a-Workflow so this issue might be done?

**Comment by rjkati** [comment]
Closing this ticket since the work described seems to be completed.
