### ISSUE TITLE
Add logs/status for batch and item level operations

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#118]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Wednesday Apr 06, 2016 at 21:16 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1779_

----

For BatchCreate there should be a log that shows the overall status ('processing', 'failed',  'success'). There should also be logs for each item (create work operations in this case). 

Perhaps something like this: https://github.com/curationexperts/tufts_models/blob/master/app/models/batch.rb (but do not serialize fields as it introduces race conditions).

**Comment by mjgiarlo** [comment]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [awead](https://github.com/awead)**
_Tuesday Nov 01, 2016 at 13:37 GMT_

----

Possibly related to https://github.com/psu-stewardship/scholarsphere/issues/373 where we need to know when a single work is finished processing.

**Comment by jlhardes** [comment]
This is an older enhancement issue with commits that seem to be outside of this repository. Closing issue since this does not appear to be something the community is needing addressed.
