### ISSUE TITLE
Display events for works

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1193]
### Descriptive summary

Hyrax has events for works, but we don't display them.

### Rationale

Maybe we should?

### Related work

We did this in our Scholarsphere application: https://github.com/psu-stewardship/scholarsphere/commit/99cc72165

**Comment by mjgiarlo** [comment]
@awead Could you include a screenshot of what this looks like so that the Hyrax UI/UX folks (cc: @ggeisler @samvera/hyrax-ui-ux-advisors) can see it? I suspect we may want to review the design of this feature before re-integrating it, and your screenshot can help them get a sense of what sort of information is being added to the work show page and where. Thanks!

**Comment by awead** [comment]
@mjgiarlo see attached:
![activity](https://user-images.githubusercontent.com/312085/27044673-6688a4e0-4f6c-11e7-87a9-dbde280b0fca.png)
It would be a problematic if there were 10+ files in the work, because the activity would be out of view, but otherwise, it's a simple solution.

**Comment by newmanld** [comment]
Question - are events intended to be public or only shown to owner/editors of works?  Are we including any activity on the work, such as assigning an editor, attaching a file, modifying a work?  I have no opinions yet - just asking for clarification as to scope.

**Comment by awead** [comment]
It would be the same as what we're doing with file sets. Which, I believe is that if the user has read access, then they can see all the activity.

**Comment by mjgiarlo** [comment]
:+1: They are not just for owners/editors. Modifying a work and attaching a file are included among the events. Adding an editor is not. Good questions, @newmanld

**Comment by newmanld** [comment]
From one of our Product Owners - what is the benefit of publicly showing the events?

**Comment by hackmastera** [comment]
+1 to having these for some subset of users. in our case, logged in (staff) users.

**Comment by mcdowney** [comment]
Closing as no longer relevant
