### ISSUE TITLE
Change button to "Save" in file set edit form

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1199]
### Descriptive summary

The language of the file set edit screen is misleading. "Update Attached File" doesn't seem to apply. Use "Save" instead.

### Rationale

Consistency, really. Also the term "attached file" doesn't seem correct.

![fileset](https://user-images.githubusercontent.com/312085/27044878-1b8ba2ac-4f6d-11e7-9a5e-b406a4aec2ee.png)

**Comment by mjgiarlo** [comment]
May I ask the @samvera/hyrax-ui-ux-advisors to chime in on this?

That is super old code (and needs i18n to :boot:): https://github.com/samvera/hyrax/blame/master/app/views/hyrax/file_sets/_form.html.erb

**Comment by newmanld** [comment]
+1 to change button to 'Save'
