### ISSUE TITLE
Work show page -- display headers as collapsible sections

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#120]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Apr 14, 2016 at 21:36 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1863_

----

### Descriptive summary
- [ ] Display relationships, metadata, items, sharing with, and user activity as collapsible sections rather than header tags
- [ ] Relationships and metadata sections MAY extend all the way to the right margin of the page if no thumbnail or no/short description

Pertains to Sufia master.
### Current UI

![](https://cloud.githubusercontent.com/assets/92044/14536835/fd5654ca-0239-11e6-819c-a528278a59d2.png)
### Expected UI

https://wiki.duraspace.org/x/DAF6B
### Related work

Refs #1722, #1843

**Comment by no-reply** [comment]
Missing wireframes.

@vantuyls I'm thinking this can be dropped unless we want to take on a thoughtful redesign of the show view.
