### ISSUE TITLE
Improvements to collection workflow

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1200]
### Descriptive summary

It is not always clear how create new collections, or edit existing ones, and add new works or existing ones. At Penn State, we made a couple of improvements to the collections UI that accomplished a few things:

#### Creating new collections

The user can now choose between:

1. Creating a new, empty collection
1. Creating a new collection and adding existing works
1. Creating a new collection and adding new works

![new_collection](https://user-images.githubusercontent.com/312085/27046263-c6de4584-4f71-11e7-84d6-eca8e1974d9d.png)

Additionally, if the user is creating a new collection from having previously selecting a number of works, the works will now appear in the collection list as a reminder of which works will be added to the new collection.

![new_collection_with_ittms](https://user-images.githubusercontent.com/312085/27046320-fd17cbe8-4f71-11e7-9ed7-d8429c14d80c.png)

See https://github.com/psu-stewardship/scholarsphere/commit/6550c36b4

#### Editing existing collection

For existing collections, users can add new works or add existing ones:

![edit_collection](https://user-images.githubusercontent.com/312085/27046361-1a431038-4f72-11e7-8710-9ddf207bf53f.png)

See https://github.com/psu-stewardship/scholarsphere/commit/ff0be0556

Furthermore, if the user is adding new works to an existing collection, they can choose between single and batch upload without loosing the reference to the collection in the url.

See https://github.com/psu-stewardship/scholarsphere/commit/773960cd1

### Rationale

This helped the user through the process of creating collections and adding works.

**Comment by awead** [comment]
Also see related to ticket to collection work: https://github.com/samvera/hyrax/issues/1141

**Comment by mjgiarlo** [comment]
I'd like to hear from the @samvera/hyrax-ui-ux-advisors on this one too. Thanks, @awead.

**Comment by newmanld** [comment]
I think this is good change.  At Cincinnati we are doing a Beta preview of our app on Sufia 7.3 (while rapidly working to retool it for Hyrax), and we have received feedback from one Beta tester, where, after creating a new collection, they clicked the 'Add Works' button and expected/assumed that it would take them to the an add new works dialogue, not add existing works.  They expressed confusion as to what they were supposed to do on the Dashboard.  Our interim solution is to relabel the button 'Add existing works', but this is a more comprehensive solution.  I think (?) what we see today with Sufia 7.3 is the same in Hyrax, so I think this feedback applies.

If the user chooses 'Add new works', then the membership within the collection (on the Relationships tab) will be pre-selected for them?

I expect more UI changes with collections coming from the work with Display Sets - @elrayle - but think this is a change worth making now.

**Comment by ggeisler** [comment]
These look like good updates to me. For the case "the user is creating a new collection from having previously selecting a number of works" I wonder if presenting a checkbox (checked by default) next to each of the previously selected works in the collection list would be a good idea? That way the collection list serves not only as a reminder of which works will be added to the new collection but also an opportunity for the user to remove one or more works. This is unlikely to happen very often, but when it does, it prevents the user from having to navigate back to the previous context to remove the unwanted works and start the process over.

If and when there is a consensus that the ScholarSphere updates above are ones we want to adopt for collections in Hyrax, I'd be happy to work them into the Display Sets WG mockups as appropriate.

**Comment by mjgiarlo** [comment]
@ggeisler @elrayle do y'all know the extent to which the Collection Extensions work will include bits related to :point_up:?

**Comment by elrayle** [comment]
We do have the edit case covered.  See the mockup in #1427.  Just above the list of items is Deposit new works through this collection and Add existing works to the collection.

**Comment by ggeisler** [comment]
@mjgiarlo I do think @awead provided some useful examples, which I (unintentionally) might not have fully considered in doing the recent collections mockups, so perhaps the best approach is to revisit the tickets Adam pointed us to after the current collections extensions sprints are completed and see if there are any additional improvements we can borrow.

**Comment by mcdowney** [comment]
Closing, as I think this has been superseded by the subsequent Collections Extension work
