### ISSUE TITLE
Work show page -- item display (epic)

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#121]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Apr 14, 2016 at 21:37 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1864_

----

### Descriptive summary
- [ ] Implement "show/hide item metadata" links for files (showing technical/characterization metadata)
- [ ] Show sort/view type (gallery, etc.)/pagination controls/search-within-work above items

Pertains to Sufia master.
### Current UI

![](https://cloud.githubusercontent.com/assets/92044/14536835/fd5654ca-0239-11e6-819c-a528278a59d2.png)
### Expected UI

https://wiki.duraspace.org/x/DAF6B
### Related work

Refs #1722, #1843

**Comment by no-reply** [comment]
Missing wireframes.

cc: @vantuyls

**Comment by mcdowney** [comment]
No longer relevant
