### ISSUE TITLE
Remove duplicate code from GenericWorkHelper.render_collection_links

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#123]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Tuesday Apr 19, 2016 at 16:17 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1895_

----

It's calling `Sufia::CollectionMemberService` which duplicates functionality of `CurationConcerns::WorkShowPresenter.collection_presenters`

**Comment by no-reply** [comment]
This predates the CE work. Any refactor here should be reconsidered in light of that work.
