### ISSUE TITLE
Don't attempt to display ungenerated derivatives

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#1233]
A works show page having a video file_set rendered is failing with 404 when the source of the video tag is sent to the server. 

https://github.com/samvera/hyrax/blob/master/app/views/hyrax/file_sets/media_display/_video.html.erb

When removing the `file: 'mp4'` and `file: 'webm'` parameter in each of the path generators, the video is rendered and is capable of playing. 

If I'm reading this correctly, the DownloadsController seems to expect the file_set name in the `file` param: https://github.com/samvera/hyrax/blob/master/app/controllers/hyrax/downloads_controller.rb#L63

**Comment by jcoyne** [comment]
@revgum do you have ffmpeg enabled in the hyrax configuration?

**Comment by revgum** [comment]
@jcoyne no we don't

**Comment by jcoyne** [comment]
@revgum so the UI is trying to server the derivatives enabled by that flag.  The fix is probably to wrap the UI partial with a test for that configuration value.

**Comment by no-reply** [comment]
Wrapping the UI with a flag test seems slightly fragile in production, since the flag could change values and still not have derivatives generated.

Perhaps there's a solution that involves displaying the derivative video when it is present, and gracefully failing otherwise?

**Comment by jcoyne** [comment]
@no-reply Can we make the guarantee that the derivative video is on the same system?  In our system (not hyrax) we have wowza make video derivatives.  While this isn't the default configuration, it does seem like it wouldn't be uncommon. Hyrax's video handling is extremely basic an I suspect it doesn't support a large number of use cases.

**Comment by jlhardes** [comment]
Closing this issue as it does not seem to be a problem any longer for the original reporting institution and no one else has reported experiencing this issue.
