### ISSUE TITLE
video element style is overflowing

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#1234]
A works show page, with a video element rendered in the upper left, needs a style rule to prevent it from overflowing to the rest of the page. 

Since this video element is wrapped in a boostrap column, a simple fix to set max-width would work: `video { max-width: 100%; }` 

Consider these two screenshots as examples:

With max-width set:
![screen shot 2017-06-19 at 10 36 13 am](https://user-images.githubusercontent.com/32885/27297868-6fad5d6c-54db-11e7-85ec-2602d9dbecbd.png)

Without max-width set:
![screen shot 2017-06-19 at 10 36 02 am](https://user-images.githubusercontent.com/32885/27297867-6fab84e2-54db-11e7-855a-db124a6f562c.png)

**Comment by mjgiarlo** [comment]
Thoughts, @samvera/hyrax-ui-ux-advisors ?

**Comment by mtribone** [comment]
We've had that issue come up before. @revgum's solution is go.

**Comment by VivianChu** [comment]
@revgum - I checked out latest hyrax and it seemed like this issue has been fixed. The video element looked fine to me. Could you try again? Thanks

**Comment by mcdowney** [comment]
Closing as fixed
