### ISSUE TITLE
ImportUrlJob should check http status and handle non-200 codes differently

### ISSUE THREAD

**Issue by cam156** [samvera/hyrax#1235]
### Descriptive summary

In Hyrax master the import_url job does not check the status of the url from the remote server.  This could cause an error page to be copied as the content into hyrax.

### Rationale

This causes the system to believe that the content was captured successfully, when really no content was preserved.  

### Expected behavior

When a url times out we should notify the user that the download failed, not just copy the error page as content.

### Actual behavior

The html error page is copied to the content of the work and preserved instead of the content.

### Steps to reproduce the behavior

1. In general if you try to gather many large files from Box, or Dropbox the last few URLS will tend to timeout.

### Related work

We addressed this issue in ScholarSphere here: https://github.com/psu-stewardship/scholarsphere/commit/22fe08c1957dda228bf4d6a5e239f6a48bee25f1s

**Comment by scherztc** [comment]
See what we did locally to solve this : https://github.com/uclibs/scholar_uc/pull/1668
