### ISSUE TITLE
Creating immediate feedback after work creation

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1236]
### Descriptive summary

We found a few seconds lag time after "Save" was clicked before the page changed. To provide more feedback to the user, we created an "in progress" visual that showed the user the form had been submitted and also gave immediate feedback to visually impaired users via screen reader.

Here's a video demo with the screen reader audio in the background:

https://www.dropbox.com/s/u2858kwnplbv9a0/demo.mov?dl=0

### Rationale

Better user experience; also removes cancel button which was still active.

### Related work

https://github.com/psu-stewardship/scholarsphere/commit/d93555e6e

**Comment by mjgiarlo** [comment]
What do folks think about this change? @samvera/hyrax-code-reviewers @samvera/hyrax-ui-ux-advisors

**Comment by cpd3149** [comment]
this seems like a good enhancement for screen readers.

**Comment by ggeisler** [comment]
👍  I like it, even aside from the screenreader benefit.

**Comment by newmanld** [comment]
+1
