### ISSUE TITLE
Uploading many small files fails

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1238]
### Descriptive summary

At Penn State, we saw this issue only when code was deployed to one of our QA or staging environments. I have also seen the same problem with the Art Institute of Chicago's deployment of Sufia 7.2 as well. The issue appears to only show up when running in production and does not happen in development mode.

See the full details, with screen shots, here: https://github.com/psu-stewardship/scholarsphere/issues/453

In short, when uploading many files, small or otherwise the first few will fail while the rest succeed. As I've noted in the attached issue, it appears to be a client issue. Files make it to the server and are uploaded as UploadedFile objects, however the response from the server isn't processed correctly by the client. This is using some jbuilder code, and the uploaded file is not inserted into the DOM for inclusion in the request to create the work.

While I have not been able to test this with Hyrax in a deployed environment, I'm pretty sure the bug will still affect Hyrax because it deals with the jQuery file upload plugin which doesn't appear to have changed from Sufia 7.2 to Hyrax.

### Related work

I was unable to discover or fix the underlying issue, so my "fix" was to disable auto-uploading. While not ideal, it did prevent the problem from occurring:

https://github.com/psu-stewardship/scholarsphere/commit/99d38039f

But created an additional step in the upload process. Here's a video that demos the upload process:

https://www.dropbox.com/s/sevs84srwzijrpk/uploading.m4v?dl=0

**Comment by atz** [comment]
I doubt we're going to disable auto-uploading.  Is it correct that the observable symptom might be like:
1. Drag-drop 100 files onto uploader
2. Only 95 rows appear.

Or do the rows appear partial/broken somehow?

**Comment by awead** [comment]
@atz yes, that's correct. The missing files appear as blank rows. There are some screenshots in the linked issue from our Scholarsphere repo above. You have to scroll down a bit to see them. I agree, disabling auto-uploading really isn't a viable solution, but it was the only one we had available at the time.

As I said above, I was able to trace the issue down to the json response that's coming from the Hyrax/Sufia controller. It something between that response on the jbuilder template that renders the HTML that's inserted in the DOM of the form, but I couldn't for the life of me figure out what. I had limited debugging abilities, but I'm happy to replicate this error again to see if anyone has better ideas.

**Comment by mutanthumb** [comment]
Hi All-
This is a huge problem for us here at U Mich as well.
Thanks,
susan

**Comment by gordonleacock** [comment]
@awead and @atz - Is turning off auto-uploading still the only know solution for this issue?

**Comment by mjgiarlo** [comment]
I suspect that turning off auto-uploading is the only known workaround because no one has sufficiently analyzed what's at fault, @gordonleacock

**Comment by no-reply** [comment]
DCE ran into this on a recent projectt and was able to isolate the issue to a UI-side fade-in timing issue, and fix by adding some explict fade-in code in: https://github.com/curationexperts/epigaea/commit/2e1eaf7681346fd3864472b05f1af2be5a1509c3
https://github.com/curationexperts/epigaea/commit/130d517792003924e273e5fba598efe616668fb1

**Comment by no-reply** [comment]
Ping @awead @gordonleacock @mutanthumb re: https://github.com/samvera/hyrax/issues/1238#issuecomment-422114110

If someone has time to test a patch along these lines locally, we could consider how to structure a hyrax-side patch.

**Comment by blancoj** [comment]
I tested the patch and it seems to work fine. I did have to make sure I had this file:

https://github.com/curationexperts/epigaea/blob/master/app/views/hyrax/uploads/_js_templates.html.erb

**Comment by fritzfreiheit** [comment]
I've been working on tracking down a similar issue and would like to share the description and my proposed solution here.

Multiple file upload loses files issues

Description: In Hyrax, when more than one file is selected when editing a work, uploaded, then saved, a portion of the uploaded files never show up as attached to the work.

A not-so-brief overview of the current file upload process: continued in the following google doc...

https://docs.google.com/document/d/1IlVikDg887aDCl4P2A8_XUaAglPvvd7hpwRyk3J5IDI/edit?usp=sharing

**Comment by rjkati** [comment]
Unable to replicate in Hyrax 3.0.0 rc3 using Chrome 87.0.4280.141 or Firefox 85.0. @jlhardes

**Comment by fritzfreiheit** [comment]
Susan,
Yeah, I saw this. I was planning on dropping nurax and seeing if I could
replicate it.
Fritz.

**Comment by jlhardes** [comment]
@fritzfreiheit the testing by @rjkati was on nurax-dev so we can't replicate it there. Do we still have an issue to fix with this?

**Comment by mutanthumb** [comment]
Hi, fortunately, we haven't seen this in a while. @fritzfreiheit @jlhardes @rjkati

**Comment by jlhardes** [comment]
Thanks @mutanthumb! Closing this issue.
