### ISSUE TITLE
Finding works shared with me

### ISSUE THREAD

**Issue by awead** [samvera/hyrax#1240]
### Descriptive summary

In Sufia, there was a _Shared with Me_ tab in the dashboard that listed works or objects that the user had edit access to, but weren't owned by them. In Hyrax, that seems to have been removed. If an item is shared with me, I can edit it in Hyrax, but I can't find it easily unless I know what it is beforehand and locate via a regular search.

Is there a plan to restore that functionality to Hyrax or is something else intended?

**Comment by ggeisler** [comment]
@awead Something else is intended. The mockup below is from https://github.com/samvera-labs/hyku/issues/447 (though at this point I assume we would implement in Hyrax, not just Hyku) and shows that a user will see all works she has edit access to in the Your Works tab, with a column that indicates whether each work was one that was shared with her or one she deposited herself: 

![43ffcb26-f8ee-11e6-930f-6641832cda2f](https://user-images.githubusercontent.com/101482/27343006-86956a5e-5596-11e7-9d40-a3116321bd24.png)

This ticket has been around a while but is currently open.

**Comment by awead** [comment]
@ggeisler ah, that makes sense. Thanks for the clarification!

**Comment by elrayle** [comment]
To address this issue, [app/search_builders/hyrax/my/works_search_builder.rb](https://github.com/samvera/hyrax/blob/master/app/search_builders/hyrax/my/works_search_builder.rb) should be updated to return...
* the current user created the collection
* another user shared edit access with the current user or a group to which the current user belongs 
* another user shared read access with the current user or a group to which the current user belongs 

It should not include collections where the read access is granted to the current user ONLY through PUBLIC visibility.
