### ISSUE TITLE
Collections don't have a thumbnail

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#1256]
There is no place in the edit a collection page to pick a thumbnail.  
All the collections display the default thumbnail:

<img width="571" alt="screen shot 2017-06-21 at 1 41 59 pm" src="https://user-images.githubusercontent.com/92044/27400967-7b1e6bb6-5687-11e7-8d0f-25a1676b7d6f.png">

**Comment by cpd3149** [comment]
picking a thumbnail would be good. 

i was also thinking it might be nice to upload a collection logo that's not tied to any specific work in the collection. for example, a lab might want a collection for their technical reports, and they might want to personalize the collection with a logo rather than the default thumbnail.

**Comment by ggeisler** [comment]
FWIW, both the thumbnail and logo ideas are part of the collection-related design work underway in the [Display Sets WG](https://wiki.duraspace.org/pages/viewpage.action?pageId=81959951).

Preliminary mockups that illustrate thumbnail and logo ideas:

![hyrax-mockups_graffle__admin__collection_new_edit](https://user-images.githubusercontent.com/101482/27403021-b9377730-567d-11e7-887f-e9b54c6fff2a.png)
----
![public collection show](https://user-images.githubusercontent.com/101482/27403031-c5eecd34-567d-11e7-9aca-faa2a4c1e20f.png)

**Comment by ggeisler** [comment]
Although I'm not sure the mockups above exactly satisfy the example @cpd3149 offers, in that the thumbnail would come from one of the collection item thumbnails, and the logo is presented as part of the branding, not in place of the collection thumbnail. So, if that is something the community is going to want to do, we'd have to make the thumbnail selection more elaborate, to enable uploading an image or selecting an item thumbnail.

**Comment by cpd3149** [comment]
these mockups look really good @ggeisler ! what i meant by selecting an isolated collection thumbnail is to offer groups the ability to brand their collections. the butterfly research mockup seems to take care of that by offering way more flexibility.

**Comment by jcoyne** [comment]
@ggeisler where do we put the "manage collection" stuff that's currently on the edit collection page?

I got a start on implementing your mockup, but I don't know what to do with that panel on the bottom.  Should we ditch it?

<img width="961" alt="screen shot 2017-06-21 at 8 55 58 pm" src="https://user-images.githubusercontent.com/92044/27414078-a96d5d46-56c4-11e7-8d76-4614d91a5325.png">

**Comment by ggeisler** [comment]
@jcoyne Well, nothing is final because, as I said above, these are only preliminary mockups intended for the Display Set WG to discuss, but yes, I believe our direction is to remove the Manage Items section from the New/Edit collection page.

**Comment by jcoyne** [comment]
@ggeisler in that case, should i move the batch controls (checkboxes) to the collection show page?

**Comment by ggeisler** [comment]
@jcoyne Yeah, probably so. I'm still finalizing that mockup and have had no feedback on that approach but that's what I have now.
