### ISSUE TITLE
Contrast Ratio for Buttons, Labels, and Links

### ISSUE THREAD

**Issue by mtribone** [samvera/hyrax#1257]
### Descriptive summary

In Hyrax 2.0.0 alpha the default Bootstrap colors for buttons, labels and links do not have sufficient color contrast for users with differing color vision. 

### Rationale

Makes the interface hard to read, see, understand, use, etc. for users with differing color vision. 

### Expected behavior

I would expect all users to be able to use the interface and not be blocked by barriers such as sufficient color contrast on interface elements.

### Actual behavior

Default Bootstrap elements and colors aren't sufficient in some contexts per the WAVE accessibility toolbar.

### Steps to reproduce the behavior

1. Easiest way is to add the WAVE accessibility toolbar to your browser
1. Click the toolbar icon
1. Click the contrast button

### Related work

https://github.com/psu-stewardship/scholarsphere/pull/539
https://github.com/psu-stewardship/scholarsphere/pull/552

**Comment by jcoyne** [comment]
In Hyrax 2.0 you can customize the colors of the buttons and links and background in the user interface. So how do we handle this?  Should we just provide better defaults or should we encourage users to install WAVE themselves when they customize the UI?

**Comment by ggeisler** [comment]
I think we should provide AA-passing defaults, even if we expect most implementors to override the colors with their own, institution-specific colors. Perhaps we could just use the PSU colors that @mtribone previously pointed to as updated defaults?

**Comment by mtribone** [comment]
@jcoyne @ggeisler Yeah I would provide AA-passing defaults and encourage adopters who customize the UI to check the contrast either with WAVE or some other tool.

**Comment by mjgiarlo** [comment]
Worth adding an entry to the Hyrax Management Guide about this?

**Comment by h-parekh** [comment]
Confirmed with @mtribone that this issue has been fixed in Hyrax 2.1.
