### ISSUE TITLE
Refactor Tables Inside of List Items in Search Results

### ISSUE THREAD

**Issue by mtribone** [samvera/hyrax#1268]
### Descriptive summary

In Hyrax 2.0.0 alpha, we use tables inside of `<li>` for the search results. Consider refactoring the results to use `<dd><dl>` for the metadata for each result OR improve the tables with captions and headings and row attributes.

### Rationale

[Tables without additional work](http://accessibility.psu.edu/tables/) are hard for screen reader users. Tables inside of an ordered list are even harder. 

### Expected behavior

Ease-of-use for users of assistive technology to navigate, tab, and understand results of search. 

### Actual behavior

Tables within ordered lists make it complex for screen reader users.

### Steps to reproduce the behavior

1. tab through the results using VoiceOver
1. try it in a screen reader with a user.

**Comment by jcoyne** [comment]
@mtribone the link you point to says that the tables are fine so long as the headers are marked as such (Hyrax uses `th` for the headers).  I wonder if this is a bug in a particular screen reader or is common to all screen readers?

**Comment by jcoyne** [comment]
@mtribone I see we aren't adding `scope="row"` would doing that fix this issue?

**Comment by mtribone** [comment]
@jcoyne Yeah we can add things like `scope="row"` to help. And then do another round of testing. Heavily nested HTML was a problem for our tester.

**Comment by metageeky** [comment]
From a screen reader perspective, tables are preferable over lists for search results assuming that each column is a piece of metadata. For example, if one column is title, another column is creator, etc., the screen reader user can skim over just a column instead of having to read the entire entry each time.

**Comment by mtribone** [comment]
@metageeky Ah! Great point. Our user must have an aversion to tables.

**Comment by h-parekh** [comment]
Verified with @mtribone that this issue is fixed on Hyrax Version: 2.1.0.rc2. 

Tested on:
© 2018 Samvera-Hyrax 
Nurax Version
ENV: production 
SHA: f18507eb81b5b0ba5647b36658eff80d25ff5626 
Branch: master
