### ISSUE TITLE
Hard to un-select a collection when submitting item

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#127]
<a href="https://github.com/jhallida"><img src="https://avatars.githubusercontent.com/u/5582497?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jhallida](https://github.com/jhallida)**
_Thursday May 05, 2016 at 14:29 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1984_

----

It’s hard to know how to NOT put an item in a collection when submitting it. There is no ‘no collection’ choice. You can actually use CTRL-click to unselect but that's not intuitive to most users.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/atz"><img src="https://avatars.githubusercontent.com/u/109954?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [atz](https://github.com/atz)**
_Thursday May 19, 2016 at 21:21 GMT_

----

Intuitive or not, that is the browser-default behavior for mutli-selects.  That makes it not a bug.  Adding a button to clear selections, for example, would be an enhancement/feature, not a bugfix.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mtribone"><img src="https://avatars.githubusercontent.com/u/4163828?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mtribone](https://github.com/mtribone)**
_Monday Jun 27, 2016 at 13:15 GMT_

----

Is this issue in regards to the relationships tab of a work? Do we want to add a "clear" button?

![screen shot 2016-06-27 at 9 13 22 am](https://cloud.githubusercontent.com/assets/4163828/16380902/aff25a92-3c47-11e6-9ac6-591e1f75af39.png)

**Comment by no-reply** [comment]
This issue is stale. The behavior of the `Relationships` tab is significantly different than described here.
