### ISSUE TITLE
Document how to handle/update/sync i18n strings

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1276]
Hyrax now supports 7 languages, so expecting developers to manually translate all i18n strings in their pull requests is inefficient. We should continue using `i18n-tasks` for this, which is not dependency of Hyrax (and shouldn't be, because Hyrax-the-gem does not need it even though we maintainers do). @mjgiarlo will document how to use `i18n-tasks` including:

* Setting up the Google Translate API key
* Installing `i18n-tasks`
* Configuring via `config/i18n-tasks.conf`
* Running `i18n-tasks` and dealing with its output

**Comment by darrenleeweber** [comment]
- https://github.com/glebm/i18n-tasks
- `i18n-tasks translate-missing --from en es zh fr it de pt-BR`

**Comment by darrenleeweber** [comment]
`gem install i18n-tasks` # only for hyrax, it's in hyku

open `config/i18n-tasks.yml`  # maybe tmp comment out files to be ignored
`i18n-tasks translate-missing --from base es zh it fr de pt-BR`

**Comment by mjgiarlo** [comment]
@darrenleeweber I've written up an issue documenting the issue with yaml.erb files, and asked the maintainer for advice: https://github.com/glebm/i18n-tasks/issues/253

**Comment by mjgiarlo** [comment]
@darrenleeweber OK, I've heard back from the i18n-tasks maintainer and he does not intend to support ERB files, so I've put in a PR to remove this from the config: https://github.com/samvera/hyrax/pull/1479

We will need to document this one manual step.

**Comment by mjgiarlo** [comment]
@darrenleeweber 

* `i18n-tasks` will not auto-translate our yml.erb files, so we need to update those manually when necessary (only when adding a new language, so not a big deal)
* I was thinking we'd document this in the Hyrax release management doc, and propose firing this up as part of cutting new releases. See step 2 here: https://github.com/samvera/hyrax/wiki/Release-management-process
* No worries re: the Stanford account setup.

**Comment by mjgiarlo** [comment]
@darrenleeweber This is now done: https://github.com/samvera/hyrax/wiki/Translations-(internationalization)
