### ISSUE TITLE
Save Work box does not float properly when visibility options are expanded

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#1277]
### Descriptive summary

Hyrax Master

### Rationale

The Save Work box visible in the Create Work metadata page does not float properly when the Open Access, Embargo, and Lease visibility radio buttons are selected. This causes the user to have to scroll all the way to the bottom of the main metadata screen to see the Save and Cancel buttons in the Save Work box.

### Expected behavior
Save Work box should float to allow Save and Cancel buttons to be revealed upon some scrolling, but not requiring a user to scroll down the entire metadata page. The expected behavior is seen when scrolling with the Institution or Private radio buttons selected.

### Actual behavior
When one selects the Embargo, Lease, or Open Access radio buttons, the Save Work box expands to make room for more text and/or options. This seems to cause the floating scroll functionality work differently, so that the Save Work box does not scroll all the way to it's end (where the Save and Cancel buttons are) until the user scrolls the main page all the way to the bottom.

**Comment by jcoyne** [comment]
What version of Hyrax? What browser? Can you provide a screenshot?

**Comment by vantuyls** [comment]
er, hyrax master i think. browser = Chrome  58.0.3029.110 (64-bit)

Video:  https://youtu.be/XxACb5enpBE

**Comment by vantuyls** [comment]
just confirmed this on Firefox v. 53.0.3 (64-bit)

**Comment by jcoyne** [comment]
It says that video is unavailable 😞

**Comment by vantuyls** [comment]
Try now?

**Comment by jcoyne** [comment]
Perfect, thanks.

**Comment by cpd3149** [comment]
we handled this by applying static positioning to the save widget so it doesn't jump around.

**Comment by rjkati** [comment]
This issue is no longer occurring in hyrax 3.5.0
