### ISSUE TITLE
Jasmine test fails in master

### ISSUE THREAD

**Issue by cam156** [samvera/hyrax#1284]
### Descriptive summary

When I run `rspec spec/javascripts/` no failures occur, but when I run `rake jasmine` there is one failure:

![screen shot 2017-06-23 at 10 15 24 am](https://user-images.githubusercontent.com/1599081/27485997-10009abc-57fd-11e7-8594-f05af4e1ff9d.png)

I'm guessing there is a syntax error and that may be why rspec is not running (and counting) the test.

### Expected behavior

All tests should pass when I run rake jasmine

### Actual behavior

One test is failing

### Steps to reproduce the behavior

1. git pull origin master
1. rake jasmine
1. navigate to localhost:8888

### Related work

Link to related tickets or prior related work here.

**Comment by mjgiarlo** [comment]
I'm seeing failures with `rspec spec/javascript/` too. Taking a look.

**Comment by mjgiarlo** [comment]
Failure is

```
authority select
   should change the data-autocomplete-url when you select an authority
```

**Comment by cam156** [comment]
@mjgiarlo looking more closely at that test it seems to be written in es6.

**Comment by cam156** [comment]
I am guessing that chrome is supporting es6 natively, but phantomjs is not.  We have two choices: convert the test to plain old javascript, or try to get the ci runner  (I think phantomjs) to allow es6.

**Comment by mjgiarlo** [comment]
@cam156 I took a quick hack at this and turned up a couple things, but ultimately didn't have enough time to get these tests passing. I wonder if running all our js, coffeescript, and es6 assets through their respective linters might turn up something interesting. Are you inclined to poke at this? My time to work on this is about to disappear (now through July 5 is all about OR2017), sadly.

**Comment by jcoyne** [comment]
This is still an issue as of Nov 21, 2017.

**Comment by no-reply** [comment]
I think this one has been cleaned up in the normal course of development.
Feel free to reopen if this reemerges.

![jasmine](https://user-images.githubusercontent.com/1361776/41186378-17a77a40-6b4a-11e8-8cb5-b8027d91c4ef.png)
