### ISSUE TITLE
Refactor <i> element for icons

### ISSUE THREAD

**Issue by mtribone** [samvera/hyrax#1285]
### Descriptive summary

In Hyrax 2.0.0 alpha, we have many instances where icons are hooked onto an out-of-date `<i>` element. Please use a `<span>` instead per Bootstrap style and HTML5 guidelines.

### Rationale

The `<i>` element is outdated. We have other HTML elements for voice and we should be using inline `<span>` elements to hook our icons in the page.

### Expected behavior

All Bootsrap or FontAwesome icons be attached to a `<span>'

### Actual behavior

Found many instances of `<i>` element being used.

### Steps to reproduce the behavior

1. Open the Hyrax project in the IDE or app of your choice
1. Search for the `</i>`

**Comment by mtribone** [comment]
![screen shot 2017-06-23 at 10 25 01 am](https://user-images.githubusercontent.com/4163828/27486381-68e0d038-57fe-11e7-97fc-904654dd6922.png)

**Comment by metageeky** [comment]
It does not help that FontAwesome suggests the use of outdated `<i>` tags, but mtribone is correct that this is a good thing.

**Comment by atz** [comment]
Totally support this one.
