### ISSUE TITLE
New collection form should have the layout of the edit form

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#1296]

**Comment by atz** [comment]
To clarify, you're saying that `Hyrax::CollectionsController` should be updated?  It currently does:
```ruby
layout :decide_layout
...
      def decide_layout
        case action_name
        when 'show'
          theme
        else
          'dashboard'
        end
      end
```

So AFAICT, that means that the layout IS the same for `create` as for `edit` (namely 'dashboard').  What am I missing?

**Comment by mjgiarlo** [comment]
I assume what @jcoyne means is the difference between https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections/new.html.erb and https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections/edit.html.erb. So the actual layout, not the Rails layout. Terminology is so overloaded.

**Comment by atz** [comment]
Ok, the view/template.
