### ISSUE TITLE
Embargo history include/exclude the current embargo?

### ISSUE THREAD

**Issue by darrenleeweber** [samvera/hyrax#1312]
As of Jun 29, 2017; the https://github.com/samvera/hyrax/blob/master/spec/features/embargo_spec.rb#L7 results in a page with text content (without markup) like this:
```ruby
page = "...
Manage Embargoes: Embargo test(Generic Work) 
Current Embargo This work is under embargo 
...
Past Embargoes This Generic Work has never had embargoes applied to it. 
...
```

It seems weird that the `Past Embargoes` section of that page says “This Generic Work has never had embargoes applied to it” while the `Current Embargo` section says “This work is under embargo”.  This sounds like a contradiction.
- Perhaps the `Past Embargoes` should be everything up to _and including_ the `Current Embargo`?
- Or the text for `Past Embargoes` could read something like `There are no prior embargoes` (when the `Past Embargoes` are everything up to, _but excluding_ the `Current Embargo`)?

I need to figure out whether `curation_concern.embargo_history` includes or excludes the “current embargo” but the `Hyrax::EmbargoPresenter` is not very informative, i.e.
```ruby
def embargo_history
      solr_document['embargo_history_ssim']
end
```

**Comment by jcoyne** [comment]
As far as I know `embargo_history` is just a textual log of embargos that have been applied in the past.

**Comment by mjgiarlo** [comment]
I'm going to close this for now, until we integrate this feature into the UI. We can revisit later. Thanks for writing this up!
