### ISSUE TITLE
My Works missing "show details" button

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#133]
<a href="https://github.com/hectorcorrea"><img src="https://avatars.githubusercontent.com/u/568286?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hectorcorrea](https://github.com/hectorcorrea)**
_Thursday May 19, 2016 at 13:07 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2054_

----

### Descriptive summary

According to the wire frames the "My Works" view should include an option to allow to the user to see the details of the works in the list. The wire frames propose a ">" little icon next to each work https://wiki.duraspace.org/display/hydra/My+Works+-+Phase+1+-+UI+Wireframe#mockup_p1-works-my_works

This is how Sufia looks at the moment:

![screen shot 2016-05-19 at 9 03 10 am](https://cloud.githubusercontent.com/assets/568286/15394438/e89d6e10-1da0-11e6-8d7b-6be60cf48c2e.png)
### Expected behavior

An ">" icon should be displayed next to each work to allow the user to view the details of each work.
### Actual behavior

No ">" icon exists.
### Steps to reproduce the behavior
1. Go to My Works
2. Look at the list of works
3. Wait a long time before realizing that the icon is just not gonna show up on its own.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday May 19, 2016 at 13:20 GMT_

----

I wouldn't call this a bug. It was a back logged feature request.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday May 19, 2016 at 13:20 GMT_

----

Probably not required for 7.0.0 either

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday May 19, 2016 at 21:09 GMT_

----

@hectorcorrea Can you scan the backlog for any related tickets? If we don't have any, let's keep this around, else let's :boom: it. Moving to 7.1.0.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Wednesday Sep 28, 2016 at 13:19 GMT_

----

Show the File Format as the representative file of the work. Only one file format is indexed.

Open close JS is in Batch Edit.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Dec 20, 2016 at 22:38 GMT_

----

Review this fix from SS: https://github.com/psu-stewardship/scholarsphere/commit/f476a347ad4bf604f053e24a2256a5c798e9a10a

**Comment by no-reply** [comment]
This page no longer exists, replaced by the dashboard.
