### ISSUE TITLE
Turning off transfer ownership should remove it from the UI

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#1338]
##Descriptive summary

Currently, turning off transfer of ownership in the Dashboard - Settings - Technical page does not remove transfer of ownership from menus in the repository (e.g. the item Action drop down menus in the My Works page).

Attempting to use transfer of ownership when it is turned off only results in being redirected to the homepage with the error: "You are not authorized to access this page" (see image)

<img width="1424" alt="screen shot 2017-07-13 at 3 01 23 pm" src="https://user-images.githubusercontent.com/9534576/28191178-ad7c793c-67e3-11e7-82ed-009b5b98f68e.png">

##Expected behavior

Turning off transfer of ownership makes this option in all elements of the UI go away.

##Actual behavior

Turning off transfer of ownership leaves the option in UI and using that option results in an unhelpful message.

**Comment by mcdowney** [comment]
Closing as fixed
