### ISSUE TITLE
AttachFilesToWorkJob is scheduled even when no files were uploaded.

### ISSUE THREAD

**Issue by jonathandixon** [samvera/hyrax#1339]
### Descriptive summary

Hyrax HEAD

When creating a work with no files the `CreateWithFilesActor` schedules `AttachFilesToWorkJob`.

This [line](https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/create_with_files_actor.rb#L41) should probably be changed to:

```rb
return true if files.blank?
```

### Expected behavior

AttachFilesToWorkJob should not be scheduled if there were no files uploaded.

### Actual behavior

AttachFilesToWorkJob is scheduled.

### Steps to reproduce the behavior

1. Create a work without files.
2. Observe Job Queue

**Comment by mjgiarlo** [comment]
@jonathandixon Thanks for writing this up! Are you inclined to toss a PR at this?
