### ISSUE TITLE
Document how to override metadata

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#134]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [awead](https://github.com/awead)**
_Friday May 20, 2016 at 16:16 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2072_

----

### Descriptive summary

Users should be able to add new properties to their Sufia 7 applications, as well as remove existing ones, with certain exceptions. We should document how developers can do this. It would include steps regarding model, form and view changes.
### Related work
#2066

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday May 20, 2016 at 19:28 GMT_

----

Please use this wiki page for the documentation: https://github.com/projecthydra/sufia/wiki/Customizing-Metadata (We already have this page for 6.x doc: https://github.com/projecthydra/sufia/wiki/Customizing-Metadata-(Sufia-6.x))

And feel free to consolidate. (See: https://github.com/projecthydra/sufia/wiki/Customizing-Metadata:-nested-attributes,-part-1 and https://github.com/projecthydra/sufia/wiki/Customizing-Metadata:-nested-attributes,-part-2)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Jun 10, 2016 at 17:00 GMT_

----

Tagging @jhallida

**Comment by no-reply** [comment]
See: http://samvera.github.io/customize-metadata-model.html and related pages.
