### ISSUE TITLE
Collection Types: Update Hyrax-generation process to create a collection type for Administrative Sets

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1342]
### Descriptive summary

Create a mostly read-only collection type for Administrative Sets.  This will allow users to interact with Admin Sets as though they are a collection type.

### Rationale

For the initial implementaiton, the Admin Set underlying code will not change much, if any.  But to a user, the Admin Set will appear to be a collection type.

See model issue for collection types rationale.

### Implementation

**File:** (lib/generators/hyrax/install_generator.rb)[https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/install_generator.rb]

Write a generator that...
- [x] creates a new collection type named: Administrative Sets, with machine_id: admin_set, and with a brief description of what an Admin Set is and the requirement that there be at least one
- [x] save the collection type machine_id in a globally accessible structure (most likely ENV variable, but maybe Hyrax has its own way of handling this - NEEDS INVESTIGATION)
- [x] assign default settings that correspond to the expected behaviors and restrictions of the current implementation for Administrative Sets
  - [x] nestable=false
  - [x] discovery=true
  - [x] sharing=true
  - [x] multiple_membership=false
  - [x] require_membership=true
  - [x] workflow=true
  - [x] visibility=true
- [ ] assign default settings for participants
  - [ ] collection_mangers -> group: admins
  - [ ] collection_creators -> group: admins

QUESTION: Is the group admin or admins?

### Related work

| Collection Types feature | Issue |
| ------------------------ | ----- |
| Admin Set Generator      | this issue |
| User Collection Generator | #1485  |
| Routes                   | #1347 |
| Controller               | #1341 |
| Model                    | #1343 |
| View - Index             | #1349 |
| View -  New/Edit         | #1348 |
| Partial -  Description   | #1344 |
| Partial -  Settings      | #1346 |
| Partial -  Participants  | #1345 |

**Comment by dlpierce** [comment]
Regarding "save the collection type machine_id in a globally accessible structure", would following the existing patterns for config in /lib/hyrax/configuration.rb be sufficient?

**Comment by elrayle** [comment]
@dlpierce I'm wondering if we need to do that if we define up front via the generator that the machine_id for the admin set type is `'admin_set'`.  The proposed check for `collection_type.admin_set?`  checks for `machine_id == 'admin_set'`.  See issue #1486.

**Comment by elrayle** [comment]
Remaining Work will be addressed in issues:
* Issue #1601 - Add default values for participants
* Issue #1533 - Hook generated User Collection type into the engine_cart test app generation process
