### ISSUE TITLE
Collection Types: Create model for collection types

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1343]
### Descriptive summary

Add code to implement the model part of the Rails MVC for managing collection types.

### Rationale

Site administrators can configure various types of collections as needed for their implementation.  Examples of collection types include User Collections, Exhibits, Controlled Collections, etc.

These are typically configured such that...
* User Collections - can be created by anyone, are not discoverable, works can belong to multiple user collections, optionally may be nested
* Exhibits - can be created by select staff, are discoverable, works can belong to multiple exhibits, typically are not nested
* Controlled Collections - can be created by select staff, typically discoverable, works can belong to multiple controlled collections, typically are nested.  Examples include DSpace type communities and collections, collections tied to organizational units like university departments, etc.

See [user stories](https://wiki.duraspace.org/x/YQCzB) and [requirements](https://wiki.duraspace.org/x/aojBB) for collection extensions.

### Expected behavior

Hold configuration specific to a collection type in the database.

### Implementation

**File:** app/models/hyrax/collection_type.rb
**Locaton of Data:** DB in table collection_type with an index on machine_id
**Fields:** See table below for names, descriptions, and values.

Provide general descriptive metadata fields for a collection type.

| field name | description | example values |
| ------------ | ------------ | -------------------|
| :title | Human readable label shown to users when they select collection type for new collections and in the summary table showing all collections and their types | User Collection, Exhibit, Nested Collections, etc. |
| :description: | A short description that is shown to users when they select collection type for new collections. | "A curated collection for public users." |
| :machine_id | A unique id that can be used in the future to create a class of the same name that can add additional behaviors and properties used with collections of this type.  Not used during this sprint. | user_collection, exhibit, nested_collections, etc. |

Provide property fields to hold configuration values for a collection type configuration.

| field name | description | default value | possible values |
| ------------ | ------------ | -------------| ------------------ |
| :nestable | Allow collections to be nested (a collection can contain other collections; a collection cannot have itself as an ancestor) | true | true, false |
| :discovery | Allow collections to be discoverable | true | true, false |
| :sharing | Allow users to assign collection managers, depositors, and viewers for collections they manage | true | true, false |
| :multiple_membership | Allow a work to belong to multiple collections of this type | true | true, false |
| :require_membership | A work must below to at least one collection of this type | false | true, false |
| :workflow | Allow collections of this type to assign workflow to a new work | false | true, false |
| :visibility | Allow collections of this type to assign initial visibility settings to a new work | false | true, false |

Provide ability to assign participants to a collection type.  
* collection managers
* collection creators

#### Outstanding Questions:
How do permission templates for participants fit into this work?  Are they created as part of the collection type configuration?  Or are they used by the individual collections to hold participants? or both? Are they created when the collection type is created?  See Code for Permission Templates in the wiki for an exploration of this code... https://wiki.duraspace.org/x/2aA2BQ

### Related work

| Collection Types feature | Issue |
| ------------------------ | ----- |
| Admin Set Generator      | #1342 |
| User Collection Generator | #1485  |
| Routes                   | #1347 |
| Controller               | #1341 |
| Model                    | this issue |
| View - Index             | #1349 |
| View -  New/Edit         | #1348 |
| Partial -  Description   | #1344 |
| Partial -  Settings      | #1346 |
| Partial -  Participants  | #1345 |

**Comment by randalldfloyd** [comment]
@elrayle Regarding our conversation at standup about whether the model is complete enough to move this issue to done.  One thing I didn't try to tackle from the requirements above is:

Provide ability to assign participants to a collection type.
    collection managers
    collection creators

I think I'm not able to see on my own how that should work, but #1485 calls for being able to set participants so I guess more work is needed here to support related stories?

**Comment by elrayle** [comment]
This is similar to Admin Sets use of participants.  But at the same time, it is different.  AdminSets are an object that reside in Fedora and has a permission template associated with it.  I think that the permission_templates table in the db stores access information.  We may be able to leverage that.

**Comment by elrayle** [comment]
Some modifications are still happening for this as needed.  But the requirements as described in this issue are complete.
