### ISSUE TITLE
Collection Types: Create index views for managing collection types

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1349]
### Descriptive summary

Add code to implement the index view for listing collection types.

### Rationale

See model issue for rationale.

### Implementation

**File:** app/views/hyrax/admin/collection_types/index.html.erb

#### Expected user interactions

Create the UI view for listing collection types.

From this page, a user can...
- [x] see a list of existing collection types
- [x] click a button to create a new collection type goes to `/admin/collection_types/new`
- [x] click edit for an existing collection type goes to `/admin/collection_types/{:id}/edit`
- [x] click delete for an existing collection type
  - [x] disallow if there are any collections of this type
  - [x] show a confirmation box stating this cannot be undone

Exact text for the page is in the mockup below.

#### SPECIAL NOTE on Admin Sets:

For the initial implementaiton, the Admin Set underlying code will not change.  But to a user, the Admin Set will appear to be a collection type.

To make the illusion happen...
* as part of the hyrax generation process, a collection type will be created for Administrative Sets and the id will be recorded in a variable that can be checked by this UI (see issue #1342 for Admin Set Generator)
* if current_collection_type == admin_set_collection_type_id, do not include a remove button

### Mockup

![collection-types](https://user-images.githubusercontent.com/101482/28342644-22a99ada-6bce-11e7-9532-1903a1e9bb0c.png)

### Related work

| Collection Types feature | Issue |
| ------------------------ | ----- |
| Admin Set Generator      | #1342 |
| User Collection Generator | #1485  |
| Routes                   | #1347 |
| Controller               | #1341 |
| Model                    | #1343 |
| View - Index             | this issue |
| View -  New/Edit         | #1348 |
| Partial -  Description   | #1344 |
| Partial -  Settings      | #1346 |
| Partial -  Participants  | #1345 |

**Comment by adamjarling** [comment]
@elrayle Should updating the sidebar be part of this story, or just the new view/page itself?

**Comment by elrayle** [comment]
@adamjarling - The sidebar link to the Collection Types index page was added by PR #1446.

**Comment by elrayle** [comment]
This is complete but will have one minor change.  See issue #1486.

**Comment by elrayle** [comment]
From PR #1472 

#### Issues remaining:
 -  We added a `collections?` method to the CollectionsType model so that we could simulate different modals for empty vs full collection types. This will need to be changed when we have implemented a way to find collections that belong to a collection type. (being addressed by Issue #1341)
 - Added `collection_type.machine_id != 'admin_set'` as a placeholder to check if the collection type was admin set. Not sure what the final check will be yet.
 - Actual delete functionality not wired up yet (being addressed by Issue #1524)
 - Button to take you to 'View collections of this type' (if unable to delete because collection type has collections) not wired up yet
