### ISSUE TITLE
Change internal_test_app to serve out of a relative_url_root

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#136]
<a href="https://github.com/grosscol"><img src="https://avatars.githubusercontent.com/u/1520508?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grosscol](https://github.com/grosscol)**
_Thursday Jun 16, 2016 at 13:08 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2237_

----

### Descriptive summary

Code that assumes the application will be served out of the webhost at / is detrimental.  It is not a valid assumption that all adopters will be serving their Sufia based application from the root context of the host.  In order to catch those cases, the internal_test_app should serve out of a relative_url_root by default.  Code that plays nicely with relative_url_root should also operate as expected when served out of the root context.
### Proposed behavior

Generate internal_test_app with an application.rb and config.ru that will result in the application being served out of /test_app for non-opinionated Rack web app servers.

This should work for Webrick and Puma, but will be problematic for Passenger in production.  That will have to be documented in both the config and README.

Passenger appears to read the application's relative_url_root and takes it upon itself to serve the application out of that context  This assumes that the Rack config will still be set to serve out of the root context.
### Related

Discussion in hydra-tech group: https://groups.google.com/forum/?hl=en#!topic/hydra-tech/mfzAnDaNM_g

**Comment by no-reply** [comment]
Can anyone comment on the relevance of `internal_test_app` to this issue?

If the goal of this is to fix an issue concerning engine_cart generated apps, I think that's a `wontfix`, unless there's an outstanding issue for development or CI environments we explicitly support.
