### ISSUE TITLE
Improve process of adding works to a collection from Works index page

### ISSUE THREAD

**Issue by ggeisler** [samvera/hyrax#1370]
### Descriptive summary

The process of adding a work to a collection from the Works index page has several UX problems:

1. On the Works index page, the Actions menu for a given work doesn't include a way to add to a collection
1. On the Works index page, the affordance of adding multiple works to a collection using the bulk action checkboxes is hidden, in that you have to first check one or more items before the Add to Collection button is made visible
1. If you want to add works to a new collection from the Works index page, you have to go through the Add to Collection modal, even though the radio button set of existing collections you are shown is irrelevant to your goal
1. In the modal, the use of radio buttons for choosing an existing collection, while fine if the number of collections to choose from is reasonably small, is less feasible when there are many collections, as might be expected with repositories that encourage user and/or exhibit types of collections 
1. In the modal, the instructions text refers to "files" rather than works
1. In the modal, the button labels are confusing, in that you are following a process up to now labeled as "Add to collection" but the button you have to select to add the works to an existing collection is labeled "Update Collection" (I don't think most users will think of adding works to a collection as "updating" it; that is more the way a developer thinks of actions that modify a object)

![before](https://user-images.githubusercontent.com/101482/28394415-cdbb1a42-6ca1-11e7-92a9-a3dc615db082.png)

### Recommendation

A recommendation to address items 1 and 2 above is included in the currently open ticket 
https://github.com/samvera-labs/hyku/issues/447. Since that ticket is 6 months old and some details of the mockups in it have been updated based on requirements from the Collections Extensions WG, I'll include updated mockups here:

- Replace the conditionally-displayed bulk action buttons with a Bulk Actions select menu, that is always visible:

![index](https://user-images.githubusercontent.com/101482/28394378-7e7395a4-6ca1-11e7-9d15-d56f329e5b01.png)

- The Bulk Actions menu looks like this (note the separate actions for adding to an existing collection and a new collection):

![bulk](https://user-images.githubusercontent.com/101482/28394388-94a935ea-6ca1-11e7-8d27-9f3c4ab329bc.png)

- The Select menu under Action for a given work adds options to add to both an existing collection and a new collection:

![single](https://user-images.githubusercontent.com/101482/28394395-a657f114-6ca1-11e7-8c03-45ec59e8fb98.png)

- Since there are now individual actions for adding to an existing versus a new collection, the Select a collection modal can be improved:

![after](https://user-images.githubusercontent.com/101482/28395075-4bbdb05e-6ca6-11e7-9283-a89cdf04994f.png)

1. Update title of modal to "Add selected works to collection", where "works" is pluralized appropriately based on whether the user has selected a single or multiple works
1. Remove the Add to new Collection button. If the user selects "Add work(s) to new collection" from either the single or bulk actions menus, take them straight to the New Collection page, without involving the modal.
2. Change the label of the Update Collection button to "Add to collection"
1. Change the label of the "Close" button to "Cancel" (not shown in mockup but "cancel" is more descriptive of the action it represents)
3. Replace the current label (incorrectly implemented as a fieldset legend) and radio button set with a Select2 select box and label. 

Note that we are already using Select2 in Hyrax and using it here enables us to provide a select box with a typeahead-like filter, which addresses (or at least mitigates) the problem of having a long list of collections to choose from. The user can use the select as a normal select menu when the list of choices is reasonably small, but can start typing the name of a collection in the Select2 input box if the list is longer. (See https://select2.github.io/examples.html#select-boxes-with-labels for details about the Select2 select menu.)

**Comment by elrayle** [comment]
I like it.  Should be easier to use.  I can't tell you how many times I accidentally hit Add to New Collection after selecting a collection and intending to update that collection.  All because the Add to New was all the way to the right and my autopilot went to the far right button even though I want to update 90% of the time.

A big +1 for the new design.

**Comment by mcdowney** [comment]
I think most of this was addressed with the work done on the Collections Extension, so closing this.
