### ISSUE TITLE
Collections: Create relationships partial of the new/edit form

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1377]
### Descriptive summary

Add code to implement the Relationships tab partial for the new/edit form views for collections.  This partial is shared by both the new and edit form views.

### Rationale

See model issue for rationale.

### Implementation

**Files:**
* Edit [app/views/hyrax/collections/_form.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections/_form.html.erb)
* Create [app/views/hyrax/collections/_form_relationships.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections/_form_relationships.html.erb)

#### Expected user interactions

Add the tab to the form by editing _form.html.erb.

Create the UI view for managing sub-collections for a collection by adding partial _relationships.html.erb.

Include sections for showing...
- [x] This Collection in Collections - Member of collection
- [x] Other Collections in this Collection
  - [ ] Attach New Collection (goes out an creates a new collection, then adds the relationship when done -- not working clean for works b/c you can't come back to editing the work you are adding the sub-work to via this approach)
  - [ ] Select existing collection to be a member sub-collection

Exact text for the page is in the mockup below.

#### Validation

Any changes to parent or sub-collections must validate that the path of collections is not circular.  This collection cannot be its own ancestor or descendant.

#### SPECIAL NOTE on Admin Sets:

For the initial implementaiton, the Admin Set underlying code will not change.  But to a user, the Admin Set will appear to be a collection.

To make the illusion happen...
* Nothing to do since admin sets can not nest.

### Mockup

![collection-new-edit-relationships](https://user-images.githubusercontent.com/101482/29032682-2a6545fc-7b47-11e7-829c-c384e3d20e2d.png)

#### Issues related to UI work for nesting

* #1417 original UI epic for admin index
* #1509 admin index - listing of collections - includes description of action menu items
* #1512 process `Add collection to another collection` action + modal for selecting other collection  (This one has the brain dump list of things needed for nesting)
* #1377 relationship partial for edit form

#### Collections original epic issues (mainly organized by UI)

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index            | #1417 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | (this issue) |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by adamjarling** [comment]
@elrayle From the 'Implementation' section of description above, I'm not seeing the link for `app/views/hyrax/collections/_form.html.erb`.  Should this file exist, or be created, or is the link a typo maybe?

**Comment by elrayle** [comment]
Remaining Work: 
#1719 Populate edit Relationships tab with list of parent collections and sub-collections

**Comment by elrayle** [comment]
All requirements of this issue are met by PR #1702 or covered by the Remaining Work issues.
