### ISSUE TITLE
Extraneous access control resource

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#138]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [awead](https://github.com/awead)**
_Thursday Jul 07, 2016 at 16:05 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2328_

----

### Descriptive summary

I'm noticing this while looking at calls made to Fedora while creating works in Sufia.

When I visit `/concern/generic_works/new` there's a new Hydra::AccessControl created in Fedora. However, if I continue to create the work and save it, that original acl object doesn't appear to be used at all. There's another acl that actually is governing the work.
### Expected behavior

The initial ACL ought not be created.
### Steps to reproduce the behavior
1. Add HttpLogger to the internal test app in application.rb (copy the lines from spec_helper)
2. Watch the output as your create a new work

**Comment by no-reply** [comment]
This seems related to https://github.com/samvera/hydra-head/issues/453

**Comment by no-reply** [comment]
This is fixed by Hydra::AccessControls `v10.7.0`
