### ISSUE TITLE
Transfers of ownership should be admin-aware

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#1382]
Admin should be able to transfer ownership of a work even if does not have explicit edit access to the work. The ability to manage ownership of all works in the repository over time is core to an administrator's responsibility.

## Current Behavior

As the Repository Administrator, if I do not have explicit edit access to a work, then I do not have the option to select "Transfer Ownership of Work" from the Actions menu on the Works Index page.

## Expected Behavior

As the Repository Administrator, I have the option to select "Transfer Ownership of Work" from the Actions menu on the Works Index page for any work in the Repository.

**Comment by hannahfrost** [comment]
@ggeisler and I determined that there is no design needed here. With the proper permissions in place, the Admin should be abe to do what they need to do via the existing Work edit UI.

**Comment by mjgiarlo** [comment]
@hannahfrost @ggeisler My bad! Removed that label.

**Comment by jlhardes** [comment]
This appears to be fixed - I am able to transfer the ownership of any work when I am logged in as an admin user on nurax-dev.

**Comment by rjkati** [comment]
Closed since issue is fixed.
