### ISSUE TITLE
Collections: Modify model to include Collection Type and settings methods

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1383]
### Descriptive summary

Add field collection_type to the model part of the Rails MVC for managing collections.

### Rationale

This effort is expanding the existing Collections implementation to accommodate Collection Types and the new [requirements](https://wiki.duraspace.org/x/g402BQ) that are part of the [Collection Extensions](https://wiki.duraspace.org/x/5JM2BQ) work.

### Expected behavior

Hold existing metadata properties and new :collection_type property.  Provide access to collection type configurations.

### Implementation

**File:** [app/models/concerns/hyrax/collection_behavior.rb](https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/collection_behavior.rb)
**Location of Data:** Fedora object with model Collection
**Fields:** See table below for names, descriptions, and values.

Provide property fields to hold configuration values for a collection configuration by adding the property definition to collection_behavior.rb.

| field name | predicate | description | example value | comment |
| ------------ | ----------- | --------------| ---------------- | ----------- |
| collection_type | _See question below_ | Machine id | user_collection, exhibit, nested_collection, etc. | When instantiated, should this return the machine_id or an instance of the collection_type? | 

![question_24](https://cloud.githubusercontent.com/assets/6855473/13064236/f2f04cbe-d41e-11e5-9674-e9a56a6326e6.png) **QUESTION:** What predicate should be used to store the collection_type for a collection?

NOTE: There is no metadata defined in collection_behavior.rb.  Collections get metadata through [Hyrax::CoreMetadata](https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/core_metadata.rb) included in collection_behavior.rb.  And through [Hyrax::BasicMetadata](https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb) included in the generated Collection class in the app.  Both core and basic metadata are also used by Works and are not good locations for adding the collection_type, which is specific to collections only.

Provide methods that the collection can use to determine it's configuration based on the collection type by adding the methods to collection_behavior.rb.

| method name | description | returns |
| ------------ | ------------ | -------------|
| nestable? | Can this collection be nested in others of its type? | true, if it can; otherwise, false |
| discoverable? | Can this collection be discovered by public users? | true, if it can; otherwise, false |
| shareable? | Can this collection be shared with other users? | true, if it can; otherwise, false |
| multiple_membership? | Can works belong to more than one collection of this type? | true, if it can; otherwise, false |

NOTE: These methods should get this information from the collection's collection type.  

Implementation Question:  We have the machine_id and can query the DB for the setting.  Would it be more efficient to have an instance of the collection_type accessible from the collection in order to answer these questions for the collection?  Or a pointer to a shared instance of the collection_type?

#### SPECIAL NOTE on Admin Sets:

For the initial implementation, the Admin Set underlying code will not change.  But to a user, the Admin Set will appear to be a collection.

To make the illusion happen...
* Two possible approaches:
  * OPTION 1: Add collection_type property and the methods to the Admin Sets code.  Then use the same processing mechanism as for regular collections.
  * OPTION 2: Admin Sets can have the same methods added, but they can be hardcoded to return the appropriate responses as follows...
    * nestable? false
    * discoverable? - get from collection type
    * shareable? true
    * multiple_membership? false

Option 1 might save us some time down the road.

### Related work

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | (this issue) |
| View - Index            | #1417 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by elrayle** [comment]
#### RE: predicate to hold collection's collection type

The following were discussed in slack, but rejected...

* **skos:concept/owl:class** - This was briefly explored, but it leads back to rdf:type.  https://www.w3.org/TR/skos-reference/#concepts isa https://www.infowebml.ws/rdf-owl/Class-owl.htm isa https://www.infowebml.ws/rdf-owl/Class-rdfs.htm which defines a class that can be used with rdf:type to define an instance of the class
* **rdf:type** - There are currently multiple rdf:type values and this could be one more.  However, rdf:type expects a URI as a value.  Since sites can create collection types on the fly AND sites could use the same name for collection types, yet mean something different, this is not a good match.  We would have to generate URIs on the fly and there would be a proliferation.
* **pdcd:use** - It was suggested that the need for a string constant value identifying a type was similar to the need to identify a type (or use) of a file in a fileset.  However, further exploration revealed that the types for files in filesets is predefined and uses constants.  http://pcdm.org/2015/05/12/use

**Comment by escowles** [comment]
I can see the appeal of having a literal value, since users will be creating their own collection types.

But, I'm not completely sure if "These methods should get this information from the collection's collection type" means that there will be code that makes this decision, or whether we expect there to be a CollectionType model with properties/forms/etc. for the user to set those values.  If the latter, then the URLs for those CollectionType instances would be reasonable local URIs for rdf:type or some other property.

**Comment by mjgiarlo** [comment]
> QUESTION: What predicate should be used to store the collection_type for a collection?

Do you have suggestions for this, @samvera/hyrax-metadataists ?

**Comment by geekscruff** [comment]
There is http://schema.org/additionalType ... although it also expects the value to be a URL.

**Comment by elrayle** [comment]
@escowles 
Process for creating a collection type:
* Site admin creates a new type and assigns a name (e.g. User Collection)
* machine_readable version of name is created (e.g. :user_collection) - must be unique and is indexed in collection_type database table
* a row in the collection_type database table tracks name, id, and settings (e.g. name="User Collection", machine_id="user_collection", nestable=true, multiple_membership=true, discoverable=false, etc.)

Process for creating a collection:
* User creates a new User Collection
* When the collection is saved, one of the properties is collection_type (e.g. :user_collection)  **This is what creates the need for a predicate.**

From the collection type, the collection can determine if it is nestable, allows multiple_membership, is discoverable, etc.

I am open to suggestions for an alternative approach.

**Comment by escowles** [comment]
@elrayle I think you could use the URL of the collection_type entries as the URI for rdf:type or whatever predicate winds up making sense.

**Comment by elrayle** [comment]
[schema:additionalType](http://schema.org/additionalType) was suggested as the predicate and looks quite promising.

> An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax.

It is a subtype of rdf:type.  rdf:type was originally rejected for two reasons...
* need for URI
* too many types already such that it would be hard to sort out which of the types was the collection type

Why is a subytpe of rdf:type now ok?
@escowles suggested using a gid as the URI for additionalType.  More info in next comment on gid usage.

**Comment by elrayle** [comment]
From slack discussion with @escowles 

escowles:
> if you don't want to use the CollectionType URIs, then maybe you could use the GlobalIDs e.g., `gid://hyrax/CollectionType/1`
> 
> that at least has the advantage of tooling for converting between a CollectionType instance and the string form you could store in a literal property, and it also has precedent in hyrax (since that's how Sipity does it)

elrayle:
> Can you point me to code that processes the gid?  Will this still apply since the collection type itself is NOT stored in fedora?  It is stored in the application database only.

escowles:
> * here's the sipity class that converts various things to a Sipity::Entity: https://github.com/samvera/hyrax/blob/master/app/conversions/power_converters/sipity_entity.rb
> 
> * here's where a solr document builds a GlobalID based on the class/id/etc.: https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/solr_document_behavior.rb#L53

**Comment by elrayle** [comment]
Thanks all for the discussion.  I feel like we've got some forward momentum now.

**Comment by elrayle** [comment]
Working with GIDs...
```
      gid  = GlobalID.new(RDF::URI.new(sgid)) # creates a global id from
      sgid = gid.to_s # gid://internal/CollectionType/user_collection
      mid  = gid.model_id # user_collection # NOTE: Requires collection_type to delegate id to machine_id
```

**Comment by elrayle** [comment]
Remaining work:
* PR #1521 - is adding the connection between the collection and the collection_type. 
* Issue #1383 - Admin set work is addressing the admin set specific parts
