### ISSUE TITLE
Discuss: Batch Edit redesign / overhaul

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#139]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hackmastera](https://github.com/hackmastera)**
_Thursday Jul 07, 2016 at 18:05 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2330_

----

### Goals
- Repair / expand the usability of batch edit.
- Better integrate form fields so custom fields can be re-used from other parts of the application
- Allow both single-valued and multivalued fields to be batch edited
- Redesign UI for better usability
### Related

some discussion on #2303 
@projecthydra/sufia-ui-ux-advisors

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hackmastera](https://github.com/hackmastera)**
_Thursday Jul 07, 2016 at 18:08 GMT_

----

At one point I had drawn something up, UI-wise, but I lost that and I have no memory of it (thought the memory was sufficiently outsourced!)

Just sketched this, not a proposed UI because it's too weird but a way for me to start thinking about required UI interactions. comments welcome.

![2016-07-07 14 07 17](https://cloud.githubusercontent.com/assets/845363/16663966/2d4c4c44-444c-11e6-857a-49538036d4d9.jpg)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Jul 07, 2016 at 18:10 GMT_

----

Thanks for getting this started, @hackmastera!

@DanCoughlin do you happen to have the diagram we (you) did a few years ago for the batch-edit redesign? This would be a great place to share that if you can dig it up.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hackmastera](https://github.com/hackmastera)**
_Wednesday Aug 31, 2016 at 13:03 GMT_

----

looks like design work is happening on https://github.com/projecthydra-labs/lerna/issues/291

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Dec 20, 2016 at 23:41 GMT_

----

@hackmastera indeed, we are very nearly ready to share our mock-ups.

**Comment by no-reply** [comment]
Closing this, as other batch edit projects have been underway in the community.

We'll want to revisit batch with that input in mind.
