### ISSUE TITLE
Hyrax does not enforce Discovery-only permissions

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#140]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [awead](https://github.com/awead)**
_Thursday Aug 04, 2016 at 02:04 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2392_

----

### Descriptive summary

Although discovery is not enabled as a permission option, if it is added to a generic work, the show view is permitted instead of just the index view.
### Expected behavior

With a work that is discoverable by a user, the user should be able retrieve the work in a search result, but not be able to view its full record in the show view.
### Actual behavior

A discoverable work is retrievable in a search as well as displayable in its show view.
### Steps to reproduce the behavior
1. Sign in as user1
2. Create a private work with a memorable title
3. Via the console:

``` ruby
work = GenericWork.find([work_id_you_just_created])
work.discover_groups = ["registered"]
work.save
```
1. Back in the web app, log out, and sign in as user2
2. Search for the work

You should see the work in the search results and be able to view it's record when you should not be able to. Downloading, however, is still not permitted.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Aug 04, 2016 at 03:15 GMT_

----

I'm not sure you have the right expectation.  I think that discover means you can see it in the index and in the show page.  You just can't download the item itself (binary).  
Discover == view metadata
Read == view binary.

 In any case it's confusing

**Comment by mjgiarlo** [comment]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [awead](https://github.com/awead)**
_Thursday Aug 04, 2016 at 04:20 GMT_

----

Ah, ok, I don't then. I thought the expectation was that discovery meant you could only see the items in search results (index) but **not** in the show view. Was that ever the case? I could have sworn that's the way it was at one point, but maybe I'm mistaken.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [awead](https://github.com/awead)**
_Thursday Aug 04, 2016 at 04:21 GMT_

----

FWIW, a potential fix lies in CurationConcerns::WorkSearchBuilder.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Aug 04, 2016 at 16:37 GMT_

----

My understanding, wrong as it may be, matches @awead's. Maybe that's why we abandoned the feature when we were building ScholarSphere 1.0.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Aug 04, 2016 at 17:02 GMT_

----

My understanding used to be the same as @awead's but over and over at DCE, I saw people building their own version that did as I described above.  It makes no sense at all to show people search results, but not a show page.  What is on a show page that is restricted that is not in the search results? At the very least you want to say "this item is available to look at by special appointment in XXXXX library"

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Aug 04, 2016 at 17:15 GMT_

----

I don't disagree, @jcoyne.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [awead](https://github.com/awead)**
_Thursday Aug 04, 2016 at 17:52 GMT_

----

Neither do I, @jcoyne. The use case that I'm trying to support is showing one set of metadata to a user/group, versus another. The index view would be a more restrictive view as opposed to the show view, which would have all terms. However, I think the better solution is effect a show page that shows the terms based on the user. That logic could be encapsulated into the presenter fairly easily, I would think.

**Comment by julesies** [comment]
I'm wondering if we could take advantage of the "discover" feature for embargoed content? 

We have a couple of use cases where we would want the "Metadata Only" view. 
1. For embargoed works - our Graduate School likes the work metadata to be discoverable even if we can't exposed the files while the work is under embargo. This helps show the output of students and also exposes papers to google where an author might not be able to share their paper with the public but could share with individuals by request. 
2. The Honors Theses also wants to use this "Metadata Only" view for honors theses where they want to store the files/papers permanently, but want to expose the metadata. In this case, they never intend to release the papers, for specific reasons.

It seems the "Metadata" only is current supported (of course I tested in Sufia 7.3 FWIW) but just not at the time of deposit. So you would have to go back into work and set each file to private not the easiest of tasks in the UI though. 

Maybe the more compelling uses for this are in the special collections areas, where this feature is really important, but since we are only using Hyrax for IR/Self-deposit I won't mention them. FWIW, we don't have any compelling reasons why we would need to hide the work view altogether and only make works have this "stub" appearance in search results which prohibits the view of metadata. We do have this feature in the current CDR stack, but it hasn't proven useful or even noticed.

**Comment by no-reply** [comment]
It seems like this issue still requires some discussion.

cc: @samvera/hyrax-repo-managers

**Comment by jlhardes** [comment]
I think I agree that the original report isn't really a problem. If the item is discoverable in search results then the show page should also be available to view metadata and derivatives. The item does not have to be available for download and that sounds like what we have in place now.

The embargo case is potentially a different issue. I think if we have an embargo in place now, the item is not shown in search results and it is not possible to see the metadata or derivatives. For the embargo case described above, it sounds like we would want the item to be discoverable in search results and we want the metadata to be viewable but not show derivatives while the embargo is in place.

@rjkati is it possible to test for these 2 cases to verify that:

1) an item can be set to be discoverable and viewable but not downloadable
2) what exactly happens in search results for an item that is embargoed (does it just not appear in search results at all?)

If 1) is verified then I think this ticket can be closed. If 2) is showing that embargoed results cannot appear in search results then I think we have a new enhancement issue to discuss (and maybe see if an institution already has something in place to contribute back for this workflow).

**Comment by rjkati** [comment]
@jlhardes 

For Case 1, it is possible to set the work page to Public, which makes the work discoverable. However, if I restrict access to the file (either to institution, private or embargo) independently of the work, the file is not viewable or downloadable unless an authorized user is logged in. For example https://nurax-dev.curationexperts.com/concern/generic_works/s4655g72c?locale=en has a Public work with a Private file.

For Case 2, the embargoed item does not appear in search results for most users. It will appear in search results for the depositor if the depositor is logged in.

**Comment by jlhardes** [comment]
Created #5016 for use case where embargoed work should be discoverable. Closing this issue since items can discoverable and viewable but not downloadable.
