### ISSUE TITLE
NoMethodError in Hyrax::Dashboard#index

### ISSUE THREAD

**Issue by rodyoukai** [samvera/hyrax#1400]
In a clean instalation of Hyrax, when I try to sing up a user the response is this:

> 
> NoMethodError in Hyrax::Dashboard#index
> Showing /home/rails/rails_project/vendor/bundle/gems/hyrax-1.0.3/app/views/hyrax/users/_vitals.html.erb where line #11 raised:
> 
> undefined method `delegated_attributes' for nil:NilClass
> 
> Extracted source (around line #28):
>  
> def self.delegated_attributes 
>        primary_concern.delegated_attributes    
> end       
> 
>  def self.solr_query_handler
> 
> Trace of template inclusion: /home/rails/rails_project/vendor/bundle/gems/hyrax-1.0.3/app/views/hyrax/users/_user.html.erb, /home/rails/rails_project/vendor/bundle/gems/hyrax-1.0.3/app/views/hyrax/dashboard/index.html.erb
> 
> Rails.root: /home/rails/hyrax
> 

this is the full trace:

> hyrax (1.0.3) app/search_builders/hyrax/abstract_type_relation.rb:28:in `delegated_attributes'
> active-fedora (11.4.0) lib/active_fedora/relation/finder_methods.rb:279:in `field_name_for'
> active-fedora (11.4.0) lib/active_fedora/relation/finder_methods.rb:272:in `condition_to_clauses'
> active-fedora (11.4.0) lib/active_fedora/relation/finder_methods.rb:266:in `block in create_query_from_hash'
> active-fedora (11.4.0) lib/active_fedora/relation/finder_methods.rb:266:in `each'
> active-fedora (11.4.0) lib/active_fedora/relation/finder_methods.rb:266:in `map'
> active-fedora (11.4.0) lib/active_fedora/relation/finder_methods.rb:266:in `create_query_from_hash'
> active-fedora (11.4.0) lib/active_fedora/relation/query_methods.rb:70:in `build_where'
> active-fedora (11.4.0) lib/active_fedora/relation/query_methods.rb:60:in `where!'
> active-fedora (11.4.0) lib/active_fedora/relation/query_methods.rb:56:in `where'
> hyrax (1.0.3) app/helpers/hyrax/dashboard_helper_behavior.rb:44:in `number_of_works'
> hyrax (1.0.3) app/views/hyrax/users/_vitals.html.erb:11:in `__home_rails_rails_project_vendor_bundle_gems_hyrax_______app_views_hyrax_users__vitals_html_erb__3430346791976618239_70210234342120'
> actionview (5.1.2) lib/action_view/template.rb:157:in `block in render'
> activesupport (5.1.2) lib/active_support/notifications.rb:168:in `instrument'
> actionview (5.1.2) lib/action_view/template.rb:352:in `instrument_render_template'
> actionview (5.1.2) lib/action_view/template.rb:155:in `render'
> actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
> actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
> activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
> actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
> actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
> actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:310:in `render'
> actionview (5.1.2) lib/action_view/renderer/renderer.rb:47:in `render_partial'
> actionview (5.1.2) lib/action_view/helpers/rendering_helper.rb:35:in `render'
> hyrax (1.0.3) app/views/hyrax/users/_user.html.erb:13:in `__home_rails_rails_project_vendor_bundle_gems_hyrax_______app_views_hyrax_users__user_html_erb__777666807893798853_45404400'
> actionview (5.1.2) lib/action_view/template.rb:157:in `block in render'
> activesupport (5.1.2) lib/active_support/notifications.rb:168:in `instrument'
> actionview (5.1.2) lib/action_view/template.rb:352:in `instrument_render_template'
> actionview (5.1.2) lib/action_view/template.rb:155:in `render'
> actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
> actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
> activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
> actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
> actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
> actionview (5.1.2) lib/action_view/renderer/partial_renderer.rb:310:in `render'
> actionview (5.1.2) lib/action_view/renderer/renderer.rb:47:in `render_partial'
> actionview (5.1.2) lib/action_view/helpers/rendering_helper.rb:35:in `render'
> hyrax (1.0.3) app/views/hyrax/dashboard/index.html.erb:7:in `block in __home_rails_rails_project_vendor_bundle_gems_hyrax_______app_views_hyrax_dashboard_index_html_erb__3580799334666174337_70210234029320'
> actionview (5.1.2) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
> actionview (5.1.2) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
> actionview (5.1.2) lib/action_view/helpers/capture_helper.rb:39:in `capture'
> actionview (5.1.2) lib/action_view/helpers/capture_helper.rb:153:in `content_for'
> hyrax (1.0.3) app/views/hyrax/dashboard/index.html.erb:6:in `__home_rails_rails_project_vendor_bundle_gems_hyrax_______app_views_hyrax_dashboard_index_html_erb__3580799334666174337_70210234029320'
> actionview (5.1.2) lib/action_view/template.rb:157:in `block in render'
> activesupport (5.1.2) lib/active_support/notifications.rb:168:in `instrument'
> actionview (5.1.2) lib/action_view/template.rb:352:in `instrument_render_template'
> actionview (5.1.2) lib/action_view/template.rb:155:in `render'
> actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
> actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
> activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
> actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
> actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
> actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
> actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
> actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
> actionview (5.1.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
> actionview (5.1.2) lib/action_view/renderer/renderer.rb:23:in `render'
> actionview (5.1.2) lib/action_view/rendering.rb:103:in `_render_template'
> actionpack (5.1.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
> actionview (5.1.2) lib/action_view/rendering.rb:83:in `render_to_body'
> actionpack (5.1.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
> actionpack (5.1.2) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
> actionpack (5.1.2) lib/abstract_controller/rendering.rb:24:in `render'
> actionpack (5.1.2) lib/action_controller/metal/rendering.rb:36:in `render'
> actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
> activesupport (5.1.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
> /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
> activesupport (5.1.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
> actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
> actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
> activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
> actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
> actionpack (5.1.2) lib/action_controller/metal/implicit_render.rb:33:in `default_render'
> actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
> actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
> actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
> actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
> actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
> actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
> activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
> actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
> actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
> actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
> activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
> actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
> actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
> activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
> actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
> actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
> actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
> actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
> actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
> actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
> actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
> railties (5.1.2) lib/rails/engine.rb:522:in `call'
> railties (5.1.2) lib/rails/railtie.rb:185:in `public_send'
> railties (5.1.2) lib/rails/railtie.rb:185:in `method_missing'
> actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
> actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
> actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
> warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
> warden (1.2.7) lib/warden/manager.rb:35:in `catch'
> warden (1.2.7) lib/warden/manager.rb:35:in `call'
> rack (2.0.3) lib/rack/etag.rb:25:in `call'
> rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
> rack (2.0.3) lib/rack/head.rb:12:in `call'
> rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
> rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
> active-fedora (11.4.0) lib/active_fedora/ldp_cache.rb:26:in `call'
> flipflop (2.3.1) lib/flipflop/feature_cache.rb:12:in `call'
> activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
> activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
> actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
> web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
> web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
> web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
> web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
> railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
> railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
> activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
> activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
> activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
> railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
> sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
> rack (2.0.3) lib/rack/method_override.rb:22:in `call'
> rack (2.0.3) lib/rack/runtime.rb:22:in `call'
> activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
> rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
> railties (5.1.2) lib/rails/engine.rb:522:in `call'
> puma (3.9.1) lib/puma/configuration.rb:224:in `call'
> puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
> puma (3.9.1) lib/puma/server.rb:435:in `process_client'
> puma (3.9.1) lib/puma/server.rb:299:in `block in run'
> puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by mjgiarlo** [comment]
@rodyoukai Have you created any work types yet? You must create at least one: https://github.com/samvera/hyrax/blob/v1.0.3/README.md#generate-a-work-type

**Comment by rodyoukai** [comment]
Sorry for late, I create de work types "Work" & "MovingImage" and i have this new issue:

>    def find_by!(*args) # :nodoc:
>         find_by(*args) || raise(RecordNotFound.new("Couldn't find #{name}", name))
>       end
> 
>       def initialize_generated_modules # :nodoc:

This is the Trace:

> activerecord (5.1.2) lib/active_record/core.rb:228:in `find_by!'
> hyrax (1.0.3) app/actors/hyrax/apply_permission_template_actor.rb:14:in `add_edit_users'
> hyrax (1.0.3) app/actors/hyrax/apply_permission_template_actor.rb:6:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/default_admin_set_actor.rb:11:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/interpret_visibility_actor.rb:85:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/abstract_actor.rb:26:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/abstract_actor.rb:26:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/attach_files_actor.rb:8:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/assign_representative_actor.rb:5:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/add_to_work_actor.rb:6:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/add_as_member_of_collections_actor.rb:6:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/create_with_files_actor.rb:6:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/create_with_remote_files_actor.rb:6:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/abstract_actor.rb:26:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/transactional_request.rb:9:in `block in create'
> activerecord (5.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
> activerecord (5.1.2) lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
> /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
> activerecord (5.1.2) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
> activerecord (5.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
> activerecord (5.1.2) lib/active_record/transactions.rb:210:in `transaction'
> hyrax (1.0.3) app/actors/hyrax/actors/transactional_request.rb:8:in `create'
> hyrax (1.0.3) app/actors/hyrax/actors/actor_stack.rb:23:in `create'
> hyrax (1.0.3) app/controllers/concerns/hyrax/curation_concern_controller.rb:45:in `create'
> actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
> actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
> actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
> actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
> activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
> actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
> actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
> actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
> activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
> activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
> actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
> actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
> activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
> actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
> actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
> actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
> actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
> actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
> actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
> actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
> actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
> warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
> warden (1.2.7) lib/warden/manager.rb:35:in `catch'
> warden (1.2.7) lib/warden/manager.rb:35:in `call'
> rack (2.0.3) lib/rack/etag.rb:25:in `call'
> rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
> rack (2.0.3) lib/rack/head.rb:12:in `call'
> rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
> rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
> active-fedora (11.4.0) lib/active_fedora/ldp_cache.rb:26:in `call'
> flipflop (2.3.1) lib/flipflop/feature_cache.rb:12:in `call'
> activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
> activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
> actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
> web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
> web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
> web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
> web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
> railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
> railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
> activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
> activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
> activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
> railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
> sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
> rack (2.0.3) lib/rack/method_override.rb:22:in `call'
> rack (2.0.3) lib/rack/runtime.rb:22:in `call'
> activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
> actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
> rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
> railties (5.1.2) lib/rails/engine.rb:522:in `call'
> puma (3.9.1) lib/puma/configuration.rb:224:in `call'
> puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
> puma (3.9.1) lib/puma/server.rb:435:in `process_client'
> puma (3.9.1) lib/puma/server.rb:299:in `block in run'
> puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
> Request
> 
> Parameters:
> 
> {"utf8"=>"✓",
>  "authenticity_token"=>"UAckmNCv1xlMNM6Nav6PHyvpRCjMx2+NRDi+DE/rejHrju6xfmbnvYus4zfTd9IsZE6eq/c46Pa+ZnifdhEVUw==",
>  "work"=>
>   {"title"=>["asd"],
>    "creator"=>["asd"],
>    "keyword"=>["sadasdfsd"],
>    "rights"=>["http://creativecommons.org/publicdomain/mark/1.0/"],
>    "contributor"=>[""],
>    "description"=>[""],
>    "publisher"=>[""],
>    "date_created"=>[""],
>    "subject"=>[""],
>    "language"=>[""],
>    "identifier"=>[""],
>    "based_near"=>[""],
>    "related_url"=>[""],
>    "source"=>[""],
>    "resource_type"=>[""],
>    "member_of_collection_ids"=>[""],
>    "visibility"=>"open",
>    "visibility_during_embargo"=>"restricted",
>    "embargo_release_date"=>"2017-08-09",
>    "visibility_after_embargo"=>"open",
>    "visibility_during_lease"=>"open",
>    "lease_expiration_date"=>"2017-08-09",
>    "visibility_after_lease"=>"restricted"},
>  "uploaded_files"=>["3"],
>  "new_user_name_skel"=>"",
>  "new_user_permission_skel"=>"none",
>  "new_group_name_skel"=>"Select a group",
>  "new_group_permission_skel"=>"none",
>  "agreement"=>"1",
>  "locale"=>"en"}

**Comment by mjgiarlo** [comment]
@rodyoukai It looks like a permission template is missing. Have you created one or more administrative sets? You can try selecting a different administrative set in the "Relationships" tab, assuming they've been created.

**Comment by rodyoukai** [comment]
Thanks, i solved the issue with your advise...
Regards...

**Comment by mjgiarlo** [comment]
Great
