### ISSUE TITLE
Notifications page - sort-by-date should be numeric

### ISSUE THREAD

**Issue by darrenleeweber** [samvera/hyrax#1403]
### Descriptive summary

master branch as on July-2017

### Rationale

`/notifications?locale=en` lists items with an option to sort-by-date DESC but the items appear out of order because they are sorted alphanumerically using the human readable values instead of an integer (date from the epoch)

### Actual behavior

![screen shot 2017-07-31 at 3 48 33 pm](https://user-images.githubusercontent.com/240623/28802097-a44b3c48-7609-11e7-929a-23c81eb60fbd.png)

### Steps to reproduce the behavior

1. Do something to create notifications and view them to click on the `Date` column so it sorts the items in descending order (or it should)

**Comment by mjgiarlo** [comment]
This is being rendered via jquery-datatables, so this may require Javascript work (and testing, via jasmine). So said @jcoyne
