### ISSUE TITLE
"Next" and "Previous" buttons behave improperly on catalog page

### ISSUE THREAD

**Issue by 13miciunasl** [samvera/hyrax#1407]
Clicking 'previous' on the first page of the catalog will simply refresh the page. Clicking 'next' on the last page of the catalog will bring you to an empty catalog page, and allows you to page through blank pages indefinitely.

Hyrax 2.0.0

### Expected behavior
'Previous' button should be unusable on the first page of the catalog. 'Next' button should be unusable on the last page of the catalog.

**Comment by conorom** [comment]
Same as this?
https://github.com/mlibrary/heliotrope/issues/1122

**Comment by VivianChu** [comment]
@13miciunasl - "Next" and "Previous" buttons behave properly on my local hyrax.  Could you try to check those buttons again?  Attached are my screen shots 

![previous_button](https://user-images.githubusercontent.com/1864660/36233901-0d6b215a-119d-11e8-803c-3137d29a9826.png)
![next_button](https://user-images.githubusercontent.com/1864660/36233902-0d8b0880-119d-11e8-9416-1e9e1e9c2a5d.png)

**Comment by no-reply** [comment]
This also seems to work correctly on both nurax.curationexperts.com and tenejo.curationexperts.com.
