### ISSUE TITLE
/downloads request you don't have permission for gives you the default icon

### ISSUE THREAD

**Issue by jrochkind** [samvera/hyrax#1410]
If browser requests a /downloads link that the user-agent isn't auth'd to see (say, a non-public image when you are not logged in), instead of a 403 the default icon is delivered. 

One problem with this is if you are setting caching headers, say far-future caching headers as probably makes sense for image assets, the user-agent (or any intermediate caches) now caches that default icon for that URL, when that is not the right thing to cache far-future for that URL. Now you've got cache issues.

**Comment by lsitu** [comment]
@jrochkind Do you know about the status of this ticket?
