### ISSUE TITLE
Sipity entities require global-ID but AdminSet does not have one

### ISSUE THREAD

**Issue by dazza-codes** [samvera/hyrax#1411]
### Descriptive summary

The Sipity workflow permissions use an entity as a proxy for works etc. and, in doing so, they keep a reference to the global-id for the object.  To use AdminSet with Sipity, it needs a global-id.

### Related work

This is related to investigation work on https://github.com/samvera/hyrax/issues/936

**Comment by rjkati** [comment]
Based on comments in linked PR, it does not seem that this change is needed, Please re-open if this is not the case.
