### ISSUE TITLE
dashboard list views jump around when some are populated but others are not

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#142]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hackmastera](https://github.com/hackmastera)**
_Tuesday Aug 09, 2016 at 13:59 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2416_

----

### Descriptive summary

Sufia 7. When, e.g., I have added works but not collections.
### Expected behavior

When I click from 'My works' to 'my collections' I expect the tabs to stay in the same place.
### Actual behavior

The facet list disappears and the main content area, including the tabs, jump left to fill the empty space.
### Steps to reproduce the behavior
1. Add a work
2. View 'my works'
3. click tab to view 'my collections'

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Dec 20, 2016 at 22:01 GMT_

----

@hackmastera I'm trying to decide whether this should be a 7.3.0 blocker, or bounce over to Hyrax's backlog. Do you have leanings? How fired up are you to work on this one?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hackmastera](https://github.com/hackmastera)**
_Wednesday Dec 21, 2016 at 01:36 GMT_

----

Okay to bounce; have more pressing issues over here for sure. Thanks!

**Comment by mcdowney** [comment]
Closing as no longer relevant
