### ISSUE TITLE
Notes on Hyrax::Group

### ISSUE THREAD

**Issue by darrenleeweber** [samvera/hyrax#1425]
`Hyrax::Group` is about as simple as they come and _actually_ it looks like it’s really a `Sipity::Group` because all the methods on it are _all_ about Sipity stuff.

AFAICT, there’s no way to use that class to find all the members of the group.

Also, the `Hyrax::Group` has no contact details, like an email distribution list or some kind of generic support contact details for the group.

Some design work to clarify the purpose of this class would be useful.  That is, if it's meant to represent an organization that has contact details and members, the class should have additional attributes for contact details and a way to manage the members of the group.  If it is simply a container for a group of users, it may not need any attributes other than a list of members of the group and methods to manipulate that list.

**Comment by mjgiarlo** [comment]
Hyrax groups will be worked on by Notre Dame. This is unscheduled but coming soon.
