### ISSUE TITLE
Collections: Update public landing page to include branding and other UI recommendations

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1428]
### Descriptive summary

Update code to implement the public show view for a single collection.

### Rationale

See model issue for rationale.

### Implementation

**Edit Files:** 
* [app/views/hyrax/collections/show.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections/show.html.erb)
* other files in [app/views/hyrax/collections](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections) directory

Will need to...
- [ ] modify show files under `app/views/hyrax/collections`
- [x] UI
  - [x] if exists, show banner image 
  - [x] if exists, show all logo images
  - [x] include descriptive metadata according to presenter
  - [x] include list of member items
- [x] update presenter controlling the display of metadata if needed

The primary checklist for the UI is the mockup below.

#### SPECIAL NOTE on Admin Sets:

For the initial implementaiton, the Admin Set underlying code will not change.  But to a user, the Admin Set will appear to be a collection.

To make the illusion happen...
* At least initially, the show page for admin sets will NOT change.  We can revisit if time allows.

### Mockups

There are a handful of mockups related to the public collection show page. 

#### Minimal description and branding

This example assumes the collection manager has not specified a banner image for the collection and otherwise has done minimal description. 

![collection-show-minimal-description-branding](https://user-images.githubusercontent.com/101482/28985891-898e7e48-7919-11e7-9e63-97e574bfaadc.png)

#### With more branding
In this version the collection manager has done more branding. This also includes the edit buttons that would be displaued if the user is a manager or depositor for the collection.

![public-collection-show-edit-actions](https://user-images.githubusercontent.com/101482/28986121-83d8019e-791a-11e7-91bd-f6c5bfbfce33.png)

#### Collection items include sub-collections
If the collection type allows nesting, there could be sub-collections in the given collection, which need to be distinguished from works that are part of the collection.

![public-collection-show-works-subcollections](https://user-images.githubusercontent.com/101482/28986263-0bd82f6a-791b-11e7-9cdd-abc3097fd223.png)

#### Collection show page for sub-collection
If the user drills down into a sub-collection item in a collection, the show page is very similar but we need to give the user a clear and easy way to return to the parent collection. (This sub-collection doesn't have a banner image specified, but it could.)

![public-collection-show-sub-collection](https://user-images.githubusercontent.com/101482/28986324-55a89cf6-791b-11e7-9678-5f0a16ab409e.png)

### Directly Related Work

#1376 Collections: Create branding metadata partial of the new/edit form
#1679 Collections: Remove alt text for banner on edit form Branding tab

### Related work

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index            | #1417 |
| View - Show - Admin       | #1427 |
| View - Show - Landing    | (this issue) |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by laritakr** [comment]
This will overlap extensively with the dashboard show page from issue #1427

**Comment by elrayle** [comment]
To add branding images:
* login 
* self register
* create a collection: Dashboard -> Collections -> New Collection -> set title -> Update Collection
* edit the new collection (likely you stayed in edit mode after the save)
* goto Branding tab
* click Choose File button under banner to add a banner image (only one allowed)
* click Choose File button under logo to add a logo image (can add multiple)
* click Update Collection to save
* click Cancel to go to the collection show page

This should go to the Admin Show page, but it may have gone directly to the public landing show page.  If you see a left hand menu, you are on the admin show page.  If not, you are on the public landing show page.

If on the admin show page, click `Public view of Collection` under thumbnail to go to the public landing show page.

**Comment by elrayle** [comment]
Fixed by PR #2072
