### ISSUE TITLE
Search for "Child Works" fails in Hyrax 1.0.3

### ISSUE THREAD

**Issue by whunter** [samvera/hyrax#1429]
### Descriptive summary

In Hyrax (1.0.3) when searching for works in the Relationships tab of a work edit page using the AJAX widget https://github.com/samvera/hyrax/blob/1-0-stable/app/views/hyrax/base/_find_work_widget.html.erb
the search fails and the application throws the 500 Internal Server Error linked here:
https://gist.github.com/whunter/52358910ac2547d87797fcd5ec287dbb

### Expected behavior

App should return results of search query

### Actual behavior

Search fails because of server error in AJAX request

### Steps to reproduce the behavior

1. Navigate to the edit page of a work
2. Click on "Relationships" tab
3. Enter at least two characters in the "Child Work" text box.

**Comment by mjgiarlo** [comment]
Closed by #1430  (right, @whunter?)

**Comment by whunter** [comment]
@mjgiarlo @jcoyne Thank you all for your help on this
