### ISSUE TITLE
'Type of work' facet on My Collections page contains single facet 'Collection'

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#143]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hackmastera](https://github.com/hackmastera)**
_Tuesday Aug 09, 2016 at 14:04 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2417_

----

### Descriptive summary

Sufia 7.
### Expected behavior

Either not have this facet or facet based on the types of works within the collections.
### Actual behavior

Looks like this facet will always only have one possible value in this view.
### Steps to reproduce the behavior
1. Create collection/s
2. go to 'my collections' list.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Tuesday Aug 09, 2016 at 16:43 GMT_

----

@hackmastera I just put a similar issue unto ScholarSphere: https://github.com/psu-stewardship/scholarsphere/issues/351

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Aug 09, 2016 at 18:16 GMT_

----

So, 'Type of work' facet should only display on My Works page. Good call.

**Comment by vantuyls** [comment]
this issue has been resolved. Type of Work facet no longer appears on Collection pages
