### ISSUE TITLE
Metadata Edit Permissions

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#144]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Tuesday Aug 09, 2016 at 17:07 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2422_

----

If my permissions allow, I need to be able to edit all (?) metadata fields as part of a review process. Example: Library staff member needs to alter metadata for a dissertation submission to correct spelling mistakes or assign LCSH

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hannahfrost"><img src="https://avatars.githubusercontent.com/u/1801076?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hannahfrost](https://github.com/hannahfrost)**
_Monday Aug 15, 2016 at 21:56 GMT_

----

I agree all metadata fields should be editable by a Reviewer user.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hannahfrost"><img src="https://avatars.githubusercontent.com/u/1801076?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hannahfrost](https://github.com/hannahfrost)**
_Tuesday Aug 16, 2016 at 16:43 GMT_

----

I should add that in the Hydra-in-a-Box repository, we'd like to make it so a collection manager can configure the editability of select metadata fields by a depositor in a given collection. The mediated deposit of student works like theses and dissertations is a use case for that kind of configurable metadata editing functionality.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 23:27 GMT_

----

Work on this as part of 1+-step workflow.

**Comment by mjgiarlo** [comment]
How high of a priority is this ticket? @vantuyls @hannahfrost @scholarworks

**Comment by vantuyls** [comment]
i think this is already possible under the current Hyrax. if i deposit into a one step mediation workflow, the reviewer can edit the item. Can someone else confirm and close?

**Comment by mjgiarlo** [comment]
@vantuyls I just checked and this is not currently implemented; reviewers are not granted edit access.

**Comment by mcdowney** [comment]
We're closing this in favor of writing a new story about documenting Workflow roles. Admin set manager can currently function as reviewer. Will write a story to assess need for this kind of functionality.
