### ISSUE TITLE
Remove custom accept_confirm implementation

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1445]
#1436 changed our feature specs such that they now use Selenium with headless Chrome instead. Using Capybara with this stack does not yet support the `#accept_confirm` method (and related methods) for interacting with alert/confirm browser dialogs. We've added a custom handler for this in the meantime at ` spec/support/features/confirmation.rb` -- when this is supported in the Capybara-atop-Selenium-with-Chrome-driver stack, remove this custom code.

**Comment by mjgiarlo** [comment]
The upstream ticket is https://github.com/teamcapybara/capybara/issues/1860

**Comment by twalpole** [comment]
@mjgiarlo The latest few versions of Capybara already handle the `accept_confirm`and related methods with chrome headless, so the patch you have in spec/support/features/confirmation.rb should not be necessary.  The latest version of Capybara also adds a registered driver for chrome headless, so you should be able to just specify `Capybara.javascript_driver = :selenium_chrome_headless` and not need to register your own driver.
