### ISSUE TITLE
Admin Dashboard: Administrator Can Set Permissions and Roles for All Users

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#145]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Tuesday Aug 09, 2016 at 17:16 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2425_

----

As an administrator, I need top-level access to user management, so I can control and manage user accounts and functions: restrict access to user list to administrators; search all users; view all users; sort all users by name; edit all users; delete all users; login as a user and perform all that user’s tasks

This is an admin dashboard feature. Suggest punting this over to the admin dash team for the September sprint at Penn State.
# Past Discussion

Roles & Permissions - As an administrator, I need to be able to create accounts for non institutional users (e.g. those not logged into the system via central authentication) and assign permissions for them

Comments on this User Story:
Mike Giarlo: This is a prerequisite to doing mediated deposit in Sufia. Seems like low-hanging fruit.

Richard Green: ...though, of course, this may be forbidden by institutional policy?

Steven Van Tuyl: True.

Michael Giarlo: Yes, of course. I also see this as a latter-phase story.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Tuesday Aug 09, 2016 at 17:19 GMT_

----

This was initially two user stories, one related to administrators setting permissions and the second for setting accounts for non-institutional users.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jrgriffiniii"><img src="https://avatars.githubusercontent.com/u/1443986?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jrgriffiniii](https://github.com/jrgriffiniii)**
_Wednesday Aug 31, 2016 at 20:13 GMT_

----

There may well be cases in which defining roles (with respect to user groups) will be tightly coupled with identity management systems local to the institutions (e. g. LDAP).  This could prove to render generalizing this feature more difficult.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Aug 31, 2016 at 21:00 GMT_

----

Thank you, @jrgriffiniii!

**Comment by no-reply** [comment]
cc: @samvera/hyrax-repo-managers is this still an outstanding issue?

**Comment by julesies** [comment]
this sounds like a big ticket and maybe written before we put a lot of work into admin set permissions? We can view, search, all users, but we can only edit permissions on a collection-based approach (for non-admin user). I would personally recommend to close.

**Comment by mcdowney** [comment]
Closing pending better specifications around permissions
