### ISSUE TITLE
Verify i18n update procedure

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1451]
Work documenting i18n updates began with https://github.com/samvera/hyrax/issues/1276 and we should now improve that documentation by having someone else run through the process. I suggest pairing with me on this, setting aside an hour or so.

**Comment by darrenleeweber** [comment]
I've asked HelpSU to advise us about Stanford access to the google translate API.  They responded to this request:

- incident INC00091349
- https://stanford.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=07b7dde34f3b36c82c3860001310c7c8%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true

```
Short description:      Use the google translate API service

Hi Darren,

You should have access to cloud APIs; however, you'll need further access to create projects. You'll need to contact Hans Jacobsen for access.

If you have any questions, please contact me.

Thanks,
Jason
```

**Comment by darrenleeweber** [comment]
I've sent an email to Hans Jacobson to request further assistance with the account access.  Stanford who has a public listing for Hans, i.e.

Hans Jacobsen
- hans.jacobsen@stanford.edu 
- SOM IT Director, Data Center
- (650) 723-7360
