### ISSUE TITLE
Collection Types: add helper methods to check settings in model

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1452]
### Descriptive summary

Add helper methods that allow checking of binary settings.

### Rationale

See model for rationale.

### Implementation

**File:** [/app/models/hyrax/collection_type.rb](https://github.com/samvera/hyrax/blob/master/app/models/hyrax/collection_type.rb)

Rename database columns such that we get the ? methods for free because these are all boolean variables.

| new name | old name | 
| ------------ | ------------ |
| nestable | :nestable |
| discoverable | :discovery |
| sharable | :sharing |
| allow_multiple_membership | :multiple_membership |
| require_membership | :require_membership |
| assigns_workflow | :workflow |
| assigns_visibility | :visibility |

### Related work

PR #1447 Add model for Collection Types
Issue #1343 Collection Types: Create model for collection types

**Comment by jeremyf** [comment]
We get the `?` methods for free based on the column name. I think we should rename the column names in the migration to reflect the identified helper methods names. Thoughts @elrayle

**Comment by randalldfloyd** [comment]
What's the right way to fix this - just change the existing migration or write a new change migration?  For a model that hasn't even made its way to master yet is a new migration creating too much DB history?

**Comment by jeremyf** [comment]
I favor writing migrations instead of updating existing ones. Even if there is too much database history it's a typically cleaner procedure for everyone up and down stream.
