### ISSUE TITLE
QA for pending review notifications

### ISSUE THREAD

**Issue by darrenleeweber** [samvera/hyrax#1455]
### Descriptive summary

Confirm that notifications for pending reviews are sent to the managers for an AdminSet and cc to the depositor.

### Steps to reproduce the behavior

Some related workflow notes are in https://github.com/samvera/hyrax/issues/936#issuecomment-319154569

### Related work

A bug in notifications was reported in https://github.com/samvera/hyrax/issues/936

The notification was fixed in https://github.com/samvera/hyrax/pull/1415, but it was merged before a complete QA was done to confirm the behavior is correct.

**Comment by darrenleeweber** [comment]
- AdminSet-A has:
  - managerA
  - depositorA

- AdminSet-B has:
  - managerB
  - depositorB

- depositorA creates a new work
  - depositorA got a notification about the review pending
  - managerA _did not_ get a notification about the review pending
  - managerA got a new item in the `Review Submissions`

**Comment by darrenleeweber** [comment]
@mjgiarlo - looks like the notifications QA is a partial fail, it’s gone too far the other way for managers/admins; although the notifications are not perfect, the functionality for review/approval remain the same, so the app is sorta functional, but could be better.

**Comment by darrenleeweber** [comment]
It's possible that the data structure returned at [1] needs to be modified to match the expected data structure in the call stack, because the values in this data structure seem to be OK

[1] https://github.com/samvera/hyrax/blob/master/app/services/hyrax/workflow/notification_service.rb#L54-L57

**Comment by mjgiarlo** [comment]
@darrenleeweber Good call on using string keys instead of symbols: https://github.com/samvera/hyrax/blob/master/app/services/hyrax/workflow/abstract_notification.rb#L76

**Comment by vantuyls** [comment]
@luisgreg99 did you run into any of these issues with our workflow notifications work? if so, chime in here!

**Comment by mjgiarlo** [comment]
Work in progress: https://github.com/samvera/hyrax/pull/1465

Notifications are the tip of the iceberg here. Workflow roles (when and how they are assigned) are a mess, and could use more discussion. I suggest we defer this until the Notre Dame team have had a chance to start making improvements.
