### ISSUE TITLE
Move i18n collection_type to collection_types

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1457]
### Descriptive summary

i18n translations were entered under two different starting points of collection_type: and collection_types:  They need to be consolidated.

### Rationale

Provide a single point in translations for collection type CRUD.

### Effected Files

* [config/locales/hyrax.en.yml](https://github.com/samvera/hyrax/blob/collections-sprint/config/locales/hyrax.en.yml)
  * merge all entries under collection_type into collection_types

It doesn't appear that these labels are in use yet.  So there is no other work to be done.  

@hortongn Can you confirm?  These were added as part of PR #1446.

### Related work

PR #1446 Add Collection Types to Admin Menu

**Comment by elrayle** [comment]
@kdid pointed out that for lazy-load to work, the entry needs to be plural instead of singular.  The label entries need to match the directory structure of the views.

For more information on lazy-load of translations, see [Looking up translations](http://guides.rubyonrails.org/i18n.html#looking-up-translations) in section 4.1.4.

**Comment by adamjarling** [comment]
@elrayle I'm doing a global project search for usages of, say `collection_type.form.metadata.description` or any translation references to the singular `collection_type`, but not finding anything.  Does this seem right?  Would items have been added to the hyrax.en.yml file in advance of being used?   Just making sure I don't break anything...
