### ISSUE TITLE
Audio icon is suspiciously similar to the old blue document

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#146]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cam156](https://github.com/cam156)**
_Tuesday Aug 09, 2016 at 17:21 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2427_

----

### Descriptive summary

In Sufia 7 most of the Blue documents have been removed.  I noticed the audio one is still around (or it looks the same)

In Sufia 7
![screen shot 2016-08-09 at 1 18 54 pm](https://cloud.githubusercontent.com/assets/1599081/17526147/0bf040e4-5e34-11e6-8f09-4288dc043fbb.png)

In Sufia 6
![screen shot 2016-08-09 at 1 15 14 pm](https://cloud.githubusercontent.com/assets/1599081/17526155/11981030-5e34-11e6-8de3-16ba19fe1548.png)

The entire work page in Sufia 7

![screen shot 2016-08-09 at 1 19 03 pm](https://cloud.githubusercontent.com/assets/1599081/17526177/2bfd57e6-5e34-11e6-8479-70e0c3b68d1b.png)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Aug 09, 2016 at 18:18 GMT_

----

@projecthydra/sufia-code-reviewers @projecthydra/sufia-ui-ux-advisors how do you folks think we should handle the default icon for audio items?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mtribone"><img src="https://avatars.githubusercontent.com/u/4163828?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mtribone](https://github.com/mtribone)**
_Tuesday Aug 09, 2016 at 18:25 GMT_

----

We should find an appropriate font awesome icon like we use for works and collections.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hackmastera](https://github.com/hackmastera)**
_Tuesday Aug 09, 2016 at 18:26 GMT_

----

Is it not a work? We should either use a different icon for each resource type or the same for everything.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Aug 09, 2016 at 18:27 GMT_

----

It is a work, @hackmastera, so yeah, mayhaps we should use the work icon.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hackmastera](https://github.com/hackmastera)**
_Tuesday Aug 09, 2016 at 18:28 GMT_

----

oh i get it there's no way to ever generate a unique icon from the file itself.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Aug 09, 2016 at 18:29 GMT_

----

That's true. One option we have is to use the support we already have for selecting a thumbnail from one of the work's file sets. (There's a dropdown in the work edit form for this.) And, barring that, use the default work icon?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mtribone"><img src="https://avatars.githubusercontent.com/u/4163828?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mtribone](https://github.com/mtribone)**
_Tuesday Aug 09, 2016 at 18:38 GMT_

----

If I recall correctly, I swapped out the default blue icon with a font awesome icon. I don't _believe_ we ever had icons for all of the resource types? Agree with @hackmastera about either one for each resource type or the same for everything.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Aug 09, 2016 at 18:56 GMT_

----

:+1: to same for everything.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Aug 09, 2016 at 19:00 GMT_

----

I believe the special-casing for audio comes from the following CC helper:

https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/thumbnail_path_service.rb

**Comment by no-reply** [comment]
I think this is closed, and that content icons are now normalized.
