### ISSUE TITLE
_work_action_menu duplication, drift, decay

### ISSUE THREAD

**Issue by atz** [samvera/hyrax#1462]
Why do we have these two obviously copied/forked template partials?

- [app/views/hyrax/collections/_work_action_menu.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections/_work_action_menu.html.erb)
- [app/views/hyrax/my/_work_action_menu.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/_work_action_menu.html.erb)

One received maintenance attention (i18n, `if can? :transfer` check, actual tests, etc.).  The other did not.

The only *intended* difference is the addition of `button_for_remove_from_collection`, which certainly doesn't require an entirely separate template.

IF these are both still in use, they should be consolidated.

**Comment by jcoyne** [comment]
I think it's fairly common to customize these partials in divergent directions, so I'm for keeping them distinct.

**Comment by mjgiarlo** [comment]
Yes, I believe ScholarSphere customizes one of these (the `/collections/` one) and not the other.

**Comment by atz** [comment]
Then we still should consolidate them and just have the one partial invoke the other.  That allows consumers enough hook to target their override without us duplicating maintenance burden.

**Comment by no-reply** [comment]
I think we should pursue @atz's proposal.

**Comment by rjkati** [comment]
[app/views/hyrax/collections/_work_action_menu.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/collections/_work_action_menu.html.erb) returns 404. Closing as it seems like the consolidation work was completed.
