### ISSUE TITLE
Collection Types: Update Hyrax-generation process to create a collection type for User Collections

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1485]
### Descriptive summary

Create an editable collection type for User Collections that has initial values matching the current behavior of Collections in Hyrax.

### Rationale

There is an existing implementation of the Collections concept that is generally referred to as User Collections.  By creating a User Collection collection type with default behaviors matching the current Hyrax implementation, we provide a migration path for existing applications that use collections.  Any collection that does not have a collection type assigned will be assigned the User Collection the first time it is accessed.  This removes the need for an upfront migration process for collection types.

See model issue for collection types rationale.

### Implementation

**File:** (lib/generators/hyrax/install_generator.rb)[https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/install_generator.rb]

Write a generator that...
- [x] creates a new collection type named: User Collections with a brief description of what an User Collection
- [x] save the collection type id in a globally accessible structure (most likely ENV variable, but maybe Hyrax has its own way of handling this - NEEDS INVESTIGATION)
- [x] assign default settings that correspond to the expected behaviors and restrictions of the current implementation for collections
  - [x] nestable=false
  - [x] discovery=true
  - [x] sharing=true
  - [x] multiple_membership=true
  - [x] require_membership=false
  - [x] workflow=false
  - [x] visibility=false
- [ ] assign default settings for participants
  - [ ] collection_mangers -> group: admins
  - [ ] collection_creators -> group: registered users

QUESTION: Is the group admin or admins?

### Related work

| Collection Types feature | Issue |
| ------------------------ | ----- |
| Admin Set Generator      | #1342 |
| User Collection Generator | (this issue) |
| Routes                   | #1347 |
| Controller               | #1341 |
| Model                    | #1343 |
| View - Index             | #1349 |
| View -  New/Edit         | #1348 |
| Partial -  Description   | #1344 |
| Partial -  Settings      | #1346 |
| Partial -  Participants  | #1345 |

**Comment by randalldfloyd** [comment]
@elrayle After browsing all of Hyrax for various patterns that have been employed to persist things on install, I am considering following the pattern used for creating a default admin set.  I like the way it centers around a `find_or_create_default` method in the model itself which can be called from anywhere (rake or generator) but without having too much code in generators/rake tasks that are hard to test.  This could potentially even be called from other services/controllers at run-time in the application should the install fail to create a default collection type.   I would also like to make the the default ID configurable in the hyrax initializer to satisfy the second requirement (making an ID globally available.)  Any objections to this design?

**Comment by randalldfloyd** [comment]
@elrayle BTW, regarding the second requirement (saving the default ID in a globally accessible place): because of the way I chose to implement this, the `machine_id` that will used to create the default collection type would always be available as `Hyrax::CollectionType::DEFAULT_ID`.   Is that sufficient? Even if in later iterations that constant were to be set with a value it got from somewhere (i.e. configurable via the Hyrax initializer) that would still work.

**Comment by elrayle** [comment]
Remaining Work will be addressed in issues:
* Issue #1486 - PR #1521 assign default user collection type to any existing collection that does not have a type already assigned
* Issue #1532 Add default values for participants
