### ISSUE TITLE
Collections: Set the collection_type instance variable for the Collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1486]
### Descriptive summary

All instances, new and resumed, should have an instance of Collection Type in the collection_type instance variable of the collection object based on the value of collection_type_gid property.  If the collection_type_gid property is nil, set the collection type to the default User Collection.

### Rationale

Keeping the instance of the Collection Type in the collection object allows for delegation of settings methods to the collection type.

Collection type may not be assigned for any collections that existed prior to this implementation.  There is an existing implementation of the Collections concept that is generally referred to as User Collections.  A default collection type of User Collection is being created by Issue #1485.  Any collection that does not have a collection type assigned will be assigned the User Collection the first time it is accessed.  This removes the need for an upfront migration process for collection types.
 
This work is expanding the existing Collections implementation to accommodate Collection Types and the new [requirements](https://wiki.duraspace.org/x/g402BQ) that are part of the [Collection Extensions](https://wiki.duraspace.org/x/5JM2BQ) work.

### Implementation

**Files:** 
* [app/models/concerns/hyrax/collection_behavior.rb](https://github.com/samvera/hyrax/blob/collections-sprint/app/models/concerns/hyrax/collection_behavior.rb)
* [app/controllers/concerns/hyrax/collections_controller_behavior.rb](https://github.com/samvera/hyrax/blob/collections-sprint/app/controllers/concerns/hyrax/collections_controller_behavior.rb)
* [app/models/hyrax/collection_type.rb](https://github.com/samvera/hyrax/blob/collections-sprint/app/models/hyrax/collection_type.rb)

When a collection is read back in, an instance of the collection_type is automatically set in the collection_type instance variable from the gid stored in the collection_type_gid property.  If the gid is nil, then use the default User Collection collection type created by Issue #1485.

#### In [collections controller](https://github.com/samvera/hyrax/blob/collections-sprint/app/controllers/concerns/hyrax/collections_controller_behavior.rb):

For all actions...
```
before_action :load_collection_type_instance
```

With the method definition...
```
      def load_collection_type
        # TODO: For new collections, the type comes from the modal OR uses the one and only one type the user can create.  This TODO will be removed when the processing for modals is in place.
        if @collection.collection_type_gid.nil?
          # gid will only be nil for non-migrated collections created before collection types existed
          @collection.collection_type = Hyrax::CollectionType.default_type
          @collection.collection_type_gid = @collection.collection_type.gid
          # TODO: Question -- should we save here to persist the gid setting?
        else
          @collection.collection_type = Hyrax::CollectionType.find_by(machine_id: GlobalID.new(RDF::URI.new(@collection.collection_type_gid)).model_id)
        end
      end
```

#### In [collection_type model](https://github.com/samvera/hyrax/blob/collections-sprint/app/models/hyrax/collection_type.rb):

```
      def self.default_type
        # TODO Return generated User Collection.  See Issue #1485.
        find_by_machine_id('user_collection')
      end

      def self.admin_set_type
        # TODO Return generated Admin Set.  See Issue #1342.
        find_by_machine_id('admin_set')
      end

      def self.find_by_machine_id
        # TODO Create an instance of CollectionTypes given the machine_id
      end

      def admin_set?
        machine_id == 'admin_set'
      end
```

NOTE: Not sure we need a method to instantiate the admin_set collection_type. We do need a way to tell if a collection_type is the admin_set.

### Related work

Generator for User Collection #1485 
Generator for Admin Set #1342 

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index            | #1417 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by elrayle** [comment]
Not sure we need a method to instantiate the admin_set collection_type.  We do need a way to tell if a collection_type is the admin_set.

**Comment by elrayle** [comment]
This should update [app/views/hyrax/admin/collection_types/index.html.erb](https://github.com/samvera/hyrax/blob/collections-sprint/app/views/hyrax/admin/collection_types/index.html.erb#L39) to use the `admin_set?` method.

This appears to be complete except for the special processing for AdminSets.  That portion is dependent on Issue #1486 which defines a method to check if the collection type is the admin set.

Right now the check is...
```
<% if collection_type.machine_id != 'admin_set' %>
```
and can become...
```
<% if collection_type.admin_set? %>
```

**Comment by respinos** [comment]
`Hyrax::CollectionType.gid` returns a `URI::GID.build...`, but trying to assign this to the `Collection.collection_type_gid` yields

```ActiveTriples::Relation::ValueError: value must be an RDF URI, Node, Literal, or a valid datatype. See RDF::Literal. You provided #<URI::GID gid://internal/hyrax-collectiontype/1>```.

First guess would be to do change `load_collection_type_instance` to

```
    def load_collection_type_instance
        return unless @collection # may not be necessary
        if @collection.collection_type_gid.nil?
          @collection.collection_type = Hyrax::CollectionType.default_type
          @collection.collection_type_gid = RDF::URI.new(@collection.collection_type.gid)
        else
          @collection.collection_type = Hyrax::CollectionType.find_by(machine_id: GlobalID.new(@collection.collection_type_gid).model_id)
        end
      end
```

?

**Comment by elrayle** [comment]
Do you have a branch?  Do you know which line is causing the problem?

**Comment by respinos** [comment]
https://github.com/samvera/hyrax/tree/1486_collection_type_instance_variable -- I made the changes so the controller spec passes (e.g. wrapping the collection_type.gid with RDF::URI)

**Comment by respinos** [comment]
(Oh yeah, `RDF::URI` totally doesn't work. `Collection.collection_type_gid` becomes an `ActiveTriples::Resource`, which is enumerable.)

**Comment by respinos** [comment]
@elrayle - I changed things to cast the GID to a string, which makes all the tests succeed. That seems ... odd for RDF, though.

**Comment by elrayle** [comment]
Remaining questions being addressed by:
* #1528 Looks at answering the question of whether it is sufficient for gid to be treated as a string in Fedora and in the Collections object.  
* #TBD  Need to prevent collection_type_gid property in Collection model from being changed once it is assigned.
