### ISSUE TITLE
Implement object states

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#149]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Aug 10, 2016 at 17:54 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2452_

----

At the Hydra Developer Congress in May 2016, the community discussed a shared need to support object “states” in our applications. The use cases we talked about included: 
- “Draft” or unpublished objects, such as might be created as the first step in a mediated deposit workflow 
- “Soft-deleting” or “tombstoning” objects, leaving behind a tombstone with information which could be surfaced in a user interface such as descriptive metadata (to provide context around what was deleted), a date of deletion, and a record of who deleted the object and for what reason. 

The ability to record object state was available as a feature in Fedora 3, which provided three states: active, inactive, and deleted. The sense of the room was that implementing this in Fedora 4 could be done using sensible, pre-defined predicates and classes. The [Fedora Resource Status Ontology](https://github.com/fcrepo4-exts/fcrepo-extra-ontologies/blob/master/ObjState.rdf) defines the `http://fedora.info/definitions/1/0/access/ObjState#objState` predicate (where the domain is Fedora resources) and the following applicable classes as value objects:
- [active](http://fedora.info/definitions/1/0/access/ObjState#active) -- assumed (at the moment) for all objects deposited via Sufia and other Fedora 4-based Hydra applications
- [inactive](http://fedora.info/definitions/1/0/access/ObjState#inactive) -- could be used for objects deposited via an approval workflow, until they are approved
- [deleted](http://fedora.info/definitions/1/0/access/ObjState#deleted) -- could be used for soft-deleting objects

One potential complication we discussed is how far we’d want to take the notion of “draft” or inactive objects. For instance, should we aim to support “unpublishing” an object, moving it from published back to a draft state where it may be edited further? Some folks in the room had experience implementing functionality like this in the past and shared that it gets gnarly very quickly, and the task can evolve into re-inventing version control with the potentiality for multiple users to “check out” an object, work on it, and then try to re-publish it. Our sense was that it’d be sufficient to use the draft/unpublished/inactive state as a starting point, and once something is published, it’s published (until such time as someone recommends a technical design for "mediated editing" and contributes resources towards that feature).

Another requirement would be to come up with an indexing strategy for objects in either an inactive or deleted state that meets our needs; we’re not yet clear on whether there’s a consensus here. An initial approach might make these objects discoverable only by users who have edit access to them.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Aug 10, 2016 at 17:55 GMT_

----

This would be a big change, and needs review. Thoughts, @projecthydra/sufia-code-reviewers @projecthydra/sufia-ui-ux-advisors ?

Also pinging @njaffer and @jeremyf.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/newmanld"><img src="https://avatars.githubusercontent.com/u/3521707?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [newmanld](https://github.com/newmanld)**
_Wednesday Aug 10, 2016 at 21:12 GMT_

----

Opinions for consideration in answer to questions from @mjgiarlo:

Indexing /discovery:

A use case for tombstones applies to deleted, previously public objects with persistent identifiers such as DOIs.  For this purpose tombstones would need to be both discoverable (at least by the identifier) and publicly viewable.

A user with edit access would need to be able to list ‘my deleted works’ or ‘my unpublished works.’  So they could take actions such as permanent delete, restore or publish.  Except for tombstones, I’m not sure the need is strong – for the general user or for a user with edit rights – to be able to discover in one search published, unpublished and soft deleted works.

State changes:

Providing a tombstone does not require providing the ability to restore the work.

A soft delete would require the ability to restore the work.  Fedora 3 had a configuration option to set all deletes as soft deletes.  (I think this was dropped from core features of Fedora 4?)  I think it better to give the editor (the person doing the deleting) the ability to decide whether it is a permanent or soft delete.  Similarly to give the editor the ability to restore a soft-deleted work.

I would be ok with initially saying that once something is published, it is published.  To not support an ‘undo’ for publishing until/if we investigate robust version control for works.  Version control for works (not just files) would allow reverting to a previously unpublished state, or previous metadata.  It could be complex to manage relationships between works.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hannahfrost"><img src="https://avatars.githubusercontent.com/u/1801076?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hannahfrost](https://github.com/hannahfrost)**
_Monday Aug 15, 2016 at 21:36 GMT_

----

> it’d be sufficient to use the draft/unpublished/inactive state as a starting point, and once something is published, it’s published

👍 

and

> an indexing strategy for objects in either an inactive or deleted state ... [should be / could be] make these objects discoverable only by users who have edit access to them.

👍

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Aug 29, 2016 at 19:17 GMT_

----

I agree with hannafrost's agreements. with the caveat that once something is published, it's published **but can be versioned**

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jeremyf"><img src="https://avatars.githubusercontent.com/u/2130?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeremyf](https://github.com/jeremyf)**
_Monday Aug 29, 2016 at 20:17 GMT_

----

As an implementation detail, I believe it may make sense to keep the full "work flow state" separate from the publication_state. The work flow state represents things like "Ready for Copyright Assessment" or "Pending Advisor Review". Whereas the publication-state is a simplified answer saying "No this is not yet ready".

There are several complicated queries that result from work flow state, and I'm not certain SOLR is the best location for this. But that begins to dive deep into the weeds. See #2441 for further details on two queries that I believe are necessary for administration of mediation

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 23:17 GMT_

----

We are implementing active and inactive for mediated deposit work. Leaving this ticket here for the tombstoning use case.

**Comment by geekscruff** [comment]
Re tombstone use case, I think as a minimum we should align with F4 and provide a message that the resource has gone and when it was deleted.

F4 current message is: Discovered tombstone resource at /thing, departed: 2017-05-30T12:26:25.203Z so simply replaying that on screen would be an improvement.

As it stands, trying to access a work that's been deleted results in a Blacklight::Exceptions::RecordNotFound

**Comment by no-reply** [comment]
Closing this as completed work. If we want to reintroduce the tombstone issue post-Wings, let's open a new ticket specifying our needs on that front.

cc: @samvera/hyrax-repo-managers
