### ISSUE TITLE
I can be my own proxy

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#150]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cam156](https://github.com/cam156)**
_Wednesday Aug 10, 2016 at 18:56 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2454_

----

### Descriptive summary

In Sufia 7 I can make myself a proxy.  I can look up my user on the dashboard and assign myself to be my proxy.  Yes it really does not harm, but just saying it make my head spin...
### Expected behavior

I should not be able to make myself my proxy
### Actual behavior

I can make myself my proxy

![screen shot 2016-08-10 at 2 43 29 pm](https://cloud.githubusercontent.com/assets/1599081/17566742/a5fbf29c-5f0a-11e6-8e07-508803cfb9ec.png)
### Steps to reproduce the behavior

When I am logged into sufia
And I am on my dashboard
Then I can type my email into the proxy box
And I can be added as my own proxy
### Related work

Link to related tickets or prior related work here.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Dec 20, 2016 at 21:57 GMT_

----

I suggest we fix this in Hyrax rather than block the 7.3.0 release. If a fix comes in before the release comes out, I'll be happy to include that.

**Comment by cudevmaxwell** [comment]
This was fixed in ea8370ed8f927bc9c714df7b915f9b by @blancoj, as far as I can tell.
