### ISSUE TITLE
Proposal to change mapping of required metadata property:keyword

### ISSUE THREAD

**Issue by jenyoung** [samvera/hyrax#1505]
### Descriptive summary

A discussion in the samvera/metadata slack channel occurred about the current mapping of required field `property:keyword` to `DC11.relation` in [`basic_metadata.rb`](https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb#L18)

Current DC definition of [`relation`](http://dublincore.org/documents/dcmi-terms/#terms-relation) is "A related resource." 

### Rationale

The actual intended usage of `keyword` (and how most seem to be using it) per discussion in the slack channel is for either keywords or tags. This would still be an uncontrolled vocabulary field and separate from `subject`. 

Further investigation by the Samvera Metadata IG led to a discussion during our [July call](https://wiki.duraspace.org/display/samvera/Metadata+Call+2017-07-25) about changing the mapping to [`SCHEMA:keywords`](http://schema.org/keywords) instead.

Changing the default mapping of `keyword` would also enable those who wish to use a `relation`-type property to do so correctly without have to alter the default.

**Proposal**

Change:  `property :keyword, predicate: ::RDF::Vocab::DC11.relation`

to:  `property :keyword, predicate: ::RDF::Vocab::SCHEMA.keywords`

If accepted, http://www.schema.org would also need to be added to the list of namespaces.

I'm also tagging @samvera/hyrax-metadataists for any feedback.

**Comment by geekscruff** [comment]
I support this. We would need to create a migration task for existing data (see recent discussion of changing  isPartOf #1461).

**Comment by jlhardes** [comment]
I also think this is a good change to make and worth the migration task to adjust current instances. schema:keywords is a more accurate property and sets things up better for Hyrax use out of the box.

**Comment by mjgiarlo** [comment]
(And I believe `::RDF::Vocab::SCHEMA` is already available: https://github.com/ruby-rdf/rdf-vocab/blob/develop/lib/rdf/vocab/schema.rb)

**Comment by jenyoung** [comment]
I can't add labels (which is ok) but what is the next step to move this forward? Thanks!

**Comment by geekscruff** [comment]
I think @mjgiarlo would be the person to add labels. I should have some time in a couple of weeks to take a look at this. The change is easy, but I need to put some thought into the migration.

**Comment by mjgiarlo** [comment]
Hi! I added some labels. LMK if I got the right ones.

**Comment by geekscruff** [comment]
Just having a think about how to approach migrating data when the predicate changes, I have come up with the following idea (with some inspiration from #1461) ... I am open to better ways of approaching this!

* change the predicate for keyword (this will effectively orphan existing data in fedora and make it inaccessible to hyrax)
* to mitigate ☝️  add a legacy_keyword property using the old predicate so that the existing data is not lost
* create a rake task to migrate all old data to the new property/predicate
* add a deprecation warning that the legacy field will be removed in version xxx with a note about running the task

**Comment by jenyoung** [comment]
@geekscruff This sounds like a good plan forward. I'd argue against orphaning the existing data. How do we make this happen? Thanks!
