### ISSUE TITLE
Collections: Update code to handle delete action in index pages

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1507]
### Descriptive summary

Update code to handle deleting collections from the collection index pages (Dashboard All/Managed/Your Collections).

NOTE: This issue was extracted from the uber issue for index view changes.  #1417

### Rationale

See model issue for rationale.

### Implementation

**Edit Files:**
* index for All/Your Collections - [app/views/hyrax/my/collections/index.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections/index.html.erb)
* all other files are under
  * [app/views/hyrax/my/collections](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections) - specific to collections
  * [app/views/hyrax/my](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my) - shared with works

#### Expected user interactions

**NOTE: Dialogs are the same here and on admin show page.  Create partials for the dialogs and share with #1841.** 

Update the processing that occurs when the Delete action is selected for a collection. 

From the All Collections and My Collections pages, a user can...
- [x] show delete in action menu whether or not the user can delete
- when user selects delete action
  - if the user does not have edit_access to the collection
    - [x] show dialog stating "You do not have sufficient privileges to edit this document" with only option Ok
  - if user can delete
    - AND collection has items 
      - [x] AND `collection_type.required_membership? true` (i.e. Admin Set) --> show dialog stating "This collection is defined as an `<%= collection_type.title %>` and is not empty. To delete an `<%= collection_type.title %>`, you must first remove (delete or move to another collection) all items from the `<%= collection_type.title %>`. with only option Ok
      - [x] AND `collection_type.required_membership? false` (i.e. all other types) --> show confirmation dialog warning "Deleting this collection will permanently remove the collection from the repository. Items in the collection will remain in the repository. Are you sure you want to delete this collection?" AND allow user to Delete or Cancel
    - [x] AND collection has 0 items (for both Admin Set and Collections) --> show confirmation dialog `"Are you sure you want to delete this collection? This action cannot be undone."` AND allow user to Delete or Cancel
  - [x] if user chooses to continue, perform the delete
    - [x] if collection type != admin set, execute Collection#destroy action
    - [x] if collection type == admin set, execute AdminSet#destroy action

Modal messages...
- [ ] collection or admin set is empty - show mockup message and allow delete or cancel
- [ ] collection has members - show mockup message and allow delete or cancel
- [ ] admin set has members - show "This collection is defined as an administrative set and is not empty. To delete an administrative set, you must first remove (delete or move to another administrative set) all items from this administrative set."

#### SPECIAL NOTE on Admin Sets:

For the initial implementation, the Admin Set underlying code will not change.  But to a user, the Admin Set will appear to be a collection.

To make the illusion happen...
* I believe, but need to confirm, that only admins can delete an AdminSet. But perhaps managers of the AdminSet can as well.  Two checks
  - [ ] disallow if there are any works in this admin set
  - [ ] disallow if the user does not have edit_access to the admin set - or maybe even more restrictive to just admins (need to verify current behavior)

### Mockup

![image](https://user-images.githubusercontent.com/6855473/29413417-51e35c78-832a-11e7-9112-eb8d3e19ad7a.png)

### Dependency

COMPLETED #1587 Collections: Modify My Collections search builder to return all editable collections and admin sets

### Related work

Directly related works:
#1841 Show dialog if user clicks a button on collection admin show page they can't perform
#1508 Update code to handle edit action in collection index pages

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index             | #1417 |
| Index: Collection List   | #1509 |
| Index: Filter List      | #1511 |
| Index: New Modal         | #1506 |
| Index: Edit Action       | #1508 |
| Index: Delete Action     | (this issue) |
| Index: Add as Subcollection Action | #1512 |
| Index: Bulk Actions      | #1510 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by elrayle** [comment]
@ggeisler From previous conversations, I understand that you have a preference for showing a dialog to users when they do not have permissions to perform an action.  

For this issue, that means that a user without edit access...
* will see the delete button
* if pressed, they will see a message, something like... "You do not have permissions to delete this collection.  See site admin for more information."

What would you like the actual dialog message to read?

**Comment by elrayle** [comment]
@ggeisler I'm wondering if we need two dialogs for Delete when the collection has members?

* For Admin Sets (keying off `membership_required? true`) presents a message like `"You must remove all items from the collection before it can be deleted."`
* For all other collections (keying off `membership_required? false`) presents a message like `"This collection has items.  Are you sure you want to delete the collection?"`

I looked at how Admin Sets currently handles this.  On the Admin Set show page, the Delete button is disabled if the Admin Set has any works.

**Comment by ggeisler** [comment]
@elrayle I'm unsure if we really do need two different messages. If we're working with an admin set, the message provided in the mockup is still valid, I believe. The difference is that in an admin set with `membership_required? true` a work must belong to one admin set, correct? So if the user tries to remove a work from the admin set in order to empty it, and that work doesn't belong to another admin set, they should see a message telling them why they are not able to remove the work, correct?

If the answer to my questions above are true, then I don't see the need for a distinct message for deleting an admin set; notifying the user of the membership requirement would be handled by a message displayed when the user tried to clear out the works from the admin set.

**Comment by elrayle** [comment]
@ggeisler The mockup allows the user to delete the collection without removing the items first.  This is not allowed for admin sets.  The items must be either deleted or moved to another admin set before the admin set can be deleted.

Scenarios: (check if you agree)
- [ ] collection or admin set is empty - show mockup message and allow delete or cancel
- [ ] collection has members - show mockup message and allow delete or cancel
- [ ] admin set has members - show "Administrative set is not empty.  Remove all items before deleting."

**Comment by elrayle** [comment]
> So if the user tries to remove a work from the admin set in order to empty it, and that work doesn't belong to another admin set, they should see a message telling them why they are not able to remove the work, correct?

I do believe this is true.  In this issue, the delete is happening to the admin set.  If we show the mockup message and allow them to select Delete, what happens to the works in that admin set?

**Comment by ggeisler** [comment]
@elrayle Okay, I understand the scenario now. Yes, I agree with your scenario suggestions above, although I think we can provide a slightly less terse/more informative message to the user for the third scenario. How about something like:

> This collection is defined as an administrative set and is not empty. To delete an administrative set, you must first remove (delete or move to another collection) all items from the administrative set.

Not a huge difference, just making it a bit more clear that the empty set requirement is only being enforced here because it is an admin set.

**Comment by elrayle** [comment]
@ggeisler Great.  I updated the main body of the issue to summarize the modal text.

**Comment by elrayle** [comment]
Remaining Work:
#1968 Collections: Delete admin set should forward to my collections
#1972 Collections: admin sets action menu should match collections action menu

**Comment by elrayle** [comment]
All requirements met by PR #1908 or remaining work issues.  Closing.
