### ISSUE TITLE
Collections: Update code to handle edit action in index pages

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1508]
### Descriptive summary

Update code to handle edit action in the index view (e.g. Dashboard -> All/Managed/Your Collections).

NOTE: This issue was extracted from the uber issue for index view changes.  #1417

### Rationale

See model issue for rationale.

### Implementation

**Edit Files:**
* index for All/Your Collections - [app/views/hyrax/my/collections/index.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections/index.html.erb)
* all other files are under
  * [app/views/hyrax/my/collections](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections) - specific to collections
  * [app/views/hyrax/my](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my) - shared with works

#### Expected user interactions

**NOTE: Dialogs are the same here and on admin show page.  Create partials for the dialogs and share with #1841.** 

Update the processing that occurs when the Edit action is selected for a collection. 

From the All Collections and My Collections pages, a user can...
- [x] show edit in action menu whether user can edit or not
- [x] click edit action for an existing collection
  - [x] if user does not have edit access, show dialog ""You do not have sufficient privileges to edit this collection"
  - [x] if collection type != admin set, execute Collection#edit action
  - [ ] if collection type == admin set, execute AdminSet#edit action 

### Dependency

COMPLETE #1587 Collections: Modify My Collections search builder to return all editable collections and admin sets

### Related work

Directly related works:
#1841 Show dialog if user clicks a button on collection admin show page they can't perform
#1507 Update code to handle delete action in collection index pages

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index             | #1417 |
| Index: Collection List   | #1509 |
| Index: Filter List      | #1511 |
| Index: New Modal         | #1506 |
| Index: Edit Action       | (this issue) |
| Index: Delete Action     | #1507 |
| Index: Add as Subcollection Action | #1512 |
| Index: Bulk Actions      | #1510 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by elrayle** [comment]
@ggeisler From previous conversations, I understand that you have a preference for showing a dialog to users when they do not have permissions to perform an action instead of hiding the button/action.  

For this issue, that means that a user without edit access...
* will see edit in the action menu
* if pressed, they will see a message, something like... "You do not have permissions to edit this collection.  See site admin for more information."

What would you like the actual dialog message to read?

**Comment by ggeisler** [comment]
@elrayle Well, the context is relevant; I wouldn't say I always have a preference for showing a dialog.

Can you include a screenshot of what page(s) we're talking about, so I understand the context? Offhand it's not clear to me in what context a user will see collections they can't edit.

**Comment by elrayle** [comment]
All requirements are met by PR #1908 or the remaining work issues.  Closing
