### ISSUE TITLE
I can add a proxy that already exists when I accept a transfer

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#151]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cam156](https://github.com/cam156)**
_Wednesday Aug 10, 2016 at 19:07 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2455_

----

### Descriptive summary

In Sufia 7 I can add a proxy twice by creating a proxy manually and then assigning proxy rights when I accept a transfer from that proxy.
### Expected behavior

A person should only be listed as a proxy once.
### Actual behavior

![screen shot 2016-08-10 at 3 04 22 pm](https://cloud.githubusercontent.com/assets/1599081/17567087/efcd6bca-5f0b-11e6-82b3-0aee7aecb8d8.png)
### Steps to reproduce the behavior

When I am user 1 I should transfer a work to user 2
When I am user 2 I should add user one as a proxy from my dashboard
Then I should accept the transfer choosing"Accept and add proxy"
Then I will see user 1 in my proxy list twice. 
### Related work
#2454

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Dec 20, 2016 at 21:57 GMT_

----

I suggest we fix this in Hyrax rather than block the 7.3.0 release. If a fix comes in before the release comes out, I'll be happy to include that.

**Comment by rjkati** [comment]
This issue is still present in hyrax 3.0.2. I was able to duplicate using directions provided above.
![double_proxy](https://user-images.githubusercontent.com/32644254/118818864-c7aa0600-b882-11eb-8348-460324cccf7a.PNG)

**Comment by jlhardes** [comment]
This is verified and ready to be addressed.

**Comment by fritzfreiheit** [comment]
Here's what I see now: 

<img width="926" alt="Screenshot 2023-02-21 at 4 06 53 PM" src="https://user-images.githubusercontent.com/29735643/220459172-13122681-f291-4af8-b2c1-e559e52a23d5.png">

**Comment by rjkati** [comment]
Verified on nurax-dev (Hyrax 4.0.0.beta2). After authorizing a user as a proxy and accepting a transfer from the same user (while authorizing them as a proxy a second time), the proxy user appears only once in the Current Proxies list.
