### ISSUE TITLE
Collections: Update index to handle bulk actions for collections

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1510]
## Descriptive summary

Update index page for All/My Collections to process bulk actions.  This is not a dependecny for any other work, so the priority of this issue is low.

NOTE: This issue was extracted from the uber issue for index view changes.  #1417

### Rationale

See model issue for rationale.

### Implementation

**Edit Files:**
* index for All/Your Collections - [app/views/hyrax/my/collections/index.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections/index.html.erb)
* all other files are under
  * [app/views/hyrax/my/collections](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections) - specific to collections
  * [app/views/hyrax/my](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my) - shared with works

#### Expected user interactions

From the All Collections and My Collections pages, a user can...
- [x] bulk actions on collections
  - [x] add checkbox for select/deselect all
  - [x] add checkbox for each collection (see work in branch [collections-#1417-index_views_managing_collection](https://github.com/samvera/hyrax/tree/collections-%231417-index_views_managing_collections))
  - [x] add button for bulk action to delete collections (see mockup)
  - when button is clicked
    - [x] if 0 selected, show instructions dialog (see note 2 for exact wording)
    - [x] if at least one selected, show warning dialog (see note 2 for exact wording)
  - [x] add processing of bulk delete across selected collections
    - [x] disallow if the user isn't an editor for that collection (They shouldn't be able to select any they can't edit, so this is a double check before proceeding with the delete.)
    
Exact text for the bulk actions drop list is in the mockup below.

### Mockup

Bulk delete button is the Delete collections button above the list of collections.  See note 2 for details on confirmation dialogs.

![collection-index-end-user](https://user-images.githubusercontent.com/101482/28932481-7932e160-782e-11e7-9baa-457e5c59fd97.png)

### Related work

Directly related work...

#1655 Include admin sets in collection search builders.
#1708 UI/UX question regarding checkboxes for AdminSets on Collections index page

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index             | #1417 |
| Index: Collection List   | #1509 |
| Index: Filter List      | #1511 |
| Index: New Modal         | #1506 |
| Index: Edit Action       | #1508 |
| Index: Delete Action     | #1507 |
| Index: Add as Subcollection Action | #1512 |
| Index: Bulk Actions      | (this issue) |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by elrayle** [comment]
@ggeisler Since Delete is the only supported bulk action, should checkboxes be disabled for any collection where the user does not have edit access?

**Comment by ggeisler** [comment]
@elrayle What is the scenario where a user wouldn't be able to delete a collection that user created? I guess I'm missing something.

**Comment by elrayle** [comment]
@ggeisler 

> [Can't delete when] the user does not have edit access

This scenario occurs on Dashboard -> Collections -> Managed Collections, for any collection in the list where the user has view or deposit access, but not manage access.

**Comment by elrayle** [comment]
UI/UX of Bulk Delete...

@ggeisler Can you select checkboxes for the statements you agree with and add clarifications where you expect things to be different.

Your Collections
- [ ] bulk `Delete collections` button is visible and available for users
- [ ] by definition of being on Your Collections, the user is the owner for everything in the list AND therefore, has edit/delete abilities
- [ ] include a checkbox beside each collection (rationale: collections can be deleted even if not empty)
- [ ] do not include a checkbox beside admin sets (rationale: admin sets can be deleted ONLY if empty)
- [ ] clicking `Delete collections`  (HERE DOWN SAME FOR ALL TABS)
  - [ ] with at least one checkbox selected, should show a modal warning that delete is permanent for the collection and that any members of the collection will remain in the repository (Exact wording in note 2 of the mockup.)  User can select to Cancel or Delete
  - [ ] with 0 checkboxes selected, should show a modal stating 'You must select one or more collections to delete.'  (Exact wording in note 2 of the mockup.)  User can select close.
- [ ] If user selects Delete in the warning modal, each collection is deleted and the relationship (`<subcollection/work> <pcdm:memberOf> <collection> in the sub-collections and works is removed.

Managed Collections
- [ ] bulk `Delete collections` button is visible and available for users
- [ ] include a checkbox beside each collection the user can edit (rationale: Manager users can delete collections.  Depositors and Viewers cannot.)
- [ ] do not include a checkbox beside admin sets (rationale: admin sets can be deleted ONLY if empty)

All Collections
- [ ] bulk `Delete collections` button is visible and available for users
- [ ] by definition of being on All Collections, the user is an admin and has edit/delete abilities for everything
- [ ] include a checkbox beside each collection (rationale: collections can be deleted even if not empty)
- [ ] do not include a checkbox beside admin sets (rationale: admin sets can be deleted ONLY if empty)

**Comment by ggeisler** [comment]
@elrayle These seem reasonable to me, although you should keep in mind that I'm not running the application so am just going by what makes sense to me on paper. If you or the team actively working on things feel strongly something should be different, feel free to override my opinion.

The one I didn't check in each case has to do with not including the checkbox next to admin sets. I assume this only applies to admin sets that are not empty? In other words, if an admin set is empty, then you **would** present the checkbox (assuming the user has delete privileges), since the admin set in that case is eligible for deleting.

**Comment by elrayle** [comment]
Remaining work:
#1788 Batch delete should show message if fails 
#1708 UI/UX question regarding checkboxes for AdminSets on Collections index page

**Comment by elrayle** [comment]
All requirements are addressed by PR #1788 OR in the issues for remaining work.  Closing.
