### ISSUE TITLE
Collections: (HIGH) Process action to add this collection as a member of another collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1512]
**HIGH Priority**

### Descriptive summary

Add code that allows for nesting of collections.  Add UI code that allows a user to select a collection to be the current collection's parent.

NOTE: This issue was extracted from the uber issue for index view changes.  #1417
NOTE: With #1574, this ticket is now UI or Wireframe only tasks.

### Rationale

See model issue for rationale.

### Implementation

**Edit Files:**
* index for All/Your Collections - [app/views/hyrax/my/collections/index.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections/index.html.erb)
* all other files are under
  * [app/views/hyrax/my/collections](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections) - specific to collections
  * [app/views/hyrax/my](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my) - shared with works

#### Expected user interactions

Support nesting of collections.

Low level coding...
- [x] add the ability of a collection to have a collection as a member
  - [x] verify that pcdm or hydra-works validates that the selected parent isn't already an ancestor of the child collection

NOTE: The PCDM model already supports nested collections.  And there is some code for this in hydra-pcdm and hydra-works.  But by the time it gets up to Hyrax, there is no nesting of collections.  This might simply be the case that it wasn't surfaced in the UI.  (fingers crossed)

From the All Collections and My Collections pages, a user can...
- [x] show Add collection to another collection in action menu ONLY if user has edit access to the collection AND collection.nestable? true
- [x] click Add collection to another collection action for an existing collection
  - [x] disallow if collection.nestable? false || current user does not have edit access (The action shouldn't be available in this case.)
  - [x] show modal for selecting the collection to be the parent of this collection (see mockup)
  - [x] make this collection a member of the selected collection

See mockup for text and UI changes

#### Mockup

![works](https://user-images.githubusercontent.com/101482/29427054-756a17f0-833d-11e7-8dcb-be351aa9356c.png)

#### Issues related to UI work for nesting

* #1417 original UI epic for admin index
* #1509 admin index - listing of collections - includes description of action menu items
* #1512 process `Add collection to another collection` action + modal for selecting other collection  (This one has the brain dump list of things needed for nesting)
* #1377 relationship partial for edit form

#### Collections original epic issues (mainly organized by UI)

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index             | #1417 |
| Index: Collection List   | #1509 |
| Index: Filter List      | #1511 |
| Index: New Modal         | #1506 |
| Index: Edit Action       | #1508 |
| Index: Delete Action     | #1507 |
| Index: Add as Subcollection Action | (this issue) |
| Index: Bulk Actions      | #1510 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by elrayle** [comment]
* HIGH Collections: index page - Add `add collection to another collection` to the action menu ONLY for collections of types that are nestable
* HIGH Collections: enable existing collection nesting from PCDM and Hydra:Works
* HIGH Collections: indexing of nested collections
* HIGH Collections: show page - include sub-collections in the member results if there are any (LaRita)
* MODERATE Collections: index page - Show relationship between collections -- need mockup design
* MODERATE Collections: new/edit - until management of items is moved out of edit, need to include listing and updating sub-collections (LaRita)
* LOW Home: browse by collection hierarchy -- need mockup design

**Comment by laritakr** [comment]
Notre Dame's UI Screenshots have been added to issue #1575

**Comment by elrayle** [comment]
PR #1604 created the modal with some stubbed data.

Remaining work:

* Permission logic applied to show/hide of the 'Add collection to collection' dropdown option.
* In the modal, populate the dropdown options with live collections.
* Handle the AJAX POST/request or however we tell the system to add the Collection to it's selected parent collection.
* Possibly, do not show modal if there aren't any collection types supporting nesting.

**Comment by adamjarling** [comment]
@elrayle Close this out?  The other two tickets listed in remaining work have been closed.

**Comment by vantuyls** [comment]
nesting of collections functions as expected due to the work presented here. closing (unless @elrayle thinks we should reopen as incomplete)
