### ISSUE TITLE
Change hardcoded reference to collection type 'admin_set' to use #admin_set? method

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1524]
### Descriptive summary

A temporary check was put in the collections type index view to not show the delete button if the collection type is the admin set type.  The temporary check hardcodes the machine_id as `'admin_set'`, but should really use the Hyrax::CollectionType#admin_set? method.

This is an extension of the work started in Issues:
* #1349 Create index views for managing collection types
* #1486 Set the collection type instance variable for a collection

### Implementation

In [app/models/hyrax/collection_type](https://github.com/samvera/hyrax/blob/collections-sprint/app/models/hyrax/collection_type.rb) model, add...
```
      def admin_set?
        machine_id == 'admin_set'
      end
```

In [app/views/hyrax/admin/collection_types/index.html.erb](https://github.com/samvera/hyrax/blob/collections-sprint/app/views/hyrax/admin/collection_types/index.html.erb#39), modify...

From: `<% if collection_type.machine_id != 'admin_set' %>`
To: `<% if collection_type.admin_set? %>`

### Steps to confirm the behavior in the UI

1. login as an admin
1. Dashboard -> Settings -> Collection Types

The list of collection types should include Admin Sets and it should not have a remove button.

### Dependency

Dependency is for being able to test via the UI.  You can simulate this by creating a collection type named `Admin Set`.

Issue #1342 Update Hyrax-generation process to create a collection type for Administrative Sets

### Related Work

This is an extension of the work started in Issues:
* #1349 Create index views for managing collection types (this issue follow on work 1349)
* #1486 Set the collection type instance variable for a collection

**Comment by mjgiarlo** [comment]
@billdueber I've added you to the Contributors GH team for the Samvera organization. When you accept the invitation (should be in yr :inbox_tray:), feel free to assign this issue to yourself. (And do let me know if you are unable to do so.)

Cc: @elrayle

**Comment by elrayle** [comment]
Woo hoo... another one bites the dust.
