### ISSUE TITLE
Collections Type: (LOW) Add a button on index to allow user to see all collections of this type

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1526]
**LOW Priority**

### Descriptive summary

Add a button to the collections type index page that allows the user to see all collections of a particular type.   

### Rationale

This is especially useful when attempting to delete a collection type and it is denied because collections of this type exist.

### Expected behavior

On collection types index page, for each collection type, there will be a button (label TBD) that when clicked will go to Dashboard -> Collections -> All Collections applying a filter for that collection type.

### Steps to verify the behavior

1. Create 2 collection types
1. Create 1 collection of each type
1. In Dashboard -> Settings -> Collection Types, click the View Collections (actual label TBD)

Verify forwarded to Dashboard -> Repository Objects -> Collections -> All Collections with a filter for the collection type that the View Collections button was beside.

### Dependency

COMPLETED Issue #1511 Collections: Add filtering by type and visibility

### Related work

Issue #1349 - PR #1472 - collection types index view work  (this issue follow on work 1349)
Issue #1341 - PR #1304 - collection types controller work

**Comment by elrayle** [comment]
The button was added in PR #1472.  It needs to be hooked up to the My Collections with a filter of type=collection type for the type trying to be deleted.

**Comment by blancoj** [comment]
@elrayle I think this has already been implemented.  This issue may need to be closed.

**Comment by mcdowney** [comment]
Closing this ticket as implemented
