### ISSUE TITLE
HIGH Collections: edit page - as participants are added, add the group/user with the given access role

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1541]
### Descriptive summary

When a participant is added to a collection, add an entry in the permission_templates_access table for the specified access.

### Expected behavior

When a user or group participant is added to a collection is created, the following are added to permission_templates_access table...

| agent_type | agent_id | access |
| ----- | ----- | ----- |
| `'group'` | id of the group | `'manage'` or `'deposit'` or `'view'`  |
| `'user'` | id of person | `'manage'` or `'deposit'` or `'view'`  |

### Steps to verify the behavior

1. Create 4 users:  me@ex.com, mgr@ex.com, dep@ex.com, vw@ex.com
1. Login as me@ex.com
1. Create a collection type
1. Create a collection of this type and save

Note the entries in the permissions_templates_access table that were created for the new collection.

1. Edit the collection
1. Add participants...
  1. assign mgr@ex.com as a manager
  1. assign dep@ex.com as a depositor
  1. assign vw@ex.com as a viewer

Verify that the following were added to the permissions_templates_access...

| agent_type | agent_id | access |
| ----- | ----- | ----- |
| `'user'` | `'mgr@ex.com'` | `'manage'` |
| `'user'` | `'dep@ex.com'` | `'deposit'`  |
| `'user'` | `'vw@ex.com'` | `'view'`  |

### Dependency

#1538 Collections: db tables - adjust permissions_templates to include source_type
#1523 Collections: routes - add routes needed for permissions_templates and permissions_templates_access for collection participants
#1540 Collections: new page - upon save, create entry for this collection in permission_templates
#1540 Collections: new page - upon save, add default access entries in permission_templates_access
#1378 Collections: Create sharing partial of the new/edit form

### Related Work:

Dependencies plus...
#1543 Collections: edit page - upon save, Solr for Collection object should have appropriate edit_access and read_access
#1544 Collections: edit page - upon save, Fedora for Collection object should have appropriate ACLs 
#1545 Collections: index page - add processing that allows for a work to be created directly in this collection
#1427 Collections: admin show page (min: `Deposit new works through this collection` button)

**Comment by hortongn** [comment]
This issue was fully resolved by the work in PRs #1594 and #1610.  I followed the verification steps in this issue's description and got the expected results using code that's already been merged into the `collections-sprint` branch.
