### ISSUE TITLE
Collections: Process multi-membership setting when works are added to a collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1549]
### Descriptive summary

When a work is added to a collection with allow_multiple_membership? false, there are several checks that need to be performed before the work can be added.  See Expected Behavior for details.

### Rationale

Some collection types allow for works to belong to any number of collections of that type.  For others, a work can belong to only one collection of that type.  AdminSets is an example of a 'collection type' that has allow_multiple_membership? false.

### Expected behavior

In all places where a work is added to a collection...
* if collection.allow_multiple_membership? true, add the work
* if collection.allow_multiple_membership? false...
  * if this work isn't in any collections, add the work
  * unless this work is already in a collection of this type, add the work
  * otherwise, don't allow adding of the work

### Steps to reproduce the behavior

There are several places adding a work can happen.

### Related work

Issue #1383 - PR #1471 Collections: Modify model to include Collection Type and settings methods
Issue #1346 - PR #1501 Collection Types: Create configuration settings partial of the new/edit form

**Comment by mjgiarlo** [comment]
Current ways to add a work to a collection:

1. Click `Add Works` on Collection show page, then
  1. Click `Add new work` or `Create batch of works` (collection selected in work form), or
  1. Select one or more works on the dashboard, then `Add to Collection`, then either
    1. `Update Collection` (`/collections/collection_replace_id`, `updates-collection` data-behavior), or
    1. `Add to New Collection` (`batch_document_ids` passed to `/collections/new`)
1. Edit a work

**Comment by mjgiarlo** [comment]
Look at:

* `Hyrax::Actors::CollectionsMembershipActor`
* `Hyrax::Forms::WorkForm`

**Comment by elrayle** [comment]
Thanks for all the good information in the Issue.  Makes it easy to know that it can be closed.

Fixed by PR #1555
