### ISSUE TITLE
When editing an admin set I should be able to add a representative image

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#156]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Friday Aug 26, 2016 at 17:23 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2562_

----

Picking from the representative images from the works in the admin set

**Comment by mjgiarlo** [comment]
<a href="https://github.com/atz"><img src="https://avatars.githubusercontent.com/u/109954?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [atz](https://github.com/atz)**
_Thursday Sep 29, 2016 at 00:19 GMT_

----

Why are we concerned with collection/display set features in an admin set?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Sep 29, 2016 at 02:07 GMT_

----

Admin sets in sufia are also display sets. See Gary's mockups

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Dec 16, 2016 at 23:24 GMT_

----

@jcoyne is this still in progress?

**Comment by no-reply** [comment]
Closing this, as it's now possible to set a thumbnail for an admin set.
