### ISSUE TITLE
Maintain order of title, creator, keyword in metadata

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#1568]
### Descriptive summary

Hyrax (1.x)

### Rationale

It is important to preserve the order of titles, creators, and keywords in the metadata record as they were entered in by the user. In scholarly publishing, the order of authors (creators) typically corresponds to their role in the project. For example, the first author may be the corresponding author and principal investigator. 

### Expected behavior

The order of titles, creators, and keywords should be saved to the metadata record (and displayed to the end-user) in the same order in which they were entered by the depositor.

### Actual behavior

User inputs:

![image](https://user-images.githubusercontent.com/24395592/29689508-133b0e2a-88e9-11e7-805c-2db14ad668f1.png)

Hyrax Metadata output:

![image](https://user-images.githubusercontent.com/24395592/29689668-9f2919c2-88e9-11e7-94cc-0dfd4c9cd2c7.png)
![image](https://user-images.githubusercontent.com/24395592/29689563-44f583d2-88e9-11e7-8465-a882b1c8f329.png)

### Steps to reproduce the behavior

1. Create a work
2. Enter multiple titles, creators, keywords
3. Save the work

### Related work

Northwestern, PSU, UVA, and UCSD are interested in this. 

Here's some discussion and progress:
- PSU: https://github.com/psu-stewardship/scholarsphere/issues/949
- UVA: https://github.com/uvalib/libra-oc/commit/0c9be010e344112eb8573ac7af1a475df66be3cf
- UCSD: https://github.com/ucsdlib/horton/issues/90

**Comment by cpd3149** [comment]
Question: should this ticket be broken up by metadata field [title, creator, keywords]?

**Comment by mjgiarlo** [comment]
@cpd3149 I'm not sure that's necessary at this point. Thanks!

**Comment by jenyoung** [comment]
Should we also discuss during a SMIG meeting? @samvera/hyrax-metadataists?

**Comment by wickr** [comment]
The Hyrax Metadata Ordering Working Group was formed to look at proposed solutions for ordering and see if a recommendation is possible: https://wiki.duraspace.org/display/samvera/Hyrax+Metadata+Ordering+Working+Group

**Comment by rjkati** [comment]
@jlhardes This seems to duplicate work described in #4781

**Comment by jlhardes** [comment]
Closing as duplicate - issue #4781 reported with more recent discussion.
