### ISSUE TITLE
Leverage select2 for autocompleting fields that take URIs

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#157]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [awead](https://github.com/awead)**
_Friday Aug 26, 2016 at 17:27 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2563_

----

### Descriptive summary

With collections, works, and now admin sets, there are classes of inputs that take existing URIs in the fedora repository as their inputs. Currently, there are dropdowns populated at render or text fields that require IDs.

To make for a better UI, we should use select2 as a means to query for existing resources that the user has access to and render them as human-readable options for these inputs, while building the URI as the value in the form. Then, an actual valid URI will be submitted without the user needing to worry.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Aug 26, 2016 at 22:03 GMT_

----

I might like to see #2492 first, but :+1: to this issue.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [awead](https://github.com/awead)**
_Saturday Aug 27, 2016 at 00:42 GMT_

----

I agree, in fact, upgrade first before doing this.

**Comment by mcdowney** [comment]
Closing for now as no longer relevant
