### ISSUE TITLE
When I nest a collection, I need to run a reindex the relationships on that object.

### ISSUE THREAD

**Issue by jeremyf** [samvera/hyrax#1574]
When I nest a collection, I need to run a reindex the relationships
on that object. This is the back-end work for indexing the nested relationships. It relates to #1512.

- This reindex can be a rather slow going affair, so it should run
  outside of the request cycle.
- see [Samvera::NestingIndexer.reindex_relationships][reindex_relationships]

The next steps are:

- [ ] Wire in the use of [`Samvera::NestingIndexer.reindex_relationships`][reindex_relationships].
      You'll need to make sure this is run after we save the Fedora object (and even write to the index).
      See [What happens when I deposit something?][what-happens]
  - We will likely need to add to [various indexers](./app/indexers/hyrax/collection_indexer.rb)
  - We will want to create a [job](./app/jobs/hyrax/application_job.rb)
  - Ensure that we don't update the preservation document within the indexer or job (only the index)
- [ ] Propose the reversal of the Collection to Collection
      relationship's direction. This was initially proposed in the
      [2017-8-23 Samvera Tech Call (Agenda 2.a)][agenda]. Work has begun on
      the relationship reversal in [Hydra::PCDM][switch-direction], but was set aside
      in an effort to incorporate `samvera-nesting_indexer`. _This is Jeremy: I thought I would have more time during the Collections Extension sprint to reverse the relationship, but I didn't. I instead focused on creating the Samvera::NestingIndexer gem from CurateND's effort._
- [ ] Implement [`Hyrax::Adapters::NestingIndexAdapter.each_perservation_document_id_and_parent_ids`][adapter]. This is a possibly non-trivial task as we may want to yield `document_id` and `parent_ids` in a very deliberate order based on the implementation details of [Samvera::RepositoryReindexer::NestingIndexer][implementation_details].

## Reverse Relationship Todo Items

If we agree to change the direction of the relationship:

- [ ] Update `Hydra::PCDM` gem
- [ ] Verify `Hydra::Works` gem
- [ ] Update [`Hyrax::Collections::NestedCollectionPersistenceService`][persistence_service]

If we do not agree to change the direction of the relationship:

* The community will need to understand any performance impacts.

If we delay on changing directions until after we've wired in the indexer and deployed to production code:

- [ ] Write Fedora data migration to flip the relationship in production.

[reindex_relationships]:https://github.com/samvera-labs/samvera-nesting_indexer/blob/106fa93858d47f915f9802b8efa036d518c29157/lib/samvera/nesting_indexer.rb#L19
[what-happens]:http://samvera.github.io/what-happens-deposit-2.0.html
[agenda]:https://wiki.duraspace.org/display/samvera/Samvera+Tech+Call+2017-08-23
[switch-direction]:https://github.com/samvera/hydra-pcdm/tree/switch-direction-of-collection-membership
[persistence_service]:https://github.com/samvera/hyrax/blob/collections-sprint-1512-nested-indexing/app/services/hyrax/collections/nested_collection_persistence_service.rb#L18-L20
[adapter]:https://github.com/samvera/hyrax/blob/4384b808234e742688f9c41609f04d27300e5aac/app/services/hyrax/adapters/nesting_index_adapter.rb#L26
[implementation_details]:https://github.com/samvera-labs/samvera-nesting_indexer/blob/106fa93858d47f915f9802b8efa036d518c29157/lib/samvera/nesting_indexer/repository_reindexer.rb#L41-L56

**Comment by laritakr** [comment]
Resolved by https://github.com/samvera/hyrax/pull/2636
