### ISSUE TITLE
Collections: Get screenshots of nested collections from Notre Dame

### ISSUE THREAD

**Issue by jeremyf** [samvera/hyrax#1575]
Notre Dame's CurateND has implemented nested collections.

Capture and upload the screen shots for nested collections for Notre Dame. This is to inform #1512.

Done looks like:

- [x] Attaching screenshots to this issue.
- [x] Adding a comment on #1512 that screenshots are ready.
- [x] Ping the UI Team to make sure they are aware of what has been uploaded.

The goal is to use ND's screenshots to inform an initial implementation of how Hyrax can show nested collections.

**Comment by laritakr** [comment]
# Notre Dame's nested collections UI
 
## Facets & Modal

### Collections are accessible via a facet shown in filter list:
![screen shot 2017-08-28 at 12 44 36 pm](https://user-images.githubusercontent.com/17851674/29783738-7dcb1e0c-8bef-11e7-9fc4-4bf141cceadc.png)

### When the collection facet is selected, a modal pops up showing both single and nested collections:
![screen shot 2017-08-28 at 12 44 17 pm](https://user-images.githubusercontent.com/17851674/29783797-b105c4ac-8bef-11e7-9c2f-be260ad95852.png)

### Nested collections can be expanded in the modal to show child collections:
- The parent collection is a toggle to expand the modal, or you can click the "See all xxx" to see the parent collection search results page
- Clicking a child collection goes to the child collection's search results page.

![screen shot 2017-08-28 at 12 45 03 pm](https://user-images.githubusercontent.com/17851674/29783821-cb5f78ca-8bef-11e7-9293-55902af5d2fa.png)
-------
## Search Results Pages

### This is the child collection's search results page:
- accessible from the modal
- accessible from the "Browse objects in the collection" button at the bottom of the collection's show page.
- "Full Record" goes to child collection's show page.
- Link to parent collection's show page under the title.

![screen shot 2017-08-28 at 1 14 41 pm](https://user-images.githubusercontent.com/17851674/29784609-a71c82de-8bf2-11e7-9552-0f2a08205cc8.png)

### This is the parent collection's search results page: 
- accessible from the modal
- accessible from the "Browse objects in the collection" button at the bottom of the collection's show page.
- "Full Record" goes to parent collection's show page.
- Link to child collection's show pages in the subcollections section

![screen shot 2017-08-28 at 1 03 02 pm](https://user-images.githubusercontent.com/17851674/29784723-16759b2a-8bf3-11e7-93e1-49dadd33ad6f.png)

### Search results pages for both a parent or a nested collection include an option to show or minimize the details, as well as the "Full Record" option which takes you to the show page for the collection. This is the minimized view of the child collection: 

![screen shot 2017-08-28 at 12 45 47 pm](https://user-images.githubusercontent.com/17851674/29785110-69c219ec-8bf4-11e7-8960-710e2305679d.png)

### And this is the same collection with the details expanded (the default view is the expanded one):
![screen shot 2017-08-28 at 12 45 26 pm](https://user-images.githubusercontent.com/17851674/29783874-f1dec9ba-8bef-11e7-8792-102a1a528e25.png)

-------
## Show Pages

### Show page for the parent collection:
- accessible via the "Full Record" option from the parent collection's search results page
- accessible via a link under the title on the child collection's show page
- "Browse objects in the collection" button links links back to parent collection's search results page

![screen shot 2017-08-28 at 12 59 45 pm](https://user-images.githubusercontent.com/17851674/29784064-a4a1db5a-8bf0-11e7-8aa9-1edf8083b096.png)

### Show page for the child collection:
- accessible via the "Full Record" option from the child collection's search results page
- accessible via a link to subcollections in the metadata section of the parent collection's search results page
- "Browse objects in the collection" button links links back to child collection's search results page

![screen shot 2017-08-28 at 12 45 58 pm](https://user-images.githubusercontent.com/17851674/29783971-54b06f3a-8bf0-11e7-9c5b-3d9bda26b244.png)

**Comment by laritakr** [comment]
@samvera/hyrax-ui-ux-advisors
