### ISSUE TITLE
Collections-related forms: update Save button labels

### ISSUE THREAD

**Issue by ggeisler** [samvera/hyrax#1577]
Sub-ticket of #1527, which is about creating a more consistent user experience for new/edit forms for collection types, admin sets, collections, and works.

The recommendation is to use "Save" as the label for all new pages, and "Save changes" for the edit version of these pages.

### New pages
- New Admin Set: Currently "Save" so no action needed
- [ ] New Collection Type: Currently "Save" so no action needed
- [x] New Collection: Currently "Create Collection" - update to "Save"
- New Work: Currently "Save" so no action needed

### Edit pages
- [x] Edit Admin Set: Currently "Save" - update to "Save changes"
- [x] Edit Collection Type: Currently "Save" - update to "Save changes"
- [x] Edit Collection: Currently "Create Collection" - update to "Save changes"
- [x] Edit Work: Currently "Save" - update to "Save changes"

**Comment by blancoj** [comment]
This has been closed.

**Comment by elrayle** [comment]
* Collection -> Edit -> `Save changes` should be `Save`
* Collection Type -> New -> `Save changes` should be `Save`
* Collection Type -> Edit -> `Save changes` should be `Save`

**Comment by elrayle** [comment]
Remaining work:
#1855 Collection Types: New form save button should have label 'Save'

**Comment by elrayle** [comment]
All requirements are met by PR #1691 and the list of remaining work.
