### ISSUE TITLE
Collections-related forms: Forwarding action for Save/Cancel buttons

### ISSUE THREAD

**Issue by ggeisler** [samvera/hyrax#1578]
Sub-ticket of #1527, which is about creating a more consistent user experience for new/edit forms for collection types, admin sets, collections, and works.

## New pages
The current behavior for the Save button for the new collection type, admin set, collection, and work is good. There's a different flow for New Work than the other three, but that's based on how a work is created so it's okay.

For the Cancel button, updates are needed to be consistent among pages. The general recommendation is Cancel on a new page is to return to the appropriate index page.

- New Admin Set - okay as is
- New Collection Type - okay as is
- [x] New Collection - cancel currently goes to site root, should be updated to go to Collections index page
- [x] New Work - cancel currently goes to dashboard index, should be updated to go to Works index page

## Edit pages
The current behavior for the Save button for the edit collection type, admin set, collection, and work is inconsistent, with a couple of the pages going to a show page. Because the user could want to do any number of things after editing a tab in one of the pages (including more editing), I don't think we should send the user to a new context. When the user clicks "Save changes" on a tab on one of these pages, we should save the updates but remain on that tab. Note that in I think one case the current behavior is to return to the first tab, even if the user saves from another tab. I think we should remain on the _current_ tab. So the necessary changes are:

- [x] Save changes from Edit Admin Set:  stay on current tab
- [x] Save changes from Edit Collection Type:  stay on current tab
- [x] Save changes from Edit Collection:  stay on current tab
- [x] Save changes from Edit Work:  stay on current tab

For the Cancel button, updates are needed to be consistent among pages. The general recommendation is Cancel on an edit page is to return to the appropriate index page.

- Cancel from Edit Admin Set:  okay as is
- Cancel from Edit Collection Type:  okay as is
- [x] Cancel from Edit Collection:  currently goes to site root, should be updated to go to Collections index page
- [x] Cancel from Edit Work:  currently goes to dashboard index, should be updated to go to Works index page

**Comment by elrayle** [comment]
@ggeisler I am testing the PR for this.  I noticed that you have new collection forward to col show page instead of staying on the edit form.  I would have expected new form to forward to edit form upon save.  At that point, the additional tabs are shown and the user can complete setup.  Otherwise, they might not know that those other tabs and additional setup options even exist.

**Comment by elrayle** [comment]
@ggeisler As a user, I would expect cancel from new to go to the index (as you designate), but cancel from edit to go to the show page of the item that was being edited.  You have that also going to index.

**Comment by ggeisler** [comment]
@elrayle 

> I would have expected new form to forward to edit form upon save.

Yes, I would assume that too. I don't see where I specified otherwise, but in any case I agree with this.

> As a user, I would expect cancel from new to go to the index (as you designate), but cancel from edit to go to the show page of the item that was being edited. You have that also going to index.

I think what the user expects will depend on where the user has started the editing process. You can select a collection to edit from the index page, I believe, and if I start there and realize this is not the collection I actually want to edit, I'd expect to be taken back to the index page when I cancel, so I can select the collection I do want to edit.

If I start the editing process from the show page of a given collection, then sure, I'd expect to end up back at that show page after cancel.

So I see what you're saying, but am not sure it is as clear-cut as you say. That's only looking at it from one of multiple paths.

Ideally we'd support both potential paths with the ideal redirect after cancel (using history to know how the user got to the edit page). Not sure how feasible that might be.

**Comment by elrayle** [comment]
@bkeese Per discussion above and in slack...
- [ ] on new collection form - Update Collection (aka Save) should forward to edit form
- [ ] on edit collection form - Cancel should forward to collection's show page
- [ ] on edit work form - Cancel should forward to work's show page

**Comment by elrayle** [comment]
@ggeisler If edit work -> save stays in the edit form on the same tab, shouldn't new work -> save forward to edit and stay on the same tab?  This is a little different since all tabs show from the start.  But it seems like if it stays in edit when you start from edit, the behavior for new should be similar.

**Comment by elrayle** [comment]
Work is different enough that I would prefer it to have the following behaviors.
* new -> cancel -- forward to index
* new -> save -- forward to show
* edit -> cancel -- forward to show
* edit -> save -- forward to show

@ggeisler Your thoughts?  Going with this for now doesn't preclude moving toward forwarding/staying in edit upon save later.

**Comment by ggeisler** [comment]
@elrayle Sure, okay with me.

**Comment by elrayle** [comment]
## See PR for Remaining Work 

PR #1647 has a summary of this discussion with new/cancel forwards specified for each type.  There are checkboxes to click as each is verified in the UI.

**Comment by elrayle** [comment]
Remaining Work:

#1686 Collections: edit form does not show flash messages on save/update
