### ISSUE TITLE
Collections: Migrate existing permission templates to use new source_type column

### ISSUE THREAD

**Issue by hortongn** [samvera/hyrax#1580]
### Descriptive summary

Refs #1576

Issue #1538 created a new `source_type` column in the permission_template table.  If someone is upgrading their existing Hyrax-based app, all existing permission templates should have their `source_type` column set to "admin_set".  

### Expected behavior

We might be able to just do some type of automatic inline migration at the time the user runs db:migrate.  Otherwise, a separate rake can can accomplish this.

**Comment by hortongn** [comment]
@elrayle ☝️

**Comment by elrayle** [comment]
Source type was removed by PR #2382
