### ISSUE TITLE
Collection Types: Service for collection types a user can create

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1582]
### Descriptive summary

Create a service that returns the information about the collection types a user can create.

NOTE: Check with @laritakr who may have stubbed out a method to return all collection types.

### Rationale

Users are limited in which types of collections they can create based on the participant roles assigned to the user.

### Expected behavior

**Basic Rules:**  A user can create...
    * collection types where user has `manage` access for collection types by being a user with `manage` access
    * collection types where user has `manage` access for collection types by being in a group with `manage` access
    * collection types where user has `create` access for collections types by being a user with `create` access
    * collection types where user has `create` access for collections types by being in a group with `create` access

**Special cases:**
    * all collection types when user is an admin (i.e., in the `admin` group).  This will be achieved by setting access: `'manage'` agent_type: `'group'` agent_id: `'admin`' for each collection type as they are created.  This grant then follows the rules above.  For performance, we may want to take advantage of the fact that admins can manage all and just return all collection types if user.admin? is true
    * registered user without any special access can create `user_collection`.  This will be achieved by setting  access: `'create'` agent_type: `'group'` agent_id: `'registered`' for `user_collection`.  This grant then follows the rules above.

### Steps to reproduce the behavior

1. Create users `admin@ex.com`, `mgr1@ex.com`, `mgr2@ex.com` , `cr1@ex.com`, `cr2@ex.com`, and `other@ex.com`
1. Need groups `mgr_group` and `cr_group`
  1. add `mgr2@ex.com` to `mgr_group`
  1. add `cr2@ex.com` to `cr_group`
1. Login as an `admin@ex.com`
1. Dashboard -> Settings -> Collection Types
1. Create a collection, save, and edit
1. On Participants tab
  1. add user `mgr1@ex.com` as a manager
  1. add user `cr1@ex.com` as a creator
  1. add group `mgr_group` as a manager
  1. add group `cr_group` as a creator
1. Save

Calling service should return ids for...
* for `admin@ex.com`: [admin_set, user_collection, new_collection]
* for `mgr1@ex.com`: [user_collection, new_collection]
* for `mgr2@ex.com`: [user_collection, new_collection]
* for `cr1@ex.com`: [user_collection, new_collection]
* for `cr2@ex.com`: [user_collection, new_collection]
* for `other@ex.com`: [user_collection]

NOTE: 
* By default, admin_set can only be created by admins.  
* By default, user_collections can be created by all registered users.

### Dependencies

The following issue should be completed first in order to not require revisiting this issue.

#1581 Collection Types: Change manager to manage and creator to create for participants access

### Related work

#1345 Collection Types: Create participants partial of the new/edit form

**Comment by laritakr** [comment]
I added a stub in [the CollectionType model](https://github.com/samvera/hyrax/blob/collections-sprint/app/models/hyrax/collection_type.rb). It has not yet been merged from the #1506 branch.

`def self.collection_types_for(user = current_user)`

**Comment by kdid** [comment]
PR - #1603 opened

Note that this does not address returning user collection type if the user is registered. (If this access type is generated along with the default user collection type, this may not be needed and the groups search would return the right access.)

**Comment by elrayle** [comment]
PR #1622 added participants for the two pre-defined collection types...  user_collection and admin_set.  This addresses @kdid's comment about user collection type being returned for registered users.  #1622 sets up the participants such that these are not special cases for the permissions service.
