### ISSUE TITLE
Background jobs should be wrapped by operations

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#160]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Aug 26, 2016 at 20:47 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2572_

----

Does not include event jobs _except_ for the `ContentDepositorChangeEventJob`. This should be done in both CC and Sufia.

See #2571 for more information about operations.

**Comment by no-reply** [comment]
@mjgiarlo is there more context that would make this actionable? I'm uncertain how consistently operations are used in general, and what their design goals are.

**Comment by mjgiarlo** [comment]
Operations were never fully rolled out -- @jcoyne did the initial implementation to at least expose information about jobs that power file uploads, as a way to surface information about currently running tasks via the UI. There is a bit more context here: https://github.com/samvera/hyrax/issues/159#issue-197058309

I'd be happy to jump on a quick call sometime to discuss further.

**Comment by mjgiarlo** [comment]
cc: @vantuyls

**Comment by no-reply** [comment]
closing this. I don't think operations are on the current roadmap and we'll probably overhaul with some kind of observer if these requirements resurface.
