### ISSUE TITLE
Dashboard should allow users the ability to list and show operations they created

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#161]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Aug 26, 2016 at 20:47 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2573_

----

See #2571 for more information about operations.

The dashboard should allow the ability for users to see a list of operations they created and to show individual operations to view more information.

The list of operations should contain a type and status for each operation.

The show view for an operation should show its status and any messages that have been stored on the operation (i.e., about what caused a failure). It should also show the type, status, and message for any children operations.

Needs UI design.

**Comment by no-reply** [comment]
Closing this, as it's not clear what the future of `Hyrax::Operation` will be.
