### ISSUE TITLE
Collection Types: index view should verify user is admin for new, edit, delete actions

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1619]
### Descriptive summary

There is a check in the sidebar to be sure a user can manage collection types, but there are no checks on the index view itself.  There should be a check for admin? before allowing new, edit, or delete actions.

### Rationale

Users shouldn't be able to see the collection types page unless they are admins, but for security purposes, management actions should verify the users abilities before being performed.  Putting this in place also allows for finer grain controls in the future, such as, a user may be able to create and edit, but not delete.

### Implementation

Admin Sets do this be showing/hiding the new button when the page is created.
```
<%if can? :create, CollectionTypes %>
  # show new button
<% end %>
```

Something similar can be done for the Edit and Delete buttons.

### Steps to reproduce the behavior

You won't be able to test this through the UI.  If you try to access this page as a non-admin, you get `not authorized` message and are forwarded to home.

See how Admin Sets test this.  They have a similar authorization and abilities approach.

### Related work

#1349 Collection Types: Create index views for managing collection types

Other issues effecting the index page...
-  #1341 - We added a `collections?` method to the CollectionsType model so that we could simulate different modals for empty vs full collection types. This will need to be changed when we have implemented a way to find collections that belong to a collection type.
 - #1524 - Added `collection_type.machine_id != 'admin_set'` as a placeholder to check if the collection type was admin set. Not sure what the final check will be yet.
 - #1341, #1525 - Actual delete functionality not wired up yet
 - #1526 - Button to take you to 'View collections of this type' (if unable to delete because collection type has collections) not wired up yet

**Comment by laritakr** [comment]
This issue is unnecessary. The collection types controller already does the appropriate `authorize! :manage, :collection_types` as a before_action. The specs test each controller method for anonymous or unauthorized access, and expect a redirect.
