### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by maureenbianca** [samvera/hyrax#1625]
I run the this command: rake hyrax:workflow:load and I got this error. What could be the issue?

ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: permission_templates: SELECT "permission_templates".* FROM "permission_templates"

**Comment by jcoyne** [comment]
It looks like you're attempting to load workflows before creating the database schema.  Make sure you run `rails generate hyrax:install` first.  I'll note that this isn't on the README and it probably should be.

**Comment by mjgiarlo** [comment]
@biancachebet Could you say more about what you're trying to do and what you've done already? Did you install using the installation template (per the README)? What version of Hyrax are you using?

Generally, you shouldn't have to use that rake task unless you've customized the workflows. What instructions are you following?

@jcoyne The README has folks install via template, which itself calls the install generator. And does not instruct users to use the workflow loading task. So I'm not sure what README change you're suggesting.

**Comment by biancachebet** [comment]
@jcoyne I run rails generate hyrax:install and it worked well. However, I noticed my user did not have the right privileges and I used another user and it did work pretty well. Thank you!

**Comment by rjkati** [comment]
@jlhardes looks like this issue may be resolved.

**Comment by jlhardes** [comment]
This issue is resolved and closed.
