### ISSUE TITLE
config option to turn off live notification count update

### ISSUE THREAD

**Issue by jrochkind** [samvera/hyrax#1633]
Whether current implementation or new implementation in #1624 

Live notification count update is tricky to implement, and has the potential to add non-trivial  infrastructural overhead. Implementers should have the option of turning it off if it is not necessary to their business cases and they'd rather avoid the headache, or if they find it is buggy.  With new websocket implementation, it may be even more useful to have the option to turn off the feature in case it is initially buggy, but I think some would have appreciated even with existing implementation.

**Comment by mjgiarlo** [comment]
I suggested we wait until #1624 is merged before we take this on. It will be much easier to tackle afterward, since that PR consolidates notifications to a single spot: a new `MessengerService`.
