### ISSUE TITLE
User edit profile page should show user role

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#165]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Thursday Sep 01, 2016 at 22:04 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2611_

----

Non Admin User can view their role on their profile page (read only). Admin User can edit the role on the profile page. 
- [ ] Requires a UI for selecting from available roles 

Decomposition of #2421

**Comment by mjgiarlo** [comment]
Roles are now Admin Set-specific, other than the admin role. Do you think this still makes sense to surface on the edit profile page? We're managing roles in the admin dashboard. I'm feeling like this probably needs design input, so should move to a latter phase. @vantuyls @hannahfrost @scholarworks

**Comment by hannahfrost** [comment]
@mjgiarlo I agree. Defer after some design input, and not an immediate priority. Flagging for consideration by @ggeisler when it's convenient.

**Comment by no-reply** [comment]
Closing this as there is now a workflow roles page in the Dashboard.
