### ISSUE TITLE
Should derivatives be moved out of tmp/ by default?

### ISSUE THREAD

**Issue by emanuil-tolev** [samvera/hyrax#1660]
Derivatives are stored under Rails.root/tmp/derivatives by default.

The thing is, they're not a temporary artefact. They're produced and then served from that directory.

Use of tmp/ usually implies (to me) things that are necessary for the app to function, but are perhaps only important within the lifetime of 1 app start-up, like pidfiles or temporary upload ingestion space. So, for example, I wouldn't make tmp/ a Docker volume in a dockerised Hyrax, and everything in it would go away when a container is restarted or a new one started.

However, derivatives are actual data - content that needs to be preserved across server migrations, docker container restarts, etc. If they're not stored in Fedora or a database, then they should probably live in a separate folder that makes it clear they're user-generated data and need backing up, etc. Rails.root/derivatives maybe?

(I understand you can configure the path to be whatever you want, indeed we've done that, but I thought it odd that permanent data relating to deposits was stored in tmp/.)

EDIT: For ref:

https://github.com/samvera/hyrax/blob/5c998ca56ff3bd765fc2c37cc7071aedc05113e7/lib/hyrax/configuration.rb#L52
https://github.com/samvera/hyrax/blob/7bab4b6d6dcda117aa8a97230f07310d55fe0554/lib/generators/hyrax/templates/config/hyrax.rb#L128

**Comment by mjgiarlo** [comment]
@emanuil-tolev Good call.

I'm going to tag in @samvera/hyrax-code-reviewers about this. (And this is where I start wondering if we could use a DevOps-oriented GitHub team!)

In the meantime, do you have any suggestions for other directories that could work for this? (Ones that we can safely assume will already be in place where Hyrax is run and deployed?) Thanks.

**Comment by emanuil-tolev** [comment]
> In the meantime, do you have any suggestions for other directories that could work for this? (Ones that we can safely assume will already be in place where Hyrax is run and deployed?)

Well ... where can we store assets safely on a file system? I don't think we can implicitly rely on any one directory. We could do `Rails.root/derivatives` (so just move it out of tmp). And make people very aware (in template config, wiki, etc.) that this data needs to be preserved. Storing anything on disk is always a bit of a pain.

I'd have suggested S3 or similar connectors but they're a bit too slow to be used in regular record page loading to be honest, so I can't really see much of an option besides local disk and make sure the dir is backed up.

**Comment by mjgiarlo** [comment]
@emanuil-tolev OK, thanks. I'd like other @samvera/hyrax-code-reviewers folks to sound off on their preferences.In the meantime, do you think the documentation here is sufficient? https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#derivatives

**Comment by rjkati** [comment]
Closing since documentation is in place
