### ISSUE TITLE
Collections:  Calculate the number of items in a collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1670]
### Descriptive summary

Calculate the number of items in a collection for use in the UI.  It is displayed with the collection in search results, on collection show pages, and in the list of collections in All/Your Collections.

### Rationale

Number of items may indicate to the user the usefulness of the collection.

### Expected behavior

See `services/hyrax/collections/managed_collections_service.rb` which has method `managed_collections_count`.  A similar approach can be used for this issue.  (added with PR #1655)  It performs the count in the context of the current user.

Also, there is a method on the [collection model](https://github.com/samvera/hyrax/blob/collections-sprint/app/models/concerns/hyrax/collection_behavior.rb) that gives the count of the number of items.

NOTE: Count should be the number of items a user can view.  So the count number can change based on the current users permissions.

Questions:
* Is this already calculated somewhere?
* Is this or can this be calculated at indexing time?  No, since it is user specific.
* I have some performance concerns with attempting to calculate this on the flight.  I believe that PR #1655 uses solr query to count the results without fetching data.

This issue includes the UI modifications to display the counts.  Depending on calculation method, the display may need to be done with ajax to avoid delaying the display of the page.  

NOTE:  @adamjarling is willing to do the UI side of things.

### Steps to reproduce the behavior

1. create a collection with at least 3 works in it
1. Dashboard -> Collections

Verify that the list of collections has the correct number of works listed under items.  See mockup.

1. Search for your collection

Verify that the search result that is the collection has the correct number of works listed with it.  See mockup.

#### Dashboard -> Collections -> list of collections

![image](https://user-images.githubusercontent.com/6855473/30441810-7c80b136-9948-11e7-887e-eda69e457270.png)

#### Search results

![image](https://user-images.githubusercontent.com/6855473/30441935-e32391ba-9948-11e7-8b53-d3cce0c05e58.png)

### Related work

#1509 Collections: Update UI/UX of the listing of collections in the All/My Collections index
#1655 See `services/hyrax/collections/managed_collections_service.rb` which has method `managed_collections_count`.  A similar approach can be used for this issue.

**Comment by elrayle** [comment]
Ran across this code for admin_sets.  I wonder if we can do something similar for collections.

[app/services/hyrax/admin_set_service.rb](https://github.com/samvera/hyrax/blob/collections-sprint/app/services/hyrax/admin_set_service.rb)

Although this looks like it is counting number of files for all works in the admin set instead of number of works.

**Comment by elrayle** [comment]
@ggeisler Can you confirm your expectations on the various counts that are displayed?

All/Managed/Your Collections 
- for each collection, `item count = #works + #sub-collections`

Search Results 
- `work count = #works`
- `collection count = #sub-collections`

For all, the counts are just one level down.  They don't include counts of children of children, etc.

NOTE: Since admin sets are listed with collections now, that means `item count = #works`.  When admin sets were listed separate, `item count = #files in all works`

**Comment by ggeisler** [comment]
@elrayle Your description matches my expectations.

It might or might not be relevant that the [Analytics WG](https://wiki.duraspace.org/display/samvera/HAWG+-+Tuesday+September+12%2C+2017) is currently trying to define similar metrics related to aggregation; e.g., how many views and downloads a collection has when that collection contains sub-collections and works, which contain files.

**Comment by elrayle** [comment]
@laritakr brought up yet another wrinkle in the counts...  do we count only items the user can see?

@ggeisler How does the user know what the counts mean?  Will there be helper text on the table heading for All/Managed/Your Collections?

**Comment by ggeisler** [comment]
@elrayle I'd say the counts should be of things that user can view. 

Not sure I understand the question of how does the user know what the counts mean. What needs explained, exactly? If you're referring to whether we need to explain to the user that the counts only include items they can view, I'm not sure I understand why that needs explained.

**Comment by elrayle** [comment]
I can go with the idea that the numbers are self explanatory.  I was wondering about the confusion caused by user A seeing col_1 with count=15 and user B seeing col_1 with count=13.  This scenario arises when user A has edit access to two private works in the collection that user B doesn't.  But maybe having different counts will help them figure out why they see things differently.

**Comment by laritakr** [comment]
Since deleting a collection requires all members to be gone, it might be important to show the count of all items somewhere.  I believe the metadata itself includes this total, but we might want to change the title to somehow show that it includes ALL items not just the items available to you.

I'd suggest there might be a use for the following counts:

1. total items in collection regardless of permissions (this is included in the collection's metadata.)
2. total permitted members in collection (direct members only, not descendants, sum of #3 & 4)
3. total permitted works in collection (works only, direct members only, not descendants) 
4. total permitted sub-collections in collection (collections only, direct members only)

Where counts are shown other than total members, perhaps the labels could somehow indicate that the counted items are only ones you have permission to see... "Accessible items", "Permitted Items", etc?  I'm not sure what the right term might be, but using a different title than the one in the metadata will help emphasize that these are not intended to add up.

**Comment by elrayle** [comment]
> Since deleting a collection requires all members to be gone

Collections can be deleted even if they have members.  Admin sets cannot be delete until they are empty.  If you see an issue that states otherwise, can you bring it to my attention?  There was a period of time when we did discuss collections needing to be empty, so it is possible there are outdated descriptions hanging around.

RE: Your suggestions for counts...  I'm thinking we go with 2-4 including only accessible items for this issue.  

Then there will be a follow on issue for the UI/UX discussion about whether there is also a need for all items regardless of accessibility.  It seems like the admin might have need of counts based on visibility public vs. registered vs. private, but for everyone else it is whether or not they can see it.  I'm inclined to push that deeper conversation to the UI/UX working group or the Analytics WG mentioned earlier.

**Comment by ggeisler** [comment]
I also wonder if it is possible for a user who has permission to delete a collection/admin set to not have permission to see all items in that collection? I wouldn't think that could happen, but I could be wrong.

I definitely think the page (and others) could use more thought regarding how we show counts and to make sure we're consistent with what we end up doing for the analytics-related pages. I don't have time to do that so going with what you think is best for now and having a more thorough analysis with others later seems like a good approach to me.

**Comment by elrayle** [comment]
Remaining work:
#1745 Collections: Add counts to search results

**Comment by elrayle** [comment]
All requirements are covered by PR #1739 or issues for the remaining work.  Closing this issue.
