### ISSUE TITLE
Collections: Make admin show page match mockup

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1678]
### Descriptive summary

Make the admin show page match the mockup.  The current UI implementation does not.

### Implementation

View files for the admin show page are located at...

[app/views/hyrax/dashboard/collections](https://github.com/samvera/hyrax/tree/collections-sprint/app/views/hyrax/dashboard/collections)

### Mockup

![admin-collection-show](https://user-images.githubusercontent.com/101482/28979760-dc6bde68-78ff-11e7-8a35-3f859bebdd9f.png)

### Related UI work

#1427 - PR #1562 - Add content to dashboard collections show page
#1552 - PR #1632 - Add new work to collection from collection show page
#1586 - PR #1629 - Show page should only provide Remove action for works and sub-collections

### Related work

| Collections feature | Issue |
| ------------------------ | ----- |
| Routes                   | #1380 |
| Controller               | # |
| Model                    | #1383 |
| View - Index            | #1417 |
| View - Show - Admin      | #1427 |
| View - Show - Landing    | #1428 |
| View - New/Edit          | #1374 |
| Partial -  Description   | #1375 |
| Partial -  Branding      | #1376 |
| Partial -  Relationships | #1377 |
| Partial -  Sharing       | #1378 |
| Partial -  Discovery     | #1379 |

**Comment by elrayle** [comment]
Mockup with nesting...

![image](https://user-images.githubusercontent.com/6855473/32258064-dae318de-be8e-11e7-89f8-3b223be43e47.png)

**Comment by adamjarling** [comment]
This code is now on an updated branch:  https://github.com/samvera/hyrax/tree/collections-%231678-collections_admin_show_page_updated

Notes:
- Create a new issue for the "Parent Collection" display.
- Create new issue for "Delete collection" button to be a modal and consistent with other delete patterns.
- more to come...

**Comment by adamjarling** [comment]
@elrayle For the Parent Collection HTML above, should be something like:
```
<h4>Parent Collection</h4>
<p><a href="#">Parent Collection Title Here</a> <strong>(23)</strong></p>
```

**Comment by adamjarling** [comment]
@elrayle Should this be closed out?

**Comment by vantuyls** [comment]
closing this issue as most (all?) of the work has been completed and in deference to design on a more recent issue: https://github.com/samvera/hyrax/issues/3376
