### ISSUE TITLE
Edit work form -> Relationships tab does not select collections

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1683]
### Descriptive summary

Effects: master

The collections in which a work is a member should be selected on the Relationships tab when editing the work.  Currently, they are not.  If the user saves without setting the collection, then the work is removed from the collection it was in prior to editing.

### Rationale

Works should stay in a collection until a specific action is taken to remove them.

### Expected behavior

If a user edits a work and does not visit the Relationships tab, it will be in the same works before and after editing.

### Actual behavior

If a user edits a work and does not visit the Relationships tab, the work is removed from all collections it was in before the edit.

### Steps to reproduce the behavior

1. create a new collection -- Dashboard -> Collections -> New Collection -> set title -> Save
1. create a new work -- Dashboard -> Works -> Add new work -> select any type -> Create work
1. set all required fields
1. click Relationships tab and select the collection you created
1. Save

On the work show page, verify that near the top it says it is in the collection you put it in.

1. Edit the work -> Save (Don't need to make any changes.)

Verify that the work is still in the collection you put it in.

### Related work

#1578 - PR #1647 - Fix redirects for collection/work edit save and cancel

**Comment by mjgiarlo** [comment]
Refs https://github.com/curationexperts/nurax/issues/94
