### ISSUE TITLE
Collections: edit form does not show flash messages on save/update

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1686]
### Descriptive summary

A flash message is being set in the controller when a collection is saved/updated, but it does not display on the edit form once the process completes.

### Rationale

Flash messages are used for save/update in Collection Types, Admin Sets, and Works.  They should also be displayed for Collections.

### Expected behavior

A flash message should appear at the top of the collection edit form when...
* a new collection is created and forwards to the edit form for more edits
* a collection is updated through the edit form and it stays on the edit form for more edits

See flash messages set in [app/controllers/hyrax/dashboard/collections_controller.rb](https://github.com/samvera/hyrax/blob/collections-sprint/app/controllers/hyrax/dashboard/collections_controller.rb)...
* new collection: #after_create
 ` format.html { redirect_to dashboard_collection_path(@collection), notice: 'Collection was successfully created.' }`
* update collection: #after_update 
` flash[:notice] = 'Collection was successfully updated.'`

### Actual behavior

A flash message does NOT appear at the top of the collection edit form when...
* a new collection is created and forwards to the edit form for more edits
* a collection is updated through the edit form and it stays on the edit form for more edits

### Steps to reproduce the behavior

1. create a new collection: Dashboard -> Collections -> New Collection -> set title and save

Verify forward to edit form and a flash message is displayed `'Collection was successfully created.'`

1. save again

Verify forward to edit form and a flash message is displayed `'Collection was successfully updated.'`

### Related work

#1578 - PR #1647 Fix redirects for collection/work edit save and cancel

**Comment by gordonleacock** [comment]
The code:
**format.html { redirect_to dashboard_collection_path(@collection), notice: 'Collection was successfully created.' }**
does work, but it doesn't show the flash notice when it is:
**format.html { redirect_to edit_dashboard_collection_path(@collection),  notice: "Collection was successfully created." }**
which it currently is. That is, when it goes to the edit page instead of the show page.

Still trying things to fix this.

**Comment by elrayle** [comment]
Requirements met by #1728.  Closing.
