### ISSUE TITLE
Review Queue Index Page edit and approve item buttons need to exist

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#170]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Thursday Sep 01, 2016 at 23:07 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2620_

----

Each item in the RQIP should have two buttons associated with: 1) Edit and 2) Approve

Edit Button - takes the user to the Show Page for the item where they can review and edit

Approve Button - approves the item at this step of the workflow. Selecting the Approve Button advances the workflow counter (e.g. from step 2 of 4 to step 3 of 4, because i've just completed the current workflow step).

Decomposes #2426 and #2445

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 22:53 GMT_

----

Defer until 1+-step workflow work starts.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Saturday Oct 29, 2016 at 00:44 GMT_

----

This should be decomposed into two tickets, one for the approve button (probably already done) and one for the edit.  I'm not sure that "reviewers should be able to edit" is something that everyone will want.  Thoughts?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Oct 31, 2016 at 14:31 GMT_

----

@jcoyne 

>  I'm not sure that "reviewers should be able to edit" is something that everyone will want. 

No, it's not. Though it might be for many or most folks opting in to a workflow that includes a "metadata review" step? (We're not talking about that step being in one of the default workflows though, are we?)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Monday Oct 31, 2016 at 14:56 GMT_

----

@mjgiarlo right, but metadata review could be "this is terrible, do it again, make sure to add a title"

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Oct 31, 2016 at 15:01 GMT_

----

@vantuyls @scholarworks @hannahfrost What are your expectations re: a "metadata review" workflow step? Do you want the reviewer to edit the metadata directly, or send it back to the submitter with comments?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Oct 31, 2016 at 15:06 GMT_

----

i think that review step could be either a direct edit or a comment à la "this is terrible". 

does this call for a "metadata review" step and a "metadata edit" step?

also, i don't thing the metadata edit step fits in one of the pre-packaged workflows, but it will likely be included in the first new workflow we build locally (or for that matter, any of the DSpace based repositories that migrate build).

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Oct 31, 2016 at 15:11 GMT_

----

@vantuyls 

> also, i don't thing the metadata edit step fits in one of the pre-packaged workflows, but it will likely be included in the first new workflow we build locally (or for that matter, any of the DSpace based repositories that migrate build).

Good point. I agree with this assessment, and I suspect that many institutionally built workflows will wind up including this step. That doesn't mean we need to solve this in Sufia, though.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hannahfrost"><img src="https://avatars.githubusercontent.com/u/1801076?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hannahfrost](https://github.com/hannahfrost)**
_Monday Oct 31, 2016 at 23:52 GMT_

----

@vantuyls @mjgiarlo In my view, any review step could be a direct edit or a comment-and-return. I do not feel there is a need for two distinct steps - (1) metadata review and (2) metadata edit  - and I feel pretty strongly about that.

**Comment by mcdowney** [comment]
I think this has been addressed through the mediated deposit implementation (there is now a review and approval menu for items in the review queue). Closing for now.
