### ISSUE TITLE
Collections: Show no permission/not nestable dialog when user clicks `add collection to collection` and can't nest

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1707]
### Descriptive summary

Dashboard -> Collections -> Manage Collections should always show `add collection to collection` action for a collection UNLESS there are no nestable collections in the system.  If a user clicks `add collection to collection` and they can't perform an action show a dialog explaining why they can't.

### Rationale

Educate the user when they cannot perform an action.

### Expected behavior

In Dashboard -> Collections -> Manage Collections...

- [ ] If there are 0 collection types with nestable? = true, then DO NOT show `Add collection to collection` in the action menu
- [x] otherwise, always show `Add collection to collection` in the action menu

If user clicks `Add collection to collection` in the action menu...
- [x] if `collection.nestable? == false`, then show dialog "Collections of this type `<%= collection_type.title %> do not support nesting."
- [ ] else `if can? deposit, collection`, then execute the action
- [x] else show dialog "You do not have sufficient privileges to add a collection to this collection"

### Steps to reproduce the behavior

Test via UI and write equivalent rspec tests for...

Scenario 1: 0 collection types that are nestable

1. Login as admin
1. Create two users, user 1 and user 2.
1. Create a collection type with title 'Not Nestable'  that has nestable? false and participants Create group='Registered' and Manage user=user 1
1. Make sure all other collection types nestable? false (NOTE: May have to delete User Collection through rails console since it has nestable? true and is not editable.)
1. Login as user 1
1. Create a collection of type 'Not Nestable'
1. click Dashboard -> Collections

- [x] verify that 'Add collection to collection' is NOT in the action menu for any collection in the list

Scenario 2: At least 1 collection type is nestable

1. Login as admin
1. Create two users, user 1 and user 2.
1. Create a collection type with title 'Not Nestable'  that has nestable? false and participants Create group='Registered' and Manage user=user 1
1. Create a collection type with title 'Nestable'  that has nestable? true and participants Create group='Registered'
1. Login as user 1
1. Create a collection of type 'Not Nestable' with title 'Col - not nestable + manage' and grant user 2 Manage access
1. Create a collection of type 'Nestable' with title 'Col - nestable + manage' and grant user 2 Manage access
1. Create a collection of type 'Nestable' with title 'Col - nestable + deposit' and grant user 2 Deposit access
1. Create a collection of type 'Nestable' with title 'Col - nestable + view' and grant user 2 View access
1. Login as user 2
1. Dashboard -> Collections -> Managed Collections
1. click 'Add collection to collection' in action menu beside collection 'Col - not nestable + manage'

- [x] Verify dialog is displayed with text "Collections of this type Not Nestable do not support nesting."

1. click 'Add collection to collection' in action menu beside collection 'Col - nestable + manage'

- [x] Verify modal to select sub-collection is displayed

1. click 'Add collection to collection' in action menu beside collection 'Col - nestable + deposit'

- [x] Verify modal to select sub-collection is displayed

1. click 'Add collection to collection' in action menu beside collection 'Col - nestable + view'

- [x] Verify dialog is displayed with text "You do not have sufficient privileges to add a collection to this collection"

### Related work

#1655 See changes and TODO in app/views/hyrax/my/_collection_action_menu.html.erb

**Comment by laritakr** [comment]
@elrayle Does the following look correct to you?

In order to override the standard `can? :edit, Collection` behavior, I believe this will require the following changes to incorporate the permission check for the specific collection id. 

- [ ] Add a public method in hyrax/collections/permissions_service.rb similar to the can_deposit_in_collection method.
`can_manage_collection(user:, collection:)` 
- [ ] define a private method in ability.rb (perhaps collection_access_permissions) which implements the `can?(:edit, Collection)` method from [issue 1669](https://github.com/samvera/hyrax/issues/1669), where this test is defined something like:
`can :edit, Collection if Hyrax::Collections::PermissionsService.can_deposit_in_collection() && Hyrax::Collections::PermissionsService.can_manage_collection()`
- [ ] Add the method to the self.ability_logic list so it gets executed with each ability call

**Comment by laritakr** [comment]
@elrayle A concern with the above might be if the permission template has changed, where someone who was initially not given access to the collection via the permission template, and therefore didn't get edit access on the collection, would now have access to create a nested collection in it via the revised permission template. Is this what we want? Or would we simply want to verify standard edit access? Which is the definitive source of this permission?

**Comment by elrayle** [comment]
We've been talking about ability to edit (me included), but the actual ability we need to check is whether the user can deposit in the collection.

* can :edit, Collection should be true, only for users that have `edit_access` in the solr doc as an individual user or by group membership.  This matches the normal way of checking edit access, so I don't think we need a special method for that.  Managers are added to the `edit_access` field.  This ability check will not be used for `add collection in collection`.  It is included here to clarify what `can :edit` should check.

* can :deposit, Collection should be true if [Hyrax::Collections::PermissionsService.can_deposit_in_collection(user:, collection:)](https://github.com/samvera/hyrax/blob/collections-sprint/app/services/hyrax/collections/permissions_service.rb#L73-L86)  is true

I think that is the only part of #1669 that is applicable to this issue.  And the only check that needs to be made is for each collection is `can? :deposit, collection`, only showing `add collection to collection` if it returns true.

**Comment by elrayle** [comment]
Remaining Work:
* list of available_parent_collections should include collections with deposit access
* based on the current definition of available_child_collections, only read access is required, which implies that for nestable collections, add_to_collection should always be an available action

**Comment by elrayle** [comment]
All requirements are met by PR #1812 or the remaining work issues.  Closing.
