### ISSUE TITLE
Collections: UI/UX question regarding checkboxes for AdminSets on Collections index page

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1708]
### Descriptive summary

As part of PR #1655, admin sets were added to the collections index page.  This page allows bulk delete of collections.  Since admin sets require additional checks before allowing delete, the checkboxes weren't added for admin sets.

QUESTIONS: 
* Should the checkboxes be added for all admin sets or just those that are empty?
* If they are added for all, what happens when the user selects one that is not empty?  Non-empty admin sets cannot be deleted.

### Steps to reproduce the behavior

1. Login as admin
1. Create an admin_set and a collection
1. Dashboard -> Collections

See that the admin_set does not have a checkbox and the collection does.

### Related work

#1655 Include admin sets in collection search builders.
#1510 Update index to handle bulk actions for collections
#1788 Batch delete should show message if fails

**Comment by elrayle** [comment]
Issue #1788 has a similar question about UI/UX of checkboxes for Dashboard -> Collections

**Comment by elrayle** [comment]
@ggeisler commented on #1510 which implemented batch delete for collections.

> RE: not including the checkbox next to admin sets. I assume this only applies to admin sets that are not empty? In other words, if an admin set is empty, then you would present the checkbox (assuming the user has delete privileges), since the admin set in that case is eligible for deleting.

**Comment by ggeisler** [comment]
Similar to #1788, I'd disable rather than hide the checkboxes.

**Comment by elrayle** [comment]
Answered in #1788.
