### ISSUE TITLE
Collections: admin user fails can? destroy on collection show page

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1717]
### Descriptive summary

The Delete button is hidden unless `can? :destroy` is `true`.  This should be true for admin users.  It is not true when checked on the admin show page for a collection.

### Rationale

Admins should be able to do everything.

### Expected behavior

The Delete button should always be visible to admins on the admin show page for a collection.

### Actual behavior

The Delete button is NOT visible when the admin did not create the collection.

### Steps to reproduce the behavior

1. Create two users A (admin) and B (non-admin)
1. Login as user B
1. Create a collection 'col-1'
1. Login as user A, the admin user
1. Dashboard -> Collections -> All Collections -> click 'col-1'

Verify that the Delete button is displayed beside the Edit button in the top right of the show page.

**Comment by blancoj** [comment]
@elrayle I just tested this and I don't see a problem.  I see the Delete button next to the Delete button on the landing page.  I created the coll as user abc ( not an admin ), then logged in as an admin.
<img width="1588" alt="screen shot 2017-09-26 at 2 50 48 pm" src="https://user-images.githubusercontent.com/11095558/30878270-513c3bfe-a2ca-11e7-865d-757f69592ea9.png">

**Comment by elrayle** [comment]
I agree.  This does not seem to be a real issue.  Closing.
