### ISSUE TITLE
On the item ingest page, as an admin, I should have a button that bypasses the review workflow

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#173]
<a href="https://github.com/straleyb"><img src="https://avatars.githubusercontent.com/u/6424683?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [straleyb](https://github.com/straleyb)**
_Tuesday Sep 06, 2016 at 16:18 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2634_

----

When logged in as an administrator, a user should be given a button to save and review. Instead of save and add to review queue.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Sep 06, 2016 at 17:57 GMT_

----

Perhaps a button like GitHub's merge button which provides two choices (merge commit or squash merge)?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hortongn"><img src="https://avatars.githubusercontent.com/u/5639859?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hortongn](https://github.com/hortongn)**
_Thursday Sep 22, 2016 at 20:01 GMT_

----

@vantuyls @mjgiarlo I think I've resolved this issue with #2617.  In my #2617 if an admin creates a new work, the form has radio buttons to save the new work as active or inactive (defaults to inactive).  So this effectively allows an admin to by bypass the review process by saving a new work as active (approved) if they choose.  

What do you think?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Thursday Sep 22, 2016 at 20:02 GMT_

----

Hi, @hortongn. Do only admins see the new button?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Sep 23, 2016 at 14:37 GMT_

----

Tagging @jeremyf @elrayle for comment, as we discussed this in the context of CC's inclusion of Sipity workflows.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/elrayle"><img src="https://avatars.githubusercontent.com/u/6855473?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elrayle](https://github.com/elrayle)**
_Friday Sep 23, 2016 at 14:44 GMT_

----

A configuration that allows actions based on roles could be configured to add an action that allows an **admin** to go straight from **new_state** to **published_state**; while other users with none-admin roles have many other steps between.

This will work with simple workflows that limit actions to those available in the New Work UI.

If you have a more complex workflow where one step is an **external metadata enhancement** state, you would not want to jump from **new_state** to **published_state** because the enhancement would never happen.  The jump is not a play through all states.  It is a jump that skips the normal in-between states.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 22:38 GMT_

----

Defer this ticket until we have working 1+-step workflow.

**Comment by julesies** [comment]
As of 2.0, there is a review and approval button that Admins can use in mediated deposit. Closing this, but please reopen if I'm missing something about the functionality.
