### ISSUE TITLE
Collection Types: switch order of settings require membership and multiple membership

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1730]
### Descriptive summary

On Collection Types -> Settings tab, move Multiple Membership above Require Membership.

### Rationale

This groups the 3 admin set only settings together as the last 3 settings on the tab.

### Expected behavior

No behavioral changes.

### Steps to reproduce the behavior

1. Dashboard -> Settings -> Collection Types -> edit User Collection -> Settings tab

Verify the order of settings as...
* Nestable
* Discovery
* Sharing
* Multiple Membership
* Require Membership
* Workflow
* Visibility

**Comment by blancoj** [comment]
Fix was merged into collections-sprint branch
