### ISSUE TITLE
Full Libreoffice install required for conversions

### ISSUE THREAD

**Issue by amccarty** [samvera/hyrax#1731]
Is there a minimal subset of Libreoffice binaries and libraries required for generating derivatives? While it's not a major problem for a single instance, I feel like a full installation is a bit heavy, especially for those of us who might be deploying to Elastic Beanstalk, etc. Currently the Linux flavor of Libreoffice weighs in at ~250MB:
```
du -h LibreOffice_5.4.1.2_Linux_x86_rpm/RPMS/
254M	LibreOffice_5.4.1.2_Linux_x86_rpm/RPMS/
```
Again, this isn't a major concern, just figured I'd see if there's a way around a full install.

Thanks!

**Comment by mjgiarlo** [comment]
@amccarty Good question! I'm not entirely sure. Would you be willing to explore this and drop your findings here?

**Comment by rjkati** [comment]
Closing due to lack of feedback
