### ISSUE TITLE
Notification via email should be an option

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#174]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Tuesday Sep 13, 2016 at 21:27 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2683_

----

email should be an option for sending notifications to users/admins/etc.

there are likely a number of things to unpack here (though not all are immediately in scope) including:
- [ ] How Sufia finds the email address of the user (in the user's profile? somewhere else?)
- [ ] User controls for opting in to or out of email messaging
- [ ] Possibility of receiving digest emails (e.g. if i deposit 100 items a day, i don't want 100 emails)
- [ ] Ability to edit the email message sent, or just use a stock message (e.g. "you have a new notification in Sufia")

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Tuesday Sep 13, 2016 at 21:28 GMT_

----

Turns out mailboxer already supports email:
https://github.com/mailboxer/mailboxer#emails

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 22:28 GMT_

----

Out of scope for current mediated deposit sprints.

**Comment by no-reply** [comment]
Don't we already have email notifications?

cc: @samvera/hyrax-repo-managers

**Comment by mcdowney** [comment]
@no-reply, there is currently email notification, but this story seems to be asking about opting out of notifications? We'll try to get some better specification around the desired behavior around email notifications

**Comment by no-reply** [comment]
closing this pending better requirements.

please feel free to re-open or open a new ticket with needs for email notifications.
