### ISSUE TITLE
Editing a work removes the collection it was in previously

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#1748]
### Descriptive summary

When editing a work that is part of a collection, the collection gets removed after the updated work gets saved. (master)

### Expected behavior

The collection should not be affected when a work is updated.

### Actual behavior

The collection is being removed when a work gets updated.

### Steps to reproduce the behavior

1. Create a work in a collection.
2. Edit the work to add a new keyword, and save.
3. The collection is removed from the work.

### Related work

https://github.com/curationexperts/nurax/issues/94

**Comment by mjgiarlo** [comment]
The problem seems to be that loading the "Edit work" page does not successfully select the existing collections the work is a attached to. (So when the form is submitted, the controller interprets the form params to mean the user has deselected the collections.)

**Comment by mjgiarlo** [comment]
Duplicates #1748

**Comment by mjgiarlo** [comment]
Closing because dup.

**Comment by laritakr** [comment]
@mjgiarlo You just closed this because it duplicates itself?

**Comment by mjgiarlo** [comment]
@laritakr Wrong link! Will resolve in a sec.

**Comment by mjgiarlo** [comment]
Duplicates #1683, rather

**Comment by mjgiarlo** [comment]
@laritakr :laughing:
