### ISSUE TITLE
Copy visibility and permissions from work to member works (recursively)

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#175]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Sep 19, 2016 at 13:51 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2707_

----

Now that https://github.com/projecthydra/sufia/pull/2700 is merged, we have the ability to copy visibility and permissions from concerns down to member filesets. Now that concerns can be added to concerns, visibility and permissions should be copied down recursively. Related ticket in Plum: https://github.com/pulibrary/plum/issues/721

**Comment by no-reply** [comment]
This is implemented in `VisibilityCopyJob`, yes?

Closing this until we can document desired behavior that is missing.
