### ISSUE TITLE
Delete button doesn't work in collection show page

### ISSUE THREAD

**Issue by ojlyytinen** [samvera/hyrax#1750]
### Descriptive summary

If you click the red delete button on collection show page you'll get an error message and the collection is not deleted.

Selecting delete from the actions drop down menu in the dashboard collection list does work and delete the collection.

This happens on Hyrax v2.0.0.beta4.

### Rationale

The delete button should work the same as deleting from the dashoard list.

### Expected behavior

No error message, collection should be deleted.

### Actual behavior

Rails Routing error page and error message "No route matches [DELETE] "/collections/0z708w40c". The collection is not deleted.

### Steps to reproduce the behavior

1. Create a new collection
2. Go to dashboard, then select Collections on the menu and in the list click the collection you just created
3. On the page that opens (http://localhost:3000/dashboard/collections/0z708w40c?locale=en), click the red delete button and confirm deletion in the popup that opens

**Comment by mjgiarlo** [comment]
Thanks for writing this up, @ojlyytinen.

Ticketed too in Nurax: https://github.com/curationexperts/nurax/issues/70 (Adding this here to make the linkage over there.)

**Comment by mjgiarlo** [comment]
Traceback includes e.g. `F, [2017-09-29T15:45:46.030227 #3988] FATAL -- : [700a880a-fa30-4fe2-975c-169b75287fa2] ActionController::RoutingError (No route matches [DELETE] "/collections/6q182k13s"):
` Delete button references wrong path helper? Should route to /dashboard/collections/...?

**Comment by mjgiarlo** [comment]
Do you have cycles to whip up a PR, @ojlyytinen?

**Comment by ojlyytinen** [comment]
I believe this will be a one line fix. I think I can do that sometime this week.

**Comment by mjgiarlo** [comment]
Thanks, @ojlyytinen!

**Comment by mjgiarlo** [comment]
@ojlyytinen I've assigned you to this issue for now so other interested folks can focus on other issues.

**Comment by julesies** [comment]
@mjgiarlo  I can't reproduce this on nurax now.

**Comment by mjgiarlo** [comment]
@julesies shall we close both issues?

**Comment by julesies** [comment]
@mjgiarlo can you try it first? Chris still gets the error.

**Comment by mjgiarlo** [comment]
I'm still seeing it, @julesies. And @ojlyytinen already has a fix in mind, so we'll leave this issue here.
