### ISSUE TITLE
Adding a private work to a collection throws error

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1751]
### Descriptive summary
I tried to add a bunch of works to a collection I created.  As far as I can tell, it works for any combo of works that are public, embargoed, institution only. But if you try to include a private work either in batch or single, you get "We're sorry, something went wrong"

### Expected behavior
You should either get a warning "Can't add private works" or it should allow you to add private works. 

### Actual behavior
You are permitted to select any work, but including a private work throws error. 

### Steps to reproduce the behavior

1. Dashboard: Collections
2. Add new collection
3. Add private work to collection

![screen shot 2017-09-28 at 9 24 14 am](https://user-images.githubusercontent.com/4356335/30970361-f683e152-a432-11e7-9478-23a684e0b4df.png)

### Related work

https://github.com/curationexperts/nurax/issues/69

**Comment by mjgiarlo** [comment]
I cannot reproduce this issue.

**Comment by mjgiarlo** [comment]
@julesies Tagging you here so you can confirm.

**Comment by julesies** [comment]
@mjgiarlo i don't get an error now, but the private work was not added to the collection. @cpd3149 or @mjgiarlo can you try to confirm the work gets added?

**Comment by mjgiarlo** [comment]
@julesies https://demo.curationexperts.com/concern/generic_works/6969z078d?locale=en

**Comment by julesies** [comment]
Okay, ignore that previous comment - I hit "add to new collection" button instead. But @mjgiarlo i changed your collection to private and can now get the red rails error again. "we're sorry something went wrong".

**Comment by julesies** [comment]
https://www.screencast.com/t/SGq1NFbFU

**Comment by mjgiarlo** [comment]
@julesies Yeah, I don't know. Could be? Not seeing anything specific in the logs, either.

**Comment by julesies** [comment]
@mjgiarlo close then?

**Comment by mjgiarlo** [comment]
@julesies I suppose!
