### ISSUE TITLE
New works added as child works are pending approval and cannot be viewed

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1755]
### Descriptive summary
Works added using "Attach New Work" to create a child work indicate they are pending approval, and cannot be viewed or approved. 

### Expected behavior
New work is added and listed as a child

### Actual behavior
New work is added as "pending approval" and cannot be approved by the depositor, and does not appear as a child of work as intended. The new work also cannot be searched for to add as a child.

### Steps to reproduce the behavior
1 Go to a Work
2 Click on the Edit button
3 Click on the Relations Tab
4 Other Works in the Work heading appears 
5 Click on the Attach New Work Button
6 Create a new Work (add Descriptions, Files)
7 Save the new Work
8 Go back to the first Work
9 Click on Edit
10 The new Work does not appear as a child
11 Click on the notification bell
12 The new work shows as pending approval, click on the new work name
13 The new work does not allow for approval

**Comment by mjgiarlo** [comment]
Refs https://github.com/curationexperts/nurax/issues/82

**Comment by jonathandixon** [comment]
Unable to reproduce this on master.

1. The child work only requires approval if added to an admin set with a mediated deposit workflow.
2. When the child work is pending approval, it still appears in the edit relationship tab for the parent work.
3. Child works that are pending approval may be approved by a user with approval permissions on the workflow.

**Comment by mjgiarlo** [comment]
@heathergreerklein @julesies :point_up:

**Comment by shlake** [comment]
I reproduced the "pending" behaviour:

Created two “base” works:

With Admin Set: Admin Set Test 1 - Default Workflow, Unchanged Release and Visibility
1st Work https://nurax.curationexperts.com/concern/generic_works/cz30ps70h?locale=en
Attached work: https://nurax.curationexperts.com/concern/generic_works/v979v3061

With Admin Set: Default Admin Set
1st Work: https://nurax.curationexperts.com/concern/generic_works/fb4948403?locale=en
Attached: https://nurax.curationexperts.com/concern/generic_works/02870v86p

And these 2nd "attached" works do not show up in the dashboard. I would have expected them to be on the dashboard, even if “pending” review.

**Comment by mjgiarlo** [comment]
@shlake I don't recall if this was the intended behavior or not. Do other `pending` works appear in your dashboard? Or is it just child `pending` works that do not appear?

**Comment by shlake** [comment]
@mjgiarlo No `pending` works show on my dashboard, which I think is a problem. I created a work using an Admin set with "one step" workflow and then it disappeared. I assume it was created successfully, but there is nothing in my Notifications that the work is waiting for approval. I have no idea where it went. So some notice on the dashboard would be good, as a more "permanent" place, since notifications can be deleted Oh, and because this activity is not reflected in my "User Activity". Should I create a separate issue?

**Comment by mjgiarlo** [comment]
@hannahfrost @vantuyls @ggeisler @jcoyne How do we feel about this issue? Should suppressed works appear on the dashboard, or are they missing by design? (I can't recall.)

@shlake There are no notifications in Nurax because of this: #1465 #1455 So I think we're good on issues around that. @vantuyls @julesies do you think this is a 2.0.0 blocker, or can we address in 2.0.1?

**Comment by mjgiarlo** [comment]
@vantuyls @julesies For the moment, I am removing this as a blocker and moving it to the 2.x series. Let me know if y'all think this is a bad call!

**Comment by vantuyls** [comment]
IMO if you are the depositor of the work, you should be able to see the work in your dashboard even if they are suppressed, pending approval, or otherwise 'inactive' in a workflow. 

pushing this off to 2.0.1 is fine with me but i'm going to stick priority label on this for the 2.x series.

**Comment by mjgiarlo** [comment]
@vantuyls OK!

**Comment by chrisdaaz** [comment]
i couldn't reproduce this depositing into the default admin set. the new child work appears in my works dashboard and in the work it was attached to.
