### ISSUE TITLE
As a Manager, I can edit a work pending review, but it doesn't save

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#1757]
### Descriptive summary
When logged in as a manager, I go to edit the title of a "Private Work" that is "pending review" and I'm able to edit metadata, but then upon hitting save the edit I made, disappears. 

### Expected behavior
Either I should be able to edit and save, OR I should not be able to edit if that operation is prohibited. 

### Actual behavior
I can edit works in workflow, but changes do not save. 

### Steps to reproduce the behavior

1. Create admin set with one step workflow, add a manager (IMPORTANT TO DO THIS BEFORE WORKS ARE CREATED)
2. As regular user, add a work to that admin set
3. As manager, try to edit metadata for that work just created
4. Hit save

**Comment by mjgiarlo** [comment]
Refs https://github.com/curationexperts/nurax/issues/87

**Comment by jonathandixon** [comment]
Unable to reproduce this on master.

**Comment by mjgiarlo** [comment]
@cpd3149 @juliesies :point_up:

**Comment by julesies** [comment]
We can't reproduce this one with a "clean" test. okay to close
