### ISSUE TITLE
Rights in catalog_controller template - intentional or oversight?

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#1765]
Hello. I notice that in `rights` appears several times in the `catalog_controller.rb` template at `lib/generators/hyrax/templates/`.

Should that be changed to `license` and `rights_statement` in line with changes to `BasicMetadata` and `WorkShowPresenter`?

I'm happy to pick this up, but wanted to check first that there isn't a reason for it being this way.

**Comment by mjgiarlo** [comment]
I suspect you're right. Go for it. Thanks!
