### ISSUE TITLE
As a manager, I can't see, but can edit works in admin set with review process

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#1768]
Moved from Nurax https://github.com/curationexperts/nurax/issues/101

**Descriptive summary**

As a manager of an admin set, I can can't see works in review, but I can edit them.
Using Admin Set: Test one-step work flow with faculty manager - I had a regular user submit works. As the manager, I can't see them via Work View or if I click on work title via the Admin Set dashboard but you can edit them. Similar to the behavior seen in https://github.com/curationexperts/nurax/issues/72

So far as I can tell, I can see/view objects in admin sets that do not have workflows.

@cpd3149 confirmed this.

**Expected behavior**

I can see what I can edit.

Actual behavior

Can't view, but can edit

**Steps to reproduce the behavior**

Create admin set with 1 step
Add manager, allow users to deposit
As non-manager, add work (keep the URL)
As manager visit URL
As manager go to admin set in dashboard, click title, try to edit via drop-down

**Comment by mjgiarlo** [comment]
@julesies @vantuyls We need to assign a milestone and labels to this. (Blocker-worthy for 2.0.0?)

**Comment by julesies** [comment]
sorry, I assumed blocker. @vantuyls

**Comment by vantuyls** [comment]
blocker.

**Comment by julesies** [comment]
FYI this is weird with: https://github.com/samvera/hyrax/issues/1769 but I believe #1769 is only a problem for managers with who have permissions on admin sets with 1-step workflow.

**Comment by julesies** [comment]
let's close this one,  @cpd3149 and I tested with a clean-er scenario.
