### ISSUE TITLE
Works "disappear" with deposit to Admin sets with combo: Release Embargo and Visibility Everyone

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#1772]
Descriptive summary

When submitting to admin sets 2 and 11, it defaults to "private setting" - so if the depositor doesn't actively click another setting, but hits save, the work disappears. As far as I can tell, the combo has to be embargo allowed and public visibility.

Here is the admin set setting.
screen shot 2017-10-05 at 11 58 38 am

Here is the work view, where the setting does not move from private, like the others do.
screen shot 2017-10-05 at 11 47 19 am

Steps to reproduce the behavior

Create admin set with Embargo allowed, public visibility only
deposit work to admin set - do not change access control.
Click save, work disappears.
Related work

I believe this is like curationexperts/nurax#43 Sorry I didn't catch it before.

**Comment by vantuyls** [comment]
related to: https://github.com/curationexperts/nurax/issues/102

**Comment by julesies** [comment]
@tdonohue I was wondering if you might be able to look at this one because it's another scenario like: https://github.com/samvera/hyrax/issues/1701

**Comment by julesies** [comment]
@vantuyls when copying over issues from nurax to hyrax - the links to tickets that don't have the full url seem to get confused. See ticket is ref'ing the hyrax 43 instead of the nurax 43. I can't edit in this repo so I can't change it.

**Comment by mjgiarlo** [comment]
@julesies tweaked the link in the description. Also, I'll give you access so you can do this sort of thing henceforth.

**Comment by jonathandixon** [comment]
I've confirmed this, but I'm unsure of the best approach to take to fix the issue.

What happens is the actor stack fails to create the new work, which causes the new work form to rerender with a 422 Unprocessable Entity response. The resulting page has no indication that an error occurred and the form is empty. I'm pretty sure the `Hyrax::Actors::InterpretVisibilityActor` is where the work validation failure occurs.

**Comment by jonathandixon** [comment]
Nevermind, I think I see how to pass errors back to the controller and view.
