### ISSUE TITLE
Feature request: Always make default admin set the first item in the select menu of the relationships tab

### ISSUE THREAD

**Issue by bess** [samvera/hyrax#1773]
### Descriptive summary

Currently, when a new AdminSets is created, it becomes the first (and thus, the auto-selected) option on the "Add as member of administrative set" select menu. This results in unexpected behavior for users. 

### Rationale

An institution using Hyrax starts by only using the default admin set. Staff members are depositing items, and they get used to not having to select anything in the "Relationships" tab because it has automatically selected the default admin set for them. Then, someone adds a second admin set. Now that new admin set is the one being automatically selected, and to many users it appears that their deposited items are disappearing.

### Expected behavior

I would expect that the behavior of the deposit would not change just because a new AdminSet had been created.

### Related work

This has come up at more than one institution. In slack, @bmquinn says he fixed it like this:

Brendan Quinn [1:41 PM] 
We added `selected: AdminSet::DEFAULT_ID` after https://github.com/samvera/hyrax/blob/master/app/views/hyrax/base/_form_relationships.html.erb#L6 in an override of `_form_relationships.html.erb`

**Comment by VivianChu** [comment]
@bess - Do you know if anyone working on this issue?  Thanks

**Comment by julesies** [comment]
i tested this on nurax and it works! Thank you!
