### ISSUE TITLE
Collections factory does not behave as expected without a permission template

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#1775]
### Descriptive summary

The Collections factory allows you to create a collection without a permission template. Adding nested indexing identified a bug in the permissions given to a collection via this method. 

Without a permission template, at some point during creating the collection, edit permissions are assigned to the creator. But during the reindexing, ActiveFedora::Base.find(id).to_solr does not return permissions related fields, so the edit permissions are removed during nested indexing. 

### Rationale

To ensure that tests are valid, we need to ensure that the factory is producing an object in the same way that the UI does.

### Expected behavior

A collection created via the factory will behave in the same manner as a collection created through the UI.

### Actual behavior

When a collection is created without a permission template, while using nested indexing, the creator loses access to the collection. 

### Steps to reproduce the behavior

1. Create a spec to test a collection through the factory: 
`      let(:user) { create(:user) }
      let(:collection) { create(:named_collection, user: user) }`
2.  Test without nested indexing passes 
      `expect(user.can?(:edit, collection)).to be true`
3. Add `with_nested_reindexing: true`
4. Test with nested indexing fails

Breakpoints in the nesting_index_adapter method `self.write_document_attributes_to_index_layer` show that edit_access_person_ssim is present prior to re-saving the solr document, and absent after. 

### Related work

Nesting indexing PRs: 
- Nested indexing fix: https://github.com/samvera/hyrax/pull/1736
- Add indexing for nested collections: https://github.com/samvera/hyrax/pull/1668

**Comment by elrayle** [comment]
Fixed by PR #1781
