### ISSUE TITLE
BUG Collections: use of updated_index causes participants not to save on Add

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1785]
### Descriptive summary

`updated_index` causes participants not to save in several scenarios.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

#### Scenario - new collection

When a collection is created, the `:manage` participants for the collection type should be given `:manage` access to the collection.
- [x] immediately after create, the `:manage` participants should be saved in the permission_template_accesses table for the new collection
- [x] immediately after create, the `:manage` participants should be added to `edit_access_person/group_ssim` in the solr_doc for the new collection

NOTE: User Collection type defaults to `:manage` for `admin` group.

#### Scenario - edit collection + add participant

When Add is clicked with `user: a_user@example.org` and `acess: :manage`, 
- [x] the user is immediately saved in the permission_template_accesses table  
- [x] the user is immediately added to `edit_access_person_ssim` in the solr_doc

See related work below which provides a way to eliminate this bug.

#### Scenario - new collection

When a collection is created, the `:manage` participants for the collection type should be given `:manage` access to the collection.
- immediately after create, the `:manage` participants **IS** saved in the permission_template_accesses table for the new collection
- immediately after create, the `:manage` participants **ARE NOT** added to `edit_access_person/group_ssim` in the solr_doc for the new collection

If you click 'Save changes' button in the collection edit form, the solr doc is updated as correctly to include the `:manage` participants in the `edit_access_person/group_ssim` field(s).

#### Scenario - edit collection + add participant

When Add is clicked with `user: a_user@example.org` and `acess: :manage`, 
- the user **IS** immediately saved in the permission_template_accesses table  (as expected)
- the user **IS NOT** immediately added to `edit_access_person_ssim` in the solr_doc (unexpected)

If you click 'Save changes' button in the collection edit form, the solr doc is updated as correctly to include the `:manage` participants in the `edit_access_person/group_ssim` field(s).

### Steps to reproduce the behavior

1. create a collection

verify `edit_access_person_ssim:[current_user.user_key]`
 
1. edit the same collection
1. on Sharing tab, set a user with Manage access and click Add

verify `edit_access_person_ssim:[current_user.user_key, user.user_key]`

### Related work

This bug can be eliminated by reversing the changes to file `app/models/concerns/hyrax/collection_nesting.rb` in [Fix nesting indexing commit](https://github.com/samvera/hyrax/pull/1736/commits/7877a06cc38b9943b24e5b5a51d3c3643c003d68) that is part of PR #1736.

![image](https://user-images.githubusercontent.com/6855473/31308356-a8c5cf62-ab43-11e7-963d-f63460ef940d.png)

NOTE: This may not be the solution, but does help to highlight what changes introduced the bug.

**Comment by laritakr** [comment]
@elrayle We definitely can't reverse the indexing changes as you commented above, as that breaks a lot of other indexing cases. Have you tried to repeat this after merging in the PR that I submitted yesterday? I don't want to make any additional indexing changes until the changes are included to remove caching in the nesting indexer. I'd be very surprised if the changes to fix the caching didn't fix this as well.

**Comment by elrayle** [comment]
I tested with the latest PR #1781 and see no change in this behavior.

**Comment by laritakr** [comment]
[This is the result of 
 my testing.](https://docs.google.com/document/d/1vG844HDV9ne25BYNp537C5ZxBCMe8ELsw6Tb2unY4gU/edit?usp=sharing)

In short, the index is getting updated BEFORE the Fedora save, which should not be the case. The Fedora update should happen before we build the solr index.

**Comment by elrayle** [comment]
@laritakr Good analysis.  Any thoughts on how to adjust the indexing so the save to Fedora and Solr happen in the correct order (i.e. Fedora first, and then Solr)?

**Comment by laritakr** [comment]
I don't know ActiveFedora that well so I really can't offer much of a suggestion. It seems like the ideal would be to queue all of the objects to reindex, and do the indexing after the full transaction is completed, but I'm not sure how feasible that is. Any change seems like potentially a major refactor. 

I created an issue to document the problem and open discussion on it.
https://github.com/samvera/hyrax/issues/1826

**Comment by elrayle** [comment]
Fixed by PR #1781
