### ISSUE TITLE
Collection Types: exception when failing to add a participant is ignored and logged only

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1797]
### Descriptive summary

The create service for participants for collection types rescues any errors when creating participants.  It does log the error, but provides no feedback to end users.  The errors should be gathered and returned to the end user so they can act as needed to rectify the situation.

### Rationale

Users should always receive feedback when things fail.

### Implementation

In [services/hyrax/collection_types/create_service.rb](https://github.com/samvera/hyrax/blob/collections-sprint/app/services/hyrax/collection_types/create_service.rb) `#add_participants` method rescues exceptions which hides errors from the end user.

I tried making the following change...
```
      # @api public
      #
      # Add a participants to a collection_type.
      #
      # @param collection_type_id [Integer] the id of the collection type
      # @param participants [Array<Hash>] each element holds agent_type, agent_id, and access for a participant to be added
      def self.add_participants(collection_type_id, participants)
        return unless collection_type_id && participants.count > 0
        errs = []
        participants.each do |p|
          begin
            agent_type = p.fetch(:agent_type)
            agent_id = p.fetch(:agent_id)
            access = p.fetch(:access)
            Hyrax::CollectionTypeParticipant.create!(hyrax_collection_type_id: collection_type_id, agent_type: agent_type, agent_id: agent_id, access: access)
          rescue
            msg = "Participant not created for collection type #{collection_type_id}: #{agent_type}, #{agent_id}, #{access}"
            errs << msg
            Rails.logger.error "#{msg}\n"
          end
          return true unless errs.present?
          errs
        end
      end
```

And adding the following passing and failing tests in [services/hyrax/collection_types/create_service_spec.rb](https://github.com/samvera/hyrax/blob/collections-sprint/spec/services/hyrax/collection_types/create_service_spec.rb)...
```
  describe '.add_participants' do
    let(:participants) { [{ agent_type: Hyrax::CollectionTypeParticipant::GROUP_TYPE, agent_id: 'test_group', access: Hyrax::CollectionTypeParticipant::MANAGE_ACCESS }] }
    let(:coltype) { create(:collection_type) }

    it 'adds the participants to a collection type and returns true' do
      expect(Hyrax::CollectionTypeParticipant).to receive(:create!)
      expect(described_class.add_participants(coltype.id, participants)).to be true
    end

    context 'when invalid participant' do
      let(:participants) do
        [
          { agent_type: Hyrax::CollectionTypeParticipant::GROUP_TYPE, agent_id: 'test_group', access: 'BAD_ACCESS' }
        ]
      end

      it 'returns fails to add the participants to a collection type' do
        expect(Hyrax::CollectionTypeParticipant).to receive(:create!)
        expect(described_class.add_participants(coltype.id, participants)).to eq ["Participant not created for collection type #{coltype.id}: group, test_group, BAD_ACCESS"]
      end
    end

    context 'when mix of valid and invalid participants' do
      let(:participants) do
        [
          { agent_type: Hyrax::CollectionTypeParticipant::GROUP_TYPE, agent_id: 'test_group1', access: 'BAD_ACCESS' },
          { agent_type: Hyrax::CollectionTypeParticipant::GROUP_TYPE, agent_id: 'test_group2', access: Hyrax::CollectionTypeParticipant::MANAGE_ACCESS },
          { agent_type: Hyrax::CollectionTypeParticipant::GROUP_TYPE, agent_id: 'test_group3', access: 'BAD_ACCESS' }
        ]
      end

      it 'returns fails to add the participants to a collection type' do
        expect(Hyrax::CollectionTypeParticipant).to receive(:create!)
        expect(described_class.add_participants(coltype.id, participants)).to eq ["Participant not created for collection type #{coltype.id}: group, test_group1, BAD_ACCESS",
                                                                                  "Participant not created for collection type #{coltype.id}: group, test_group3, BAD_ACCESS"]
      end
    end
  end
```

I was not able to get `#add_participants` to fail.  The reason is that the validations don't run for `create!`, which is what `add_participants` uses.  The validations will fail upon `save`.

At initial look, I am not sure why `create!` was used instead of `save!`.  I was not able to find where the save is actually happening, but I did confirm that the table is updated in the database.

Following the path of `add_participants`...
* called by `create_collection_type` and `add_default_participants`, both methods in the same class

Following the path of `add_default_participants`...
* called from `CollectionTypesController` in `create` method - used to add default participants to new collection types

Following the path of `create_collection_type`...
* called from `CollectionType` (model) in `find_or_create_default_collection_type` method to create the default User Collection collection type
  * called from `default_collection_type.rake`
  * called from `Dashboard::CollectionsController` in `default_collection_type_gid` method
    * called from `Dashboard::CollectionsController` in `create` method to use the default collection's gid if one isn't provided
  * called from `CollectionBehavior` (model) in `ensure_collection_type_gid` which is an after_initialize callback
* called from `CollectionType` (model) in `find_or_create_admin_set_type` method to create the default Admin Set collection type
  * called from `default_collection_type.rake`
  * called from `AdminSetPresenter` in `collection_type` method

Additional exploration is needed to determine...
* How are the participants actually saved?
* Where are the places that need to give feedback to the user?
* What is the best way to pass the errors back to the controller that will cause the errors to flash to the user?

NOTE: Participants added through the UI via Dashboard -> Settings -> Collection Types -> edit type -> Participants tab, do not go through the code described above.  The participants form uses Hyrax::Forms::Admin::CollectionTypeParticipants which delegates to Hyrax::CollectionTypeParticipants model ultimately calling `@collection_type_participant = Hyrax::CollectionTypeParticipant.new(collection_type_participant_params)` in Hyrax::Admin::CollectionTypeParticipantsController.

### Steps to reproduce the behavior

Not able to find how to reproduce in UI.

Can at least use the tests created for the initial exploration to test that errors are generated.

More exploration is needed to determine how this surfaces through the UI.

### Related work

#1546 Adds Collection Type Participants functionality
#1589 Store manage and create in collection_type_participant table
#1603 adds CollectionTypes service
#1634 User and group edit access for collection type permissions service
#1663 CollectionTypeParticipant model validations
#1709 Add default participants when new collection type created
#1774 Solidify abilities using permission services -- This moved `add_participants` from PermissionsService to CreateService.

**Comment by no-reply** [comment]
closed by #2840
