### ISSUE TITLE
Support Custom indexing

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#1800]
Human readable type for example

List those to be refactored here:

- [ ] app/models/concerns/hyrax/human_readable_type.rb
- [ ] app/indexers/concerns/hyrax/indexes_basic_metadata.rb
- [ ] app/indexers/concerns/hyrax/indexes_linked_metadata.rb

**Comment by geekscruff** [comment]
I've done some work on 'based_near'.

Adding customer indexers is documented in https://github.com/samvera-labs/valkyrie/wiki/Custom-Indexing

**Comment by jeremyf** [comment]
We are pursuing the [Wings strategy](https://github.com/samvera/hyrax/blob/master/lib/wings.rb), and we're closing this issue to re-assess our approach.
