### ISSUE TITLE
Can't add a work to an admin set with an Admin set fixed release date setting that has passed

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#1801]
**Descriptive summary**

When trying to add a work to an Admin set with a fixed release date setting that has passed, the work "disappears".

**Expected behavior:**
When date of embargo setting passes on the Admin set, one can still submit a work.

**Steps to reproduce the behavior**

1. Submit a work to an Admin set with an expired release date. Can use Nurax Admin Sets 16, 17, 18
2. Work disappears, page reloads to blank and work is not deposited. Similar in behavior to https://github.com/samvera/hyrax/issues/1772

moved from https://github.com/curationexperts/nurax/issues/108

**Comment by mjgiarlo** [comment]
Thank you, @jonathandixon!
