### ISSUE TITLE
Need a Workflow Builder UI

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#181]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Thursday Oct 20, 2016 at 16:22 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2808_

----

We need UI and functionality to build workflows through the Admin Sidebar. 
- [ ] Submenu in the Workflow menu
- [ ] The ability to generate a new workflow and define the steps and roles

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 20:58 GMT_

----

This issue is out of scope for the Autumn/Winter 2016 mediated deposit sprints.

**Comment by no-reply** [comment]
@samvera/hyrax-repo-managers Should this epic be under consideration on the roadmap?

My experience building workflows is that we don't have the process ironed out enough to even consider a UI. I think it might be a better use of time to design various out-of-the-box supported workflows, and leave custom workflow as a development project right now.

Thoughts?

cc: @vantuyls

**Comment by vantuyls** [comment]
i think a modification (different issue) of this would be to build a workflow visualization and/or a workflow validator to help users building workflows. That said, neither of those would be in scope for current considerations, unless someone is really eager to champion the work.

**Comment by julesies** [comment]
agree with @no-reply and @vantuyls
