### ISSUE TITLE
Collections: edit form Discovery tab needs wording updated

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1813]
### Descriptive summary

Wording on the Discovery tab of the edit form is inconsistent with the wording used for works.  The wording should be the same.

### Rationale

Providing a consistent UI reduces confusion in users.

### Expected behavior

Based on work new/edit form, the text of each visibility setting should read...
* Public - Make available to all.
* Institution - Restrict access to Institution.
* Private - Keep to myself with option to share.

### Actual behavior

* Open Access - Visible to all.
* Institution - Restricted to institution.
* Private - Restricted to institution.  (This currently doesn't match the mockup or works implementation.)

### Steps to reproduce the behavior

1. Create a new collection, set title, and Save
1. Click Discovery tab

Verify the test of the 3 options matches that described under Expected Behavior.

### Related work

#1379 - PR #1448 Create discovery partial of the new/edit form (includes mockup)

**Comment by elrayle** [comment]
@ggeisler Can you verify the preferred text...

OPTION 1: That seen in the original mockup...

![image](https://user-images.githubusercontent.com/6855473/31363044-db61d3f2-ad29-11e7-989a-7eaae51ef2dc.png)

OPTION 2: That seen on the works new/edit form...

*    Public - Make available to all
*    Institution - Restrict access to Institution
*    Private - Keep to myself with option to share

**Comment by ggeisler** [comment]
@elrayle I think at some point after I created the mockup it was decided to change the wording to that in Option 2, so it makes sense to go with that version.

**Comment by elrayle** [comment]
All requirements met by PR #1881.  Closing.
