### ISSUE TITLE
Can't ingest local file system files using Browse Everything and the local files are deleted

### ISSUE THREAD

**Issue by ojlyytinen** [samvera/hyrax#1814]
### Descriptive summary

It's impossible to add files from a local file system using Browse Everything unless you're using :inline ActiveJob queue_adapter.

[IngestLocalFileJob calls FileSetActor.create_content and then immediately removes the file](https://github.com/samvera/hyrax/blob/master/app/jobs/ingest_local_file_job.rb#L13). However, [FileSetActor relies on IngestJob.perform_later doing the job](https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/file_set_actor.rb#L36). Thus the file will have been removed by the time IngestJob is actually performed and so it will fail.

If you use :inline queue_adapter then this will work, but production systems are unlikely to use that.

Furthermore it seems strange that IngestLocalFileJob would remove the file at all. I would think that since this isn't a file that was put there by Hyrax, it shouldn't be removed by Hyrax.

I've tested this in v2.0.0.beta4

### Expected behavior

File should be ingested into Fedora and arguably the original file should remain on the file system.

### Actual behavior

Original file is removed and it is not ingested to Fedora

### Steps to reproduce the behavior

Make sure you're **not** using :inline queue_adapter and that Browse Everything is configured with a file_system provider.

1. Go to create a new work form
2. Fill in required metadata
3. Add a file using Browse Everything (be aware that this file is going to be deleted)
4. Click save
5. Try to download the file that was supposed to have been added, you will get ActiveFedora::ObjectNotFoundError page

Furthermore the file you selected will have been removed from the file system.

### Possible solution

I would just remove the one line from IngestLocalFileJob that removes the file from the local file system. But if it is indeed intended behaviour that the file be removed, then this needs to be done elsewhere after it really has been successfully added to Fedora. And I think it should somehow be made obvious to the user that the file will be deleted.

I'm happy to make a PR for this issue but I'd like some feedback on whether it's ok to just not remove the file at all.

**Comment by mjgiarlo** [comment]
@ojlyytinen Yes, please do make a PR. I don't think we want Hyrax to delete these files -- folks can and should deal with this elsewhere. Thanks!
