### ISSUE TITLE
Need UI to see what workflows exist and to investigate them

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#182]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Thursday Oct 20, 2016 at 16:24 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2809_

----

As a repository administrator, I need to be able to get an overview of what workflows currently exist for my repository. 

information that would be useful includes: a workflow name, a brief description of the workflow, the steps in the workflow, and maybe what admin sets the workflow is currently assigned to

_edited description to reflect the below conversation and clarification_

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 28, 2016 at 20:57 GMT_

----

This is already happening to some extent in CC, right, @jcoyne?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Saturday Oct 29, 2016 at 00:34 GMT_

----

I'd say this is partially exposed by the workflow roles screen. I'd certainly say this ticket is not actionable without more details.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Monday Oct 31, 2016 at 14:48 GMT_

----

i'll rework this asap to give more detail.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vantuyls](https://github.com/vantuyls)**
_Wednesday Nov 02, 2016 at 19:39 GMT_

----

The original intent here was to be able to see what workflows are available to a user with the ability to assign workflows to things. Information that would be useful includes: a workflow name, a brief description of the workflow, the steps in the workflow, and maybe what admin sets the workflow is currently assigned to. I think this can be pushed over to phase 2. 

Does that help clarify, @jcoyne @mjgiarlo ?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Nov 02, 2016 at 20:00 GMT_

----

@vantuyls works for me. thanks!

**Comment by mjgiarlo** [comment]
@vantuyls We already expose the names and descriptions of available workflows in the Admin Set "workflows" tab. Is that sufficient for this issue, or no? Keep in phase 2 or move to phase 3?

**Comment by vantuyls** [comment]
move to phase 3 and rely on the workflow creator to provide sufficient information in the description.

**Comment by mjgiarlo** [comment]
Since this issue lacks a UI design and you can already see a list of workflows when creating or editing an Admin Set, I'm inclined to close this. Pls submit a new UI design (or describe one in prose) for a new workflow viewing UI issue. Thanks!
