### ISSUE TITLE
Regression: representative not assigned automatically.

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#1827]
Introduced in https://github.com/samvera/hyrax/commit/747888b8e05b3ec91d7fb63d5635ffbef5facb4e

I'm pretty sure that this assignment in `AssignRepresentativeActor` was intended to be fixed before that commit was made:
`representative = nil`

https://github.com/samvera/hyrax/commit/747888b8e05b3ec91d7fb63d5635ffbef5facb4e#diff-99157061f8e5e4f6ace12696d7e95120R12

**Comment by no-reply** [comment]
This actor was removed entirely in https://github.com/samvera/hyrax/commit/ba9ed2f0ac2487cdd8a576007dce440b3549fc2b.

I think this ticket can be closed, as the `FileSetActor` sets the representative here: https://github.com/samvera/hyrax/blob/05a2a626ae5d90b12a4beb5b98a931ee0a4393a7/app/actors/hyrax/actors/file_set_actor.rb#L77
