### ISSUE TITLE
Collections: Show dialog if user clicks a button on admin show page they can't perform

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1841]
### Descriptive summary

Check abilities to determine whether an action button takes the action or shows a dialog explaining why the user can't take the action..

### Rationale

Educate the user when they can't perform an action.

### Expected behavior

**NOTE: Dialogs are the same here and on index page for Edit and Delete.  Create partials for the dialogs and share with #1508 and #1507.** 

`Edit` button
- [ ] `if can? :edit, collection`, forward to collection edit form
- [ ] else, show dialog "You do not have sufficient privileges to edit this collection"

`Delete` button
- [ ] `if can? :delete, collection`
  - [ ] if collection has member items, show confirmation dialog warning "Deleting this collection will permanently remove the collection from the repository. Items in the collection will remain in the repository. Are you sure you want to delete this collection?  This action cannot be undone." AND allow user to Delete or Cancel
  - [ ] if collection has 0 member items, show confirmation dialog "Are you sure you want to delete this collection? This action cannot be undone."  AND allow user to Delete or Cancel
- [ ] else when user cannot delete, show dialog "You do not have sufficient privileges to delete this collection"

`Add new work` and `Add existing works` buttons
- [ ] `if can? :deposit, collection`, perform the specified add action
- [ ] else, show dialog "You do not have sufficient privileges to add works to this collection"

### Steps to reproduce the behavior

Test via UI and write equivalent rspec tests for...

1. Create two users, user 1 and user 2.
1. Login as user 1
1. Create a collection with title 'Col - user 2 manage access without works' and grant user 2 Manage access
1. Create a collection with title 'Col - user 2 manage access with works' and grant user 2 Manage access
1. Create a work and put it in 'Col - user 2 manage access with works' collection
1. Create a collection with title 'Col - user 2 deposit access' and grant user 2 Deposit access
1. Create a collection with title 'Col - user 2 view access' and grant user 2 View access
1. Login as user 2
1. Dashboard -> Collections -> Managed Collections
1. click 'Col - user 2 manage access without works'

- [x] Verify user `Edit` and `Delete` buttons are **visible**
- [x] Verify user `Add new work` and `Add existing works` buttons are **visible**
- [x] click 'Edit' AND Verify forward to edit form
- [x] go back and click 'Delete' AND Verify confirmation dialog "Are you sure you want to delete this collection? This action cannot be undone." is displayed with options to Delete or Cancel
- [x] cancel and click 'Add new work' AND Verify forward to new work form
- [x] go back and click 'Add existing work' AND Verify forward to Dashboard -> Works

1. click 'Col - user 2 manage access with works'

- [ ] Verify user `Edit` and `Delete` buttons are **visible**
- [ ] Verify user `Add new work` and `Add existing works` buttons are **visible**
- [ ] click 'Edit' AND Verify forward to edit form
- [ ] go back and click 'Delete' AND Verify confirmation dialog "Deleting this collection will permanently remove the collection from the repository. Items in the collection will remain in the repository. Are you sure you want to delete this collection?  This action cannot be undone." is displayed with options to Delete or Cancel
- [ ] cancel and click 'Add new work' AND Verify forward to new work form
- [ ] go back and click 'Add existing work' AND Verify forward to Dashboard -> Works

1. click 'Col - user 2 deposit access'

- [ ] Verify user `Edit` and `Delete` buttons are **visible**
- [ ] Verify user `Add new work` and `Add existing works` buttons are **visible**
- [ ] click 'Edit' AND Verify shown dialog "You do not have sufficient privileges to edit this collection"
- [ ] go back and click 'Delete' AND Verify shown dialog "You do not have sufficient privileges to delete this collection"
- [ ] cancel and click 'Add new work' AND Verify forward to new work form
- [ ] go back and click 'Add existing work' AND Verify forward to Dashboard -> Works

1. click 'Col - user 2 view access'

- [ ] Verify user `Edit` and `Delete` buttons are **visible**
- [ ] Verify user `Add new work` and `Add existing works` buttons are **visible**
- [ ] click 'Edit' AND Verify shown dialog "You do not have sufficient privileges to edit this collection"
- [ ] go back and click 'Delete' AND Verify shown dialog "You do not have sufficient privileges to delete this collection"
- [ ] cancel and click 'Add new work' AND Verify shown dialog "You do not have sufficient privileges to add works to this collection"
- [ ] go back and click 'Add existing work' AND Verify shown dialog "You do not have sufficient privileges to add works to this collection"

### Related work

#1507 Update code to handle delete action in collection index page
#1508 Update code to handle edit action in collection index page
#1840 View and Deposit users should be able to see collection admin show page
#1843 Only show New Collection button if a user can create a collection
#1844 For major action buttons, should the UI hide, disable, or show dialog when user can't perform an action?

**Comment by blancoj** [comment]
@elrayle Isn't this taken care of by #1507 and #1508?

**Comment by elrayle** [comment]
The current UI does not show action buttons for actions a user cannot perform.  I believe we are going with this approach for the admin show page at this time.  The UI/UX group may want to revisit this in future releases.
