### ISSUE TITLE
For major action buttons, should the UI hide, disable, or show dialog when user can't perform an action?

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1844]
### Descriptive summary

For major actions on a page, should the UI hide, disable, or show a dialog when the user can't perform the action.  

### Rationale

Provide a consistent and intuitive UI/UX.

### Effected areas

Collection index
- New Collection button
  - [ ] hide
  - [ ] disable
  - [ ] dialog when clicked and the user can't create a collection

Considerations:
* For New collection, if a user cannot create a collection, this is unlikely to change.  They will not see New collection in some situations and not in others.  This leans me toward hide.

Collection admin show
- Edit button
  - [ ] hide
  - [ ] disable
  - [ ] dialog when clicked and the user can't edit the collection
- Delete button
  - [ ] hide
  - [ ] disable
  - [ ] dialog when clicked and the user can't delete the collection
- Add existing works button
  - [ ] hide
  - [ ] disable
  - [ ] dialog when clicked and the user can't deposit in the collection
- Add new work button
  - [ ] hide
  - [ ] disable
  - [ ] dialog when clicked and the user can't deposit in the collection

Considerations:
* For all buttons on the collection admin show page, depending on users access to other collections, they may sometimes have the ability to deposit and/or edit and sometimes not.  This leans me toward showing a dialog saying why they can't perform the action. 

There are other similar actions in Admin Sets and Works.  Collections are being used to establish the pattern.

### Effected Issues

#1841 Show/hide buttons on admin show page based on abilities
#1843 Only show New Collection button if a user can create a collection

**Comment by ggeisler** [comment]
@elrayle I agree with your leanings in each case. Generally, the dialog approach seems preferable because it's the only option of the three that helps the user understand why they cannot perform the action. However, as you suggest with the new collection button, if there is little chance of the user being confused by a missing action, then it makes more sense to simply not show it.

**Comment by elrayle** [comment]
Related issues were updated to reflect the answer to this question.  Closing.
