### ISSUE TITLE
Enabled Primary and Secondary Terms on change sets

### ISSUE THREAD

**Issue by carrickr** [samvera/hyrax#1851]
Current change_sets have no required terms, concepts of primary or secondary terms, etc.  They are valid by default.  This should be improved to offer better change_set support

Improve the spec for `GenericWorkChangeSet` as well since it should no longer be valid on instantiation  `GenericWork.new` without also being passed required fields.

**Comment by no-reply** [comment]
@carrickr It's not clear to me what the scope of this ticket is, or how to label/milestone it. Can you offer some guidance?
