### ISSUE TITLE
Thumbnails should be generated consistently based on your view

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#186]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cam156](https://github.com/cam156)**
_Wednesday Nov 09, 2016 at 17:37 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2867_

----

### Descriptive summary

In Sufia 7.0 master when you see an icon in the system it can be coming from many different places.
Some places use an image: https://github.com/projecthydra/sufia/blob/master/app/assets/images/work.png

Some places use an icon:
https://github.com/projecthydra/sufia/blob/5ae15949188bdcba9de98e756e6edc044d3df8cc/app/views/_toolbar.html.erb#L21

Some places use the blacklight helper: https://github.com/projectblacklight/blacklight/blob/acf1bcc0e779b4dc83110b007f49bea20759728b/app/helpers/blacklight/catalog_helper_behavior.rb#L212

You can see how many different places fa-cubes was hard coded into the system:
https://github.com/projecthydra/sufia/search?utf8=%E2%9C%93&q=fa-cubes

Can we come up with some guidelines for what way to do it?

When there are no consistent patterns you end up with no consistency on the screen... https://github.com/psu-stewardship/scholarsphere/issues/417

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Wednesday Nov 09, 2016 at 17:45 GMT_

----

I think we need to tease apart the icon from the thumbnail.  The icon is used for a generic type of thing "My Collections". The thumbnail is used for specific things "A few of my favorite things" (an instance of Collection).  The thumbnail reverts to the icon if no specific thumbnail can be found.

That said, we should do a better job of encapsulating the icon for a generic work type.  Perhaps a helper like `model_icon_class(Collection) => "fa fa-cubes"`?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Wednesday Nov 09, 2016 at 18:06 GMT_

----

@jcoyne I do not think that there is a clear pattern.  Take a look at the code there is an icon and an image of an icon being used in multiple places.  If the pattern was clear we would either be using the image or the icon, but not both...

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Wednesday Nov 09, 2016 at 18:09 GMT_

----

Here is the collection in the 4 Balcklight views:
![screen shot 2016-11-09 at 1 08 42 pm](https://cloud.githubusercontent.com/assets/1599081/20149084/b6255522-a67d-11e6-8b5e-6305051f9235.png)
![screen shot 2016-11-09 at 1 08 37 pm](https://cloud.githubusercontent.com/assets/1599081/20149087/b8d3459a-a67d-11e6-93f7-8e28634577e4.png)
![screen shot 2016-11-09 at 1 08 32 pm](https://cloud.githubusercontent.com/assets/1599081/20149091/bb55b62c-a67d-11e6-99ef-38bfe2a99d5e.png)
![screen shot 2016-11-09 at 1 08 23 pm](https://cloud.githubusercontent.com/assets/1599081/20149095/bee97a6c-a67d-11e6-944f-570ac0345f7a.png)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Wednesday Nov 09, 2016 at 18:13 GMT_

----

You can see the work is an image by default and the collection is an icon by default.

![screen shot 2016-11-09 at 1 13 00 pm](https://cloud.githubusercontent.com/assets/1599081/20149202/45418bc2-a67e-11e6-9a83-f04d898a2572.png)

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Wednesday Nov 09, 2016 at 18:15 GMT_

----

I would like to see the object in the system, collection or work, use a consistent mechanism for getting their image/icon.  The reason I mix them is becuase they seem very mixed up...

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Nov 10, 2016 at 03:16 GMT_

----

I'm thinking we should get rid of https://github.com/projecthydra/sufia/blob/master/app/assets/images/default.png and https://github.com/projecthydra/sufia/blob/master/app/assets/images/work.png and replace them with the icon configured for the specific work type.   What do you say?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Thursday Nov 10, 2016 at 14:29 GMT_

----

@jcoyne I think work.png was added when the thumbnails ended up in solr, so that there was a url to point to. https://github.com/projecthydra/sufia/blob/master/app/services/sufia/work_thumbnail_path_service.rb#L5 and the default image is used here: https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/thumbnail_path_service.rb#L17

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Nov 10, 2016 at 15:30 GMT_

----

@cam156 yes, that's right, but should we continue doing that?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/cam156"><img src="https://avatars.githubusercontent.com/u/1599081?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cam156](https://github.com/cam156)**
_Thursday Nov 10, 2016 at 15:54 GMT_

----

@jcoyne Not sure.  We now have default icons Icons, and we have default images, and we have helpers and services that should all work consistently.  To allow the thumbnail service to generate a thumbnail for every item the images are needed.  I do not think you can use an icon in an image tag.  Should we look at the Thumbnail services and have it not create a default image?  Then we could change the places that use the thumbnail url to display either an image or an icon.  The issue that we ran across is there is not an easy override spot in blacklight for the slideshow and masonry views like there was for gallery: https://github.com/projecthydra/sufia/blob/master/app/views/collections/_media_display.html.erb

We might be better suited only using images so the Thumbnail service can generate a link and then views in blacklight get the correct image without any overrides.  That means use images over icons though.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Dec 20, 2016 at 23:21 GMT_

----

I suggest we engage @projecthydra/sufia-ui-ux-advisors in this discussion and take it up in Hyrax in the new year.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mtribone"><img src="https://avatars.githubusercontent.com/u/4163828?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mtribone](https://github.com/mtribone)**
_Wednesday Dec 21, 2016 at 12:30 GMT_

----

I'm looking to ditch FontAwesome for the future of ScholarSphere, reduce the number of icons, and use SVG instead. Also per @cam156 conversation above we need to handle the thumbnails in a consistent manner. And the alt text for accessibility.

My reasons for wanting to ditch font icons:
https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/

And dropping 300k from the asset pipeline

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hackmastera](https://github.com/hackmastera)**
_Wednesday Dec 21, 2016 at 14:03 GMT_

----

@mtribone awesome plan. maybe a new issue for icons? I also think there are too many.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Dec 21, 2016 at 19:12 GMT_

----

Yes, new focused issues are preferable. I suggest we write up small, actionable issues in Hyrax since the only scheduled releases now for Sufia are 7.3.0 (feature-focused, hoping to get this out in Jan.), 7.2.1 (migration-focused), and 6.7.0 (migration-focused), and close this issue.

**Comment by vantuyls** [comment]
@mtribone @mjgiarlo @cam156 any chance one of  you could resurrect this issue into the proposed focused, actionable issues?

**Comment by mjgiarlo** [comment]
@vantuyls Honestly, I'd close this as `#wontfix`. Time to declare bankruptcy on these old issues.

If someone wants this done, they should either 1) do the work, or 2) commission a WG to take it up, rather than making the backlog even more unmanageable.

**Comment by vantuyls** [comment]
closing per suggestion.
