### ISSUE TITLE
Work type selection modal should gracefully handle up to 20 work types

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#190]
<a href="https://github.com/vantuyls"><img src="https://avatars.githubusercontent.com/u/9534576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vantuyls](https://github.com/vantuyls)**
_Tuesday Nov 22, 2016 at 17:25 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2933_

----

When the number of Work Types exceeds about 5, the work type selector interface starts to spill off the bottom of the page. I wonder if a matrix of work types, rather than a list, would help alleviate this problem. Or possibly, after 4 work types, new work types are listed in a second column?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Dec 20, 2016 at 21:43 GMT_

----

This needs design and I'm not sure folks are likely to create 5 types of work off the bat, so I'm not going to make this a blocker. I suggest we take this up in Hyrax.

**Comment by ggeisler** [comment]
I won't spend time doing any mockups unless we feel it's necessary, but if and when we want to deal with the potential of longer lists of work types, I suggest we 1) flow the work types choices into two columns of equal width, and 2) ensure the modal window has scrollbars.

**Comment by mjgiarlo** [comment]
Currently the design we're implementing for work type selection (both for single works and for batch works) in advance of creating new works is a modal with styled radio buttons. This works fine for a small number of work types. The design should accommodate up to 20 work types.

**Comment by mjgiarlo** [comment]
@ggeisler Thanks! I'll remove from design needed for now. This is on the backlog for later consideration.

**Comment by no-reply** [comment]
Is this an issue for current users?

@samvera/hyrax-repo-managers

**Comment by julesies** [comment]
No, we have 10 worktypes and it's fine. Closing.
