### ISSUE TITLE
Extract social features (TBD) into a new gem

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#2]
Work with the Hydra Plugins WG to solicit a recommendation for plugin patterns and pull out social features (TBD) as an optional Hyrax plugin.

**Comment by elrayle** [comment]
@mjgiarlo Is this a blocker for 2.1.0?

**Comment by mjgiarlo** [comment]
@elrayle Nope. AFAIK, this is no longer being asked for or worked on. Closing!
