### ISSUE TITLE
Can't Add Folder on Add or Edit Work on Safari (Mac)

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2006]
Descriptive summary

Using Safari on Mac, the "Add folder" button, does not allow me to "upload" a folder. Chrome & Firefox on Mac does show the "Upload" option when "add folder" is selected.

Rationale

Adding folder is expected to behave in all browsers. Plus there is a button to "Add folder..." and it doesn't allow uploading of folders (using Safari).

Expected behavior

In Chrome & Firefox, this screen pops up when "Add folder" is clicked (from Edit work -Files tab OR from Add New Generic Work - Files tab):
screen shot 2017-10-23 at 1 25 54 pm

Actual behavior

The file popup window has "choose" not upload:
screen shot 2017-10-23 at 1 26 34 pm

Steps to reproduce the behavior

From Works page, click "Add New Work"
Select Generic Work, click Create Work
Click "Files" tab
Click "Add Folder..."

**More comments at:**
https://github.com/curationexperts/nurax/issues/118

**Comment by jcoyne** [comment]
This it's likely something that hasn't been implemented (yet?) in Safari.

**Comment by jcoyne** [comment]
It looks like it's not a feature in Safari 11, but it is in the "Technology Preview" build: http://caniuse.com/#feat=input-file-directory

**Comment by jcoyne** [comment]
Broken by #1735 ?

**Comment by no-reply** [comment]
Is this still an issue on present versions of Safari?

**Comment by vantuyls** [comment]
just tested this on Safari v 12.0 and this is no longer an issue.
