### ISSUE TITLE
As a user I expect to be able to set the thumbnail for a work from the file manager

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2009]
Expected behavior

I would expect changing the representative media in the file manager to change the item's thumbnail or to give me the option to also change the thumbnail.

Actual behavior

I can select a representative file in the file manager but this does not change the thumbnail. The option to change the thumbnail is buried 'additional fields' on the metadata edit screen.

**more comments at:**
https://github.com/curationexperts/nurax/issues/112

**Comment by jcoyne** [comment]
I see a radio button for the thumbnail and the representative:

![Uploading Screen Shot 2017-10-30 at 8.33.04 AM.png…]()

These fields should be independent of one another.

**Comment by vantuyls** [comment]
closing as a duplicate of #2010 .
