### ISSUE TITLE
Based Near is missing its facet and field labels

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2011]
Descriptive summary

"Based Near" location facet is getting the default humanization for its label.

screen shot 2017-10-13 at 10 45 15 am 2

**more comments at:**
https://github.com/curationexperts/nurax/issues/111

**Comment by jcoyne** [comment]
@vantuyls I don't think the screenshot attached as you wanted.

**Comment by vantuyls** [comment]
@jcoyne thanks for grabbing that. 

see the additional information at the linked comment in the OP.
