### ISSUE TITLE
Conflicting information about presence of files when a work is created

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2012]
Descriptive summary

After creating a work, the top of the screen says files are being processed but the bottom of the screen says the work has no files. If you then edit the work to see what's happening, no files are listed on the files tab (because they are still being processed?)

Rationale

Things don't stay in this state for long but it is very jarring when it happens.

Expected behavior

Accurate reflection of the presence of files

Actual behavior

Conflicting information about presence of files

Steps to reproduce the behavior

Create a work
Add files
Save the work and scroll to the bottom of the work screen
Edit the work again.
screen shot 2017-10-13 at 9 43 17 am 2
Conflicting flash messages

screen shot 2017-10-13 at 9 43 49 am 2
Edit screen after saving the work with files.

Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**more comments at:**
https://github.com/curationexperts/nurax/issues/110

**Comment by vantuyls** [comment]
@awead is this something you'd be willing to look at?

**Comment by no-reply** [comment]
@vantuyls we do all `FileSet` creation and processing in the background. FileSet processing may fail during various stages of object creation, so creating empty an `FileSet` preemptively doesn't seem like a great option. At the moment, I think we need to consider this "working as designed".

If we want to address it, I think we need to be rethinking how we process Files/FileSets on ingest more comprehensively.
