### ISSUE TITLE
Field configuration in `BasicMetadataIndexer` cannot be extended in subclasses

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#2019]
### Descriptive summary

The [`BasicMetadataIndexer` defines several `class_attributes`](https://github.com/samvera/hyrax/blob/55ce354a372e97b3eb168927d1b84eddcaac3bff/app/indexers/hyrax/basic_metadata_indexer.rb#L4) which are inherited in subclasses, including `DeepIndexingService`. The values in these variables can't be extended in subclasses without overwriting the values in the base class and others in the tree.

We should refactor to allow these to be cleanly extended.

### Rationale

These services are shared between `Work` and `FileSet` objects. Extending indexing for works can cause problems for FileSets that don't have the same metadata as some custom work type.

### Expected behavior

Subclasses should be able to reuse the logic in the core indexing services without forcing configuration down to other work types.

```ruby
class MyIndexingService < Hyrax::DeepIndexingService
  stored_and_facetable_fields << :my_field
end

class EtdIndexer < Hyrax::WorkIndexer
  def rdf_service
    MyIndexingService
  end
end

Hyrax::DeepIndexingService.stored_and_facetable_fields.include?(:my_field) # => false

FileSet.create # runs without error
```
### Actual behavior

```ruby
class MyIndexingService < Hyrax::DeepIndexingService
  stored_and_facetable_fields << :my_field
end

Hyrax::DeepIndexingService.stored_and_facetable_fields.include?(:my_field) # => true

FileSet.create #  undefined method `my_field' for #<FileSet:0x0000556396ca7f70>
```

### Steps to reproduce the behavior

1. see "Actual behavior" above.

It's possible to work around by doing something like:

```ruby
class MyIndexingService < Hyrax::DeepIndexingService
  def self.stored_and_facetable_fields
    @stored_and_facetable_field ||=
       (Hyrax::DeepIndexingService.stored_and_facetable_fields.dup  << :my_field)
  end
end
```

**Comment by jcoyne** [comment]
Instead of using the shift operator try using `+=` Otherwise you're modifying the original.

**Comment by no-reply** [comment]
@jcoyne In the current implementation `#+=` is a no-op. `stored_and_facetable_fields` is a class attribute that must be altered to make any change.

**Comment by no-reply** [comment]
Sorry, I think this is just me working too late on a sunday.
