### ISSUE TITLE
Collections: Bread crumbs for admin set show page should use collections links

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2071]
### Descriptive summary

Change bread crumbs for admin set show page to match those for collection show page.

### Rationale

Admin sets are simulating being just another collection, so the bread crumbs should look like the admin set is just another collection.

### Expected behavior

`admin/admin_sets/:id` breadcrumbs should be...
* My Dashboard - forward to `dashboard`
* Your Collections - forward to `dashboard/my/collections`
* _admin set title_ (no link)

### Actual behavior

`admin/admin_sets/:id` breadcrumbs are...
* Home - forward to `/`
* Administration - forward to `dashboard`
* translation missing:... - forward to `admin/admin_sets`
* View Set (no link)

### Steps to reproduce the behavior

1. login as admin user
1. create an admin set with title `'Test Admin Set'`
1. Dashboard -> Collections -> click title of the new admin set

- [ ] Verify that the breadcrumbs are...
  * My Dashboard - forward to `dashboard`
  * Your Collections - forward to `dashboard/my/collections`
  * 'Test Admin Set'  (no link)

**Comment by gordonleacock** [comment]
Okay, will do.

On Tue, Jan 30, 2018 at 10:46 AM, E. Lynette Rayle <notifications@github.com

**Comment by elrayle** [comment]
These specific changed fixed by PR #2587.  Additional changes requested in Issue #2588.
