### ISSUE TITLE
Sipity Entity loads workflow objects from Fedora

### ISSUE THREAD

**Issue by carolyncole** [samvera/hyrax#214]
### Descriptive summary

Sipity::Entity proxy_for loads the object from Fedora instead of from Solr.  For cases where the workflow is changing the object this is good.  For cases where the workflow is displaying information about the object this is unnecessarily slow. 

We may want to include a secondary method and allow users of entity to chose a "read only" object (from solr) and or and "editable" object from fedora.

For Notifications (https://github.com/projecthydra-labs/hyrax/tree/master/app/services/hyrax/workflow) a read only copy would be sufficient.

**Comment by mjgiarlo** [comment]
@vantuyls Do you want to slot this into MD milestone 2 or 3, or leave in its current milestone?

**Comment by no-reply** [comment]
I'm closing this as wontfix. This will be largely moot after a `wings`.
