### ISSUE TITLE
Breadcrumbs on collections edit view is titled "Browse View"

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2164]
### Descriptive summary
On Collections sprint branch: Change breadcrumb text where highlighted below.

![screen shot 2017-11-13 at 11 02 15 am](https://user-images.githubusercontent.com/17851674/32735310-6011e95e-c862-11e7-8d84-978b1590e3e1.png)

**Comment by julesies** [comment]
There are a few breadcrumbs issues, not sure if we have the whole picture of what is going on, but this was punted till after 2.0 https://github.com/samvera/hyrax/issues/1712 

If it seems helpful for someone to look at the issue larger, LMK!

**Comment by elrayle** [comment]
I concur that there should be a review of all the breadcrumbs and an issue proposing a full app strategy.  We've fixed a few that are egregious, but not attempted to fix them all.  I'm putting this in the Backlog for Collection Sprints.

For reference, here is what Gary's mockups proposed for the breadcrumbs for the New form.  Presumably 'New' would switch to 'Edit' when editing.
![image](https://user-images.githubusercontent.com/6855473/32905959-8ad2738e-cac9-11e7-8681-853db1287f05.png)

**Comment by laritakr** [comment]
Actually, the breadcrumb that's there actually takes you to the public show page. So the label "Browse View" is somewhat accurate, though probably not what is desired there.

**Comment by gordonleacock** [comment]
I've been working on the breadcrumbs with Lynette. Slowly... :-)

**Comment by no-reply** [comment]
@laritakr @elrayle @gordonleacock What's the status of this ticket? Do we need to be tracking it for 2.1.0?

**Comment by no-reply** [comment]
This seems like a pretty quick fix. I'd propose renaming the key `.edit_view` witht a value of "Edit View".

See: https://github.com/samvera/hyrax/blob/8cd726b1d16fa1b85eec02d2fbdaa2f71c31178a/app/controllers/concerns/hyrax/breadcrumbs_for_collections.rb#L17
