### ISSUE TITLE
Upgrade to ActiveFedora 12.0

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#2203]

**Comment by jcoyne** [comment]
@no-reply did you encounter some difficulty when you tried this?  Do you know what the problem might be?

**Comment by CGillen** [comment]
@no-reply & @jcoyne Is it possible to pick this back up for 2.x? Recent security advisories for Rails are starting to require 5.2. It looks like the latest Hyrax 2.x release (2.7.1) is being held back by ActiveFedora 11 not supporting Rails 5.2.

The latest inciting advisory is https://github.com/advisories/GHSA-65cv-r6x7-79hv

**Comment by no-reply** [comment]
Hyrax 2.x supports up to AF 12.2. Hyrax 3 *only* supports 13+.
