### ISSUE TITLE
Style for workflow state

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#225]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Friday Sep 23, 2016 at 15:15 GMT_
_Originally opened as https://github.com/projecthydra/curation_concerns/issues/1029_

----

On the show page under the title. `.show`

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Friday Oct 14, 2016 at 21:03 GMT_

----

Item show page, @jcoyne?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Friday Oct 14, 2016 at 22:06 GMT_

----

Yep

**Comment by mjgiarlo** [comment]
@projecthydra-labs/hyrax-ui-ux-advisors Do you folks have suggestions for how we should display the current workflow state of items on their show pages?

**Comment by newmanld** [comment]
@mjgiarlo – can you add some examples of workflow states that might be displayed?  And would part of a given workflow configuration be whether or not a work, and thus a show page for the work,  is itself private, at any given workflow stage?

**Comment by mjgiarlo** [comment]
@newmanld You bet. I'll toss a screenshot here this afternoon. You'll just see the one state, but there are a handful of possible labels you could see in its place.

And, yes, workflow configuration includes which steps in the workflow "activate" or "deactivate" a work. When a work is activated, the usual Hydra access controls are used. When a work is deactivated, the code also factors in workflow roles of the requesting user.

**Comment by mjgiarlo** [comment]
See the "complete" label beneath the work title, @newmanld @projecthydra-labs/hyrax-ui-ux-advisors:

![workflow_label](https://cloud.githubusercontent.com/assets/131982/21829044/c910c864-d748-11e6-936f-af90dfe0c0ff.png)

**Comment by mjgiarlo** [comment]
@vantuyls Do you want to slot this into MD milestone 2 or 3, or leave in its current milestone?

**Comment by newmanld** [comment]
I think the placement beneath the title is ok, but a label may be needed to put the status in context.  So, expanding on the status of ‘complete’, perhaps “workflow state: complete”?  Or just “status: complete”?   Other ideas?

**Comment by ggeisler** [comment]
I agree with @newmanld that, depending on the potential values of the workflow state text, it might help to preface the state with "status". I definitely think that is necessary if one of the values is really going to be "complete." 

On the other hand, if the text of potential states can be terms that are more meaningful on their own, we might be able to get away with not prefacing them. See a few examples below, where I used the terms "Published" (instead of "complete") and "In review" (not complete). I don't have the full context of the mediated deposit work to know if those are acceptable terms to use, but I think the terms we use matter so it might be worth discussing.

In the examples below, I've also moved the workflow state into a label and put it next to the visibility state label. As long as we don't have more than a couple of labels like this, this arrangement seems better to me than having one next to the title and the other below the title.

(I like this approach, but another approach could be to present the visibility and workflow states elsewhere on the page, with the metadata. They wouldn't be as prominent there, which could either be good or bad, depending on how you feel about colorful labels in prominent places.)

![published-private](https://cloud.githubusercontent.com/assets/101482/22483624/e076a396-e7b2-11e6-9bd1-a3977e8a3976.png)

![in-review](https://cloud.githubusercontent.com/assets/101482/22483631/e62b0552-e7b2-11e6-98bb-7788e8b080ec.png)

![published-open](https://cloud.githubusercontent.com/assets/101482/22483633/eb3e4a9a-e7b2-11e6-9429-60e74076ac43.png)

**Comment by sfbetz** [comment]
What's the primary goal of workflow label vs access label? If workflow label is helping admin move items through a deposit and review process, then it should probably appear beside those other tasks.  If access label helps end user understand if she can view an object, then it makes sense in prominent spot like beside title. I can see huge potential for confusion with the "private / published" combo above. I understand what it means, but that's some pretty conflicting label info for a typical user. Can you point me to wireframes for steps through mediated workflow? That might help me understand question better. Also, do we need a show page for incomplete items?

**Comment by ggeisler** [comment]
@sfbetz Not sure if you are asking me specifically for wireframes or to answer your other questions, but I don't think I know any more than you about the mediated deposit details. I wasn't involved in the work and don't know if there are any wireframes produced by anyone else. I was just trying to help move this discussion forward. My assumption was the primary purpose of these labels is helping the user understand the status of the work.

I agree that the scenario with "private" and "published" could be confusing. It seems better to me than "private" and "deposited," but it would be great to hear some other ideas.

**Comment by sfbetz** [comment]
Sorry @ggeisler - I was pinged through UX advisors so just trying to get some context on question to help with solution. My questions are for everyone on thread (maybe @mjgiarlo can chime in?) - just trying to understand the UI and workflow steps that user progresses through when approving / mediating a work - seems to make sense to align label with those actions, using same language, but couldn't find any wireframes to see what that looks like...

**Comment by mjgiarlo** [comment]
@ggeisler Here's a little bit of data on what workflow states we currently have:

* deposited
* pending_review
* changes_required

And this can be expected to grow when users create and load their own custom workflows. I wonder if we should instead ask the work whether it's currently suppressed or not, and if so, show "Published" and if not, show "In Review"? What's nice about this is we can ask this in the future (without needing to explicitly map the new state onto one of these two labels) when new states are added, and I suspect most users want to know if a thing is available or not vs. what exact workflow state it's in.

**Comment by mjgiarlo** [comment]
@sfbetz :speech_balloon: 
> f workflow label is helping admin move items through a deposit and review process, then it should probably appear beside those other tasks. If access label helps end user understand if she can view an object, then it makes sense in prominent spot like beside title.

@ggeisler :speech_balloon: 
> My assumption was the primary purpose of these labels is helping the user understand the status of the work.

What I had in mind was the same as @ggeisler says here -- we have admin-specific workflow UI tools, which are admittedly a work in progress, but I don't see admins using show pages to push things through workflows.

**Comment by ggeisler** [comment]
@mjgiarlo Yep, showing either "Published" or "In review" appeals to me if it makes sense (and it sounds like it might). As you say, it seems like the most common thing a user would want to know here is just whether it's published or not, and that approach eliminates having to worry about new states that arise in future workflows.

If we go with this approach, then we can focus on answering the original question of this ticket, which I think was about styling of the workflow state. I don't have anything better to offer than my mockups above, where we show both the workflow and visibility states on the same line as the work title, styled as labels. If we use the terms "Published" and "In review," I don't think they need a "Workflow:" qualifier for them to make sense to the user, though I share a slight concern with @sfbetz about the situation when you have "Private" and "Published" next to each other. I don't have a basis for judging whether that has enough potential for confusion to warrant trying to come up with different strategy, however.

**Comment by mjgiarlo** [comment]
@ggeisler OK. My sense is that, given the mockups and discussion above, this issue is actionable -- and we can revisit the design, as always, when someone has time to do usability testing. Thank you!

**Comment by jcoyne** [comment]
@mjgiarlo this is done, right?

**Comment by mjgiarlo** [comment]
@jcoyne Not the design discussed above, no.

**Comment by no-reply** [comment]
@vantuyls I'd like to close this ticket and open a new issue with any further changes to workflow state display.

Thoughts?

**Comment by vantuyls** [comment]
I think this is done now? The discussion, it seems to me, doesn't resolve what changes actually need to be made beyond what we currently see in Hyrax. I'm inclined, also, to close if other participants don't have strong opinions.
