### ISSUE TITLE
show existing files when editing a work

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2267]
### Descriptive summary
currently, when editing a work, the Files tab does not show current attached files. this is counter to expected UI behaviour. Users expect to see the their files when editing an existing work. This could also make replacement (instead of versioning) of a file easier to accomplish in the ui. 

### Expected behavior
On Edit, Files tab should show existing attached files on the work. 

### Actual behavior
On Edit, Files tab shows no existing works, only newly added works.

**Comment by mjgiarlo** [comment]
Duplicates #125

**Comment by vantuyls** [comment]
would be useful if one could remove existing files when editing works, too.

**Comment by no-reply** [comment]
Closing this as a duplicate.
