### ISSUE TITLE
Update Hyrax chinese locale

### ISSUE THREAD

**Issue by hweng** [samvera/hyrax#2270]
### Descriptive summary

Please update the Hyrax chinese locale file to be up-to-date with the English version.

### Rationale

A Hyrax 2.0 release is coming soon, it would be a great for us to be able to help ensure the chinese locale file is accurate and up-to-date. 

### Related work

https://github.com/ucsdlib/horton/issues/147

**Comment by mjgiarlo** [comment]
@hweng I did update all locales when I cut the 2.0.0 release, which is already out. Can you say more about what you're looking for?

**Comment by hweng** [comment]
@mjgiarlo Sorry I was not aware the new release is out. This ticket's description is copied from https://github.com/ucsdlib/horton/issues/147.
I reviewed and updated the Chinese locals to have it makes more sense. It was done last Wednesday. And I thought it's better to make a pull request after the holiday .

**Comment by mjgiarlo** [comment]
No problem, @hweng! Thanks.

If you have any changes to recommend to the Chinese translations (some of which are not from a native speaker), I'd be happy to merge a pull request. Should we keep this issue open for that, or close the issue?

**Comment by hweng** [comment]
@mjgiarlo I just tried to push a commit, got "fatal: unable to access 'https://github.com/samvera/hyrax.git/': The requested URL returned error: 403"

Then I updated .git/config to use ssh:  .git/config url = ssh://git@github.com:samvera/hyrax.git, but get the "ERROR: Repository not found. fatal: Could not read from remote repository."

Since It didn't happen to me last time when I made a pull request for creating the chinese locals. Do you have any idea about it?

You may close this issue now or after the pull request merged. Thanks!

**Comment by hweng** [comment]
The permission issue is resolved. I was not in the samvera developer community. @jeremyf just sent me an invitation.
