### ISSUE TITLE
TinyMCE editor is not loading menu based on config yml

### ISSUE THREAD

**Issue by crowesn** [samvera/hyrax#2273]
### Descriptive summary

Hyrax 1.0.5 - The tinymce editor loads what appears to be a default menu set, ignoring menu elements included in config yml

### Rationale

Menu items to include image attachment and linking functions are missing without config yml in force.

### Expected behavior

Tinymce editor should load with menu items from config yml

### Actual behavior

Tinymce editor loads with what appears to be a default menu set, does not include menu items required by config yml

### Related work

Local fix from Scholar@UC - https://github.com/uclibs/scholar_uc/pull/1763

**Comment by sandbergja** [comment]
Thanks so much for taking this on, @dlpierce.  It will be very helpful for us. :-)

**Comment by revgum** [comment]
@dlpierce  

Can I suggest a fix?

Replace : https://github.com/samvera/hyrax/blob/master/app/assets/javascripts/hyrax/app.js.erb#L29-L31

with `tinyMCE.init(<%= TinyMCE::Rails.configuration.to_javascript %>);` and the tinymce.yml will be rendered as the options to the editor.

Also, however, the current `tinymce.yml` is referring to an old image upload plugin.. I would propose to use TinyMCE's image plugin instead. Here's the `tinymce.yml` that works well for us:

```
menubar: false
toolbar1: styleselect | bold italic | undo redo
toolbar2: table | fullscreen | image
plugins:
  - table
  - fullscreen
  - image
```

**Comment by crowesn** [comment]
we resolved this issue in our 1.0 app with this simple fix: https://github.com/uclibs/scholar_uc/pull/1763/files

**Comment by revgum** [comment]
That's also a good fix, though I think the `tinyMCE` related code in `app.js.erb` should be removed, to avoid confusion, if this is the long term solution.

On the other hand, there is a decent argument to be made for keeping the `tinyMCE` initialization inside `app.js.erb` and using the `#to_javascript` method in that it keeps this kind of javascript initialization alongside the others that the Hyrax app uses.

**Comment by dlpierce** [comment]
Calling the tinymce helper in a form that uses it is enough to load a config, and seems to be the least amount of change to make it work. See https://github.com/samvera/hyrax/pull/2953/files#diff-5224152394414a552e0be1d14e12a812R65

**Comment by dlim87** [comment]
Nurax doesn't appear to be reading the config file, still. Among other things, it's set to hide the menubar, but it's still showing the default tinymce configuration that has it

**Comment by jlhardes** [comment]
@dlpierce this looks like you have been involved on this one already and there is a solution to implement. Does that still need to happen?

**Comment by jlhardes** [comment]
Able to change .dassie/config/tinymce.yml settings and that changes the menu options whenever the TinyMCE WYSIWYG editor is loaded. Tested in Pages and Content Blocks for repo-admin users.
