### ISSUE TITLE
The depositor of a Work should be granted a `depositing` sipity entity role by default

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#228]
<a href="https://github.com/revgum"><img src="https://avatars.githubusercontent.com/u/32885?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [revgum](https://github.com/revgum)**
_Thursday Dec 01, 2016 at 00:42 GMT_
_Originally opened as https://github.com/projecthydra/curation_concerns/issues/1114_

----

- [ ] When a Work is first created, the user that deposited the work should be granted the `depositing` sipity role for this specific entity.

This aims to establish a default role for users who deposit works and eliminates the need for role management at this level. This enables the ability to redirect works back to the depositor to take some action midway through a workflow (ie. review a work before it is approved, in a mediated deposit context).

@jeremyf points out that this type of functionality exists in Sipity:
Form: https://github.com/ndlib/sipity/blob/master/app/forms/sipity/forms/submission_windows/etd/start_a_submission_form.rb#L88

Granting permissions: https://github.com/ndlib/sipity/blob/e240064a490156d432df001e582a46e9bcb550ea/app/repositories/sipity/commands/permission_commands.rb#L16

**Comment by mjgiarlo** [comment]
@vantuyls Do you want to slot this into MD milestone 2 or 3, or leave in its current milestone?

**Comment by mjgiarlo** [comment]
This issue requires reconsideration given #256. It's no longer the case that we want to grant this role to this workflow automatically. This is related to https://github.com/projecthydra/sufia/issues/3049#issuecomment-277013620

I'm inclined to close this ticket.

**Comment by vantuyls** [comment]
im fine with closing this given #256 as long as there is a way to assign the depositor the depositor role in the workflow or in the admin set.

**Comment by hannahfrost** [comment]
👍

**Comment by jcoyne** [comment]
Isn't the idea for this to allow the submitter to make edits and resubmit their work once it's been returned for some reason?

**Comment by mjgiarlo** [comment]
Yes, that's right, @jcoyne, and I can confirm this isn't currently working.

The work that remains to be done with this ticket is to wire the Admin Set "Depositor" role to the appropriate workflow "depositing" role, the same way we wired the Admin Set "Manager" role to the appropriate workflow "approving" role. 

I assume this is high priority.

**Comment by hannahfrost** [comment]
Yes, @mjgiarlo. High Priority.

**Comment by mjgiarlo** [comment]
@hannahfrost Done!

**Comment by jcoyne** [comment]
>The work that remains to be done with this ticket is to wire the Admin Set "Depositor" role to the appropriate workflow "depositing" role, the same way we wired the Admin Set "Manager" role to the appropriate workflow "approving" role.

@mjgiarlo I'm not sure that's right. I think I heard @jeremyf talking about an entity specific responsibility. I think that's the direction we need to go. Otherwise anyone with deposit access to the admin set could modify this work.  I'd really like @jeremyf's to lay out a plan for the way forward on this.

**Comment by mjgiarlo** [comment]
> Otherwise anyone with deposit access to the admin set could modify this work.

Why is that the case? Because until the work is published, access/visibility is governed by workflow roles (vs. ACLs), and if two users share this role, they both have equal access to it?

If :arrow_up: is right, I agree that we should talk with @jeremyf about this and figure out:

1. How/when to grant users the ability to take the `request_review` action in a workflow?
2. How to build out the admin set depositor feature?

**Comment by jcoyne** [comment]
When I submit a work, I should be granted  the depositor role for this entity (and only this entity).  We should make a callback in the workflow at the deposit time. The callback will grants the depositor the entity specific role. 

This role should allow the user to return the entity to the initial state (allowing edits) and then must be resubmitted for approval.

**Comment by jeremyf** [comment]
@jcoyne The service class you want is here: https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/workflow/permission_generator.rb

The example of granting entity specific permissions: https://github.com/projecthydra-labs/hyrax/blob/master/spec/services/hyrax/workflow/permission_generator_spec.rb#L25-L31

**Comment by jeremyf** [comment]
@mjgiarlo @vantuyls Are there considerations for deposited on behalf of? (Proxy deposits?)

**Comment by mjgiarlo** [comment]
@jeremyf Is this in progress?

Yes, we should think through the interaction with proxy deposits.

**Comment by jeremyf** [comment]
@mjgiarlo I'm opening this up to work on.

Can you fill in the blank?

```gherkin
Given I can deposit a work as a proxy for User A
When I deposit a work on behalf of User A
Then I _____ have the "depositing" role for the deposited work
And User A _____ have the "depositing" role for the deposited work
```

**Comment by mjgiarlo** [comment]
Discussing on Slack, @jeremyf

**Comment by mjgiarlo** [comment]
This issue should be worked on separate from any changes to the timing around when proxy deposits fire.

**Comment by jeremyf** [comment]
Based on Slack conversations the following is the correct behavior.

```gherkin
Given I can deposit a work as a proxy for User A
When I deposit a work on behalf of User A
Then I will have the "depositing" role for the deposited work
And User A will not have the "depositing" role for the deposited work
```

**Comment by mjgiarlo** [comment]
Follow-up issue that changes how proxy depositors interact with mediated deposit workflows: https://github.com/projecthydra-labs/hyrax/issues/534

**Comment by no-reply** [comment]
@vantuyls Maybe we should close this pending the output of the permissions WG? Is there someone there we can tag in? (is that @jeremyf?)

**Comment by vantuyls** [comment]
or @laritakr
