### ISSUE TITLE
make read access works available to add to collections

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2280]
Adding works a user can read/see to a collection is an important use case.

# Current Behavior
User can only add works to a collection that they "own" (ie that show up in My Works)

# Expected Behavior
User should be able to add works to a collection that they can see/read

**Comment by elrayle** [comment]
The behavior is...
* can add works to collections when current_user can edit or deposit into the collection
* cannot add works to collections when current_user only has read access to the collection

**Comment by elrayle** [comment]
This was addressed by the addition of checkboxes to Managed Works such that batch Add to Collection can be used to add readonly works to a collection.  PR #2434

**Comment by elrayle** [comment]
@vantuyls I would like to close this issue.  The title of the issue and the description don't seem to match.  I believe the title is the correct description of the issue.  Such that, it's not that you want to add any work to a readonly collection.  It is that you want to add a readonly work to a collection which you have deposit/edit access.  Please confirm so I can close this issue.

**Comment by vantuyls** [comment]
Yes, i believe that i accurate. Closing now.
