### ISSUE TITLE
InterpretVisibilityActor should return false if dates are not valid lease/embargo

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#229]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Friday Dec 02, 2016 at 15:04 GMT_
_Originally opened as https://github.com/projecthydra/curation_concerns/issues/1115_

----

If invalid dates for the lease or embargo are provided, it raises an uncaught `ArgumentError: invalid date`

**Comment by mjgiarlo** [comment]
<a href="https://github.com/tdonohue"><img src="https://avatars.githubusercontent.com/u/483997?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tdonohue](https://github.com/tdonohue)**
_Monday Dec 05, 2016 at 22:48 GMT_

----

I dug into this a bit today. It seems there *is* date validation code in Embargoable at: https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/models/concerns/hydra/access_controls/embargoable.rb#L9 

This date validation code also checks for invalid dates, see: https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/validators/hydra/future_date_validator.rb

However, the existing validation code doesn't seem to be triggered before the `ArgumentError: invalid date` occurs in `Embargo.embargo_release_date=` : https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/models/hydra/access_controls/embargo.rb#L9

I'm a bit confused as to why the validation isn't triggering when expected.  But, after this bit of digging, it seems like there may be something deeper to this bug. I'm not sure adding duplicative validation to `InterpretVisibilityActor` will solve the issues.  Any hints/ideas here, @jcoyne ?

**Comment by vantuyls** [comment]
@luisgreg99 any update on our local investigation of this issue? drop comments here please.

**Comment by no-reply** [comment]
Are there steps to reproduce for this issue?

**Comment by no-reply** [comment]
confirming that the named module behaves as described (it has tests that predate this ticket ensuring this!). an ActorStack level test introduced in #4802 also confirms that the actor stack rejects expired embargos.
