### ISSUE TITLE
Maintain Visibility Setting When Transferring Ownership of a Work

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#2293]
### Descriptive summary

When you transfer a work to another user, the work's visibility setting is changed to Private. Work ownership transfers should maintain the visibility settings of the work as they were before the transfer.

### Rationale

The unexpected change in visibility settings adds a task for a user when they accept ownership of a public, embargoed, or institution-only work. The new owner of the work might not know the original visibility setting of the work. This creates confusion.

### Expected behavior

Visibility settings should not change during the ownership transfer between users.

### Actual behavior

Visibility is changed to Private for all transferred works.

### Steps to reproduce the behavior

- User A creates a Work and sets the visibility to public (makes sure the admin set the does not have a mediated workflow activated)
- User A transfers the work to User B
- User B accepts the work
- Check the visibility status

### Related Work

First reported https://github.com/curationexperts/nurax/issues/135

**Comment by mcdowney** [comment]
I think this is fixed, so closing for now.
