### ISSUE TITLE
Wire up nested collection delete buttons on collection's admin show page

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2295]
### Descriptive summary

Collections Sprint: Nested collections relationships can be added on the index page actions, show page buttons, or edit view relationships tab. The relationships tab contains buttons to remove the relationships, but the modals are not yet wired up.

- /app/views/hyrax/dashboard/collections/_modal_remove_from_collection.html.erb
- /app/views/hyrax/dashboard/collections/_modal_remove_sub_collection.html.erb

### Details

All functionality regarding nesting collections should be routed through the nest collection controller, form, and persistence service. This originates on the edit collections view, so this task will require:

- [ ] adding routes for the remove actions, similar to the routes already present for the actions which create the relationships
- [ ] new remove methods in the nest collection controller corresponding to the new actions
- [ ] a new method in the nested collection persistence service to persist the changes
- [ ] wire up the modals to use the new routing to remove the relationships

### Design Modification

In order to simplify the UI and make it more consistent, the management of collection relationships is going to only be available on the collection's admin show page.  This is already the location where work relationships with a collection are managed.

The following changes should be made as part of this issue's resolution.

* remove Relationships tab from edit form
* move Remove modal to admin show page
* add Remove buttons to admin show page for parents and subcollections
* hook up Remove buttons so they launch the Remove confirmation modal and remove the relationship if confirmed

Make sure the ability to Create new collection as subcollection from the parent collection's admin show page still works with the Relationships tab removed from the edit form.

### Related issues
#1719 
#2294 
#2221

**Comment by laritakr** [comment]
Referencing Issue #2573 because PR #2487 may change the design for this issue mentioned above for this issue.

**Comment by elrayle** [comment]
@laritakr Is this done with PR #2692 and #2727?
