### ISSUE TITLE
Administrator is missing download/view abilities

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#230]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [awead](https://github.com/awead)**
_Thursday Dec 08, 2016 at 21:16 GMT_
_Originally opened as https://github.com/projecthydra/curation_concerns/issues/1118_

----

### Descriptive summary

Administrators aren't able to see files attached to works, view thumbnails, or download their content.

At Penn State we fixed this my making changes to DownloadsController and Ability.

https://github.com/psu-stewardship/scholarsphere/commit/fe3cd199ec7bd912e815cdda9df0d793f1e667e3

I'm marking the issue here, but I'm not sure if the patch should be the same or go in this repo.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Dec 08, 2016 at 23:42 GMT_

----

I'd suggest fixing the download issue by doing this in `Ability`:

```ruby
can :download, :all if admin?
```

**Comment by mjgiarlo** [comment]
<a href="https://github.com/awead"><img src="https://avatars.githubusercontent.com/u/312085?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [awead](https://github.com/awead)**
_Friday Dec 09, 2016 at 16:23 GMT_

----

Good idea. Doesn't work right off the bat, so there needs to be some tweaking in CanCanCan maybe.

**Comment by no-reply** [comment]
Is this still an issue?

**Comment by vantuyls** [comment]
no longer an issue. administrator can now see and interact with all works regardless of visibility etc.
