### ISSUE TITLE
Consider removing notifiable contexts from Sipity::WorkflowState

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#231]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Wednesday Oct 12, 2016 at 18:55 GMT_
_Originally opened as https://github.com/projecthydra/curation_concerns/issues/1054_

----

I think the notifiable_contexts in Sipity::WorkflowAction ought to be sufficient.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Wednesday Oct 12, 2016 at 21:33 GMT_

----

@jeremyf what do you think of this proposal?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jeremyf"><img src="https://avatars.githubusercontent.com/u/2130?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeremyf](https://github.com/jeremyf)**
_Wednesday Oct 12, 2016 at 23:14 GMT_

----

The plan would be to replace those with functions as part of the callback? I can get behind that. It would move the configuration of emails out of the database and into a function.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Oct 13, 2016 at 02:01 GMT_

----

@jeremyf I don't think I made myself clear.  Presently it allows WorkflowState and WorkflowAction to be notifiable contexts. I'm positing that we don't need notifiable contexts for both states and actions.  I think that notifications should happen only on WorkflowActions.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Monday Nov 14, 2016 at 22:00 GMT_

----

@jeremyf ping?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Jan 10, 2017 at 17:30 GMT_

----

:arrow_up: @jeremyf comments?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jeremyf"><img src="https://avatars.githubusercontent.com/u/2130?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeremyf](https://github.com/jeremyf)**
_Tuesday Jan 10, 2017 at 17:32 GMT_

----

Yes. Notifications need only happen for actions.

Jeremy Friesen

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Jan 10, 2017 at 17:51 GMT_

----

OK, I'll move this to Hyrax. Thanks!

**Comment by mjgiarlo** [comment]
@vantuyls Do you want to slot this into MD milestone 2 or 3, or leave in its current milestone?

**Comment by no-reply** [comment]
It sounds like we have considered this. Is there an interest in making a ticket to do any particular work here?

As it stands, I'm not sure anyone but @jcoyne or @jeremyf could tease out what the actionable part of this ticket is in a reasonable amount of time.
