### ISSUE TITLE
Draft 2.1.0 release notes

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#2326]
# IIIF

Make clear in the release notes the requirement that Apache and Passenger require configuration to get RIIIF integration working. See https://github.com/curationexperts/riiif/blob/753ed1d73bc58d18124b247dc5a006fc60cb54a6/README.md#special-note-for-passenger-and-apache-users.

Also, write up the steps needed to use RIIIF when upgrading:

1. Copy [new config values](https://github.com/samvera/hyrax/blob/e2b2e9fd718f72c283b7165c93ccbc98a335a1ed/lib/generators/hyrax/templates/config/initializers/hyrax.rb#L114-L144) to `config/initializers/hyrax.rb`
2. Leave the new config values commented out if you won't be enabling the IIIF image server. You're done! Else, uncomment at least `config.iiif_image_server` and set it to true.
3. If using RIIIF, run `rails g hyrax:riiif`.
4. [Turn on public file server](https://github.com/pulibrary/pul_uv_rails/issues/8)
5. See more in-depth instructions here: https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#image-server

# Actor stack

If you've customized the actor stack or integrated with it in your code, note that the structure of collection members has changed. `member_of_collection_ids` was deprecated, to be replaced by `member_of_collections_attributes`:

```diff
- { 
-   member_of_collection_ids: ['123']
- }
+ {
+   member_of_collections_attributes: { '0' => { id: '123' } },
+ }
```

# Show View Attribute CSS

The CSS classes for individual attributes in the show view have been changed to use a prefix. This is to avoid collisions between attribute names and classes elsewhere in the codebase (e.g. "pagination"). 

```diff
- <li class='attribute title'>
+ <li class='attribute attribute-title'>
```

**Comment by no-reply** [comment]
@mjgiarlo Is it okay to edit the second section of this, since we again support `member_of_collection_ids` env params?

**Comment by mjgiarlo** [comment]
@no-reply Yes, please! Feel free to build out the release notes as you/we see fit in the description above. Thank you for your work on this.

**Comment by mkorcy** [comment]
@mjgiarlo The IIIF notes you added for Apache + Passenger users are also true for the default AdminSet, loading `/admin/admin_sets/admin_set%2Fdefault` so those notes may be more generally applicable and worth noting outside the IIIF scope.

**Comment by mjgiarlo** [comment]
@mkorcy OK, cool. I added a note to the Hyrax mgmt guide here: https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#slashes-in-default-admin-set Feel free to tweak that as you wish. Thanks!

**Comment by no-reply** [comment]
This was released.
