### ISSUE TITLE
Use UniversalViewer on the work show page

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#2345]
- [x] Pull in UniversalViewer and use when `Hyrax.config.iiif_image_server?` is `true` (extract from Hyku)
- [x] Layer in the [`rendering_ids` change](https://github.com/samvera-labs/hyku/pull/1376)
- [x] Layer in [adding metadata to the manifest](https://github.com/samvera-labs/hyku/pull/1436)
- [x] Additional Javascript changes (mentioned by @geekscruff)

**Comment by no-reply** [comment]
Can this be closed following the merge of https://github.com/samvera-labs/hyku/pull/1436 ?

**Comment by julesies** [comment]
@mjgiarlo is this done??

**Comment by geekscruff** [comment]
The additional javascript changes haven't been done, but they are not essential and can be pulled into a separate issue - I'm happy to do that. The rest is complete AFAIK.

**Comment by julesies** [comment]
@geekscruff thanks. We are trying to see if this is ready to test on Nurax. Getting UV running on Nurax is one of the things we want to do before 2.1.0 beta so just checking in on timing/readiness. 
cc @cjcolvar who is working on the nurax side.

**Comment by geekscruff** [comment]
Yes, I'd say so for sure ... it may not be 'switched on' in the current deployment, see the info here https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#image-server

If it isn't, it looks like you can run
```
rails g hyrax:riiif
```

and check that 

```
config.iiif_image_server = true
```

**Comment by geekscruff** [comment]
I think it might expose some documentation requirements and I'd be happy to contribute

**Comment by julesies** [comment]
@geekscruff that would be awesome, this is what we have so far, some notes that @cjcolvar is working from for nurax https://github.com/curationexperts/nurax/issues/171

**Comment by mjgiarlo** [comment]
In addition to the coverage of this in the management guide, there's also this draft documentation which will go into the 2.1.0 release notes: https://github.com/samvera/hyrax/issues/2326

Just fyi!

**Comment by geekscruff** [comment]
I've added an issue for number for in the list: https://github.com/samvera/hyrax/issues/2723

**Comment by geekscruff** [comment]
I think we can close this now.

**Comment by vantuyls** [comment]
@geekscruff @mjgiarlo @no-reply @julesies i'm planning to close this (per the comments) if there are no objections.
