### ISSUE TITLE
ActiveFedora::Base.reindex_everything loses all nested indexing fields in solr

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2372]
### Descriptive summary

In Collections Sprint branch, nested indexer adds **"nesting_collection__ancestors_ssim"**,
**"nesting_collection__parent_ids_ssim"**, and **"nesting_collection__pathnames_ssim"**. Running 
`ActiveFedora::Base.reindex_everything` from the rails console removed all three of those fields from solr. 

### Rationale

The nested collection indexer is triggered as an after update_index action in Hyrax. Running the Active Fedora reindexer is indexing separately from the nested collections indexer and doesn't trigger the necessary action.

### Expected behavior

Running a full reindex needs to reindex all nested collections as well.

### Actual behavior

The nested collection indexing is not being included.

### Steps to reproduce the behavior

1. Create nested collections.
1. Solr indexes should include the three nesting collection fields.
1. Open rails console
1. ActiveFedora::Base.reindex_everything
1. Solr indexes are missing all three nesting collection fields.

**Comment by laritakr** [comment]
The issue here is that ActiveFedora uses to_solr for its reindexing. For nested collections, to_solr does not include the additional nested collections indexed fields. Those are added in Hyrax as an after_update_index callback which reindexes the collection again.

Methods `each_preservation_document` and `each_perservation_document_id_and_parent_ids` are not implemented in Hyrax::Adapters::NestingIndexAdapter so Samvera::NestingIndexer::RepositoryReindexer will not currently function.

In the meantime, if each TOP level nested collection is manually reindexed, it will reindex all of the child collections.

**Comment by elrayle** [comment]
@laritakr Can this be closed with the merge of PR #2636?

**Comment by laritakr** [comment]
Resolved via PR #2636
