### ISSUE TITLE
Deprecation warning on the primary code path.

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#2388]
There doesn't seem to be any way to avoid this deprecation.

```
DEPRECATION WARNING: passing in permissions with a new collection is deprecated and will be removed from Hyrax 3.0 (). (called from collection_params at /Users/jcoyne/workspace/samvera/hyrax-collections/app/controllers/hyrax/dashboard/collections_controller.rb:342)
```

**Comment by no-reply** [comment]
Can we clear up this deprecation? I'm not clear on what we plan to remove, or what I should fix to avoid breakage in 3.0.

Alternatively, we could remove the warning and continue to use the existing behavior.

**Comment by no-reply** [comment]
@elrayle I think the issue here is that current Hyrax mainline code uses the old interface. I don't think we can deprecate until we can change internal callers.

**Comment by no-reply** [comment]
A potential rework with a better deprecation warning might be:

```return [] unless permissions = attributes.delete("permissions_attributes")

Deprecation.warn(self, "some message about not calling with `permissions_attributes`")

permissions.each_with_object([]) do |p, participants|
  next unless access = access(p)
  participants << { agent_type: agent_type(p), agent_id: p["name"], access: access }
end```

**Comment by elrayle** [comment]
@no-reply Your example is very helpful.  I will look and see if there are places that need to be updated or if the deprecation needs to be removed because we are still using it.

**Comment by elrayle** [comment]
The example in hyrax/app/forms/hyrax/forms/batch_edit_form.rb is permissions for a work.  It is not subject to the deprecation warning which applies to collections only.

I could find no usages in the primary code of setting permissions on collections using permissions_attributes parameter.
