### ISSUE TITLE
Collections branch over uses feature tests

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#2389]
Feature tests are exceptionally slow, therefore they should be used judiciously.  In `spec/features/dashboard/collection_spec.rb` it's testing a number of edge cases that could be tested in the form test or view tests instead.

**Comment by jeremyf** [comment]
There are a lot of JS features being tested as well. I think for this to move forward, we'll need someone comfortable with refactoring feature tests into their smaller constellations of unit tests.
