### ISSUE TITLE
Implementing Workflow Action Callback Service Validation

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#240]
<a href="https://github.com/jeremyf"><img src="https://avatars.githubusercontent.com/u/2130?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeremyf](https://github.com/jeremyf)**
_Friday Sep 23, 2016 at 15:06 GMT_
_Originally opened as https://github.com/projecthydra/curation_concerns/issues/1024_

----

With the addition of [CurationConcerns::Workflow::ActionTakenService](https://github.com/projecthydra/curation_concerns/blob/d797e6ad735430392a7d744c6304ded9f797e8bf/app/services/curation_concerns/workflow/action_taken_service.rb), implementors will make callback functions.

These functions should adhere to an expected interface. To provide guidance on updating installations, a spec helper (e.g. "it is expected to conform to the Workflow Action Callback Service interface) should be created.

See #1023

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Tuesday Jan 10, 2017 at 17:34 GMT_

----

@jcoyne @jeremyf Should we pull this over to Hyrax, or meh?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jeremyf"><img src="https://avatars.githubusercontent.com/u/2130?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jeremyf](https://github.com/jeremyf)**
_Wednesday Jan 11, 2017 at 14:16 GMT_

----

@mjgiarlo I think this is something to move to Hyrax

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Wednesday Jan 11, 2017 at 18:54 GMT_

----

@jeremyf OK, will do.

**Comment by no-reply** [comment]
Closing this pending any particular need.
