### ISSUE TITLE
Changing  the AdminSet predicate breaks AdminSetService

### ISSUE THREAD

**Issue by little9** [samvera/hyrax#2405]
### Descriptive summary

A new option was added to Hyrax 2.0.0 that lets you change the admin set membership predicate. By default this is `isPartOf`. If you change the predicate the AdminSetService performs bad solr queries because the isPartOf predicate is hardcoded in the service: https://github.com/samvera/hyrax/blob/150e5bc99a48915160e4a1e909d262bd05acfb55/app/services/hyrax/admin_set_service.rb#L29
### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Expected behavior

The `AdminSetMember` service works correctly after changing the admin set predicate.

### Actual behavior

It doesn't because the solr query is hardcoded. 

### Steps to reproduce the behavior

1. Change the admin set membership predicate
2. View a page that has admin set counts 

### Related work

Issue #1461

**Comment by bess** [comment]
@mjgiarlo suggests perhaps we need to use `Solrizer.solr_name(Hyrax.config.admin_set_predicate.qname.last, :symbol)` 

@no-reply notes that this is also an issue elsewhere in the code base

**Comment by CGillen** [comment]
@vantuyls This issue was never actually solved. The comment on curationexperts/epigaea/pull/797 accidentally closed this automatically. That PR does provide a solution that can be used here.

**Comment by wickr** [comment]
Reopening since the code was merged into the epigaea repo not here.
