### ISSUE TITLE
Collect new and returning users per week from Google Analytics

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#244]
Display these numbers as a bar chart in the "User activity" section of the "activity summary"

See projecthydra-labs/hyku#431 for mockup.

**Comment by mjgiarlo** [comment]
#238 incorrectly referenced this ticket, when it was meant for #224. Ignore the above commits; they are unrelated.

**Comment by jcoyne** [comment]
Part of this work (new users) is going to be done in #430. The purpose of this ticket is to harvest the returning user count and add it to the existing graph.
