### ISSUE TITLE
Removed nested forms from modals in Collection edit

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2457]
### Descriptive summary

The collections edit form has nested html form tags.  This is not allowed in HTML 5.  It may have unpredictable behaviors in the UI.

### Rationale

We should follow HTML 5 specifications and not nest forms.

### Expected behavior

To be able to edit metadata fields and save.

### Actual behavior

There are currently no failures through the UI, but not all browsers have been tested.  A test failure can be caused by giving a user access to the collection which causes a nested form to be included in the edit collection page that allows the user's access to be removed.

Modify test:   https://github.com/samvera/hyrax/blob/collections-sprint/spec/features/dashboard/collection_spec.rb - edit collection (around line 592) -> from dashboard -> collections actions menu (around line 622)

Recommended modification:  TBA - test is being rewritten to avoid failure as part of PR #2447 

### Steps to reproduce the behavior

Through UI:
1. Create a collection
1. Edit the collection
1. Change some metadata fields
1. Change things on other tabs
1. Click Save changes

Verify changes from all tabs are made to the collection.  

NOTE: Not seeing problems doing this in the UI before the refactor.  Want to make sure it continues to work after the refactor.

Through tests:
1. Run test with modifications that cause Manage User form to include a Remove button for the user who created the collection.  spec/features/dashboard/collection_spec.rb around line 630

### Related work

PR #2447 Adds access to collections

**Comment by adamjarling** [comment]
@laritakr  Looks like the main issue with nested forms (at least here), is that the modal windows have their own `<form>`s.  And then there’s the main form wrapping all tabs.   

One route (at least to try) would be to post the data via JavaScript.  So I’d remove the nested `<form>` tag, put a click listener on the button, then do an AJAX post.   Does that sound like a reasonable alternative?

The risk is it alters (possibly) the way the current app was meant to handle success/failures of the nested form post…. possibly.  Not really sure how (or where), the handling action is happening.

I’d have to figure out what data this (for one example modal) returns, `form_tag(hyrax.dashboard_create_nest_collection_under_path(collection.id))` , then somehow stick that to the modal markup via `data-xxx` attributes.  Then the JS handler can read the data attribute values, and make an AJAX post.

Does this sound like a direction to even attempt?

**Comment by laritakr** [comment]
Calling @jeremyf in to help with ideas, since I based my code on the form he set up.

**Comment by laritakr** [comment]
I don't have an answer to the forms issue itself, as that was based on the structure that @jeremyf set up, but conceptually this appears to go back to my concern with having the relationships tab on the edit collections page. 

Editing relationships is not the same as editing collections, and should really be done separately from the collections. (Just because we did it that way for works doesn't mean it was right then either, and doesn't mean we should base new development on a prior wrong solution.)

The nested relationships can already be managed elsewhere... do we have the same problem on the index or show views?

**Comment by elrayle** [comment]
One line was added to features/dashboard/collection_spec.rb test `edit collection` (around line 592) -> `from dashboard -> collections action menu` (around line 621).  See the TODO which references this issue.  If you comment out the statement starting with `allow_any_instance_of(ActiveRecord::Association::CollectionProxy`, you will see the error caused by nested forms.  Once the refactor is complete, this line and related comments can be deleted.

The line to avoid the nested form failure was added by PR #2447.

**Comment by elrayle** [comment]
There is also a problem with the forms for the Sharing tab.  When access is granted, there is a form with a Remove button for each user/group granted access.

**Comment by adamjarling** [comment]
@elrayle @laritakr  Quick update, I've removed the nested forms from modals for the Edit Collections "Relationships" tab, as it seemed pretty straight forward and seems to work.

The bad news in the "Sharing" tab's form construction is a bit more complex and seems pretty risky (for me to the the work at least) to re-factor it.   

The specific issue which started this whole line of work, seems to be using https://apidock.com/rails/ActionView/Helpers/UrlHelper/button_to for the "Remove" button in the User/Group table.  

My question would be was this implemented this way for a certain reason?  Like security, or could be a need that I don't know about?   I could try to remove that button helper and just handle the link directly and see what that does?

**Comment by laritakr** [comment]
@adamjarling Sorry, I'm not at all familiar with the implementation of the remove button, so I can't offer any insights into that. That seems to be the way a lot of buttons are done though, so it seems surprising that it would be causing problems just in this one place. However, if you can easily make the change and see if it helps in this case, it seems like a reasonable thing to try.

**Comment by adamjarling** [comment]
@elrayle I might have a fairly straightforward fix for your previous failing test situation.  In `app/views/hyrax/dashboard/collections/_form_share_table.html.erb`, replace `button_to t(".#{access}.remove")` in both cases with `link_to t(".#{access}.remove")`.   Looks like the functionality is the same in the UI.  Curious if that'd pass the test for you.   

I'm did a `reset --hard` against your `coll-2219_works_into_deposit_col`, and now I'm getting 9 failing tests in `spec/features/dashboard/collection_spec.rb`.   Not sure of the cause, could be a misconfiguration or something on my end, but until I figure that out I can't really test the rspec.

**Comment by elrayle** [comment]
There is also a problem with the forms for the Sharing tab.  When access is granted, there is a form with a Remove button for each user/group granted access.

**Comment by adamjarling** [comment]
An update to the scope of this ticket; we'll be removing the nested forms living in modals created when editing Collections.

**Comment by elrayle** [comment]
Fixed by PR #2481
