### ISSUE TITLE
Dead or untested code

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#2458]
There are no tests showing how we ever get into this block.  Is it dead code?
https://github.com/samvera/hyrax/blob/collections-sprint/app/controllers/hyrax/dashboard/collections_controller.rb#L290-L292

Added in https://github.com/samvera/hyrax/commit/51d30b3daf8d59484d1faaca2b84b2ae0acf753a

**Comment by blancoj** [comment]
That is supposed to avoid adding a logo again on edit. The test case would be...
* create a collection
* add one logo with alttext and linkurl
* save
* now, go and update that logos alttext and linkurl and add another logo.
* you should see the changed alttext and linkurl and also the  new logo information.

**Comment by jcoyne** [comment]
@blancoj great. can you write that into an RSpec test?

**Comment by jeremyf** [comment]
We've lost the thread of what code is unused. I'm closing this issue. If it remains, we'll need someone to submit a new ticket.
