### ISSUE TITLE
Dashboard::CollectionSearchBuilder is confused about AdminSets

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#2468]
Here it says to allow `AdminSets`

https://github.com/samvera/hyrax/blob/collections-sprint/app/search_builders/hyrax/dashboard/collections_search_builder.rb#L11

whereas here it is only getting `Collections`

https://github.com/samvera/hyrax/blob/collections-sprint/app/search_builders/hyrax/dashboard/collections_search_builder.rb#L38
  
Also take a look at https://github.com/samvera/hyrax/blob/collections-sprint/app/search_builders/hyrax/dashboard/collections_search_builder.rb#L21

**Comment by jonathandixon** [comment]
I believe Admin Sets are now just a type of Collection.

- L11 allows the search builder to return both collections and admin sets. 
- L21 should return ids for collections/admin sets the users has the required permissions for.
- L38 - creators of collections are stored as the depositor and creators of admin sets are stored as creator. This method accounts for this discrepancy.

**Comment by jcoyne** [comment]
@jonathandixon I don't believe that L38 works as you have stated.  Presently it's filtering for permission templates that are `source_type = 'collection'` ( which precludes `source_type='admin_set'`) You can find that code here: https://github.com/samvera/hyrax/blob/collections-sprint/app/services/hyrax/collections/permissions_service.rb#L15

**Comment by jonathandixon** [comment]
You are correct. If I recall correctly, this search builder was originally designed to return both Admin sets and collections. If that is still the case then a call to `Hyrax::Collections::PermissionsService#admin_set_ids_for_deposit` should also be made from the search builder.

**Comment by elrayle** [comment]
Admin Sets 'look like' just another type of Collection, but in reality are almost exclusively processed the same as they were before CE.  They are included in the lists that show up on Dashboard -> Collections -> Your/Managed Collections, but editing uses the original admin set process.

I'm looking deeper to understand why collection_search_builder.rb was switched from returning both admin sets and collections (`source_ids_for_deposit`) to just collections (`collection_ids_for_deposit`) in PR #1774.  I notice that admin_set_search_builder.rb uses `admin_set_ids_for_deposit`.  The dashboard does include both, so I'm looking to see how the `solr_access_filters_logic` method is playing into this search builder and confirming which search builder creates the list of admin sets/collections for the dashboard.

**Comment by elrayle** [comment]
@jcoyne Seems like this issue will be addressed when PR #2382 is merged with the change from using collection_ids_for_deposit to source_ids_for_deposit.  Do have any other remaining questions?

**Comment by elrayle** [comment]
PR #2382 is merged... closing
