### ISSUE TITLE
Add parent collection details to Collections show page

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#2478]
### Description
In the mockup located in issue #1678 the content for the Parent Collection needs to be added to the page.  This work is part of the Collection Extensions sprint.

The markup should be wired up to display as follows:

```
<% #TODO: Should the display of this be conditional? %>
<section class="parent-collection-wrapper">
  <h4>[TODO: Wire up] Parent Collection</h4>
  <a href="#">[TODO: wire up] Butterflies of the World</a>
  <span class="parent-collections-count">(24)</span>
</section>
```

### Rationale
Now that collections may be nested, the UI should be updated to reflect these relationships.

### Expected behavior
If a parent collection exists, it will be displayed.

### Actual behavior
Parent collection information not yet present.

### Related work

Reference #1678 for more details.
@elrayle  Want to fill out the appropriate label/project info?

**Comment by elrayle** [comment]
Fixed by PR #2504
