### ISSUE TITLE
Collection index page - consolidate individual modals per row into dynamically populated modals

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#2487]
### Description
Current in the Collections index page, each collection row generates 3 modals in the markup, per row, which are identified by unique #id.  This could easily get out of hand with say 100 rows (300 modals).  The goals is to create 3 skeleton modals in terms of markup, and dynamically populate the necessary row data into the modal when the modal window is initiated.

Part of the collection extensions sprint.

### Rationale

This is an optimization.  It will drastically reduce the amount of markup rendered to the collections index page.

### Expected behavior

Fewer modals will be rendered in the markup, and dynamically populated by the content from the appropriate row interacted with.

### Actual behavior

Multiple modals are being generated per row.  Code duplication.

**Comment by elrayle** [comment]
Fixed by PR #2487
