### ISSUE TITLE
Create a page for editing user roles

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#250]
For starters this should allow you to grant or revoke admin level access for a user.  It should have a link to the user profile page.  It should have a link back to the "Manage Users page" 
It should display the avatar, group membership, counts of admin sets, collections and works created.

**Comment by mjgiarlo** [comment]
See https://github.com/projecthydra-labs/hyku/issues/444

**Comment by elrayle** [comment]
How does this fit with the use of Role Manager as the [default Hydra::User group_service](https://github.com/projecthydra/hydra-head/blob/fcff3b509085eca53ad975b03f8c277041fd91ad/hydra-access-controls/lib/hydra/user.rb)?  Role Manager already has a UI for assigning users to 'roles' (aka groups when used as the group service).

**Comment by elrayle** [comment]
We added Manage Groups to the admin menu with a link to /roles.

**Comment by elrayle** [comment]
@jeremyf How does this fit with the efforts on [hydra-groupy](https://github.com/projecthydra-labs/hydra-groupy)

**Comment by elrayle** [comment]
I'm wondering where we are going with groups and roles.  In the current Hyrax, with Roles Manager being the default group_service, it seems like there is one concept with roles implementing groups.  Then 'group' membership can be tested with cancancan to control abilities.

Are you envisioning groups and roles each as a concept in Hyrax?  If so, what will be the impact of being in a group or having a role?

**Comment by jeremyf** [comment]
Right now the goal is to maintain the public interface of RoleMapper but provide a better configuration point, as well as some name clarity on things (e.g. `User.group_service == RoleMapper` is a rather jarring name change).

The only thing to look at for Hydra::Groupy at this point is the README. Other things are exploratory.

**Comment by no-reply** [comment]
cc: @vantuyls 

Is this in the roadmap?

**Comment by vantuyls** [comment]
in the form of the work that the Permission Analysis Working Group is doing. We still need to have discussions with that WG about what it means to possibly implement PAWG work into Hyrax. 

https://wiki.duraspace.org/display/samvera/Samvera+Permissioning+Analysis+and+Design+Working+Group

**Comment by no-reply** [comment]
Closing this, pending further discussion about PAWG outcomes.
