### ISSUE TITLE
<h4> should not have tags in innerHTML

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2505]
## Descriptive summary

A pattern was established for showing lists of collections/works where the list has an outer tag of `<h4>` around the entire list.  

### Rationale

A UI reviewer made the following comment...

> Typically you would want to keep content within a  #`<h4>` or any headline `<hX>` tag just text, and not embed markup (like the nested `<ul><li>`...).

### Expected behavior

`<h4>` tags to have just text as the innerHTML

### Actual behavior

`<h4>` tags have `<ul><li>`... tags as part of the innerHTML

Search the code for... `<h4 class="media-heading">`

There may be other similar instances of including tags inside header tags.

### Related work

PR #2504 Show parent collections on collection show pages
PR #2599 General collections area UI cleanup (for Issue #2591)

**Comment by adamjarling** [comment]
Looks like the instances referenced (`<h4>`) in linked files have already been refactored.  No longer relevant.
