### ISSUE TITLE
collection_member_controller should not allow adding subcollections

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2531]
### Descriptive summary

There is no check in collection_member_controller whether the set of batch ids are only works.  It should reject collection members and direct toward using the nesting controllers and services.  

### Rationale

There is extensive checking of ancestry through nesting controllers and services.  Those should be used for adding subcollections.

### Expected behavior

The tests that attempt to add subcollections should result in an error regardless of permissions.

### Actual behavior

The tests that attempt to add subcollections pass when permissions allow the user to add the child to the parent.

### Steps to reproduce the behavior

The UI uses the nesting controller and services for subcollections and parent collection assignment.  So there is no way to test this through the UI.  

There are tests in spec/controllers/hyrax/dashboard/collection_members_controller_spec.rb for adding subcollections.  These tests need to be changed to check for failure any time there is an attempt to add a collection as a child.  There should be a flash message about the failure and a note in the log stating that the nesting controllers and services should be used.

### Related work

PR #2522 Controller that adds members to a collection

**Comment by elrayle** [comment]
An alternative would be to update the code used to add members.
* if a work, use the existing code to add the member
* if a collection, use nesting services and controllers to add the member

This is actually probably easier to do than failing if a collection is added.

**Comment by no-reply** [comment]
Closing this as a `wontfix`. since it's a controller ticket that has no external manifestation, it doesn't seem worth directed work.

It's likely that this process will get revisited as part of the Wings/Valkyrie work.
