### ISSUE TITLE
Clarity on what a pageview is and what a download is and how they are generated

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2542]
### Descriptive summary

Needs Clarification. We should probably look at Google analytics' and Piwik's documentation to see what they consider a page view. 

https://wiki.duraspace.org/pages/viewpage.action?pageId=87467336

**Comment by mcritchlow** [comment]
@vantuyls - I have a question related to this ticket as I'm working on trying to setup queries for GA to pull down (and filter) pageview data. What do we want counting as a pageview?

Just the show/public URL, or also the edit/update/etc. routes?

Example:
http://localhost:3000/concern/images/ -- show/public/read-only view
vs
http://localhost:3000/concern/images/edit -- edit view

**Comment by vantuyls** [comment]
chatted about this. we only want to count views on the landing page for a work or fileset. We do not want to count things like edit views.

**Comment by jlhardes** [comment]
Analytics update has these defined but if there isn't an analytics service in place, is there anything that shows for Work stats regarding Page Views and Downloads? Trying views and downloads on Nurax-dev is not changing the Analytics graphs for any Works so far but Nurax-dev also doesn't have any analytics service connected at this point. This might require more testing via a Hyrax instance with a connected analytics service (Google Analytics or Matomo) to know for sure it is resolved. Does that seem right to you, @orangewolf, @sara-g or others involved in that Analytics update work?

**Comment by jlhardes** [comment]
An update to the update: Nurax-dev does have an analytics service connected - it is using Google Analytics. If there is no analytics service connected, there are no analytics graphs available from the Work view and the Analytics reports on the Dashboard are also not available. This issue is still addressed and can stay closed.
