### ISSUE TITLE
Reconcile reinstating `:member_of_collection_id` argument in CE branch

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2545]
### Descriptive summary

PR #2533 adds back `:member_of_collection_id` in addition to `member_of_collections_attributes`.  This allows the CollectionsMembershipActor to process either env parameter.  The same changes need to be completed in collections-sprint branch.
 
### Rationale

Support for both parameters, which carry the same information, allows for backward compatibility.

### Related work

PR #2533 Reinstate `:member_of_collection_id` argument option to Actor Stack
PR #2326 Draft 2.1.0 release notes

**Comment by no-reply** [comment]
I have this in progress.
