### ISSUE TITLE
Namespace field classes

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#2567]
### Descriptive summary

In the 'show' page HTML, fields are laid out like so:

```
<tr>
  <th>Pages</th>
  <td>
    <ul class="tabular">
      <li class="attribute pagination">135</li>
    </ul>
    </td>
  </tr>
```

The `<li>` has a class of the field/attribute name.

In the example above, there is already a `pagination` class (in bootstrap probably) so the display of this field is different to other fields.

It strikes me that this could easily occur with other fields, leading to the need to either change property names or put in unnecessary bespoke css.

Namespacing the field classes, simply by prefacing the class with something (like attribute_name_pagination) would prevent this from happening.

**Comment by no-reply** [comment]
In think form fields are namespaced with `"#{model_class.to_s.downcase}_"`. That might be a good pattern to try to reproduce across the board.

**Comment by mbklein** [comment]
I would argue against making show presenters, or even their styles, model specific. It's fine for forms, but I think display should be less tied down. Bootstrap class namespaces follow the pattern of `genus genus-species`, and I think it's probably our best bet here as well. (e.g., `<li class="attribute attribute-pagination"/>`)
