### ISSUE TITLE
Update rubocop to support 2.5.0

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2568]
### Descriptive summary

The current rubocop resolves to 0.51.0.  This version does not support ruby 2.5.0.  Updating to rubocop 0.52.1 causes 116 offenses.

There was a recent update in the test matrix to support ruby 2.5.0.  If you update locally to ruby 2.5.0, rubocop will not run.  Updating to ruby 2.5.0 is necessary for direct Hyrax development as there are test failures that only occur under ruby 2.5.0.  

Travis does not appear to be running the latest rubocop since rubocop checks pass in Travis.  

### Related work

PR #2469 Update test matrix to ruby 2.5.0

**Comment by no-reply** [comment]
@samvera/hyrax-code-reviewers is there an objection if I update Hyrax to use a forthcoming 1.0.0 version of `bixby`? The goal would be to decouple the style guide from system support/bug fixes in `rubocop`.
