### ISSUE TITLE
admin_set without description cannot display

### ISSUE THREAD

**Issue by bess** [samvera/hyrax#2575]
### Descriptive summary
In Hyrax 1.0.5 (and 1.x stable) an admin_set without a description cannot be displayed. The error is `ActionView::Template::Error: undefined method `each' for nil:NilClass`

### Expected behavior

I expect to see the admin set show view. 

### Actual behavior

I see an application error. 

### Steps to reproduce the behavior

1. Create an admin_set without a description
1. Go to http://YOUR_HYRAX_APP/admin/admin_sets/YOUR_ADMIN_SET_ID

### Related work

This can be fixed by editing `app/views/hyrax/collections/_collection_description.erb` like this:
```ruby
<% presenter.description.try(:each) do |description| %>
   <p class="collection_description"><%= iconify_auto_link(description) %></p>
<% end %>
```

See https://github.com/curationexperts/laevigata/pull/867/files for example fix.

**Comment by no-reply** [comment]
I think this should be reproducible in 2.x, which suggests we need patches in both places.

**Comment by no-reply** [comment]
I can't reproduce in 2.x
