### ISSUE TITLE
Collections - edit form -> sharing tab allows any text as user

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2578]
### Descriptive summary

The Add user search box allows any text as the user.  It should show 'No matches found.' when the text entered does not match a valid user.

### Rationale

Provide feedback to the user when they type in an invalid value.

### Expected behavior

NOTE: Check out how Edit Administrative Set -> Participants handles this.  The code should be the same for the most part.

#### Error 1:
When searching for a user on the Sharing tab that does not exist, a message is displayed stating 'No matches found.'  When the user clicks outside the search box, the text should go back to 'Search for a user...', such that the invalid user cannot be assigned a role.

#### Error 2:
Add button should not process if either the user or role is not selected.  A dialog should tell the user their error...  'Select a user and a role before adding access.'  There should be a similar check for group add button.

#### Error 1:
When searching for a user on the Sharing tab that does not exist, no message is displayed.  And you can add the invalid user to one of the roles.

#### Error 2:
If role is selected and user is blank, adds an entry for the role with a blank user.

#### Error 1:
1. Dashboard -> Collections -> action menu  (beside any collection you own) -> Edit collection -> Sharing tab
1. Type random text in box Search for a user...

Verify a message is displayed below the search box stating 'No matches found.'

#### Error 2: 
1. Dashboard -> Collections -> action menu  (beside any collection you own) -> Edit collection -> Sharing tab
1. Leave user and role blank and click Add

Verify a modal is displayed with message 'Select a user and a role before adding access.'

1. Dashboard -> Collections -> action menu  (beside any collection you own) -> Edit collection -> Sharing tab
1. Leave user blank, select a role, and click Add

Verify a modal is displayed with message 'Select a user and a role before adding access.'

1. Dashboard -> Collections -> action menu  (beside any collection you own) -> Edit collection -> Sharing tab
1. Select an existing user, leave role blank, and click Add

Verify a modal is displayed with message 'Select a user and a role before adding access.'

1. Dashboard -> Collections -> action menu  (beside any collection you own) -> Edit collection -> Sharing tab
1. Leave group and role blank and click Add

Verify a modal is displayed with message 'Select a group and a role before adding access.'

1. Dashboard -> Collections -> action menu  (beside any collection you own) -> Edit collection -> Sharing tab
1. Leave group blank, select a role, and click Add

Verify a modal is displayed with message 'Select a group and a role before adding access.'

### Related work

See widgets for adding participants on Edit Administrative Sets -> Participants tab.

**Comment by adamjarling** [comment]
Hi @jgondron  I was working on some UI cleanup in the Collections Edit > Sharing page and noticed this section has some nested forms (see attached).  I was also noticing the "Add group" form helper doesn't render an actual `<form>` tag to the DOM.  

If you want to chat about it, or figure out an alternate way to handle the updating of the data, let me know...

![edit-collections-sharing-tab](https://user-images.githubusercontent.com/3020266/35705680-c1cc84ca-0768-11e8-96c0-f637852da141.png)

**Comment by elrayle** [comment]
Fixed by PR #2611 

Remaining analysis of Add group form is in Issue #2619.
