### ISSUE TITLE
Dashboard breadcrumbs are not consistent

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2588]
### Descriptive summary

Breadcrumbs for work, collection, and admin set CRUD should be consistent, but they are not.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Expected behavior

Works
* index - Home (link to `/`) / Dashboard (link to `/dashboard`) / Works (no link)
* new - Home (link to `/`) / Dashboard (link to `/dashboard`) / Works (link to /dashboard/my/works) / Create new work (no link)
* edit - Home (link to `/`) / Dashboard (link to `/dashboard`) / Works (link to /dashboard/my/works) /  title (link to work's show page) / Edit (no link)
* show - Home (link to `/`) / Dashboard (link to `/dashboard`) / Works (link to /dashboard/my/works) / title (no link)

For new page, the page title should be...  New <%= work_type_title %>

Collections
* index - Home (link to `/`) / Dashboard (link to `/dashboard`) / Collections (no link)
* new - Home (link to `/`) / Dashboard (link to `/dashboard`) / Collections (link to /dashboard/my/collections) / Create new collection (no link)
* edit - Home (link to `/`) / Dashboard (link to `/dashboard`) / Collections (link to /dashboard/my/collections) /  title (link to collection's show page) / Edit (no link)
* show - Home (link to `/`) / Dashboard (link to `/dashboard`) / Collections (link to /dashboard/my/collections) / title (no link)

For new page, the page title should be...  New <%= collection_type_title %>

Admin Sets
* new - Home (link to `/`) / Dashboard (link to `/dashboard`) / Collections (link to /dashboard/my/collections) / Create new collection (no link)
* edit - Home (link to `/`) / Dashboard (link to `/dashboard`) / Collections (link to /dashboard/my/collections) /  title (link to admin set's show page) / Edit (no link)
* show - Home (link to `/`) / Dashboard (link to `/dashboard`) / Collections (link to /dashboard/my/collections) / title (no link)

For new page, the page title should be...  New <%= collection_type_title %>
where collection type is the AdminSet collection type.  Want to be sure to pick up any title change the site made to the AdminSet collection type.

### Actual behavior

Works
* index - Home / Dashboard / Works (no link)
* show - Dashboard / Your Works / title (no link)
* new - Home / Dashboard / Your Works / Add New Work (no link)
* edit - Home / Dashboard / Your Works / title / Edit (no link)

Collections
* index - Home / Dashboard / Collections (no link)
* show - Dashboard / Your Collections / title (link to public)
* new - Home / Dashboard / New <%= collection_type_title) (no link)
* edit - Dashboard / Your Collections / Browse View (link to public)

Admin Sets
* show - Dashboard / Your Collections / title (no link)
* new - Home / Dashboard / Your Collections / Create new administrative set (no link)
* edit - Home / Dashboard / Your Collections / Edit (no link)

### Steps to reproduce the behavior

Navigate to each page for each object type and verify that the breadcrumbs match expectations.

### Related work

PR #2140 Fix admin_set controller to add proper breadcrumbs
PR #2356 code in breadcrumb on new coll
PR #2587 Did some minor fixes to breadcrumb inconsistencies
Issue https://github.com/curationexperts/nurax/issues/144 Add "Public View" button for collections on edit page

**Comment by gordonleacock** [comment]
@elrayle - When you have "Dashboard" above I'd assuming you mean the text "My Dashboard", correct?

**Comment by chrisdaaz** [comment]
i thought about adding a new issue, but i thought i'd post here first:

When you are viewing one of your admin sets from the dashboard, the "Your Collections" breadcrumb links you to your administrative sets. It is:

My Dashboard / Your Collections (/admin/admin_sets/) / Collection

Instead of:

My Dashboard / Your Collections (/dashboard/my/collections/) / Collection ()

**Comment by elrayle** [comment]
This needs to be reviewed against the most recent design of breadcrumbs to be sure it is consistent with what is specified.  It is certainly close, but needs confirmation.

**Comment by elrayle** [comment]
This issue has been superseded by breadcrumb refactor issues.

Closed: #2818, #2819, #2820, #2829, #2848
Open: #2892 

A review is beginning to compare the refactors to date with the [overall design of the breadcrumb refactor](https://docs.google.com/spreadsheets/d/1Bppr6IRWljrNmEFpVm3vnMlSnuFJs29DES-YDMV_rOs).  Issues will be added for any that do not comply.
