### ISSUE TITLE
Collections admin show page - search form results stay on same page

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#2590]
### Descriptive summary

Currently when on the collections admin show page (see screenshot), entering a value in the search bar and submitting redirects user to the collection public show page.

### Rationale

Searching on a page should not take the user out of their current context.

### Expected behavior

Search form results display on the same page the user is currently searching from.

### Actual behavior

User is redirected to the public collections show page when searching from the admin collection show page.

![collection-admin-show-page](https://user-images.githubusercontent.com/3020266/35647271-99e5feb8-0697-11e8-9ae3-73998248cdf3.png)
![collection-public-show-page](https://user-images.githubusercontent.com/3020266/35647272-99f392bc-0697-11e8-8533-f878f1a0e2d0.png)

**Comment by adamjarling** [comment]
@elrayle This `form_for` is happening on this page:  
`app/views/hyrax/collections/_search_form.html.erb`

I'm not sure which controller processes this, but that's where you'll probably find your answer on where it's redirecting to.

**Comment by elrayle** [comment]
Fixed by PR #2585.
