### ISSUE TITLE
Collections pages - update text sizing in list results and header to create consistency between views

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#2591]
### Descriptive summary

There are inconsistent usages of `<h2><h3><h4><media-body>` etc in the Collection views.  Make a sweep through the UI and clean up inconsistencies.

There are also many unnecessary usage instances of `class="row" class="col-md-12"` Bootstrap classes applied to elements.

Also, some unnecessary usages of Bootstrap Media Object components when no image is within the element's context.  Also some embedded Media Object class markup in `<h3>` headline tags.

### Rationale

Creating nested headlines `<h2><h3><h4>` when used appropriately will provide a smoother UX, along with helping accessibility.  Make the code more concise.  

### Expected behavior
Markup is reduced to what's necessary and applied appropriately.  For example see the below screen shot for text size of Subcollections and Works.

![collection-public-show-page](https://user-images.githubusercontent.com/3020266/35647777-4115b5d8-0699-11e8-940f-d8fae720641b.png)

**Comment by elrayle** [comment]
Fixed by PR #2599 

There probably needs to be another issue that does the same refactor for Dashboard -> Works CRUD.

**Comment by elrayle** [comment]
Fixed by #2599

**Comment by elrayle** [comment]
Issue #2505 refers to usage of `<hX>` with innerHTML and `class="media-heading".
