### ISSUE TITLE
For nested collections, replace create with build in specs when possible

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2593]
### Descriptive summary

Branch: collection-sprint

As part of #2221, the collection factory was enhanced with the ability to create a solr document for nested collections by passing in the values, rather than requiring the full nested indexing process to occur.

In order to speed up the specs, those creating a collection and using `with_nested_reindexing` should be reviewed, and modified by building a collection and using `with_nesting_attributes` if the actual indexing is not an integral part of the spec. 

Examples of the use of `with_nesting_attributes` can be found in `/spec/services/hyrax/collections/nested_collection_query_service_spec.rb`

**Comment by no-reply** [comment]
FactoryBot's `attributes_for` might also be really useful here.

**Comment by no-reply** [comment]
nested indexing behavior is completely changed, and this should be closable.
