### ISSUE TITLE
When I Remove and Re-add an Authorized Proxy Depositor they are not Displayed

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#2597]
### Descriptive Summary 

In Hyrax 2.0.x, when I edit my profile I can add a user as an authorized proxy. If, before saving the profile, I remove the user, then attempt to readd them, the user is not displayed among the authorized proxy users. If I save the profile, they are added as an authorized proxy user anyway.

### Rationale

This issue could lead to significant permissions confusion for a user trying to manage proxy roles. I can accidentally create a state where unexpected permissions are granted. The user experience is also somewhat frustrating, as it appears I cannot readd someone who I had previously dropped.

### Expected behavior

Users added as proxy users with the enter-2 form should display as proxy users while editing the profile, with the option to remove. Users not displayed while editing the profile should not be proxy users upon save.

### Actual behavior

See descriptive summary.

### Steps to reproduce the behavior

1. Register as a user
1. Visit `Dashboard`
1. Click "Your Activity" -> "Profile" -> "Edit Profile"
1. Under "Authorize Proxies" type at least two letters and pick a user to add
1. Click the red *X* next to the user's name under "Current Proxies"
1. Under "Authorize Proxies" type the same two letters and add the same user
1. Observe that the user is not added to "Current Proxies"
1. Click "Save Profile"
1. Click "Edit Profile"
1. Observe that the user is listed under "Current Proxies"

### Related work

 - https://github.com/samvera/hyrax/issues/150
 - https://github.com/samvera/hyrax/issues/151
 - https://github.com/curationexperts/nurax/issues/93

**Comment by rjkati** [comment]
@jlhardes This seems to have been fixed in Hyrax 3.0.1. 

When I add a user as a proxy, they are automatically added to the Current Proxies list. I then click the "Delete Proxy" button for the user and they are removed as a proxy. Then I add the same user as a proxy and they appear in the Current Proxies list. The user stays in the Current Proxies list if I navigate away from the page and return.

**Comment by jlhardes** [comment]
@no-reply this bug appears to be fixed but I want to check in with you as the reporter before closing. Are we good to close this one?

**Comment by jlhardes** [comment]
Closing this issue as fixed.
