### ISSUE TITLE
Tentative Design to address:  Inconsistent labels for Dashboard, Collections, and Works

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2598]
## DO NOT ACT ON THIS ISSUE JUST YET

Discussions are underway to determine exactly how the label conflicts should be resolved.

### Descriptive summary

Dashboard is presented to the user as My Dashboard in breadcrumbs and dashboard page title.  Collections and Works are presented to the user as Your Collections and Your Works in most breadcrumbs and in their respective index pages.  Sometimes in breadcrumbs, they are only referred to as Collections and Works.

### Rationale

Consistency in labels is important to avoid user confusion.

### Expected behavior

I propose that breadcrumbs should always only use non-qualified labels...  Dashboard, Collections, and Works.

The title on the Dashboard would be Your Dashboard to be consistent with the use of Your for tabs on the Collections and Works index pages.

As is currently the case, the tabs on index pages should continue to use Your Collections and Your Works in order to distinguish them from tabs All Collections, Managed Collections, All Works, and Managed Works.

### Actual behavior

Breadcrumbs for Dashboard either say Dashboard or My Dashboard.  Breadcrumbs for Collections either say Collections or Your Collections.  Breadcrumbs for works either say Works or Your Works.

The title on the Dashboard say My Dashboard (for non-admin users) or Dashboard (for admin users).  The title on the index page for Collections is Collections.  And for Works is Works.

Actual and expected behavior is the same for tabs.  They are listed here to include them in the set of information related to labels.  Tabs on index pages use Your Collections and Your Works in order to distinguish them from tabs All Collections, Managed Collections, All Works, and Managed Works.

### Steps to reproduce the behavior

Visit all CRUD pages related to Works and Collections, as well as the Dashboard page.  Confirm titles and breadcrumbs are labeled consistently according to the expectations.

### Related work

Issue #2588 Dashboard breadcrumbs are not consistent
PR #2140 Fix admin_set controller to add proper breadcrumbs
PR #2356 code in breadcrumb on new coll
PR #2587 Did some minor fixes to breadcrumb inconsistencies
Issue #1712 Breadcrumb on show views should not include "Your Works" with an unauthenticated user 
Issue #1156 Batch Works Upload screen lacks breadcrumbs
Issue #911 Inconsistent terms (Discusses some of the broader questions of labels.)
Issue https://github.com/curationexperts/nurax/issues/144 Add "Public View" button for collections on edit page

**Comment by julesies** [comment]
This is another ticket re: breadcrumbs https://github.com/samvera/hyrax/issues/1712

**Comment by elrayle** [comment]
This issue has been superseded by breadcrumb refactor issues.

Closed: #2818, #2819, #2820, #2829, #2848
Open: #2892 

A review is beginning to compare the refactors to date with the [overall design of the breadcrumb refactor](https://docs.google.com/spreadsheets/d/1Bppr6IRWljrNmEFpVm3vnMlSnuFJs29DES-YDMV_rOs).  Issues will be added for any that do not comply.
