### ISSUE TITLE
Collections javascript - consolidate .js files

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#2606]
### Descriptive summary

Currently there are 2 javascript files used interacting with Collections pages.  
- `app/assets/javascripts/hyrax/collections_forms.js`
- `sets/javascripts/hyrax/collections.js`

These could be consolidated into `collections.js`.  And also the file itself could be structured better to group related functionality:
- Group 'click handler' functions
- Group 'add listener' functions
- Possibly add an `init()` method which provides a menu of sorts for the file's contents.

### Related work
Any UI / javascript interactions in the Collections pages

If someone else picks up this story, feel free to ping me (@adamjarling) for clarification.

**Comment by adamjarling** [comment]
@elrayle Just added this.

**Comment by adamjarling** [comment]
Pulled this into work on #2780

**Comment by elrayle** [comment]
Fixed by PR #2787
