### ISSUE TITLE
Collections > Edit > Sharing: Add group form element not displaying

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#2619]
### Descriptive summary

See screenshot for more detail.  On the Collections > Edit > Sharing tab, the row for "Add group" is a `<form>` (similar to "Add user"), but the Add group `<form>` element is not rendering.  It could be due to using an embedded form, perhaps?   Or some type of misconfiguration.  The scope of this issue could be to confirm Add group is not working as expected, and discover the cause while fixing as-is.  

If it's a nesting form causing the functionality not to work, then a new issue should be created to remove the nested forms for Add group and Add user.

### Rationale

Add group does not currently work?  Nested forms are not legal HTML5.

![edit-collection-sharing-nested-forms](https://user-images.githubusercontent.com/3020266/35824273-fa506ac0-0a77-11e8-9fec-9a29756d0f4e.png)

@elrayle Issue added.  Feel free to add/label as you see fit.

**Comment by adamjarling** [comment]
@elrayle When this ticket was created, I believe the functionality didn't work.  Now it appears the functionality works (for users).   So two questions:
- How does one add Groups to test this?
- Is this currently not working for you?  

Or is the issue just with UI layout?

**Comment by davidschober** [comment]
@adamjarling it doesn't seem as if the functionality is working for groups. the "Add User" functionality seems to be working. Adding a group drops the user off on the description tab with no update. The functionality seems to work as expected in an admin set.

**Comment by adamjarling** [comment]
FYI, Nurax doesn't have the latest updates from Hyrax `master` which fixes the "Users" getting added.

**Comment by adamjarling** [comment]
So I've tested a few things, and the issue boils down to:
- Both forms (Add Groups and Add Users) use "simple forms" to render the form.  
- If you inspect the rendered markup, the first `<form>` expected to render via simple form, doesn't have an opening or closing `<form>` tag.  This is most likely why it's not submitting.
- The second form does have the proper opening and closing `<form>` tags.  Why it's submitting successfully and working as expected.
- If I flip flop the forms, the first one never renders properly, and the second one always renders properly, and submits successfully.
