### ISSUE TITLE
For each work type we should have the ability to set the default AdminSet

### ISSUE THREAD

**Issue by carolyncole** [samvera/hyrax#262]
As an administrative User, I would like the ability to set the default AdminSet for each work type so I can limit users that have deposit ability for a work type and set the workflow for each work type.

**Comment by jcoyne** [comment]
@cam156 sounds good. Do you have a concrete use case at PSU for this?  I'm curious to hear it.

**Comment by cam156** [comment]
@jcoyne this came up at the mediated deposit standup and I was the person to write the ticket. @vantuyls or @acollier do you have a specific use case?

**Comment by mjgiarlo** [comment]
@cam156 I think you mean @scholarworks

**Comment by no-reply** [comment]
i think hanging more behavior on work types (and therefore Ruby model classes) is not well advised. these are heavily overloaded already.

other ways of auto-sorting objects into admin sets seem good, but i think in general the community is moving toward front-loading admin set selection.
