### ISSUE TITLE
Convert Hyrax::Analytics into a parent class for analytics platforms

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2624]
### Descriptive Summary
In order to allow multiple analytics systems to be used, let's turn Hyrax::Analytics into a parent class for each child analytics platform to implement. This will help abstract the logic for a specific platform and let us generally use them elsewhere in Hyrax.
Most methods should `raise NotImplementedError` unless they are common to any child platform.

We can start by refactoring the existing google analytics code which will also help us remove google specific code from the rest of hyrax.

**Comment by mcritchlow** [comment]
So are you thinking the deliverable from this ticket is an agreed upon API we want each subclass/adapter to implement? Or the actual initial implementation itself of the parent class and the GA child? Or both? :)

**Comment by mcritchlow** [comment]
Should we setup ticket(s) for giving [Hyrax::Statistic](https://github.com/samvera/hyrax/blob/master/app/models/hyrax/statistic.rb) the same treatment? Perhaps with this ticket as a dependency? It and its subclasses definitely are setup assuming GA, including the existing Hyrax::Analytics GA profile.

**Comment by nestorw** [comment]
Both. 😄 I think #2625 and #2626 are dependent on this ticket and the deliverable for this one is the agreed upon API. I also think we should let the GA child drive the parent's API. 

The GA specific work done in Hyrax::Statistic should probably be moved to the GA Analytics implementation

**Comment by mcritchlow** [comment]
As discussed on the call, I'll take an initial pass at documenting an interface that the Google Analytics and Matomo subclasses can implement. I think there's going to need to be a fair amount of discussion around this since the current "contract" with Analytics (and Statistics by extension) is basically to authenticate, call `#statistics` and call `#to_flot`. But given that we're moving away from both jQuery flot and we're dropping Legato for GA, we'll need to decide where to place the additional burden of query construction and where that should live in the API.

**Comment by mcritchlow** [comment]
@conorom @sethaj @nestorw @lfarrell - While I didn't as far as I'd hoped with this yesterday, I've gotten a start on some API thoughts for Hyrax::Analytics that we can probably start kicking around and I can talk about on our call today https://gist.github.com/mcritchlow/63e5b203c2221a620adfebc8e74420a9

Part of the motivation, which perhaps needs discussion in its own right, is to leave the Hyrax::Statistic class more or less as-is.

**Comment by mcritchlow** [comment]
I would have marked this as done (as a starting point at least), but I think we had a good discussion about possibly collapsing this API into fewer calls.

@nestorw @conorom - thoughts? You all have been more heads down in the individual API's of GA and Matomo, so might have a better sense of what we might collapse for:

* pageviews
* downloads
* unique visitors
* returning visitors

**Comment by mcritchlow** [comment]
Question above still stands, and I'd like to further complicate it by asking if we can/should consider batch querying:
- https://github.com/google/google-api-ruby-client#batches

Not sure if Matomo has an equivalent feature? 

@conorom - I know you're off now, but did you have any thoughts about collapsing queries on the GA side? I know you dug into this more than the rest of us, and I'm circling around to it now

**Comment by mcritchlow** [comment]
As one proposal I think collapsing unique and returning visitor queries certainly seems do-able on the GA side.

**Comment by conorom** [comment]
@mcritchlow Sorry for missing the question. If "collapsing" means adding multiple metrics on one dimension (which is always date for us), then this is already done in the preliminary code I've written (remembers "users" means unique visitors):
https://github.com/samvera/hyrax/blob/ec18e6f3f34d0fdf0a9a7a20d8c230dabe8f9fa1/app/services/hyrax/analytics/google_analytics.rb#L17

Now, being clever about batching requests would be awesome, especially if it meant avoiding hitting API request limits (which is a problem we encountered in Fulcrum as bots hit the site). You can see I'm already using the batch endpoint:
https://github.com/samvera/hyrax/blob/ec18e6f3f34d0fdf0a9a7a20d8c230dabe8f9fa1/app/services/hyrax/analytics/google_analytics.rb#L50
...and that `report_requests` is actually an array:
https://github.com/samvera/hyrax/blob/ec18e6f3f34d0fdf0a9a7a20d8c230dabe8f9fa1/app/services/hyrax/analytics/google_analytics.rb#L58

If Matomo can do this as well (edit: OK looking in Slack now it seems it can't) and if the DB-writing code is simple enough to iterate over then batching requests for the dates that are not yet cached *might* be the way to go, but you'd need to start thinking about batching everything start to finish.

One thing I can't remember. Will several triggers still remain, i.e. the Work/FileSets `/stats` pages right now will check the analytics cache for an item and call the API if necessary. Then there is the (optional) rake task to update everything. Is the plan to only use the scheduled rake task in the new analytics?

**Comment by conorom** [comment]
I'm pretty sure analyticsreporting v4 API only supports `batchGet` requests:
https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports

**Comment by mcritchlow** [comment]
@conorom - that's awesome information, thank you! I don't think a decision has been made on the triggers you mention.

Personally I'd advocate for dropping that and leaning on a nightly rake task to keep things up to date. Having the app do live queries as it's setup to do now just doesn't seem sustainable to me, and the requirement to have a nightly rake task that's invoked via systemd or cron doesn't seem unreasonable at all. But that's probably something that should get vetted beyond my personal opinion :) What do you think?

**Comment by conorom** [comment]
FYI, each "report request" counts against the daily quota, even if they are sent together in a batch:
https://developers.google.com/analytics/devguides/reporting/core/v4/limits-quotas
Bummer

**Comment by mcritchlow** [comment]
well that's unfortunate.. we're definitely going to have to be careful here

**Comment by mcritchlow** [comment]
In reading about this more and watching the video linked to in the page from @conorom , I think we need to strongly consider moving away from the filter-style requests that have been historically used for individual pages/records. I think for large sites we're absolutely going to run up against the 50k request limit per day.

The [alternative they recommend in the video](https://youtu.be/1UfER93ALxo?t=1346) is to use the `ga:pagePath` dimension and do something like:
```
?ids=ga:1234
&metrics=ga:visits
&dimensions=ga:pagePath
&start-date=2018-03-13
&end-date=2018-03-14
&max-results=10000
````

or for something like visits per day,
```
?ids=ga:1234
&metrics=ga:visits
&dimensions=ga:date
&start-date=2018-03-10
&end-date=2018-03-14
&max-results=10000
````

Presumably for pages, in the first example, there's a way to then ask for the next 10k in another request. Just haven't tracked that down yet.

**Comment by conorom** [comment]
API v3 calls what you're looking for `start-index`, which v3-based Legato wraps as `offset`:
https://developers.google.com/analytics/devguides/reporting/core/v3/reference#startIndex
https://github.com/tpitale/legato

NB that v4 changes these from v3's `max-results` and `start-index` to `pageToken` and `pageSize`, with a handy `nextPageToken` sent in the response for use in a subsequent response:
https://developers.google.com/analytics/devguides/reporting/core/v4/migration

@sethaj had to do battle with this quota stuff in our project, once he noticed that it was being maxed out by page requests from crawlers (possibly Google's own bot?). The starting point for our current analytics was (loosely?) inspired by Sufia's analytics code (so essentially what Hyrax still has now), that's why we're using Legato.

You can see where Seth pulls out the filter and starts using offset in the history of these files (so perhaps he also watched that video!). This code may not be worth poring over as Legato (and hence API v3) is involved:
https://github.com/mlibrary/heliotrope/blob/b480e4068acfdb6e7e0dca4e547ac33802371eb6/app/models/pageview.rb
https://github.com/mlibrary/heliotrope/blob/b480e4068acfdb6e7e0dca4e547ac33802371eb6/lib/tasks/ga_cache.rake

Also note we only use that rake task to pull in analytics, it's not done from loading any `/stats` pages.

**Comment by mcritchlow** [comment]
Thanks again @conorom 

I think what @cam156 did for Scholarsphere it probably a good model for the new implementation. It is using Legato of course, but I think the approach is solid.  https://github.com/psu-stewardship/scholarsphere/commit/4672181d0279cfefcbc8e471d02bd7a65410e6bb

**Comment by mcritchlow** [comment]
@conorom - could I bother you to let me know about this bit on the downloads query:

**Comment by conorom** [comment]
Actually, the old Legato query for downloads used events (totalEvents), too, but the way that was switched out from the default (pageview) was very clunky looking, by using this model:
https://github.com/samvera/hyrax/blob/master/app/models/hyrax/download.rb
...here in the overridden `ga_statistics` method: https://github.com/samvera/hyrax/blob/1e504c200fd9c39120f514ac33cd42cd843de9fa/app/models/file_download_stat.rb#L14

So I was just trying to recreate what's there already with Legato, up until the point I added `uniqueEvents`, which is a new requirement that can be pulled down at the same time.
