### ISSUE TITLE
Replace Legato with Google's ruby API?

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2629]
Should we replace Legato with Google's Ruby API?

Legato imposes a class structure that will likely get in the way of the proposed plugin system.
Google's gem is fairly similar to Matomo's and should simplify building a shared way of accessing them.

One possible downside is that Google's gem is marked as alpha. But with their tendency to remove and change services, that may be a risk no matter what.

**Comment by jcoyne** [comment]
No objections here.

**Comment by conorom** [comment]
Right now I'm assuming we're going to ditch the `.p12` key file (which is deprecated by Google and can't be used directly by their gems) in favor of the JSON key file. This means existing GA+Hyrax users will have to get the JSON key file and make it available to the app when they switch to the new analytics stuff:
```
Go to https://console.cloud.google.com/iam-admin/serviceaccounts/
Select your project in the dialog that appears
Click the "3 dot" menu icon on the right-hand side of the row for the service account you currently use
Select 'Create key'
Choose JSON format
Move the downloaded file alongside the p12 file that is currently available to your Hyrax-based app
Replace the p12 path with the JSON file path in `config/analytics.yml`
Done!
```

**Comment by mjgiarlo** [comment]
Indeed: https://github.com/samvera/hyrax/issues/60

**Comment by mcritchlow** [comment]
Sounds like the original question, per the title of this ticket, has an answer (we're transitioning to google's ruby api). Seems like #60 is for the work in making this happen. Do we still need this one open?
