### ISSUE TITLE
The choice of Administrative Set should be more prominent to the user

### ISSUE THREAD

**Issue by cam156** [samvera/hyrax#263]
### Descriptive summary

The current location of the Administrative Set does not make the choice obvious to the user.  In reality we may also not want the user to have the ability to choose.  We want the user to not have the ability to deposit in the default set, and or the ability to default the admin set based on the user's permissions.

**Comment by jcoyne** [comment]
@cam156 can you give a concrete example here? I think it would help me understand better.

**Comment by cam156** [comment]
@vantuyls @acollier Did you have concrete examples for forcing a user towards one admin set or another?

Just speaking from using the system it was non obvious to me that the AdminSet choice was on the relationship tab.  If I was not testing AdminSet I would have never changed from the default.  Given that users choose the path of least resistance, I doubt in real life the way things are set up that a user would choose an Admin Set.  

It could just be a difference of user.  In my mind's eye a user is any student, faculty, or staff.  If this is only meant to work for librarians I could see them making the connection.

**Comment by mjgiarlo** [comment]
:arrow_up: @scholarworks

**Comment by mjgiarlo** [comment]
This is important work, and I am moving this to the backlog until 1) we get one or more Hyrax releases out and 2) we have some designers work on this in the context of the overall UI. Pinging @projecthydra-labs/hyrax-ui-ux-advisors. Perhaps we can start thinking about a UI/UX refresh now for Hyrax 2.0. I don't see that coming out 'til 2018 which gives us plenty of time to work on it.

**Comment by no-reply** [comment]
I think the location and process for admin set selection has been completely redesigned since this ticket.

Closing for that reason.
