### ISSUE TITLE
Fedora detection fails when sever root is 404

### ISSUE THREAD

**Issue by sephirothkod** [samvera/hyrax#2631]
This applies to Hyrax 2.x and more specifically to the fcrepo endpoint code. 

anyone using tomcat or jetty without a root directory setup will encounter this and be given no useful error message. I assumed that it was an error with the authentication and spent way to long attempting to debug that.

### Expected behavior

We should be seeing that fedora is up if it is up...

### Actual behavior

If the root of the server (regardless of fedoras status) is empty (404) we fail to detect that fedora is up

### Steps to reproduce the behavior

1. Setup a servlet container, either tomcat or jetty (I was using jetty), and make sure that there is no ROOT folder in the webapps directory.
1. Drop a fedora war file in the webapps directory and makes sure it is running at its context path.
1. Set your Hyrax instance to point to that fedora instance
1. Watch as everything crashes and burns. ie. check "system status" on the dashboard or ping the fedora instance by running the ping method off of any fcrepo_endpoint.

**Comment by no-reply** [comment]
@dlpierce should we close this as wont-fix?

**Comment by orangewolf** [comment]
this seems pretty clearly a wont-fix here in 2024
