### ISSUE TITLE
Update to Jasmine 3.0

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2634]
### Descriptive summary

PR #2628 attempted to do an automatic update to Jasmine 3.0.  Multiple jasmine tests fail at 3.0 and need to be resolved before Jasmine can be updated.

### Expected behavior

All Jasmine tests pass when using Jasmine 3.0

### Actual behavior

At least 5 Jasmine tests are failing using Jasmine 3.0

### Steps to reproduce the behavior

Update gemspec to use Jasmine ~>3.0
Run Jasmine tests
Verify none fail

### Related work

PR #2628 Update to Jasmine 3.0
PR #2633 Temporarily pin Jasmine to < 2.99

**Comment by RudyOnRails** [comment]
Just dropping some supporting info here before forgotten. Jasmine 3 includes breaking changes: https://github.com/jasmine/jasmine/blob/master/release_notes/3.0.md
