### ISSUE TITLE
Remediate Hyrax simple-form error on version 3.5.1

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2665]
### Descriptive summary
Simple-form version 3.5.1 causes build failure.

PR #2663 locks Hyrax's simple-form and parser versions.

**Comment by laritakr** [comment]
see issue https://github.com/plataformatec/simple_form/issues/1549

**Comment by cjcolvar** [comment]
See also https://github.com/samvera/hydra-editor/issues/139

**Comment by no-reply** [comment]
See also #2296

**Comment by elrayle** [comment]
@no-reply @vantuyls As this has a viable temporary pin, I would recommend targeting a fix for this in 2.1.1.

**Comment by no-reply** [comment]
Depending on what happens with `hydra-editor` 3.3.3 and 4.0.0, fixing this may involve a breaking API change in `hydra-editor`. For that reason, it might not be possible to release a fix in 2.1.1.

I'd like to track it with the 2.1.0 tickets, in hope that a solution will present itself in the next few days; and we don't leave Hyrax 2.1 pinned to a version of `simple-form` that won't receive bug fixes.

@jrgriffiniii I believe the fix necessary is a release of `hydra-editor` at 3.3.3, which is already prepared on (https://github.com/samvera/hydra-editor/tree/3-3-stable), followed by a release of 4.0.0, which has an existing RC that has been tested with Hyrax.
