### ISSUE TITLE
Workflow schema validation errors should include more information

### ISSUE THREAD

**Issue by carolyncole** [samvera/hyrax#267]
### Descriptive summary

I got the following information from loading workflows in the spec internal in hyrax:

```
{:workflows=>{0=>{:actions=>{2=>{:notifications=>{0=>{:name=>["must be an initialized Ruby constant"]}}}}}}}
```

There are two workflows in the system and I obviously tweaked one of them, but there is no indication of which workflow file failed, what the workflow name, action name, notification name, or the value of the item that does not match the validation.

I'm sure I tweaked the workflow by accident, but which one and exactly where is not easy to discern from the error that was produced.

**Comment by cam156** [comment]
So as it turned out the class name changed for the notification, so I did not change anything, but the class that used to exists no longer exists, so my workflow was now invalid.  I figured that out by diffing the template in the code with my template.  If I did not have the ability to run a diff I would have NEVER figured this out from the error above. Ok maybe never but it would have taken me hours....

**Comment by jcoyne** [comment]
:+1: I have had the same problem

**Comment by no-reply** [comment]
This still seems high value.

The workflow schema validation output is customizable with https://dry-rb.org/gems/dry-validation/1.0/messages/

They are actually currently pretty informative:

`#<Dry::Validation::MessageSet messages=[#<Dry::Schema::Message text="name must be Class" path=[:workflows, 0, :actions, 1, :notifications, 0, :name] predicate=:type? input="FooBar">] options={:source=>[#<Dry::Schema::Message text="must be Class" path=[:workflows, 0, :actions, 1, :notifications, 0, :name] predicate=:type? input="FooBar">], :full=>true}>`

but the output is formatted just like that. Much better would be to loop through the messages and output a nicely descriptive error describing the path to the errant key, and the outputting the message text (in this case "name must be a Class") with the actual value.

for example:

"Error on workflow entry [:workflows, 0, :actions, 1, :notifications, 0, :name]	 name must be Class	 Got: FooBar"
