### ISSUE TITLE
Collection type creation loses settings if you add a participant before a save.

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2672]
### Descriptive summary
When creating a Collection Type, if you select/deselect settings, then don't hit save, then click to the participants tab, then add a participant, when you return to the "settings" tab, your settings have returned to default. I can see this leading to some mistakes and having to delete collection types since they can't be edited after created. So I think this is important to address somehow. 

### Expected behavior
Selections are retained as you move through tabs or there is a warning given. 

### Steps to reproduce the behavior

1. Create a collection type
2. Add title, hit save
3. Go to settings: Change the Settings, don't click save
4. Go to participants: add a partcipant
5. Go to Settings: See defaults back. 

### Related Work

Reported in Nurax issue https://github.com/curationexperts/nurax/issues/178

**Comment by vantuyls** [comment]
could we use the approach here?: https://github.com/samvera/hyrax/pull/2799

**Comment by dlpierce** [comment]
I'm near finished implementing the approach mentioned above, while also addressing #2907, which depends on fixing #2273.
