### ISSUE TITLE
Deactivate Embargoes for Selected Fails

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2676]
copied from Nurax: https://github.com/curationexperts/nurax/issues/180
Descriptive summary
In the [Manage Embargoes page](https://nurax.curationexperts.com/embargoes, from the Expired Active Embargoes tab, users have the option to select multiple works and filesets and deactivate their embargoes in bulk.

Actual behavior
Select a few embargoes to deactivate:
![image](https://user-images.githubusercontent.com/4356335/36491236-4339e964-16f8-11e8-97a6-bf0ce5910626.png)

You get SWW

![image](https://user-images.githubusercontent.com/4356335/36491214-343bcac2-16f8-11e8-9816-1b26e21b3ece.png)

**Comment by elrayle** [comment]
This only happens when you try to deactivate a File embargo.  It does not happen for works.

Log errors...
```
NoMethodError (undefined method `copy_visibility_to_files' for #<FileSet:0x0055df0978a9e0>):
[2018-03-01T15:06:10.477403 #3223] FATAL -- : activemodel (5.1.5) lib/active_model/attribute_methods.rb:432:in `method_missing'
/opt/nurax/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-eb16822e9e4e/app/controllers/concerns/hyrax/embargoes_controller_behavior.rb:28:in `block in update'
/opt/nurax/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-eb16822e9e4e/app/controllers/concerns/hyrax/embargoes_controller_behavior.rb:26:in `each'
/opt/nurax/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-eb16822e9e4e/app/controllers/concerns/hyrax/embargoes_controller_behavior.rb:26:in `update'
```

**Comment by elrayle** [comment]
I just tried deactivating a single File and used the button beside the file to deactivate it and it worked fine.  It only seems to fail when you use the batch deactivate button at the top AND you have at least one file included in the selected items to deactivate.

**Comment by elrayle** [comment]
This is the exception that is thrown when the error occurs...
![image](https://user-images.githubusercontent.com/6855473/36910260-365832a6-1e0e-11e8-90cc-c562a29789d4.png)
