### ISSUE TITLE
Private objects shown to Public Users

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2677]
Moved from nurax: https://github.com/curationexperts/nurax/issues/172

Descriptive summary
A non-authenticated user, I can see objects that are private. This includes Files, Child Works, Collections. I can not get to the actual files, but I can see representations of files and works (with generic File title) and I can see full titles of Private Collections on the Work View.

In addition the Admin Set Title appears on the work view.

Here is a good example including all issues listed:
https://nurax.curationexperts.com/concern/images/r494vk17h?locale=en

Here is a place Private Collections are NOT shown to unauthenticated users in nesting context. And so it's working as expected.

https://nurax.curationexperts.com/collections/9019s2486?locale=en

Desired behavior is:
Private collections are never shown to unauthenticated user/or users with read
Admin sets are never shown on work page
Private files are never shown to unauthenticated user/or users without read

cc @vantuyls for any clarification

**Comment by laritakr** [comment]
The issue of displaying private files on a work is a larger issue, and preferred behavior is still to be determined. This will be moved to another issue. Reference discussion here: https://groups.google.com/forum/#!topic/samvera-tech/eCQdh9qy1io

**Comment by julesies** [comment]
sorry just catching up. I think @vantuyls  made the call to no show private files on a work, so pinging him for clarification.

**Comment by laritakr** [comment]
ongoing discussion is here: https://groups.google.com/forum/#!topic/samvera-tech/eCQdh9qy1io

**Comment by vantuyls** [comment]
Okay, i've made a call over on that google groups thread. 

Based on this and previous conversations, it sounds (to me) like the most common need is for hiding the files if the user does not have permission to access them (ie. they will not appear in the file list).
