### ISSUE TITLE
Add Cloud Files Doesn't work

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2678]
Moved from nurax: 
https://github.com/curationexperts/nurax/issues/169

Descriptive summary
When going to Add Cloud Files, you just get a grey screen
I'm not totally clear if this is a set up issue or a Hyrax issue. 

![image](https://user-images.githubusercontent.com/4356335/36491697-65079fa4-16f9-11e8-829c-57b154fce3d0.png)

cc @jrgriffiniii who can help with bugs on BE

**Comment by jenlindner** [comment]
@julesies The error in the logs was 'Dropbox requires a client_id', which is a config issue. I edited the config and it seems to be working again, can you confirm? Thanks.

**Comment by julesies** [comment]
yes thanks @jenlindner now we can finish testing BE clients. TY!
