### ISSUE TITLE
A/V player controls not working properly

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2681]
Lots of discussion here: https://github.com/curationexperts/nurax/issues/153

Descriptive summary
For both the work view and file set pages, video files and audio files do not download properly. This was tested on Chrome and Safari on Mac. 

**Update: Safari playback doesn't seem to be working at all

On the work view page, the full screen and download buttons do not work at all.
here is an example: https://nurax.curationexperts.com/concern/images/r494vk17h?locale=en

On the fileset page, fullscreen and download buttons work, but downloads the wrong file. See audio download example.

![image](https://user-images.githubusercontent.com/4356335/36492178-86a6bbf8-16fa-11e8-8eb3-d832b7fd0e31.png)

On the work view page, under Items: if one chooses "Select an action: download" on a video file, it downloads the proper file.
![image](https://user-images.githubusercontent.com/4356335/36492201-912fe11c-16fa-11e8-9fc2-5066c26fc0be.png)

Navigate to a video or audio work
try to use the player buttons
click the download button
navigate to fileset page
try to use the player buttons
click the download button

**Comment by cjcolvar** [comment]
@julesies @elrayle Can we close this issue given that #2744 was closed?

**Comment by julesies** [comment]
closing, confirmed fixed. new Safari video issue was created. https://github.com/samvera/hyrax/issues/2815
