### ISSUE TITLE
Dashboard Collection Show UI needs fine-tuning for unusual situations

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2685]
### Descriptive summary

When you use long titles or multiple titles, the collection show page looks really ugly. A UI person needs to decide what to do in these situations. 

- With two titles, the titles wrap oddly.
- Should collection titles in the parent and subcollection list be truncated?
- Should collection titles in the modals be truncated?
- Should the index list show both titles?

![screen shot 2018-02-21 at 2 31 54 pm](https://user-images.githubusercontent.com/17851674/36501772-ff167d24-1715-11e8-9d16-d4d38290da3e.png)

![screen shot 2018-02-21 at 2 37 20 pm](https://user-images.githubusercontent.com/17851674/36501766-fabde546-1715-11e8-9333-19a37f02445f.png)

## after adding a second title
![screen shot 2018-02-21 at 2 39 54 pm](https://user-images.githubusercontent.com/17851674/36501668-bb431c88-1715-11e8-9d56-137f415c6413.png)

## two titles on the index list
![screen shot 2018-02-21 at 2 54 41 pm](https://user-images.githubusercontent.com/17851674/36502217-3dcefda6-1717-11e8-954f-f72919b87eee.png)

**Comment by laritakr** [comment]
The public show page is fairly good for this same situation. 
![screen shot 2018-02-21 at 2 48 56 pm](https://user-images.githubusercontent.com/17851674/36501900-6c0a5ef0-1716-11e8-96d9-2e0cb191ca8f.png)

**Comment by adamjarling** [comment]
@laritakr Yea, I see what you mean here.   For the modal select dropdown, that may be the best solution, to truncate the width maybe?  Unless that would be a deal-breaker for identifying the right collection.

For the Remove button layouts, it's almost as if they need to be displayed in more of a grid or tabular way, instead of a straight list.  To account for proper button display, and flow of the rows. 

The 'after adding a second title' screen shot' is odd how the second title comes in at the end.  Seems both titles should stack, and keep the button placement consistently placed to the right.

If you want, you can assign this ticket to me and I could play with a few things.

**Comment by laritakr** [comment]
@adamjarling I'm working on the remove buttons, so I'll our work might conflict. Probably best if this waits a bit and I tag you when I finish.

**Comment by laritakr** [comment]
Blocked by https://github.com/samvera/hyrax/issues/2295

**Comment by laritakr** [comment]
Also, _show_parent_collection_row.html.erb and _subcollection_list.html.erb partials both have styling which should be moved to CSS.
   
```
<li style="margin: 5px 0">
  <%# TODO: move styling into CSS %>
```

**Comment by laritakr** [comment]
@adamjarling My work on #2295 is mostly complete, so this is no longer blocked. You can work on it whenever you have time.

**Comment by adamjarling** [comment]
@laritakr Just made some updates to the bulk of what I believe was left in this ticket's comments.  Here are a few screenshots of the updates:

![collections-show-ui-cleanup-modal](https://user-images.githubusercontent.com/3020266/37056752-f28871f4-214a-11e8-9eb8-715bb95a4125.png)
![collections-show-ui-cleanup-modal2](https://user-images.githubusercontent.com/3020266/37056753-f29b166a-214a-11e8-8eb0-268bf8e9923b.png)
![collections-show-ui-cleanup](https://user-images.githubusercontent.com/3020266/37056754-f2af8514-214a-11e8-9f9f-ef67f6a6a199.png)

**Comment by adamjarling** [comment]
For the super long Collection title in the `<select> <option>`, there's no real way to add via CSS the ellipsis.  I capped the width of the `<select>` itself so it doesn't bleed outside the modal, but if we do want to still truncate the inside text, we'll have to find an alt solution.
