### ISSUE TITLE
Analytics -- Modeling

### ISSUE THREAD

**Issue by mcritchlow** [samvera/hyrax#2689]
### Descriptive summary
To Do:

- [x] Consider existing Analytics modeling/structure and compare against needs of the new project. See: https://gist.github.com/mcritchlow/61068fbfce6833129426ba1f79c74683
- [x] Discuss options with the entire group, form basic consensus
- [x] Discuss options with folks in the community who have more experience with larger data migrations and ask for input

Future tickets will break down the actual implementation work. The deliverable from this ticket is an agreed upon plan for moving forward.

### Related work
[Hyrax::Statistic API documentation](https://gist.github.com/mcritchlow/63e5b203c2221a620adfebc8e74420a9#current-api-expectations)

#2624

**Comment by mcritchlow** [comment]
So I put my head down into this for a today and here are some other thoughts on this after going back to the current mockups (thanks @nestorw ). I'd definitely like some feedback/thoughts on this, because it's definitely possible I'm thinking about this wrong or there's a much easier way forward.

1. We actually need to track `visitors` in two contexts, by `Work type` to satisfy #2557 for the Work Analytics Activity Page and `site-wide` to satisfy #2541 for the Admin Dashboard
2. `unique_visitors` is the only visitor metric we're interested in tracking by `Work type` (not `returning_visitors` or `total`)
3. `unique_visitors`, `returning_visitors` and `total` are what we want for the Admin dashboard
4. The current `Hyrax::Statistic` class and its subclasses essentially assume there's a single data value per `Stat` class: `views`, `downloads` referenced as a `cache_column` as a class attribute but eventually used in methods as `object_method` and sent in `to_flot` which is expecting an array of `[<Date>,<StatValue>]`. Basically all the methods in the superclass for managing analytics (cached and remote) assume this single stat value data structure.

So I'm wondering if it makes sense to continue with this approach. It's easier in a sense, but it seems like it ends up making for a _lot_ of DB tables and queries as a result.. The mockups look like the query interface would benefit from having, say:
- a single `WorkStat` class that has everything we want to track for works, which is now `views`, `unique_visitors` (plus a `date`, `work_id`)
- a `FileStat` class that would hold `downloads` and `views` (plus a `date` and `file_id`)
- and a `SiteStat` class that holds site-wide stats like `unique_visitors` and `returning_visitors`.

**Comment by mcritchlow** [comment]
Per the discussion on the tech call and slack, it seems we're agreed on the approach of starting clean with new table(s).  :tada: 

@jcoyne floated the idea of a single table, such as (per @mjgiarlo ):

```
ActiveRecord::Schema.define(version: 20_171_026_154_256) do
  create_table 'resource_stats', id: :serial, force: :cascade do |t|
    t.datetime 'date'
    t.integer 'hits'
    t.string 'hit_type'
    t.string 'resource_id'
    t.string 'resource_type'
    t.datetime 'created_at', null: false
    t.datetime 'updated_at', null: false
    t.integer 'user_id'
    # one or more indexes that make sense
  end
end
```

I do think this sort of structure would do the trick for both Work and FileSet stats we need to track for the current effort, and it would probably scale into collection wide metrics as well for later Analytics phases. I don't think it'll work for site-wide metrics we need track, I think that might be pushing it and we might still need a dedicated table for those.

Before locking this down though, I'd be interested in any concerns from folks who've been working on the new front end reporting interface. @sethaj @lfarrell , any concerns on your end?

-- /cc @conorom @nestorw @vantuyls

**Comment by mcritchlow** [comment]
gist from @nestorw https://gist.github.com/nestorw/cf1573d82bdf817c71266451b06a291e#file-analytics_tables-md

**Comment by sethaj** [comment]
I was wondering if we could generalize this table even more to include different kinds of events, and not just analytics data. So maybe something like this:

https://gist.github.com/sethaj/5504632ee0dc985d87b939de6f5bdb1f

Maybe that's one step too far though...

**Comment by mcritchlow** [comment]
Yeah that's an interesting point. We need to track those statistics _somewhere_. I suppose a possible negative is it might put a little more burden on the query interface to be smart enough to know what to pull out for the given context/combo of `resource_type` + `event_type`, etc.  

The alternative to not including those stats in this table is we need a separate table just for them which would indeed look very similar to that table minus a few fields. Plus the site-wide stats.

**Comment by nestorw** [comment]
My main concern with the single table plan above is that it requires one row per metric per resource_type per day.
If we gear it towards one row per resource type with columns for each metric, it will drastically reduce the number of rows per day and make queries much simpler.
We could even add columns for status changes for each work_type.

### event_type based rows
pros:
- no need for migration to add new event_types
- what am I missing?
cons:
- multiplies the number of rows for each event_type
- more complex joins required, especially for nested works, collections, etc

### resource_type based rows
pros: 
- fewer rows per day
- simpler queries, all data for a resource_type is in the row
- easier aggregation for collections, nested_works, etc
- status changes and other non-GA metrics can be added as a column
cons:
- rows will be more sparse since not all columns will apply to each resource_type
- maybe I'm missing something?

**Comment by mcritchlow** [comment]
@nestorw - overall I'm in agreement with you. I guess I can think of one pro/con (depending on how you frame it) for the different approaches. With the event_type structure, it's an easy to query to say "From the start date in the analytics config file, what dates are we missing statistics for"? Basically making up for potential remote failures/etc. That said, I don't see anything keeping us from being able to pretty easily answer that question with the resource_type data structure.

If there was interest in keeping the same Hyrax::Statistic codebase in use for our work, then I suppose that might be another potential negative to consider for the resource_type structure. But, we're not, so I don't see that on the table as a concern.

I'm in favor of the idea of a single database row, for a given date, having all the statistics needed for a given resource type.

**Comment by mcritchlow** [comment]
Ok, so per our group's conversation this morning, here's what I _believe_ to be what we've agreed upon:

```
ActiveRecord::Schema.define(version: 20_171_026_154_256) do
  create_table 'resource_stats', id: :serial, force: :cascade do |t|
    t.datetime 'date'
    t.integer 'downloads'
    t.integer 'pageviews'
    t.integer 'unique_visitors'
    t.integer 'returning_visitors'
    t.string 'resource_id'
    t.string 'resource_type'
    t.datetime 'created_at', null: false
    t.datetime 'updated_at', null: false
    t.integer 'user_id'
    # one or more indexes that make sense
  end
end
```

And we'll use parameterized scopes to hopefully simplify the querying process for reports. I'm going to create a couple tickets based off this decision. First will be to create the table/migration/model with some initial test coverage. Then a second for defining and implementing the custom scope lambas we'll need to do all the querying.

**Comment by mcritchlow** [comment]
Closing, next step is #2735
