### ISSUE TITLE
Use inclusive language in user activity log

### ISSUE THREAD

**Issue by flutterflies** [samvera/hyrax#2697]
### Descriptive summary
After a user's profile has been updated a message shows in their activity log which says "User xxx has edited his or her profile." This should be rewritten in a way that makes no use of gendered pronouns such as "User xxx has edited their profile.".
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/12132647/36562349-bf370136-17e4-11e8-9ccd-dabb50e37b51.png">

### Rationale
There is a constantly increasing number of people that do not wish to identify within the traditional gender binary. While using the phrase "he or she" is inclusive of women it can still be considered exclusive of this growing group of people. 

### Steps to reproduce the behavior

1. Edit your profile
1. Look at the activity log on your dashboard

### Related work

https://github.com/samvera/hyrax/blob/master/app/jobs/user_edit_profile_event_job.rb#L9

**Comment by julesies** [comment]
thanks for reporting this @flutterflies

**Comment by mjgiarlo** [comment]
@flutterflies Fix: https://github.com/samvera/hyrax/pull/2699

**Comment by mjgiarlo** [comment]
@flutterflies This will be included in the next release of Hyrax, 2.1.0. Thanks again. :)
