### ISSUE TITLE
Collect Work Status History

### ISSUE THREAD

**Issue by sethaj** [samvera/hyrax#2719]
In order to display Work Status Over Time for #2555 , we first need to collect that information. A Work's "Status" will refer to it's sipity_workflow_state.name. The overall archetecture of the analytics backend might dictate how this is done but could possibly be:

- [ ] Create a migration and model which will contain the work's id, it's state and the date/time.
- [ ] When a work changes state, add a row to the table. The trigger could possbily just be in `services/hyrax/workflow/workflow_action_service.rb` around line 22, getting the current statename like possibily `PowerConverter.convert_to_sipity_entity(work).workflow_state.name`
- [ ] Decide: If a work is deleted, it's status history should also be deleted(?) If this is true, probably create an actor "cleanup_work_status_history" modeled after the `cleanup_trophies_actor.rb`

See #2720 which is similar to this, but for Visibility history.

**Comment by mcritchlow** [comment]
@nestorw @lfarrell (and Seth if you're around! ) I think my main question/concern about adding these metrics (visibility and work status) into our recently created resource stats table would be where we could potentially end up with multiple entries per day. Basically the scenario I'm thinking is on the same day the following occurs (either visibility or work status):

1. Record is created, set visibility to private
2. Add metadata, set visibility to public
3. Find out the we don't have the right donor agreement to make this public, set visibility to campus only.

Is this 3 entries in the DB for that `work_id` for the day?
Or, do we update an existing entry if there already is one and create one if not (`find_or_create` basically)?
Or??

cc/ @vantuyls

**Comment by vantuyls** [comment]
thinking about this in the larger context of event tracking (and dare i say PREMIS), those should all be separate entries.

**Comment by nestorw** [comment]
I like your `find_or_create` idea for these entries. We aren't keeping an audit log for statuses, it's a history that we're using to make tables with granularity down to the day.

**Comment by nestorw** [comment]
maybe it really should be a separate table then if we need to store them all.

**Comment by mcritchlow** [comment]
Ok, yeah, so if these need to all be individual entries, which indeed makes good sense from the context you mention @vantuyls , then as @nestorw said I lean towards a separate table for these things. The new table is really setup to work for daily entries, and I think this might just complicate things too much, even though it would be great (in a sense) to have everything in one table
