### ISSUE TITLE
Run nested indexing as a job instead of inline

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2728]
### Descriptive summary

Samvera nested indexer is triggered as an after_update_index callback for collection indexing. It is a rather time-consuming process, and should not be run inline. This should spin off a job instead.

https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/collection_nesting.rb

Link to related tickets or prior related work here.

**Comment by jgondron** [comment]
I have this mostly working in a branch, but I've uncovered an issue that is the more likely culprit for the slowness: #2798. 2798 also introduces a race condition between when the async job completes and when a user adds another child to a collection. I have more details on this if needed, but I'd recommend fixing 2798 first and then reassessing if this ticket is still needed. If it is, I can retest to make sure the race condition was resolved with 2798.

**Comment by elrayle** [comment]
@laritakr @jgondron Should this issue be closed?  My understanding from our conversations is that it is not recommended to run nesting in a background job as it negatively impacts use of the index in other areas.  If that is the case, can you give a summary of the issues so this issue can be closed?

**Comment by laritakr** [comment]
Yes I believe it should be closed. With efforts toward resolving the effects of issue 2798, the impact of inline nested indexing is lowered.

The only current reliance on the nested indexing fields is for validation of creating nested relationships. The nesting modals throw an error if the indexing isn't complete. So by spinning the indexing to a different job, we can't add any new subcollections until the indexing from the prior one is completed. 

There is no good way to directly identify to the app that the collection is in a transient state, so to prevent the error in cases where we are waiting for the indexing to continue, we would have to modify the validation methods to treat the absence of the nested indexing fields from the solr document as the indicator that the object is in a transient state.

Alternately, we could spin the full creation of the relationship itself into a job, rather than just the indexing. This would mean that other cases where nested indexing occurs would still be handled inline. Spinning them off as well would mean that the relationship creating job would then spin off a second nesting job. 

However, not creating the nested relationship inline would mean that the users have to wait until the job finishes for the new parent or child collection to appear. This seems less than ideal unless we are certain that it is necessary.

**Comment by elrayle** [comment]
@laritakr I'd like to summarize to be sure I understand the issues correctly.

* The nested indexing fields are used by a validation algorithm to determine which collections can be a parent or subcollection of a collection.
* While indexing is running, the indexing fields are empty or absent?
* Empty/missing indexing fields make the current validation check inaccurate.

**Comment by laritakr** [comment]
@elrayle While indexing is running the nesting indexer fields in solr documents are missing. And missing fields make the validation check fail with an error.
