### ISSUE TITLE
Proposal: remove more/less from pagination of parent collections

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2743]
### Descriptive summary

Relates to https://github.com/samvera/hyrax/issues/2618

When pagination was added to the parent collections list, the issue specified that it be added in addition to the existing more/less functionality rather than replacing it. This created awkward code in view partials and specs for both dashboard and public views, and left clunky code in collection presenter.

I am proposing that the pagination is adequate, and the more/less code should be removed. 
We may also want to consider whether paginating on 10 collections is the right quantity, or if we want a smaller default pagination value for collections and subcollections.

### Rationale

1. Using both more/less and pagination is inconsistent with other code throughout the app
2. Using both complicates the code

With the size of our community, maintainability and consistency should be our goals.

See sample screen shots below in comments

**Comment by laritakr** [comment]
## Screenshots of Public collection views

![screen shot 2018-03-01 at 6 12 16 pm](https://user-images.githubusercontent.com/17851674/36875368-a251204e-1d7d-11e8-9a77-a49b9324d4b5.png)
![screen shot 2018-03-01 at 6 11 58 pm](https://user-images.githubusercontent.com/17851674/36875369-a4378cfe-1d7d-11e8-845c-82dd1427fb61.png)
![screen shot 2018-03-01 at 6 11 30 pm](https://user-images.githubusercontent.com/17851674/36875370-a5d0d566-1d7d-11e8-9bc3-3fef852af9f7.png)

**Comment by laritakr** [comment]
## Screenshot of Dashboard collection views

![screen shot 2018-03-01 at 6 10 29 pm](https://user-images.githubusercontent.com/17851674/36875398-c229e73e-1d7d-11e8-967c-2af38ab301db.png)
![screen shot 2018-03-01 at 6 09 05 pm](https://user-images.githubusercontent.com/17851674/36875399-c4b07cac-1d7d-11e8-8466-ae94c51498fa.png)
![screen shot 2018-03-01 at 6 09 05 pm](https://user-images.githubusercontent.com/17851674/36875406-c8a403ce-1d7d-11e8-8ef4-7d472405a1e0.png)

**Comment by elrayle** [comment]
I'm fine with this as it simplifies the UI and technical debt.

**Comment by laritakr** [comment]
@elrayle do you know if anyone designed it with both, or was the issue to add pagination created to include both simply because more/less was already there?

**Comment by laritakr** [comment]
## After proposed changes
(After changes, only the 6-parent collections will look different)


![screen shot 2018-03-02 at 11 16 14 am](https://user-images.githubusercontent.com/17851674/36909307-a8332474-1e0b-11e8-80c0-44bc9a922892.png)
![screen shot 2018-03-02 at 11 16 06 am](https://user-images.githubusercontent.com/17851674/36909309-aa3b3dec-1e0b-11e8-9b9f-adfdb7eb61be.png)

**Comment by laritakr** [comment]
Tagging @samvera/hyrax-ui-ux-advisors for approval before I make this change.
