### ISSUE TITLE
Viewer of an admin set cannot see private works

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2760]
Moved from: https://github.com/curationexperts/nurax/issues/191

Reporting for
Testing for Hyrax 2.1.0 beta 1
Browser: Chrome Version 64.0.3282.167 (64-bit)
Admin Sets and Workflow testing (AS 1.14)
Descriptive summary
When logged in as a Viewer of an admin set, when going to the URL of the work this error is displayed:

![image](https://user-images.githubusercontent.com/4356335/36923645-ece63b0a-1e39-11e8-8a1a-1b219970fe8d.png)

In addition, as a viewer, when I click on the admin set in Managed Collections, I get that same error.

**Comment by elrayle** [comment]
@jrr A couple of clarifying questions:
* Can the Viewer see the private work in the list of works on the admin set's show page?
* Was the Viewer a Viewer of the admin set when the work was created?

**Comment by elrayle** [comment]
Oh, I just saw that you get an error following these steps...
* Dashboard -> Collections -> Managed Collections -> click title of admin set where user is viewer
Get unauthorized error.

If that is correct, then the previous questions are unimportant.

**Comment by elrayle** [comment]
### Proposal:  

When a viewer or depositor is added, grant them read_access to the admin set (unless group=public or registered)

### Impact:  

This will allow viewers and depositors to see the admin set show page following Dashboard -> Collections -> Managed Collections -> click title of admin set where user is viewer or depositor.

### Backward Compatibility:

In 1.0 and 2.0, viewers and depositors are not given read access to admin sets.  This means the solr docs for admin sets created in those versions will not have read access.

#### Proposed Migration Solution:

The [Hyrax::Collections::MigrationService](https://github.com/samvera/hyrax/blob/master/app/services/hyrax/collections/migration_service.rb) runs as part of the migration process to add collection_type_gid to the solr doc and setup the permissions for all existing collections.  This script could be extended to add read access for all viewers and depositors of admin sets.

**Comment by julesies** [comment]
sorry @elrayle not sure how I missed these questions. I totally forgot about the viewer not having access to previous works. This is so hard b/c i don't know when viewers are added. but i'll try a fresh test.

**Comment by elrayle** [comment]
Discussed at samvera-tech call and email sent to samvera-tech list requesting feedback on the proposal.

**Comment by julesies** [comment]
@elrayle I tested this with direct URL access and a clean test and the viewer of the admin set can see the work but not the file. I did confirm that the student@example.com is listed as a viewer in the admin set, work and file. cc @laritakr  in case it's an index thing!
