### ISSUE TITLE
User who is a proxy of another user gets exception after Create New Batch of Works

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2761]
moved from https://github.com/curationexperts/nurax/issues/192

Reporting for
Testing for Hyrax 2.1.0 beta 1
Browser: Chrome Version 64.0.3282.167 (64-bit)
Works (W_1.7)
Test Case
Issue happens if logged in as "admin". Does not occur if logged in as a regular user/manager.

Descriptive summary
When attempting to “Create Batch of works” (added description, resource type, relationships, visibility (set to Private), added to Admin Set 1, etc.), after checking the “Check deposit agreement” and clicking on “Save” receive the “We're sorry, but something went wrong error message”.

![image](https://user-images.githubusercontent.com/4356335/36923715-2644ec20-1e3a-11e8-9ae8-8c61e1e0de54.png)

**Comment by afred** [comment]
Hi @julesies, we are at the Samvera Dev Congress and we're trying to reproduce this bug and can't. We've followed the steps you have listed above, but could you expound on the `etc` part?

From the error shown, it looks there was a hiccup in displaying some of the user interface for sharing, specifically the "Sharing" tab when adding a batch.

If you can give us some more specific details about exactly what was filled in, clicked on, etc., then it will get us closer to replicating it. Thanks!

**Comment by julesies** [comment]
Hope this helps, ping me on slack if you need to! Also, does someone want to try this on Nurax? also curious if you have more than one work type in your test instance?
1. As admin (I didn't try other roles), log in
2. Go to dashboard: Works
3. Click Create Batch of Work: Select Image from Modal
4. Add folder: select folder
5. Click Description tab: enter test values into each required field
6. Click public visibility
7. Click agree to deposit and click save. 
8. then you see the error.

**Comment by julesies** [comment]
@afred ☝️

**Comment by chrisdaaz** [comment]
i got this error when adding a batch of works to "Default Admin Set" on [NURAX](https://nurax.curationexperts.com): 

![image](https://user-images.githubusercontent.com/24395592/38108324-1539fcce-335a-11e8-8d4d-fabed6e8c979.png)

The error happens upon hitting `save`, but the works appear in the `/dashboard/my/works` view.
