### ISSUE TITLE
Viewer see Collections they shouldn't in dashboard.

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2762]
https://github.com/curationexperts/nurax/issues/200

Viewer sees way more collections than they should: I'm using student@example.com

Clicking on a collection in the list gives "Unauthorized" error message.

Note the visibility filter also shows way less than it should given the collections below:

![image](https://user-images.githubusercontent.com/4356335/36923769-518e9eee-1e3a-11e8-8f5c-861ea1ffec80.png)

**Comment by elrayle** [comment]
I see a bunch of admin sets and only 4 collections.  I do have permissions to the 4 collections and can view their show pages.  The visibility I see is for the 4 collections.

So I think that all admin sets are being picked up by the search filter applied for Managed Collections whether the user has access or not.

I picked one of the Admin Sets 'Admin Set Test 9...' and checked its permissions.  It has...
* Depositors:  Registered Users
* Viewers: student@example.com

Based on that, I would expect student@example.com to have this admin set in their list of Managed Collections AND be able to view the admin set.

As an aside...  one issue I would like to resolve is that right now, if participants=Registered Users | Public, the admin set/Collection will appear on the Managed Collections tab.  I do not really consider a user to have special access when the access is granted to everyone and believe the search that creates Managed Collections should exclude those AdminSets/Collections.

I suspect that most of the admin sets in the list are brought in with participants=Registered Users | Public.

Potentially related Issue:  #2760 Viewer of an admin set cannot see private works
