### ISSUE TITLE
Unauthorized access of Works for transferred ownership

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2763]
Moved from: https://github.com/curationexperts/nurax/issues/202
Reporting for
Testing for Hyrax 2.1.0 beta 1
Browser: Chrome Version 64.0.3282.167 (64-bit)
Works (W_1.14)
Descriptive summary
When in the Works view, after accepting transferred ownership, the only action available is "Highlight work on profile".

![image](https://user-images.githubusercontent.com/4356335/36923831-8729ccae-1e3a-11e8-9bf7-d6184a987802.png)

When trying to access a Work that has been transferred from an "admin" account, I receive an "unauthorized" error message.

![image](https://user-images.githubusercontent.com/4356335/36923841-8e36a97c-1e3a-11e8-9b45-767637e0e0ae.png)

Expected behavior
After accepting the transfer of ownership, I should have full control of the work/files.

**Comment by julesies** [comment]
@gamontoya can you test this again? (this ticket was moved from nurax)

**Comment by no-reply** [comment]
Closing this as cannot be reproduced. Per Hyrax release-issues call (at present timestamp).
