### ISSUE TITLE
2.1.0.beta1:  Search "My shares" gives error messages

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#2767]
also reported to 
* hyku:  https://github.com/samvera-labs/hyku/issues/1518
* nurax: https://github.com/curationexperts/nurax/issues/213

### Descriptive summary

/dashboard/shares page is not present in hyrax/nurax/hyku. 

Nurax: QA Testing for Hyrax
Hyrax Version: 2.1.0.beta1
Hyrax Branch: v2.1.0.beta1_qa
Hyrax Revision: 8fe35f54e067fd499a4467b9ccbefa48233d43a2 

Hyku v1.0.0.beta2 Docker 

Firefox 58.0.2 (64-bit) canonical 1.0

### Rationale

This is a bug.

### Expected behavior
Search within the with the option "My shares" selected presents results on my shared work. 
The search fields which allow this selection of "My shares" are located at    
* /             hyrax starting page (eg. see localhost:3000 or https://nurax.curationexperts.com/) and 
* /catalog
* that very field on the top of the Edit dialog of a single work.

### Actual behavior
Search with the  option "My shares" selected directs to /dashboard/shares which is not preset.

### Steps to reproduce the behavior
1. Login
1. Go to  
* /            hyrax starting page (eg. see localhost:3000 or https://nurax.curationexperts.com/)  
* /catalog
* that very field on the top of the Edit dialog of a single work.
1. Then select "My Shares" from the pull down right next to the search "Go" button
1. (optional) enter search term 
1. Press the "Go" button 

### Related work

also reported to 
* hyku:  https://github.com/samvera-labs/hyku/issues/1518
* nurax: https://github.com/curationexperts/nurax/issues/213

**Comment by elrayle** [comment]
Looks like this is a long standing issue left over from either Hyrax 1.0 or Sufia.  This is technical debt that should get fixed.

@vantuyls Blocker for 2.1.0 address in 2.1.1 since it has been around awhile?

**Comment by no-reply** [comment]
The controller handling "Shared Works" was removed (when?). I'd suggest the following options:

 * Remove the `My Shares` button from the search dropdown
 * Point the `My Shares` button to a search on Managed Works (rename?; remove for admin users?)
 * Reinstate the old controller (:no_good:)

**Comment by elrayle** [comment]
We remove that dropdown from our apps, so I don't have a strong opinion between option 1 and 2.  This has been broken for a while, so I'm not sure how strongly desired it is.  I would lean away from option 3 as it increases instead of decreases technical debt.

**Comment by vantuyls** [comment]
if i'm thinking about this right "My Shares" is just the stuff one has shared. correct?

if yes, i don't think this search bar is the "right" place to access that stuff - i'd prefer people access their shared/managed content via the dashboard. (edited)

and by "I'd prefer" i mean that i think using that dropdown and a blank search box browse action to get to a dashboard location is a cheap shortcut that i'd like to avoid.

if thats all this dropdown option is offering, i think we should remove it

so, option 1

**Comment by elrayle** [comment]
We remove that dropdown from our apps, so I don't have a strong opinion between option 1 and 2.  This has been broken for a while, so I'm not sure how strongly desired it is by the community in general.  I would lean away from option 3 as it increases instead of decreases technical debt.

**Comment by elrayle** [comment]
There is a search box on Dashboard -> Collections -> Managed Collections that performs the action that searching My Shares used to perform.  So I second option 1.

**Comment by vantuyls** [comment]
okay, i think we move forward with Option 1: remove My Shares from the search drop down menu.

**Comment by elrayle** [comment]
For 2.1.0, the scope of this issue is to remove My Shares from the selection list beside the search box on the home page.

For 2.1.x, there should be a refactor to remove all references to my shares.
