### ISSUE TITLE
Changing visibility on a work doesn't reindex correctly

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#2777]
### Descriptive summary

When visibility is changed on a work, the access in Fedora gets changed, but it doesn't reindex correctly. This is similar to a prior issue in collections which required an extra "update_index". See http://samvera.github.io/nested-indexing.html#potential-pitfalls for more information. 

The nesting reindexer is causing the data to not be indexed on changes, because indexing happens before the actual data is persisted to Fedora, and the nesting reindexer uses persisted data, not cached data. 

There may be other errors... UI testing is needed to find everywhere where data is not being indexed appropriately for works.

Identified situations with bugs
- [ ]  Changing visibility setting on a work

**Comment by cjcolvar** [comment]
:+1: I noticed this specific case where changing visibility of a work required two saves in order to change the visibility badge but thought I was just doing something odd.

**Comment by laritakr** [comment]
Caused by this issue: https://github.com/samvera/hyrax/issues/1826
