### ISSUE TITLE
Add download link to Audio and Video Work and Fileset Pages

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2795]
Per the convo in PR https://github.com/samvera/hyrax/pull/2790 this ticket is to address the download action for Audio and Video Files. The download button on audio and video players does not work. As a minimal fix for 2.1 we are adding "Download this file" links to audio and video works and fileset views under the thumbnail. 

To do: 

- [ ] Add "download this file links" to Work view for Audio and Video works

- [ ] Add "download this file" links to fileset view for Audio and Video filetypes

For background read: https://github.com/curationexperts/nurax/issues/153 

Examples:

A PDF example (shows download file under thumbnail): https://nurax.curationexperts.com/concern/parent/r494vk17h/file_sets/fj236208t

these examples are where there is no download file option except in the player. when you click that button it downloads a file named "j-ogg.ogg".

a video Work view example: https://nurax.curationexperts.com/concern/images/r494vk17h?locale=en

an audio Fileset view example: https://nurax.curationexperts.com/concern/parent/r494vk17h/file_sets/wh246s13j

**Comment by elrayle** [comment]
Fixed by PR #2797
