### ISSUE TITLE
Only show files users have permission to see

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2796]
### Descriptive summary
Currently Hyrax shows a generic representation of private files attached to public work/institutional work. Now we want to hide this and only show files that a user has permission to see. 

### Expected behavior
Users can see only files they have permission to see

### Actual behavior
Users can see all files attached to a work, with generic representations of files they are not permitted to see. 

### Related work

https://github.com/samvera/hyrax/issues/2677

**Comment by elrayle** [comment]
Per discussion at samvera-tech call, this issue is no longer a blocker for 2.1.0 release.

Rationale:  The current behavior is the existing behavior for 1.0 and 2.0.  As this is not a behavior change, it is not a blocker issue for release.

**Comment by elrayle** [comment]
### Proposed Solution

Add a setting to Dashboard -> Settings -> Features -> Hide private files when user doesn't have access which is OFF by default for backward compatibility.

On views, add check of the setting and do not show private files if is it ON.

**Comment by julesies** [comment]
I think we were going to first look into making this feature into a flipper? @elrayle should we remove from project?

**Comment by elrayle** [comment]
@julesies The proposed solution says to add to Settings -> Features which under the covers means to add a flipper.

This is ready to implement as stated in the **Proposed Solution** in the previous comment.

**Comment by julesies** [comment]
Not sure how I missed that! Thanks!
