### ISSUE TITLE
NestedCollectionPersistenceService#persist_nested_collection_for is causing unexpected save and reindex of parent.

### ISSUE THREAD

**Issue by jgondron** [samvera/hyrax#2798]
### Descriptive summary

Nested collections are triggering a save on the parent and should not be. This is causing additional after save/index events on the parent object that are unnecessary. The result is a cascade to reindex to all of that parent's descendants. The effect is that adding a sub-collection or work to a large collection is slow.

### Rationale

Since we are only storing the relationship on the child, modifying the parent should not be necessary. 

### Expected behavior
When https://github.com/samvera/hyrax/blob/master/app/services/hyrax/collections/nested_collection_persistence_service.rb#L15 is called, I would expect it to update the child only.

### Actual behavior
When https://github.com/samvera/hyrax/blob/master/app/services/hyrax/collections/nested_collection_persistence_service.rb#L15 is called, it updates the child, then saves both the child and the parent. This can be traced down to the indirect association insert_record method https://github.com/samvera/active_fedora/blob/master/lib/active_fedora/associations/indirectly_contains_association.rb#L15. Within this context, the "container" is the child collection/work and the "record" is the parent collection.

Here are the relevant bits of a stack trace related with this operation:

```
    #22 ActiveFedora::Associations::IndirectlyContainsAssociation.insert_record(record#Collection, force#TrueClass, validate#TrueClass) at /Users/jgondron/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/indirectly_contains_association.rb:15
    #23 block (2 levels) in ActiveFedora::Associations::CollectionAssociation.block (2 levels) in concat_records(*records#Array) at /Users/jgondron/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/collection_association.rb:162
    #24 ActiveFedora::Associations::CollectionAssociation.add_to_target(record#Collection, skip_callbacks#FalseClass) at /Users/jgondron/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/collection_association.rb:260
    #25 block in ActiveFedora::Associations::CollectionAssociation.block in concat_records(*records#Array) at /Users/jgondron/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/collection_association.rb:161
    ͱ-- #26 Array.each at /Users/jgondron/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/collection_association.rb:159
    #27 ActiveFedora::Associations::CollectionAssociation.concat_records(*records#Array) at /Users/jgondron/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/collection_association.rb:159
    #28 ActiveFedora::Associations::IndirectlyContainsAssociation.concat(*records#Array) at /Users/jgondron/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/indirectly_contains_association.rb:9
    #29 ActiveFedora::Associations::CollectionProxy.<<(*records#Array) at /Users/jgondron/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active-fedora-11.5.2/lib/active_fedora/associations/collection_proxy.rb:857
    #30 #<Class:Hyrax::Collections::NestedCollectionPersistenceService>.persist_nested_collection_for(parent#Collection, child#Collection) at /Volumes/Repositories/samvera/hyrax/app/services/hyrax/collections/nested_collection_persistence_service.rb:18
```

### Steps to reproduce the behavior

1. Create a nested collection
2. Add a sub-collection or work to the new collection

### Related work

There is a request to background job the nested reindexing to improve performance (#2728), but this issue is likely the cause of the performance issues, not the nested reindexing.

**Comment by laritakr** [comment]
I added a new work with one image file. The nested reindexer was called 6 times during this process, which means update_index was called 6 times on the work as well.

**Comment by laritakr** [comment]
Adding a member_of_collections relationship causes the unnecessary reindex of the parent, but none the child. A subsequent manual reindex of the child is necessary.

However, removing a member_of_collections relationship does NOT reindex the parent. Given that we were told that saving the parent is necessary for the LDP container relationship and can't be removed, why is it not required for removal of the relationship?
