### ISSUE TITLE
is part of list of collections should be comma separated

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2800]
### Descriptive summary

When a work belongs to multiple collections, the list of collections should be comma separated.

### Expected behavior

Same as actual except collections are comma separated...
```
Is part of: Col 10.3, UC 8.1 public shared
```

### Actual behavior

![image](https://user-images.githubusercontent.com/6855473/37245261-6abce73e-2463-11e8-8669-bb95426a23ce.png)

### Steps to reproduce the behavior

1. Put a work in at least 2 collections
1. Dashboard -> Works

Verify collection names are comma separated.

**Comment by laritakr** [comment]
Collection list doesn't appear until https://github.com/samvera/hyrax/pull/2803 is merged.
