### ISSUE TITLE
Move Authorize Proxies to "Your Activity" in dashboard

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2811]
### Descriptive summary

Right now to see/find the place to add a proxy you have to go to Dashboard: Your Activity: Profile: Profile Edit: Authorize Proxies.  I'd like to move it under "Your Activity" in the dashboard. 

### Rationale

It's very hidden right now.

What do you think about making a PR to hyrax for this vs doing locally?

@samvera/hyrax-repo-managers

**Comment by chrisdaaz** [comment]
i like this idea. we use proxies often.

**Comment by brianmcbride** [comment]
I think this is a good idea to implement.

**Comment by rjkati** [comment]
This seems reasonable to me.

**Comment by newmanld** [comment]
+1

**Comment by hannahfrost** [comment]
+1

—
Hannah Frost
Manager, Digital Library Product and Service Management
Service Manager, Stanford Digital Repository
Stanford Libraries

m: +1 (650) 799 1352
Lathrop 384
Stanford, CA 94305-6069




On Mar 16, 2018, at 11:00 AM, Linda Newman <notifications@github.com<mailto:notifications@github.com>> wrote:


+1
