### ISSUE TITLE
Jobs Should Enqueue to Different (or Configurable) Queues

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#2817]
### Descriptive summary

Various jobs in Hyrax queue to `Hyrax.config.ingest_queue_name`. These jobs have differing performance properties and priorities, but cannot be moved onto separate queues without reopening the job classes.

### Rationale

Some jobs (e.g. the `CreateDerivative` job) can end up being quite CPU intensive. Running only a few of them will tend to bog down a server. Other jobs on the same queue can run massively in parallel and benefit from it. We currently make it hard for applications to put these on separate queues; something any production applications that might have to process items at any scale will want.

### Expected behavior

I should be able to configure or inject the queue name without reopening the class.

### Actual behavior

My application needs to own jobs that go to `Hyrax.config.ingest_queue_name` to configure job priority or thread numbers.

### Steps to reproduce the behavior

1. Ingest some items
1. Watch all the jobs go into the same `ActiveJob` queue.

**Comment by no-reply** [comment]
Application side fix:

in `config/initializers/hyrax.rb`, `CreateDerivativesJob.queue_as(:my_special_queue)`; on console `CreateDerivativesJob.queue_name # => "my_special_queue"`

Information about this should go in documentation to close this ticket.

**Comment by mjgiarlo** [comment]
@no-reply Oh, geez... I think we may already have covered this, which suggests perhaps this documentation is in the wrong place (or needs links from other places): https://github.com/samvera/hyrax/wiki/Background-Workers#queue-names

**Comment by no-reply** [comment]
Closing this per @mjgiarlo's pointers above.

I'm expecting to do some doc writing on background workers and sidekiq configuration in prep for upcoming training.

**Comment by mjgiarlo** [comment]
:+1:
