### ISSUE TITLE
Cannot add groups as participants in collections

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#2824]
### Descriptive summary

Hyrax Admin Sets allow users and groups (hydra role management groups) to be added as managers/ depositors/ viewers; however, new collection types only allow individuals to be added as managers/ depositors/ viewers. When trying to add a group, the interface updates, but does not show or respect group membership. 

cc: @davidschober

### Rationale

Collections should allow group membership, just like administrative sets.

### Expected behavior

Groups *and* individuals can be added as collection participants. 

### Actual behavior

Groups *cannot* be added, only individuals. 

### Steps to reproduce the behavior

1. On a system with Hydra Role Management (or other role system) + Collections Extentions
2. Create a group in the system
3. Create a collection type
4. Allow sharing
5. Add group as a manger of the collection

### Related work

Link to related tickets or prior related work here.

**Comment by chrisdaaz** [comment]
this was not tested in nurax but was noted by a local instance of hyrax 2.1 beta + role management.

**Comment by elrayle** [comment]
Dup #2619 which is currently being worked on

**Comment by davidschober** [comment]
Thanks! @elrayle
