### ISSUE TITLE
Remove Your pronoun from breadcrumbs

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2829]
### Descriptive summary

Bread crumbs leading to the Collections and Works index pages include the pronoun Your as in Your Collections and Your Works.  These pronouns should be removed.

### Expected behavior

Bread crumbs that link to the works index page should use label:  Works
Bread crumbs that link to the collections index page should use label:  Collections

### Actual behavior

Bread crumbs that link to the works index page should use label:  Your Works
Bread crumbs that link to the collections index page should use label:  Your Collections

### Steps to reproduce the behavior

As an admin and then again as a non-admin...

1. Visit the following pages and confirm they use the label Collections in the breadcrumb.

Dashboard -> Collections
Dashboard -> Collections -> New Collection
Dashboard -> Collections -> click a title to go to admin show page
Dashboard -> Collections -> click a title -> click Public view of Collection
Dashboard -> Collections -> click a title -> Edit collection

2. Visit the following pages and confirm they use the label Collections in the breadcrumb.

Dashboard -> Works
Dashboard -> Works -> Add new work -> select type
Dashboard -> Works -> Create batch of works -> select type
Dashboard -> Works -> click a title to go to show page
Dashboard -> Works -> click a title -> Edit
Dashboard -> Works -> click a title -> Analytics
Dashboard -> Works -> click a title -> Attach Child -> select type

Dashboard -> Works -> click title (for a work that has files) -> click title for a file
Dashboard -> Works -> click title (for a work that has files) -> click title for a file -> Edit This File
Dashboard -> Works -> click title (for a work that has files) -> click title for a file -> Analytics

### Related work

[Breadcrumb related issues](https://github.com/samvera/hyrax/issues?q=is%3Aissue+is%3Aopen+label%3Abreadcrumbs)

**Comment by jcoyne** [comment]
Isn't this important? The "Your" indicates the collections an works you have access to as opposed to all the works or collections in the system. It seems this is particularly important to an admin user who may have their own works on one screen, and "all works" on another screen.

CC @ggeisler

**Comment by elrayle** [comment]
This PR has the side effect of removing Your from the tabs on Dashboard -> Collections and Dashboard Works.  The tabs now read...

* non-admin
     * Dashboard -> Collections tabs:  Managed Collections | Collections
     * Dashboard -> Works tabs:  Managed Works | Works
* admin
     * Dashboard -> Collections tabs: All Collections | Collections
     * Dashboard -> Works tabs: All Works | Works

Examples...

![image](https://user-images.githubusercontent.com/6855473/38032624-f41d8572-3252-11e8-9fd1-f7f66b9c1373.png)

![image](https://user-images.githubusercontent.com/6855473/38032664-0b4eb1c6-3253-11e8-8861-46fdc2cd8343.png)

**Comment by elrayle** [comment]
@jcoyne FYI... This change was discussed fairly broadly and it was decided to remove the pronouns.  They were being used inconsistently.  Examples... My Dashboard, Your Works, etc.  And the URLs use 'my' while the tab uses 'Your'.

@vantuyls @julesies @mjgiarlo Any comments to add to this discussion?

**Comment by ggeisler** [comment]
FWIW, I believe my past relevant mockups suggested **changing** (not removing) the pronoun used in various places in the app to "Your" from "My". As @jcoyne suggested above, I think seeing "Your Collections" can be helpful to the user to in immediately understanding that these are not all collections, just ones that user has access to.

For example, I believe a user that see tabs like:

> Managed Collections | Your Collections
> All Works | Your Works

will more easily understand the difference between the two tabs than:

> Managed Collections | Collections
> All Works | Works

That said, since I've been pretty much out of the loop of Samvera  development for six months or so there very well might have been subsequent discussions where the consensus was to remove the pronoun altogether.

**Comment by vantuyls** [comment]
Okay, i'm in favor of removing the pronouns from the breadcrumbs - the index page (e.g. Works, Collections, etc.) provides both tabs, so including "your" there is confusing.

I am also in favor of keeping the pronouns on the tabs on these index pages as they offer clarity.
