### ISSUE TITLE
Add left sidebar to lease and embargo management pages

### ISSUE THREAD

**Issue by smithjp** [samvera/hyrax#2837]
### Descriptive summary

I would like to see the dashboard sidebar on the lease and embargo management pages since I am navigating to these pages through the sidebar.

### Expected behavior

I should see the dashboard sidebar on the manage leases page.
I should see the dashboard sidebar on the manage embargoes page.

### Actual behavior

I can navigate to the lease and embargo management pages, but the sidebar is not currently available on these pages.

### Steps to reproduce the behavior

As an admin...

1. Login and navigate to the user dashboard
1. Click on the link 'Manage Embargoes'
1. Confirm that the sidebar is not present

**Comment by julesies** [comment]
there are few pages in this category @smithjp related: https://github.com/curationexperts/nurax/issues/239
