### ISSUE TITLE
Matomo vs GA terminology

### ISSUE THREAD

**Issue by nestorw** [samvera/hyrax#2850]
<img width="853" alt="screen shot 2018-03-27 at 12 18 50 pm" src="https://user-images.githubusercontent.com/1766876/37983101-69f5c1d0-31c0-11e8-83ab-8744e4a03e04.png">

**Comment by vantuyls** [comment]
Terms we need definitions and crosswalks for:
- Visitor
- User
- Session

**Comment by vantuyls** [comment]
**Visitor** - An individual person who visits the repository - this is sometimes referred to as User
- Matomo: nb_unique_visitor
- Google: ga:users

**Session** - a repository usage event (e.g. a user visiting the repository and interacting with content in some way)
- Matomo: nb_visits
- Google: ga:sessions

**Comment by mcritchlow** [comment]
Ok, so if I'm understanding this correctly, we need to update our resource statistic table which currently is:

```
    create_table :resource_stats do |t|
      t.datetime :date, null: false
      t.integer :user_id
      t.integer :downloads
      t.integer :pageviews
      t.integer :unique_visitors
      t.integer :returning_visitors
      t.string :resource_id
      t.string :resource_type

      t.timestamps
    end
    add_index :resource_stats, :date
    add_index :resource_stats, [:date, :resource_id, :resource_type]
 ```

And it should be:
```
    create_table :resource_stats do |t|
      t.datetime :date, null: false
      t.integer :user_id
      t.integer :downloads
      t.integer :pageviews
      t.integer :visitors
      t.integer :sessions
      t.string :resource_id
      t.string :resource_type

      t.timestamps
    end
    add_index :resource_stats, :date
    add_index :resource_stats, [:date, :resource_id, :resource_type]
 ```

Is that right?

**Comment by mcritchlow** [comment]
@nestorw :point_up: does that look right to you?

**Comment by mcritchlow** [comment]
For now I'm going to update the database migration for creating the table to align with what's above. if that turns out to be incorrect let's adjust as needed
