### ISSUE TITLE
Collections doesn't have select all dropdown

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#2852]
But the works page does. For consistency, they should both be the same.  

Works page (/dashboard/my/works):
<img width="251" alt="screen shot 2018-03-27 at 11 50 33 am" src="https://user-images.githubusercontent.com/92044/37988205-2d2855a2-31b5-11e8-8038-27970f41d11e.png">

Collections (/dashboard/my/collections):
<img width="273" alt="screen shot 2018-03-27 at 11 50 46 am" src="https://user-images.githubusercontent.com/92044/37988214-2ffeb104-31b5-11e8-8b22-ac8034be4e7f.png">

**Comment by no-reply** [comment]
Reopening this for some design work. https://github.com/samvera/hyrax/pull/3307

@samvera/hyrax-ui-ux-advisors

**Comment by chrisdaaz** [comment]
at a minimum, i think the checkboxes should have consistent alignment in the column.

before #3290 

![image](https://user-images.githubusercontent.com/24395592/46033351-a5588e00-c0c3-11e8-99ca-4f4f269e752d.png)

after:

![image](https://user-images.githubusercontent.com/24395592/46033330-94a81800-c0c3-11e8-893e-d8de37280233.png)

**Comment by chrisdaaz** [comment]
@VivianChu i'm unable to test on a local hyrax. my screenshots are from https://nurax-dev.curationexperts.com

it looks like the alignment issue is still there on both Firefox (62.0.2) and Chrome (69.0.3497.100)

**Comment by VivianChu** [comment]
@chrisdaaz - I just tried to test from https://nurax-dev.curationexperts.com and I didn't see the alignment issue.  Here's the screen shot from both Firefox (62.0.2 64-bit) and Chrome Version 69.0.3497.100 (Official Build) (64-bit)
![collectionsalignment](https://user-images.githubusercontent.com/1864660/46158771-73663980-c233-11e8-9356-919409268d73.png)

**Comment by chrisdaaz** [comment]
weird. this appears to only be the case when there are collections that cannot be selected:

![image](https://user-images.githubusercontent.com/24395592/46159293-93065d80-c245-11e8-8bcf-1510ddd6938b.png)

here's the `<td>` with the problematic alignment:

```
<td>
        <input type="checkbox" class="disabled" disabled="true">
</td>
```

here's the `<td>` with good alignment:

```
<td>
        <input type="checkbox" name="batch_document_ids[]" id="batch_document_jm214p18d" value="jm214p18d" class="batch_document_selector" data-hasaccess="true">
</td>
```

**Comment by VivianChu** [comment]
@chrisdaaz - how to create the collections that cannot be selected? I can try that locally. Thanks

**Comment by chrisdaaz** [comment]
@VivianChu just learned that admin sets cannot be deleted if they have works in them. to test locally, you would need to create an admin set, add works to the admin set, then go to the dashboard/collection view to see this alignment issue.

**Comment by VivianChu** [comment]
@chrisdaaz - I was able to see the alignment issue after adding admin sets and works .  What should I do?  Fix the alignment issue and put back the change for select all dropdown?  Thanks

**Comment by chrisdaaz** [comment]
@VivianChu yes, that would be great. thank you!

**Comment by VivianChu** [comment]
@chrisdaaz - The alignment issue has been fixed and the select all dropdown has been added for my branch.  Here's the screen shot. 
![afteralignmentfix](https://user-images.githubusercontent.com/1864660/46171381-30b55900-c255-11e8-9aeb-6af07d6b996d.png)

**Comment by chrisdaaz** [comment]
@VivianChu i reopened the PR with your newest commit -- thanks so much
