### ISSUE TITLE
Front-end sorting only takes into account objects on page

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#2858]
### Descriptive summary

Throughout the application (e.g. on the Notifications page), we have data tables that support sorting. Some behavioral problems with that sorting were fixed in #2741, but they still take into account only the objects actually loaded into the tables. Sorting, e.g. notifications by date , sorts the 10 objects loaded onto the page, but does not provide the most/least recent notifications system wide.

### Rationale

Users expect sorting to take into account all of the relevant objects.

### Expected behavior

Notifications (and other sorting tables) should display the appropriate objects in the requested order. New objects should display on the page when the sort order changes.

### Actual behavior

Notifications (and other sorting tables) display only the objects already on the page.

### Steps to reproduce the behavior

1. Generate more than 10 notifications for a user
1. Log in as the user
1. Visit `/notifications`
1. Take note of which notifications are displayed
1. Click the sort icon to the right of the `Date` column to change the order
1. Observe that the same 10 notifications display as before

### Related work

Related to #1653; #2741.

**Comment by rjkati** [comment]
Unable to replicate in Hyrax 3.0.0 rc3 in either Chrome 87.0.4280.141 or Firefox 85.0 @jlhardes

**Comment by jlhardes** [comment]
Thanks @rjkati! Closing this issue.
