### ISSUE TITLE
Add a read-only mode flipper

### ISSUE THREAD

**Issue by bess** [samvera/hyrax#2877]
### Descriptive summary
Add a FlipFlop feature flipper to allow the system to be put into read-only mode. While in read-only mode, no changes can be made. No new works can be deposited, no workflow changes can be made, etc. 

### Rationale

It is difficult and dangerous to perform large scale data migrations or imports live on a production repository. It would be much better if we could put the production system into read-only mode, take a snapshot, migrate on the snapshot, and then replace the production system. 

### Related work

Penn State has a feature like this which they rely on heavily for production migrations. Here is an example of a feature like this in a Hyrax 1 application: https://github.com/curationexperts/laevigata/pull/945/files

**Comment by decimalator** [comment]
this would definitely be beneficial when, like now, I am needing to migrate a Fedora repository that Hyrax relies upon.

**Comment by jlhardes** [comment]
After some discussion on Slack #hyrax, there might be local work that can be contributed back for this issue.

https://github.com/curationexperts/laevigata/pull/945/files at DCE and https://github.com/UNC-Libraries/hy-c/commit/397923a53afcd099cb21b9087fdd40376bafebdc at UNC Libraries were both mentioned. @lfarrell knows the UNC work is compatible with 2.x, at least (not sure about 3.x).

**Comment by lfarrell** [comment]
#5159 I've gone ahead and opened a PR to add this to 3.x. If we get it merged there we can think about back porting it to 2.x

**Comment by MPLSFedResearchTZ** [comment]
In the ready-only mode, maybe we should disable the Edit button on the work display page?
![image](https://user-images.githubusercontent.com/93392603/140810023-08d668ab-1c6c-4cc7-b69a-dd621d8d1c08.png)

**Comment by MPLSFedResearchTZ** [comment]
Under ready-only mode, after I click the Edit option of work dropdown menu in the work list page, I got the page below. Maybe just show one warning message?
![image](https://user-images.githubusercontent.com/93392603/140810355-9a59a840-7c87-43ae-b3bd-19b1abddbf4b.png)

**Comment by jlhardes** [comment]
QA on nurax-dev and locally verifies that this is working as expected.
