### ISSUE TITLE
Non-admin cannot select single membership collection when editing work

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2880]
### Descriptive summary

A non-admin user cannot select a single membership collection when creating/editing a work.  Selecting a single membership collection works for an admin user.  It would be good to check other combinations of collection type settings to be sure there isn't some weird behavior for those either. 

### Expected behavior

Searching for a single membership collection by name should show the collection in the list of selectable collections on Relationships tab of the New/Edit form.

### Actual behavior

Searching for a single membership collection by name DOES NOT show the collection in the list of selectable collections on Relationships tab of the New/Edit form.

### Steps to reproduce the behavior

Prereq: As an admin, create a Collection Type with Allow Multi-Membership OFF and allowing all users to create.  Referring to it in the test below as Single Membership.  If this doesn't fail, then turn off all settings for the collection type.

1. Login as non-admin (important as this bug does not appear to exist for admins)
1. Create a collection of the Single Membership type and give it a title like SM Collection
1. Create a work filling in required metadata, file, etc.
1. Before saving (or edit after saving), click the Relationships tab
1. In the search for collection box, start typing the collection's title (e.g. SM Collection)

After a few letters, the single membership collection should appear in a list that can be selected.

**Comment by blancoj** [comment]
@elrayle I could not reproduce this error it worked fine for me.

**Comment by elrayle** [comment]
I can't reproduce either.
