### ISSUE TITLE
Referrer and non-referrer breadcrumb behavior should be the same for all non-logged in users

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2892]
### Descriptive summary

When a user is not logged in, the breadcrumbs that get displayed are different when there is a referrer and not a referrer.  It is not clear to me why this is the case.  The breadcrumbs for works and collections when not logged in should always be `Home -> work's title` and `Home -> collection's title`, respectively.

We should probably look into why it was originally coded with different behavior just to be sure we are not changing something that was intentional.

### Rationale

Consistent breadcrumbs reduces user confusion.

### Expected behavior

As a non-logged in user, navigating to a work and copying the URL for the work into the browser, should have the same breadcrumbs:  `Home -> work's title`

As a non-logged in user, navigating to a collection and copying the URL for the collection into the browser, should have the same breadcrumbs:  `Home -> collection's title`

### Actual behavior

As a non-logged in user, navigating to a work has breadcrumbs: `Home -> work's title`
Copying the URL for the work into the browser has breadcrumbs: `Home`

As a non-logged in user, navigating to a collection has breadcrumbs: `Home -> collection's title`
Copying the URL for the collection into the browser has breadcrumbs: `Home`

### Steps to reproduce the behavior

1. Log out
1. From home page, Recently Uploaded section, click the title of any work

Verify the breadcrumb is `Home -> work's title`

1. Copy the URL for the work and paste it into the browser

Verify the breadcrumb is `Home -> work's title`

1. From home page, Explore Collections section, click the title of any collection

Verify the breadcrumb is `Home -> collection's title`

1. Copy the URL for the collection and paste it into the browser

Verify the breadcrumb is `Home -> collection's title`

### Related work

PR #2878 GenericWorksController: don't show 'Your Works' when logged out
PR #2845 Remove Your pronoun from breadcrumbs
PR #2874 render home breadcrumb with dashboard awareness of user signed in

Note: This will impact the tests in [spec/controllers/hyrax/generic_works_controller_spec.rb](https://github.com/samvera/hyrax/blob/master/spec/controllers/hyrax/generic_works_controller_spec.rb)

**Comment by mcdowney** [comment]
I think this has been addressed; closing for now
