### ISSUE TITLE
Update text on Manage Proxies page to clear up permissions 

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2895]
### Descriptive summary
UPDATED AFTER COMMENTS: 
Update the text on the Manage Proxy page to clear up what happens when you remove a proxy. 
New text should be: 
"Select a user who can deposit works on your behalf. Both you and your proxy will be able to make changes to these works. You can revoke a proxy by clicking the Delete Proxy button. To revoke their ability to edit a work they previously submitted, remove them from the Sharing tab on each work."

Some discussion here: https://github.com/curationexperts/nurax/issues/248

Rationale:
Because it's not clear that you have to edit individual works to remove edit access when you remove a proxy.

This page: 
![screen shot 2018-04-05 at 12 18 54 pm](https://user-images.githubusercontent.com/4356335/38378409-9699c1ca-38cb-11e8-88fe-eceace1e67a7.png)

**Comment by newmanld** [comment]
I think the proposed text is an improvement.  +1 . 

IF there's still room for suggestions, then I would want to make it clear to people (if this is still true) that their proxy can edit works that they deposited, although that is implied by the explanation that they have to remove the proxy on the Sharing Tab.  Suggest:

"Select a user who can deposit works on your behalf.  Both you and your proxy will be able to make changes to these works.  You can revoke a proxy by clicking the Delete Proxy button.  To revoke their ability to edit a work they previously submitted, remove them from the Sharing tab for each work."

An obvious suggestion for future enhancement would be to provide owners with an choice when removing a proxy to also remove proxies as editors of pre-existing works.  If this has either been discussed and turned down, or is already written up as an enhancement request on a separate issue, could someone comment?

**Comment by ggeisler** [comment]
I like @newmanld's text modification. Was going to suggest something very similar.

**Comment by julesies** [comment]
@ggeisler and @newmanld thanks, i'll edit the top with the text that Linda provided so it's clear to the person working on the ticket.

**Comment by julesies** [comment]
@newmanld i agree that is the desired behavior. I have no idea if it's been written up, but think it should be :)

**Comment by vantuyls** [comment]
I agree to the text originally proposed and discussed here. 

I've changed the title of this issue to reflect that this is no longer a proposal, but something to take action on.
