### ISSUE TITLE
Universal Viewer does not show new file version

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2910]
There are lots of comments in the nurax ticket about how to solve this problem please see the comments:  https://github.com/curationexperts/nurax/issues/253

### Descriptive summary

Reporting for
Testing for Hyrax 2.1.0 beta 2
Browser: Chrome 65.0.3325.181 (32-bit)

Descriptive Summary
Example: https://nurax.curationexperts.com/concern/generic_works/db78tc05q?locale=en#?c=0&m=0&s=0&cv=0&xywh=-319%2C-3%2C1273%2C438

I have created a public work and attached an image (rubber duck in the linked example). I would like to upload a new version of the image. I click on the image title in the "Items" section, then "Edit this image", then the Versions tab to upload a new version. After uploading a new version (Old well in the linked example), I navigate back to the Work page. The Universal Viewer still displays the old image. The thumbnail in the Items section displays the new image. I can download the new image.

**Comment by dlpierce** [comment]
I've got some still WIP code that adds "fcr:versions/version{n}" to the URI in the manifest and ultimately fetched by riiif. I hit a snag with the specs and encoding of the colon, but have found the issue (the ActionDispatch and CGI modules have different end results) so this should be very close to done.

**Comment by orangewolf** [comment]
This is a much better solution than my cache busting code. @geekscruff @dlpierce anything I can do the help get this over the line?

**Comment by dlpierce** [comment]
@orangewolf  There was a concern with including version info in the public URI. I've been working on an enhancement to riiif to allow it to recognize additional image information, such as a timestamp, and use that to improve the browser caching strategy (conditional get instead of fixed 1 year).

Aside from that, the actor stack should be checked that it correctly indexes the new file version, especially the characterization metadata.

**Comment by orangewolf** [comment]
@dlpierce the indexing seems correct to me, but in our experience you have 4 layers of caching problem:

1) caching on disk to tmp/network_files
2) Rails caching 
3) Browser caching
4) Cloud based caching with things like Cloudflare

It sounds like your proposed solution fixes (3), though URI change would fix all 4 in one go. I saw the PR comments, and I wonder if it would be better to add something in the URI that is uniqish but is not a use readable version number?

**Comment by dlim87** [comment]
I did a QA check on this and it mostly seems to be working. Editing a file with a new version generally replaced it in the viewer and the thumbnail.

There was one edgecase though: when updated with a file type that isn't renderable in the UV (a svg in this case), it displayed the expected empty "No preview available/download this file" prompt in the place of the viewer, but was still showing a thumbnail of the last version

**Comment by jeremyf** [comment]
I've reported the edge case (see #4521), and am closing this issue.
