### ISSUE TITLE
CollectionsMembershipActor with Hyrax2 attributes

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#2918]
### Descriptive summary

While `member_of_collection_ids` could be passed in with a blank string, creating a new work produces an error `No ID provided for Collection.` See https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/collections_membership_actor.rb#L78

### Rationale

For version 2.1.0 I think we should have a fix in place to handle the circumstance where the soon to be deprecated `member_of_collection_ids` parameter is a blank string. 

I think a good fix would be in the `#assign_for_collection_ids` method in the actor class:

```
unless collection_ids.blank?
  Deprecation.warn(self, ':member_of_collection_ids has been deprecated for removal in Hyrax 3.0. ' \
                                          'use :member_of_collections_attributes instead.')
```

**Comment by no-reply** [comment]
If the suggested patch passes the existing tests, I think I'd be :+1:.

My sense is that this could easily be slotted into a 2.1.1 or later. @revgum is there something you are seeing or aware of that makes this feel more pressing?

**Comment by revgum** [comment]
@no-reply I'm testing a migration from Hyrax 2.0.0 to 2.1.0 and this is a breaking bug that prevents saving any works.

**Comment by elrayle** [comment]
The fix may be as simple as changing the test on the line to...
```
if collection_ids.present?
```
which will not be true for `[]`

**Comment by no-reply** [comment]
I think that should work.

We should get a regression test in, as well.

If no one else picks this up today, I'll self assign as travel work for the weekend.
