### ISSUE TITLE
New collection modals open incorrect URL

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#2927]
### Descriptive summary

My instance **was not maintaining `?locale=en` between requests**, and so trying to create a new collection failed to load the new collection page. Browser is sent to an improperly structured url like `/dashboard/collections/new&collection_type_id=1`. 

The html rendered for the collection_type radio button is: `<input type="radio" name="collection_type" data-path="/dashboard/collections/new&collection_type_id=1">`

Bugs found in: https://github.com/samvera/hyrax/blob/ca0766b3cc1b83859ce1b08d7cafbda18be07c84/app/views/hyrax/my/collections/_modal_collection_types_to_create.html.erb#L19 
and:
https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections/index.html.erb#L36

## Steps to reproduce

- From the dashboard, click 'New Collection' 
- Select one of the collection types (non AdminSet)
- Click 'Create Collection'.
- Browser tries to load `/dashboard/collections/new&collection_type_id=1`

### Rationale

Browser would be redirected to a 404

**Comment by laritakr** [comment]
This works correctly in hyrax & nurax.
