### ISSUE TITLE
Application template not running Hyrax generator or migrations

### ISSUE THREAD

**Issue by mark-dce** [samvera/hyrax#2933]
### Descriptive summary

I'm using Hyrax v2.1.0.beta2 and following the application generation instructions at https://github.com/samvera/hyrax/tree/master#creating-a-hyrax-based-app.  These use a rails application template to generate the application.

I'm using 
* Ruby 2.3.4
* Rails 5.0.6
* Template: https://raw.githubusercontent.com/samvera/hyrax/v2.1.0.beta2/template.rb

*NOTE:* I feel like I must be missing something obvious and stupid, but I can't figure out what.

### Rationale

Users should be able to successfully use the documentation to start building a new application.

### Expected behavior

The Hyrax generators and migrations run

### Actual behavior

A new application directory is made, hyrax is not added to the gemfile, generators don't run, migrations don't run.

### Steps to reproduce the behavior

```
rails _5.0.6_ new hyrax-demo https://raw.githubusercontent.com/samvera/hyrax/v2.1.0.beta2/template.rb`
cd hyrax-demo
cat Gemfile | grep hyrax
#nothing
ls config/initializers/hyrax.rb
# ls: config/initializers/hyrax.rb: No such file or directory
```

### Related work

Link to related tickets or prior related work here.

**Comment by mark-dce** [comment]
@no-reply @mjgiarlo can you take a look at this and see if you can get an app to generate.  I'm kinda stuck trying to get the rest of Samvera Camp stuff done... I'm sad to admit I've been banging my head against this for a day and a half.  I've tried with Ruby versions 2.3.4, 2.4.2, and 2.4.4 and Rails versions 5.0.6 (in readme) and 5.1.6.  Nurax appears to be running on Ruby 2.3.4 and Rails 5.1.6.

**Comment by mark-dce** [comment]
If I try to run the commands manually, it looks like there's no hyrax generator defined:

```
Marks-MacBook-Pro-2:hyrax-demo mark$ rails generate 'hyrax:install', '-f'
Running via Spring preloader in process 2294
Could not find generator 'hyrax:install,'. Maybe you meant 'hyrax:install', 'qa:install' or 'hyrax:clamav'
Run `rails generate --help` for more options.
Marks-MacBook-Pro-2:hyrax-demo mark$ 
```

**Comment by mark-dce** [comment]
Ok, my bad, I was reading the template file and included the quotes around 'hyrax:install' inadvertently.  This works, but I still can't figure out why the template doesn't run the same thing:

```
rails generate hyrax:install -f
```

**Comment by mjgiarlo** [comment]
@mark-dce you're missing the `-m` flag on the `rails new` command.

**Comment by mark-dce** [comment]
@mjgiarlo - thanks! - not sure how I did that multiple times, but " I must be missing something obvious and stupid"
