### ISSUE TITLE
Verification of groups not happening for adding participants/sharing

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2937]
### Descriptive summary

A user can add any group name whether or not it exists for Collection Types, Collections, and Admin Sets.  This error existed for Hyrax 2.0 as well.  New/Edit works operates different using a selection list of all groups instead of having the user type in the group name.

### Rationale

Users should not be able to add non-existent groups.

### Expected behavior

Adding a non-existent group name should not be allowed and at least show a flash message stating the name doesn't exist.

### Actual behavior

Adding a non-existent group name is allowed and the non-existent group is added to the roles table.

### Steps to reproduce the behavior

1. Dashboard -> Collections -> edit a collection -> Sharing tab
1. Type in group name 'Junk', select a role, and click Add

Verify that you get a flash message stating that "Junk group does not exist."
Verify for Collections, Collection Types, and Admin Sets.

As an alternative, the change could be made to match that used for works sharing tab, which uses a selection list of existing groups.

### Related work

Issue #2921 - empty user field allowed when adding sharing

**Comment by elrayle** [comment]
Per discussions in Slack, it was decided not to fix this issue. Hyrax is designed to work with any of a number of group systems including but not limited to LDAP, Shibboleth, Groupify, RoleMapper, etc. Some of these include predefined groups and can have large numbers of groups defined making getting all groups return an unwieldy number of groups.

There is an effort to rework groups and authentication. It is anticipated this UI will be improved through better API access to groups when that work is complete.

@vantuyls If you concur, can you close this issue and corresponding PR #2954?

**Comment by rjkati** [comment]
@jlhardes looks like there was a previous decision to close this ticket. See comments.

**Comment by jlhardes** [comment]
Agreed, the PR was closed but this issue was never closed. Closing now.
