### ISSUE TITLE
Refactor tests using collections and admin sets to use light weight factories

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2940]
### Descriptive summary

New factories that avoid fedora access unless necessary were created for collections and admin sets.  Parts can be created as needed, including permission template, solr doc, nested indexing, and the actual fedora object.  All tests that use collections and admin sets should use the lighter weight factories.  

Tests can be updated and committed a few at a time.  When the last test is updated, the old factories can be removed.

There are lots of examples in the light weight factories for building/creating collections and admin sets.  The basic build is...

```
build(:collection_lw)
build(:adminset_lw)
```

See factories for more examples...
* [spec/factories/collections.rb](https://github.com/samvera/hyrax/blob/master/spec/factories/collections.rb)
* [spec/factories/admin_sets_lw.rb](https://github.com/samvera/hyrax/blob/master/spec/factories/admin_sets_lw.rb)

### Rationale

Avoid accessing Fedora in tests as it is very slow.

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
Closing this. I don't think it's worth focused effort to complete this work in light of Wings/Valkyrie.
