### ISSUE TITLE
Displaying of a parent work(s) in hyrax is broken.

### ISSUE THREAD

**Issue by straleyb** [samvera/hyrax#2960]
It seems like this works in sufia 7.x but not in the current master in hyrax. Nurax doesn't show this as well, so im taking that as good proof that this feature is broken.

**Comment by vantuyls** [comment]
Can we get confirmation from someone that this isnt expected behavior and that this is truly a bug? @no_reply

**Comment by laritakr** [comment]
This may be related to the fix to show parent collections of works on the works show page: https://github.com/samvera/hyrax/pull/2789

**Comment by elrayle** [comment]
@straleyb Can you post a screen shot of this in sufia 7.x?

**Comment by elrayle** [comment]
### Hyrax 2.0...
Same as for 1.0:
* child work is in the list of items in the parent, but there is nothing that distinguishes an uploaded file from a child work
* parent is not displayed in the child, but I would have expected it in the Relationships section

![image](https://user-images.githubusercontent.com/6855473/39322382-b594e220-4957-11e8-807b-32484e30d8c4.png)

**Comment by julesies** [comment]
@elrayle what about for the edit view, can you add a parent work from a child?

**Comment by no-reply** [comment]
Closing this as working as designed.
