### ISSUE TITLE
UV showing with video marked as representative media

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2965]
Moved from: https://github.com/curationexperts/nurax/issues/273

**Descriptive summary**
For the UV to show, the representative media should be an image file. However this work's rep media is a video file. See https://nurax.curationexperts.com/concern/images/r494vk17h (also the URL changes when you click on it?).

Expected behavior: UV doesn't show but the video selected does.
Related: 
https://github.com/curationexperts/nurax/issues/272

to reproduce:
1. Create a work with multiple files. images and video
2. set the representative (in the description tab AFTER SAVE) file to the video
3. view the work
4. UV shows, it shouldn't.

**Comment by hortongn** [comment]
Here is the discussion on a previous issue that I think led to the UV being shown on works where the representative file is not an image: https://github.com/samvera/hyrax/issues/2802#issuecomment-376190608

And this is where that change happened:
https://github.com/samvera/hyrax/pull/2846/files#diff-cd3c371abc5c4eafc5a0bbb1c4039539

**Comment by julesies** [comment]
@hortongn ah I see. I believe the meaning here is the "visibility status" not the file type status. So the comment right under clarifies when it should show (i think). Can you let me know how you read that?

**Comment by julesies** [comment]
I'm thinking the representative media should always be shown at the top of the work view.... do people agree? cc @vantuyls  

use case: PDF paper with supplemental image files. You want the PDF to show at the top.

**Comment by vantuyls** [comment]
Agree with @julesies

**Comment by cjcolvar** [comment]
Looks like this was my fault from the comment that @hortongn linked.  I'm glad we're fixing it!

**Comment by cjcolvar** [comment]
@hortongn Do you have cycles and want to make the fix?  If not, I can pick it up.

**Comment by hortongn** [comment]
@cjcolvar I'll hop on this fix right now.  Thanks!

**Comment by elrayle** [comment]
Fixed by PR #2971.  Closing.
