### ISSUE TITLE
Collection count on /dashboard/collections page is wrong

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#2974]
### Descriptive summary

As a logged in user, on the collections page, there is text that says how many collections are "in the repository". This text actually only shows the up to the number of collections on the page and only the number of the collections the user has access to. 

### Rationale

It seems that the purpose of this text is to show users how many collections are in the repository. 

### Expected behavior

The number should reflect the number of collections in the repository.

### Actual behavior

(Admin) Displays number of collections on the page: 
![image](https://user-images.githubusercontent.com/24395592/39372804-14ef8744-4a0b-11e8-9e22-4a79ac9f2503.png)

(Admin) Changes when you change the number:
![image](https://user-images.githubusercontent.com/24395592/39372838-3373a70e-4a0b-11e8-8a1e-454819904c82.png)

(User) Only the collection the user has edit access to:
![image](https://user-images.githubusercontent.com/24395592/39373050-f5bee4ae-4a0b-11e8-826e-a0c446a576a6.png)

### Steps to reproduce the behavior

1. Dashboard- > Collections
2. Try to determine how many collections are in the repository

### Related work

moved from https://github.com/curationexperts/nurax/issues/275

**Comment by elrayle** [comment]
I checked out Dashboard -> Works to see how it handles count.  It doesn't display count at all.  

OPTION 1: Remove the display of count for Dashboard -> Collections.
OPTION 2: Fix display of count for Dashboard -> Collections
  OPTION 2a:  Add an issue to add count to Dashboard -> Works for 2.1.1
  OPTION 2b:  Do no plan to add count to Dashboard -> Works  

@vantuyls @no-reply Your thoughts?

**Comment by vantuyls** [comment]
I'd remove the counts for now (Option 1) and put an issue in to for Option 2b as @elrayle suggested.

**Comment by elrayle** [comment]
We are going with Option 2b.  See issues targeted for 2.1.1...
* Issue #2996 Adjust wording for count of collections on Dashboard -> Collections
* Issue #2987 Show count of works on Dashboard -> Works
