### ISSUE TITLE
Home page tabs should use expanded and collapsed states instead of selected

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#2978]
### Descriptive summary

Results from the Accessibility360 audit report noted the following as a "critical" issue of "medium" complexity:

> Home page: "Featured Works," "Recently Uploaded," "Explore Collections," and "Featured Reasearcher" tabs.
> 
> These tabs function properly but should use "expanded" and "collapsed" rather than "selected."
>
> Recommended fix: Mark these up properly as tabs. Example code can be provided upon request.

### Rationale

Accessibility concern.

### Expected behavior

Tabs exhibit expand/collapse behavior instead of selected behavior.

### Steps to reproduce the behavior

Go to a Hyrax homepage, or Nurax https://nurax.curationexperts.com/

![accessibility-home-page-tabs](https://user-images.githubusercontent.com/3020266/39430604-e3d7ac0e-4c53-11e8-8569-28c097ee6793.png)

### Related work

Link to related tickets or prior related work here.

**Comment by laritakr** [comment]
@adamjarling When I look at the code, `Explore Collections` and `Featured Researcher` already use aria-expanded. (`Featured Works` and `Recently Uploaded` do not). Should these be handled some other way than they currently are? I'm not sure what is being requested here.

**Comment by adamjarling** [comment]
@laritakr Looks like the ticket info and recommended fix are pretty direct from the Accessibility 360 report.  I'll see if I can clarify it a bit given what's currently in the code and get back to you.

**Comment by adamjarling** [comment]
@laritakr Yea, I'm seeing the `aria-expanded` on all 4 of the anchor elements referenced.  On the `<a>` tag. And it looks like proper implementation of Bootstrap nav pills.  I'd mark this as "will not complete".  Seems it's fine.
