### ISSUE TITLE
Show count of works on Dashboard -> Works

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2987]
### Descriptive summary

Collections show how many collections the user has access to on a given tab in Dashboard -> Collections.  This issue proposes adding a similar count for works on Dashboard -> Works.

### Rationale

Provide similar UI experience for collections and works.

### Expected behavior

On Dashboard -> Works -> Your Works, the count of the number of works should use the wording:  `'X works you own in the repository'`, replacing X with the actual count.

On Dashboard -> Works -> Managed Works, the count of the number of works should use the wording:  `'X works you can manage in the repository'`, replacing X with the actual count.

On Dashboard -> Works -> All Works, the count of the number of works should use the wording:  `'X works in the repository'`, replacing X with the actual count.

_NOTE: In all cases, 'X works' should be bold and the remainder of the text normal._

### Actual behavior

There are no counts on any of the Dashboard -> Works tabs.

### Steps to reproduce the behavior

1. Create 13 works as an admin user and 12 works as a non-admin user.
1. Share 11 of the works created by the admin with the non-admin user.  (any role)

NOTE: The count of works for each condition should be `> page_size`.

1. Login as the admin user
1. visit Dashboard -> Works -> Your Works

Verify that just under the tabs, there is a message `'13 works you own in the repository'`

1. visit Dashboard -> Works -> All Works

Verify that just under the tabs, there is a message `'25 works in the repository'`

1. Login as the non-admin user
1. visit Dashboard -> Works -> Your Works

Verify that just under the tabs, there is a message `'12 works you own in the repository'`

1. visit Dashboard -> Works -> Managed Works

Verify that just under the tabs, there is a message `'11 works you can manage in the repository'`

### Related work

PR #2981 Display count of collections on Dashboard -> Collections
Issue #2996 Adjust wording for count of collections on Dashboard -> Collections

**Comment by elrayle** [comment]
As I wrote this, I was wondering whether we could display a better message for works and for collections.  `'in the repository'` implies to me that the count is the total number of works regardless of which tab you are on.

@ggeisler Do you have a recommendation of language to use for each tab?  Perhaps something like...

All tab - `'36 works in the repository'`
Your tab - `'8 works you own in the repository'`
Managed tab = `'3 works you can manage in the repository'`

**Comment by ggeisler** [comment]
@elrayle Can you post a screenshot of how the Dashboard > Collections currently looks, so I have some context for the wording suggestions? (I don't easy access to a realistic version of the app and it takes a while to dig through all my past mockups to find ones relevant to what you're asking about.)

**Comment by elrayle** [comment]
@ggeisler Here are screen shots from the current implementation of Dashboard -> Collections.

![image](https://user-images.githubusercontent.com/6855473/39444203-f7349952-4c84-11e8-80f5-0b2fd3cd91c6.png)

**Comment by ggeisler** [comment]
Thanks @elrayle. Yes, I think your suggested wording for the Works tabs makes sense. This might be obvious already, but to follow the pattern on the Collections tabs, I'd bold everything except the "in the repository" part at the end of each string.
