### ISSUE TITLE
When deleting a collection display title instead of collection ID

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#2997]
https://github.com/curationexperts/nurax/issues/271

### Descriptive summary
Currently, when deleting a collection a user sees the following flash notice:

* _Collection 41687h57c was successfully deleted_

### Recommended Improvement

Show the collection title instead since a collection ID isn't very helpful

* _How the Cat Tamed the Dog was successfully deleted_

### Steps to reproduce the behavior
Delete via Collection's show page:
* Select Collection to delete
* Click on Delete collection
* Delete this collection?
* Click on OK
* Collection 41687h57c was successfully deleted
------------------
Delete via listing of all collections using Action option:
* Go to list of Collections
* Identify collection for deletion
* Select Delete Collection from Actions
* Are you sure you want to delete this collection? This action cannot be undone
* Click Delete
* Collection dz010q15f was successfully deleted

**Comment by no-reply** [comment]
Closed by #3001; backported in #3021
