### ISSUE TITLE
Ensure GeoConcerns may be plugged in

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#3]
Work with the HPWG and the GeoConcerns community to ensure GeoConcerns may be plugged into Hyrax.

**Comment by elrayle** [comment]
@mjgiarlo This is marked as a blocker and on backlog.  Is this a blocker for 2.1.0?

**Comment by mjgiarlo** [comment]
Not a blocker. In fact, I'm going to close this issue. Thanks!
