### ISSUE TITLE
Long FileSet's title overflows in FileSet show view

### ISSUE THREAD

**Issue by jayanthdeejay** [samvera/hyrax#3006]
### Descriptive summary

When a file with long name is attached to a work, file set title overflows.

### Actual behavior
<img width="752" alt="screen shot 2018-05-02 at 4 35 46 pm" src="https://user-images.githubusercontent.com/2188493/39547946-0e8b6394-4e27-11e8-8431-da5ac0d0278f.png">

### Related work

https://nurax.curationexperts.com/concern/parent/s1784k80t/file_sets/qn59q406w

**Comment by blancoj** [comment]
@jayanthdeejay can you check if this is an issue.  I can't duplicate it.  If it is not, please close the issue.
