### ISSUE TITLE
Don't set batch= in BatchEditsController spec

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#303]
It seems this avoids testing a bunch of critical logic. 

spec/controllers/batch_edits_controller_spec.rb

**Comment by atz** [comment]
Link: https://github.com/projecthydra-labs/hyrax/blob/d254b74349532c9b8a99c2661dc83dafdd3413d4/spec/controllers/hyrax/batch_edits_controller_spec.rb#L41-L42

**Comment by no-reply** [comment]
closed. i think the batch tests are pretty shoddy all around, and maybe this particular smell isn't worth a ticket 3 years on.
