### ISSUE TITLE
Reindex_everything with nested collections

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#3037]
Has 'reindex_everything' been tested with the new nested collections?

I had reason to drop and reindex a fairly small solr index and saw two issues

1) The following error for each 'work' - updating the index for the failing work and re-running reindex_everything worked for this (although I had to do this for each work after the error, I couldn't simply update the index for each work to begin with so it's definitely not scalable):

```
#<RuntimeError: Unable to find SolrDocument with ID=x059c736d>
Samvera::NestingIndexer::Exceptions::ReindexingError: ReindexingError on ID="x059c736d"
        Unable to find SolrDocument with ID=x059c736d
```

2) My Nested collections are not there at all now, just the top level. 

Running reindex_everything on an existing solr index works fine, but running it with an empty solr document doesn't.

It appears that this is the expected behaviour from this test, but it prevents rebuilding solr so seems like a blocker to me:
https://github.com/samvera/hyrax/blob/master/spec/services/hyrax/adapters/nesting_index_adapter_spec.rb#L44

**Comment by elrayle** [comment]
@laritakr ⬆️

**Comment by elrayle** [comment]
@geekscruff Did you have any nested collections prior to running `reindex_everything`?

**Comment by geekscruff** [comment]
@elrayle yes, I'd created an org structure and everything bar the top level disappeared

**Comment by geekscruff** [comment]
@elrayle I changed solr version (hence needing to run the reindex to create a new solr index) so there's a possibility it's my issue. I wonder if someone else could test it? I can do more testing too.

**Comment by laritakr** [comment]
@elrayle Ok I'm on it. The nesting indexer rebuilds the index one document at a time, so there may be an issue if you drop the full index before you begin. I'll do some digging to try to see if I can recreate the problem so I can figure out what's happening.
