### ISSUE TITLE
Fix randomly failing feature tests associated with select_member_of_collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3038]
### Descriptive summary

A number of feature tests are randomly failing since the addition of `select_member_of_collection` feature which uses jquery select2 to search for a collection by name.

### Expected behavior

REMOVE optional line from each test...
```
      optional 'ability to get capybara to find css select2-result (see Issue #3038)' if ENV['TRAVIS']
```

All tests in spec/features/collection_multi_membership_spec.rb and spec/features/work_show_spec.rb pass consistently when the optional line is removed from the tests.

### Actual behavior

6 tests in collection_multi_membership_spec.rb and 1 in spec/features/work_show_spec.rb (all marked optional for Travis) randomly fail when running in Travis.

NOTE: These tests pass locally and only fail on Travis.  They are currently marked optional.  The goal of this Issue is to remove the optional statement and have them run without failures in Travis.

The error occurs on the `select_member_of_collection` line which calls the method in spec/support/selectors/rb.  The failing line in that method is the attempt to click `collection.title.first` within `select2-result`.

Attempts to fix included...
* adding `expect(page).to have_css('.select2-result') which causes some wait time through Malificient
* adding sleep time
* changing the expect to look for `select2-results-label` instead of `select2-result`

There are similar tests that use `select_collection` also defined in spec/support/selectors.rb that pass consistently.

### Related work

PR #3027 Change radio buttons into autocomplete field for add works to collection modal

**Comment by jrgriffiniii** [comment]
https://circleci.com/gh/jrgriffiniii/hyrax/17 is queued to run a possible solution to this.  If this works, I can merge this into https://github.com/samvera/hyrax/pull/3493
