### ISSUE TITLE
Collections/Works tabs - accessibility improvements for screen readers

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#3042]
### Descriptive summary

From the Accessibility 360 Audit Report:

"All Collections" and "Your Collections" tabs
These act similarly to tabs but are not marked up as such.
Mark these up as tabs. Sample code can be provided upon request to assist in remediation.

![collections-tabs](https://user-images.githubusercontent.com/3020266/39712789-fae097f8-51e9-11e8-9706-ac67c93f0a00.png)

![works-tabs](https://user-images.githubusercontent.com/3020266/39713885-ef90f4a2-51ed-11e8-8f9b-b113f4491624.png)

### Rationale

Accessibility update for screen readers.

### Tasks
- [ ] Mark these "tabs" up as accessible tabs which work for screen readers.
- [ ] Review best practices on how to implement marking up as tabs.  Perhaps something along the reasoning/lines of this article?  (http://simplyaccessible.com/article/danger-aria-tabs/)

**Comment by kdid** [comment]
@adamjarling are we sure this applies here?

These aren't really tabs in the sense that there is hidden content on the page.
These are links to two different pages of results with a full page load fetching different results for each link.

"Your Works" links to /dashboard/my/works 
"Works" links to /dashboard/works

**Comment by kdid** [comment]
Closing as these aren't really tabs in the sense that there is hidden content on the page.
These are links to two different pages of results with a full page load fetching different results for each link.
