### ISSUE TITLE
Viewer of Admin Set should be able to see a work in any state

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3065]
### Descriptive summary

Right now a viewer for an admin set with a 1-step workflow can NOT view works that have not been approved.

### Rationale

Viewer should always be able to see the work in the admin set for which they are designated a viewer. 

### Steps to reproduce the behavior

To test viewer access to unapproved works in mediated deposit workflow:

1. Create an admin set with 1 -step mediated deposit.
2. using 3 different test accounts, add 1 account to viewer, 2nd to manager, add registered users as depositor. use the 3rd account as registered user.
3. Log in as 3rd account, deposit a work to that admin set
4. Log in as 2nd account, verify the work is there, but do not approve. Grab the url to the work
5. Log in as 1st user, go to URL, verify if you can or can’t see the work.

If you then need to test viewer role after the work has been approved? if so

1. Log back in as manager, approve work, grab URL
2. Log in as viewer, go to URL

### Related work

Link to related tickets or prior related work here.
Will be testing this to see if https://github.com/samvera/hyrax/pull/3056 fixes it.

**Comment by elrayle** [comment]
Dup of Issue #3069 which has additional information, so keeping it instead.
