### ISSUE TITLE
Collections: You can't access the Branding, Discovery, or Sharing tabs until you've already created the collection

### ISSUE THREAD

**Issue by sandbergja** [samvera/hyrax#3107]
### Descriptive summary

A UX issue from one of our student workers: when you create a new collection, only one tab is visible (the Description tab).  After the collection is added, you can edit it, which brings up the Branding, Discovery, and Sharing tabs.

This leads to a roundabout workflow for users who generally create public (or otherwise non-private) collections.  Note that this workflow is not consistent with the work creation workflow, where you can set visibility right away and access all the tabs you want before creating a Work.

### Rationale

Creating a public collection is more steps than the user might expect.

### Expected workflow

1. Go to Collections > New Collection.
2. Choose the type of collection you'd like to create.
3. Fill in the required metadata.
4. Choose visibility settings.
5. Click save.

### Actual workflow

To create a public collection on nurax on 2.1.0.rc3:

1. Go to Collections > New Collection.
2. Choose the type of collection you'd like to create.
3. Fill in the required metadata.
4. Click save.
5. Go to the Discovery tab and choose your visibility setting.

**Comment by elrayle** [comment]
NOTE that this is not just a matter of making the Collection new/edit UI match the Work new/edit UI.  One of the reasons for delaying display of the tabs is that in some cases, the collection needs to exist before certain actions can be taken.  Most notably, before uploading branding files and before attempting to share the collection with others.  Nesting would also require the collection exist, but nesting is established from the collection show page after it exists.

**Comment by mcdowney** [comment]
Closing for now with reference to elrayle's comment above.
