### ISSUE TITLE
undefined method `trophies' for nil:NilClass

### ISSUE THREAD

**Issue by rodyoukai** [samvera/hyrax#3120]
Hi, I have this error when try enter to my profile page, this is the trace:

https://gist.github.com/rodyoukai/8296d1dd8d9e5573100962275cc54a28

**Comment by RudyOnRails** [comment]
I would try and put a byebug in [here](https://github.com/samvera/hyrax/blob/87db60024378b8af316266ba374e1523e3a7b0b5/app/controllers/hyrax/dashboard/profiles_controller.rb#L14) and see what's up with the instance variable, because `@presenter` is nil in the views...

**Comment by rodyoukai** [comment]
I solved, 

this line:       	@presenter = Hyrax::UserProfilePresenter.new(@user, current_ability)

was not in **app/controllers/hyrax/dashboard/profile_controller.rb**

And the file **app/views/layouts/hyrax/dashboard.html.erb** must be on **app/views/layouts/dashboard.html.erb**
