### ISSUE TITLE
Create of new hyrax 2.1.0 app breaks due to lack of javascript runtime

### ISSUE THREAD

**Issue by kerchner** [samvera/hyrax#3126]
### Descriptive summary

Running
`rails _5.1.6_ new mynewhyraxapp -m https://raw.githubusercontent.com/samvera/hyrax/v2.1.0/template.rb`

results in an incomplete app.  Several of the tasks invoked, such as `generate    hyrax:install` result in `Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.`

### A workaround

A workaround is to:
1. accept the partial install
2. edit the new app's Gemfile, and uncomment `gem 'therubyracer'`
3. re-run `rails _5.1.6_ new mynewhyraxapp -m https://raw.githubusercontent.com/samvera/hyrax/v2.1.0/template.rb`.  You'll be prompted whether to overwrite the `Gemfile` - respond with **`n`** (no).  I suppose the subsequent overwrite prompts can be accepted (or not).

**Comment by jcoyne** [comment]
I prefer to install `nodejs` on the system rather than `therubyracer`

**Comment by kerchner** [comment]
I suppose the issue, then, is that I should have followed the `JavaScript runtime` section of the README more closely, to install nodejs on my system (Ubuntu Linux) first.   Closing the issue.
