### ISSUE TITLE
Failing Build

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#3146]
### Descriptive summary

The Hyrax build is failing with various style issues.

We should be protected from upstream RuboCop rule changes, so I'm not sure why we suddenly have style violations all over on `master`.

**Comment by jcoyne** [comment]
https://github.com/rubocop-hq/rubocop/commit/e41a2d5bd5b33cba1219e0f798397fac9b8fe543

**Comment by no-reply** [comment]
This might be fixed by release of `parser` v2.5.1.2.
