### ISSUE TITLE
URL and title visible for works not yet approved in mediated deposit

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3168]
### Descriptive summary

Hyrax 2.1. We found this locally and confirmed on nurax. Works in mediated deposit, that are not yet approved are accessible via URL, but only the title shows. here's an example https://nurax.curationexperts.com/concern/generic_works/mc87pq36b?locale=en

I'm remembering that we talked about this and did not expect the work title to be available at all. You can not search for the work but you can access via URL

**Comment by cjcolvar** [comment]
I believe this was previously reported as https://github.com/samvera/hyrax/issues/3104 and fixed with https://github.com/samvera/hyrax/pull/3148.

**Comment by julesies** [comment]
@cjcolvar perfect! closing
