### ISSUE TITLE
Feature/unfeature buttons don't work when there are five works already featured

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3169]
### Descriptive summary

In 2.1 Hyrax, the feature/unfeature button at some point splits into 2 buttons (supposed to be one) and then stops working entirely. I can't find a good way to reproduce this with steps consistently, but try going to a work and feature and unfeature it, go back to the home page and back to the work. 

We think it might be if you hit 5 featured works, then it breaks. 

here is a screenshot from nurax.

![screen shot 2018-07-25 at 1 35 23 pm](https://user-images.githubusercontent.com/4356335/43217335-55f522c2-900f-11e8-9d86-a71c1cca1c58.png)

### Done when

Users no longer have the option to feature works when there are already five works features on the home page (?). Open to other suggestions.

**Comment by chrisdaaz** [comment]
it looks like there's a five work limit for featuring on the home page. i'm going to edit this ticket because i think the maybe the feature buttons shouldn't appear when there are five works already featured.

**Comment by chrisdaaz** [comment]
screenshot: 
![image](https://user-images.githubusercontent.com/24395592/49174349-aef0b300-f30b-11e8-8ed6-c2ec02dc1472.png)
