### ISSUE TITLE
The #show view for a work type shows "Unauthorized" when it's type is not returned in search results.

### ISSUE THREAD

**Issue by afred** [samvera/hyrax#3174]
### Descriptive summary

On Hyrax 2.1.0

### Rationale

Use case:
I've created multiple work types, but I want to restrict which work types are returned in search results.

### Expected behavior

I should be able to see the `#show` view for any work type that is not part of search results, but for which I still have read access.

### Actual behavior

You get the "Unauthorized" page.

### Steps to reproduce the behavior

In your app...

1. Create multiple work types, e.g. `Apple` and `Orange`
1. Change `SearchBuilder#models` to exclude one of the models, e.g.
    ```ruby
    class SearchBuilder < Blacklight::SearchBuilder
      # ...
      def models
        [Apple]
      end
      # ...
    end
    ```
    _This is per the docs here: http://samvera.github.io/building-searches.html#development-aka-doing-something-useful._
1. Create an instance of the excluded model and save it, e.g. `Orange.create(...)!`
1. Try to view the `#show` page for the newly created record.
1. You get "Unauthorized"

### Why this happens.

`Hyrax::WorksControllerBehavior#presenter` instantiates a presenter object with a curation concern retrieved from search results.

But if you've explicitly excluded a work type from the search results, then there won't be any curation concern to retrieve.

Through several method calls within `Hyrax::WorksControllerBehavior`, this eventually raises a `CanCan::AccessDenied` error, which `Hydra::Controller::ControllerBehavior` rescues from in order to display the "Unauthorized" page.

**Comment by jrochkind** [comment]
I am still way back on sufia, but I've run into all sorts of things where random uncaught exceptions are turned into "unauthorized" methods, which I don't think is right, and definitely makes debugging confusing.   I wonder if this is an instance of the same thing, and still in hyrax. I wonder if that situation is actually triggering a bug (uncaught exception), which is then turned into unauthorized?

An arbitrary uncaught exception (unexpected fatal error) should probably not be turned into an "unauthorized" message or a 401.  Aside from being just wrong, it makes debugging _really_ confusing.

**Comment by no-reply** [comment]
@afred in light of discussion on #3191, is this a `wontfix`?

**Comment by no-reply** [comment]
Closing issue, pending feedback from @afred
