### ISSUE TITLE
Sharing tab is hidden from all users but can be accessed indirectly (for works in 1-step workflow)

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3175]
### Descriptive summary

Hyrax 2.1 This was tested on nurax-dev and nurax-stable. 

The sharing tab is hidden for works in a 1-step workflow. This tab is hidden even from repo-admins.

There are two problems here:

- the sharing tab is the only way to revoke or add permissions to an individual work

- you can actually get to the sharing tab (as any user) by visiting the dashboard, all works, clicking on the visibility badge for the work 

### Steps to reproduce the behavior
1. As repo admin, go to work that is pending review and click on work.
2. No sharing tab
AND
1. As repo admin (or any user), go to dashboard all works
2. click on the visibility badge for a work pending review 
![screen shot 2018-07-30 at 12 23 02 pm](https://user-images.githubusercontent.com/4356335/43409926-402ef1ba-93f3-11e8-9a8e-89aeaaf071c7.png)
3. go to sharing tab contents with no sharing tab visible
![screen shot 2018-07-30 at 12 22 56 pm](https://user-images.githubusercontent.com/4356335/43410080-b70c64d4-93f3-11e8-8ce7-a9452d162ba5.png)

I know there are related tickets, but I can't find anything exactly like this. I also thought we decided to not make those badges clickable at some point? @vantuyls ?

**Comment by rjkati** [comment]
@jlhardes I am getting a "Sorry, I don't understand your search" message when I try to edit a work on nurax-dev as a repo-admin. This is the same message that I get when I try to create a work as a repo-admin. Since I need to edit a work as a repo admin to reproduce the behavior in the ticket, it seems that this ticket will need to be tested locally.

**Comment by jlhardes** [comment]
I can go into nurax-dev as a repo-admin so I am seeing items that are pending review in my Dashboard under Works > All Works. When clicking on the work title for one of these, I do not go into the edit view but instead see the public view with an added Review and Approval menu interface. In the All Works tab within the Dashboard, the Visibility of Work badges are clickable but on nurax-dev I cannot use those badge links to enter edit mode on any works as a repo-admin user (it works as a non-admin logged in user). So I am closer but still can't quite test this on nurax-dev (and I think that badge link issue for repo-admin users is specific to nurax-dev, I don't experience that in my local install).

On my local install, I do not seem to have mediated deposit available as a workflow and the instructions provided in the Samvera KB are not something that is matching what I am seeing in my Admin interface (https://samvera.github.io/workflow_and_mediated_deposit.html). I can create Admin Sets but I don't ever see a Workflow tab to set a Workflow.

I tried creating an Admin Set on nurax-dev to have a mediated deposit workflow but I can't figure out how to do it there either. There seem to be other Admin Sets that exist already with the mediated deposit workflow and I can deposit to them as a non-admin logged in user and those works show as pending review.

**Comment by jlhardes** [comment]
I have figured out how to make mediated deposit work on my local install (this involves creating a collection that is an Admin Set, then editing that collection after creating - then the Workflow tab is available as described in the Samvera KB documents, so that needs an update).

The badge link for a work that is pending review in a mediated deposit workflow is working locally for a repo-admin user to access the edit form for a Work and it does still show the sharing screen but without the Sharing tab available for repo-admin users as the original report describes. Once you click on one of the available tabs, the sharing screen is gone and you can't get back to it. There is no other way to get at that sharing screen since using the Select menu to enter the edit form of a Work places you in the Descriptions tab and the Sharing tab isn't available. So this is a bug that is still present for repo-admin users - they should have the Sharing tab available when they are editing a work that is Pending Review in a mediated deposit workflow.

**Comment by jeremyf** [comment]
There are two parts:

1. Analysis
2. Questions

## Analysis

Some more sleuthing.  First, the primary view that has the sharing is [_guts4form.html.erb](https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/views/hyrax/base/_guts4form.html.erb).

On a cursory glance we have some interesting dichotomies.  Compare the two block directives:

1. The looping conditions for the tab **navigation** links: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/views/hyrax/base/_guts4form.html.erb#L6-L7
2. The looping conditions for the **content** portions: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/views/hyrax/base/_guts4form.html.erb#L27-L28

Notice that in the **navigation** we have all tabs (which might include `"sharing"` depending on how we populate the tabs variable), but in the **content** portion we omit sharing.

Now, if we look at the larger context lines 19 through 23 add a **navigation** element to the sharing tab: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/views/hyrax/base/_guts4form.html.erb#L19-L23

And we also explicitly add a sharing **content** element at lines 42 to 46: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/views/hyrax/base/_guts4form.html.erb#L42-L46

Now note on line 19, that we have `class="hidden"` (that's acted on in [JS editor object](https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/assets/javascripts/hyrax/editor.es6#L17), but we'll get to that later.)

I suspect that in some cases we are possibly rendering two **navigation** elements that are linking to the rendered share **content** section.  One of those **navigation** elements is likely hidden (as per the `class="hidden"`) and the associated JS never "reveals" it.  We introduced that logic around that "hidden" behavior in c838900cf5614cf6041f6880ff5d8c79fbf99f67.

The commit message is:

```
commit : c838900c 
Author : Justin Coyne
Date   : Fri Mar 10 20:41:20 2017 

Don't show share tab when selected workflow doesn't allow it.

It doesn't make sense to allow people to add "edit" users on a mediated
workflow where we intend to strip away everyone's edit access.

Fixes #3134
```

The reported bug is: https://github.com/samvera-deprecated/sufia/issues/3134
The PR is: https://github.com/samvera-deprecated/sufia/pull/3138

## Questions

With the above analysis and context, I have a few questions:

1) Are we rendering two **navigation** links for sharing? (with one being hidden)
2) Should we be enforcing "don't allow sharing" via a JS widget? (my inclination is no, that's not a JS function!)
3) Could the interplay of the two **navigation** links, the JS widget, and the "data state" be creating the current inconsistent behavior?

With the above context, what is the right thing to do?  When should we "show the sharing tab?" is the question, and one past proposal is: 

> It doesn't make sense to allow people to add "edit" users on a mediated
> workflow where we intend to strip away everyone's edit access.

Note: I have not fired up the application to get it to this state, but find that this may a great opportunity to pair program with some (@jlhardes has been able to duplicate this behavior, so perhaps you could steer and I could navigate?)

**Comment by jlhardes** [comment]
Testing locally shows this is fixed (sharing tab is available as a repo-admin user for a work that is pending review). I can't seem to test this on nurax-dev, however. As a repo-admin user I am currently unable to access the edit form for any work whether it is my work or in the list of all works. Trying to access the edit form for a work sends me to the Hyrax home page with a green alert that says "Sorry, I don't understand your search."

**Comment by jlhardes** [comment]
Testing on nurax-dev is not possible but testing locally is still showing this as fixed so this is verified as done.
