### ISSUE TITLE
repo-admin cannot transfer ownership of another user's work to themselves

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#3176]
### Descriptive summary

Hyrax 2.1, tested on nurax-stable

If a repo-admin attempts to transfer ownership of another user's work to their own account, they encounter an error message

### Rationale

If a user deposits a work and leaves the institution, repo-admins cannot claim ownership of the deposited work.

### Expected behavior
Repo-admin should be able to transfer ownership of another user's work to themselves

### Actual behavior
After completing the process to transfer the work to their own account, repo-admin receives error message "specify a different user to receive the work".  The ownership of the work does not transfer.

### Steps to reproduce the behavior

1. Log in as a regular user and create a public work

1. Log in as a repo-admin, navigate to the works dashboard and find the work that was created in step 1

1. Select "transfer ownership of work" from the drop-down menu

1. Try to transfer ownership to your repo-admin account

**Comment by RudyOnRails** [comment]
I ran into this last week in Sufia. My gut is that this is the validation that needs to be tweaked: https://github.com/samvera/hyrax/blob/master/app/models/proxy_deposit_request.rb#L44

**Comment by jeremyf** [comment]
I believe this may be addressed in https://github.com/samvera/hyrax/pull/4497, however, it would require retesting once that's merged.

**Comment by rjkati** [comment]
Issue is still present in hyrax 3.0.0 rc3

**Comment by rjkati** [comment]
Confirmed that repo-admins can now transfer ownership of works to themselves in Hyrax 3.0rc4
@jlhardes
