### ISSUE TITLE
Issue while setting up role in installation process

### ISSUE THREAD

**Issue by codeinvolute** [samvera/hyrax#3185]
irb(main):002:0> admin.users << User.find_by_user_key( "test2@jhu.edu" )
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "test2@jhu.edu"], ["LIMIT", 1]]
Traceback (most recent call last):
        1: from (irb):2
ActiveRecord::AssociationTypeMismatch (User(#47460127844500) expected, got nil which is an instance of NilClass(#47460077944360))
irb(main):003:0> admin.save
   (0.1ms)  begin transaction
  Role Exists (0.2ms)  SELECT  1 AS one FROM "roles" WHERE "roles"."name" = ? AND ("roles"."id" != ?) LIMIT ?  [["name", "admin"], ["id", 1], ["LIMIT", 1]]
   (0.1ms)  commit transaction
=> true
irb(main):004:0> u = User.find_by_user_key( "your_admin_users_email@fake.email.org" )
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "your_admin_users_email@fake.email.org"], ["LIMIT", 1]]
=> nil
irb(main):005:0> u = User.find_by_user_key( "test2@jhu.edu" )
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "test2@jhu.edu"], ["LIMIT", 1]]
=> nil
irb(main):006:0> u.admin?
Traceback (most recent call last):
        1: from (irb):6
NoMethodError (undefined method `admin?' for nil:NilClass)

**Comment by no-reply** [comment]
Hi @codeinvolute.

It looks as though the user with key `test2@jhu.edu` doesn't exist. `User.find_by_user_key( "test2@jhu.edu" )` is returning `nil` which is why your first and last lines are raising errors.
