### ISSUE TITLE
Cross-site scripting vulnerabilities

### ISSUE THREAD

**Issue by hortongn** [samvera/hyrax#3187]
### Descriptive summary

For a school project, a student at the University of Cincinnati performed a manual penetration test on UC's Scholar@UC application (based on Hyrax 1.x).  He found four potential cross-site scripting vulnerabilities where the work or file title fields were not being properly sanitized.  

We then replicated the attacks on nurax-dev.curationexperts.com and found the same behavior.  So the vulnerabilities appear to be in the current version of Hyrax.

### Vulnerability 1

1. Go to the Add New Generic Work form
1. Create and save a work (no file is needed) with the title `<ScriPt>prompt("Confirm Password")</ScRIPT>`
1. On the work's show page click the `Citations` button
1. You will see a popup asking the user to enter their password.

(the vulnerability seems to be in the Chicago citation format when it tries to list the work title)

### Vulnerability 2 

1. Go to the Add New Generic Work form
1. Create and save a work (no file is needed) with the title `<ScriPt>prompt("Confirm Password")</ScRIPT>`
1. Visit /dashboard/my/works
1. Under `Actions` click the `Select` dropdown for the work you just created
1. Click on `Delete Work` and confirm the delete
1. The page you land on after delete will display a popup asking the user to enter their password.

(The vulnerability appears to be in the flash message that tries to list the deleted work's title)

### Vulnerability 3

1. Go to the Add New Generic Work form
1. Create and save a work using the title `<ScriPt>prompt("Confirm Password")</ScRIPT>` and attach at least 1 file
1. After the work is saved, click `Edit` to go to the work's edit form.
1. Change the work to a different visibility setting and save the work
1. You will see a popup asking the user to enter their password.

(the vulnerability seems to be on the "Apply changes to contents?" page when it tries to list the work title)

### Vulnerability 4

1. Make sure the UniversalViewer is configured
1. Go to the Add New Generic Work form
1. Create and save a work using the title `<img src=xx:x onerror=eval('\x61ler\x74(1)') /> and attach 1 image file
1. When you are redirected to the work's show page you will see a popup with the number 1

(The vulnerability appears to be in the UniversalViewer.  The popup only shows when the UV is present on the page)

NOTE: The same behavior exists if `<img src=xx:x onerror=eval('\x61ler\x74(1)') />` is used for the **file** title instead of **work** title.

**Comment by no-reply** [comment]
@cjcolvar could I get your input on **Vulnerability 4** above?

I think I have minimal fixes for the other three, but the universal viewer issue seems different. I'm sure we just need to scrub some input, but I'm not being as quick as I would like about finding out which. Insights?

**Comment by chrisdaaz** [comment]
Vulnerabilities 1-3 have been removed via https://github.com/samvera/hyrax/pull/3233 and confirmed on `nurax-dev`

4 appears to have a new ticket (https://github.com/samvera/hyrax/issues/3232). closing this.

**Comment by edsilv** [comment]
Have fixed the xss vulnerability in the UV using https://github.com/leizongmin/js-xss

https://github.com/UniversalViewer/universalviewer/commit/16161a2b4770c027558916b8d262b09fb23b1758
