### ISSUE TITLE
Failing Test: "Hyrax::CollectionType collections returns collections of this collection type"

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#3192]
### Descriptive summary

`rspec ./spec/models/hyrax/collection_type_spec.rb:140` fails intermittently on CI

### Rationale

We need a stable green build.
[log.txt](https://github.com/samvera/hyrax/files/2278527/log.txt)

**Comment by jrgriffiniii** [comment]
This suite also fails randomly for `spec/features/collection_type_spec.rb:366` (https://github.com/samvera/hyrax/blob/master/spec/features/collection_type_spec.rb#L366).  Please see https://circleci.com/gh/samvera/hyrax/1521.

**Comment by laritakr** [comment]
Note: The above fixes only the issue James referenced.

**Comment by jeremyf** [comment]
I believe this is now closed.
