### ISSUE TITLE
Upgrade Universal Viewer

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#3232]
### Descriptive summary

The `pul_uv_rails` gem we use to deliver Universal Viewer is long out of date, and the UV version it ships is vulnerable to **Vulnerability 4** as described in #3187.  We are looking at local (`iiif_manifest`-side) fixes for this particular issue, but should upgrade UV anyway

### Rationale

Since `pul_uv_rails` is un/under-maintained, it's probably time for Hyrax to move to a different solution. At the very least, we should upgrade to a recent version of UV.

### Related work

#3187

**Comment by escowles** [comment]
BTW, we tested a current version of UV 2 and a recent version of UV 3, and found both are vulnerable.  We filed https://github.com/UniversalViewer/universalviewer/issues/612 about this.

**Comment by escowles** [comment]
WIP PR to update pul_uv_rails to UV 2.0.2 is here: https://github.com/pulibrary/pul_uv_rails/pull/11

**Comment by kdid** [comment]
Moving back to ready, while we wait for dependencies to be figured out/updated for a UV update, we're working around vulnerability no. 4 in #3187 by sanitizing output from the `iiif_manifest` gem.

**Comment by geekscruff** [comment]
Another bug lending weight to fixing `pul_uv_rails` https://github.com/pulibrary/pul_uv_rails/issues/12

**Comment by no-reply** [comment]
We now
