### ISSUE TITLE
Can't select all when show per page is set to 100

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3242]
### Descriptive summary

Hyrax 2.1 (and just tested on nurax-dev) 

When you are viewing works (more than 100) and you set this number on the show items drop down to 100, you can't select all.
See the text that shows when you try to select all.

![](https://user-images.githubusercontent.com/4356335/40365168-fd986c78-5da1-11e8-8b08-e627dd98aaae.png)

### Rationale

this is confusing and makes it hard to do bulk adding works to collections because it makes it so the most you can select is 50. In addition, selections only work for the page you are on. One can not select 50, page over and select 50 more. 

###Steps to reproduce

1. go to hyrax that has more than 100 works
2. change the show per page to 100
3. try to select all

### Related work

Link to related tickets or prior related work here.

**Comment by julesies** [comment]
Related issue that is another problem: https://github.com/curationexperts/nurax/issues/141

**Comment by no-reply** [comment]
This looks like it's by design, see: https://github.com/samvera/hyrax/commit/ea99beca83ed9922fce5c1668ed858e3af65b336. 

@cam156 can you provide any context about the underlying issue here?

**Comment by rjkati** [comment]
Still present in Hyrax 3.0 rc3. Also, the explanatory text overlays the select check box and is not legible. Looks like this ticket might need further follow up @jlhardes 
![select_100_works](https://user-images.githubusercontent.com/32644254/106001286-c22f7280-607d-11eb-845b-968099d09206.PNG)

**Comment by jlhardes** [comment]
Thanks @rjkati! If this capability is being purposefully disabled based on previous user testing, we have a documented use case for why this capability is needed. If there isn't a technical issue with selecting 100 items at a time we should fix this (and make sure text isn't overlapping the Select All checkbox).

**Comment by jeremyf** [comment]
I'm starting to look at the implementation details of this.

**Comment by jeremyf** [comment]
[Here's the commit](https://github.com/samvera/hyrax/blob/0222988b13ddf03cb584c8c9168da7c8d826b674/app/controllers/hyrax/my_controller.rb#L56
) that includes the number that controls the max batch size.

[Here's the commit](https://github.com/samvera/hyrax/blob/0222988b13ddf03cb584c8c9168da7c8d826b674/app/assets/stylesheets/hyrax/_file-listing.scss#L157) that adds the overlay of "Too many items, can not select all."
Introduced in 2017.

These were both rather surprising.  One adds a CSS hack, the other is a hard-coded and somewhat arbitrary 80.  I'm going to explore what to do.  But this should be a quick fix to at least let 100 (and all valid options in that select box) work.

**Comment by jeremyf** [comment]
I added an [optional configuration to the Hyrax config](https://github.com/samvera/hyrax/blob/af0273647371cd7ba994f87e5d6a87729aa4a3c5/lib/hyrax/configuration.rb#L764) for page sizes.  I had 2 works, and changed the drop down to only include `[1]`. Below is the image (the select option says 1 per page, but the implicit per page of the controller is larger than that)

<img width="417" alt="Screen Shot 2021-02-02 at 2 59 48 PM" src="https://user-images.githubusercontent.com/2130/106655433-55c5df00-6567-11eb-8a4b-565062d30fd2.png">

To test with the least antics, there are a few options:

1. Have 101 objects in your test data
2. Have 2 objects in your test data and adjust the Hyrax config to [Hyrax config](https://github.com/samvera/hyrax/blob/af0273647371cd7ba994f87e5d6a87729aa4a3c5/lib/hyrax/configuration.rb#L764) to `[1]` and add `&per_page=1` to your query parameter.

**Comment by jlhardes** [comment]
This is working for me testing locally with 2 objects and configuring the Show per page drop-down to show 1 object. When I first enter Dashboard > Works, I see both objects and I can select both objects with the Select checkbox (there is no per_page parameter showing, I forgot to add that parameter but I still think this is a good test since the css text overlay didn't show up). I can change that Show per page drop-down to 10 and then back to 1 and at that point only 1 object shows and there are 2 pages of results, with the second object on the second page (and there is now a per_page parameter). On the first page, I can still use the Select checkbox to select all on that page (which is just 1 object). I think this fix is working.
