### ISSUE TITLE
Remove "Is part of: `Collection Name` from collection view

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3243]
### Descriptive summary

Hyrax 2.1 (also tested on nurax-dev today)

Users on a collection page can view a list of work titles. Beneath the work titles is a line of text that says that the work is part of the collection.

![](https://user-images.githubusercontent.com/24395592/39774299-10db3d16-52c0-11e8-8943-a8ee004fe0bb.png)

### Rationale

This user is already on the collection page and this line of text is redundant.

### Steps to reproduce the behavior

1. Steps to reproduce the behavior
2. As a non-logged in user, visit a public collection with multiple items.

**Comment by vantuyls** [comment]
i would be happy modifying that line of information to read something like:
"this work also belongs to the following collection(s)"

**Comment by afred** [comment]
@vantuyls @hweng We're reviewing this in post-tech-call review session, and are wondering if there is more work to be done in order to get the PR through. Thanks!

**Comment by vantuyls** [comment]
@no-reply @julesies does my comment above clarify enough to resolve this?

**Comment by hweng** [comment]
I agree with @no-reply's comment. As the item could belong to more than one collection, Keeping "is part of" looks fine to me.

**Comment by vantuyls** [comment]
Yes, but the redundancy would be nice to get rid of. Is suppressing the name of the current collection (based on the collection page one is on) possible?

**Comment by vantuyls** [comment]
lets make it so. thanks @hweng
