### ISSUE TITLE
After deactivating embargo, return to work view 

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3244]
### Descriptive summary
Hyrax 2.1.x
Right now, if you deactivate a single embargo you go to a Manage Embargo page for that work. It's pretty confusing. What about just going back to the work view page instead?

Current behavior: Click deactivate embargo
![](https://user-images.githubusercontent.com/4356335/39546309-f19d47a2-4e21-11e8-9734-988640810bf0.png)

Then you are redirected to this page
![](https://user-images.githubusercontent.com/4356335/39546317-f91df670-4e21-11e8-8d30-fd8aebd2b39a.png)

Instead go back to work edit or work view. (not sure which is more appropriate)

Comment from @vantuyls "i think that would be a less confusing approach. I'm all for it."

### Rationale

unnecessary step

### Steps to reproduce the behavior

1. go to manage embargoes page 
2. deactivate a single work
3. directed to this page

**Comment by vantuyls** [comment]
this issue has been resolved and the expected behavior is now in place.
