### ISSUE TITLE
Add work to another work (in_works)

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#325]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jcoyne](https://github.com/jcoyne)**
_Wednesday Mar 30, 2016 at 21:54 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/1709_

----

### Descriptive summary

Add the work currently being edited as a member of other works.
- [in context of New Work](https://wiki.duraspace.org/display/hydra/New+Work+-+tab+Relationships+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab
- [in context of Edit Work](https://wiki.duraspace.org/display/hydra/Edit+Work+-+Relationships+tab+-+Phase+1+-+UI+Wireframes) - Relationships Tab - contents of tab

Closely related to #1710 
Ref #1577

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Wednesday Mar 30, 2016 at 21:54 GMT_

----

@mjgiarlo backlog?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Thursday Nov 17, 2016 at 17:13 GMT_

----

@dlpierce can you give us an update on the status of this work?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/mjgiarlo"><img src="https://avatars.githubusercontent.com/u/131982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Jan 23, 2017 at 23:39 GMT_

----

@dlpierce We're 1-2 blockers away from cutting a beta/RC for 7.3.0. Do you think you might have time to wrap this and #1710 in the coming week or two?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/dlpierce"><img src="https://avatars.githubusercontent.com/u/105335?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dlpierce](https://github.com/dlpierce)**
_Tuesday Jan 24, 2017 at 18:22 GMT_

----

@mjgiarlo Yes, I'll make it a priority to get this done for 7.3.0.

**Comment by mjgiarlo** [comment]
Remaining work in this ticket:

* Minor view reformatting in the edit view to make the current impl match the mockups (not sure that is a high priority)
* Surface the "This Work in Other Works" and "Other Works in this Work" widgets in the new view.

**Comment by dlpierce** [comment]
I'm going to use this issue for tracking '"Surface the "This Work in Other Works" and "Other Works in this Work" widgets in the new view.' and leave the other part for #326 .

In the interest of sharing the code for this feature between the new and edit forms, I would like to move from using ajax calls to update child/parent work relationships to performing the update when the Save button is clicked.

Rationale is it's reasonable for a user to expect their changes to not be automatically saved when presented with Save and Cancel buttons. Currently the work relationships will be instantly persisted when the Add or Remove button is clicked, even when there are other changes entered in the work form. Clicking Cancel after making relationship changes will not undo the relationships and clicking Save only persists metadata property changes and file uploads. The timing of the save call was briefly discussed in the [original PR](https://github.com/projecthydra/sufia/pull/2243#issuecomment-230568564) of this feature.

As a bonus, making this change should facilitate bringing this feature to the form for a new work.

Any thoughts from @projecthydra-labs/hyrax-code-reviewers ?

**Comment by mjgiarlo** [comment]
This ticket and #326 should focus on UI changes for the add child/parent feature, now that @jcoyne is about to put in a related PR that removes javascript in favor of handling this in the form (so as not to run afoul of locking issues).

**Comment by mjgiarlo** [comment]
We found issues with this approach and abandoned it.
