### ISSUE TITLE
Work factory build requires Fedora

### ISSUE THREAD

**Issue by cjcolvar** [samvera/hyrax#3255]
In a test `build(:work)` attempts to contact Fedora when setting the `visibility` attribute.  This is counter to the expected behavior of `build` which should just initialize a model and not attempt to persist anything.  Resolving this issue should also help to speed up tests since Fedora won't be contacted needlessly.

**Comment by no-reply** [comment]
Interestingly, once `visibility:` is set once, I can freely change it between `open` and `restricted` without accessing fedora.

**Comment by no-reply** [comment]
The offending line appears to be https://github.com/samvera/hydra-head/blob/4ffa873d713a418e03d81688d18948595951ae1d/hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb#L24-L26.

We try to build an access control before the object exists. This happens even when only accessing `#visibility`.

**Comment by no-reply** [comment]
This was closed by the same work that closed #453.
