### ISSUE TITLE
Admin Set title only shows to user with edit abilities

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#3273]
### Descriptive summary

Admin Set show page only shows title to people with edit access. Someone with depositor role can see the admin set show page but it doesn't show the admin set's title. 

Partial `show_actions.html.erb` needs the permission test moved to only control the button rendering.

### Steps to reproduce the behavior

1. Display admin set as manager role... title shows.

![screen shot 2018-09-13 at 3 22 39 pm](https://user-images.githubusercontent.com/17851674/45511665-9c82c680-b76b-11e8-9929-25f0312db77f.png)

2. Display admin set as depositor role... title does not show.

![screen shot 2018-09-13 at 3 23 17 pm](https://user-images.githubusercontent.com/17851674/45511642-8d9c1400-b76b-11e8-888c-63547b251285.png)

**Comment by dlim87** [comment]
This has been fixed 

Creator:
![Image 2019-11-06 at 9 53 53 AM](https://user-images.githubusercontent.com/5492162/68324010-65f8c100-007b-11ea-8620-bb249391b0f1.png)
manager
![Image 2019-11-06 at 9 51 57 AM](https://user-images.githubusercontent.com/5492162/68324031-6ee99280-007b-11ea-8e93-ed3be09af27e.png)
depositor
![Image 2019-11-06 at 9 52 21 AM](https://user-images.githubusercontent.com/5492162/68324046-76a93700-007b-11ea-97bf-63f0da54089d.png)
viewer
![Image 2019-11-06 at 9 52 54 AM](https://user-images.githubusercontent.com/5492162/68324062-8163cc00-007b-11ea-8c47-0e31d2847efc.png)
