### ISSUE TITLE
Paginate the transfers page

### ISSUE THREAD

**Issue by hackmastera** [samvera/hyrax#329]
### Descriptive summary

If you have a lot of transfers, a single user loading this page begins to drag down the entire system.

**Comment by mjgiarlo** [comment]
@hackmastera A few follow-up question:

1. Do you have a sense of what number constitutes "a lot" so we could do some targeted testing?
2. Do you think datatables might work for this purpose, or would the same happen? (I believe there's a pagination plugin for datatables.) We're using them elsewhere in the system to get "automatic" sorting and filtering.
3. What are your and @projecthydra-labs/hyrax-ui-ux-advisors thoughts on the current state of the transfers UI? Specifically, we display that information in two places using the exact same templates -- I wonder if that's confusing, and if one view makes more sense than the other. See below.

First, there's the transfers page which you can get to via the Dashboard toolbar menu:

![transfers_page](https://cloud.githubusercontent.com/assets/131982/22432075/99275ef8-e6c8-11e6-94b3-006728405d8d.png)

And then there's the "widget" in the dashboard itself:

![dashboard_transfers](https://cloud.githubusercontent.com/assets/131982/22432083/a15946ae-e6c8-11e6-93b4-86aed660b35b.png)

(I'll note that they render the *exact same* partials, so making improvements to one would make improvements to the other.)

**Comment by mtribone** [comment]
I think that having transfers on the dashboard for @hackmastera's use case might be a bit too much, but I think that would be up to her and her users to decide. I say paginate that thing and test it out. 

Also, the dashboard concept could use some more testing to see if we're in the same place we were several years ago. Our needs for an "at a glance" dashboard to trigger actions and get bite sized info may not be useful anymore or robust in combo with the toolbar.

**Comment by ggeisler** [comment]
Just speaking from a Hyku perspective, I'd like to see all tables on the admin side of things be DataTables, both for the functionality like pagination, column sorting, and searching you get and for consistency in the user experience and visual design.

I agree with @mtribone about transfers on the dashboard possibly being too much. I see the purpose of a dashboard to be showing an overview of recent and/or important activity, not necessarily to contain duplicated functionality for convenience. You'll eventually end up with a too cluttered dashboard and have to make decisions about what features are important enough to duplicate on the dashboard and which aren't. And the user will not have a clear mental model of what is doable from the dashboard and what isn't.

**Comment by jcoyne** [comment]
@ggeisler DataTables requires all the data to be rendered to the page, (even if most of it is hidden), right?  This could potentially be millions of records, so the time to collect all that information could be too great to give the user a good experience.

**Comment by ggeisler** [comment]
@jcoyne I agree that if there are potentially that many rows, and all the data has to loaded initially, we wouldn't want to give the user that experience. 

What about server-side processing mode, though? I don't have any firsthand experience implementing it, but it seems like this is an option for just this sort of case (potential of huge numbers of rows of data)? https://datatables.net/manual/data/

**Comment by hackmastera** [comment]
Some more context from me:

Only a small portion of my users were using transfers as the basis of their workflow. Due to this problem, they changed their workflow and are now doing it another way. So I don't actually have a use case here anymore; I mostly wanted it registered as an issue for the benefit of others.

When we started having the problem I did change the template feeding the dashboard to only show 'in progress' transfers, and to send users back to the dashboard when they approved a transfer. That made the dashboard for those users load in a reasonable time.

I would guess the problem started around 300 transfers; I can say for sure it existed at 500.

Y'all are right to bring the dashboard into this conversation, though; not sure if that should be a separate issue.

**Comment by no-reply** [comment]
cc: @samvera/hyrax-repo-managers

**Comment by julesies** [comment]
@no-reply this makes me think of  the recent conversation about the concept of ownership we had on slack, started by this permissions group. https://docs.google.com/document/d/1LsIso-RMrHC0_bDxw9t5mwmVu8a6rHm8cF_xId9gOAM/edit

It's not a concept that is easily understood outside the context of faculty proxy deposit. It's also unclear what the implications of not transferring works are, say if a student deposited 10k works and then left the institution and yet is still the owner of those works.

So I think ownership and transfers may need some further consideration in general.

**Comment by julesies** [comment]
Also, I get the sense that some institutions are setting up an automatic transfer of the ownership to a manager-type role. SAIC, Ubiquity, OSU?

**Comment by RudyOnRails** [comment]
@julesies - correct. The Art Institute currently does not do automatic transfers in Sufia 7.2, but we are beginning to setup work on splitting up "depositor" into "depositor" and "owner" concepts by adding an `owner` predicate, or possibly saving some time and using the existing mechanics of `proxyDepositor` and `depositor`.

**Comment by julesies** [comment]
As of Hyrax 2.1 Transfers are accessed via the dashboard. Pagination seems like a good step to prevent the OP's issue. The larger issue still stands "ownership" as a concept needs some thought. Not sure when a good time to deal with this is.

**Comment by julesies** [comment]
Closing per discussion with repo-managers, if there is still a potential to drag the system, please let us know.
