### ISSUE TITLE
Map license to dcterms:license

### ISSUE THREAD

**Issue by ruthtillman** [samvera/hyrax#3293]
### Descriptive summary

Map field "license" to dcterms:license instead of DCT:rights.

### Rationale

Right now “license” maps to DCT:rights. Rights and licensing are related but fundamentally different data, as the license conveys information about how the object may be used. Map instead to 
dcterms:license. This will require data migration.

From the Metadata IG Hyrax review project. UCSD, IU, Tufts and Oregon State in favor of this change.

### Related work

See also comment https://github.com/samvera/hyrax/issues/808#issuecomment-296028015

**Comment by jenyoung** [comment]
Also, the list of Creative Commons licenses needs to be updated to 4.0 licenses. Current list is for 3.0

**Comment by no-reply** [comment]
I like the idea of moving to `dcterms:license` but want to acknowledge that we don't currently meet the range restriction http://dublincore.org/documents/dcmi-terms/#terms-license. Should we try to wrap the license update, nested data, and predicate change all into this ticket?

**Comment by kdid** [comment]
@jenyoung @ruthtillman @no-reply - can someone clarify what needs to be done here? I'm not sure I'm following.

**Comment by jlhardes** [comment]
Updating issue title to reflect that property should be mapped to 
http://purl.org/dc/terms/license

**Comment by jenyoung** [comment]
Also updated ticket to reflect the above

**Comment by fritzfreiheit** [comment]
@kellyChex -- Here's what I've worked out on how to QA this. It's all done from your localhost as you will need to run a rake task do verification through the rails console.

* Using a local install, start up and run Hyrax with the latest from head.
* Create a GenericWork and add a license metadata field (using `Additional Fields`)
* Note the id of the GenericWork
* Edit the file `app/models/concerns/hyrax/basic_metadata.rb`
* Replace the following line (this will allow the creation of works with the old license predicate) :
`property :license, predicate: ::RDF::URI.new('http://dublincore.org/documents/dcmi-terms/#terms-license'), multiple: true`
with
`property :license, predicate: ::RDF::Vocab::DC.rights, multiple: true`
* Restart Hyrax
* Add another GenericWork with a license field and note the id
* Start a rails console and run the following:
`predicate_from = ::RDF::Vocab::DC.rights`
`predicate_to = ::RDF::URI.new('http://dublincore.org/documents/dcmi-terms/#terms-license')`
`ActiveFedora::Base.all.select { |w| w.ldp_source.content.include? predicate_from.to_s }.map { |w| w.id }`
`ActiveFedora::Base.all.select { |w| w.ldp_source.content.include? predicate_to.to_s }.map { |w| w.id }`
* You should see the associated ids for for the two works appear as the results, one for each search.
* Stop the rails server and run the following rake task
`bundle exec rake hyrax:migrate:migrate_keyword_predicate`
* Rerun the two commands in the console, the search for the `predicate_from` should return empty while the search for the `predicate_to` should return both GenericWork ids.
`ActiveFedora::Base.all.select { |w| w.ldp_source.content.include? predicate_from.to_s }.map { |w| w.id }`
`ActiveFedora::Base.all.select { |w| w.ldp_source.content.include? predicate_to.to_s }.map { |w| w.id }`
* Restore `app/models/concerns/hyrax/basic_metadata.rb` by:
`git checkout -- app/models/concerns/hyrax/basic_metadata.rb`

**Comment by dlim87** [comment]
Hyrax performed as described in that test plan. QA approved
