### ISSUE TITLE
Add "Rights note" field

### ISSUE THREAD

**Issue by ruthtillman** [samvera/hyrax#3294]
### Descriptive summary

Add free-text field labeled “Rights note.” Description: “Contains information about rights held in and over the resource.” Map to: http://purl.org/dc/elements/1.1/rights

### Rationale

While rightsstatements are a useful way of managing and displaying data about rights at a large scale, one ongoing concern which came up in the discussion of cultural heritage objects was the need to manage and display the _who_ as well as the what. An item might simultaneously have the rights statement that it is in copyright, a rights note about who holds the rights, and a CC-BY license (for which the rights note might be particularly important, as it could contain information about who should be credited).

WGBH and Tufts area already doing this locally, Oregon State in favor of change.

**Comment by no-reply** [comment]
This seems like a non-breaking addition that could be put in place immediately.

**Comment by dlim87** [comment]
QA - this field is in the new/edit work page, and displays correctly on the public show page when filled
