### ISSUE TITLE
Add field "Access rights"

### ISSUE THREAD

**Issue by ruthtillman** [samvera/hyrax#3295]
### Descriptive summary

Add free-text field labeled “Access rights” . “Contains information about who can access the resource or an indication of its security status.”  Map to: http://purl.org/dc/terms/accessRights

### Rationale

This may be used to indicate information about the object for which this is a digital surrogate or for the digital object itself. NU already doing this locally; IU in favor of this change.

Note, http://purl.org/dc/terms/accessRights hasRange RightsStatement. However, RightStatement can be textual, not just a URI pointing to text. Institutions may choose to use controlled values.

**Comment by dlim87** [comment]
QA - this field is implemented, and displays properly in the new/edit form, json, and public view pages
