### ISSUE TITLE
Add abstract field, mapped to DCT:abstract, label "Abstract"

### ISSUE THREAD

**Issue by ruthtillman** [samvera/hyrax#3297]
### Descriptive summary

Add field for abstract mapped to http://purl.org/dc/terms/abstract and label Abstract. 

### Rationale

Both Cultural Heritage and IR use cases may require differentiation between an abstract and a description. Currently we are storing data in description and calling it abstract. This disconnect can be resolved by properly labeling description and adding abstract with appropriate label.

Note, this may require some people to migrate their data, depending on how they are using abstract/description.

### Related work

https://github.com/samvera/hyrax/issues/3296

**Comment by jrochkind** [comment]
Can anyone point me to any guidance on what the difference is between an "abstract" and "description" in those domains?

**Comment by jenyoung** [comment]
In IRs, `Abstract` typically means the abstract accompanying an article for example. In Cultural Heritage uses, `Description` could contain information like `Based on a play which originally appeared in France as "Un peu plus tard, un peu plus tôt."` That's how I think of it anyway.

**Comment by no-reply** [comment]
do we consider #3296 dependant on this? or would we be happy to roll out that change before this one? @samvera/hyrax-metadataists

**Comment by no-reply** [comment]
This also seems non-breaking and like we can add it without complication.

**Comment by dlim87** [comment]
QA - There is both a description and abstract field, and they both display information properly
