### ISSUE TITLE
Remove "keyword" from required fields

### ISSUE THREAD

**Issue by ruthtillman** [samvera/hyrax#3298]
### Descriptive summary

Make keyword no longer required. 

### Rationale

Works will not necessarily have keywords. Keywords in IRs are often unuseful. Oregon State, UCSD, and Lafayette already doing this locally. (Notre Dame removed requirement from Curate.)

**Comment by no-reply** [comment]
Two questions about this seem open

  - How should we handle the removal of this requirement wrt backwards compatibility? (existing apps should continue to require this field?)
  - Should this field move below the `Additional Fields` fold?

@samvera/hyrax-metadataists @samvera/sufia-ui-ux-advisors

**Comment by jcoyne** [comment]
The fields that are required is something that can easily(?) be configured by the implementer.  All they need do is set the required fields to whatever they want:

```
MyWorkTypeForm.required_fields = [:title, :creator]
```

https://github.com/samvera/hyrax/blob/master/app/forms/hyrax/forms/work_form.rb#L33

In light of this, do we need to change the defaults?

**Comment by geekscruff** [comment]
Current defaults are [:title, :creator, :keyword, :rights_statement], we could cut this right down to [:title] and then document that folks should customize.

It's not strictly a breaking change, but if a 3.x release is on the near horizon, might be worth waiting, and perhaps doing all (with discussion) of the metadata group recommendations at once (https://github.com/samvera/hyrax/issues/created_by/ruthtillman)

**Comment by ruthtillman** [comment]
@geekscruff ++ on minimizing it, although I could see arguments for creators too... but to answer  @jcoyne's question -- why make the default something not great and say that people can change it vs. making it something simple and tell people how to make more fields required.
