### ISSUE TITLE
Home Page Featured Works is showing double images

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3305]
### Descriptive summary

On nurax-dev, when you are a logged out, the homepage featured works show as double thumbnails. 
![screen shot 2018-09-25 at 10 25 04 am](https://user-images.githubusercontent.com/4356335/46020866-5b64ad80-c0ad-11e8-83bd-76f514989a4e.png)

### Steps to reproduce the behavior

1. In a new browser/logged out visit https://nurax-dev.curationexperts.com/?locale=en

**Comment by no-reply** [comment]
I can't reproduce this in a recent version of Chromium, but can with Firefox.

**Comment by RudyOnRails** [comment]
Odd, we are seeing duplicate images, but inside thumbnail variants, and in Sufia, and not on all works/assets. I think the causes are separate, but just wanted to share.

**Comment by RudyOnRails** [comment]
I know I'm stating the obvious, but just for reporting, it seems like the issue on Nurax is in the generated markup (actual img element nested in the anchor) vs our single thumbnail image that seems to be generated with duplicate/overlapping images.

![screen shot 2018-10-04 at 12 00 17 pm](https://user-images.githubusercontent.com/1021154/46490249-1f2bfe00-c7cd-11e8-8efc-8bef681e5169.png)
