### ISSUE TITLE
Non-working pagination link on dashboard: works

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3306]
### Descriptive summary

on nurax-dev (not sure what version of hyrax it's running!), the dashboard: works view has an extra pagination section that does not work. See bottom right (that is the part that doesn't work). the bottom left nav does work. 

![screen shot 2018-09-25 at 11 46 36 am](https://user-images.githubusercontent.com/4356335/46026400-40983600-c0b9-11e8-8dab-5672bd76923d.png)

**Comment by no-reply** [comment]
Can reproduce, apparently browser independent.

**Comment by adamjarling** [comment]
Looks like the extra pagination in the bottom right appears when viewing "All Works", as opposed to "Your Works".
