### ISSUE TITLE
Move email text to locale files

### ISSUE THREAD

**Issue by smithjp** [samvera/hyrax#3321]
### Descriptive summary
When an email is sent by hyrax, it appears that hard-coded text is used.  This means that the emails are always sent in English and are not easy to modify.  We would like to see the email text moved to locale files for translation and to allow local modifications.

We are interested in submitting a PR for this change and want to get some feedback before moving forward.

### Expected behavior
Email text should be moved to locale files as interpolated strings.

### Actual behavior
Email text is hard-coded.

### Related work
List of files with hard-coded message text:
* app/controllers/hyrax/depositors_controller.rb
* app/models/proxy_deposit_request.rb
* app/services/hyrax/import_url_failure_service.rb
* app/services/hyrax/batch_create_success_service.rb
* app/services/hyrax/batch_create_failure_service.rb
* app/services/hyrax/fixity_check_failure_service.rb
* app/services/hyrax/workflow/changes_required_notification.rb
* app/services/hyrax/workflow/deposited_notification.rb
* app/services/hyrax/workflow/pending_review_notification.rb

### Possible problems
I believe that the i18n language is chosen based on the current user's preferences.  If a user has chosen to view the application in Spanish, then the email messages should be sent in Spanish.  The recipients of the email may not read Spanish which could be a problem.  This may require setting an application-wide default language somewhere to force the emails to be sent in an appropriate language.

**Comment by julesies** [comment]
@no-reply any thoughts on this? We are getting ready to start and wanted to know if we should work in hyrax or locally. Thanks!

**Comment by no-reply** [comment]
I think we need a concept of a preferred language. Email recipients should expect to receive emails in their language of choice. Some steps along the way to this might be:

  - [ ] move email text into `i18n` locales; add translations for supported languages; but always send in english
  - [ ] add/respect application-wide configuration for preferred locale; always send email with preferred locale's text
  - [ ] add profile option for user-specific preferred locale; default to application-wide preferred locale; send emails with recipient's preferred text.

Does that provide enough to grab onto? I think any progress toward the first step above would be amazing.
