### ISSUE TITLE
Customizing UI

### ISSUE THREAD

**Issue by prathyusha06** [samvera/hyrax#3322]
I wanted to change the UI of the landing page. Do I have to edit the view files before installing the application? Because I couldn't find appropriate view files after the installation

**Comment by no-reply** [comment]
@prathyusha06 the views are inherited from the `hyrax` engine by default. if copy them over into your generated application at the appropriate path, the local copies will override the upstream ones.

can you say a bit more about what you'd like to customize? we like to keep track of what kinds of view overrides folks are finding necessary so we can respond more usefully to inquiries like this one. thanks!
