### ISSUE TITLE
Cannot add a read only work to a collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3323]
### Descriptive summary

Users should be able to include works they can read in a collection to which they have deposit access.

### Rationale

Primary Use Case:  Building an exhibit collection where the exhibit curator is not the content creator.

### Expected behavior

While viewing a read only work, if the user has deposit access to at least one collection, the Add to Collection button should be visible and should provide a means for a read only work to be added to a collection.
 
### Actual behavior

While viewing a read only work, the Add to Collection button is never displayed.  Edit access to the work is required to see this button.

### Steps to reproduce the behavior

As user A...
1. create a public work named work-1

As user B...
2. create a collection named col-1
3. navigate to work-1

Should see Add to Collection button.

4. click Add to Collection
5. search for and select col-1
6. click Save Changes

**Comment by no-reply** [comment]
It's not clear to me at a glance whether this is a bug or an enhancement request.

My guess is that this permission limitation is _by design_, but still undesirable. cc: @vantuyls, @samvera/hyrax-repo-managers

**Comment by julesies** [comment]
this is related https://github.com/samvera/hyrax/issues/3179

I'm pretty certain we fixed this in 2.1 testing and ruled it quickly as a need b/c without these features, exhibits are impossible.
