### ISSUE TITLE
Bad handling of accented characters in file names

### ISSUE THREAD

**Issue by j-dornbusch** [samvera/hyrax#3324]
### Descriptive summary

When you upload a file with accented caracters in its name, they're stored and displayed as url-encoded everywhere.

### Rationale
Thanks to UTF-8 we could keep accented or non-latin caracters as-is instead of encoding/decoding it.

### Expected behavior
Keep accented caracters as is both in Solr and Fedora, or decode it in view. First solution preferred.

### Actual behavior
Accented caracters are stored as url-encoded in fedora
![fedora_view](https://user-images.githubusercontent.com/13169449/46722666-62c3b380-cc76-11e8-8476-358fe07c552f.png)
Accented caracters are stored as url-encoded in solr
```
"title_tesim":["Abri_dans_les_rizi%C3%A8res_15830349053_o.jpg"],
"label_tesim":["Abri_dans_les_rizi%C3%A8res_15830349053_o.jpg"],
"label_ssi":"Abri_dans_les_rizi%C3%A8res_15830349053_o.jpg",
```
Accented caracters are displayed as url-encoded.
![work_show_view](https://user-images.githubusercontent.com/13169449/46722323-89351f00-cc75-11e8-88c9-73e24e722659.png)
### Steps to reproduce the behavior

1. Save attached file, rename it "Abri dans les rizières_15830349053_o.jpg" and upload it in a new work 
![Abri dans les rizières_15830349053_o.jpg](https://user-images.githubusercontent.com/13169449/46722379-a23dd000-cc75-11e8-90ad-045209b0b42b.jpg)

2. Fill required metadata fields and save

**Comment by rjkati** [comment]
Accented characters in file names display correctly in Hyrax 3.0.0 rc3. @jlhardes 
![image_name](https://user-images.githubusercontent.com/32644254/105999116-52b88380-607b-11eb-8af1-b61303eaed07.PNG)

**Comment by jlhardes** [comment]
Thanks @rjkati! The display in the deployed application seems to be fixed now so I am hoping that means what is stored in Solr and Fedora is also better for accented characters. That isn't something we can test on Nurax so I think it will be good to double-check this in Fedora/Solr on a local implementation, if possible.

**Comment by jeremyf** [comment]
This is the screenshot from Solr; Note the accent, though we do convert spaces to `_`, though that's outside of scope for this bug. I'm checking Fedora.

![Screen Shot 2021-02-04 at 9 00 16 AM](https://user-images.githubusercontent.com/2130/106903056-858bf880-66c7-11eb-9ae2-bdf479ec75fe.png)

**Comment by jeremyf** [comment]
This is the screenshot from Fedora, Note again the accent.

![Screen Shot 2021-02-04 at 9 03 52 AM](https://user-images.githubusercontent.com/2130/106903434-f9c69c00-66c7-11eb-9213-cdb2ac3cb8ab.png)

**Comment by jeremyf** [comment]
I'm closing this ticket as the UI, Solr, and Fedora all include the <kbd>à</kbd>
