### ISSUE TITLE
CookieOverflow due to large amount of session data

### ISSUE THREAD

**Issue by fereira** [samvera/hyrax#3336]
### Descriptive summary

Using hyrax v2.1.0, accessing some pages causes as CookieOverflow exception (FATAL).  

### Rationale

We have a application based upon Hyrax 2.1.0 that stopped working overnight and generates a CookieOverflow exception.   We have several hyrax 2.1.0 applications running with dev, staging, and production instances.  When logging in, viewing works, and some other pages and using the developer tools in chrome I can interrogate cookies that have been created.   On a couple of other hyrax 2.1.0 based sites  there is a session cookie that ranges in size from 511 bytes to a bit over 1100 bytes.  On the broken system, the first time the session cookie gets created it's 3849 bytes.  From reading up on the exception there is, apparently a 4K limit on cookies, and it *looks* like the system is exceeding that limit when switching between pages.    

I'd like to know why the session cookie is so large on the broken system, and if it's possible to store session data elsewhere (as has been recommended on some sites I viewed) so that the 4K limit is not an issue.

### Steps to reproduce the behavior

I don't think that this is reproducible without writing some code which puts large amounts of data in the session.

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
This seems like a Rails configuration problem. Where session data is stored depends on your Rails application's settings. See, e.g. https://www.justinweiss.com/articles/how-rails-sessions-work/
