### ISSUE TITLE
Disabling admin set choice causes "sharing" tab to disappear

### ISSUE THREAD

**Issue by j-dornbusch** [samvera/hyrax#3339]
### Descriptive summary

On hyrax (2.3.3), when you disable the ability for end users to choose an admin set (via FlipFlop), it causes the "sharing" tab to be hidden.

### Rationale

We don't want to let users select admin sets, but we need to allow them to share their works.

### Expected behavior

When you disable "Assign admin set" feature, only the "Administrative Set" menu in the "relationships" tab should disappear. 

### Actual behavior

When you disable "Assign admin set" feature, the "Administrative Set" menu in the "relationships" tab disappears but the "Sharing" tab is hidden. You have this Warning in browser console : "No data was passed from the admin set. Perhaps there are no selectable options?". 

### Steps to reproduce the behavior

1. Go to /admin/features?locale=fr
Disable : 
> Assign admin set 	Ability to assign uploaded items to an admin set 

2. Create a new work

- "sharing" tab is not visible (class: hidden).
- Warning in browser console : "No data was passed from the admin set. Perhaps there are no selectable options?"

**Comment by mcdowney** [comment]
Closing, as this seems to duplicate: https://github.com/samvera/hyrax/issues/3175
