### ISSUE TITLE
Performance issues with ActiveFedora.where

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3349]
### Descriptive summary

ActiveFedora::Base.where uses solr to find resources and then resumes all the results from Fedora.  In many cases, it is not necessary to have the Fedora objects.  This applies generally to Hyrax, but this issue uses one instance as an example.

This issue should also identify other places where ActiveFedora::Base.where is used to determine if those can also be converted to pure solr.

### Rationale

Resuming objects from Fedora is expensive from a performance perspective and should only be done when needed.

### Expected behavior

Getting a count of objects in a collection should be done completely through solr.

```
def total_items
    ActiveFedora::SolrService.query("member_of_collection_ids_ssim:#{id}", rows: 100000000).count
end
```

Note: Not sure how to tell SolrService to return all matches.  I think it defaults to something like the first 10 rows.  So in the example, I made the rows requested very large, but there may be a better way. 

### Actual behavior

Getting a count of objects in a collection is performed with ActiveFedora.where which searches solr to find objects and then resumes them from Fedora.

```
def total_items
    ActiveFedora::Base.where("member_of_collection_ids_ssim:#{id}").count
end
```

https://github.com/samvera/hyrax/blob/master/app/presenters/hyrax/collection_presenter.rb#L67-L69

NOTE: The other uses of ActiveFedora::Base.where for counting in this presenter cannot be changed as solr docs do not support the accessible_by method.  I don't know if there is an equivalent approach that can be used to make those pure solr queries.

### Steps to reproduce the behavior

1. Run spec testing #total_items method in [collection_presenter_spec.rb](https://github.com/samvera/hyrax/blob/master/spec/presenters/hyrax/collection_presenter_spec.rb#L135-L153)
2. confirm the test passes before and after the change

**Comment by no-reply** [comment]
This looks like an `ActiveFedora` performance issue, rather than a Hyrax issue. `ActiveFedora::Base.where("member_of_collection_ids_ssim:#{id}").count` shouldn't ([doesn't?](https://github.com/samvera/active_fedora/blob/34ba358d993d4a9debcfbea6b0bc3617b3d46b7a/lib/active_fedora/relation/calculations.rb#L5-L12)) touch Fedora or instantiate any `ActiveFedora::Base` objects.

Can you clarify whether this is an observed performance issue?

**Comment by no-reply** [comment]
@elrayle is it okay to close this in light of discussion in slack yesterday? Or do you have some sense about how best to scope this for upcoming work?
