### ISSUE TITLE
i18n-debug gets required regardless of I18N_DEBUG setting

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#335]
It gets required when `config/application.rb` does `Bundler.require(*Rails.groups)`.  I don't think there's any need for requiring it in `spec_helper.rb`.

I think the fix is to do something like this conditionally in `spec_helper.rb`

```ruby
I18n::Debug.on_lookup = ->() { }
```

**Comment by atz** [comment]
Maybe with a comment about what that chunk of arcana is doing...

**Comment by no-reply** [comment]
Removed the "bug" tag, since this doesn't seem to impact production code.
