### ISSUE TITLE
Install XRay Rails

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#3354]
### Descriptive summary

This package is incredibly helpful in the Avalon Media System project.  @cjcolvar suggested it might be possible to add to Hyrax?

https://github.com/brentd/xray-rails

### Rationale
Fast discovery of where UI partials live in the application.

**Comment by no-reply** [comment]
closing this for now.

i imagine many folks have their own preferences about things to install in the development environment. happy to accept PRs to introduce them, but i think any tickets should be short-lived---if it's not happening quickly, it probably isn't worth the organizational overhead of maintaining a ticket.
