### ISSUE TITLE
Language Locale drops when Viewing depositor profile

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#3356]
### Descriptive summary

Tested on [nurax-dev](https://nurax-dev.curationexperts.com) with Windows/ Chrome. Language `locale` is dropped when user views the user profile.

### Rationale

Users who select a language other than English should make that selection only one.

### Expected behavior

Language selection should persist throughout the user's navigation of Hyrax.

### Steps to reproduce the behavior

1. Go to https://nurax-dev.curationexperts.com
2. Change the language to any non-English language
3. Search for the word "test"
4. Click on the Depositor's name/ email

You should be directed to the depositor's profile, in English.

### Related work

refs https://github.com/curationexperts/nurax/issues/235

**Comment by rjkati** [comment]
Issue is still present in hyrax 3.0 rc3

**Comment by jlhardes** [comment]
I can verify that this is working for English and Spanish but I am seeing errors prior to viewing the depositor profile when trying to change to other languages so I can't verify this is fixed across the board for all language views.

**Comment by jlhardes** [comment]
This change is deployed to nurax-dev and I can verify that it is working to see the Depositor profile info in the selected language. The problem described in the previous comment is likely connected to a local development install using Docker.
