### ISSUE TITLE
Edit Work buttons layout re-factor

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#3364]
### Descriptive summary

The layout of main buttons for Edit Work page is confusing, and could be better organized.  Investigate alternative layout options.

<img width="1033" alt="work-buttons-edit-page" src="https://user-images.githubusercontent.com/3020266/47806128-fed95b80-dd06-11e8-918b-654dae1b82d6.png">

Link to related tickets or prior related work here.

**Comment by adamjarling** [comment]
@chrisdaaz @vantuyls 2 options for how to clean this display up a bit.  Preference?  I also fixed the label sizing next to the Title, and made the buttons the primary button color to follow suit on Edit Collections page.  Trying to get some consistency.

![work-buttons-edit-page-option2](https://user-images.githubusercontent.com/3020266/47862980-4e319180-ddc4-11e8-846b-2f367fb3a4b3.png)

![work-buttons-edit-page-option1](https://user-images.githubusercontent.com/3020266/47862981-4e319180-ddc4-11e8-80a1-d8b107fafe6f.png)

**Comment by vantuyls** [comment]
i prefer the second, as it places the buttons in the same horizontal space. i'm assuming there is a hard line break between the two rows to prevent the icky re-stacking effect we're currently seeing. 

also, how does this do on mobile?

**Comment by vantuyls** [comment]
@samvera/hyrax-repo-managers may want to have a peek at this

**Comment by adamjarling** [comment]
@vantuyls Sounds good.  Here's how it looks on mobile:

After:

![edit-work-buttons-mobile-new](https://user-images.githubusercontent.com/3020266/47867828-a8d0ea80-ddd0-11e8-812e-679b79355037.png)

Before:

![edit-work-buttons-mobile-old](https://user-images.githubusercontent.com/3020266/47867840-aff7f880-ddd0-11e8-82a9-0dc4a5d479f2.png)

**Comment by julesies** [comment]
looks much better!

**Comment by adamjarling** [comment]
@jcoyne How about these two options?  The 2nd option, of putting the buttons in their own row, is how Github might approach this.   Maybe Github should just be the style guide for how to implement Bootstrap in Hyrax when in doubt.

If I ran further with this, I'd go buttons above title, then break out "Relationships" and "Items" in their own panel groupings, with a lower subhead `<h3>`.  To make the content separation more distinguishable maybe?

#### Button Group
![edit-work-buttons-btn-grouping](https://user-images.githubusercontent.com/3020266/47876255-d9238380-dde6-11e8-89af-cc1296088427.png)

![edit-work-buttons-btn-grouping-toggle-open](https://user-images.githubusercontent.com/3020266/47876254-d9238380-dde6-11e8-95dd-995eb5410406.png)

#### Button in own row
##### Above title
![edit-work-buttons-btn-own-row](https://user-images.githubusercontent.com/3020266/47876253-d88aed00-dde6-11e8-8ab9-66e52a2736fd.png)

##### Below title
![edit-work-buttons-btn-own-row-in-panel](https://user-images.githubusercontent.com/3020266/47876733-07559300-dde8-11e8-9af9-3c90e200d30a.png)

![github-example-button-row](https://user-images.githubusercontent.com/3020266/47876252-d88aed00-dde6-11e8-8e3c-65ae7d83e7ae.png)

**Comment by adamjarling** [comment]
Last screenshot, then I'll give it a rest.   Something like this...

![generic-work-show-page-idea](https://user-images.githubusercontent.com/3020266/47879297-3cfd7a80-ddee-11e8-89e4-403d7a662a98.png)

**Comment by vantuyls** [comment]
of those, i like the buttons above the title. that way they don't invade the metadata box. not sure there is a "best" approach, though.

**Comment by adamjarling** [comment]
Great.  @vantuyls Are you ok with 'panelizing' Relationships and Items sections in this page as well?

**Comment by adamjarling** [comment]
My idea is that maybe we're currently using panels as a container to shove all the page content in them, instead of using them to visually group UI segments.

**Comment by davidschober** [comment]
I think the last screenshot is the most well organized for a variety of reasons:

- similar content is grouped
- tertiary content (relationships, Thumbnails) are cleanly broken out
- user actions are grouped by similar tasks (e.g. Edit, attach child, delete)

The work type ( "Generic Work") looks to be the Header of the page. It seems that should be lower on the page hierarchy than the title of the work. Even if it's above the Title it should be obvious it's of lower importance visually.

**Comment by adamjarling** [comment]
Here's another version, with the following updates:

- Uses the work title(s) as `<h1>` tag(s) which may be better for seo and accessibility?
- Swaps the "CRUD" type function buttons (Edit, .... Delete), to the right which is more typical in the application.

![generic-work-show-page-idea-v2](https://user-images.githubusercontent.com/3020266/47926167-e9db0480-de8d-11e8-9d9d-4db725b1e2d6.png)
