### ISSUE TITLE
Try a new idea for the homepage layout

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#3369]
### Descriptive summary

Try something and do a quick user-test via repo managers, of an alternative layout the homepage, using standard Bootstrap components.

### Rationale

It's the first thing users see, and should be somewhat engaging.

**Comment by adamjarling** [comment]
So @chrisdaaz suggested using the repo managers Slack channel for some gut-reaction user-testing on alt layouts.  I just posted these there, to get a quick consensus on good direction, or bad direction.  Again, just tossing out ideas quickly, nothing is finalized or very thought out.  

@vantuyls @no-reply 

#### Current Layout
![hyrax-homepage-current-layout](https://user-images.githubusercontent.com/3020266/47935279-d76dc480-dea7-11e8-8a59-96c84f92427e.png)

#### Alternate Layout
![hyrax-homepage-alternate-layout-idea](https://user-images.githubusercontent.com/3020266/47935280-d76dc480-dea7-11e8-8d61-c28097fcdba2.png)

**Comment by vantuyls** [comment]
@samvera/hyrax-repo-managers

**Comment by chrisdaaz** [comment]
i like it. i always thought the home page was missing something like a hero image or welcome message.

**Comment by adamjarling** [comment]
Sounds good.  Assuming most institutions will override this and create their own homepage, I think for this minimal code addition, it hopefully conveys the message the homepage can and should be customizable.
