### ISSUE TITLE
Upgrading Hyrax makes featured works appear wrong

### ISSUE THREAD

**Issue by bess** [samvera/hyrax#3371]
### Descriptive summary

Upgrading an application from Hyrax 2.1.0 to 2.3.3 appears to have broken the display of featured works -- their thumbnails now appear twice on the main page (see attached screenshots). 

### Rationale

This is unexpected and makes the front page look wrong. 

### Expected behavior

I expect to be able to upgrade and the display of featured works should stay the same or be enhanced.

### Steps to reproduce the behavior

1. Starting with a Hyrax 2.1.0 application, I updated the Gemfile to specify Hyrax 2.3.3. I ran bundle update and deployed the results. 
2. Now the application has two thumbnail images for all featured works.

Before: 
![before](https://user-images.githubusercontent.com/65608/47968998-c670af00-e071-11e8-8186-c501a727dbca.png)

After:
![after](https://user-images.githubusercontent.com/65608/47969001-d092ad80-e071-11e8-83a1-72c69d13c66c.png)

I tried un-featuring a work and re-featuring it -- no change. Downgrading the hyrax version fixes the problem.

**Comment by chrisdaaz** [comment]
we fixed this here: https://github.com/samvera/hyrax/pull/3320 

but we should backport this to the 2.3.3 release @no-reply

**Comment by no-reply** [comment]
We're going work on getting a 2.4.0 release out containing this fix.
