### ISSUE TITLE
Alternative layout for Collections Show page

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#3376]
### Descriptive summary

Investigate an alternative way to lay out sections in the Collections show page.

### To Do:
- [x] Pull Collection title out of the panel header, and make it a standard `<h1>` page title.
- [x] Remove `btn-primary` class from all button group buttons in the current page header.
- [x] Divide page sections (Subcollections and Works) into their own Bootstrap `panel`s.
- [x] Get feedback from Repo Managers and UX Interest Group Slack channels

![collections-show-page](https://user-images.githubusercontent.com/3020266/48013571-36bb1700-e0ea-11e8-9d20-34ba84620c4d.png)

### Rationale

Request by @julesies 

### Related work

#3364

**Comment by adamjarling** [comment]
Here are some updated views:

#### Default view
![collections-show-page-new](https://user-images.githubusercontent.com/3020266/48025636-9f65bc00-e109-11e8-8586-dccc8e585866.png)

#### Search results within the page
![collections-show-page-search-results-new](https://user-images.githubusercontent.com/3020266/48025646-a5f43380-e109-11e8-8059-547fbd283070.png)

#### Original view
![collections-show-page-original](https://user-images.githubusercontent.com/3020266/48025757-eb186580-e109-11e8-87b3-f2145fc49324.png)

**Comment by adamjarling** [comment]
Another iteration based on feedback from the Repo managers on what the primary action is... adding a Work to the Collection, and not necessarily nesting collections.

![collections-show-page-add-works-featured](https://user-images.githubusercontent.com/3020266/48073614-bf968900-e1a4-11e8-9fcc-3b6c6b415ddb.png)

**Comment by julesies** [comment]
Adding slack comments over here. I think this look great, much cleaner and I'm so happy that the add work to collection buttons are more obvs! I wonder what @elrayle  thinks about whether or not adding a new vs existing items is more common, but I thought that adding a new work to a collection is the only way to confer collection based permissions, i would say we probably want to emphasize that! @elrayle am I wrong, do permissions get granted to both existing and new works IF added via the collection page???

**Comment by chrisdaaz** [comment]
from @elrayle via slack:

"• Can you switch to order of the Add/Create buttons for  subcollections so they match the order used for works.
• It would be good if the wording for the add/create buttons is similar as possible.  I think only the add subcollection button would be effected…  suggesting: Add existing collection as subcollection
• What does it look like when there is a parent collection?
• RE: removing color from buttons - I’m fine with that, but I know that color scheme is used throughout.  Are the colors being removed from buttons throughout Hyrax?  I believe red was selected for destructive actions, blue for common actions, and clear for less common actions."

**Comment by adamjarling** [comment]
@elrayle 

> "• Can you switch to order of the Add/Create buttons for subcollections so they match the order used for works.

So in the Subcollections panel footer it'd look like: 
"Create new collection as subcollection" | "Add a subcollection" ?

> • It would be good if the wording for the add/create buttons is similar as possible. I think only the add subcollection button would be effected… suggesting: Add existing collection as subcollection

Sounds good to me, I'll use your wording.

> • What does it look like when there is a parent collection?

I'll test this out and post a screen shot.

> • RE: removing color from buttons - I’m fine with that, but I know that color scheme is used throughout. Are the colors being removed from buttons throughout Hyrax? I believe red was selected for destructive actions, blue for common actions, and clear for less common actions."

There are some comments here about how to handle button coloring in the standard Bootstrap way: 
https://github.com/samvera/hyrax/pull/3367#issuecomment-435137099

I think the best approach is to use Bootstrap as close to how it's intended, given the quantity of developers working in the codebase.  Primary colored buttons (currently blue), should be the primary action button (if the only button I believe), and only one button should be primary colored when presented in a group of buttons.

I can keep destructive buttons red.

**Comment by mcdowney** [comment]
I think this has been addressed? Closing (for now).
