### ISSUE TITLE
Current View Download in Universal Viewer returns HTTP 400 error

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#3378]
### Descriptive summary

Hyrax 2.3.3

### Rationale

This appears to be a bug, but I'm not sure if it's a configuration issue or inherited from Universal Viewer.

### Expected behavior

Universal Viewer provides file download options:
- Current View
- Whole image as a JPG
- Whole image as [original file format]

All options should be functional.

### Actual behavior

Attempting to download the current view option returns a 400 error.

### Steps to reproduce the behavior

1. Upload an image to [nurax-dev](https://nurax-dev.curationexperts.com/)
2. Click the download button in UV
3. Select Current View
4. Click download.

Here's an image with the problem: https://nurax-dev.curationexperts.com/concern/images/ks65hc302

**Comment by chrisdaaz** [comment]
this should not be a blocker as this bug has been around since at least 2.1

**Comment by lfarrell** [comment]
Per the example above, https://nurax-dev.curationexperts.com/images/vq27zn51q%2Ffiles%2Fd2a2fe06-1e07-402a-8343-d4a00b4b4abb/**-617,-1,**640,480/640,480/0/default.jpg. It's asking for negative image coordinates. I don't think this is allowed by the RIIIF spec. These coordinates are out of bounds of the image and hence the 400 error.

**Comment by no-reply** [comment]
This looks like it might be a Universal Viewer (or else RIIIF) bug.

The download link works fine when the whole image is in the scope, but for some reason fails when zooming out.

**Comment by mkorcy** [comment]
I tracked this down to an issue in Hyrax::DisplaysImage due to the hard coding of the IIIFManifest::DisplayImage being hardcoded to 640x480. I should be able to provide a fix, although I'm not sure if this is moot, I was looking at nurax and it looks like 'Current View' is not in the latest hyrax.  I'm on 2.5.1

**Comment by no-reply** [comment]
the "Current View" works on `nurax-dev` today much of the manifest code has been rewritten since the last activity on this ticket.

can anyone with a running 2.9.x app check if there's anything more to do here?

**Comment by rjkati** [comment]
This seems to be fixed in Hyrax 3.0.1. Selecting "Current View" in Universal Viewer on nurax-dev opens a new tab which displays the zoomed image as a jpg. I think this is the expected behavior. @jlhardes

**Comment by jlhardes** [comment]
This bug appears to have been addressed and fixed along the way. @chrisdaaz, we think this is ready to close. Does that work for you?

**Comment by chrisdaaz** [comment]
yes, thank you
