### ISSUE TITLE
Keep view/focus on depositor summary page when switching tabs  

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3402]
### Descriptive summary
Hyrax 3.0.0rc testing   
```
QA Testing for Hyrax
Hyrax Version: 2.4.0
Hyrax Branch: master
Hyrax Revision: c41b819a6e396a5cd78c91c7b691d1bed39662ad
© 2018 Samvera-Hyrax
Nurax Version
ENV: production
SHA: 1d80945a9d26b798207eec54feef1e035336a414
Branch: 2018-11-13-10-00
Updated: 13 Nov 2018 16:00:30
```
Test: [SD_1.6](https://docs.google.com/spreadsheets/d/1Hxq3VIdKy35Hr_-OQkyiEYXZNOap8_LUbWCM6hl8oZU/edit#gid=248186373)
```
* Navigate to the home page
*Click on the "Recently Uploaded" tab
*Click on a depositor's name
*Click all links to make sure they work
```
### Rationale
Keep view/focus on depositor summary page when switching tabs  

### Expected behavior
Clicking on I) "Activity" tab II) and then "Highlighted" tab the page view /focus is kept unchanged with the top of the page showing app name (Nurax) language and login.
 
### Actual behavior
Clicking on I) "Activity" tab II) and then "Highlighted" tab the page view is changed to have the depositors name on the top of the page. 

### Steps to reproduce the behavior

Links / tabs on the depositors page work. However, clicking on I) "Activity" tab II) and then "Highlighted" tab the page view is changed to have the depositors name on the top of the page.

**Comment by chrisdaaz** [comment]
this is confirmed here: https://nurax-dev.curationexperts.com/users/gamtest7@test-dot-org

clicking between tabs forces the top of the viewport to set at the top of the `tab-content`

**Comment by chrisdaaz** [comment]
this appears to have been introduced since the 2.1 release

**Comment by dlim87** [comment]
QA - I'm not sure if I completely understand the behavior described in the original ticket, but this bug still exists:  On a user show page, clicking between the highlighted and activity pages cause it to jump around: 

![Screen Recording 2019-09-17 at 02 32 PM](https://user-images.githubusercontent.com/5492162/65081366-57820900-d958-11e9-972e-d23857c9e975.gif)

**Comment by dlim87** [comment]
This has been fixed for users which have no featured items (as demoed in the PR): 
![](https://user-images.githubusercontent.com/1331659/65915428-72fe0280-e3a1-11e9-95be-2c834131b4a3.gif)

But is still occurring (to a much less noticeable degree) for users that do have featured items:
![Screen Recording 2019-11-06 at 09 10 AM](https://user-images.githubusercontent.com/5492162/68320692-48c0f400-0075-11ea-9df9-ebfffbf800bd.gif)
