### ISSUE TITLE
Permissions are not applied to files when a work is created by proxy

### ISSUE THREAD

**Issue by crowesn** [samvera/hyrax#3416]
### Descriptive summary

Ucrate running Hyrax v2.3.3

Nurax Version 
    SHA: 9433ac9c83968d803c9413ec4e4e3315282ad088
    Branch: 2018-11-15-10-00
    Updated: 15 Nov 2018 16:00:29 

### Descriptive summary

If I'm a proxy and create a work with attached files on behalf of another user (the owner), that owner will have edit access to the work, but not to the files. __This bug was noticed locally when switching from `:inline` jobs to `:sidekiq`__. Our testing shows that the bug exists in both development and production environment modes with sidekiq running. The bug was encountered locally and on Nurax (https://nurax-dev.curationexperts.com/concern/parent/0g354f32m/file_sets/zs25x868d).

### Rationale

The owner should be able to edit file sets attached to works created on their behalf by proxies.

### Expected behavior

Filesets attached to works submitted by a proxy on behalf owner should be editable by the owner.

### Actual behavior

Filesets attached to works submitted by a proxy on behalf owner are not editable by the owner.

### Steps to reproduce the behavior

1. Ensure that job queue is running as `:sidekiq`
1. Create a work with file(s) as a proxy
1. Log in as the owner
1. Visit the show page for one of the files
1. Notice that you don't have an edit button

### Related work

Related? https://github.com/samvera/hyrax/issues/3076

**Comment by chrisdaaz** [comment]
Verified. Work owner has the edit option for the work, but not the file: 

![image](https://user-images.githubusercontent.com/24395592/48575640-1ce2b680-e8d8-11e8-9c76-009f66599cf2.png)

Clicking on the title of the file displays the fileset view but no options to edit.

**Comment by dlim87** [comment]
QA - this is still working as expected on nurax
