### ISSUE TITLE
Transfer ownership of collections

### ISSUE THREAD

**Issue by sandbergja** [samvera/hyrax#3419]
### Descriptive summary

Right now, you can transfer ownership of works in hyrax.  In this case, even though person A uploaded a work, it shows up under person B's "Your works" tab in the dashboard.  There isn't the same functionality for collections, unless I'm missing something.  It would be nice if person A could start a collection, do some work on it, and then transfer the ownership of it to person B, so that person B can have quick access to it in their "Your collections" tab.

### Rationale

Repository admins and managers often start to pre-populate collections before handing them over to other units on campus.  However, once we're done pre-populating them and are ready to hand them over to those other units, it seems like that unit should be the owner of the collection.

**Comment by no-reply** [comment]
I'm wondering if "transferring ownership" isn't the wrong thing, given the overall collection permissions ecosystem.

Post Hyrax 2.1, a Hyrax 2.1 collection type with "sharing" turned on allows a user to add another user, and then remove themselves as a "Manager" of a collection.

**Comment by no-reply** [comment]
cc: @samvera/hyrax-repo-managers

**Comment by mcdowney** [comment]
Closing for now; no-reply's comment above seems like the correct solution here.
