### ISSUE TITLE
Performance findings

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#3424]
When I create a file like this:

```ruby
# benchmark.rb
require_relative 'config/environment'
```
at the root of a hyrax application and I do:

```
$ time ruby benchmark.rb

real	0m27.175s
user	0m19.089s
sys	0m7.405s
```

I see quite a long time just to startup the application.

When I expand `benchmark.rb` to be:
```ruby
require 'stackprof'

StackProf.run(mode: :wall, out: 'profile.dump') do
  require_relative 'config/environment'
end

```

and then run:
```
ruby benchmark.rb && stackprof profile.dump
```
 
I see the following results:

```
==================================
  Mode: wall(1000)
  Samples: 15618 (58.18% miss rate)
  GC: 798 (5.11%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
     11273  (72.2%)       10043  (64.3%)     ActiveSupport::Dependencies::Loadable#require
       798   (5.1%)         798   (5.1%)     (garbage collection)
       232   (1.5%)         232   (1.5%)     #<Module:0x00007f9bcdec9378>.mechanism
       102   (0.7%)         102   (0.7%)     RDF::URI#parse
       114   (0.7%)          87   (0.6%)     Kernel#require
       177   (1.1%)          80   (0.5%)     <top (required)>
        72   (0.5%)          71   (0.5%)     RDF::Vocabulary.__prefix__
       109   (0.7%)          60   (0.4%)     RDF::Vocabulary.each
        59   (0.4%)          55   (0.4%)     <top (required)>
        53   (0.3%)          53   (0.3%)     Rails::Initializable::Initializer#before
        65   (0.4%)          47   (0.3%)     #<Module:0x00007f9bcdd12778>.new
        47   (0.3%)          46   (0.3%)     ActiveSupport::Dependencies#search_for_file
     11492  (73.6%)          46   (0.3%)     Bundler::Runtime#require
        47   (0.3%)          45   (0.3%)     Rails::Application#routes_reloader
        46   (0.3%)          45   (0.3%)     Rails::Paths::Path#expanded
        60   (0.4%)          45   (0.3%)     <top (required)>
        61   (0.4%)          44   (0.3%)     <top (required)>
        42   (0.3%)          42   (0.3%)     RDF::Vocabulary.to_s
       143   (0.9%)          39   (0.2%)     <top (required)>
        33   (0.2%)          33   (0.2%)     Module#delegate
        33   (0.2%)          33   (0.2%)     TZInfo::ZoneinfoDataSource#enum_timezones
        38   (0.2%)          31   (0.2%)     Rails::Application#initialize
       214   (1.4%)          31   (0.2%)     ActiveSupport::Dependencies#load_file
       118   (0.8%)          30   (0.2%)     <top (required)>
       209   (1.3%)          28   (0.2%)     <module:Helpers>
        36   (0.2%)          27   (0.2%)     <top (required)>
        60   (0.4%)          25   (0.2%)     <top (required)>
        74   (0.5%)          24   (0.2%)     <top (required)>
        29   (0.2%)          23   (0.1%)     <module:Sprockets>
        23   (0.1%)          23   (0.1%)     RDF::Util::Cache::ObjectSpaceCache#delete
```

This indicates to me that we're spending almost all of the time with `Bundler::Runtime#require`

**Comment by jcoyne** [comment]
Compare this to the same findings in a vanilla Blacklight:
```
23:36 $ time ruby benchmark.rb

real	0m1.986s
user	0m1.486s
sys	0m0.402s

```
$ stackprof profile.dump
==================================
  Mode: wall(1000)
  Samples: 1598 (2.38% miss rate)
  GC: 231 (14.46%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       261  (16.3%)         261  (16.3%)     #<Module:0x00007feffa221ce8>.storage_to_output
       231  (14.5%)         231  (14.5%)     (garbage collection)
       107   (6.7%)         107   (6.7%)     Bootsnap::LoadPathCache::RealpathCache#find_file
        89   (5.6%)          75   (4.7%)     RuboCop::NodePattern::Compiler#run
       483  (30.2%)          54   (3.4%)     Kernel#require_with_bootsnap_lfi
        61   (3.8%)          36   (2.3%)     Kernel#require
       104   (6.5%)          32   (2.0%)     RuboCop::NodePattern::Macros#def_node_matcher
       196  (12.3%)          22   (1.4%)     Kernel#require_with_bootsnap_lfi
        21   (1.3%)          21   (1.3%)     TZInfo::ZoneinfoDataSource#enum_timezones
        21   (1.3%)          20   (1.3%)     Module#delegate
        15   (0.9%)          15   (0.9%)     Bootsnap::LoadPathCache::LoadedFeaturesIndex#key?
       110   (6.9%)          15   (0.9%)     Bootsnap::CompileCache::ISeq::InstructionSequenceMixin#load_iseq
        15   (0.9%)          15   (0.9%)     Rails::Paths::Path#expanded
        14   (0.9%)          13   (0.8%)     Rails::Application#routes_reloader
        15   (0.9%)          12   (0.8%)     Gem::StubSpecification#data
        30   (1.9%)          12   (0.8%)     Kernel#require_with_bootsnap_lfi
        12   (0.8%)          12   (0.8%)     Rails::Application#initialize
       187  (11.7%)          12   (0.8%)     Kernel#require_with_bootsnap_lfi
       251  (15.7%)          11   (0.7%)     <top (required)>
        15   (0.9%)          11   (0.7%)     #<Module:0x00007feff803f350>.from_rubylibdir
        11   (0.7%)          11   (0.7%)     MonitorMixin#mon_enter
        11   (0.7%)          11   (0.7%)     Bundler::Runtime#setup_manpath
      1004  (62.8%)          10   (0.6%)     Bootsnap::LoadPathCache::LoadedFeaturesIndex#register
        16   (1.0%)          10   (0.6%)     Set#initialize
        13   (0.8%)          10   (0.6%)     MIME::Type.simplify_matchdata
         9   (0.6%)           9   (0.6%)     Bootsnap::LoadPathCache::LoadedFeaturesIndex#strip_extension
        42   (2.6%)           9   (0.6%)     Bootsnap::CompileCache::ISeq::InstructionSequenceMixin#load_iseq
        55   (3.4%)           9   (0.6%)     #<Module:0x00007feff804d1d0>.setup
         9   (0.6%)           9   (0.6%)     Set#add
        92   (5.8%)           8   (0.5%)     Kernel#require_with_bootsnap_lfi
```

**Comment by no-reply** [comment]
Thanks @jcoyne.

Does it seem like this is mainly due to the larger dependency tree? Is there action you'd propose based on these results?

**Comment by jcoyne** [comment]
@no-reply I'm not sure what to do about this.  I suspect it's just too many dependencies.  I wonder if things wouldn't get better if we took a look at moving things out of engines (QA, noid-rails) into external services (using Docker containers perhaps?).
