### ISSUE TITLE
Add warning popup when automatically reseting admin set visibility 

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3433]
### Descriptive summary
Add warning when automatically setting admin-set visibility options. 

### Rationale
Show a warning pop-up after pressing `Save changes` button and automatically setting admin-set visibility options.

### Expected behavior
Automatic changes to visibility of a admin-set raises an warning pop-up. 

### Actual behavior
No warning is displayed, when 'Visibility' automatically is set to `All settings allowed`

### Steps to reproduce the behavior
!. create an admin-set collection 
2. set  'Visibility' to `Private` 
3. change 'Release' to  `Allow depositor to choose settings` or `Depositor must choose embargo`, 
4. Save changes 

'Visibility' is automatically set to `All settings allowed`

Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
We're considering this for inclusion in the Hyrax 3.0.0 project, but wanted to check in with others about the desirability of this feature request.

  1. How do we feel about the interface for updating the admin set permissions, given this behavior? Should we consider other re-works of that interface?
  1. If not, is the addition of a pop-up widely considered desirable?

cc: @samvera/hyrax-repo-managers @vantuyls

**Comment by vantuyls** [comment]
I  think the behavior of the system makes sense right now. the popup, i assume, would be the normal in-browser message that we already see throughout the system (not a new window pop up).

This interface, though, is not in great shape. something we'd hoped to address (or begin to) with Permissions work on the roadmap. I think we ought to consider changes to this area of Hyrax in the context of a broader UI/UX overhaul.

**Comment by mcdowney** [comment]
Closing for now as working as expected
