### ISSUE TITLE
Admin set: order of workflow options changes upon save 

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3434]
### Descriptive summary
Hyrax v3.0.0beta testing on nurax 

### Rationale
I expect a consistent ordering of options in the ui 

### Expected behavior
edit adminset ui: order of the work-flow options is kept after saving changing to ' One-step mediated deposit workflow' option 

### Actual behavior
order of the work-flow options changes in ui

### Steps to reproduce the behavior

1. create 'Admin set' collection'
2. go to workfow tab 
3. select 'One-step mediated deposit workflow'
4. press 'Save changes'
 
### Related work

Link to related tickets or prior related work here.

**Comment by chrisdaaz** [comment]
can't reproduce. i'm seeing no change in the order of workflow options:

![image](https://user-images.githubusercontent.com/24395592/48868447-36d03d80-ed9f-11e8-9ca8-1bf4c33bd0d1.png)

![image](https://user-images.githubusercontent.com/24395592/48868456-4059a580-ed9f-11e8-8156-52e5aca07790.png)
