### ISSUE TITLE
Depositor can't see his submited 'private' work under one-step admin-set

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3435]
### Descriptive summary
Hyrax Version: 3.0.0.pre.beta1
Hyrax Branch: master
Hyrax Revision: 892c70712350a5583a51ad4c5cfec000d07b75de

### Rationale and  Expected behavior
Depositor should see all its work including private ones when submitting under one-step deposit admin set during review process, not only after the manager requests a change/approves that work the depositor get immediate access back. 

### Actual behavior
see https://github.com/samvera/hyrax/issues/3435#issuecomment-440288143 
After the manager requests a change/approves that work the depositor get immediate access back. 

### Steps to reproduce the behavior
as non admin user with depositor rights  
1. submit a new, private work  into an one-step admin set 

### Related work

Link to related tickets or prior related work here.

**Comment by chrisdaaz** [comment]
verified and related to https://github.com/samvera/hyrax/issues/857

**Comment by chrisdaaz** [comment]
this also shipped with 2.1 fyi

**Comment by laritakr** [comment]
I believe this is a nurax issue. When I look at the workflow definition in nurax, it doesn't match the workflow in hyrax. 

https://github.com/curationexperts/nurax/blob/master/config/workflows/mediated_deposit_workflow.json#L20-L21

https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/templates/mediated_deposit_workflow.json.erb#L20-L22

@chrisdaaz can someone please get this corrected and verify if the issue still exists after a re-deploy?

**Comment by laritakr** [comment]
I worked with @bess to update the workflows on nurax-dev, and I believe that this is working as expected. 

@chrisdaaz or @no-reply can you confirm and close this issue?

**Comment by laritakr** [comment]
Fixed. Requires workflow update to make it work in existing app.
