### ISSUE TITLE
Endless review loop when submitting work to one step admin set 

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3436]
### Descriptive summary
Hyrax Version: 3.0.0.pre.beta1
Hyrax Branch: master
Hyrax Revision: 892c70712350a5583a51ad4c5cfec000d07b75de

### Rationale
Endless review loop when submitting work to one step admin set when the user has both, depositor and manager role.  

### Expected behavior
users with manager + depositor role can approve their own works submitted in one step deposit admin sets 

### Actual behavior
Endless review loop when submitting work to one step admin set when the user has both, depositor and manager role.  
User (manager role) can not see that work under  `Review Submissions`, even if that user has admin rights .
Work is listed  under thttps://nurax-dev.curationexperts.com/?locale=en#recently_uploaded (logged in user with joint manager + deposit roles) 
 
### Steps to reproduce the behavior

1. user has depositor an manager role in a one step deposit admin set 
2. submit new work 
3. click 'Review and Approval ' in the  work view 
4. select approve option
5. work is not deposited but 'Review and Approval' is still present in the work view 
6. ...
7 ....

### Related work

Link to related tickets or prior related work here.

**Comment by jmfrenzel** [comment]
https://nurax-dev.curationexperts.com/concern/generic_works/p2676v645?locale=en

**Comment by chrisdaaz** [comment]
i also tested this on `nurax-stable` and it appears that this bug shipped with 2.1

**Comment by vantuyls** [comment]
@chrisdaaz @jmfrenzel i'm a little puzzled. as an admin, you always see the review and approval panel on any work, correct. the work linked above shows as deposited. can one of you clarify?

**Comment by chrisdaaz** [comment]
@vantuyls these are not admin users, these are general users who have the `manager` and `depositor` role on an admin set

**Comment by vantuyls** [comment]
bad wording on my part. I meant Manager. So, if you are a Manager on an admin set, you will see the review panel no matter what, I believe. So even though the item is deposited, the review panel will still appear. Is that what we see happening here? if not, can someone further describe?

**Comment by jmfrenzel** [comment]
@vantuyls, I can confirm https://github.com/samvera/hyrax/issues/3436#issuecomment-476244757 
The review panel is kept documenting the process. Understanding this feature, the comment and change request option in the review panel make sense for further communication with the depositor after the initial approval. In that sense "endless loop" is a feature not a bug.
The issue can be closed. 
Btw. could not find this feature documented.

**Comment by vantuyls** [comment]
@chrisdaaz agreed?

**Comment by chrisdaaz** [comment]
@vantuyls up, thanks @jmfrenzel
