### ISSUE TITLE
Deactivate Leases for Selected does not work

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3441]
### Summary 
QA Testing for Hyrax
Hyrax Version: 3.0.0.pre.beta1
Hyrax Branch: master
Hyrax Revision: 892c70712350a5583a51ad4c5cfec000d07b75de 

WIn/Linux Chrome/Firefox 
### Related work
https://github.com/curationexperts/nurax/issues/316

**Comment by chrisdaaz** [comment]
unable to reproduce on `nurax-dev` with windows/ firefox.
