### ISSUE TITLE
Deactivate Embargoes for Selected does not work

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3442]
### Descriptive summary

The "Deactivate Embargoes for Selected" function under the manage embargoes page does not work.
QA Testing for Hyrax
Hyrax Version: 3.0.0.pre.beta1
Hyrax Branch: master
Hyrax Revision: 892c70712350a5583a51ad4c5cfec000d07b75de 

### Rationale
The "Deactivate Embargoes for Selected" function is a useful management tool for repository managers.
### Expected behavior
When a user selects works/files/etc, under the expired active embargoes on the manage embargoes page, and then clicks on the "Deactivate Embargoes Selected" the works/files leases will be deactivated.
### Actual behavior
When a user selects works/files/etc, under the expired active embargoes tab on the manage embargoes page, and then clicks on the "Deactivate Embargoes for Selected" the works/files users are then presented with an error page.

### Steps to reproduce the behavior

1.    As repository admin go here - https://nurax-dev.curationexperts.com/embargoes?locale=en#expired
2.   Select multiple works/files
3.    Click on Deactivate Embargoes for Selected button

### Related work
#3441

**Comment by chrisdaaz** [comment]
i was unable to reproduce this with windows/firefox. when i tried on `nurax-dev` i got a success message:

![image](https://user-images.githubusercontent.com/24395592/48866924-1baeff00-ed9a-11e8-99d7-dbc1c997b30c.png)
