### ISSUE TITLE
Unable to transfer works after disabling, then re-enabling the feature as admin

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#3443]
### Descriptive summary

Hyrax 3.0.0beta -- nurax-dev

### Rationale

This bug report affects a a feature flipper setting.

### Expected behavior

Administrators should have the ability to turn off and turn back on features via the features configuration dashboard:

![image](https://user-images.githubusercontent.com/24395592/48867763-e5bf4a00-ed9c-11e8-9ac2-16aa4260ec93.png)

### Actual behavior

When turning off the `Transfer works` option, then turning it back on, I am blocked from transfering works to other users. It is as if the switch is stuck on off.

### Steps to reproduce the behavior

1. Log in as an admin
2. Go to Dashboard -> Settings -> Features
3. Turn "Transfer works" off
4. Turn "Transfer works" back on
5. Attempt to transfer a work as an admin or a user

### Related work

Link to related tickets or prior related work here.

**Comment by dlpierce** [comment]
Unable to reproduce.
