### ISSUE TITLE
save widget jumps around when scrolling

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#345]
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hackmastera](https://github.com/hackmastera)**
_Wednesday Feb 01, 2017 at 17:31 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/3044_

----

This behavior has been around since Sufia 7.2 or so.

**Comment by hackmastera** [comment]
it is worse in sufia 7.3 than 7.2, maybe because of the sticky footer? it has an extra spot of jumpiness when you hit the bottom of the screen.

**Comment by vantuyls** [comment]
issue cannot be reproduced. presumably resolved sometime over the past half year.
