### ISSUE TITLE
Adding a user to collection removes unsaved changes in other tabs

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#3454]
### Descriptive summary

Version: Hyrax 3.0

When editing a collection, the user makes changes to the Branding and Discovery tabs, but does not click "Save changes".  If the user adds another user to the same collection via the Sharing tab, the page refreshes and the changes to the branding and discovery tabs are lost.  The user does not receive a warning that prompts them to save their changes when leaving the active tab.

### Rationale

The user should be alerted that their changes will not save when they navigate away from the active tab.

### Expected behavior
User should see a warning message before leaving the Branding and Discovery tabs that prompts them to click the "Save changes" button.

### Steps to reproduce the behavior

1. Navigate to an existing collection and click the "edit collection" button.
2. Upload a new collection banner, or change the discovery settings.  Do NOT click "Save Changes."
3. Click the "Sharing" tab and add a new user to the collection.
4. Navigate back to Step 2 and see if your changes are still present.

**Comment by j-dornbusch** [comment]
It may be a side effet of #3469 .
As Javascript is not running, the page is reloaded : the contents of the text fields are preserved but not the file upload controls.

**Comment by blancoj** [comment]
This was closed by PR https://github.com/samvera/hyrax/pull/3910
