### ISSUE TITLE
Title metadata property does not need to be facetable

### ISSUE THREAD

**Issue by wickr** [samvera/hyrax#3457]
### Descriptive summary

Current `core_metadata.rb` includes `:title` as `:facetable` but this is not expected behavior and is not serving any purpose.

### Expected behavior

Title is not declared as facetable.

### Actual behavior

Title is declared as facetable but not actually faceted.

### Related work

I didn't find any other title facet related code (like config.add_facet_field ) or prior issues.

**Comment by wickr** [comment]
After looking at something else, I was reminded that `:facetable` sets which Solr fields something is saved as (here as _sim), and whether or not a field is faceted obviously happens elsewhere.

Should title be `:stored_searchable` instead of `:facetable` ?

**Comment by no-reply** [comment]
i'm inclined not to fuss with this individually, but would be open to a more comprehensive audit of indexing behavior post-Wings.
