### ISSUE TITLE
Conduct usability testing on Collection Dashboard and Work Dashboard

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#3458]
### Descriptive summary

Usability testing of the Collection Dashboard and the Work Dashboard should be conducted to learn what is confusing about each dashboard and between the two dashboards for collection managers/admin users. Identify changes that can be prioritized to improve usability and understanding of these views (terminology changes, contextual help, different viewing configurations, etc).

### Expected behavior

Users can view either dashboard (or a combined dashboard/some other view) and understand context for settings related to a work in its collections or a collection of works.

### Actual behavior

Each dashboard is currently only viewable separately and is not connected to the other dashboard so connections between works and collections settings take effort to think through and cause confusion.

**Comment by no-reply** [comment]
closing this as something we can't act on at the Hyrax level. i'd love to see an institution or the community perform this kind of testing, but i think it's fair to say we'd need a bigger organizational effort to put that together.
