### ISSUE TITLE
"Works created" link on profile page does not return any results

### ISSUE THREAD

**Issue by j-dornbusch** [samvera/hyrax#3478]
### Descriptive summary

Hyrax v3.0.0-beta1
In the "profile" page of the Dashboard, the number of created works is correctly displayed. But by clicking on it, you obtain a blank list of result.

### Expected behavior

The number of items in the search page should match the number displayed in the profile page.

### Steps to reproduce the behavior

1. Create a work
2. Go to you profile page
![profile_bug](https://user-images.githubusercontent.com/13169449/51679776-1b242600-1fe0-11e9-8370-ae8b2955592f.png)
3. Click on the "Created works" link
![profile_bug1](https://user-images.githubusercontent.com/13169449/51679789-29724200-1fe0-11e9-9a59-7f80c006244e.png)

The only explanation I found is that the solr request contains a local qf parameter.
With this parameter isolated the Solr response is empty :
```
http://localhost:8983/solr/hydra-development/select?q={!qf=depositor_ssim}dornbusch@ehess.fr
```
With a more basic syntax it works : 
```
http://localhost:8983/solr/hydra-development/select?q=depositor_ssim:dornbusch@ehess.fr
```

### Related work
Once this problem is solved, there will be a second one.
If you change the user key field in hydra.rb : 
```
config.user_key_field = Devise.authentication_keys.first # change this
```
it is not taken into account by the partial : 
https://github.com/samvera/hyrax/blob/b5c6605917c01c51b4504f7e27999146fc584713/app/views/hyrax/users/_vitals.html.erb#L12
The filtering uses `user.to_s`, which is equivalent to email.

**Comment by vantuyls** [comment]
the count on Works Created in the profile does not match the count of items displayed when the link is selected (for my account on nurax-dev, works created shows 20 items but the results of selecting the link show 18 items.)

**Comment by crisr15** [comment]
"Works created" link works and takes me to search results.  But number of search results listed on the profile page (43) did not match the number that showed up on the search list (42).  

Should this stop this from passing QA? Do we need to make another ticket?

**Comment by jeremyf** [comment]
In my reading of the code, I have a possible explanation.

For the Profile page, the partial (`./app/views/hyrax/users/_vitals.html.erb:11`) that renders the `44` calls the following code:

```ruby
# ./app/helpers/hyrax/dashboard_helper_behavior.rb
def number_of_works(user = current_user)
  Hyrax::WorkRelation.new.where(DepositSearchBuilder.depositor_field => user.user_key).count
rescue RSolr::Error::ConnectionRefused
  'n/a'
end
```

For the resulting page, which renders `43` results, we get there via the `link_to_field` method found here:

```ruby
# ./app/helpers/hyrax/hyrax_helper_behavior.rb:106
def link_to_field(name, value, label = nil, facet_hash = {})
  label ||= value
  params = { search_field: name, q: "\"#{value}\"" } if name != ''
  state = search_state_with_facets(params, facet_hash)
  link_to(label, main_app.search_catalog_path(state))
end
```

When rendering the number on the Profile page, it appears only the `{ depositor: user.user_key }` is used.

The link on the Profile page to the search results passes two facets to the `link_to_field` method: `{ generic_type: "Work", depositor: user.to_s }`.

So, it could be:

1)  An inconsistency in `user.user_key` and `user.to_s`
2)  The fact that the Profile page does not also send `{ generic_type: "Work" }` as a facet
3)  The `Hyrax::WorkRelation#allowable_types` (which is `Hyrax.config.curation_concerns`) is a super-set of objects that have `generic_type: "Work"`

**Comment by MariaStarPower** [comment]
When I click on **Works created** from the Profile page,  I am directed to the results page where I can see the works created by the user, **except** that the results display **one less** work than the number of works displayed on the Profile page.

<details>

Link to Works created in the Profile page (displays 44 works):

<img width="1485" alt="Image 2020-09-09 at 5 14 19 PM" src="https://user-images.githubusercontent.com/32848057/92667149-fae1d180-f2bf-11ea-934e-dbc284211ee2.png">

Results page (displays 43 works):

<img width="1486" alt="Image 2020-09-09 at 5 15 22 PM" src="https://user-images.githubusercontent.com/32848057/92667204-22d13500-f2c0-11ea-974a-dd4255537863.png">

</details>
