### ISSUE TITLE
Hyrax::Statistics::TermQuery treats reindexing for Works (using #update_index) as if it has been indexed multiple times

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/hyrax#3491]
### Descriptive summary

Reindexing any Work (such as a `GenericWork`) using `#update_index` returns unexpected results when querying using the `Hyrax::Statistics::Works::ByResourceType` (or anything derived from `Hyrax::Statistics::TermQuery`).  It seems to count the resource more than once (as if it's been indexed multiple times):

```ruby
GenericWork.create(title: ['test'], resource_type: ['Conference Proceeding']).save!
GenericWork.create(title: ['test'], resource_type: ['Conference Proceeding']).save!
GenericWork.create(title: ['test'], resource_type: ['Image']).save!
GenericWork.create(title: ['test'], resource_type: ['Journal']).save!

service = Hyrax::Statistics::Works::ByResourceType.new
JSON.parse(service.query.to_json)
=> [{"label"=>"Conference Proceeding", "data"=>2}, {"label"=>"Image", "data"=>1}, {"label"=>"Journal", "data"=>1}]
GenericWork.all.each {|w| w.update_index}
JSON.parse(service.query.to_json)
[{"label"=>"Conference Proceeding", "data"=>3}, {"label"=>"Image", "data"=>2}, {"label"=>"Journal", "data"=>2}]
```

**Comment by jrgriffiniii** [comment]
@cjcolvar discovered this originally, and found that this was related to the `terms` `requestHandler` (which, by default, uses the [solr.TermsComponent](https://lucene.apache.org/solr/guide/7_6/the-terms-component.html)).  He also discovered that this _could_ be resolved by passing `optimize` in the Solr query, but this might come with some performance issues: https://lucidworks.com/2018/06/20/solr-and-optimizing-your-index-take-ii/

**Comment by rjkati** [comment]
Closing since a solution to this issue is given in the comments and no further action is recommended.
