### ISSUE TITLE
Batch edit should ask user if they want to propagate visibility changes down to members

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#351]
Refs https://github.com/projecthydra/sufia/issues/2450 (HT: @hackmastera)

Hyrax already has some machinery for handling conditional permission percolation for single works. When a user changes the visibility of a work, they are redirected to an interstitial page at which point they can choose, or not, to copy permissions down to member filesets (using the `InheritPermissionsJob`). We should consider repurposing this in the batch edit context, and expanding it to also ask about copying permissions down to member works (recursively)?

**Comment by no-reply** [comment]
Closing this pending broader work on batch edits.
