### ISSUE TITLE
Webmock blocks Capybara from disconnecting from Selenium sessions after completing feature tests

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/hyrax#3514]
This doesn't occur consistently.  Normally Capybara transmits a `DELETE` request to the Selenium server.  This can (but it should not) be treated as a HTTP request which must be stubbed within the scope of a test suite (this is a configuration of WebMock: https://thoughtbot.com/blog/how-to-stub-external-services-in-tests#disable-all-remote-connections)
This can be observed in https://circleci.com/gh/samvera/hyrax/506

**Comment by rjkati** [comment]
Discussion in #3516 indicates that this is fixed. Closing this ticket but please re-open or create a new ticket if it occurs again.
