### ISSUE TITLE
Updating Spec Tests to use Light Weight Collection Factory - Unfinished

### ISSUE THREAD

**Issue by mtribone** [samvera/hyrax#3520]
### Descriptive summary

During the Hyrax/Valkylrie sprint we were working on making the test suite more performant. One of those tasks were to go through the spec tests and update any that used `create` to `build` for the collection factory and utilize the `with_permission_template` to improve performance. 

Old factory
https://github.com/samvera/hyrax/blob/master/spec/factories/collections_factory.rb

New factory
https://github.com/samvera/hyrax/blob/master/spec/factories/collections.rb

### Rationale

Using `create` is very expensive and persists the objects, while using `build` just has it to use in memory. Making this update _should_ make the test suite faster.

### Expected behavior

Faster tests

### Actual behavior

Unfinished work from the sprint. Needs to be completed.

### Related Issues
- #2940 
- #2593 

### Related work
-  #3517 
-  #3483
-  #3487
-  #3488
-  #3490

**Comment by no-reply** [comment]
going to go ahead and close this. it's still interesting work, but i think not worth tracking as a ticket
