### ISSUE TITLE
Hyrax development environment installation fails with sqlite3 related error

### ISSUE THREAD

**Issue by j-dornbusch** [samvera/hyrax#3536]
### Descriptive summary

`rake engine_cart generate` fails on a fresh install of Hyrax development environment or or on an old installation that used to work until now.

```/home/xxxxxx/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/connection_specification.rb:188:in `rescue in spec': Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)```

This issue seems related the February 4th update of the sqlite3 gem (1.4.0).

### Expected behavior

`rake engine_cart:generate` should work out of the box

### Actual behavior

You have to force sqlite version in hyrax.gemspec.
```spec.add_development_dependency 'sqlite3', '~> 1.3.0'```
Then `bundle update` and `rake engine_cart:generate` will work as usual.

### Steps to reproduce the behavior

Follow installation guide : https://github.com/samvera/hyrax/wiki/Hyrax-Development-Guide#generate-test-app

**Comment by j-dornbusch** [comment]
@cjcolvar My IDE said it: with your fix, the example is now too long.... Rubocop does not agree...

**Comment by no-reply** [comment]
@j-dornbusch is this still happening for you after `bundle update engine_cart`?

**Comment by j-dornbusch** [comment]
@no-reply I confirm that after restoring hyrax.gemspec and updating engine_cart I am able to launch `rake engine_cart.generate` successfully
