### ISSUE TITLE
Deleting current proxy immediately after authorization fails

### ISSUE THREAD

**Issue by chuckgreenman** [samvera/hyrax#3542]
### Descriptive summary

Behavior observed on Hyrax v2.3.3 as well as on Nurax.

On the Manage Proxies page, after adding a proxy the user pops up under current proxy.  If you click on the "Delete Proxy" button the proxy will be removed from the Current Proxies button.  After refreshing the page, the proxy remains.

### Rationale

While normally you wouldn't want to immediately remove a proxy, it could be necessary in the event you accidentally add someone as there proxy.  In that case it's especially important to remove the proxy rather than fail silently which could allow the accidentally authorized user to make changes on their behalf.

### Expected behavior

Clicking Delete Proxy, actually removes that proxy

### Actual behavior

Click Delete Proxy removes proxy from page, but fails silently due to a bad path.

### Steps to reproduce the behavior

1. Visit the Manage Proxies page.
2. Authorize a user as a proxy
3. Refresh the manage proxies page
4. See the proxy reappear under Current Proxies

### Related work

We discovered this on our samvera/hyrax application here at the University of Cincinnati, and [integrated this change](https://github.com/uclibs/ucrate/pull/661/files) to fix it.

**Comment by blancoj** [comment]
@chuckgreenman I could not reproduce on my local machine.  Is this still an issue?

**Comment by julesies** [comment]
We can reproduce this on nurax-dev and nurax-stable @blancoj

**Comment by chuckgreenman** [comment]
I can also still reproduce it. @blancoj [here's the code](https://github.com/uclibs/ucrate/pull/661/files) we implemented locally to change fix the problem.  I can rework this a little for hyrax if the approach is okay for the project's style.
