### ISSUE TITLE
CreateWithRemoteFilesOrderedMembersActor test is unstable

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/hyrax#3549]
The following test has failed randomly on CircleCI: https://github.com/samvera/hyrax/blob/master/spec/actors/hyrax/actors/create_with_remote_files_ordered_members_actor_spec.rb#L43

After restarting a build, this passed without error.  Please see https://github.com/samvera/hyrax/pull/3548#issuecomment-465611983 for an example of this occurrence.

**Comment by cjcolvar** [comment]
I'm stumped...I haven't been able to reproduce this locally and I don't have any ideas about why this error would be happening.  @mbklein @no-reply any ideas?
Should we just mark this test as [optional](https://github.com/samvera/hyrax/blob/5a9d1be16ee1a9150646384471992b03aab527a5/spec/support/optional_example.rb) so it can pass or fail without affecting the build?

**Comment by mbklein** [comment]
No clue. What kind of failure was it? Since the build was re-run, I can't see the old log any more.

**Comment by cjcolvar** [comment]
@mbklein There was an autoload issue which I addressed here: https://github.com/samvera/hyrax/pull/3537
But the failing test now has to do with a bad RDF namespace:
```
Failure/Error: fs.save!

Ldp::BadRequest:
  35b076c317f1e7mode:namespaces-http://scholarsphere.psu.edu/ns#
./app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb:72:in `block in create_file_from_url'
./app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb:68:in `new'
./app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb:68:in `create_file_from_url'
./app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb:59:in `block in attach_files'
./app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb:50:in `each'
./app/actors/hyrax/actors/create_with_remote_files_ordered_members_actor.rb:50:in `attach_files'
./app/actors/hyrax/actors/create_with_remote_files_actor.rb:16:in `create'
./spec/actors/hyrax/actors/create_with_remote_files_ordered_members_actor_spec.rb:48:in `block (6 levels) in <main>'
./spec/actors/hyrax/actors/create_with_remote_files_ordered_members_actor_spec.rb:47:in `block (5 levels) in <main>'
```
Taken from this build: https://circleci.com/gh/jrgriffiniii/hyrax/112

**Comment by mbklein** [comment]
So... wait. There's a flappy test where the failure is based on an unrecognized namespace?

**Comment by cjcolvar** [comment]
Yup, as far as I can tell.

**Comment by hackmastera** [comment]
Proposal is to revert code introduced in https://github.com/samvera/hyrax/pull/3477 as a step toward diagnosing the problem. That PR doesn't reference an issue. @mbklein is there an issue we should create or reopen to track the work of that PR?

**Comment by mbklein** [comment]
There should definitely be an issue – this is going to be a showstopper issue for anyone using `CreateWithRemoteFilesOrderedMembersActor` in a real-world setting.

**Comment by hackmastera** [comment]
@mbklein thank you!
