### ISSUE TITLE
Creating a work within two collections allows invalid combination

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#3557]
### Descriptive summary

When creating a work from within a collection of a type that does not allow multiple membership, if a second collection is added on the relationship tab, the work is created as a member of both collections. **This should be reported as an error via the multiple_membership_checker.** It appears that the error messages only appear when both collections are of the same collection type.

### Rationale

Multiple membership is not allowed for collection types without the option selected.

### Expected behavior

Error message should be thrown via the multiple_membership_checker.

### Actual behavior

Work is created as a member of two collections. 

### Steps to reproduce the behavior

1. Create Collection type with "MULTIPLE MEMBERSHIP" checked.
2. Create Collection A of above collection type.
3. Create Collection type without "MULTIPLE MEMBERSHIP" checked.
3. Create Collection B of above collection type.
4. Display Collection B.
5. Select "Deposit new work through this collection", and begin to create the work.
6. On relationship tab, Collection B should already be selected. 
7. Key "Collection A" in Collections dropdown, select it, and click "Add".
8. Save work.

Work is created as a member of both collections, with no error message.

**Comment by laritakr** [comment]
Closing... according to the [worker documentation](https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/collections_membership_actor.rb#L81-L85), this is expected behavior.

**Comment by blancoj** [comment]
@elrayle  I had a conversation with @no-reply about this issue.  After discussing it a little bit, it seems like this is not really an issue, but expected behavior. Could you confirm that?  Thank you!

**Comment by no-reply** [comment]
cc: @elrayle 

my understanding of the Multiple Membership restriction is that it prevents Objects from being added to multiple collections *of the same type*. That seems consistent with the behavior described here. 

Otherwise, every object would be restricted to only being a member of its Admin Set, yes?

If this is correct, I'd like to close this.

**Comment by no-reply** [comment]
actually, closing this pending correction.
