### ISSUE TITLE
BaseActor replace #destroy with Valkyrie

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#3575]
### Descriptive summary

Use Valkyrie and the related valkyrie_metadata_adapter configuration to destroy curation_concern valkyrie resource. 

The method should iterate through related collections, remove the curation_concern as a member of the collection, update the collections indexed metadata, and then destroy the curation_concern.

### Rationale

This functionality should replace the expected behavior of the BaseActors destroy method.

### Related work

See #3569

**Comment by no-reply** [comment]
we're not planning to continue work on the actor stack.
