### ISSUE TITLE
PCDM::Object - files relationship defined through AF directly_contains

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3576]
### Code

lib/hydra/pcdm/models/concerns/object_behavior.rb

### Model Usage

* PCDM::Object (and by extension Works::Work, Works::FileSet)

### Active Fedora Usage

* calls AF directly_contains method to create the files relationship.

**Comment by no-reply** [comment]
is your thinking that we should change this? what's the status of this relative to current work on Files?
