### ISSUE TITLE
Operations that fail should store error information

### ISSUE THREAD

**Issue by bbranan** [samvera/hyrax#358]
When an operation is executing via a worker, its status should be kept up-to-data in the database so that its ultimate result can be seen in the Operations UI panel. If an operation fails, the reason for the failure should be included in the message column, so that it can also be displayed in the UI.

Example: If the operation is creating a work, but the work has no value for the title field, the error generated should be stored in the database as the message under the operation, and the operation status should be changed to "failed" (or something similar.)

**Comment by jcoyne** [comment]
I don't think this ticket is actionable without specific completion criteria.  There are an infinite number of ways to fail, so let's enumerate the ones we care about.

**Comment by mjgiarlo** [comment]
What we need to make this ticket actionable: go through all the operations' jobs and write up the specific failure conditions to capture. We will work on this after MVP.

**Comment by no-reply** [comment]
Blocked by deeper consideration of #159

**Comment by no-reply** [comment]
Closing due to desire to deprecate Operations.
