### ISSUE TITLE
Works::Work inherits from AF::Base

### ISSUE THREAD

**Issue by rotated8** [samvera/hyrax#3591]
### Code

lib/hydra/works/models/work.rb

### Active Fedora

  inherits `ActiveFedora::Base`

### Related issues

**Comment by no-reply** [comment]
I don't think this is necessarily an issue.

Currently, we generate `Valkyrie::Resource` classes directly from the `AF::Base` resources. I think this can stay as-is until we're at a point where we can deprecate Works altogether.
