### ISSUE TITLE
PCDM::PCDMIndexer extends ActiveFedora::IndexingService

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3601]
### Code

lib/hydra/pcdm/pcdm_indexer.rb #generate_solr_document

### Active Fedora Usage

* extends ActiveFedora::IndexingService... `class PCDMIndexer < ActiveFedora::IndexingService`
* calls #member_ids method created when defining the ActiveFedora relationship named members using the AF #ordered_aggregation method
* calls #ordered_object_ids defined in pcdm_behavior.rb (#3590)
* calls #member_of_collection_ids defined in pcdm_behavior.rb (#3594)

### Related issues

* #3571 PCDM::Collection/Object - members relationship defined through AF ordered_aggregation
* #3590 PCDM::Collection/Object - #ordered_objects method using AF relationship reflection #ordered_members
* #3594 PCDM::Collection/Object - #member_of_collection_ids method using using AF relationship reflection #member_of_collections

**Comment by no-reply** [comment]
is `PCDMIndexer` used anywhere in Hyrax, or should we close this out?
