### ISSUE TITLE
work#reload refactor to operate in Valkyrie context

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#3604]
### Descriptive summary

Calls to `#reload` should use the `valkyrie_metadata_adapter` to fetch/reload the resource from the backend. 

There are many of these calls throughout the specs, but there are a few found in the application as well.

https://github.com/samvera/hyrax/blob/master/app/jobs/create_derivatives_job.rb#L14
https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/file_set_actor.rb#L74

### Proposed Solution

Instead of these `#reload` calls, replace with a local call to something like the following:

```
def reload
  adapter = Valkyrie::MetadataAdapter.find(Hyrax.config.valkyrie_metadata_adapter)
  resource = adapter.query_service.find_by(id: id)
  adapter.resource_factory.from_resource(resource: resource)
end
```

**Comment by no-reply** [comment]
instead of reworking `#reload` itself, we should simply replace the existing calls with a more explicit fetch of the valkyrie resource.

for the test suite cases, the best thing may be to refactor the test whenever the production code changes to support valkyrie.
