### ISSUE TITLE
PCDM::Validators::PCDMObjectValidator raises ActiveFedora::AssociationTypeMismatch

### ISSUE THREAD

**Issue by rotated8** [samvera/hyrax#3607]
### Code

lib/hydra/pcdm/validators/pcdm_object_validator.rb

### Active Fedora

raises `ActiveFedora::AssociationTypeMismatch`

### Related issues

**Comment by no-reply** [comment]
i think this is okay, since these validators are for ActiveFedora models and won't be used by Valkyrie.
