### ISSUE TITLE
Hyrax::CollectionBehavior replace functionality with Valkyrie collection behavior equivalents

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#3608]
### Descriptive summary

CollectionBehavior has a tight coupling to ActiveFedora and needs a lot of rework to make use of the the valkyrie_metadata_adapter QueryService and Persister. 

https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/collection_behavior.rb

### Rationale

Replace the coupling to ActiveFedora with related to Valkyrie functionality

### Related work

#3609 : `#add_members`
#3610 : `#add_member_objects`
#3611 : `#member_objects`
#3612 : `#member_object_ids`
#3613 : `ActiveFedora.index_field_mapper.solr_name`
#3865: Set `use_valkyrie` to true

**Comment by hweng** [comment]
What the Acceptance Criteria for this ticket?
