### ISSUE TITLE
Hyrax::CollectionBehavior#add_members

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#3609]
### Descriptive summary

_edit_ : There is a comment in the code that suggests we deprecate the method as it seems that it is no longer used.

Replace `Hyrax::CollectionBehavior#add_members` with the valkyrie_metadata_service.query_service` equivalent.
https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/collection_behavior.rb#L53-L56

### Rationale

Query the backend to find all of the resources that need to be associated with the collection.

### Proposed Solution

```
    def add_members(new_member_ids)
      return if new_member_ids.blank?
      adapter = Valkyrie::MetadataAdapter.find(Hyrax.config.valkyrie_metadata_adapter)
      members << adapter.query_service.find_many_by_ids(ids: new_member_ids)
    end
```

Refs: #3608

**Comment by laritakr** [comment]
Fixed via #3841
