### ISSUE TITLE
Hyrax::CollectionBehavior ActiveFedora.index_field_mapper.solr_name references

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#3613]
### Descriptive summary

There are multiple references to `ActiveFedora.index_field_mapper.solr_name` in the Hyrax::CollectionBehavior that all need to be replaced. 

https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/collection_behavior.rb#L92
https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/collection_behavior.rb#L174
https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/collection_behavior.rb#L179

### Rationale

Decouple the behavior of determining the proper Solr index field name from ActiveFedora to Valkyrie.

See #3608

**Comment by laritakr** [comment]
Completed via #3858
