### ISSUE TITLE
collection "views" don't work after choosing (masonry, list, etc)

### ISSUE THREAD

**Issue by davidschober** [samvera/hyrax#3626]
### Descriptive summaryI

n a collection, the view buttons on the right side of the screen stop working,
reloading the page doesn't help.

Note: this was tested locally and on Nurax

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Expected behavior
All view buttons should work regardless of which view you are currently in

### Actual behavior
Once you click on Masonry view the Gallery, List and Slideshow buttons stop working

### Steps to reproduce the behavior

   - open a collection view.
   - click through the 'view' buttons on the right side of the page.
   - Once you click on the Masonry view, all other view buttons will stop working, unless you back out.

### Related work

Link to related tickets or prior related work here.

**Comment by wickr** [comment]
Example on Nurax: https://nurax-dev.curationexperts.com/collections/pk02c993w?locale=en&view=masonry

'Sort by' and 'Relevance' form controls also are obscured.

**Comment by dlim87** [comment]
QA - you can freely switch between all the view types in a collection now
