### ISSUE TITLE
wings persister: optimistic locking

### ISSUE THREAD

**Issue by hackartisan** [samvera/hyrax#3673]
make these pending specs pass

**Comment by hackmastera** [comment]
PR was linked to wrong ticket.

**Comment by jrgriffiniii** [comment]
I'm not certain how to retrieve the active lock token used to compare with the current lock token for the resource.  The `Valkyrie::Resource` uses the underlying `ActiveRecord` ORM for this: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/locking/optimistic.rb#L95 and https://github.com/samvera/valkyrie/blob/master/lib/valkyrie/persistence/postgres/persister.rb#L32.

However, the `Valkyrie::Resource` is not persisted using this persister, and this behavior must be offered here: https://github.com/samvera/hyrax/blob/master/lib/wings/valkyrie/persister.rb#L22

I have been making progress with my branch: https://github.com/jrgriffiniii/hyrax/tree/issues-3673-jrgriffiniii-locking

**Comment by no-reply** [comment]
this is supported!
