### ISSUE TITLE
README doesn't link to samvera.github.io documentation

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#3675]
### Descriptive summary

For the Hyrax README - it seems to never link to the samvera.github.io anywhere. It links a lot to hyr.ax and to this internal wiki, but the feature guide and much of the tech documentation is being updated at samvera.github.io  

### Rationale

It's unclear what docu is current/authoritative. 

Could the README get a look over and at the minimum link to both places?

**Comment by vantuyls** [comment]
would dropping links into the Help and Managing a Hyrax Application sections suffice?

**Comment by julesies** [comment]
yeah a good first step...Coud we add also for Feature List to link to the feature guide on samvera.github.io not the hyr.ax under this sentence... For non-technical documentation about Hyrax, see the Hyrax documentation site.

**Comment by mjgiarlo** [comment]
**Related note**: We are moving away from `hyr.ax` as the canonical form of the Hyrax docs site. Instead, we are using `hyrax.samvera.org`. I have made the necessary changes to the Hyrax docs site (in this repo's `gh-pages` branch) and I have a README PR that needs review: https://github.com/samvera/hyrax/pull/3727

**Comment by laritakr** [comment]
Update https://github.com/samvera/hyrax/blob/gh-pages/CONTRIBUTING.md with information regarding adding documentation to samvera.github.io
