### ISSUE TITLE
operators on relationships defined for valkyrie resources

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3676]
### Descriptive summary

For ActiveFedora::Base models, defining a relationship allowed use of `<<` and `+=` operators.  How can we support or convert the use of these operators for relationships defined using `attribute` method for valkyrie resources?

### Rationale

Support or convert code to support valkyrie versions of model methods and relationships.

##### AF Definition
```
      indirectly_contains :member_of_collections,
                          has_member_relation: Vocab::PCDMTerms.memberOf,
                          inserted_content_relation: RDF::Vocab::ORE.proxyFor,
                          class_name: 'ActiveFedora::Base',
                          through: 'ActiveFedora::Aggregation::Proxy',
                          foreign_key: :target,
                          type_validator: Validators::PCDMCollectionValidator
```

##### AF addition operators

```
  af_object.member_of_collections << new_parent_collection1
  af_object.member_of_collections += new_parent_collection2
```

##### Valkyrie Definition

```
        attribute :member_of_collection_ids, ::Valkyrie::Types::Set.of(::Valkyrie::Types::ID)
```

##### Valkyrie addition operators

```
  val_resource.member_of_collection_ids << new_parent_collection1.id
  val_resource.member_of_collections_ids += new_parent_collection2.id
```

### Question

How to convert from AF to Valkyrie while supporting both in code?

### Related work

PR #3636 - define member_ids as ordered
Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
Is this resolved, or is there still an issue here?

I'm not sure I fully understand the need to support both approaches. If it's needed, why not call a service and resolve the difference with a factory method + polymorphism?

```ruby
membership_manager = CollectionMembershipManager.for(model: val_resource) 
# or membership_manager = CollectionMembershipManager.for(model: af_object)

membership_manager <<  new_parent_collection1.id
membership_manager +=  new_parent_collection2.id
membership_manager <<  new_parent_collection3
membership_manager +=  new_parent_collection4
```

**Comment by no-reply** [comment]
@hackartisan is this one we can close as wont-do?

**Comment by hackartisan** [comment]
@no-reply the reason I wasn't sure was because I didn't know if there was any backwards compatibility concern.

**Comment by no-reply** [comment]
@hackartisan i haven't considered that backwards compatibility between Valkyrie and Active Fedora models is a desired outcome. in general, we've resisted adding convenience methods or business logic to valkyrie models during this process.

**Comment by tpendragon** [comment]
In my role as Valkyrie technical lead I'm closing this, mostly because `<<` breaks a bunch of stuff in `Dry-rb` land. We're already breaking the rules allowing `+=`. If you add this to the Valkyrie models you'll regret it near-instantly.
