### ISSUE TITLE
Should wings query find_inverse_references_by assume the reference stores the uri?

### ISSUE THREAD

**Issue by hackmastera** [samvera/hyrax#3712]
Currently it does. But `member_ids` holds the id, not the uri. Are there hyrax conventions? Should we set some? Should we try to make the implementation accept either?

**Comment by revgum** [comment]
This was addressed in #3783 by adding an `OR` to the query service to consider either the URI or the ID. The discussion, and current thinking, is captured in "Collection Query Service" comment in https://github.com/samvera/hyrax/issues/3784#issuecomment-495301603
