### ISSUE TITLE
LDP::BadRequest errors are raised inconsistently for the Hyrax::Actors::CreateWithRemoteFilesOrderedMembersActor test suite

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/hyrax#3729]
Please see https://circleci.com/gh/jrgriffiniii/hyrax/216#tests/containers/8 for one occurrence.

**Comment by cjcolvar** [comment]
I think this is a duplicate of https://github.com/samvera/hyrax/issues/3549

**Comment by jrgriffiniii** [comment]
It is indeed a duplicate of #3549
