### ISSUE TITLE
No menu margin on mobile due to normalize.css?

### ISSUE THREAD

**Issue by mccallum** [samvera/hyrax#3741]
### Descriptive summary

Version 3.0.0.pre.beta2. 

### Rationale

On mobile size of responsive, .navbar-nav has no left margin:
<img width="635" alt="navbar" src="https://user-images.githubusercontent.com/1591022/55839480-dc7d1280-5adc-11e9-9933-74624e722584.png">

Likely due to normalize.css (https://github.com/necolas/normalize.css/) within Bootstrap CSS which ends up with: 
```
.navbar-nav {
    margin: 7.5px -15px; 
}
```

### Expected behavior

Healthy margin to nav menu on all screen sizes.

### Actual behavior

Healthy margin only on desktop -- mobile slams it against left side of screen.

### Steps to reproduce the behavior

1. Open any page on smartphone.
2. Look at main menu (.navbar) of "Home," "About," etc.

### Related work

This is a toe-dipping issue for me. Eager for coming feedback, etc.

**Comment by dlim87** [comment]
![Image 2019-09-30 at 4 04 11 PM](https://user-images.githubusercontent.com/5492162/65922960-fc123b00-e39b-11e9-9406-589c5af00bc1.png)
It now maintains a good margin, even on very low horizontal resolution
