### ISSUE TITLE
Crowded/Overlapping Dashboard view when active user activity

### ISSUE THREAD

**Issue by ShanaLMoore** [samvera/hyrax#3768]
### Descriptive summary

When frequent/multiple user activity, Dashboard view becomes unusable

### Rationale

User experience is severely impacted

### Expected behavior
To list out activity in a readable manner. Possibly paginate activity list?

### Actual behavior
Dashboard view becomes unreadable and unusable 

### Steps to reproduce the behavior
 
1. Log in as a non admin user
2. Click Dashboard. Click Works. Click "Create batch of works".
3. Select "Generic Work", and add multiple files (at least 5). Save
4. Go back to the Dashboard view. You may need to refresh the page several times are background jobs are processing the uploads. The multiple activity over crowds the Dashboard view page (see screenshot)

Screenshot from Chrome Mac. Also tested on Safari Mac, Chrome Windows, Firefox Windows
<img width="1046" alt="Screen Shot 2019-04-29 at 2 37 36 PM" src="https://user-images.githubusercontent.com/10081604/56928663-642ac100-6a8c-11e9-9ff9-0c784f66c9e5.png">

**Comment by chrisdaaz** [comment]
replicated on windows/firefix:

![image](https://user-images.githubusercontent.com/24395592/56928861-b32d2200-6a9d-11e9-9ff7-7470bccfcf28.png)

**Comment by fritzfreiheit** [comment]
This appears to be a CSS problem.

**Comment by kellyChex** [comment]
<img width="812" alt="Screen Shot 2019-07-16 at 10 02 01 AM" src="https://user-images.githubusercontent.com/9621070/61314186-e46de200-a7b0-11e9-8534-19d54451cf1c.png">

Overcrowding confirmed as fixed.
