### ISSUE TITLE
Write a production build guide

### ISSUE THREAD

**Issue by hackartisan** [samvera/hyrax#377]
A high-level overview of what you'll need on your production machine and how everything connects, similar to https://github.com/projecthydra-labs/hydradam/wiki/Production-Installation%3A-Overview

**Comment by downwriter** [comment]
After discussion at Developer Congress 2019, the focus will be to include Production Installation documentation on the samvera.github.io page.

**Comment by downwriter** [comment]
https://samvera.github.io/service-stack.html

**Comment by downwriter** [comment]
Branch for samvera.github.io created for Production Installation Overview.

Incorporating the Production Concerns from Hyrax Management Guide: https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#production-concerns

Will review with samvera.github.io owner
