### ISSUE TITLE
Skip to Content link doesn't always set keyboard focus

### ISSUE THREAD

**Issue by sandbergja** [samvera/hyrax#3774]
### Descriptive summary

In Hyrax 2.5.0 and Firefox, I can press the tab key and keyboard focus goes to the "Skip to Content" link.  I can press enter, and the visual focus of the screen does move down to the content of the page.  However, when I press tab again, keyboard focus goes right back to the "Skip to Content" link.

### Rationale

Currently, users who navigate hyrax apps using a keyboard aren't reliably well-served by the "Skip to Content" link.  Depending on the browser they use, it could skip to content for visual purposes, but not for navigation purposes.

### Expected behavior

I expect that the "Skip to Content" link also sets keyboard focus to the content, regardless of browser.

### Actual behavior

The "Skip to Content" link does not set keyboard focus to the content in Firefox.  It does in Chrome.

### Steps to reproduce the behavior

Go to Firefox, and press Tab - Enter - Tab.

### Related info

An interesting article here, including mobile considerations: https://axesslab.com/skip-links/

Another interesting article: https://www.bignerdranch.com/blog/web-accessibility-skip-navigation-links/

**Comment by dlim87** [comment]
This works as would be expected for most of the client facing pages. However, on most of the dashboard pages, it appears to focus outside of the content, since tabbing goes to my browser's bookmark toolbar (on Firefox 71.0b7, on a mac)

**Comment by MariaStarPower** [comment]
**Does not pass** - The "Skip to Content" link does not appear when I tab through the site on Firefox.

Firefox browser:

![image](https://user-images.githubusercontent.com/32848057/100941408-6ea20d80-34ae-11eb-827e-1f328633a7d1.png)

**Comment by bkeese** [comment]
In Firefox 83.0 on Ubuntu linux, the Skip To Content link appears as expected. Perhaps this is a Mac/Firefox issue?

**Comment by jlhardes** [comment]
In Firefox 83 on Mac OS 10.14.6, the Skip To Content link appears when tabbing and works as expected - Tab to get the Skip To Content link to show, Enter to activate the Skip To Content link, then Tab is tabbing through the content links on the page below the main navigation and search box. On Macs, there is a need to have Full Keyboard Access set to All Controls in System Preferences > Keyboard > Shortcuts (this doesn't seem to be set by default and makes a difference using the keyboard in Firefox).
