### ISSUE TITLE
Replace calls to ActiveFedora.index_field_mapper.solr_name in app (removes 54 refs to ActiveFedora)

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3794]
### Descriptive summary

This issue involves removing references to `ActiveFedora.index_field_mapper.solr_name`.

### ActiveFedora code

Active Fedora call being replaced...

Example 1:  has_model from app/models/concerns/hyrax/solr_document_behavior.rb
```
      first(ActiveFedora.index_field_mapper.solr_name('has_model', :symbol)).constantize
```

Example 2: depositor from app/models/concerns/hyrax/solr_document_behavior.rb
```
      val = first(Solrizer.solr_name('depositor'))
```

To locate, search code for `ActiveFedora::SolrQueryBuilder.construct_query(` in `app/search_builders`.

### Replacement code

Example 1: has_model from app/models/concerns/hyrax/solr_document_behavior.rb
Switch to use Valkyrie::Persistence::Solr::Queries constant
```
      first(Valkyrie::Persistence::Solr::Queries::MODEL).constantize
```

Example 2: depositor from app/models/concerns/hyrax/solr_document_behavior.rb
Switch to using Solrizer to generate the name.
```
      val = first(Solrizer.solr_name('depositor'))
```

For some instances, you can compare [master app/search_builders](https://github.com/samvera/hyrax/tree/master/app/search_builders) with [valkryie-6 app/search_builders](https://github.com/samvera/hyrax/tree/valkyrie-6/app/search_builders) to see how it was changed in that branch.

More exploration may be needed to insure the field being converted to a solr_name is supported by Solrizer.

### Considerations

* I only found one instance matching the pattern shown in example 1.  The remaining matched that pattern in example 2.
* Not all diffs between master and valkryie-6 branch are necessarily related to removing references to ActiveFedora.  The valkyrie-6 branch has not been kept in sync with master.
* For the ActiveFedora.index_field_mapper.solr_name, many of the calls at master didn't exist when the valkyrie-6 branch was active.
* Do NOT replace this call if found in lib/wings directories.

### Impact on Testing

Not expected to require test changes.  All tests should pass with the replacement code.

**Comment by cjcolvar** [comment]
I wouldn't recommend using `Solrizer`: https://github.com/samvera/maintenance/issues/19

**Comment by no-reply** [comment]
Agreed about Solrizer.

Instead, we should consider in-lining solr name generation to Hyrax.

**Comment by jrgriffiniii** [comment]
With deprecating Solrizer and looking to remove references to `ActiveFedora.index_field_mapper`, I can offer to complete my progress on the following: https://github.com/samvera/hyrax/compare/master...jrgriffiniii:issues-3794-jrgriffiniii-active-fedora-index_field_mapper

**Comment by jrgriffiniii** [comment]
This should be close to completion.  I have been struggling with a lack of Coveralls reporting for test coverage analysis, and I'm trying to determine what has yet to be tested fully on https://github.com/samvera/hyrax/compare/master...jrgriffiniii:issues-3794-jrgriffiniii-active-fedora-index_field_mapper

**Comment by hackmastera** [comment]
What about just replacing these with the actual value of solr field that you want?
