### ISSUE TITLE
Replace calls to ActiveFedora.id_field with 'id' (removes 5 refs to ActiveFedora)

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3798]
### Descriptive summary

This issue involves removing references to `ActiveFedora.id`.

### ActiveFedora code

Active Fedora class being replaced...

Example from app/search_builders/hyrax/catalog_search_builders.rb
```
      "{!join from=#{ActiveFedora.id_field} to=file_set_ids_ssim}#{dismax_query}"
```

To locate, search code for `ActiveFedora.id` in `app`.

### Replacement code

This is a simple replacement of `ActiveFedora.id_field` with `'id'`.  There are places in the code where this change has already been made.

Example from app/search_builders/hyrax/catalog_search_builders.rb
```
      "{!join from=id to=member_ids_ssim}#{dismax_query}"
```

### Considerations

* Do NOT replace this call if found in `lib/wings` directories.

### Impact on Testing

Not expected to require test changes.  All tests should pass with the replacement code.

**Comment by no-reply** [comment]
I think it would be best not to hard code `'id'` currently, `id_field` is configurable, and it would be best to keep that feature while deprecating the old way of setting it.
