### ISSUE TITLE
Improve interaction between save button and file uploads in work form

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#380]
Part of the work done to close out the Sufia 7.3.0 release included the following JavaScript changes, which fixed couple error conditions involving how in-progress uploads interact with the save button in the work form:

https://github.com/projecthydra/sufia/pull/3069

The downside of this implementation is that the save button does *appear* to be clickable before all uploads have finished, but it's not actually clickable. (IOW, this isn't a bug but rather a UX enhancement.)

The save button should be disabled (not merely unclickable via `preventDefault()`) while any uploads are running.

@jcoyne made the following suggestions about how we might implement this:
> I think we need a `isSaveButtonActive` method that checks both form validity and `this.uploads.inProgress`. It should be triggered when a upload starts or finishes (the `fileuploadstarted` and `fileuploadstopped` events), or the checkbox is checked, or the metadata is changed.

**Comment by awead** [comment]
There's an additional problem, whereby if you add files and then delete all of them, the files requirement still shows that it's met. We fixed this by making use of a `fileuploaddestroyed` callback in Uploaded.js. See: https://github.com/psu-stewardship/scholarsphere/commit/d5e52b4cf

**Comment by adamjarling** [comment]
So uploading a folder of files, this looks like the problem.  The "Save" button is disabled while the first file is uploading, then some check is enabling it, and so forth.  

And as the issue mentions, looks like the form's submission is still being prevented in a multi-upload.

https://screencast.com/t/sMKZbA9G
