### ISSUE TITLE
Remove visibility attribute from Wings::ModelTransformer::ActiveFedoraResource

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/hyrax#3806]
Visibility as an attribute should be explicitly removed from https://github.com/samvera/hyrax/blob/master/lib/wings/model_transformer.rb#L181 given the work which was introduced in https://github.com/samvera/hyrax/pull/3797

**Comment by no-reply** [comment]
visibility and ACLs in wings have been completely reworked since this ticket was written; closing.
