### ISSUE TITLE
Valkyrize FileActor including the ability to save the file using valkyrie wings

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3813]
### Descriptive summary

Update FileActor to use valkyrie to save the file and connect it to the FileSet.  This will require additional infrastructure to track the File metadata using a Valkyrie Resource, copying the resource metadata to the file's metadata_node, and making the attachments between the file and fileset that work for wings and non wings adapters.

**Comment by no-reply** [comment]
i think this one might be closed?
