### ISSUE TITLE
Replace calls to ActiveFedora::Base.uncached (removes 2 refs to ActiveFedora)

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3824]
#### First Pass

#3823 -defines Hyrax::ObjectNotFoundError

#### Second Pass

Depending on the implementation selected, the second pass may have a dependency on #3800.

----
### Descriptive summary

`ActiveFedora::Base.uncached` temporarily turns off the ActiveFedora cache while executing the passed in block.  It restores the prior state of caching once the block completes.  There does not appear to be equivalent behavior for Valkyrie metadata adapters.  Some thought will need to go in to the way to maintain this for the Wings adapter, but potentially make it a null-op for other metadata adapters.

### ActiveFedora code

Active Fedora call being replaced...

Example from app/models/concerns/hyrax/ability.rb
```
        fedora_object = ActiveFedora::Base.uncached do
```

To locate, search code for `ActiveFedora::Base.uncached`.

#### First pass

Define Hyrax::Base wrapper method...

```
module Hyrax
  class Base
    def self.uncached(&block)
      ActiveFedora::Base.uncached &block
    end
end
```

_NOTE: If app/models/hyrax/base.rb does not exist, create it as part of this issue._

Example from app/models/concerns/hyrax/ability.rb
```
        fedora_object = Hyrax::Base.uncached do
```

_NOTE: This might be a good time to rename `fedora_object` to `resource`.

### Second pass

There does not appear to be a Valkyrie equivalent for this.  There will need to be some thought around how to transform this method for use with all Valkyrie adapters.

**Exploration required.**

### Considerations

* Do NOT replace this call if found in `lib/wings` directories.

### Impact on Testing

Not expected to require test changes.  All tests should pass with the replacement code.

### Related Work

PR #3790 Valkyrize calls to ActiveFedora::Base.find 

PR #3804 does a similar first part creating a wrapper for ActiveFedora for ActiveFedora::SolrService.  The second part of replacing the ActiveFedora code has not yet been addressed, at the time of the writing of this issue.

There will be similar issues created that are also replacing ActiveFedora::Base methods.

**Comment by laritakr** [comment]
These are used only within the nesting index adapter, so this issue should probably wait to be part of a general plan for indexing.

**Comment by elrayle** [comment]
Encapsulated in `Hyrax::Base.uncached` in PR #4205
