### ISSUE TITLE
Replace ActiveFedora usage in NestingIndexAdapter

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#3829]
### Descriptive summary

Issue #3790 was tasked with removing direct calls to ActiveFedora::Base.find throughout the application. This issue relates specifically to the Nesting Indexing functionality, because simply replacing calls with Valkyrie functions will not be adequate. Nesting Reindexing needs to be redesigned along with the rest of the indexing.

### Background

The NestingIndexAdapter is the bridge from Hyrax to the `Samvera::NestingIndexer`. Simply replacing the method calls to ActiveFedora with Valkyrie calls will not be an adequate replacement for non-AF data. 

Other documentation: https://samvera.github.io/nested-indexing.html

### Rationale

Nested Indexing is done as a separate step, following the initial indexing in order to add additional fields to the solr document. These fields are needed for validation within Hyrax (to prevent circular nesting), as well as for the ability to create custom nested searches. 

The nested reindexing adapter, as implemented in Hyrax, is dependent on the indices already existing for the related objects. It was also implemented as it was (see `app/models/concerns/hyrax/collection_nesting.rb`) to minimize the number of times nested reindexing happens (each object save in AF triggers numerous reindexes of the object). 

The methods are built as they are because they are totally dependent on the underlying Fedora structure and ActiveFedora methods. 
- `uncached` when used, was required simply because of how ActiveFedora handles transactions. It was caching results of prior finds, and not returning current data. This will most likely be unnecessary outside of ActiveFedora.
- the methods in `each_perservation_document_id_and_parent_ids`, such as `descendant_uris` are used to support the override of `ActiveFedora::Base.reindex_everything`. Obviously there will need to be a new way to reindex an entire system.

Once we have a new way of indexing for Valkyrie, probably will need to create various Nesting Index Adapters as well. There is no one-size-fits-all adapter.

### Related Tasks

https://github.com/samvera/hyrax/issues/3800
https://github.com/samvera/hyrax/issues/3824

**Comment by no-reply** [comment]
We're going to want to just re-implement nested indexing in the newer valkyrie indexers called for by #3800, i think.
