### ISSUE TITLE
Transfer ownership has a dependency on proxy deposit 

### ISSUE THREAD

**Issue by geekscruff** [samvera/hyrax#3836]
### Descriptive summary

If proxy deposits is disabled, trying to transfer ownership of a work will fail with an authorisation error. Presumably this is happening here https://github.com/samvera/hyrax/blob/master/app/controllers/hyrax/transfers_controller.rb#L12

### Rationale

I don't believe there should be a dependency between these two features. Nominating a proxy and transferring ownership are two distinct actions.

### Expected behavior

I should be able to transfer ownership.

### Actual behavior

I am redirected to the homepage with an authorisation error.

### Steps to reproduce the behavior

1. Disable proxies in the feature flipper
2. Go to 'my works' choose a work and hit 'transfer ownership' in the dropbown.

**Comment by dlim87** [comment]
QA - this is working as described
