### ISSUE TITLE
Deprecate feature to configure indexing for a property when defined in model

### ISSUE THREAD

**Issue by hackmastera** [samvera/hyrax#3863]
### Descriptive summary

Instead people will need to write indexers that explicitly handle each property.  

### Rationale

Valkyrie models do not allow this type of configuration. Indexing this way is a blocker for removing active fedora dependency.

### Related work

#3800

**Comment by no-reply** [comment]
This is to deprecate the following index configuration style:

```ruby
property :title, predicate: RDF::DC.title do |index|
  index.as :discoverable, :stored_searchable
end
```

in favor of:

```ruby
class MyWork < ActiveFedora::Base
  self.indexer = MyWorkIndexer
end
```
