### ISSUE TITLE
Wings persister `delete` method does not remove relationships

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#3873]
### Descriptive summary

Wings persister `delete` method deletes only the given Fedora object. It does not remove the related access controls and member of collections relationships.

### Rationale

The Active Fedora Converter method `convert` applies Active Fedora relationships to a resource via methods `apply_depositor_to(af_object)`, `add_access_control_attributes(af_object)`, `convert_members(af_object)`, and `convert_member_of_collections(af_object)` in order to appropriately map between af_objects and Valkyrie::Resources. 

When we delete a resource, the mapping needs to remove all of these associated relationships as well. 

### Expected behavior

Deleting a resource will remove the object from Fedora, along with its access controls and membership relationships. 

### Actual behavior

The object is deleted from Fedora but the access controls and relationships remain.

### Related work

See comments on https://github.com/samvera/hyrax/pull/3868

**Comment by no-reply** [comment]
I'm not sure we want the Wings adapter to do this extensive cleanup. Other adapters won't be able to do this, so I think we'll need to build out other patterns for deleting resources with appropriate cleanup in the main codebase.
