### ISSUE TITLE
fixedsticky CSS broken?

### ISSUE THREAD

**Issue by aploshay** [samvera/hyrax#3891]
### Descriptive summary

In hyrax v2.5.0: the `position: sticky` value for the `fixedsticky` class is not taking effect on `<div id="savewidget>` in the edit interface, as the `col-sm-4` class takes greater precedence and specifies `position: relative`.

The overall result is the widget stays at the top of the page, instead of floating downwards if the user expands "Additional Fields" and scrolls down, as the `fixedsticky` class is intended to do.

My current workaround is to modify [the CSS for `fixedsticky`](https://github.com/samvera/hyrax/blob/master/app/assets/stylesheets/hyrax/_fixedsticky.scss#L2-L8) from a `.fixedsticky` block to `div.fixedsticky` since the greater specificity gives it greater precedence and overrules the `position` value from `col-sm-4`.

I tried to confirm/deny this is present in newer hyrax versions, but the current instructions for spinning up a test app are broken? #3886

**Comment by no-reply** [comment]
@samvera/hyrax-ui-ux-advisors 
can someone reproduce this on nurax?

**Comment by aploshay** [comment]
Oh, interesting -- it's _not_ present on the [Nurax test site](https://nurax-dev.curationexperts.com/concern/generic_works/new?locale=en).  There, `fixedsticky` is being loaded with higher priority than `col-sm-4`/`col-xs-12`. while it's the opposite in our own Hyrax-based app.

**Comment by no-reply** [comment]
@aploshay any idea what's going on? possibly fixed in Hyrax 3.0?

**Comment by aploshay** [comment]
Thanks for the follow-up.  I looked at this again, at [the sequence in which Nurax is loading css assets](https://github.com/curationexperts/nurax/blob/master/app/assets/stylesheets/application.css#L13-L15) versus [the sequence ESSI was using](https://github.com/IU-Libraries-Joint-Development/essi/blob/67a989cc2638fd0a8e91612335262e8170c53d17/app/assets/stylesheets/application.scss#L13-L16), and found that re-sequencing ESSI's to require `hyrax` last resolved the issue.  Sorry for the false alarm!  Closing the issue.
