### ISSUE TITLE
Relationships that have ids but not an id or ids method are not converted to the valkyrie resource

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3904]
### Descriptive summary

Relationships that have `_ids` appended for the valkyrie resource attribute but do not have an equivalent `_id` or `_ids` property on the active fedora object, fail to copy over the IDs.  The potential relationships that are effected are determined by method `relationship_keys_for`.

### Rationale

All relationships should be converted over to the Valkyrie resource.

### Expected behavior

When an ActiveFedora FileSet with files and original file set is transformed into a Valkyrie resource, the resource should have file_ids and original_file_ids set to the ids from the ActiveFedora FileSet.  For both of these, I believe they should be converted to Valkyrie IDs.

### Actual behavior

When an ActiveFedora FileSet with files and original file set is transformed into a Valkyrie resource, the resource has `file_ids=[]` and `original_file_ids=[]`.

### Steps to reproduce the behavior

Need to write test to check these tranformations.

1. Use test to setup the ids in an ActiveFedora FileSet for files and original_file by adding a file to the file set
2. Use test to check that the ids were transformed into the Valkyrie resource

### Related work

PR #3902 Fixes a problem in the valkyrie id to fedora id matcher and needs to be merged prior to fixing this issue.

**Comment by elrayle** [comment]
For a fileset, this produces...

| resource attribute | af _ids | af _id | af .map(&:id) | af .id | pluralize attrname | convert to Valkyrie ID? |
| ------------------ | ------ | ------ | ------------- | ----- | ---------- | -- |
| "list_source_ids" |  |  | | f23a69e2-7d02-4b55-b4f8-6ed2fb4b0890/list_source  | | ? |
| "ordered_member_proxy_ids" |  |  | ? |  | YES | ? |
| "related_object_ids" | ? |  | ? |  | YES | ? |
| "member_of_collection_ids" | ? |  | ? |  | YES | ? |
| "file_ids" |  |  | "f23a69e2-7d02-4b55-b4f8-6ed2fb4b0890/files/3bcbc7a3-2ee9-4950-b8c7-c5be38d2a043" |  | YES | ? |
| "original_file_ids" |  |  |  | "f23a69e2-7d02-4b55-b4f8-6ed2fb4b0890/files/3bcbc7a3-2ee9-4950-b8c7-c5be38d2a043" | NO | ? |
| "thumbnail_ids" |  |  | ? | ? | NO | ? |
| "extracted_text_ids" |  |  | ? | ? | NO | ? |

**Comment by elrayle** [comment]
For a work, `#relationship_keys_for` produces...

| resource attribute | af _ids | af _id | af .map(&:id) | af .id | pluralize attrname | convert to Valkyrie ID? | comment |
| ------------------ | ------ | ------ | ------------- | ----- | ---------- | -- | -- |
| "member_ids" | USE | | could use | | YES | YES | |
| "list_source_ids" |  |  | | USE  | no | ? | should this be converted? |
| "ordered_member_proxy_ids" | USE | | | | YES | ? | should this be converted? |
| "related_object_ids" | ? |  | ? |  | YES | YES? | |
| "member_of_collection_ids" | ? |  | ? |  | YES | YES? | [] even if the work is in a collectio |
| "file_ids" |  |  | USE |  | YES | YES? | |
| "access_control_ids" |  | USE |  | could use | no | YES? | |
| "representative_ids" | | USE |  | could use | no | YES? | |
| "thumbnail_ids" |  |  | ? | ? | no | YES? | |
| "rendering_ids" | ? |  | ? | | no | YES? | |
| "admin_set_ids" |  | USE |  | could use | no | YES? | |
| "embargo_ids" |  | ? |  | ? | no | YES? | |
| "lease_idsc" |  | ? |  | ? | no | YES? | |

NOTE: "member_ids" and "member_of_collection_ids" are deleted before using this list of keys to create attributes in the valkyrie resource.
But they are included in the list when converting attributes from the active fedora object into the valkyrie resource (in #attributes method).

For a work, example ids...

| resource attribute | example ID |
| ------------------ | ------ |
| "member_ids" | member_ids = ["b8fe387d-1dd0-469e-9245-21b234683cfa"] |
| "list_source_ids" | list_source.id = "f23a69e2-7d02-4b55-b4f8-6ed2fb4b0890/list_source" |
| "ordered_member_proxy_ids" | ? |
| "related_object_ids" |  |
| "member_of_collection_ids" |  |
| "file_ids" |  |
| "access_control_ids" | |
| "representative_ids" | |
| "thumbnail_ids" |  |
| "rendering_ids" |  |
| "admin_set_ids" | admin_set_id ="3db7af5d-7f02-4124-8aec-0620dd5dfa22" |
| "embargo_ids" |  |
| "lease_idsc" |  |

**Comment by no-reply** [comment]
this may be out of date. it's hard to be sure because the steps to reproduce are a bit vague. but at least the behavior described around `file_set` and `original_file` isn't current.

**Comment by no-reply** [comment]
this is addressed systematically in #4825
