### ISSUE TITLE
Create CC mixins with deprecation warnings.

### ISSUE THREAD

**Issue by tpendragon** [samvera/hyrax#391]
Some CC mixins with the appropriate deprecation warnings would help significantly with migration to Hyrax 2.0.

**Comment by mjgiarlo** [comment]
@tpendragon Do you have particular mixins in mind?

**Comment by no-reply** [comment]
It feels a bit like the ship has sailed on this one.

I'd support any backwards compatibility PRs on 1.x to ease migration from CC/Sufia, but lets keep any tickets concrete and narrowly scoped.
