### ISSUE TITLE
Use Environment variables for Hyrax configuration

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#3916]
### Descriptive summary

It's a [best practice](https://12factor.net/config) to store application configuration in the environment. Hyrax currently makes this hard for its dependent applications, by generating a large number of hard-coded configurations into the application. In places where environment variables are used, we sometimes use arbitrarily different variables depending on the Rails env (e.g. `SOLR_DEVELOPMENT_PORT` vs `SOLR_TEST_PORT` vs a hard-coded port in production(!)).

Instead, we should normalize on using environment variables across the board, and using the same ones regardless of `RAILS_ENV`.

### Rationale

Hyrax should set the example for its applications, and encourage best practices among its adopters.

**Comment by downwriter** [comment]
https://github.com/railsconfig/config

do we want to include above?

**Comment by no-reply** [comment]
@downwriter Can you say more?

I think this is mostly unrelated to the ENV issue (is that correct?). I also have the vague recollection that i stopped using `railsconfig/config` and other third-party configuration gems when `config_for` got added to Rails. But I can't remember what all I wanted from them originally.

**Comment by downwriter** [comment]
After re-reading, it is matter of finding all ENV variables in code and normalizing, correct? I'll start reviewing code for ENV for various dependences, etc. and document here. Thanks for clarification. 

I know `config` is used in Hyku currently to handle config for dev, test, prod as well as ENV variables, multi-tenancy settings, etc. [12factor](https://12factor.net/config) does state handling this via environment config files isn't the greatest approach. I wasn't sure if it should be consider. Apologies for confusion.

**Comment by no-reply** [comment]
> After re-reading, it is matter of finding all ENV variables in code and normalizing, correct?

Yeah, i think that's part of it.

We'll also want to look at adding/documenting ENV variables for settings in `./config` YAML files that don't already have them, and for (some/all?) `Hyrax::Configuration` settings as well.

**Comment by downwriter** [comment]
cool. thanks.

**Comment by no-reply** [comment]
this is getting quite a lot better. we're now deploying with Helm, and this approach is used heavily there.

closing this as not in need of directed work.
