### ISSUE TITLE
when valkyrie resource returns false for valid?, the converted AF FileSet returns true for valid?

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3917]
### Descriptive summary

If a Valkyrie::Resource which returns false for valid? is converted to an Active Fedora FileSet (and likely any AF object), the new AF FileSet return true for valid?

### Rationale

If the Valkyrie::Resource is invalid, then any object created from it should also be invalid.

### Background

This was discovered while writing an equivalent test for https://github.com/samvera/hydra-works/blob/master/spec/hydra/works/services/add_file_to_file_set_spec.rb#L22-L30.  This test was to be applied to [Wings::Works::AddFileNodeToFileSet](https://github.com/samvera/hyrax/blob/master/lib/wings/hydra/works/services/add_file_node_to_file_set.rb).

The wings' version of the test causes the Valkyrie::Resource for the FileSet to return false for `valid?`  The first thing that happens in the service is a conversion from the Valkyrie::Resource to an Active Fedora FileSet.  When the conversion is complete, the AF FileSet does not return false for `valid?`.

NOTE: In the test, the Valkyrie::Resource is not really invalid based on the contents of the resource.  But the `valid?` method is stubbed to return false.

### Unknowns

Should the first step in the conversion process from resource to AF object be a check for whether the resource is valid?  The same question applies when converting from AF object to resource.

Should the conversion process try to do the conversion even if the resource says it is invalid and somehow set a flag in the AF object that it is also invalid?

### Expected behavior

OPTION 1:  Throw exception

The conversion process should fail with an exception stating that the resource is invalid and cannot be converted.

OPTION 2: Try to convert and have new AF object.valid? return false
 
An invalid resource that is converted to an AF object should return the same results for `valid?`

```
resource.valid?  # returns false
af_object = Wings::ActiveFedoraConverter.new(resource: resource).convert
af_object.valid?  # returns false
```

### Actual behavior

```
resource.valid?  # returns false
af_object = Wings::ActiveFedoraConverter.new(resource: resource).convert
af_object.valid?  # returns true
```

### Steps to reproduce the behavior

1. create a valkyrie resource and make it return false for `valid?`
2. use `Wings::ActiveFedoraConverter.new(resource: resource).convert` to try to convert it

Make sure the result is as described in the Expected behavior section.

### Related work

Issue #3813 Valkyrize FileActor including the ability to save the file using valkyrie wings
PR #3814 use active_fedora storage adapter to save file and connect it to the file_set

**Comment by elrayle** [comment]
Discussion with @no-reply 

Try testing making the resource truly invalid by removing the title and see how the conversion from resource to AF object proceeds.  Same for reverse direction.  Decisions about how to handle this can follow based on what happens.

**Comment by elrayle** [comment]
Discussion with @no-reply 

Try testing making the resource truly invalid by removing the title and see how the conversion from resource to AF object proceeds.  Same for reverse direction.  Decisions about how to handle this can follow based on what happens.

**Comment by jeremyf** [comment]
I wrote the following passing test:

```ruby
context "with a valkyrie_resource from an invalid ActiveFedora object" do
  it 'returns an ActiveFedora model that is invalid' do
    work = GenericWork.new(id: 'moomin_id', title: nil)
    expect(work).not_to be_valid
    converter = Wings::ActiveFedoraConverter.new(resource: work.valkyrie_resource)
    converted = converter.convert
    expect(converted).not_to be_valid
  end
end
```

**Comment by jeremyf** [comment]
In the present state (`main` branch at a8597884e1ee1802119ee9e82cb7ae9e52ee203f), a `Valkyrie::Resource` does not have a `valid?` method.  Validation happens via an associated Form object.  Given the Form object uses config based metadata and the associated ActiveFedora has hard-coded properties, I'm uncertain how to best proceed.

I see the utility and expectation, but am wondering about implementation.

**Comment by jeremyf** [comment]
I'd love to hear further thoughts from @no-reply and @elrayle

**Comment by jeremyf** [comment]
Given `x` is a Valkyrie Resource
And `f(x)` converts `x` to an object that responds to `valid?`
When `f(x).valid? == false`
Then `f(f(x)).valid? == false`

**Comment by elrayle** [comment]
Given `x` is an ActiveFedora object which responds `x.valid?` and returns `false`
And `f(x)` converts `x` to a `Valkyrie::Resource` (which doesn't have method valid?)
And `g(f(x))` converts `f(x)` resource back to an ActiveFedora object that responds to valid?
Then `g(f(x))` responds to `valid?` and returns `false`
