### ISSUE TITLE
WINGS: permissions and FileMetadata resource

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3922]
### Descriptive summary

There is an open question about the best approach for handling permissions in the FileMetadata resource.  It is not expected that Valkyrie::Resource::AccessControls will do what we need.

**Comment by no-reply** [comment]
@elrayle: is there still an open question here? if so, what is it?

**Comment by eporter23** [comment]
As part of older ticket reviews, closing this because Valkyrization work has continued forward.
