### ISSUE TITLE
WINGS: Valkyrie resource created from ActiveFedora objects respond to reload

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3928]
### Descriptive summary

Any Valkyrie Resource transformed from an ActiveFedora object should not respond to `:reload` method.  

### Rationale

Valkyrie Resources do not have a concept of reloading a resource.

### Expected behavior

```
resource = af_object.valkyrie_resource
resource.reload # should throw missing method
```

All active fedora methods are currently supported by a pass through to the active fedora version of the resource by catching missing method.  This happens in `lib/wings/hydra/pcdm/models/concerns/pcdm_valkyrie_behavior.rb #method_missing`.

Update this method to check specifically for the `:reload` method and continue to throw method missing instead of forwarding the call to the active fedora object.

#### REQUIRES EXPLORATION

The reload method for active fedora objects is used in app code and in tests.  Exploration is needed to determine if these reloads can go away when they are switched to Valkyrie::Resources.  If this functionality is still needed, then implement a Hyrax reload method for resources.  Something like...

```
module Hyrax
  ...

  def self.reload_resource(resource:)
    query_service = Hyrax.query_service
    query_service.find_by(id: resource.id)
  end
```

During the transition time from AF to Valkyrie, a second method could be created to handle both resources and af_objects.

```
module Hyrax
  ...

  def self.reload_object(:object)
    return object.reload if object.is_a? ActiveFedora::Base
    return reload_resource(resource: object) if object.is_a? Valkyrie::Resource
    # possibly throw method missing if object isn't an AF:Base or Valkyrie:Resource
  end
```

This would allow us to encapsulate the reload functionality making it easier to remove later if needed.

### Actual behavior

```
resource = af_object.valkyrie_resource
resource.reload # returns active fedora object
```

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
#3952 tries to fix this by removing `method_missing` entirely. I think this is the best approach, but there is some code relying on it already, so a solution to that will need to be found. See the failing tests on that PR.
