### ISSUE TITLE
Collection Thumbnail JS Does Not Work On All Collection URLs

### ISSUE THREAD

**Issue by orangewolf** [samvera/hyrax#3930]
### Descriptive summary

In version 2.5.1 (and the code appears unchanged in master), collection thumbnail selection does not work on certain collections.  If a collection's url contains the string 'edit' anywhere but the last characters, that part of the URL and not the correct portion will be substituted.  

### Rationale

As an admin I want to be able to select thumbnails for all collections.

### Expected behavior

Thumbnail selection works on all collections irrespective of urls

### Actual behavior

`https://dl.atla.com/dashboard/collections/edith-stein-collection/edit?_=1566882335253`

becomes

`https://dl.atla.com/dashboard/collections/filesh-stein-collection/edit?_=1566882335253`

instead of

`https://dl.atla.com/dashboard/collections/edith-stein-collection/files?_=1566882335253`

### Steps to reproduce the behavior

Create a collection with a UUID or minted ID that contains 'edit' like `asdfedit`. Go to dashboard -> edit collection -> select thumbnail.  A 404 will appear in the JS console.

**Comment by Dananji** [comment]
I was not able to reproduce this issue on either Nurax test site or locally running Hyrax. I followed the steps here, and I don't get a 404.

**Comment by orangewolf** [comment]
@Dananji the keys are - the collection URL must contain the substring 'edit' and the 404 happens in the JS on the loaded page.  The more important thing is that thumbnails don't work. I have a PR, but I'm trying to get specs for it.
