### ISSUE TITLE
WINGS: attach file metadata to valkyrie fileset for non-wings adapters

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#3933]
**NOTE: This issue will not be ready to be addressed until near the end of the valkyrization process.**

### Descriptive summary

Wings attaches the file to the fileset through the ActiveFedora storage adapter.  Other storage adapters will not do that.  FileMetadataBuilder should take responsibility for making the attachment.

### Proposed code

Some code was written in the Valkyrie 6 branch and initially included in the FileMetadataBuilder.  In an effort to not address code changes until they are required, this code is being removed.  As it might be useful later when we try to use Hyrax with other valkyrie adapters, the code is being recorded here, along with some observations and questions.

Class: Wings::FileMetadataBuilder (in lib/wings/services)

_planning to move to Hyrax, so look for Hyrax::FileMetadataBuilder (in app/services/hyrax)_

```
    def create
      ...
      attach_file_metadata(file_metadata: file_metadata, file_set: file_set)
      file_metadata
    end
```

```
    # @param file_metadata [Hyrax::FileMetadata] the metadata to represent the file
    # @param file_set [Valkyrie::Resource] the associated FileSet
    # @return [Hyrax::FileMetadata] the persisted metadata file_metadata that represents the file
    def attach_file_metadata(file_metadata:, file_set:)
      # TODO: WINGS - May have to adjust this when versioning is valkyrized
      return file_metadata if file_set.file_ids.include? file_metadata.id # For Wings, this was done by storage adapter. This avoids trying to set it twice.
      attach_file_metadata_to_valkyrie_file_set(file_metadata, file_set)
    end

    private

      def attach_file_metadata_to_valkyrie_file_set(file_metadata, file_set)
        # TODO: WINGS - Need to test this against other adapters once they are available for use.
        # TODO: Seems like this should be attaching by setting file id in correct attributes based on use.
        #       Why is the file_metadata copied before setting file_ids on file_set?  It was originally created
        #       by JobIOWrapper specifically for this purpose, but its never saved until here.  If the copy is
        #       what we want to save, then I'm not sure the reason for assigning an id above.
        #       I would expect this to set original_file_ids, extracted_test_ids, or thumbnail_ids based on use.
        #       I would expect it to set file_ids (as it does).  Perhaps the copy is something to do with Versioning.
        #       Seems like this may need a rewrite after investigating.
        existing_file_metadata = file_set.original_file_id || file_metadata
        file_metadata = existing_file_metadata.new(file_metadata.to_h.except(:id))
        saved_file_metadata = persister.save(resource: file_metadata)
        file_set.file_ids = [saved_file_metadata.id]
        persister.save(resource: file_set)
        saved_file_metadata
      end
```

**Comment by no-reply** [comment]
Why not prioritize this immediately? It seems like a major blocker to completion of the project, and design of work below the Wings fold would benefit from an understanding of what it needs to be compatible with in the main codebase?

**Comment by no-reply** [comment]
i think this might also be done.

**Comment by no-reply** [comment]
i think this can be closed as fixed. `Hyrax::ValkyrieUpload` provides the most used wrapper for this behavior.

**Comment by tpendragon** [comment]
## Proposed Success Criteria

Write a new ticket that says "Document `Hyrax::ValkyrieUpload` (or somewhere better I don't know) to explain how file attachments work in Hyrax, then close this one.
