### ISSUE TITLE
Unable to Add Files to Work under an Embargo

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#3958]
### Descriptive summary

Hyrax Version: 3.0.0.pre.beta3
Hyrax Branch: master
Hyrax Revision: 1358cb7b210e88d7662574c3aa7d73d69e265648

Nurax Version
ENV: production
SHA: 37125c9f9c07be45d3ba84a894fdd42332df53c5
Branch: 2019-09-11-10-00
Updated: 11 Sep 2019 15:00:24

### Rationale

Users should be able to update works that are embargoed with new files. 

### Expected behavior

Works that with Public, Private, or Institution visibility settings can have new files added to them after the work is created.

### Actual behavior

Works with an Embargo visibility setting cannot be updated with new files. After adding new files and saving the work, the app stays on the Edit work screen and no updates are made.

### Steps to reproduce the behavior

1. Create a work
2. Save the work with an embargo visibility setting (set the embargo for sometime in the future)
3. Edit the work
4. Add new files
5. Save the work

This is true for both adding works one at a time **and** adding a folder of files.

### Related work

Link to related tickets or prior related work here.

**Comment by dlim87** [comment]
I was able to add a new file to an existing embargoed and a leased work as of
Hyrax Version: 3.0.0.pre.rc1
Hyrax Branch: master
Hyrax Revision: 84dad1d89ba08f4d9f8ded43f2afb98dfa8c402f
Nurax Version
ENV: production
SHA: a2d5ecd45371aa744969c8e093a8b461867ebef4
Branch: 2019-10-04-10-00
Updated: 4 Oct 2019 15:00:18
