### ISSUE TITLE
Dashboard accessibility audit 

### ISSUE THREAD

**Issue by kellyChex** [samvera/hyrax#3964]
### Descriptive summary

QA Testing for Hyrax
Hyrax Version: 3.0.0.pre.rc1
Hyrax Branch: master
Hyrax Revision: 48ed925
Nurax Version
ENV: production
SHA: 40b47b0d71af1b958e016ebe49212c1740683133
Branch: 2019-09-12-10-00
Updated: 12 Sep 2019 15:00:37

In testing for the Hyrax 3.0 release, the following points are actions that were discovered during a FireFox tab test and axe accessibility audit. Note, only critical issues are being reported at this time.

**ARIA role must be appropriate for the element:**

![Screen Shot 2019-09-11 at 4 47 31 PM](https://user-images.githubusercontent.com/9621070/64743224-e358e880-d4b3-11e9-8910-71aec4035f0b.png)

**Heading levels should only increase by one:**

![Screen Shot 2019-09-11 at 4 48 16 PM](https://user-images.githubusercontent.com/9621070/64743242-fc619980-d4b3-11e9-80b5-9d488eba33f7.png)

**Ensures landmarks are unique:**

![Screen Shot 2019-09-11 at 4 48 58 PM](https://user-images.githubusercontent.com/9621070/64743280-18653b00-d4b4-11e9-8fe1-ba103e91def5.png)

### Steps to reproduce the behavior

1. Install the Axe plugin or addon from Deque (https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/ is the firefox version).
2. Open https://nurax-dev.curationexperts.com/collections/td96k2517?locale=en
3. Open the inspector (right-click, and select "Inspect element")
4. Click on the 'Axe' tab
5. Click 'Analyze'

### Tab Test:

In Firefox and Safari, not able to tab through any of the links and buttons on the Dashboard page. 

Chrome working well. 

https://cl.ly/d5b05c539aea/download/Screen%252520Recording%2525202019-09-12%252520at%25252007.37%252520PM.mov

**Comment by MariaStarPower** [comment]
Results of analysis:

<details>

<img width="1431" alt="Image 2020-09-10 at 2 48 17 PM" src="https://user-images.githubusercontent.com/32848057/92812750-b5331080-f374-11ea-9e17-ae0699a2cdb7.png">

</details>

**Comment by MariaStarPower** [comment]
I am able to tab through the links and buttons on the Dashboard in Firefox and Chrome (Chrome is better).
