### ISSUE TITLE
Analytics graph is not getting displayed in Safari/Chrome Mac sometimes

### ISSUE THREAD

**Issue by SumithBaddam** [samvera/hyrax#3970]
### Descriptive summary

Testing on Hyrax 3.0
Browserstack:
    Safari 12.1 browser
    Chrome browser

Analytics plot/graph is not getting displayed in Safari/Chrome Mac sometimes. If I open the collection/work analytics, it's not getting displayed but if I copy paste the URL in browser, it seems to work. 
Examaple: https://nurax-dev.curationexperts.com/works/kk91fk53m/stats?locale=en
If we copy paste this URL, it displays. But if we open it from the collection, it is displaying empty graph. This issue might be because of browserstack. So I would like someone else to verify this.

### Expected behavior
Display analytics graph for works.

### Actual behavior
Displaying empty graph.

### Steps to reproduce the behavior
"Navigate to work view page:
*Click on the analytics button
*Graph displays"

Example:
https://nurax-dev.curationexperts.com/works/kk91fk53m/stats?locale=en

**Comment by julesies** [comment]
FWIW, I think this might block us from upgrading to 3.0. But we might be able to help figure out things. @smithjp

**Comment by julesies** [comment]
also FWIW, we have seen some similar bugs to this in previous releases https://github.com/curationexperts/nurax/issues/83

**Comment by MariaStarPower** [comment]
This is **fixed** - I can see the **Analytics graph** when I click on the Analytics tab from a work's show page:

Graphs are displaying perfectly in Google Chrome:

<details>

<img width="1456" alt="Image 2020-09-08 at 1 51 20 PM" src="https://user-images.githubusercontent.com/32848057/92526461-66ea0a00-f1da-11ea-961c-b8be33304f20.png">

<img width="1482" alt="Image 2020-09-08 at 2 14 30 PM" src="https://user-images.githubusercontent.com/32848057/92528457-a49c6200-f1dd-11ea-95e7-43b46b3f1753.png">

<img width="1479" alt="Image 2020-09-08 at 2 16 33 PM" src="https://user-images.githubusercontent.com/32848057/92528630-ef1dde80-f1dd-11ea-8395-80c3856ef3a2.png">

</details>

Graphs are displaying perfectly in Safari:

<details>

<img width="1432" alt="Image 2020-09-08 at 1 52 52 PM" src="https://user-images.githubusercontent.com/32848057/92526607-a31d6a80-f1da-11ea-8419-c99dcc22b67d.png">

<img width="1432" alt="Image 2020-09-08 at 2 15 22 PM" src="https://user-images.githubusercontent.com/32848057/92528524-c72e7b00-f1dd-11ea-938b-53632609e60b.png">

<img width="1434" alt="Image 2020-09-08 at 2 17 55 PM" src="https://user-images.githubusercontent.com/32848057/92528743-1ecce680-f1de-11ea-9dea-8c68895b2892.png">

</details>
