### ISSUE TITLE
Sharing work with user during creation creates fatal error

### ISSUE THREAD

**Issue by dlim87** [samvera/hyrax#3974]
### Descriptive summary
Hyrax 3.0 pre-release QA

When creating a new work, if you go to the sharing tab and add the ability for another user to edit or view this work, upon saving, the app crashes with a "no agent" error. Note, this is only during work creation. If you create the work without this step and then share it through the edit form, it works fine.
<details><summary>Error message</summary>
RuntimeError in Hyrax::GenericWorksController#create
no agent

Extracted source (around line #434):
```
def group_agent?(agent)
        raise 'no agent' unless agent.present?
        agent.first.rdf_subject.to_s.start_with?(GROUP_AGENT_URL_PREFIX)
      end
```
Rails.root: /opt/nurax/releases/20190912150037
</details>
<details><summary>Trace</summary>
hydra-access-controls (10.7.0) app/models/concerns/hydra/access_controls/permissions.rb:434:in `group_agent?'
hydra-access-controls (10.7.0) app/models/concerns/hydra/access_controls/permissions.rb:410:in `block in search_by_type_and_mode'
hydra-access-controls (10.7.0) app/models/concerns/hydra/access_controls/permissions.rb:421:in `block in search_by_mode'
hydra-access-controls (10.7.0) app/models/concerns/hydra/access_controls/permissions.rb:420:in `select'
hydra-access-controls (10.7.0) app/models/concerns/hydra/access_controls/permissions.rb:420:in `search_by_mode'
hydra-access-controls (10.7.0) app/models/concerns/hydra/access_controls/permissions.rb:410:in `search_by_type_and_mode'
hydra-access-controls (10.7.0) app/models/concerns/hydra/access_controls/permissions.rb:273:in `edit_groups'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/models/concerns/hyrax/permissions/writable.rb:16:in `block (2 levels) in <module:Writable>'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/models/concerns/hyrax/permissions/writable.rb:24:in `block in paranoid_permissions'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/models/concerns/hyrax/permissions/writable.rb:23:in `each'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/models/concerns/hyrax/permissions/writable.rb:23:in `paranoid_permissions'
activesupport (5.1.7) lib/active_support/callbacks.rb:413:in `block in make_lambda'
activesupport (5.1.7) lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
activesupport (5.1.7) lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
activesupport (5.1.7) lib/active_support/callbacks.rb:600:in `catch'
activesupport (5.1.7) lib/active_support/callbacks.rb:600:in `block in default_terminator'
activesupport (5.1.7) lib/active_support/callbacks.rb:198:in `block in halting'
activesupport (5.1.7) lib/active_support/callbacks.rb:507:in `block in invoke_before'
activesupport (5.1.7) lib/active_support/callbacks.rb:507:in `each'
activesupport (5.1.7) lib/active_support/callbacks.rb:507:in `invoke_before'
activesupport (5.1.7) lib/active_support/callbacks.rb:130:in `run_callbacks'
activesupport (5.1.7) lib/active_support/callbacks.rb:827:in `_run_validate_callbacks'
activemodel (5.1.7) lib/active_model/validations.rb:405:in `run_validations!'
active-fedora (13.0.0) lib/active_fedora/validations.rb:100:in `block in run_validations!'
activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
activesupport (5.1.7) lib/active_support/callbacks.rb:827:in `_run_validation_callbacks'
active-fedora (13.0.0) lib/active_fedora/validations.rb:100:in `run_validations!'
activemodel (5.1.7) lib/active_model/validations.rb:335:in `valid?'
active-fedora (13.0.0) lib/active_fedora/validations.rb:69:in `valid?'
active-fedora (13.0.0) lib/active_fedora/validations.rb:93:in `perform_validations'
active-fedora (13.0.0) lib/active_fedora/validations.rb:50:in `save'
active-fedora (13.0.0) lib/active_fedora/associations/builder/orders.rb:44:in `save'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/base_actor.rb:71:in `save'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/base_actor.rb:22:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/model_actor.rb:17:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/apply_permission_template_actor.rb:10:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/transfer_request_actor.rb:9:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/interpret_visibility_actor.rb:77:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/default_admin_set_actor.rb:14:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/add_to_work_actor.rb:10:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/collections_membership_actor.rb:17:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/create_with_files_actor.rb:14:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/create_with_remote_files_actor.rb:16:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
/opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-48ed92594013/app/controllers/concerns/hyrax/works_controller_behavior.rb:54:in `create'
actionpack (5.1.7) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.7) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.7) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.7) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.7) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.7) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.7) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.7) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.7) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.7) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.7) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.7) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.7) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.7) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.7) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.7) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:844:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
active-fedora (13.0.0) lib/active_fedora/ldp_cache.rb:26:in `call'
flipflop (2.6.0) lib/flipflop/feature_cache.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
honeybadger (3.3.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (3.3.0) lib/honeybadger/agent.rb:337:in `with_rack_env'
honeybadger (3.3.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (3.3.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (3.3.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
passenger (5.3.2) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
</details>
<details><summary>Request</summary>
Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"ikrktN9nTQjoJgK7mCPKS9nz3koioKh8Qgnubec+a3J7c72U+Jpm+Ah6DplloO5u610RxZBe+5lBuHENgwsyBA==",
 "generic_work"=>
  {"title"=>"Admin set test 6",
   "creator"=>["Lim, Daniel"],
   "rights_statement"=>"http://rightsstatements.org/vocab/InC/1.0/",
   "contributor"=>[""],
   "description"=>[""],
   "abstract"=>[""],
   "keyword"=>[""],
   "license"=>[""],
   "access_right"=>[""],
   "rights_notes"=>[""],
   "publisher"=>[""],
   "date_created"=>[""],
   "subject"=>[""],
   "language"=>[""],
   "identifier"=>[""],
   "based_near_attributes"=>{"0"=>{"hidden_label"=>"", "id"=>"", "_destroy"=>""}},
   "related_url"=>[""],
   "source"=>[""],
   "resource_type"=>[""],
   "admin_set_id"=>"pg15bd88s",
   "member_of_collection_ids"=>"",
   "permissions_attributes"=>{"0"=>{"type"=>"person", "name"=>"manager@notch8.com", "access"=>"edit"}},
   "visibility_during_embargo"=>"restricted",
   "embargo_release_date"=>"2019-09-13",
   "visibility_after_embargo"=>"open",
   "visibility_during_lease"=>"open",
   "lease_expiration_date"=>"2019-09-13",
   "visibility_after_lease"=>"restricted",
   "visibility"=>"restricted"},
 "new_group_name_skel"=>"Select a group",
 "new_group_permission_skel"=>"none",
 "new_user_name_skel"=>"",
 "new_user_permission_skel"=>"none",
 "agreement"=>"1",
 "locale"=>"en"}
</details>
<details><summary>Session dump</summary>
_csrf_token: "8TlZICf9K/DgXAwi/YMkJTKuz4+y/lPlA7GfYGQ1WXY="
batch_edit_state: "on"
history: [7409750, 7409730]
search: {"id"=>7409750}
session_id: "ae7d0f5d8ac4b0a2fc28aea3643cf06e"
warden.user.user.key: [[2998], "$2a$11$dpR.2/gOe4ijs/3T27uBQO"]</summary>
</details> 
<details><summary>Env dump</summary>
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.9"
HTTP_CACHE_CONTROL: "max-age=0"
HTTP_ORIGIN: "https://nurax-dev.curationexperts.com"
HTTP_VERSION: "HTTP/1.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "12.46.197.135"
SERVER_NAME: "nurax-dev.curationexperts.com"
SERVER_PROTOCOL: "HTTP/1.1"
</details> 

<details><summary>testing info</summary>
Tested on Mac and windows - Chrome 76.0.3809.132,
Mac - Safari 12.1.2,
Windows - Firefox 69.0

<details><summary>hyrax info</summary>
Hyrax Version: 3.0.0.pre.rc1
Hyrax Branch: master
Hyrax Revision: 48ed925940130bcc5e75092c974555f4f1654390

Nurax Version
ENV: production
SHA: 40b47b0d71af1b958e016ebe49212c1740683133
Branch: 2019-09-12-10-00
Updated: 12 Sep 2019 15:00:37</details>
</details>

### Rationale
We probably do not want the user to encounter fatal error pages

### Expected behavior
Given the discussion in previous discussions, it's unclear whether or not it should be possible to share with users on a work creation, but if it isn't, it should block the save not crash.

### Actual behavior
There are no warnings before the error page
### Steps to reproduce the behavior

1. Log in
2. Go to the create work page
3. Enter values for the required fields
4. Make sure it's in an admin set that allows sharing (the default one should work)
5. Go to the sharing tab 
6. Add any user
7. Press the save button

### Related work
Similar behavior with groups, instead of users: https://github.com/samvera/hyrax/issues/3805
Suggestion to prevent sharing until after a work is created: https://github.com/samvera/hyrax/issues/3274

**Comment by dlpierce** [comment]
This was introduced by https://github.com/samvera/hydra-head/pull/469

**Comment by crisr15** [comment]
Passed QA.  Created a new work and shared with another user.  Work was properly created and the user showed up in the sharing tab when revisiting the work after creation.
