### ISSUE TITLE
Repository search dropdown menu option should display configured repository name

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#398]
Dropdown menu for cross-repository search field shows "All of Hyrax".  In that phrase, "Hyrax" should be replaced with the name of repository that has been configured on the Admin Dashboard under Configuration > Settings > Labels.

Acceptance  criteria: 
- [ ] I have not configured the name of my repository, and when I click on the cross-repository search field menu, I see "All of Hyrax" as an option there.
- [ ] I have configured the name of my repository as "Foo" and when I click on the cross-repository search field menu, I see "All of Foo" as an option there.

**Comment by jcoyne** [comment]
We may want to wait this out as I'm not sure this appears in the new UI.

**Comment by vantuyls** [comment]
I believe this now functions as @hannahfrost suggested. Can i get another quick check and then maybe we can close this?

**Comment by mjgiarlo** [comment]
Yep, this looks done to me as well. Thanks, @vantuyls!
