### ISSUE TITLE
Batch editing work accessibility audit 

### ISSUE THREAD

**Issue by kellyChex** [samvera/hyrax#3992]
### Descriptive summary

Descriptive summary
QA Testing for Hyrax
Hyrax Version: 3.0.0.pre.rc1
Hyrax Branch: master
Hyrax Revision: 48ed925
Nurax Version
ENV: production
SHA: 40b47b0d71af1b958e016ebe49212c1740683133
Branch: 2019-09-12-10-00
Updated: 12 Sep 2019 15:00:37

In testing for the Hyrax 3.0 release, the following points are actions that were discovered during a FireFox tab test and axe accessibility audit. Note, only certain issues are being reported at this time

**id attribute value must be unique**
![Screen Shot 2019-09-12 at 10 19 51 PM](https://user-images.githubusercontent.com/9621070/64839204-76c11500-d5ab-11e9-9b26-ef3608581a71.png)

![Screen Shot 2019-09-12 at 10 20 24 PM](https://user-images.githubusercontent.com/9621070/64839215-893b4e80-d5ab-11e9-9281-c72b90614c20.png)

![Screen Shot 2019-09-12 at 10 20 45 PM](https://user-images.githubusercontent.com/9621070/64839227-95bfa700-d5ab-11e9-8a02-b6a2b4bd218a.png)

**ARIA role must be appropriate for the element**
![Screen Shot 2019-09-12 at 10 21 15 PM](https://user-images.githubusercontent.com/9621070/64839248-a7a14a00-d5ab-11e9-8bf7-d1ef2ea5f1c8.png)

**Ensures landmarks are unique**
![Screen Shot 2019-09-12 at 10 21 48 PM](https://user-images.githubusercontent.com/9621070/64839267-bdaf0a80-d5ab-11e9-9837-5de00f8e320a.png)

**Page must contain a level-one heading**
![Screen Shot 2019-09-12 at 10 22 19 PM](https://user-images.githubusercontent.com/9621070/64839288-cdc6ea00-d5ab-11e9-8a6e-5f18b710bd73.png)

### Steps to reproduce the behavior

1. Install the Axe plugin or addon from Deque (https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/ is the firefox version).
2. Open batch edit page 
3. Open the inspector (right-click, and select "Inspect element")
4. Click on the 'Axe' tab
5. Click 'Analyze'

The batch edit page can be found by following these steps:
* Navigate to the "Works" page
* Select multiple Works in the table
* Click the "Edit Selected" button
* The "Batch Edit Description" screen will appear which contains two tabs: "Descriptions" and "Permissions

### Tab Test 

Link: https://nurax-dev.curationexperts.com/batch_edits/edit?batch_document_ids%5B%5D=kh04dp966&batch_document_ids%5B%5D=tq57nr202&batch_document_ids%5B%5D=th83kz52k 

On Firefox and Safari, tabbing through any of the links on the Batch Edit page is not possible. 

Chrome works fine.

**Comment by rjkati** [comment]
axe did not identify any accessibility issues on the batch edit page (dev.nurax running Hyrax 5.0.0.rc2) in Firefox
![batch-edit_noissues](https://github.com/samvera/hyrax/assets/32644254/00eaafd3-91bc-4b54-a0dc-8ec0c45d3f38)

It is also now possible to tab through links on the Batch Edit page in Firefox
