### ISSUE TITLE
Dependency Maintenance Status Badge on README.md does not work

### ISSUE THREAD

**Issue by brianmcbride** [samvera/hyrax#3995]
### Descriptive summary

Dependency Maintenance Status Badge on README.md does not display an image and when clicked on you are redirected a new site asking for login information

code snippet
`[![Dependency Maintenance Status](https://dependencyci.com/github/samvera/hyrax/badge)](https://dependencyci.com/github/samvera/hyrax)
`

### Rationale

The badge should be removed or update to ensure it is working and helpful to users.

### Expected behavior

A working maintenance status badge.

### Actual behavior

Broken icon image and when clicking on the link user is directed to https://tidelift.com/login and prompted to login.

### Steps to reproduce the behavior

1. Go [here](https://github.com/samvera/hyrax)
2. Click on Dependency Maintenance Status Badge (in the code row)

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
it seems like it might be helpful to enlist some folks to review the README in advance of the 3.0.0 release.
