### ISSUE TITLE
Broken Image shows in Safari but not in Chrome

### ISSUE THREAD

**Issue by downwriter** [samvera/hyrax#3999]
### Descriptive summary

QA Testing for Hyrax

Hyrax Version: 3.0.0.pre.rc1
Hyrax Branch: master
Hyrax Revision: 9b2360f
ENV: production 
SHA: aa07ac6ed440e9f700cce91fc602c115482e6bed 
Branch: 2019-09-16-10-00 
Updated: 16 Sep 2019 15:00:28

### Rationale

When performing QA testing for Hyrax 3.0, I was testing the Collections Index functionality (C_1.1). The basic functionality of the test passes, but I noticed that a broken image shows up in Safari on Mac, but not in Chrome for Mac. 

### Expected behavior

Broken image icon would not show up in the collection detail like it is handled by Chrome. 

### Actual behavior

The broken image icon shows up in the collection detail when using Safari browser on Mac. 

### Steps to reproduce the behavior

1. From Hyrax homepage, click "View all collections" 
2. Click on "New York World's Fair, 1939-1940" Collection (https://nurax-dev.curationexperts.com/collections/n296wz323?locale=en)
3. Collection page shows collection detail, table items in collection, and links to those items 
4. Broken collection image does not show in Chrome for Mac: 

![image](https://user-images.githubusercontent.com/7670281/64975771-6b087380-d875-11e9-9c45-62cfff3d4635.png)

5. Broken collection image does show in Safari: 

![image](https://user-images.githubusercontent.com/7670281/64975850-93906d80-d875-11e9-893b-d23ce8581280.png)

### Related work

None currently.

**Comment by MariaStarPower** [comment]
This is **fixed** - the broken image does _not_ display on the collection's show page in Chrome or Safari:

Google Chrome:

<details>

<img width="1478" alt="Image 2020-09-08 at 2 44 23 PM" src="https://user-images.githubusercontent.com/32848057/92530752-d1eb0f00-f1e1-11ea-9633-ffb6a048fd83.png">
<img width="1488" alt="Image 2020-09-08 at 2 45 01 PM" src="https://user-images.githubusercontent.com/32848057/92530795-e929fc80-f1e1-11ea-97d1-c5bd836fc1cf.png">

</details>

Safari:

<details>

<img width="1432" alt="Image 2020-09-08 at 2 47 06 PM" src="https://user-images.githubusercontent.com/32848057/92530939-38702d00-f1e2-11ea-938d-31c66bf21e1b.png">
<img width="1434" alt="Image 2020-09-08 at 2 47 49 PM" src="https://user-images.githubusercontent.com/32848057/92530981-4d4cc080-f1e2-11ea-8dce-76a8c653a880.png">

</details>
