### ISSUE TITLE
Tabbing goes to adressbar in edit collection > participants on safari

### ISSUE THREAD

**Issue by dlim87** [samvera/hyrax#4001]
### Descriptive summary
Using OSX safari, if you go to edit collection > participants, and press tab after selecting something in the add user > role selection, instead of going to the add button, it shifts focus to the address bar. 

This is only on safari, as it worked as expected in firefox and chrome
![Screen Recording 2019-09-16 at 11 21 AM](https://user-images.githubusercontent.com/5492162/64982895-1b757800-d874-11e9-9a50-89dc197b26fa.gif)

Tested on a mac, using Safari 12.1.2
<details><summary> nurax info</summary>
Hyrax Version: 3.0.0.pre.rc1 

Hyrax Branch: master 
Hyrax Revision: 9b2360f3127aee794e7851d97852adaf240ca9ba

Nurax Version
ENV: production 
SHA: aa07ac6ed440e9f700cce91fc602c115482e6bed 
Branch: 2019-09-16-10-00 
Updated: 16 Sep 2019 15:00:28
</details>

### Rationale
This is a major accessibility problem, as it would prevent tabbing into any fields further down in the page

### Expected behavior
Pressing tab from the role box would select the add button
### Actual behavior
Pressing tab from the role box selects the address bar
### Steps to reproduce the behavior

1. Open nurax in Safari
2. log in as a user that has permission to edit a collection/create a collection
3. Go to the dashboard and select a collection to edit
4. Go to the participants tab
5. enter a name, and role, using tab instead of the mouse to traverse the fields
6. tab from the user roles dropdown
### Related work

similar to https://github.com/samvera/hyrax/issues/3453

**Comment by Dananji** [comment]
Safari skips buttons, check-boxes, and anchors in tab rotation by default.
It is an advanced feature to include these into the tab order, which can be enabled in `Accessibility` in `Advanced` preferences in Safari.

**Comment by dlim87** [comment]
^ Yes, this was a local settings problem. This ticket can be closed
