### ISSUE TITLE
Deactivate Leases for Selected Fails

### ISSUE THREAD

**Issue by gamontoya** [samvera/hyrax#4002]
### Descriptive summary

- Hyrax Version: 3.0.0.pre.rc1
- Hyrax Branch: master
- Hyrax Revision: 9b2360f3127aee794e7851d97852adaf240ca9ba
- ENV: production
- SHA: aa07ac6ed440e9f700cce91fc602c115482e6bed
- Branch: 2019-09-16-10-00
- Updated: 16 Sep 2019 15:00:28

### Rationale

In the Manage Leases section, admin should be able to select multiple items to deactivate the embargoes with one click.

### Expected behavior

On the `Expired Active Leases` tab, select multiple items and click on `Deactivate Leases for Selected.` Un-click on `Change all files within`... Items are deactivated.

### Actual behavior

On the `Expired Active Leases tab`, select multiple items and un-click `Change all files within...`. Next click on `Deactivate Embargoes for Selected`. Receive the following Controller Error:

![leasesError2](https://user-images.githubusercontent.com/4314914/64985122-06e7ae80-d879-11e9-9fb2-376f540ff0fc.png)

### Steps to reproduce the behavior

1. Log in as Administrator
2. Tasks > Manage Leases
3. Click on "Expired Active Leases"
4. Select two/three items
5. Un-click "Change all files within..."
6. Click on "Deactivate Embargoes for Selected"
7. Get Controller Error

### Related work

- https://github.com/samvera/hyrax/issues/3993

**Comment by dlim87** [comment]
Video: https://share.getcloudapp.com/qGuzqBg8

This no longer causes a controller error.
