### ISSUE TITLE
Adding a keyword to "large" collection takes a long time to save

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#4013]
### Descriptive summary

I added one subject to this collection https://nurax-dev.curationexperts.com/dashboard/collections/r494vk302/edit?locale=en#description 

When I hit save, it took 15-30 secs to complete. I tried it 3 times with different results in that range. 
### Rationale

This is a long time for a metadata edit. 

### Expected behavior

Either some feedback in the UI saying it's going to take a while, or MD edits are quicker

### Steps to reproduce the behavior

1. As an admin, log into nurax
2. navigate to this collection https://nurax-dev.curationexperts.com/dashboard/collections/r494vk302/edit?locale=en#description
3. edit description, click additional fields, add a subject
4. click save, note time

**Comment by julesies** [comment]
In addition, if you click away from the page while it's saving (because you think you can), say clicking on dashboard: collections, once the collection saves, you get kicked back to the collection page you previously edited.

**Comment by kellyChex** [comment]
I tested this performance issue and it took about ~15 seconds for the page to load after saving.

**Comment by no-reply** [comment]
I'm hoping we can get [Skylight](https://skylight.io) turned back on so we can diagnose performance issues like this more readily.

**Comment by jeremyf** [comment]
I'm wondering if the following commit 793b412912aaaea8b059be724c65b8545d8d591c cleared this up.

**Comment by MariaStarPower** [comment]
**Pass** - The collection saved in roughly 7 seconds and the new edits were saved.

<details>

<img width="1457" alt="Image 2020-10-08 at 9 56 03 AM" src="https://user-images.githubusercontent.com/32848057/95490160-b132e800-094c-11eb-8d9a-e90d2fa6c442.png">

<img width="1458" alt="Image 2020-10-08 at 9 58 00 AM" src="https://user-images.githubusercontent.com/32848057/95490235-ce67b680-094c-11eb-98a3-a9b8dcd4943b.png">

<img width="1453" alt="Image 2020-10-08 at 11 19 18 AM" src="https://user-images.githubusercontent.com/32848057/95498178-48ea0380-0958-11eb-8bcb-a2844cc3434b.png">

</details>

**Comment by jeremyf** [comment]
Seven seconds, while that's a long time, may be acceptable.  Thoughts @jlhardes ?

**Comment by jlhardes** [comment]
7 seconds still seems pretty long for a save action but it is faster than initially reported. Can this be considered fixed for the Hyrax 3.0 release and we continue to look at improving save times for metadata edits on "large" collections for 3.x? This seems like something to include in the testing script. (And I'm not sure what is meant by large - a lot of items in a collection, large file size totals for a collection, both?)

**Comment by crisr15** [comment]
Passed QA.  Saved in less than 2 seconds.
