### ISSUE TITLE
WINGS: extracted text fails to copy content via LDP

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4018]
### Descriptive summary

lib/wings/hydra/works/services/add_file_to_file_set correctly adds content for an original file and thumbnail image, but LDP fails to copy content when use is extracted text.  The same file can be successfully added when use is original file.

This was traced down to the LDP put request.  It is confirmed that the file that is part of the LDP request does have content.  The rest of the LDP put request looks the same as it does when use is original file.

It was also validated, that the same test passes when it is run directly under Hydra::Works instead of going through the wings wrapper.

It is unclear why this fails.

### Related code

FAILING TEST: https://github.com/samvera/hyrax/blob/master/spec/wings/hydra/works/services/add_file_to_file_set_spec.rb#L44-L61

LDP PUT: https://github.com/samvera/ldp/blob/master/lib/ldp/client/methods.rb#L86-L98

### Related work

PR #3939 wings wrapper for Hydra:Works:AddFileToFileSet

**Comment by randalldfloyd** [comment]
@elrayle Is this still accurate and still not been solved by other Wings work around FileSets?  I will be out at Solar Vortex and am going through issues looking for something Wings-related that I can be prepared to work on. Not sure if others would consider this a blocker, but we at IU would.

**Comment by elrayle** [comment]
The problem is that the File was being read ahead of the ldp put request.  So at the point the put request was executed, the contents were already consumed.  We were able to get the test for [extracted files](https://github.com/samvera/hyrax/blob/master/spec/wings/hydra/works/services/add_file_to_file_set_spec.rb#L42-L57) to pass by rewinding the file in ActiveFedora /lib/active_fedora/file.rb #local_or_remote_content even when new_record? is true.

An ActiveFedora PR is coming shortly.
