### ISSUE TITLE
Ability to configure the properties that display for a collection.

### ISSUE THREAD

**Issue by tpendragon** [samvera/hyrax#402]
Right now just the title/description are hard-coded in the collection's `show.html.erb` page. There needs to be a way to add other properties (we have, for instance, a slug to represent the collection.)

**Comment by mjgiarlo** [comment]
@tpendragon What about https://github.com/projecthydra-labs/hyrax/blob/master/app/views/hyrax/collections/_show_descriptions.html.erb#L3-L6 ?
