### ISSUE TITLE
File versioning not working 

### ISSUE THREAD

**Issue by kellyChex** [samvera/hyrax#4052]
### Descriptive summary

QA Testing for Hyrax
Hyrax Version: 3.0.0.pre.rc1
Hyrax Branch: master
Hyrax Revision: 8fb0af0d375fce895864b32a5096ad44610a4471
© 2019 Samvera-Hyrax
Nurax Version
ENV: production
SHA: c1b85cf2409afd38b3cfea8499f4e207425b8fc9
Branch: 2019-09-26-12-55
Updated: 26 Sep 2019 17:55:33

### Expected behavior

Users should be able to save different file versions within a work.

### Actual behavior

Users are not able to successfully save different file versions within a work. 

### Steps to reproduce the behavior

1. Go to the show page for a work with a file https://nurax-dev.curationexperts.com/concern/generic_works/th83kz52k?locale=en 
2. Scroll down to the Items section below 
3. Click Versions under Actions on the file 
4. Choose a new file
5. Click Upload new file 
6. Says successfully updated but does not show the new version or update the thumbnail

**Comment by jeremyf** [comment]
@kellyChex I'm unable to duplicate this bug.  And I know this was reported awhile ago, but I'm wondering if there was something around waiting for the background jobs to finish?

I'm going to close this bug, but if you find time to retest this, please feel free to re-open.
