### ISSUE TITLE
Routing Error displaying in UV 

### ISSUE THREAD

**Issue by kellyChex** [samvera/hyrax#4062]
### Version

QA Testing for Hyrax
Hyrax Version: 3.0.0.pre.rc1 
Hyrax Branch: master 
Hyrax Revision: b8bb6599ab71652af7b8a12071010c00ec0ac1b7
© 2019 Samvera-Hyrax 
Nurax Version
ENV: production 
SHA: b3a84c10229fe771ca9b026b005e818c93bc69bf 
Branch: 2019-10-02-16-25 
Updated: 2 Oct 2019 21:25:59

### Expected behavior

When navigating to a Work's show page you should see an image in the Universal Viewer.

### Actual behavior

There is a routing error displaying in the Work's Universal Viewer. 

### Steps to reproduce the behavior

1. Go to Home --> Dashboard --> Works --> Works Show page for example: https://nurax-dev.curationexperts.com/concern/images/kh04dp966?locale=en 
2. See the following routing error, `No route matches [GET] "/uv/uv.html"`

### Screenshot 

<img width="1163" alt="Screen Shot 2019-10-02 at 8 18 19 PM" src="https://user-images.githubusercontent.com/9621070/66097089-fa8a7380-e551-11e9-89ef-c711b0223127.png">

**Comment by no-reply** [comment]
I think this is nurax specific issue. Can someone confirm?

**Comment by geekscruff** [comment]
This is caused by the yarn install not having been run.

**Comment by teoflax** [comment]
Hello, I'm just experiencing the same error, could you share how it was solved
