### ISSUE TITLE
Users need to be able to ingest into collections that are not their own.

### ISSUE THREAD

**Issue by tpendragon** [samvera/hyrax#407]
I think this is a base disagreement between the use cases of CC and Sufia. In CC a collection was just another resource type and all users (assuming you had permission in `ability.rb`) could assign an object to any collection. In Sufia, a collection is more of a personal curation exercise.

I see two ways to proceed:

1. Allow edit permissions to be assigned to collections.
2. Define Sufia's concept of collections as a different thing, and CC's concept as just another Curation Concern with a special part of the relationships tab.

Thoughts?

**Comment by jcoyne** [comment]
I don't know why collections shouldn't have a sharing section on their form just as works do. I think this would resolve this

**Comment by tpendragon** [comment]
We hide the sharing section, because users editing permissions complicates the workflow. We just need a space to set the default permissions, I think?

**Comment by mjgiarlo** [comment]
@tpendragon I believe @jonathandixon has enabled sharing (incl. edit permissions) on collections in 2.0.0.alpha. How close is that to what you have in mind? (I'm not sure what CC collections are, especially in light of Admin Sets and Display Sets. Whatever those are.)

**Comment by mjgiarlo** [comment]
This is high priority.

**Comment by atz** [comment]
High priority, but low clarity.  @tpendragon proposes competing solutions and @jcoyne adds a separate thought.  (Also unclear relationships to AdminSets/permissions templates.)    This is not a ticket I would pick up and consider actionable.

**Comment by mjgiarlo** [comment]
@atz @jcoyne @tpendragon So, the core requirement in this issue, as I understand it, is that all registered users should be able to manage (add/remove) works in all collections. What would y'all think about adding a new Flipflop feature that is off by default, and when turned on enables the above behavior? I wonder if many of the code changes could be encapsulated in the `Hyrax::CollectionsService`, which is already used by the `WorkForm` and `MyControllerBehavior` and elsewhere. It could use the Flipflop feature to switch how it queries the system for the list of collections a user has access to, returning all collections. Is this a feasible, more actionable approach?

**Comment by tpendragon** [comment]
Sure, that's fine.

**Comment by julesies** [comment]
I think in a post Hyrax 2.1 world this is not longer needed, so I'm going to close. If I'm missing something let me know!
