### ISSUE TITLE
Use of find_many_by_alternate_ids should not be used outside of wings as a way to find related resources

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4085]
**Not Ready for action. Discussion of the need for this change is required first.**

----

### Descriptive summary

The pattern established in Wings query service for find_by is...

* non-Wings adapters - find_by(id: id) looks for a matching primary id

* Wings adapter - find_by(id: id) assumes id is the alternate id and calls find_by_alternate_id

Following on this, it would make more sense to redefine find_many_by_ids to assume the ids are alternate ids within the Wings adapter and primary ids for non-Wings adapters.

This decision may impact our long term goal of working with any valkyrie adapter.

### Rationale

The long term goal is to support any valkyrie adapter.  It does not seem to be a valid assumption that relationships will store the alternate id when using adapters other than wings.

### Expected behavior

* For non-wings adapters... find_many_by_ids(ids:) looks for matching primary ids

* For wings...find_many_by_ids(ids:) should assume ids are alternate ids and should call custom query find_many_by_alternate_ids.

All current references to `find_many_by_alternate_ids` should be changed to `find_many_by_ids`.  

When using wings, this will effectively be the same call.  But for non-Wings, it provides two ways to find resources.

### Actual behavior

* For non-wings adapters... find_many_by_ids(ids:) looks for matching primary ids

* For wings...find_many_by_ids(ids:) looks for matching primary ids

### Related work

PR #4083 Test custom query `FindManyByAlternateIds
PR #3841 Replace ActiveFedora::Base.find(ids) calls

**Comment by no-reply** [comment]
> The long term goal is to support any valkyrie adapter. It does not seem to be a valid assumption that relationships will store the alternate id when using adapters other than wings.

This doesn't seem right.

We aren't using `alternate_id` to support constraints for Wings, we're using it as an application choice to support other adapters that can't/don't support bespoke ids.

e.g. the postgres adapter uses UUIDs **exclusively** in the `:id` field. In order to support existing Hyrax Noids, or other application generated identifiers, we must store those in `alternate_ids`. Where the application wants to do lookup based on those ids, we need to query them explicitly.

**Comment by no-reply** [comment]
is there more to resolve here? or should we close for now?

**Comment by mjgiarlo** [comment]
@elrayle :speech_balloon: 
> is there more to resolve here? or should we close for now?

@elrayle what say you?
