### ISSUE TITLE
fcrepo getting some options but not others - need to override -Dfcrepo.modeshape.configuration

### ISSUE THREAD

**Issue by svogtunh** [samvera/hyrax#4125]
### Descriptive summary

I need to change the repository.json from the default to my own to configure a database other than sqlite.  I thought the way to do this would be to override fcrepo.modeshape.configuration setting to point at my repository.json file. I did this by ading java_options in the .fcrepo_wrapper.yml and it seems to work for some options but not others.  I would appreciate any help at all.

### Expected behavior

I expected to be able to specify java options in the .fcrepo_wrapper.yml.  I do, and some of them seem to work but this one is ignored.

My .fcrepo_wrapper.yml is:

```
# Place any default configuration for fcrepo_wrapper here
# Need a method of defining installation-relative parameters (JAVA_OPTS home-dir).
port: 8984
enable_jms: false
#fcrepo_home_dir: tmp/fcrepo4-development-data
fcrepo_home_dir: /mnt/LocalDataStores/hyrax
version: 4.7.5
version_file: tmp/fcrepo_version
java_options: ['-Dfcrepo.log.auth=DEBUG',
'-Dfcrepo.log.http.api=DEBUG',
'-Dfcrepo.log.kernel=DEBUG',
'-Dfcrepo.properties.management=relaxed',
'-Dfcrepo.home=/mnt/LocalDataStores/hyrax',
'-Dfcrepo.modeshape.configuration=file:///usr/local/dev/ruby/my_app/etc/fcrepo/jdbc-postgresql/repository.json',
'-Dfcrepo.spring.jms.configuration=file:///usr/local/rvm/gems/ruby-2.6.3@my_app/gems/fcrepo_wrapper-0.9.0/data/spring-noop.xml',
'-Xmx512m']
```

### Actual behavior

START UP LOG MESSAGES:

<pre>
Oct 22 14:44:39 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: Starting Fedora 4.7.5 on port 8984 ... [main] INFO org.eclipse.jetty.util.log - Logging initialized @1223ms
Oct 22 14:44:39 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: [main] INFO org.simplericity.jettyconsole.DefaultJettyManager - Added web application on path / from war /tmp/fcrepo-webapp-4.7.5-jetty-console/fcrepo-webapp-4.7.5-jetty-console.jar
Oct 22 14:44:39 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: [main] INFO org.simplericity.jettyconsole.DefaultJettyManager - Starting web application on port 8984
Oct 22 14:44:39 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: [main] INFO org.eclipse.jetty.server.Server - jetty-9.2.3.v20140905
Oct 22 14:44:40 digitalcollections.unh.edu my_app.sh[17743]: /usr/local/rvm/gems/ruby-2.6.3@my_app/gems/valkyrie-1.7.1/lib/valkyrie/types.rb:125: warning: already initialized constant #<Module:0x0000000008a22580>::Int
Oct 22 14:44:40 digitalcollections.unh.edu my_app.sh[17743]: /usr/local/rvm/gems/ruby-2.6.3@my_app/gems/dry-types-0.12.3/lib/dry/types.rb:119: warning: previous definition of Int was here
Oct 22 14:44:40 digitalcollections.unh.edu my_app.sh[17743]: [DEPRECATION] pg will not be included as a dependency in Valkyrie's gemspec as of the next major release. Please add the gem directly to your Gemfile if you use a postgres adapter.
Oct 22 14:44:40 digitalcollections.unh.edu my_app.sh[17743]: [DEPRECATION] activerecord will not be included as a dependency in Valkyrie's gemspec as of the next major release.Please add the gem directly to your Gemfile if you use a postgres adapter.
Oct 22 14:44:45 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: [main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
Oct 22 14:44:45 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: SLF4J: Class path contains multiple SLF4J bindings.
Oct 22 14:44:45 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: SLF4J: Found binding in [jar:file:/tmp/fcrepo-webapp-4.7.5-jetty-console.jar_8984/webapp/WEB-INF/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
Oct 22 14:44:45 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: SLF4J: Found binding in [jar:file:/tmp/fcrepo-webapp-4.7.5-jetty-console.jar_8984/condi/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
Oct 22 14:44:45 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Oct 22 14:44:46 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Oct 22 14:44:46 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: [main] INFO / - 1 Spring WebApplicationInitializers detected on classpath
Oct 22 14:44:46 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: [main] INFO / - Initializing Spring root WebApplicationContext
/*****YOU CAN SEE THAT THE DEFAULT FILE-SIMPLE IS BEING USED****/
Oct 22 14:44:47 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: INFO 14:44:47.567 (ModeShapeRepositoryFactoryBean) Using repo config (classpath): file:/tmp/fcrepo-webapp-4.7.5-jetty-console.jar_8984/webapp/WEB-INF/classes/config/file-simple/repository.json
/*****BUT OTHER PROPERTIES HAVE BEEN SET AS SPECIFIED IN .FCREPO_WRAPPER.YML****/
Oct 22 14:44:47 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: INFO 14:44:47.572 (DefaultPropertiesLoader) Loading properties
Oct 22 14:44:47 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: INFO 14:44:47.572 (DefaultPropertiesLoader) com.arjuna.ats.arjuna.common.ObjectStoreEnvironmentBean.default.objectStoreDir = /mnt/LocalDataStores/hyrax/com.arjuna.ats.arjuna.common.ObjectStoreEnvironmentBean.default.objectStoreDir
Oct 22 14:44:47 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: INFO 14:44:47.572 (DefaultPropertiesLoader) com.arjuna.ats.arjuna.objectstore.objectStoreDir = /mnt/LocalDataStores/hyrax/com.arjuna.ats.arjuna.objectstore.objectStoreDir
Oct 22 14:44:47 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: INFO 14:44:47.572 (DefaultPropertiesLoader) fcrepo.object.directory = /mnt/LocalDataStores/hyrax/fcrepo.object.directory
Oct 22 14:44:47 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: INFO 14:44:47.572 (DefaultPropertiesLoader) fcrepo.binary.directory = /mnt/LocalDataStores/hyrax/fcrepo.binary.directory
Oct 22 14:44:47 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: INFO 14:44:47.572 (DefaultPropertiesLoader) fcrepo.modeshape.index.directory = /mnt/LocalDataStores/hyrax/fcrepo.modeshape.index.directory
Oct 22 14:44:47 digitalcollections.unh.edu my_app_fcrepo.sh[17742]: INFO 14:44:47.572 (DefaultPropertiesLoader) fcrepo.activemq.directory = /mnt/LocalDataStores/hyrax/fcrepo.activemq.directory
Oct 22 14
</pre>

And, you can see that my settings are being passed to the process as in:

<pre>
ps aux | grep 8984
skv2000   19466  0.9 11.7 3402156 694396 ?      Sl   14:44   0:36 java -Dfcrepo.log.auth=DEBUG -Dfcrepo.log.http.api=DEBUG -Dfcrepo.log.kernel=DEBUG -Dfcrepo.properties.management=relaxed -Dfcrepo.home=/mnt/LocalDataStores/hyrax -Dfcrepo.modeshape.configuration=file:///usr/local/dev/ruby/my_app/etc/fcrepo/file-simple/repository.json -Dfcrepo.spring.jms.configuration=file:///usr/local/rvm/gems/ruby-2.6.3@my_app/gems/fcrepo_wrapper-0.9.0/data/spring-noop.xml -Xmx512m -jar /tmp/fcrepo-webapp-4.7.5-jetty-console/fcrepo-webapp-4.7.5-jetty-console.jar --headless --port 8984
</pre>

### Steps to reproduce the behavior

1. Alter your .fcrepo_wrapper.yml to specify a new fcrepo.modeshape.configuration file
2. Restart your application.

**Comment by no-reply** [comment]
It looks a bit like you are planning to use FCRepo wrapper for production-like infrastructure. I'd recommend *very strongly* against this. (see the note here: https://github.com/samvera/hyrax/wiki/Hyrax-Development-Guide#run-the-wrappers)

The Fedora and Solr wrappers are provided as a developer convenience.

If you are wanting to change this setting for your development/test environment, I'd suggest opening a ticket on https://github.com/cbeer/fcrepo_wrapper

**Comment by rjkati** [comment]
Closed since question was answered. Please reopen if follow up is needed.
