### ISSUE TITLE
Update to 2.6.0 breaks expecting browse everything config file

### ISSUE THREAD

**Issue by gwiedeman** [samvera/hyrax#4140]
### Descriptive summary

When updating from Hyrax 2.5.1 to 2.6.0 without having previously used browse-everything or ran the browse-everything generator, Hyrax will crash expecting the browse_everything_providers.yml configuration file.

### Rationale

If browse-everything is optional to install, it should run without installing the generator. Otherwise docs should be updated.

### Expected behavior

Start as normal

### Actual behavior

Crashes expecting a browse_everything_providers.yml configuration file

### Steps to reproduce the behavior

1. Start with an 2.5.1 app without browse anything
2. Change gemfile to Hyrax 2.6.0
3. run bundle update hyrax
4. Try to rails s

**###Trace:**

"""
=> Booting Puma
=> Rails 5.1.6.2 application starting in production
=> Run `rails server -h` for more startup options
Exiting
/usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/browse-everything-1.0.1/lib/browse_everything.rb:62:in `rescue in configure': Missing browse_everything_providers.yml configuration file (BrowseEverything::ConfigurationError)
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/browse-everything-1.0.1/lib/browse_everything.rb:55:in `configure'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/browse-everything-1.0.1/lib/browse_everything.rb:77:in `config'
        from /var/www/hyrax-UAlbany/config/initializers/hyrax.rb:273:in `block in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/hyrax-2.6.0/lib/hyrax.rb:44:in `config'
        from /var/www/hyrax-UAlbany/config/initializers/hyrax.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `block in load'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:286:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/engine.rb:655:in `block in load_config_initializer'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:168:in `instrument'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/engine.rb:654:in `load_config_initializer'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/engine.rb:611:in `each'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/engine.rb:611:in `block in <class:Engine>'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/initializable.rb:48:in `each'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/initializable.rb:48:in `tsort_each_child'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `call'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/initializable.rb:58:in `run_initializers'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/application.rb:353:in `initialize!'
        from /var/www/hyrax-UAlbany/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:24:in `app'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/rack-2.0.7/lib/rack/server.rb:283:in `start'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:44:in `start'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:135:in `block in perform'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:130:in `tap'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:130:in `perform'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/command/base.rb:63:in `perform'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/command.rb:44:in `invoke'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/railties-5.1.6.2/lib/rails/commands.rb:16:in `<top (required)>'
        from /var/www/hyrax-UAlbany/bin/rails:9:in `require'
        from /var/www/hyrax-UAlbany/bin/rails:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1@hyrax/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /var/www/hyrax-UAlbany/bin/spring:15:in `require'
        from /var/www/hyrax-UAlbany/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
"""

**Comment by no-reply** [comment]
I think the issue here is *not* that Hyrax depends on browse-everything 1.0.1; it appears we still support 0.16.

Instead `bundle update hyrax` upgrades Hyrax *and all its dependencies*. Adding a local Gemfile dependency to `browse-everything` `< 1.0.0` will fix this.

I think we can resolve this by adding to the release notes: Hyrax 2.6 adds support for browse-everything 1.0+. If you choose to upgrade to BE 1.0, you'll need to take action X (see be release notes). To avoid upgrading browse everything, add Y to your gemfile.

Unfortunately `bundle update --conservative hyrax` also has this problem, *unless* browse everything has other dependents in your gemfile.

**Comment by no-reply** [comment]
Looks like the [BrowseEverything Release Notes](https://github.com/samvera/browse-everything/releases) don't mention the generator. Is it safe to recommend running it for existing apps that might already have BE routes?

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/browse-everything/compare/master...jrgriffiniii:fix-generator would address this upstream, I just need to test this with the Hyrax upgrade path outlined in this issue before issuing a patch release.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/browse-everything/pull/309 fixes the bug, I will include a version release in this, request a review, and publish a patch release to RubyGems.

**Comment by jrochkind** [comment]
> Instead bundle update hyrax upgrades Hyrax and all its dependencies. Adding a local Gemfile dependency to browse-everything < 1.0.0 will fix this.

You can also `bundle update --conservative hyrax` which will ONLY update hyrax and not _any_ of it's dependencies. Just another option, just part of what bundler supports, nothing hyrax/samvera-specific. 

Some of this is the legacy of b-e not being released in a 1.0-promissing-no-backwards-incompat-until-2.0 until recently.

**Comment by no-reply** [comment]
> You can also bundle update --conservative hyrax which will ONLY update hyrax and not any of it's dependencies. 

This isn't an accurate description of what `bundle update --conservative` does, in my understanding. `--conservative` still updates hyrax dependencies, except those that are also transitive dependencies of other packages.

**Comment by no-reply** [comment]
> Some of this is the legacy of b-e not being released in a 1.0-promissing-no-backwards-incompat-until-2.0 until recently. Ideally I'd say hyrax should have dependeded on b-e ~> 1.0, but since that wasn't available, it was perhaps depending on unrestricted b-e, meaning it can update to a backwards-incompat version at any time and hyrax isn't going to stop it.

I'm not sure I understand. The current version of `browse-everything` is `1.0.2`. Hyrax *does* have an open ended dependency, and we should probably fix that, but in practice it supports every current release in the specified range. We support `browse-everything` 0.16 and up, including the releases in the 1.0 series (which I understand to be following SemVer).

Likely I'm misunderstanding something? Is there action we can take to shore things up?

**Comment by jrochkind** [comment]
> This isn't an accurate description of what bundle update --conservative does, in my understanding. --conservative still updates hyrax dependencies, except those that are also transitive dependencies of other packages.

It's not documented very comprehensibly, but I've been using it for months and it's seemed to behave how I described to me. but I could be wrong!

**Comment by no-reply** [comment]
> It's not documented very comprehensibly, but I've been using it for months and it's seemed to behave how I described to me. but I could be wrong!

There's pretty extensive documentation at: https://bundler.io/man/bundle-update.1.html#OVERLAPPING-DEPENDENCIES
