### ISSUE TITLE
Cannot create a new work in Safari

### ISSUE THREAD

**Issue by Dananji** [samvera/hyrax#4144]
### Descriptive summary

When creating a new work, the work form doesn't show up in Safari. It works on Chrome. This was introduced in the [work done](https://github.com/samvera/hyrax/blob/master/app/assets/javascripts/hyrax/admin/admin_set/visibility.es6#L176) to fix embargo date in collections edit form in Safari. 

### Rationale

A Safari user cannot create a new work, because the form doesn't show up.

### Expected behavior
When work type is selected and `Create Work` button on the modal is clicked the work form shows up.

### Actual behavior

When clicked on `Create Work` button in the modal, the work form doesn't show up. No errors are displayed, and it stays on the `Works` page.

### Steps to reproduce the behavior

1. Sign in, in Safari
2. Go to `Works` page in the dashboard
3. Click on `Add new work` button
4. Select work type and click `Create work` in the modal
5. Modal closes and it stays on the `Works` page

### Related work

#4067

**Comment by dlim87** [comment]
This has been fixed 
![Screen Recording 2019-11-06 at 10 00 AM](https://user-images.githubusercontent.com/5492162/68324490-529a2580-007c-11ea-9d28-2c2567297469.gif)
