### ISSUE TITLE
core_metadata error on browser when brining up hyrax.

### ISSUE THREAD

**Issue by blancoj** [samvera/hyrax#4166]
### Descriptive summary

When starting hyrax, getting a `No schema defined: core_metadata` error message on the browser.  This is happening because, the config path in this method is not being computed correctly.

https://github.com/samvera/hyrax/blob/master/app/services/hyrax/simple_schema_loader.rb#L119

instead of `config/metadata/#{schema_name}.yaml` , it should be `../config/metadata/#{schema_name}.yaml`

### Rationale

Without this fix you can't start hyrax.

### Expected behavior

For Hyrax to come up.

### Actual behavior

Hyrax does not come up.

### Steps to reproduce the behavior

1. Go to local http://localhost:3000/

**Comment by dlim87** [comment]
I generated a new instance of hyrax and was able to spin it up without problems, so I think this is working properly
