### ISSUE TITLE
Allow CreateDerivativesJob to receive either an AF object or a Valkyrie resource

### ISSUE THREAD

**Issue by randalldfloyd** [samvera/hyrax#4191]
Allow CreateDerivativesJob to receive either an ActiveFedora object or a Valkyrie resource

### Descriptive summary
Convert CreateDerivativesJob to allow it to receive either an ActiveFedora based object or a Valkyrie::Resource equivalent object.

### Rationale
Allow jobs to execute correctly with existing AF implementation or the Wings Valkyrie implementation.

### Expected behavior
CreateDerivativesJob receives a Valkyrie::Resource and performs the action.

### Actual behavior
CreateDerivativesJob raises an exception when passed a Valkyrie::Resource.

### Approach for Conversion
[See Pattern for Jobs Receiving Parameter that may be an AF Object or a Valkyrie Resource](https://docs.google.com/document/d/1f9yDjtkXapFf1DYLyPhprnB4CPGaZw9p_k8T_tcor-U/edit#heading=h.qt9rxydfd727)

### Related work

These have all be modified to support AF object or Valkyrie resource using the [established pattern](https://docs.google.com/document/d/1f9yDjtkXapFf1DYLyPhprnB4CPGaZw9p_k8T_tcor-U/edit#heading=h.qt9rxydfd727). 

* Issue #4101 Allow GrantEditToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4102 Allow GrantReadToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4103 Allow RevokeReadToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4099 Add GlobalID::Identification for resources passed to jobs (PR #4124)

**Comment by mjgiarlo** [comment]
May be blocked by #4060.

**Comment by hackartisan** [comment]
related work: https://github.com/samvera/hyrax/pull/5540

**Comment by no-reply** [comment]
some discussion occurred in Slack https://samvera.slack.com/archives/CDRHAMUTV/p1692716666450449.

> I don't think we need to update the existing job

**Comment by hackartisan** [comment]
Created https://github.com/samvera/hyrax/issues/6162 and closing this.
