### ISSUE TITLE
use a Dry::Struct/Types default for FileMetadata type attribute

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4226]
### Descriptive summary

In file `app/models/hyrax/file_metadata.rb`, method `#for` sets the default of type to `Hyrax::FileSet::ORIGINAL_FILE`.  It is preferred to use a Dry::Struct/Types default in the type definition instead of in the `#for` method.

This would look something like...

```
attribute :type, ::Valkyrie::Types::Set, default: [Hyrax::FileSet.original_file_use]
```

Need to determine the impact this will have on setting the `type` in the `#for` method.

### Related work

PR #4225 [Requested change](https://github.com/samvera/hyrax/pull/4225#discussion_r371544309)

**Comment by no-reply** [comment]
@elrayle are there any cases where we want to use `.for` to make anything other than an `original_file`?

**Comment by elrayle** [comment]
**Short answer:** I am fine with dropping `.for`.  We can always add it back in if it is needed later.

**Longer answer:**

FileMetadata was originally created to follow the same conventions set out in [figgy's FileMetadata](https://github.com/pulibrary/figgy/blob/master/app/resources/nested_resources/file_metadata.rb#L38-L46).  The `.for` method is calling in 5 places in figgy, 2 of which are from tests.

The only place I see `FileMetadata.for` in use is in Hyrax is in [file_actor_spec](https://github.com/samvera/hyrax/blob/master/spec/actors/hyrax/actors/file_actor_spec.rb#L143-L147)

I believe the original thought was that it might be useful in a later part of the valkyrization process, e.g. when the derivative creation process was converted to use valkyrie.  But any such use is hypothetical at this point in time.

**Comment by no-reply** [comment]
@elrayle i think you've misinterpreted me. i like `.for`, i'm asking about the `.try(:type) || [default]` pattern in it.

as far as i can tell, the documented supported parameter never has `#type` method, so will always use the default. if that's the case, we can just use a `Dry::Struct` style default and drop the line that tries `.try(:type)`

**Comment by no-reply** [comment]
after a conversation in slack, we've agreed to go ahead and drop `.for` which is only used for convenience in tests
