### ISSUE TITLE
Replacement for file_set.original_file

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4233]
### Descriptive summary

AF filesets had method `#original_file` which was a quick way to get the original file for a fileset and is used extensively.  PR #4215 removes the `#original_file` method from the valkyrie resource equivalent Hyrax::FileSet.  The reason for the removal is that all knowledge of the use of a file was moved to Hyrax::FileMetadata.

This results in the following code being used to get the original file (ex. from PR #4215)

```
      def current_original_file(file_set)
        Hyrax.query_service
             .custom_queries
             .find_many_file_metadata_by_use(resource: file_set, use: Hyrax::FileMetadata::Use::ORIGINAL_FILE)
             .first
      end
```

It is undesirable to have this code block repeated throughout Hyrax.  To resolve this, a single method should be created that all other places original_file is needed can call.

### Related work

PR #4215 Create `FileSetDescription` to find characterization for FileSets
PR #4225 handle conversion of custom use types for files

**Comment by no-reply** [comment]
This is closed by #4236.
