### ISSUE TITLE
Presenters can't vary which presenters are generated for children anymore.

### ISSUE THREAD

**Issue by tpendragon** [samvera/hyrax#424]
This was a regression introduced when the MemberPresenterFactory was added. The factory itself can have the work presenter class changed, but that can't be different for different presenters.

I can work around this locally by creating a special conditional factory to set to the work_presenter_class, but ideally we should be passing in those classes as part of the initialization of the MemberPresenterFactory.

**Comment by tpendragon** [comment]
That's useful, but I don't think so. The factory is called from a variety of places and needs different presenters in each. I think we want a pattern for a configurable presenter factory.

**Comment by jeremyf** [comment]
So in cases where the MemberPresenterFactory is instantiated, add to the instantiating class a configurable `work_presenter_class` and `file_presenter_class` that is passed to the instantiation of the MemberPresenterFactory?

For example, tweak this class:

```ruby
module Hyrax
  module Forms
    class FileManagerForm
      include HydraEditor::Form
      self.terms = []
      delegate :id, :thumbnail_id, :representative_id, :to_s, to: :model
      attr_reader :current_ability, :request
      def initialize(work, ability)
        super(work)
        @current_ability = ability
        @request = nil
      end

      def version
        model.etag
      end

      delegate :member_presenters, to: :member_presenter_factory

      private

        def member_presenter_factory
          MemberPresenterFactory.new(model, current_ability)
        end
    end
  end
end
```

https://github.com/projecthydra-labs/hyrax/blob/595a5c3b32b0a8e5466744f2f6b59a92276a47fe/app/forms/hyrax/forms/file_manager_form.rb#L23

**Comment by tpendragon** [comment]
That's probably a good idea, but we should pass in the factory rather than the classes, so we're not just passing in something to instantiate something.

That being said, I'm concerned it's a lot of configuration for what's a fundamental problem: given a solr document, build the appropriate presenter. It was solved before by configuring that at the controller level, but even that had problems if a single object could have multiple types of children with their own presenters.

In Plum we use a dynamic presenter for instantiation, I think a configurable form of that would be beneficial here: https://github.com/pulibrary/plum/blob/master/app/presenters/dynamic_show_presenter.rb

**Comment by jeremyf** [comment]
@tpendragon I think that is perhaps the first step…I believe the pattern we are looking for is a Factory Factory.

I pass the document and the context (e.g. controller) and the class makes the decision. Thinking of the method interface, something along the following lines.

```ruby
Presenter.registered_presenter_builders = [
  # insert stack here
]
document_presenter = Presenter.new(to_present: document, context: controller)
```

The `.build_for` method would then loop through the registered finders…

```ruby
def self.new(to_present:, context:)
  presenter_builder = registered_presenter_builders.detect { |b| b.can_present?(to_present: to_present, context: context) }
  presenter_builder.new(to_present: to_present, context: context)
end
```

We could then expose the customization for the registered_presenter_builder. (A natural extension of this is that we end up asking the presenter to render itself; after all it should know the partial it should use)

**Comment by no-reply** [comment]
I moved this to backlog, since it doesn't look like it's a clearly actionable ticket as written.
