### ISSUE TITLE
CollectionsMembershipActor adds the collection when the _destroy flag is true. 

### ISSUE THREAD

**Issue by simonmchoy** [samvera/hyrax#4269]
### Descriptive summary

When removing a collection after adding it to a work, CollectionsMembershipActor still adds the collection even though the _destroy flag is set to true. 

This is happening in both new/update works, in version 2.4.1, 2.7.0, and most likely 3.x.

### Rationale

After a user adds a collection, the user might change his/her mind and remove it before saving the work.  In this case if the collection's _destroy flag is true, it should not get added when the work is saved.

I believe we need to check if _destroy is set to true before calling the add method here:

https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/collections_membership_actor.rb#L51

### Expected behavior

Collection should not be added when _destroy flag is true

### Actual behavior

Collection gets added when _destroy flag is true

### Steps to reproduce the behavior

1. Edit an existing work
2. Add a collection to the work
3. Remove the collection (before saving)
4. Save the work

**Comment by no-reply** [comment]
thanks for the report. @elrayle is going to look into it and thinks the fix will be simple

**Comment by simonmchoy** [comment]
Thanks.  Btw, I just checked in a fix in our project, so I also can look into putting it in Hyrax code base, if it can wait.

**Comment by jeremyf** [comment]
@simonmchoy Please post a gist of that fix. I can add that fix to the core code-base.

**Comment by simonmchoy** [comment]
@jeremyf , basically i changed the else block to this in around line 51:

  else
    add(env, attributes['id']) unless
      ActiveModel::Type::Boolean.new.cast(attributes['_destroy'])
  end

thanks.

**Comment by jeremyf** [comment]
Closed by #4278
