### ISSUE TITLE
Remove public user index

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#438]
@cam156 stated that in Scholarsphere:  "in 2016 the index was viewed 31 times out of the 1,642 views of all of the individual user pages.  That seems low."

The primary use case was so that librarians can see the users. Since we now have an admin user list, we need not maintain the public index.

**Comment by vantuyls** [comment]
closing this out of preference for the duplicate at:
https://github.com/samvera/hyrax/issues/3112
