### ISSUE TITLE
Add left sidebar to logged-in user pages

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#441]
To build on the UX introduced with the Hyrax admin dashboard, the left sidebar should be added to all of the pages that a logged-in user uses for administrative and content management tasks.

The attached mockups show how this sidebar looks for the roles that do not have administrative privileges for the repository or for admin sets: registered user, admin set depositor, admin set reviewer. (Other parts of the mockups are obviously skeletal, and not intended as a focus for this ticket.) 

With these functions moved to the left sidebar, the top menu bar is impacted. The “Dashboard”, “Works” and “Collections” menus are no longer presented, as the pages they encompass are now accessed from the left sidebar when the user is in the administration context. "Administration" is accessed on a menu revealed by clicking on the user name in the upper right. Clicking on “Administration” takes the user to the "Your Activity" Screen. "Notifications" link remains in the top bar to the left of the user name.

This is an overarching explanatory ticket. Individual tickets are linked for each of the user pages to get the left sidebar. 

![activitysummary](https://cloud.githubusercontent.com/assets/1801076/23084971/db9bf294-f519-11e6-9036-d50025a77e00.png)

**Comment by hannahfrost** [comment]
Still need to add a ticket about making the left sidebar collapsible, as shown in https://github.com/projecthydra-labs/hyku/issues/447

**Comment by vantuyls** [comment]
can we close this?

**Comment by mjgiarlo** [comment]
I think so. @hannahfrost?
