### ISSUE TITLE
Give approver edit access for new works [one step mediated deposit]

### ISSUE THREAD

**Issue by njaffer** [samvera/hyrax#4411]
### Descriptive summary

Assigning approver role does not grant access to newly created works with one step mediated deposit

### Rationale

When a user is assigned as an approver, they do not see the newly deposited works pending for approval. Making the approver admin solved the issue.

### Expected behavior
When a user is made an approver, they should see all the new deposits on their dashboard

### Actual behavior
When a user is made an approver, they DO NOT see all new deposits on their dashboard

### Steps to reproduce the behavior

1. Assign a user "approver" role 
2. Create a new work
3. Ask the "Approver" user to check their dashboard of they see the new deposit and can approve the deposit

### Related work

Link to related tickets or prior related work here.

**Comment by blancoj** [comment]
@njaffer what I found in testing this is that if work is crated under mediated deposit and it is public, and say you have user1 as the approver, user1 can approve the work and the work will show up in the "Review Submissions" page on user1's dashboard.  Note user1 is not an admin for this test.

Now, if the work created is private, then the work shows up on the "Review Submissions" page for user1, but when he/she clicks on the link to that work, he/she will get an "Unauthorized" message.  It seems like user1 should be able to approve private works, right?

**Comment by eporter23** [comment]
Tested in Hyrax 3.5 and this appears to be resolved.
