### ISSUE TITLE
Add left sidebar to Collections page where logged-in user manages their collection(s)

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#442]
Per https://github.com/projecthydra-labs/hyrax/issues/441

![collections](https://cloud.githubusercontent.com/assets/1801076/23085317/e5ec80a4-f51b-11e6-8607-6425dfb64a60.png)

**Comment by vantuyls** [comment]
I believe we can close this?

**Comment by mjgiarlo** [comment]
@vantuyls You mean because the CE work cycle is covering it, or what? Pulling in @elrayle to confirm this or something like it is already in-scope for that work. Also pinging @hannahfrost and @ggeisler to loop 'em in.

**Comment by ggeisler** [comment]
Yes, I believe this is now covered by #1417.

**Comment by mjgiarlo** [comment]
Thanks, @ggeisler @vantuyls
