### ISSUE TITLE
Sharing existing work on Twitter when user not logged in to twitter.

### ISSUE THREAD

**Issue by SumithBaddam** [samvera/hyrax#4511]
### Descriptive summary

Testing on Hyrax 3.0.0 on Firefox browser.

--
When clicking on twitter icon, it takes to the twitter window but then it doesn't prompt for login. But if I am logged in, it works as expected. This is the same case with both windows and firefox. Same on Chrome Mac but this might be more to do with Twitter's interface for logging in than any Hyrax problem. When logged into Twitter, this works as expected.

### Expected behavior
When user is not logged in to twitter, it should redirect him to login page.

### Actual behavior
It is not redirecting to login page.

### Steps to reproduce the behavior

1. Click on an item
2. "View"" page displays
3. Visibility tags display
4. Download link displays
5. Click on the Twitter icon
6. If the user is not logged in to Twitter in the browser, the platform's login page will display
7. If the user is already logged in to Twitter account in the browser, then the user will be brought to a New Post page on Twitter's site
8. The New Post page on Twitter's site will contain the work's title and URL

**Comment by no-reply** [comment]
@dlpierce since twitter doesn't exist anymore, can this be closed?
