### ISSUE TITLE
Adding existing managed works to a collection clears pre-selection

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#4513]
### Descriptive summary

When adding managed works to an existing collection via the collection’s edit page, the pre-selected collection name is cleared after the user clicks the “managed works” tab.

### Rationale

Adding managed works and the user’s own works to a collection should have the same behavior.

### Expected behavior
The collection name should be pre-selected when adding both managed works and the user’s own works to a collection from the collection’s edit page.

### Actual behavior
The collection name is not pre-selected when adding managed works to a collection from the collection’s edit page.

### Steps to reproduce the behavior

Prerequisite: Must have manager or depositor access to a collection and two managed works which are not already in that collection.

1. Go to the collections page for your managed collection: https://nurax-dev.curationexperts.com/dashboard/collections/qv33rw82t?locale=en
2. Click “add existing works to the collection”: https://nurax-dev.curationexperts.com/dashboard/my/works?add_works_to_collection=qv33rw82t&add_works_to_collection_label%5B%5D=collections+testings+for+hyrax+3.0&locale=en
3. Click “managed works” tab: https://nurax-dev.curationexperts.com/dashboard/works?locale=en
4. Select two managed works
5. Click “Add to Collection”
6. The collection name is blank.

**Comment by jeremyf** [comment]
@rjkati  I'm unable to duplicate this behavior, for each of the above steps, could you provide a URL.  I'm uncertain if I'm following the same path.

**Comment by rjkati** [comment]
@jeremyf, I've added links to the initial comment per your request. however I'm not sure if you have manager access to the collection. I'm happy to walk through it at standup if that's helpful.

@jlhardes this issue is still present in Hyrax 3.0.2

**Comment by jlhardes** [comment]
The All Works tab in this process is not pulling the collection name through to assign the selected works.

**Comment by eporter23** [comment]
This appears to be resolved. I was able to add several works to 2 different collections using the steps noted above. 
<img width="873" alt="Screen Shot 2022-04-27 at 9 16 16 AM" src="https://user-images.githubusercontent.com/13855987/165532274-5f248985-0b05-44bd-a221-a07e2b7f286c.png">
