### ISSUE TITLE
Deactivate Embargoes from Manage Embargoes dashboard tab does not work

### ISSUE THREAD

**Issue by mcdowney** [samvera/hyrax#4515]
### Descriptive summary

Attempting to deactivate expired embargoes from the Manage Embargoes section of the dashboard UI does not succeed in deactivating the embargoes.

This is happening on 3.0.0.pre.rc2 in Chrome, Safari and Firefox.

### Rationale

This seems to have been introduced into the 3.0 release candidate since the most recent round of testing, and was discovered pursuant to test RA_1.18 in the testing script.

### Expected behavior

Selecting one or more Expired Active Embargoes from the "Expired Active Embargoes" tab and clicking on "Deactivate Embargoes for Selected" should remove the embargoes from the selected work(s). 

### Actual behavior

The green modal declaring "Deactivation succeeded!" appears, but the works remain embargoed and in the list of Expired Active Embargoes.

### Steps to reproduce the behavior

1. As an admin user, navigate to Dashboard > Tasks > Manage Embargoes.
2. Click on "Expired Active Embargoes"
3. Select one or more expired embargoes to deactivate.
4. Click on "Deactivate Embargoes for Selected"
5. Find the works still in the Expired Active Embargoes list

### Related work

Link to related tickets or prior related work here.

**Comment by jeremyf** [comment]
This commit ( 241cbed1df4ad416b8d44763ae321e642443ed88 ) changed the form field names, which in turn broke the batch behavior.  I'm reviewing what needs to be done.
