### ISSUE TITLE
Deactivating Leases from Manage Leases dashboard tab does not work

### ISSUE THREAD

**Issue by mcdowney** [samvera/hyrax#4516]
### Descriptive summary

Attempting to deactivate expired leases from the Manage Leases section of the dashboard UI does not succeed in deactivating the leases.

This is happening on 3.0.0.pre.rc2 in Chrome, Safari and Firefox.

### Rationale

This seems to have been introduced into the 3.0 release candidate since the most recent round of testing, and was discovered pursuant to test RA_1.19 in the testing script.

### Expected behavior

Selecting one or more Expired Active Leases from the "Expired Active Leases" tab and clicking on "Deactivate Leases for Selected" should remove the embargoes from the selected work(s).

### Actual behavior

The green modal appears, advising user to "Select something first", but the works remain in the list of Expired Active Leases. Works scheduled to revert to private after lease expiration remain public.

### Steps to reproduce the behavior

1. As an admin user, navigate to Dashboard > Tasks > Manage Leases.
2. Click on "Expired Active Leases"
3. Select one or more expired leases to deactivate.
4. Click on "Deactivate Leases for Selected"
5. Find the works still in the Expired Active Leases list

### Related work

Link to related tickets or prior related work here.

**Comment by rjkati** [comment]
Deactivating leases using instructions above now displays an error message in iOS Safari and Chrome:

![Image from iOS (1)](https://user-images.githubusercontent.com/32644254/112487033-ccef4680-8d52-11eb-8623-b42f37eff01f.png)

https://nurax-dev.curationexperts.com/leases?locale=en

**Comment by no-reply** [comment]
this latest seems like a new bug. can we open a new ticket for it?
