### ISSUE TITLE
Updating Embargoes from the Manage Embargoes dashboard tab does not work

### ISSUE THREAD

**Issue by mcdowney** [samvera/hyrax#4517]
### Descriptive summary

Attempting to update active embargoes from the Manage Embargoes section of the dashboard UI does not succeed in updating the embargoes.

This is happening on 3.0.0.pre.rc2 in Chrome, Safari and Firefox.

### Rationale

This seems to have been introduced into the 3.0 release candidate since the most recent round of testing, and was discovered pursuant to test RA_1.20 in the testing script.

### Expected behavior

Clicking on a work in the list of All Active Embargoes from the Manage Embargoes tab should take you to a form that allows you to update the date of expiration for the active embargo. Clicking on "Update Embargo" should persist the change and take the user to the Work's show page, where the updated embargo date now appear.

### Actual behavior

Changing the date of expiration for the embargo does nothing. The user is taken to the work show page, where the green modal appears with the message "Work 'X' successfully updated," but the date listed under "Embargo release date" in the work's metadata remains the old date of expiration.

### Steps to reproduce the behavior

1. As an admin user, navigate to Dashboard > Tasks > Manage Embargoes.
2. Click on a Generic Work in the list of All Active Embargoes
3. Change the desired embargo date.
4. Click on "Update Embargo".
5. Notice the embargo release date in the work's metadata remains the same.

### Related work

Link to related tickets or prior related work here.

**Comment by eporter23** [comment]
Re-tested in Hyrax 3.5 and 4 beta2 and this issue appears to be resolved.
