### ISSUE TITLE
Deleting a Collection from collection's admin show page should give more verbose warning dialogue

### ISSUE THREAD

**Issue by mcdowney** [samvera/hyrax#4523]
### Descriptive summary

Attempting to delete a collection by clicking the "Delete collection" button from a collection's administrative show page has a much briefer warning dialogue than is desirable. 

This is happening on 3.0.0.pre.rc2 in Chrome, Safari and Firefox.

### Rationale

Users should receive the same messaging when attempting to delete a collection from the administrative show page interface that they do when trying to delete a collection from the Dashboard.

### Expected behavior

The testing script indicates that on clicking "Delete collection" from a collection's administrative show page, a the user should be presented with a modal contain one of two warnings:
1. For collections with constituent works: "Deleting this collection will permanently remove this collection from the repository. Items in this collection will remain in the repository. Are you sure you want to delete this collection?'"
2. For collections without constituent works: "Are you sure you want to delete this collection? This action cannot be undone."

### Actual behavior

On clicking "Delete collection" from a collection's administrative show page, the user is presented with a modal that simply says "Delete this collection?"

### Steps to reproduce the behavior

1. As a logged in user, navigate to Dashboard > Collections > Managed collections
2. Click on the title of a collection for which you have Manager privileges.
3. On the administrative show page, click on "Delete collection"
4. See the brief warning dialogue.

### Related work

Link to related tickets or prior related work here.

**Comment by jeremyf** [comment]
@mcdowney Could you point me to the testing script?

I'm hesitant to add conditional logic into the text of the confirmation modal.  My preference would be to modify the language to the following, and better support both cases without adding switching logic:

> Deleting this collection will permanently remove this collection from the repository. Any items in this collection will remain in the repository. Are you sure you want to delete this collection? This action cannot be undone.

Thoughts @jlhardes ?

**Comment by mcdowney** [comment]
Hi @jeremyf, here is a link to the testing script: https://docs.google.com/spreadsheets/d/1XxG00RCkypCqLjfzx2RnoKLbZdaMxXMbW8A4hNHRrc0/edit?usp=sharing

The issue in question is in the Collection - sharing tab, the very last scenario.

My two cents is that what you propose sounds great; I think the objection was that there was a circumstance under which users were not getting the more verbose messaging, but that more verbose messaging is preferable. Happy to defer to @jlhardes here, though.
