### ISSUE TITLE
Extract ActorStack validations

### ISSUE THREAD

**Issue by jeremyf** [samvera/hyrax#4529]
## Descriptive summary

Building from the [following document](https://github.com/samvera/hyrax/wiki/Proposed-High-Level-Outline-for-Deprecating-the-ActorStack), extract the validations of the actor stack.

- [ ]    Hyrax::Actors::OptimisticLockValidator
- [ ]    Hyrax::Actors::CreateWithRemoteFilesActor
- [ ]    Hyrax::Actors::CreateWithFilesActor
- [ ]    Hyrax::Actors::CollectionsMembershipActor
- [ ]    Hyrax::Actors::AddToWorkActor
- [ ]    Hyrax::Actors::AttachMembersActor
- [ ]    Hyrax::Actors::ApplyOrderActor
- [ ]    Hyrax::Actors::DefaultAdminSetActor
- [ ]    Hyrax::Actors::InterpretVisibilityActor
- [ ]    Hyrax::Actors::TransferRequestActor
- [ ]    Hyrax::Actors::ApplyPermissionTemplateActor
- [ ]    Hyrax::Actors::CleanupFileSetsActor
- [ ]    Hyrax::Actors::CleanupTrophiesActor
- [ ]    Hyrax::Actors::FeaturedWorkActor
- [ ]    Hyrax::Actors::ModelActor
- [ ]    Hyrax::Actors::InitializeWorkflowActor

## Things to consider

Given that downstream adopters may have altered the actor stack, there may be some challenges.  As an initial way forward, we could inject at the beginning of the stack an actor that performs all of the validations performed in the above actors.

This assumes that downstream implementations have not removed actors from the stack.  At present, we don't need to worry about composition.

The extracted validations should not mutate parameters, this behavior would continue in the existing actors that changes state to perform mutations.

To fully insulate our changes, we could create N+1 actors; One actor that contains the validation and one new actor for each of the above defined actors.  We would then swap out the existing actors for the new narrower focus actors.  I believe this would require coordination with downstream implementations, as anyone injecting new actors in the stack may lose their injection points.

In addition, there are different types of validations to consider:

1) User input validation; this should be separated from the other validations.  Examples include: "title missing", "title too long"
2) Application/data state validation; do we have a well-formed admin set that has its permission template?  This is the business logic, and should be re-usable outside of the controller/view logic.

**Comment by elrayle** [comment]
RE: actors in apps - An [actor](https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/work/templates/actor.rb.erb) is generated when the work is generated.  Our local app does use significant work in these generated actors.

**Comment by jeremyf** [comment]
The following actors have some form of validation:

* `Hyrax::Actors::OptimisticLockValidator` - Form’s working version is not current working version
* `Hyrax::Actors::CreateWithRemoteFilesActor` - Validate’s remote URL with registered ingest directory
* `Hyrax::Actors::CreateWithFilesActor` - Validates that the given user owns the files
* `Hyrax::Actors::CollectionsMembershipActor` - Validates that the work can belong to the specified collections
* `Hyrax::Actors::AddToWorkActor` - Verify that the acting user can edit the parent and child works
* `Hyrax::Actors::InterpretVisibilityActor` - validates visibility regarding embargo and lease parameters 
* `Hyrax::Actors::ApplyOrderActor` - Similar to AddToWorkActor, validate if works can be related by the current user
