### ISSUE TITLE
Relationship between User.id and Agent.proxy_for_id

### ISSUE THREAD

**Issue by escowles** [samvera/hyrax#453]
Currently, User.id is an integer, but Agent.proxy_for_id is a varchar which can either be a reference to User.id, or a magic value such as "admin" or "registered".  Should we split these two types of values up, so Agent.proxy_for_id can be a simple integer referencing User.id?

Having the type mismatch results in having to do typecasting and account for the differences, e.g.:

https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/workflow/permission_query.rb#L261

See also discussion in https://github.com/projecthydra/curation_concerns/pull/1153

**Comment by jcoyne** [comment]
group ids are strings.   So, no I don't think we could split those up.

**Comment by jcoyne** [comment]
@escowles @cbeer is there anything actionable here or can we close?

**Comment by jcoyne** [comment]
@escowles this is getting stale. can it be closed?
