### ISSUE TITLE
thinking about analytics

### ISSUE THREAD

**Issue by Jake-Marley** [samvera/hyrax#4564]
### Descriptive summary

consider the analytics dashboard. count. count the things. [rattle, rattle]

### Rationale

I wear the chain I forged in life,” replied the Ghost. “I made it link by link, and yard by yard; I girded it on of my own free will, and of my own free will I wore it. Is its pattern strange to you?”

### Expected behavior

comprehensive analytics. [rattle]

### Actual behavior

empty. so...cold...[rattle, rattle]

**Comment by ghost-of-christmas-still-to-come** [comment]
"I am in the presence of the Ghost of Christmas Yet To Come?" said Scrooge.
The Spirit answered not, but pointed onward with its hand.
"You are about to show me shadows of the things that have not happened, but will happen in the time before us," Scrooge pursued. "Is that so, Spirit?"
The upper portion of the garment was contracted for an instant in its folds, as if the Spirit had inclined its head.

**Comment by ghost-of-christmas-still-to-come** [comment]
<img width="1204" alt="Screen Shot 2020-10-30 at 9 11 54 AM" src="https://user-images.githubusercontent.com/73671133/97729474-02d41b80-1a90-11eb-983d-4f6c4cf136e6.png">

[Larger Copy](https://repo.samvera.org/concern/images/e479d840-3dbe-4905-bc9a-84662791eb2a?locale=en#?c=0&m=0&s=0&cv=0&xywh=-944%2C0%2C4387%2C1875)
