### ISSUE TITLE
Reduce time to save using wings adapter

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4568]
### Descriptive summary

It takes almost 10x as long to save a resource using the Wings adapter as when calling save on an ActiveFedora (AF) object.  To save, Wings converts the resource to and AF object and then calling save on that object.  After saving, the updated AF object is converted back to a resource.  It is expected to be slower than saving directly with AF, but not 10x slower.

Most likely, the round-trip conversion is happening multiple times.  Need to explore the persistence process to find where the conversions are happening and determine if some can be eliminated, combined, or re-worked.

### Rationale

Saving with wings should only be a little slower and ideally only involve 1 round-trip conversion.

### Expected behavior

Running the steps to reproduce, the time to save with wings persister should only be slightly longer than the time to save the AF object.

### Actual behavior

Running the steps to reproduce, the time to save with wings persister is almost 10x longer than the time to save the AF object.

### Steps to reproduce the behavior

1. Setup the object and resource
```
af_gw1        = GenericWork.new(title: ["af generic work 1"])
wings_m1 = Monograph.new(title: ["wings monograph resource 1"])
```

2. Capture time to save the object...
```
af_gw1.save
```

3. Capture time to save the resource...
```
Hyrax.persister.save(resource: wings_m1)
```

**Comment by no-reply** [comment]
we have a number of benchmarks in place now, which have steadily improved as work has continued since october. i'm going to close this now as lacking a clear scope beyond that.

if there are useful performance targets we should reach for, we can open another ticket to work on them.
