### ISSUE TITLE
Explore whether collection types are working with Hyrax::PcdmCollections

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4589]
### Descriptive summary

Determine if collection types are working with Hyrax::PcdmCollections.

### Rationale

Collection types are core to Hyrax and should work with Valkyrie versions of Collections.

### Expected behavior

Add feature tests for creating collections from the UI using Valkyrie and ensuring collection type behavior works. There are existing `collection_type_spec` feature specs, probably these can be ported to swap in the valkyrie models.

Expect collection types to work with Hyrax::PcdmCollections.

### Actual behavior

If actual does not match expected, open an issue with details about what actual happened and what was expected.

**Comment by no-reply** [comment]
blocked by #4590

**Comment by no-reply** [comment]
i don't think this is blocked anymore. AFAIK collection creation works and is tested, so it should be possible to explore interactions with collection types.

**Comment by rjkati** [comment]
I ran through the collection types tests on pg.nurax and everything passed. https://docs.google.com/spreadsheets/d/1GPwpGuIlReciKkNeNUp-2N8enuxX3_a4jf-tnU-wlnA/edit#gid=1874707375

I think we can consider this ticket completed and open new tickets to address specific problems as they occur.
