### ISSUE TITLE
Document process for setting up Hyrax based app for development using Docker

### ISSUE THREAD

**Issue by JzGo** [samvera/hyrax#4630]
### Descriptive summary

Detail steps required to start developing a Hyrax based app using the Hyrax Dockerfile and `docker-compose`

### Rationale

As a Hyrax based app developer, I would like to be able to set up all the required services within a containerized Docker environment to simplify and standardize my workflow with Hyrax applications

**Comment by rjkati** [comment]
@jlhardes does the documentation in https://github.com/samvera/hyrax/blob/main/CONTAINERS.md satisfy this ticket?

**Comment by jlhardes** [comment]
Yes! Those are the instructions for getting Hyrax up and running with Docker. Closing this issue.
