### ISSUE TITLE
Add bibliographic_citation to the form

### ISSUE THREAD

**Issue by noraegloff** [samvera/hyrax#4632]
**Descriptive summary**
bibliographic_citation appears in [basic_metadata.rb](https://github.com/samvera/hyrax/blob/2.5.1/app/models/concerns/hyrax/basic_metadata.rb#L37) but does not appear in the form when editing, creating, or viewing a Work in Nurax, which is running Hyrax Version: 3.0.0.pre.rc2.

**Rationale**
Many publishers mandate that a full bibliographic citation be included in the metadata for any preprints or postprints of scholarly publications that are made available in institutional repositories.  

**Related work**
There was consensus in the discussion on issue #4286 for having 'all user supplied metadata expressed in [basic_metadata.rb] listed on the edit form and displayed on the single item show view.' That would also apply in this case.

**Comment by rjkati** [comment]
bibliographic_citation does not appear on the Generic Work or Image form on nurax-dev, which is currently running Hyrax 3.0.2

**Comment by jlhardes** [comment]
Bibliographic Citation is now a form field when adding or editing a work and values are stored in that field on nurax-dev. Any values entered, however, are not showing on the work view page. I will create another issue to show this metadata when there is a value for bibliographic citation.
