### ISSUE TITLE
Thumbnail path service unnecessarily attempts to convert thumbnail for a Generic Work to valkyrie object

### ISSUE THREAD

**Issue by bkeese** [samvera/hyrax#4647]
### Descriptive summary

On a docker dev build (at least), clicking on a thumbnail for a fileset of a Generic Work produces an error.

### Steps to reproduce the behavior

Branch: docker_fits
docker-compose build
docker-compose up
log in as archivist1@example.com
click dashboard
click works
click add new work
select Generic Work
complete required fields and add .png file
check deposit agreement and save

this error appears in the log:

app_1         | E, [2020-12-03T18:14:46.710571 #1] ERROR -- : [ActiveJob] [CreateDerivativesJob] [09a4ebe5-c0b2-4463-a63f-82fe00bfed02] Error performing CreateDerivativesJob (Job ID: 09a4ebe5-c0b2-4463-a63f-82fe00bfed02) from Async(default) in 953.42ms: NoMethodError (undefined method `permissions' for #<#<Class:0x0000559129d09ac0>:0x0000559126e232d8>
app_1         | Did you mean?  permission_manager):
app_1         | /app/samvera/hyrax-engine/lib/wings/model_transformer.rb:67:in `ensure_current_permissions'
app_1         | /app/samvera/hyrax-engine/lib/wings/model_transformer.rb:56:in `block in build'
app_1         | /app/samvera/hyrax-engine/lib/wings/model_transformer.rb:56:in `tap'
app_1         | /app/samvera/hyrax-engine/lib/wings/model_transformer.rb:56:in `build'
app_1         | /app/samvera/hyrax-engine/lib/wings/model_transformer.rb:39:in `for'
app_1         | /app/samvera/hyrax-engine/lib/wings/valkyrizable.rb:21:in `valkyrie_resource'
app_1         | /app/samvera/hyrax-engine/lib/wings/valkyrie/resource_factory.rb:32:in `to_resource'
app_1         | /app/samvera/hyrax-engine/lib/wings/valkyrie/query_service.rb:81:in `find_by_alternate_identifier'
app_1         | /app/samvera/hyrax-engine/app/services/hyrax/thumbnail_path_service.rb:27:in `fetch_thumbnail'
app_1         | /app/samvera/hyrax-engine/app/services/hyrax/thumbnail_path_service.rb:10:in `call'
app_1         | /app/samvera/hyrax-engine/app/services/hyrax/indexes_thumbnails.rb:28:in `thumbnail_path'
app_1         | /app/samvera/hyrax-engine/app/services/hyrax/indexes_thumbnails.rb:23:in `index_thumbnails'
app_1         | /app/samvera/hyrax-engine/app/services/hyrax/indexes_thumbnails.rb:16:in `block in generate_solr_document'
app_1         | /app/samvera/hyrax-engine/app/services/hyrax/indexes_thumbnails.rb:15:in `tap'
app_1         | /app/samvera/hyrax-engine/app/services/hyrax/indexes_thumbnails.rb:15:in `generate_solr_document'
app_1         | /app/samvera/hyrax-engine/app/indexers/hyrax/indexes_workflow.rb:10:in `generate_solr_document'
app_1         | /app/samvera/hyrax-engine/app/indexers/hyrax/work_indexer.rb:9:in `generate_solr_document'

then when clicking the thumbnail in the work show page, you get this:

ArgumentError in Hyrax::FileSetsController#show
Nil location provided. Can't build URI.

add_breadcrumb I18n.t("hyrax.file_set.browse_view"), main_app.hyrax_file_set_path(params["id"])
      when 'show'
        add_breadcrumb presenter.parent.to_s, main_app.polymorphic_path(presenter.parent)
        add_breadcrumb presenter.to_s, main_app.polymorphic_path(presenter)
      end
    end

Rails.root: /app/samvera/hyrax-webapp

Application Trace | Framework Trace | Full Trace
/app/samvera/hyrax-engine/app/controllers/hyrax/file_sets_controller.rb:142:in `add_breadcrumb_for_action'
/app/samvera/hyrax-engine/app/controllers/concerns/hyrax/breadcrumbs.rb:29:in `trail_from_referer'
/app/samvera/hyrax-engine/app/controllers/concerns/hyrax/breadcrumbs.rb:8:in `build_breadcrumbs'

**Comment by no-reply** [comment]
i'm able to reproduce this *ONLY* if i use the `async` ActiveJob adapter. i'm digging in further, but in the meanwhile..

  - #4673 prevents the index state caused by the error from breaking views
  - i'm working on using a proper `ActiveJob` adapter for the development install.

**Comment by no-reply** [comment]
#4675 provides a realistic sidekiq setup. at least *sometimes* i can reproduce in this environment too.

i'm working on getting down to the root issue. a naive patch here will cause trouble for `FileSet` permissions
