### ISSUE TITLE
Dropdown menus not working in IE 11

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#4733]
### Descriptive summary

It appears that, among other things, dropdowns (e.g. the locale selector) broke somewhere between Hyrax 2.5.1 and more recent versions

### Expected behavior

On the Hyrax 2.5.1 version of the site, the locale expands, with the language options

### Actual behavior

After Hyrax 2.5.1 (2.9.0 and later) the dropdown menu does not expand

### Steps to reproduce the behavior

1. in internet explorer (e,g, version 11)
2. compare 2.5.1: http://demo.curationexperts.com/
to a later version (3.0.0.pre.rc3, though I’m seeing it in our 2.9.0 versions too) @  https://nurax-stable.curationexperts.com/
3. Click on a dropdown, eg the locale box

![Image 2021-01-21 at 9 52 18 AM](https://user-images.githubusercontent.com/3440166/105507390-1eb71a00-5c99-11eb-969d-e67415dbcf55.png)

**Comment by jcoyne** [comment]
@jlhardes I don't know much about this issue in particular, but please be aware that Microsoft itself has already dropped IE11 support for Teams in November 2020 and in the rest of Microsoft 365 will drop IE11 support in Aug 2021. https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

I'm not sure how long the community can effectively support IE11 if Microsoft itself won't.

**Comment by jlhardes** [comment]
Thank you, @jcoyne! So far we don't seem to be able to test for this easily (no one seems to have IE 11 or tools that support testing it) so if the Hyrax Maintenance WG is unable to do anything with this it might very well be abandoned as unfixable.

**Comment by jcoyne** [comment]
One option available aside from fixing for IE11 or doing nothing is to add a banner for IE11 users that says "IE11 is not supported..."

**Comment by crisr15** [comment]
Suggest adding documentation what browsers are supported.  Recommend not supporting IE as it is end of life.

**Comment by crisr15** [comment]
What browsers will be supported?

**Comment by jlhardes** [comment]
After [discussion with Hyrax Interest Group](https://samvera.atlassian.net/wiki/spaces/samvera/pages/921305103/Hyrax+Interest+Group+Call+2021-02-08), we are not supporting Internet Explorer in the Hyrax codebase so we will not be fixing this issue.
