### ISSUE TITLE
Upgrading to Hyrax 2.8: `uninitialized constant Hyrax::IndexesWorkflow::Solrizer`

### ISSUE THREAD

**Issue by travisLilleberg** [samvera/hyrax#4735]
### Descriptive summary
I'm updating our sites from Hyrax 2.5 to 2.9. Our tests pass just fine until I hit 2.8.0, at which point I start getting this error on every test:

```
NameError:
  uninitialized constant Hyrax::IndexesWorkflow::Solrizer
# /Users/tlille01/.rvm/gems/ruby-2.5.8@tufts-curation/gems/hyrax-2.9.3/app/indexers/hyrax/indexes_workflow.rb:3:in `<module:IndexesWorkflow>'
# /Users/tlille01/.rvm/gems/ruby-2.5.8@tufts-curation/gems/hyrax-2.9.3/app/indexers/hyrax/indexes_workflow.rb:2:in `<module:Hyrax>'
# /Users/tlille01/.rvm/gems/ruby-2.5.8@tufts-curation/gems/hyrax-2.9.3/app/indexers/hyrax/indexes_workflow.rb:1:in `<top (required)>'
# ./lib/tufts/curation/indexer.rb:6:in `require'
# ./lib/tufts/curation/indexer.rb:6:in `<top (required)>'
# ./lib/tufts/curation.rb:10:in `require'
# ./lib/tufts/curation.rb:10:in `<top (required)>'
# ./spec/spec_helper.rb:7:in `require'
# ./spec/spec_helper.rb:7:in `<top (required)>'
# ./spec/tufts/curation_spec.rb:3:in `require'
# ./spec/tufts/curation_spec.rb:3:in `<top (required)>'
```

### Rationale
Solrizer is being called in indexers/hyrax/indexes_workflow.rb, on lines 3, 6, 34, and 38. Since Hyrax itself is calling Solrizer, Hyrax should probably make sure it's loaded, as well.

### Notes
I have solved this by requiring solrizer in my own application, but I thought I'd mention the issue here. I'd be happy to create a PR that just adds `require 'solrizer'` to the top of the file, if that seems like a good fix. 

Thanks.

**Comment by cjcolvar** [comment]
This was an issue due to ActiveFedora dropping the dependency on solrizer and Hyrax not picking it up yet.  That happened in https://github.com/samvera/hyrax/pull/4330 which looks like only appears in v2.9.0.  It should be safe to jump straight to the latest Hyrax 2.x release (currently 2.9.3) and that should fix the issue for you.

**Comment by travisLilleberg** [comment]
Alright, thank you.
