### ISSUE TITLE
Some language views no longer working

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#4746]
### Descriptive summary

This is happening in current code (Hyrax 3.x, post rc3 tag) using the Docker build. Switching language on the home page from English to any of the following languages: Deutsch, Français, Italiano, Português do Brasil, or 中文 is resulting in a "translation missing" error message with regards to admin set thumbnails:

<img width="998" alt="Screen Shot 2021-02-10 at 4 17 04 PM" src="https://user-images.githubusercontent.com/3440166/107573353-6f94a100-6bbb-11eb-9ffe-8f45c2b2e249.png">

Likewise, trying to view a work (navigate to a Work page in English) and then change language results in a "translation missing" error message with regards to social media (Facebook sharing):

<img width="1001" alt="Screen Shot 2021-02-10 at 4 18 00 PM" src="https://user-images.githubusercontent.com/3440166/107573478-9357e700-6bbb-11eb-8c20-c5f8c834b0cb.png">

Neither of these issues are happening when switched to Español.

### Rationale

These are major error messages.

### Expected behavior

Expected behavior is that translations are available for all languages listed and work on the home page and all available views.

### Actual behavior

Actual behavior is that translations appear to be missing in certain places for almost all language options.

### Steps to reproduce the behavior

1. Change language on the home page to any choice other than Spanish
2. Reload the application in the browser (keep language as English)
3. View a work
4. Change the language to any choice other than Spanish

### Related work

Not clear if this is connected but this issue regarding language has seen recent work: Language Locale drops when Viewing depositor profile (#3356)

**Comment by no-reply** [comment]
maybe we need to run translations?

else, is `i18n` not working in docker?

**Comment by rjkati** [comment]
This has been fixed in Firefox 86.0.1 and Chrome 89.0.4389.90 on Windows. @jlhardes
