### ISSUE TITLE
Lease date field error when non-date text entered

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#4757]
### Descriptive summary

In Hyrax 3.x, entering non-date text in the Lease date field ("asdfas", for example) on a Work produces a stack trace error when saving the Work.

### Rationale

Stack trace errors shouldn't happen for this action.

### Expected behavior

Error message should show on Work form (like it does when doing this same action on Embargo) to indicate:

Visibility When setting visibility to "lease" you must also specify lease reduced access date.
Lease reduced access date Must be a future date.

Error checking applied to Embargo seems to not be applied to Lease.

### Actual behavior

See attached stack trace error screenshot

### Steps to reproduce the behavior

1. Login to nurax-dev
2. Create a new Work
3. Fill in required text fields (title, creator, rights statement)
4. Select Lease for Visibility
5. Enter "adfasdg" (or text that is not a date) in date field
6. Check box for deposit agreement
7. Click Save button

<img width="1012" alt="Screen Shot 2021-02-26 at 10 50 15 AM" src="https://user-images.githubusercontent.com/3440166/109324059-2e8ac680-7822-11eb-8595-6373b03f283d.png">

**Comment by rjkati** [comment]
In both firefox and chrome on windows, I'm unable to enter non-numeric characters into the Lease date field. @crisr15 can you duplicate this on a Mac?

**Comment by no-reply** [comment]
@rjkati @jlhardes i'm also confused and unable to reproduce. the field (i think) we're talking about is a date picker, which browsers are hopefully (mine is) restricting to date entries

**Comment by jlhardes** [comment]
Safari on Mac is not giving a date picker for Lease or Embargo date fields for me so maybe that is the problem here. I am able to completely remove the default value and enter any text but then that seems to produce the error screen. Chrome on Mac and Firefox on Mac are both showing the date picker. In those browsers, the only way I can enter a value is as a structured date.

**Comment by no-reply** [comment]
@jlhardes can we call this one a non-blocker for 3.0.0 then?

**Comment by jlhardes** [comment]
Yes, I think this is not a blocker for 3.0 but it is a priority for 3.x.

**Comment by jeremyf** [comment]
I will be debugging and testing with Safari.

**Comment by jlhardes** [comment]
It is no longer possible to enter non-date text on Safari for Lease or Embargo dates. This is fixed!
