### ISSUE TITLE
Lease date field error when past date entered

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#4758]
### Descriptive summary

In Hyrax 3.x, entering a date in the past in the Lease date field on a Work produces a stack trace error when saving the Work.

### Rationale

Stack trace errors shouldn't happen for this action.

### Expected behavior

Error message should show on Work form (like it does when doing this same action on Embargo) to indicate:

Lease reduced access date Must be a future date.

Error checking applied to Embargo seems to not be applied to Lease.

### Actual behavior

See attached stack trace error screenshot

### Steps to reproduce the behavior

1. Login to nurax-dev
2. Create a new Work
3. Fill in required text fields (title, creator, rights statement)
4. Select Lease for Visibility
5. Enter a date in the past in date field
6. Check box for deposit agreement
7. Click Save button

### Related work

Related to #3978 and #4757

<img width="1027" alt="Screen Shot 2021-02-26 at 10 51 16 AM" src="https://user-images.githubusercontent.com/3440166/109324844-3860f980-7823-11eb-8b64-9cea0cd11e6c.png">

**Comment by rjkati** [comment]
I receive the same error message on nurax-dev when entering a past Lease date.
![old_lease](https://user-images.githubusercontent.com/32644254/109340811-7d8f2680-7837-11eb-9b0f-080b8e6cc65f.PNG)

**Comment by crisr15** [comment]
![Uploading Action Controller_ Exception caught - nurax-dev.curationexperts.com.png…]()

**Comment by jlhardes** [comment]
Stack trace error is no longer occurring so this issue is being closed.
