### ISSUE TITLE
Create AccessControl solr docs in Valkyrie solr when creating works, collections, and adminsets

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4767]
### Descriptive summary

When writing to Valkyrie's solr is enabled and an object that has access controls (e.g. Works, Collections, AdminSets) is created, a Hydra::AccessControls and Hydra::AccessControls::Permission solr docs are written to ActiveFedora managed solr core but not to the Valkyrie solr core.

### Rationale

AccessControls are a core model type and should be saved in the Valkyrie solr core.

### Expected behavior

When `config.query_index_from_valkyrie = true` in `config/initializers/hyrax.rb` and a Work is created or edited...

* should write several access related solr docs to ActiveFedora managed solr core (at least for now)
* should write the same access related solr docs to Valkyrie's solr core 

### Actual behavior

When `config.query_index_from_valkyrie = true` in `config/initializers/hyrax.rb` and a Work is created or edited...

* writes access related solr docs to ActiveFedora managed solr core (at least for now)
* DOES NOT write access related solr docs to Valkyrie's solr core 

#### Prerequisites

Edit `.internal_test_app/config/initializers/hyrax.rb` and set config

```
  config.query_index_from_valkyrie = true
```

#### Get count of access related solr docs

Get counts through Solr UI for ActiveFedora Solr core:
1. navigate to: http://localhost:8983/solr/#/hydra-development/query
2. check facet and set `facet.field=has_model_ssim`
3. go to bottom of results and record counts for model types
    * Hydra::AccessControls
    * Hydra::AccessControls::Permission

Get model type counts in Solr UI for Valkyrie Solr core:
1. navigate to: http://localhost:8987/solr/#/hyrax-valkyrie-test/query
2. check facet and set `facet.field=has_model_ssim`
3. go to bottom of results and record counts for model types
    * Hydra::AccessControls
    * Hydra::AccessControls::Permission

#### Check for count changes when adding a work

BEFORE get counts of access related solr docs for both ActiveFedora Solr core and Valkyrie Solr core.

1. Login
2. Dashboard -> Works -> Add new work -> type=Generic Work
3. Fill in required fields and add a file
4. Save

AFTER get counts of access related solr docs for both ActiveFedora Solr core and Valkyrie Solr core.

Verify that the counts for access related solr docs increased by the same amount in both Solr cores.

### Related work

* Issue #4756 - UBER: Not all model types are saved to the Valkyrie Solr core 
* Issue #4765 - Create a solr doc in Valkyrie solr when creating/modifying an AdminSet
* Issue #4766 - Create a FileSet solr doc in Valkyrie solr when files are added to a Work

**Comment by no-reply** [comment]
i'm wondering whether these documents support any features other than `ActiveFedora`'s query DSL? do we want to write ACL and permissions documents to solr in valkyrie? i had assumed we wouldn't.

**Comment by elrayle** [comment]
Sounds like this isn't needed.  We can reopen later if we determine they are needed.  Closing for now.
