### ISSUE TITLE
Can recommended FITS version be updated to 1.2.0+?

### ISSUE THREAD

**Issue by kerchner** [samvera/hyrax#4815]
### Descriptive summary

The latest version of https://github.com/samvera/hyrax/blob/e21dc432b2a1cbdf6ce44f5494353fbb291ba9c5/documentation/developing-your-hyrax-based-app.md still recommends FITS version 1.0.5.  Although I personally have not tested it, based on this thread https://github.com/harvard-lts/fits/issues/140#issuecomment-413902198 it looks like the issue is fixed in FITS 1.2.0+

### Rationale

Deployments following the recommendations will be able to take advantage of improvements in FITS since 1.0.5.

**Comment by no-reply** [comment]
yes. even our own docker build installs 1.5.0.

could you submit a pull request?
