### ISSUE TITLE
Deactivating Leases displays validation error

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#4832]
### Descriptive summary

Attempting to deactivate expired leases from the Manage Leases section of the dashboard UI gives "Validation failed: embargo release date must be a future date" error

![record_invalid](https://user-images.githubusercontent.com/32644254/112518361-af7ca580-8d6f-11eb-984d-3adc54b62aed.PNG)

This has been replicated in iOS Safari and Chrome.
https://nurax-dev.curationexperts.com/leases?locale=en

### Steps to reproduce the behavior

As an admin user, navigate to Dashboard > Tasks > Manage Leases.

1. Click on "Expired Active Leases"
2. Select one or more expired leases to deactivate.
3. Click on "Deactivate Leases for Selected"
4. Observe error message

**Comment by no-reply** [comment]
thanks. i was able to reproduce this just now.

**Comment by rjkati** [comment]
I can't reproduce the error anymore on nurax-dev, so it seems like this issue is not a problem anymore. @jlhardes

**Comment by jlhardes** [comment]
Closing as resolved.
