### ISSUE TITLE
Depositing a work with past embargo gives no id error

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#4833]
### Descriptive summary

Depositing a work with an embargo date in the past gives an "No ID provided for ActiveFedora::Base" error.
![noID](https://user-images.githubusercontent.com/32644254/112519132-71cc4c80-8d70-11eb-9d59-4c21da6b8136.PNG)

https://nurax-dev.curationexperts.com/concern/generic_works?locale=en

### Expected behavior
Depositing a work with a past embargo should fail to be created and entered information should be preserved (per #3978 )

### Actual behavior
The user receives an error message.

### Steps to reproduce the behavior

1. Log in
2. Create a work
3. Set an embargo or lease date to before today
4. Press the save button

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment]
@jeremyf i wonder if you could take a look at this one? i noticed that the new `EditPermissionsService` is implicated.

**Comment by crisr15** [comment]
Tested in Nurax with a work that had a passed embargo date.  

received error: 
[FireShot Capture 009 - Action Controller_ Exception caught - nurax-dev.curationexperts.com.pdf](https://github.com/samvera/hyrax/files/6400394/FireShot.Capture.009.-.Action.Controller_.Exception.caught.-.nurax-dev.curationexperts.com.pdf)

**Comment by jeremyf** [comment]
Looking at Nurax as of 2021-04-29, the SHA is b034218b89dde7df534e32d1e5ade9161e129a1d.  And based on footer, Nurax tracks to the `master` branch, which we've since renamed to `main`.

Which has the following permission logic:

https://github.com/samvera/hyrax/blob/b034218b89dde7df534e32d1e5ade9161e129a1d/app/services/hyrax/edit_permissions_service.rb#L167-L181

My changes were from ab6c75616e3e87c0e9dfa3bb2ac483abada31edf

Which look as follows: https://github.com/samvera/hyrax/blob/ab6c75616e3e87c0e9dfa3bb2ac483abada31edf/app/services/hyrax/edit_permissions_service.rb#L169-L177

Below is the log, at the end of the log is the commit that Nurax is on.  At the beginning of the log are all of the commits that are in the `main` branch but are not deployed to Nurax.

```sh
*   ab6c75616 — Merge pull request #4885 from samvera/gh-4833-depositing-a-work-with-past-embargo-gives-no-id-error Daniel Pierce, (2021-04-26) (HEAD -> main, origin/main)
|\  
| * 35af65db1 — Refactoring to extract inner block logic Jeremy Friesen, (2021-04-24)
| * 22c888138 — Factoring from ActiveFedora::Base to query_service Jeremy Friesen, (2021-04-24)
| * d2ddfd793 — Renaming local variable for clarity Jeremy Friesen, (2021-04-24)
| * 657ef7c83 — Documenting spot to remove ActiveFedora::Base call Jeremy Friesen, (2021-04-23)
| * 696da5dbb — Removing redundant `.any?` check Jeremy Friesen, (2021-04-23)
| * c97c31fc6 — Compacting array building logic Jeremy Friesen, (2021-04-23)
| * 76c68fb1f — Renaming method to better reflect return value Jeremy Friesen, (2021-04-23)
* |   17e3da911 — Merge pull request #4891 from samvera/solr-configset Jeremy Friesen, (2021-04-26)
|\ \  
| * | 91201a0d2 — give useful output when the Solr ConfigSet can't upload with auth tamsin johnson, (2021-04-26)
|/ /  
* | 6f5af1efd — Make dassie sidekiq depend on services Daniel Pierce, (2021-04-22)
* | c18846c04 — Adding TROUBLESHOOTING section for CONTAINERS.md Jeremy Friesen, (2021-04-22)
* | e810cba17 — chart: readd support for kubernetes versions before 1.19 tamsin johnson, (2021-04-22)
|/  
* 52b2934c6 — allow the SolrCloud assign-configset utility to create collections tamsin johnson, (2021-04-21)
* b034218b8 — chart: populate secrets and env when Minio is used tamsin johnson, (2021-04-20)
```

**Comment by crisr15** [comment]
Nurax dev is not pulling from main.  Testing is on hold until new code is deployed.

**Comment by jlhardes** [comment]
I can verify this is working on a local hyrax app so once Nurax-dev is pulling from main again we can verify there and close this issue.

**Comment by jlhardes** [comment]
This is still giving an error on nurax-dev but it seems to be a different error than the original report: ActionController::UrlGenerationError in Hyrax::GenericWorks#create

See attached PDF file for full stack trace. 
[4833_Action Controller_ Exception caught.pdf](https://github.com/samvera/hyrax/files/6428169/4833_Action.Controller_.Exception.caught.pdf)

**Comment by jeremyf** [comment]
@jlhardes I believe the new error relates to #4889.  Based on the exception, it looks like you're running SHA ff0986b0f5e4 which does not include 840a08ff858c0cc23b8a83b69d0cadf0308ca3f2.

Below is the log of the `main` branch, at the top is the current "HEAD" of main.  At the bottom is the commit prior to SHA ff0986b0f5e4. Note that 840a08ff8 occurs later in the log.

```console
*   a8597884e — Merge pull request #4909 from samvera/gh-4900-edit-form-error-for-valkyrie Jeremy Friesen, (2021-05-04) (HEAD -> main, origin/main)
|\  
| * 01ecf2692 — Adding permision_populator to change set Jeremy Friesen, (2021-05-04)
|/  
* 9d51cb1fd — Adjusting lease/embargo_enforced helper logic Jeremy Friesen, (2021-05-04)
* 625a1a9eb — Adding rendering of lease related error messages Jeremy Friesen, (2021-05-04)
* 840a08ff8 — Fixing rendering logic for visibility component Jeremy Friesen, (2021-05-04)
* 7fe7786c6 — Ensuring non-parseable date bubbles up to UI Jeremy Friesen, (2021-05-04)
* ff0986b0f — Merge pull request #4908 from samvera/valkyrie-member-presenter Jeremy Friesen, (2021-05-04)
* 28f2086a6 — support full `MemberPresenterFactory` API in `PcdmMemberPresenterFactory` tamsin johnson, (2021-05-03)
* c08983cf5 — support member order in Valkyrie MemberPresenterFactory tamsin johnson, (2021-05-03)
* e78d3b24a — add a MemberPresenterFactory implementation that supports valkyrie tamsin johnson, (2021-05-03)
```

**Comment by jlhardes** [comment]
Tested again on nurax-dev now that it is fully updated with all changes for this fix and it works as expected (red alert message that date needs to be in the future and new work is not saved and edited work is not saved). This is done!
