### ISSUE TITLE
Setting lease with date in the past has error messaging problems

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#4845]
### Descriptive summary

Setting the Visibility of a Work with a Lease that has a date in the past does not work, which is correct. However, the error messaging that shows is not helpful and ends up leaving you somewhat stuck in the Work edit form.

### Rationale

If it does not work to set a lease date in the past (which is correct, it should not work that way), the other visibility options (Public, Embargo, Private) should still be available while the error message inside Lease shows that the date must be a future date. It should be possible to either correct the Lease date and then save to apply the lease or select another visibility option and continue editing the work.

### Expected behavior

If a Lease date is in the past, the lease is not applied and the other Visibility options are still available while the error message inside Lease shows that the date must be a future date. The flash error message at the top contains text to explain that the Lease date needs to be a date in the future (or the date value is not valid).

### Actual behavior

Empty flash error message appears at the top and the Visibility looks like a Lease has been applied (no other visibility options show) and there is an error message that the date must be a future date. User can either correct the date and continue applying the Lease or they have to exit the Work edit form (using menu options or something similar to abandon the edit form without saving) and come back into the Work edit form, where the visibility options are all available, set as they were before editing, and the invalid Lease has not been applied.

<img width="1098" alt="Screen Shot 2021-03-31 at 4 34 56 PM" src="https://user-images.githubusercontent.com/3440166/113210072-d3455d00-9241-11eb-807e-051d8ae45b97.png">

### Steps to reproduce the behavior

1. Edit a Work
2. Under Visibility, select Lease
3. Change the date on the lease to a date in the past
4. Save changes
5. See empty flash error message and no visibility options except for Lease (which has to have a corrected date to be applied).

**Comment by no-reply** [comment]
is this different from #4758

**Comment by jlhardes** [comment]
I think this might be an update on #4758. The behavior described in that issue is not occurring anymore. Safari on Mac doesn't provide a calendar picker so dates are entered manually. Entering a date in the past manually was producing a stack trace error but now is giving this empty flash error message along with the message with the date field that it must be a future date. The behavior described here is happening across all browsers now (also tried Chrome and Firefox, both of those have calendar pickers for this field). I can't track down what actually changed to address the stack trace error but it looks like #4758 can be closed.

**Comment by jeremyf** [comment]
Testing this requires #4833

**Comment by jeremyf** [comment]
Work log with #4833, when I add a lease date that is a past date, I get the following:

```
No route matches {:action=>"edit", :controller=>"hyrax/leases", :id=>Hyrax::Forms::FailedSubmissionFormWrapper(#<Hyrax::GenericWorkForm:0x00005566fc825858>), :locale=>:en}, possible unmatched constraints: [:id]
```

![Screen Shot 2021-04-26 at 10 12 51 AM](https://user-images.githubusercontent.com/2130/116097267-fc59e180-a677-11eb-8228-4c3a16b36341.png)

We are invoking `edit_lease_path(f.object)` when `f.object` is not persisted.  That indicates some switching logic is in play that echoes the observed problem of not rendering the full UI element for managing the visibility.

**Comment by jlhardes** [comment]
Testing this locally shows this is fixed when trying to use a past date in the Lease field on a new work or for editing an existing work. Nurax-dev is giving the above described response when editing an existing work and a stack trace error when using a past date in the Lease field on a new work. These changes do not seem to have made it to nurax-dev yet.

**Comment by jlhardes** [comment]
All changes have now made it to nurax-dev and this is fixed. A helpful error message appears that the Lease date must be in the future when editing a work or creating a new work and entering a Lease date that is in the past. This is done!
