### ISSUE TITLE
Use config to determine if valkyrie should be used.

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4895]
### Descriptive summary

Methods that have separate processing for ActiveFedora and Valkyrie commonly have a parameter named `use_valkryie` that defaults to `false`.  Instead of defaulting to false, default to the configuration ``.

### Rationale

Allow all methods capable of using valkyrie to be set to use it with one configuration change.

### Expected behavior

```
use_valkyrie: Hyrax.config.use_valkryie?
```

Locate methods to update by searching for `use_valkyrie: false`.

!!! CAUTION !!!  **DO NOT** change for any call to Hyrax.query_service!

### Actual behavior

```
use_valkyrie: false
```

**Comment by straleyb** [comment]
This ticket is done. All the places where valkyrie has been enabled with configuration are the right places where valkyrie works. The rest of the places are hardcoded for a reason. Those places are not ready to be moved over to configuration.
