### ISSUE TITLE
Edit form with Monograph (Valkyrie resource) fails to display all fields in the Descriptions tab

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4899]
### Descriptive summary

The Monograph is a Valkyrie resource.  When editing an existing Monograph work, all the fields shown in the new work form should also be shown in the edit work form.  But the edit work form only shows the Title field.

### Rationale

The edit form should behave the same for AF objects and Valkyrie resources.

### Expected behavior

The edit form should have the same fields as the new form on the Description tab.  The image below is the new form.

![image](https://user-images.githubusercontent.com/6855473/116749677-48d25380-a9cf-11eb-9ab3-3bae831ff7c6.png)

### Actual behavior

Only the Title field is displayed on the Descriptions tab.  The image is the actual edit form.

![image](https://user-images.githubusercontent.com/6855473/116749341-ccd80b80-a9ce-11eb-9444-3887a90e3c7c.png)

### Steps to reproduce the behavior

Prerequisite
1. Login
2. Click Share Work on Home page
3. Select Monograph as type of work
4. Fill in required fields and add file.
5. Save

Reproduce behavior
1. Navigate to Dashboard -> Works
2. Edit the work created in the prerequisites

Fails to display all fields.

### Related Work

Issue #4900 - Edit form error when setting Sharing permissions

**Comment by no-reply** [comment]
this might be fixed by #4947

**Comment by elrayle** [comment]
There have been changes to generators and it is possible that the Monograph on nurax-pg is slightly different than the Monograph on nurax-dev.  This will require more exploration, but I would start there before jumping deep into Hyrax code.

**Comment by elrayle** [comment]
Issue #5447 describes the problem when trying to edit a Monograph that causes the exception.  This is only an issue when Settings -> Features -> Batch Upload is ON.  When that is turned off, I can confirm that this issue is fixed.
