### ISSUE TITLE
Edit form error when setting Sharing permissions

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4900]
### Descriptive summary

Monograph work is a Valkyrie resource. When creating a Monograph work with Sharing permissions set, an error occurs when savings the new work.

### Rationale

The edit form should behave the same for AF objects and Valkyrie resources.

### Expected behavior

View and edit permissions can be set for groups and users on the Sharing tab.  When saving, the work saves with out error and grants the permissions set on the Sharing tab.

### Actual behavior

View and edit permissions can be set for groups and users on the Sharing tab.  When saving, an error occurs when attempting to grant permissions set on the Sharing tab.  The image shows error that occurred when saving.

![image](https://user-images.githubusercontent.com/6855473/116751246-bd0df680-a9d1-11eb-8bdd-0a542ae70c79.png)

#### Prerequisites

Edit the hyrax initializer in the test app (e.g. `.internal_test_app/config/initializers/hyrax.rb` or `.dassie/cofig/initializers/hyrax.rb`) and set config

```
  config.query_index_from_valkyrie = true
```

#### Steps
1. Login
2. Click Share Work on Home page
3. Select Monograph as type of work
4. Fill in required fields and add file.
5. On Shared tab, select a user (e.g. basic_user@example.com) and grant them edit permission.
6. Save

Error occurs as seen under Actual behavior.

### Related work

Issue #4901 - Indexing of Monograph (Valkyrie resource) into the Valkyrie solr core does not include permissions
Issue #4899 - Edit form with Monograph (Valkyrie resource) fails to display all fields in the Descriptions tab

**Comment by jeremyf** [comment]
I tested this against `main` at SHA 9d51cb1fd.  There were a few adjustments and I'm now testing against efee62e00 which was the state on 2021-04-30.

**Comment by jeremyf** [comment]
I'm looking at the Reform populators: https://trailblazer.to/2.1/docs/reform.html#reform-populators

**Comment by jeremyf** [comment]
I have a fix…but am struggling with creating a failing test at the correct level.
