### ISSUE TITLE
Embargoes #update method in embargoes_controller_behavior.rb needs to be able to work with Valkyrie 

### ISSUE THREAD

**Issue by straleyb** [samvera/hyrax#4911]
### Descriptive summary

EmbargoesControllerBehavior needs to be transitioned to work with Valkyrie. The configuration is on line 31 and is used by `Hyrax.custom_queries.find_many_by_alternate_ids` This method isn't just returning an af_object anymore. When the configuration is swapped to true for the custom queries, it can either return an af_object or valkyrie_object. The #update method in this behavior needs to know how to handle that properly.

# Current behavior
The #update method in the EmbargoesControllerBehavior doesn't handle valkyrie objects if `Hyrax.custom_queries.find_many_by_alternate_ids` is swapped to `use_valkyrie: true`. If the tests are run for this method, they fail due to not supporting the valkyrie object returned by the query.

# Expected behaior
The #update method in the EmbargoesControllerBehavior handles both the af_object and valkyrie_object when `use_valkyrie: true` is set. Once this is done, then we can swap that to use the actual configuration `Hyrax.config.use_valkyrie`

**Comment by elrayle** [comment]
Fixed by #4934.  Confirmed by @straleyb in Slack #developer-congress channel on 2021-07-13 14:48ET.
