### ISSUE TITLE
Duplicate IIIF and Universal Viewer Code

### ISSUE THREAD

**Issue by lfarrell** [samvera/hyrax#4954]
### Descriptive summary

I'm not sure if this is a bug exactly, but it appears that work_show_presenter.rb, manifest_metadata method, https://github.com/samvera/hyrax/blob/v2.9.5/app/presenters/hyrax/work_show_presenter.rb#L216, is no longer used. It looks like it has been replaced by https://github.com/samvera/hyrax/blob/v2.9.5/app/presenters/hyrax/iiif_manifest_presenter.rb#L70. I'm wondering if the IIIF code in the work_show_presenter should be removed as it appears to be dead code.

**Comment by no-reply** [comment]
both the `WorkShowPresenter` and the `IiifManifestPresenter` are supported as `WorksControllerBehavior#iiif_manifest_presenter` types.

the history here is that there was a complete rewrite of the manifest generation last fall. the introduction of `IiifManifestPresenter` was a key part of that rewrite, but the existing behavior is retained. applications have the option to switch back to `WorkShowPresenter` to provide manifest generation (e.g. by overriding `iiif_manifest_presenter` on the controllers).

at this point, `IiifManifestPresenter` has been around for a couple of releases and i think the `WorkShowPresenter` behavior is safely considered legacy, but i haven't seen any reason to deprecate it yet.

**Comment by lfarrell** [comment]
Okay, thanks for the update. We'd overridden the WorkShowPresenter manifest_metadata method locally, which was causing some issues when upgrading from 2.6.0 to 2.9.5 as it isn't called by default anymore,but we got them worked out. I'll go ahead and close the ticket.

**Comment by no-reply** [comment]
ah, that's good to know. normally we try to avoid this kind of impact on a minor version bump. in this case, the benefit of the new behavior is high enough that it seemed wise to make it the default, even though it could be breaking in cases like yours.

glad you were able to sort it out.
