### ISSUE TITLE
Display alternative titles in item view

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5015]
### Descriptive summary

Alternative titles can be added to an item (work or collection) and are mapped to http://purl.org/dc/terms/alternative but are not showing in the item view.

### Rationale

If alternative titles can be added to the metadata for a work or collection then they should also show to end users.

### Expected behavior

Alternative Title is a field that displays in the item view for both works and collections.

### Actual behavior

Alternative titles can be added and edited in the work edit form or collection edit form but do not display in the view of those works and collections. 

Example: https://nurax-dev.curationexperts.com/concern/images/1r66j142g - "Cat" is title; "Alt Cat" and "Alt Kitty" are 2 alternative titles which do not show in view

### Steps to reproduce the behavior

1. Log in (as either admin or regular logged in user)
2. Create a work or a collection with required metadata
3. Add Alternative title entries and save
4. View work or collection

### Related work

#4286 is work completed to add alternative title as a metadata field in the edit form.

**Comment by jlhardes** [comment]
Testing on Hyrax 4 beta 2 on nurax-dev and locally shows this field is still not displaying, although data is being saved.

**Comment by rjkati** [comment]
Values for the alternative title field are now displaying on nurax-dev (Hyrax 4.0.0.beta)

![alternative title](https://user-images.githubusercontent.com/32644254/221257375-ea5c83c2-c58e-42d6-831b-9e4993db5218.PNG)
