### ISSUE TITLE
Samvera Logo does not display correctly on README

### ISSUE THREAD

**Issue by mark-dce** [samvera/hyrax#5066]
### Descriptive summary

On the main Hyrax README (in `main`) the samvera logo does not display correctly - see the section under https://github.com/samvera/hyrax/blob/main/README.md#acknowledgments

It appears this is because the image being linked to at https://wiki.lyrasis.org/download/thumbnails/87459292/samvera-fall-font2-200w.png?version=1&modificationDate=1498550535816&api=v2 is password protected on the lyrasis wiki.

### Actual behavior
![image](https://user-images.githubusercontent.com/3064318/129222325-611c6895-b5f4-49f5-b0ae-9196f26bba22.png)

### Steps to reproduce the behavior

1. Open a new incognito or private browser window
2. Visit https://github.com/samvera/hyrax/blob/main/README.md#acknowledgments

## Suggested solution
* Link to a public access copy of the logo - e.g. https://samvera.org/wp-content/uploads/2017/06/samvera-logo-tm.svg
* OR Include a copy of the Samvera logo in the Hyrax repo and link to the copy in the repo

**Comment by eporter23** [comment]
Closing as this appears to be resolved now: 
<img width="1085" alt="Screen Shot 2023-01-27 at 9 52 32 AM" src="https://user-images.githubusercontent.com/13855987/215116013-fdd13d2d-3d3a-4e6f-bf5d-9a6e0cce47cc.png">
