### ISSUE TITLE
Add compatibility with Blacklight 7

### ISSUE THREAD

**Issue by anusharanganathan** [samvera/hyrax#5075]
### Descriptive summary
When viewing the list of works in a dashboard, the logs are filled with the following deprecation warning 

```
DEPRECATION WARNING: You provided a String value to IndexPresenter#field_value Provide a Blacklight::Configuration::Field instead. This behavior is deprecated in Blacklight 7. (called from block in __usr_local_bundle_gems_hyrax_______app_views_catalog__index_list_default_html_erb__4462691090849688107_47379448317800 at /usr/local/bundle/gems/hyrax-2.9.5/app/views/catalog/_index_list_default.html.erb:8)
```

### Rationale

It will prevent future upgrades of blacklight.

### Expected behavior

Deprecation warnings are addressed.

### Actual behavior

The logs are filled with the deprecation warning message, making it difficult to track errors.

### Steps to reproduce the behavior

1. Login to Hyrax 2.9.5
2. Visit your dashboard, where there is a list of works.
3. Check the log file.

### Related work

Hyrax 2.9.5 is missing commit https://github.com/samvera/hyrax/commit/4a476aabf967e634ba54269794afb62982a129c0 which is a fix for this issue. (It was available in an earlier version).

**Comment by no-reply** [comment]
@anusharanganathan thanks for this report!

the warnings you point to are raised by Blacklight. Hyrax 2.x won't add support for any new blacklight versions, so it's unlikely that these will be resolved in that release series (though i'd be happy to review/merge/release any contributions that move this forward.).

you might want to consider configuring the `Deprecation` gem to silence these warnings. https://github.com/cbeer/deprecation#reporting

**Comment by no-reply** [comment]
i'm rescoping this to blacklight 7 support, since i'm not sure we have a tracking ticket for that yet.

**Comment by anusharanganathan** [comment]
> @anusharanganathan thanks for this report!
> 
> the warnings you point to are raised by Blacklight. Hyrax 2.x won't add support for any new blacklight versions, so it's unlikely that these will be resolved in that release series (though i'd be happy to review/merge/release any contributions that move this forward.).
> 
> you might want to consider configuring the `Deprecation` gem to silence these warnings. https://github.com/cbeer/deprecation#reporting

Thank you @no-reply. Given the clarification, we've decided not to worry about this deprecation warning. Also thanks for the tip regarding configuring the Deprecation gem

**Comment by marrus-sh** [comment]
I’m going to put future work on this in #3271 and close this issue.
