### ISSUE TITLE
undefined method `state=` when creating Monograph

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5084]
### Descriptive summary

When creating a Monograph through the UI, an exception is raised.

```
NoMethodError at /concern/monographs
undefined method `state='
```

The same error does not occur for GenericWork.

### Expected behavior

When required data is entered in new work form, a Monograph will be created.

### Actual behavior

When required data is entered in new work form, an exception is thrown.

```
NoMethodError at /concern/monographs
undefined method `state='
```

### Steps to reproduce the behavior

1. login
2. navigate to Dashboard -> Works
3. click Add new work
4. select Monograph for the work type
5. fill in required descriptive metadata, add a file, check depositor agreement
6. save

During save, the exception is raised.

**Comment by elrayle** [comment]
When the error occurs...

```
>> target.model_name
=> #<Hyrax::Name:0x00007fbb0fb79a40 @name="FileSet", @klass=#<Class:0x00007fbb8a679ba0>, @singular="file_set", @plural="file_sets", @element="file_set", @human="File set", @collection="file_sets", @param_key="file_set", @i18n_key=:file_set, @route_key="hyrax_file_sets", @singular_route_key="hyrax_file_set">
```

**Comment by rjkati** [comment]
@jlhardes I'm not able to reproduce this on nurax-dev, but I'm not sure if nurax-dev has the proper set up. On nurax-dev, I am able to successfully create a work using the "image" and "generic work" worktypes, but "monograph" is not a work type selection option.

On nurax-pg, I get a "NameError in Hyrax::GenericWorksController#new" error when I try to create either an "image" or "generic work". Monograph is also not a work type selection option on nurax-pg. More info on the error at: https://github.com/samvera/hyrax/issues/5134#issuecomment-957879887

**Comment by jlhardes** [comment]
Thanks @rjkati! This might not be specific to Monograph as a work type but more about Valkyrie work to test. @elrayle mentioned on Slack: "The reference to Monograph [in issue reports] is a legacy of the test app in Hyrax that defines some work types as ActiveFedora based and some (including the Monograph) as a Valkyrie resource.  In nurax-pg, all work types are Valkyrie resources." 

So if you can create works (image or generic work) on nurax-dev then we don't have any issue with the ActiveFedora based code. It looks like this might be more of a Val:MVP issue for testing on nurax-pg?

**Comment by rjkati** [comment]
I tested this on my local docker build (running hyrax 3.0.2) and was able to successfully deposit a monograph without getting the exception error listed above.

**Comment by rjkati** [comment]
In Hyrax Working Group standup, we decided to verify that this works on nurax-dev once the latest hyrax build has been deployed.

**Comment by MPLSFedResearchTZ** [comment]
Tried creating works and collections, found the following issue:
1. When saving the new created collection, there was no response, e.g. message appearing, page redirecting.
2. After saving the new created work, attached files were not displayed.

Otherwise, did not see any problem.

**Comment by jlhardes** [comment]
I do not see a Monograph work type on nurax-dev, I am still only seeing Generic Work and Image as the types of works that can be created. @MPLSFedResearchTZ were you testing on nurax-dev and able to create a Monograph work? It looks like we might not have Monograph generated as a work type to use yet on nurax-dev, @elrayle?

**Comment by MPLSFedResearchTZ** [comment]
@jlhardes  I don't see Monograph as a type either. When I tested on nurax-dev, after I created an image type, added a file, the work display page said there were associated files but when I opened the work from the work display page, I could see the image file was at the bottom of the page.

![image](https://user-images.githubusercontent.com/93392603/141132959-270ebf13-6a6c-4232-aa7a-9a5fca3cc16b.png)


![image](https://user-images.githubusercontent.com/93392603/141132651-cb777f8b-4ca2-4497-b4b3-9a61b7ef7045.png)

**Comment by jlhardes** [comment]
Testing on nurax-dev shows a NoMethodError in Hyrax::Monographs#new when selecting Monograph to create a new work, so I'm not able to get beyond step 4 in the steps to reproduce the behavior above. See attached full stack trace:

[nurax-dev_stackTraceError_2021-12-06.pdf](https://github.com/samvera/hyrax/files/7662856/nurax-dev_stackTraceError_2021-12-06.pdf)

**Comment by jlhardes** [comment]
Testing locally with a Docker build running the internal test app .dassie, I am able to create a work as a Monograph with no errors.

**Comment by conorom** [comment]
I was thinking of looking at this but in our working group stand up just now @fritzfreiheit said he could not recreate it and @elrayle says that is likely because this is fixed already (somewhere else) and so will not happen in dev anymore.

However @elrayle also reckons there may be a problem with how Monographs were created in `nurax-pg`, so the problem may still happen there. I'll leave this open for another while but there may not be anything to do here.

**Comment by elrayle** [comment]
In attempting to confirm this is fixed, I tried creating a monograph on nurax-dev.  It failed to create, but the error is related to batch processing which is behind a flipper config.  When I turned batch upload off, I can confirm that this issue is fixed.

See Issue #5447 for the batch upload related error for Monograph.
