### ISSUE TITLE
undefined method `representative_id` trying to edit a Monograph

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5127]
### Descriptive summary

Error `undefined method `representative_id` trying to edit a Monograph` when trying to edit an existing Monograph work.

### Steps to reproduce the behavior

1. create a Monograph with required steps and save
2. edit the saved Monograph

Gets error `undefined method `representative_id' for #<MonographForm:0x00007fd8610d2398>` occurring in file `app/views/hyrax/base/_form_representative.html_erb` at line... 

```
          <%= f.select :representative_id, form_file_set_select_for(parent: @form), {}, { class: 'form-control' } %>
```

### Related Work

Issue #5135 - Val MVP: Edit works as a valkyrie resource through UI

**Comment by rjkati** [comment]
Works can be edited on nurax-pg in Hyrax 3.4.1

**Comment by jlhardes** [comment]
Closing this issue since error not occurring now when editing a work.
