### ISSUE TITLE
Val MVP: Edit AdministrativeSet as a valkyrie resource through UI

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5131]
### Descriptive summary

As part of the Valkyrization MVP, a user should be able to edit an admin set through the UI with the underlying code processing the admin set as a `Hyrax::AdministrativeSet`.

### Rationale

Part of the basic Valkyrization MVP for testing the progress of the valkyrization effort.

### Steps to reproduce the behavior

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Collections](https://nurax-pg.curationexperts.com/dashboard/my/collections?locale=en)
2. Right Click the action menu beside an existing admin set
2. Select Edit Collection
3. Modify the title
4. Save

The admin set should be updated and listed in Dashboard -> Collections with the updated title.

### Related work

See all work tagged with Milestone [Valkyrization MVP](https://github.com/samvera/hyrax/milestone/19)

**Comment by MPLSFedResearchTZ** [comment]
Got error after clicking Edit Collection:

![image](https://user-images.githubusercontent.com/93392603/141175026-0419c39b-2aec-45c5-9822-19070742f386.png)

**Comment by rjkati** [comment]
This seems like it is blocked by #5130. There are no admin sets displaying in the "Collections" page, because it is not possible to create a new admin set without encountering an error message. Therefore there aren't any admin sets that can be edited to test this ticket.

**Comment by rjkati** [comment]
Admin sets can be edited on nurax-pg in Hyrax 3.4.1

**Comment by jlhardes** [comment]
Closing this issue since admin sets are now editable.
