### ISSUE TITLE
Val MVP: Create PcdmCollection as a valkyrie resource through UI

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5132]
### Descriptive summary

As part of the Valkyrization MVP, a user should be able to create a collection through the UI with the underlying code processing the collection as a `Hyrax::PcdmCollection`.

### Rationale

Part of the basic Valkyrization MVP for testing the progress of the valkyrization effort.

### Steps to reproduce the behavior

_**Prerequisite**:  Assumes that collection type User Collection exists._

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Collections](https://nurax-pg.curationexperts.com/dashboard/my/collections?locale=en) -> New Collection
2. Select User Collection
2. Fill in required metadata
3. Save

The collection should be created and listed in the Dashboard -> Collections -> Your Collections.  Viewing the collection's show page should display with the correct metadata.

_NOTE: If you aren't an admin, there won't be All Collections and Your Collections tabs.  You will just see the list of collections and it should include the new collection._

### Related work

See all work tagged with Milestone [Valkyrization MVP](https://github.com/samvera/hyrax/milestone/19)

**Comment by MPLSFedResearchTZ** [comment]
No confirmation after clicking save in creating a new collection, but actually the collection has been added to the db.

**Comment by MPLSFedResearchTZ** [comment]
Got this error when editing an existing collection:
![image](https://user-images.githubusercontent.com/93392603/140778482-d63bb704-4860-42e8-a38d-e39c903ebda4.png)

**Comment by rjkati** [comment]
When I create a new collection and click "save" the "save" button becomes grayed out and I do not see a confirmation message. When I click on the "Collections" tab in the dashboard, I can see the new collection. As a user, I expect nurax-pg to confirm that the collection has been created successfully.

**Comment by rjkati** [comment]
Collections can be created on nurax-pg in hyrax 3.4.1

**Comment by jlhardes** [comment]
Closing this issue since collections can be created.
