### ISSUE TITLE
Val MVP: Edit PcdmCollection as a valkyrie resource through UI

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5133]
### Descriptive summary

As part of the Valkyrization MVP, a user should be able to edit a collection through the UI with the underlying code processing the collection set as a `Hyrax::PcdmCollection`.

### Rationale

Part of the basic Valkyrization MVP for testing the progress of the valkyrization effort.

### Steps to reproduce the behavior

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Collections](https://nurax-pg.curationexperts.com/dashboard/my/collections?locale=en)
2. Right Click the action menu beside an existing collection
2. Select Edit Collection
3. Modify the title
4. Save

The collection should be updated and listed in Dashboard -> Collections with the updated title.

### Related work

See all work tagged with Milestone [Valkyrization MVP](https://github.com/samvera/hyrax/milestone/19)

**Comment by rjkati** [comment]
Error message as described in #5132 is still present

**Comment by rjkati** [comment]
Collections can be edited on nurax-pg in Hyrax 3.4.1

**Comment by jlhardes** [comment]
Closing this issue since collections can be edited.
