### ISSUE TITLE
Val MVP: Create works as a valkyrie resource through UI

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5134]
### Descriptive summary

As part of the Valkyrization MVP, a user should be able to create a work through the UI with the underlying code processing the work as a `Hyrax::Work`.

### Rationale

Part of the basic Valkyrization MVP for testing the progress of the valkyrization effort.

### Steps to reproduce the behavior

Once controller, forms, etc. are updated to work with a `Hyrax::Work` instead of an `ActiveFedora::Base` object, the following should continue to work.

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Works](https://nurax-pg.curationexperts.com/dashboard/my/works?locale=en) -> Add new work
2. Select any Work Type  (They are all Valkyrie Resources on nurax-pg.)
2. Fill in required steps
3. Save

The work should be created and the show page should display with the correct metadata filled in.  The work should be listed in Dashboard -> Works.

### Related work

See all work tagged with Milestone [Valkyrization MVP](https://github.com/samvera/hyrax/milestone/19)

**Comment by elrayle** [comment]
@rjkati It is great to have the steps to reproduce.  If you include a screenshot, that is even better.  That way I know for sure that I am seeing the same error you saw.

**Comment by rjkati** [comment]
@elrayle Well now that I said that, I'm getting a generic error screen at https://nurax-pg.curationexperts.com/concern/generic_works/new?locale=en
![nurax-pg_create_work](https://user-images.githubusercontent.com/32644254/140162526-fabe96fb-9a3e-4b3f-a66a-093be8719672.PNG)

This screen appears in both firefox and chrome. I used both an admin and non-admin account

**Comment by rjkati** [comment]
I am now able to successfully ingest a work on nurax-pg. The work show page displays and the work appears in the dashboard works list. The file is not attached to the work, see https://github.com/samvera-labs/nurax-pg/issues/29

**Comment by rjkati** [comment]
@jlhardes, seems like this issue can be closed?

**Comment by jlhardes** [comment]
There are other steps related to filesets and files attaching to the work that are still unfinished but this part of creating a work is complete. Closing this issue.
