### ISSUE TITLE
Val MVP: Create Hyrax::FileSet as a valkyrie resource through UI

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5136]
### Descriptive summary

As part of the Valkyrization MVP, a user should be able to add a file to a work through the UI with the underlying code processing the file metadata as a `Hyrax::FileSet`.

### Rationale

Part of the basic Valkyrization MVP for testing the progress of the valkyrization effort.

### Steps to reproduce the behavior

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Works](https://nurax-pg.curationexperts.com/dashboard/my/works?locale=en) -> Add new work
2. Select any Work Type  (They are all Valkyrie Resources on nurax-pg.)
2. Fill in required metadata
3. Add a file
3. Save

The work should be created, the file should be added, and the show page for the work should include the file in the list of files.  Clicking the title of the file should display the file set page with file metadata.

### Related work

See all work tagged with Milestone [Valkyrization MVP](https://github.com/samvera/hyrax/milestone/19)

**Comment by MPLSFedResearchTZ** [comment]
The file was not attached to the newly created work and I had to edit the existing work to attach a file.

**Comment by rjkati** [comment]
When testing on nurax-pg, the work is created, but the file does not appear in the file list on the work show page.

Example: https://nurax-pg.curationexperts.com/concern/generic_works/84b2019f-5a84-4e7e-b2f7-3c75b7e63a1a?locale=en

**Comment by rjkati** [comment]
File sets now appear in the Items list, but cannot be downloaded. When I click on the fileset URL, I get a "You are not authorized to access this page" message. 

Example work: https://nurax-pg.curationexperts.com/concern/images/5c2c56d1-7bf8-4299-b97f-237f8e9c989b?locale=en
![file_sets](https://user-images.githubusercontent.com/32644254/155017906-7f181b30-4901-4e79-a0cd-81eeb091fb5d.PNG)

**Comment by rjkati** [comment]
Retested and download links now display on the work show page. However, thumbnails and the image viewer do not load.

Also, when I click on the "Download image" link, I get a "ActiveFedora::ObjectNotFoundError in Hyrax::DownloadsController#show" error message.

I am still unable to download files as described in https://github.com/samvera/hyrax/issues/5136#issuecomment-1047183433

![downloadImage](https://user-images.githubusercontent.com/32644254/159345156-4c7d3829-cb2e-4f6a-9b60-82a052849623.PNG)

![hyraxdownloadscontroller](https://user-images.githubusercontent.com/32644254/159345179-570c8ef1-020a-414a-959a-92b2fddf92fa.PNG)

**Comment by jlhardes** [comment]
Closing this epic issue to focus on the smaller issues that remain to complete the FileSet work.
