### ISSUE TITLE
Val MVP: Store files through valkyrie storage_adapter through UI

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5138]
### Descriptive summary

As part of the Valkyrization MVP, a user should be able to create add a file to a work through the UI with the underlying code processing the file using a valkyrie storage_adapter.

### Rationale

Part of the basic Valkyrization MVP for testing the progress of the valkyrization effort.

### Steps to reproduce the behavior

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Works](https://nurax-pg.curationexperts.com/dashboard/my/works?locale=en) -> Add new work
2. Select any Work Type  (They are all Valkyrie Resources on nurax-pg.)
2. Fill in required metadata
3. Add a file
3. Save

The work should be created, the file should be added, and the show page for the work should include the file in the list of files.  Clicking the Actions selector beside the file and selecting Download should download the file to your computer.

### Related work

See all work tagged with Milestone [Valkyrization MVP](https://github.com/samvera/hyrax/milestone/19)

**Comment by rjkati** [comment]
I am able to complete the deposit process using the steps described above. The work is created, but the file is not shown in the list of files.

https://nurax-pg.curationexperts.com/concern/generic_works/61e7abd7-e867-468d-9cf9-4dc90ded23f5?locale=en (need admin access to view)

**Comment by MPLSFedResearchTZ** [comment]
I could not see the attached file either. Another thing is, should we display the list of files when user clicks the work to see the work details?

**Comment by rjkati** [comment]
This issue is still present on nurax-pg. I am able to complete the deposit process, but the file is not displayed in the items list on the work show page and cannot be downloaded.

Example: https://nurax-pg.curationexperts.com/concern/generic_works/83244e10-f1e6-4f8f-ae32-957ecbac3365?locale=en

**Comment by jlhardes** [comment]
Closing this epic issue to focus on smaller issue to complete within adding a file to a work and getting it to store correctly.
