### ISSUE TITLE
non-wings adapter cannot edit collections and works

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5244]
### Descriptive summary

When using the postgres adapter in nurax-pg, works and collections get the same `Valkyrie::Persistence::ObjectNotFoundError` when you try to edit an existing work or collection.  This is caused by the `alternate_ids` not getting set when the work/collection is created.  The edit process expects to be able to read the work/collection back in by searching for postgres for an alternate identifier equal to the id.

### Rationale

Editing should work for wings adapter and non-wings adapters.

### Expected behavior

Dashboard -> Works -> edit work -> should display the work edit form

### Actual behavior

Dashboard -> Works -> edit work -> raises `Valkyrie::Persistence::ObjectNotFoundError` in the `query_service #find_by_alternate_identifier` method.

![image](https://user-images.githubusercontent.com/6855473/140390167-88dc65cd-5cca-49cf-98fe-51f3d016cf76.png)

### Steps to reproduce the behavior

Prereq:  Create a valkyrie resource type work.  On nurax-pg, all work types are valkyrie resource work types.

1. Login to [nurax-pg](https://nurax-pg.curationexperts.com)
1. Dashboard -> [Works](https://nurax-pg.curationexperts.com/dashboard/my/works?locale=en)
2. Click the action menu beside an existing work
2. Select Edit Work
3. Modify the title
4. Save

### Related work

Issue #5135 - Val MVP: Edit works as a valkyrie resource through UI

**Comment by no-reply** [comment]
this is a nurax-pg configuration issue, and we should track it over there.
