### ISSUE TITLE
create default admin set for non-wings adapters

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5261]
### Descriptive summary

There needs to be a process for generating the default admin set and remembering it.  Historically this was done by assigning `"DEFAULT_ADMIN_SET"` as the `id` of the admin set.  But other adapters, like postgres, do not allow directly setting of `id`.

### Rejected approaches

Several approaches have been tried:
* set ID to predetermined value (current approach) - doesn't work for some adapters (e.g. postgres)
* set alternate_ids to be the predetermined value - doesn't work when NOIDs are turned on because they are saved in as the alternate id
* set title to be a predetermined value - doesn't work because query by title isn't supported

### Proposed approach

Allow the adapter to save the admin set and then store the generated ID in permanent storage.

Basic functioning of this approach:
* first admin set created will be assigned as the default
* store id of default permanently-- where? perhaps in database
* read default from from permanent store and cache in Hyrax.config.default_admin_set_id
* set default using Hyrax.config.default_admin_set_id= and update permanent store
* change which admin set is default (any admin set can be the default) - via UI?  

### Alternate simplified approach
* create an admin set
* edit `configs/initializers/hyrax.rb` and set `default_admin_set_id`
* restart app
* Hyrax.config.default_admin_set_id will be read from hyrax initializer

**Comment by apertome** [comment]
@elrayle "set default using Hyrax.config.default_admin_set_id= and update permanent store" -  how do we accomplish storing it permanently?

**Comment by elrayle** [comment]
There are two open questions for the full proposed approach:
* where to permanently store the default admin set id
* where in the UI is the best place to set an admin set as the default

The first could be saved to the database.

With these two open questions, I lean toward the Alternate simplified approach which does not prevent expanding later to be able to set it in the UI.
