### ISSUE TITLE
Homepage tabs

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#5337]
### Descriptive summary

Bootstrap 4 upgrade branch.

Tabs UI / styling needs ironing out.

### Rationale

Should look as Bootstrap 4 tabs are supposed to

### Expected behavior

Something similar to this:

![image](https://user-images.githubusercontent.com/3020266/150839013-998948f6-ccec-45ce-a144-c22b9c46832c.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/3020266/150839071-995cc045-05a8-48f2-ae12-14fd005e33ba.png)

**Comment by adamjarling** [comment]
@mathewjordan Assume this is getting fixed via your Tabs sweep?

**Comment by mathewjordan** [comment]
Yes addressed in https://github.com/samvera/hyrax/pull/5365/commits/7db3c693ad8c00ab472c08d26dca5917f8fba77b
