### ISSUE TITLE
Bootstrap 4: Default font-size has shifted

### ISSUE THREAD

**Issue by mathewjordan** [samvera/hyrax#5340]
### Descriptive summary

Default font-size has shifted from `14px` in Bootstrap 3 to `1rem` (computed by modern browsers as `16px`). This change gives greater control over font-size globally but may impact installs of Hyrax. 

### Rationale

To avoid cosmetic issues, we may want to set a fixed font-size of `0.875em` computed as 14px (the previous default for bootstrap 3)

### Expected behavior

Should we reset the computation of the default font-size for the Hyrax front-end to be `0.875em` in the `<html>` element? All bootstrap elements would still calculate at 1rem, but that rem would be computed as 14px.

Alternatively, it may be okay to ignore this and let everything inflate. This might be the most forward facing solution but could lead to issues for anyone who has set `px` based font-sizing in a custom way.

### Actual behavior
Bootstrap 4 will inflate everything from a default of 14px to 16px (1rem)

**Comment by adamjarling** [comment]
We might just run with `1rem`, and document the decision and allow others to customize to taste.

**Comment by marrus-sh** [comment]
Closing this thanks to #5366, which I think is good enough for now.
