### ISSUE TITLE
`blacklight-gallery` has JS errors in Blacklight 7

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#5343]
### Descriptive summary

There are some uncaught JS errors on the Work page.

### Expected behavior

No browser console errors

### Actual behavior

![image](https://user-images.githubusercontent.com/3020266/150850960-9f23c1cf-8f3d-4a71-b7ed-a3a9c73a5f13.png)

### Steps to reproduce the behavior

1. Load the app, and open up the browser console and notice the errors.

**Comment by marrus-sh** [comment]
I believe the `_gaq` error also shows up on `main` (or used to, at least). But if `$(...).slideshow` works on `main` but not on `bl7bootstrap4` then that might be something we need to fix.

**Comment by adamjarling** [comment]
Not sure, but wonder if these errors are blocking a lot of javascript from running in the app. Will investigate and take a chance.

**Comment by mathewjordan** [comment]
> Not sure, but wonder if these errors are blocking a lot of javascript from running in the app. Will investigate and take a chance.

Was wondering the same.

**Comment by adamjarling** [comment]
@marrus-sh Looks like the `$(...).slideshow` error is coming from `blacklight_gallery`

![image](https://user-images.githubusercontent.com/3020266/151231371-1ee33ec2-3aab-48ee-a6f6-4b240c7ce8a6.png)

Which is getting pulled in via Dassie:  `/.dassie/app/assets/javascripts/blacklight_gallery.js`

So maybe it's not getting pulled in successfully?  I don't really know what compiles these files, or best way to trace this out?

**Comment by marrus-sh** [comment]
i’ll try to take a look. if we don’t get to all of the JS issues this dev congress that’s fine with me; i think if we can get a frontend which is well-put-together on the HTML and CSS side then scripting issues should be relatively feasible to pick up later.

**Comment by adamjarling** [comment]
Update, I can remove references to these files, but it doesn't make other items in the app (like a modal opening / closing) magically work.

**Comment by adamjarling** [comment]
This seems to no longer be an issue on the current branch.

**Comment by jlhardes** [comment]
I don't see any JS errors on the Work page either when viewing a work or editing a work so I am closing this issue.
