### ISSUE TITLE
Can't add a new Work

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#5345]
### Descriptive summary

The Add new work button doesn't pop up a modal

### Expected behavior

![image](https://user-images.githubusercontent.com/3020266/150853956-8c5fd021-cda6-4656-bfcb-08592728ff09.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/3020266/150854100-4238a9b6-1629-4ddc-852b-cd3ed3721f7e.png)

### Steps to reproduce the behavior

1. Go to the work page in Dashboard
2. Click Add new work button

**Comment by jlhardes** [comment]
This is working now in the `bl7bootstrap4` branch.
