### ISSUE TITLE
Collection page cleanup

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#5348]
### Descriptive summary

General clean up on the Collection page

### Actual behavior

![image](https://user-images.githubusercontent.com/3020266/150856244-a650281a-0a6c-4c2b-a8e2-e046c368c5ba.png)

### Steps to reproduce the behavior

1. Do this
2. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by jlhardes** [comment]
Search bar formatting and Show count dropdown are cleaned up on `bl7bootstrap4` branch. Collection Type filter is showing options but the following is still not working:

- [ ] Active tab state for All Collections / Your Collections (lists are changing but active tab does not visibly change)
- [ ] Filters toggle for Visibility not working

![Screen Shot 2022-05-11 at 9 47 38 AM](https://user-images.githubusercontent.com/3440166/167866342-f4e60288-96db-4482-9be6-d121ad1d6202.png)

**Comment by eporter23** [comment]
Additional note - there is poor color contrast for the Collection Type label text against badge color in the Type column.

**Comment by jlhardes** [comment]
Filter toggles are partially working now. Visibility shows options and applies selection but Collection Type shows options and does not do anything to apply a selection.

**Comment by bwatson78** [comment]
@abelemlih is working his magic with that issue above.

**Comment by jlhardes** [comment]
@CB987's PR for All Works/Your Works also cleared up the active tab switching on collections!

**Comment by CB987** [comment]
@jlhardes lol thanks but I can't take that credit-- I believe that was @bwatson78 's [work on this commit](https://github.com/samvera/hyrax/commit/6caaeba1f7b05f589cc8443e4dbf9d77896bc95b), which i used as a template for my fix.

**Comment by jlhardes** [comment]
Oops, sorry @bwatson78 I missed that work on your part! I guess it is similar changes in different places for the active tabs in Collections and Works. Anyway, active tab switching on collections is working now so this issue is closer to done! Thank you!

**Comment by bwatson78** [comment]
@jlhardes Just addressed that with commit: [861978d](https://github.com/samvera/hyrax/commit/861978da77092c9e33aec18e27daef5b22dbe907)
