### ISSUE TITLE
Fix Google Analytics

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#5349]
### Descriptive summary

Google Analytics integration is affecting UI display.  There has been work done in Hyrax `main` which hasn't been pulled into the `blacklight-7`.  Maybe we can cherry-pick some of the commits of latest work?

### Expected behavior
Google Analytics is up to date with Hyrax `main` branch.

### Actual behavior
Intermittent UI errors possibly causing by GA.

### Steps to reproduce the behavior

For one dev, she can't load the Dashboard and gets an error pointing to GA.  

1. Login as an admin user (not any other user account)
2. Successful login takes the user to the dashboard, and gives the following error;
![dashboard-error](https://user-images.githubusercontent.com/1331659/150865945-b0604370-25f8-4eaa-ae9d-4f1724ee9b71.png)

### Related work

#5275

**Comment by Dananji** [comment]
This is fixed in the latest rebased branch: https://github.com/samvera/hyrax/tree/bl7bootstrap4
