### ISSUE TITLE
Can't edit user profile in `Profile` section

### ISSUE THREAD

**Issue by Dananji** [samvera/hyrax#5353]
### Descriptive summary

`Edit Profile` action in the `Profile` section throws an error.

### Expected behavior

Take the user to a form with fields to change/update info.

### Actual behavior
![edit-profile](https://user-images.githubusercontent.com/1331659/150867298-13009889-84ec-4f39-b1b8-5ce76d558874.png)

### Steps to reproduce the behavior

1. From the `Dashboard` sidebar, `Your Activity` -> `Profile`
2. Click on `Edit Profile` button

**Comment by marrus-sh** [comment]
i’ll try to take any Rails/ERB syntax errors and so forth; they shouldn’t be too hard to resolve.
