### ISSUE TITLE
Users can't logout

### ISSUE THREAD

**Issue by Dananji** [samvera/hyrax#5354]
### Descriptive summary

Logout doesn't work, where the user is still able to perform any action when they were logged in after clicking the `Logout` button.

### Expected behavior
![logout-nurax](https://user-images.githubusercontent.com/1331659/150870321-6c01f4ba-96af-4077-859a-474bd485c781.png)

### Actual behavior
![logout-bl7](https://user-images.githubusercontent.com/1331659/150870510-d1205cbe-2ddb-4c3d-9fee-05a9ba68372e.png)

**Comment by marrus-sh** [comment]
This issue was also raised in Slack working off of `main`, so I’m not sure it pertains to this upgrade. @cjcolvar remarked:

> I've never heard of this happening before.
> Is this a development environment where the DB may have been reset but not the rails server?  I wonder if the user session is still active but the DB has been wiped out from underneath.

Resetting the browser session seemed to fix the problem in that case. Does that also work here?

**Comment by adamjarling** [comment]
Hey all, I noticed this as well, and yes @marrus-sh clearing out the browser `/.dassie` session cookie logs a user out.
