### ISSUE TITLE
Cannot visit Works page

### ISSUE THREAD

**Issue by Dananji** [samvera/hyrax#5367]
### Descriptive summary

When there are existing Works in the repository, can't see them on the Works page

### Expected behavior
![works-main](https://user-images.githubusercontent.com/1331659/151047014-6d10d5d6-d1ed-4f09-981f-7554e2c6ff80.png)

### Actual behavior
![works-bl7](https://user-images.githubusercontent.com/1331659/151047033-78faa049-31d9-44cb-a31f-bed22b01c9b4.png)

### Steps to reproduce the behavior

1. Create a Work while on `main` branch
2. Switch to `bl7bootstrap4` branch, `rm .dassie/Gemfile.lock`, `bundle update`, `docker-compose up`
3. Visit Works page from the sidebar on the dashboard

**Comment by adamjarling** [comment]
@Dananji How were you able to get Works added?
