### ISSUE TITLE
Cannot visit Collections page

### ISSUE THREAD

**Issue by Dananji** [samvera/hyrax#5369]
### Descriptive summary

When there are existing Collections in the repository, cannot go to the Collections page.

### Expected behavior
![collection-main](https://user-images.githubusercontent.com/1331659/151048071-be306144-b03a-4632-8bbd-008cad5972d5.png)

### Actual behavior
![collection-bl7](https://user-images.githubusercontent.com/1331659/151048081-28fac1e7-0ceb-4981-8bd7-710f338cd2ae.png)

### Steps to reproduce the behavior

1. Create a Collection while on `main` branch
2. Switch to `bl7bootstrap4` branch, `rm .dassie/Gemfile.lock`, `bundle update`, `docker-compose up`
3. Visit Collections page from the sidebar on the dashboard

**Comment by marrus-sh** [comment]
Going to investigate this.

**Comment by Dananji** [comment]
@marrus-sh This is what I was trying to do yesterday but failed. 

With the new branch you created the authentication issue was fixed, so I was able to bring up the branch with the upgrade without removing the contents in the containers (i.e. without doing a `docker-compose down -v`).

**Comment by marrus-sh** [comment]
`render_facet_item` is deprecated in Blacklight 7 and i’m wondering if switching over to its replacement might solve the problem. trying to figure out what that replacement might be……
