### ISSUE TITLE
Align the Hyrax and Hyku dashboards

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#537]
The Hyrax and Hyku dashboards have diverged, with quite a bit more functionality living in the latter. We ought to contrast the Hyrax and Hyku admin dashboards and extract useful functionality down into Hyrax. (One bit that should live in Hyku proper is the group management, for now.)

**Comment by mjgiarlo** [comment]
- [ ] Move `Reports` item so it's under `Tasks` category
- [ ] Add `Repository Activity` item with `Activity summary` (`/dashboard`) and `System status` (`/status`) subitems 
- [ ] Add `Users and groups` item with `Manage users` (`/admin/users`) and `Manage groups` (`/admin/groups`) subitems (latter blocked by ND work on group implementation for Hyrax)
- [ ] Add `Labels` (`/labels/edit`) subitem to `Settings` item
- [ ] Split `Appearance` page into two tabs: `Banner Image` and `Colors`

**Comment by metageeky** [comment]
For the case of Hyrax, it would be good to make being able to edit styling via the dashboard a flippable option (if turned off, Hyrax doesn't insert `_appearance_styles.html.erb` into `app/views/layouts/_head_tag_content.html.erb`). Some implementations will invest more in customizing the web presence and would likely prefer to not have to juggle their CSS with the administrative settings.

**Comment by mjgiarlo** [comment]
@metageeky Would you mind writing this up as a new enhancement issue?

**Comment by no-reply** [comment]
Is there outstanding work here?

If so, I think I would like to open individual tickets for remaining items and close this overarching ticket.

cc: @vantuyls

**Comment by vantuyls** [comment]
i  think this can be closed with the addition of the ticket for the suggestion.
