### ISSUE TITLE
Valkyrie: Hyrax::PermissionTemplate #source_model uses ActiveFedora::Base.find

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5406]
### Descriptive summary

Hyrax::PermissionTemplate should use the Hyrax.query_service to find and load the object.  This will work for both ActiveFedora wings adapter and for other Valkyrie adapters.

The error is seen when editing an admin set.  The view `hyrax/admin/admin_sets/_form_visibility.html.erb` gets access to `Hyrax::PermissionTemplate` thru the `Hyrax::PermissionTemplateForm`.  It tries to retrieve the model from `Hyrax::PermissionTemplate #source_model`.

### Rationale

PermissionTemplate methods should work for both ActiveFedora and Valkyrie

### Expected behavior

Editing a Hyrax::AdministrativeSet and clicking the Participants tab should load the tab in the edit form.

### Actual behavior

Editing a Hyrax::AdministrativeSet and clicking the Participants tab gets an `Hyrax::ObjectNotFoundError` while loading the tab in the edit form.

![image](https://user-images.githubusercontent.com/6855473/151537705-2a741c82-9548-4a18-a281-71bbca757647.png)

#### Prerequisites:

Edit `/config/initializers/hyrax.rb` and set:
1. set the admin set model
```
  config.admin_set_model = "Hyrax::AdministrativeSet"
```
2. restart rails server

#### To reproduce:

1. navigate to Dashboard -> Collections
2. click button: New Collection
3. select type: Admin Set
3. click button: Create Collection
3. set Title: My Admin Set (or other meaningful name)
4. click Save (this loads the editor for the admin set)
5. click the Participants tab

The error will occur as the tab tries to load.

NOTE: There may be other errors once this error is resolved.

### Related work

See related issues in Issue #5326 UBER: Hyrax-Valkyrization MVP

**Comment by no-reply** [comment]
i think this one is a `wontfix`?

`source_model` has to continue to return the ActiveFedora model, for backwards compatibility reasons. it's not ready to deprecate since AF support needs to stay.

the valkyrie side equivalent is just `#source`.
