### ISSUE TITLE
Valkyrie: Hyrax::AdministrativeSet fails to delete fully

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5407]
### Descriptive summary

When an admin set is created as a Hyrax::AdminstrativeSet and later deleted, it goes through the process without error, but fails to fully delete. 

### Rationale

Deleting admin sets should work whether the admin set is an Active Fedora admin set or a Valkyrie admin set.

### Expected behavior

Deleting an admin set fully deletes the admin set and its access control from the data store and solr.

### Actual behavior

Deleting an admin set deletes the admin set from the datastore, but fails to delete it from solr and fails to delete its access control from the datastore.

#### Prerequisites:

Configure Hyrax:
1. Edit `/config/initializers/hyrax.rb` and set:
```
  config.collection_model = "Hyrax::PcdmCollection"
  config.query_index_from_valkyrie = true
  config.index_adapter = :solr_index
```
2. restart rails app
3. Make sure regular `hyrax-development` and `hyrax-valkyrie-dev` solr cores are running .  _Your core names may vary depending on how you start them and how they are configured in the app._
4. Make sure you have access to the datastore (i.e. postgres)

NOTE: For testing of nurax-pg, the solr core is typically named nurax-pg.

Create Admin Set
1. click button: New Collection
2. select type: Admin Set
3. click button: Create Collection
3. set Title: DELETE ME (or other meaningful name)
4. click Save
5. Copy the id from the URL

Verify that the admin set was created in both solr cores with `q`:  `title_tesim:DELETE ME` (or similar query).
Verify that the admin set and it access control were created in the datastore.

#### To reproduce:

1. Navigate to: Dashboard -> Collections
1. Click on the title of the admin set you want to delete (e.g. DELETE ME)
2. click button: Delete

Verify that the admin set was deleted from both solr cores with `q`:  `title_tesim:DELETE ME` (or similar query).
Verify that the admin set and it's access control were created in the datastore.

### Related work

See related issues in Issue #5326 UBER: Hyrax-Valkyrization MVP
See Issue #5331 describing the same issue for Hyrax::PcdmCollection

**Comment by no-reply** [comment]
looks like this behavior should get added to the `AdminSetDestroy` transaction.

**Comment by jlhardes** [comment]
Unable to fully test locally using koppie since I'm not sure how to access the Postgres datastore. I can see Solr and was able to create the admin set, query for it in Solr, delete the admin set, and then verify that Solr no longer has a record for the admin set. The UI looks like everything works as it should but I can't verify that the admin set and its access control are removed from the datastore.

**Comment by gamontoya** [comment]
@rjkati Not able to verify this issue either.

**Comment by alishaevn** [comment]
we were able to verify today that this issue has already been resolved. 

<details>
<summary> postgres gui (dbeaver) settings</summary>

![image](https://github.com/samvera/hyrax/assets/29032869/b1f9ff73-7380-45be-b661-d6963bd7ad03)
</details>

<details>
<summary> after creating an admin set</summary>

![Screenshot 2023-05-24 at 1 31 55 PM](https://github.com/samvera/hyrax/assets/29032869/20de4cfd-1d04-4771-99e2-56798f5ed0e5)
![Screenshot 2023-05-24 at 1 32 45 PM](https://github.com/samvera/hyrax/assets/29032869/7fec7e1b-d300-468d-aa40-45005c2eeae2)
![Screenshot 2023-05-24 at 1 47 33 PM](https://github.com/samvera/hyrax/assets/29032869/f591af5b-ac17-4e3c-9aa2-1beb98371ea0)
</details>

<details>
<summary> after deleting the above admin set</summary>

![image](https://github.com/samvera/hyrax/assets/29032869/5b407cda-0769-4db6-9be4-3d323353ff19)
![image](https://github.com/samvera/hyrax/assets/29032869/f32e6bf1-8d4a-452b-947a-352e6ec42ba2)
![image](https://github.com/samvera/hyrax/assets/29032869/e5b3ac9f-c4ed-41d1-9daf-cf6f20fbb614)
</details>

**Comment by jessicahilt** [comment]
SoftServ verified.
