### ISSUE TITLE
Dashboard menu sidebar - not all menu items should be displayed to all users

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#541]
As a registered user with no higher privileges, when I look at my dashboard, I should only see "My Activity" and "Reports" under "Tasks". Currently I see all menu items.

This matrix outlines the visibility of dashboard menu items to user roles: https://docs.google.com/spreadsheets/d/1r1R035qj13AFpZpgG9Nui1-JxvKJyQYrswH6RVbl1tM/edit#gid=0

**Comment by jcoyne** [comment]
Can you flesh this out more? What do you mean by "all menu items"  Specifically which items should not be seen. By default we give registered users a number of privileges, among them is the ability to create works and collections so it follows that they should be able to see and manage their works and collections.  Are you asserting they should not see the links for "Works" and "Collections"?

**Comment by ggeisler** [comment]
I think they should see the links for Works and Collections. I made that comment in the spreadsheet (cell A12) but perhaps @hannahfrost didn't see it.

**Comment by hannahfrost** [comment]
I did miss that comment, @ggeisler. Fleshing it out more now. Thanks!

**Comment by hannahfrost** [comment]
@jcoyne Thanks. Do the additions to the matrix help?

**Comment by jcoyne** [comment]
@hannahfrost I'm more confused than ever. The grid show registered users not having links for works and collections despite what @ggeisler is saying above.

**Comment by hannahfrost** [comment]
@jcoyne Hasty oversight because I was distracted. I think it is better now. I bet you'll let me know if it is not clearer!

**Comment by vantuyls** [comment]
Can we close this issue?

**Comment by mjgiarlo** [comment]
I do believe so.
