### ISSUE TITLE
Update Work List page UI

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#5412]
### Descriptive summary

General updates to the Work List page UI.

![image](https://user-images.githubusercontent.com/3020266/151593017-27ebe6a9-f030-45c8-b529-2e0f10742e63.png)

### Expected behavior
- [x] Active tab state works for All Works / My Works
- [x] Filters toggle
- [x] Search bar formatting updated
- [x] Show count dropdown cleaned up

### Steps to reproduce the behavior

1. Go to a Work list page in the Dashboard

**Comment by jlhardes** [comment]
Search bar formatting is updated and Show count dropdown is cleaned up on `bl7bootstrap4` branch but Active tab still doesn't visibly switch between All Works and My Works (but list of works does change) and Filters do not toggle to show options.

**Comment by CB987** [comment]
i'm looking at this one

**Comment by jlhardes** [comment]
That fixed the All Works/Your Works tab switching!
