### ISSUE TITLE
Edit Work page UI

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#5413]
### Descriptive summary

General cleanup on Edit Work page

![image](https://user-images.githubusercontent.com/3020266/151593659-f6606501-5d99-4a05-9ddf-9543da1cac26.png)

### Expected behavior
- [ ] Form labels should look like BS4 default style
- [ ] Vertical align tags and labels
- [x] Checkmark icons are missing / broken

### Steps to reproduce the behavior

1. Edit a Work

**Comment by jlhardes** [comment]
All three expected behaviors are still issues in `bl7bootstrap4` branch

**Comment by jlhardes** [comment]
The form labels vs guidance text isn't part of this issue as defined so we can open a new issue to change that if needed. The vertical alignment of the labels and tags looks the same now as it does on nurax-dev so I am fine with moving forward without making any changes there. The checkbox icons are fixed and the other issues seem to be fixed or consistent with what we currently see on nurax-dev (pre-upgrade).
