### ISSUE TITLE
Update feature tests for Bootstrap 4

### ISSUE THREAD

**Issue by marrus-sh** [samvera/hyrax#5420]
### Descriptive summary

Certain HTML class names have changed as a result of the upgrade to Bootstrap 4 (in the `bl7bootstrap4` branch), causing some tests to break. These tests need to be updated to reflect the new class names, or be rewritten to be less fragile.

I believe most if not all of these tests are feature tests.

### Related work

Part of #5276.

**Comment by abelemlih** [comment]
@jlhardes is this still an issue? All the feature specs in the `bl7boot4rails6` branch are passing.

**Comment by jlhardes** [comment]
If all feature specs are passing in `bl7boot4rails6` then I think this issue has been addressed. Closing this issue.
