### ISSUE TITLE
Creating Hyrax-based app incompatible with gem 'qa' 5.8.0

### ISSUE THREAD

**Issue by jzimpel** [samvera/hyrax#5435]
### Descriptive summary

With the current 5.8.0 version of gem 'qa', which is installed when creating a new Hyrax-based app, an exception is raised:
`.rvm/gems/ruby-2.5.7/gems/qa-5.8.0/lib/qa/authorities/local.rb:20:in 'subauthorities_path': undefined method '[]' for nil:NilClass (NoMethodError)` 
which can be traced back to statements in config/initializers/hyrax.rb that are included by a template installation (`rails _5.2.5_ new new-from-template-v3-0-1 -m https://raw.githubusercontent.com/samvera/hyrax/v3.0.1/template.rb`):
```
Qa::Authorities::Local.register_subauthority('subjects', 'Qa::Authorities::Local::TableBasedAuthority')
Qa::Authorities::Local.register_subauthority('languages', 'Qa::Authorities::Local::TableBasedAuthority')
Qa::Authorities::Local.register_subauthority('genres', 'Qa::Authorities::Local::TableBasedAuthority')
```

Tested with:
Hyrax (v3.0.1)
Rails (5.2.5)
Ruby (2.5.7)
Qa (5.8.0)

and:
Hyrax (v3.3.0)
Rails (5.2.6)
Ruby (2.5.7)
Qa (5.8.0)

**Comment by cjcolvar** [comment]
I ran into this issue as well and am trying to fix it by cutting a new version of QA which reverts the change which causes this issue.
https://github.com/samvera/questioning_authority/pull/350
