### ISSUE TITLE
New work under review not showing up at "Review Submissions" on dashboard

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [samvera/hyrax#5436]
### Descriptive summary

In Hyrax 3.3.0, as a manager of a workflow, after a work is created by a user and is under review, I expect to see it in two sections on dashboard: 1) In the list of the "Managed Works" in "Works" section; 2) In the list of the "Under Review" in "Review Submissions" section. 

### Expected behavior

The manager can see the newly created work under review at the section of "Managed Works":

![image](https://user-images.githubusercontent.com/93392603/152865081-9efa652f-6294-4f30-8b56-c79e56a0de45.png)

It should be in the list of the section of "Review Submissions".

### Actual behavior

But the newly created work is missing in the list of "Under Review" in "Review Submissions" section:
![image](https://user-images.githubusercontent.com/93392603/152868523-514b8146-1a8a-4dc0-9015-15780e11e3d0.png)

### Steps to reproduce the behavior

1. Log in as an admin user,  select an admin set and then attach to it a submission-review workflow, e.g., the "mediated deposit workflow".  After this, assign a non-admin user as the manager of the admin set and define the user/user roles who will use this admin set with the submission workflow to submit works.
2. Log in as a non-admin user that has the authority to submit work to the submission-review workflow, create a new work.
3. Log in as the non-admin user who was assigned as the manager to the submission-review workflow, check if the newly created work is in the list of "Managed Works" at dashboard.
4. Then go to the list of the "Under Review" under dashboard section of "Review Submissions", and check if work is also there.

### Related work

[Link to related tickets or prior related work here.](https://github.com/samvera/hyrax/issues/3171)

**Comment by fritzfreiheit** [comment]
I could not reproduce this on my local host (built from scratch). But I did find an inverted version of this problem where the works in an admin set with single-step mediated deposit were showing up in the "Under Review" section of "Review Submissions", but not in the "Managed Works" tab under Dashboard Works page for non-admin users with managing role for that admin set. I've open a ticket to address this alternate issue: #5471

**Comment by rjkati** [comment]
I can replicate this issue in my local build of Hyrax 4.0.0.beta1

**Comment by rjkati** [comment]
This is working now on nurax-dev (Hyrax 4.0.0.beta2)
