### ISSUE TITLE
Highlighting a work on user profile displays "ArgumentError in Hyrax::Dashboard::Profiles#show" error message

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5455]
### Descriptive summary

On nurax-pg, selecting a work to highlight on my profile generates an "ArgumentError in Hyrax::Dashboard::Profiles#show" error when viewing my profile

### Expected behavior

After I highlight a work on my profile and navigate to my profile page, my profile page should display.

### Actual behavior

After I highlight a work on my profile and navigate to my profile page, an error message displays.

### Steps to reproduce

1. On nurax-pg, navigate to Dashboard -> Works
2. In the Actions menu next to a work, select "Highlight Work on Profile"
3. Navigate to Dashboard -> Your activity -> Profile
4. Observe error message
![argumenterror](https://user-images.githubusercontent.com/32644254/155217833-b6f32e99-7ca3-46c0-b70b-99d2ce3bda9d.PNG)

**Comment by jlhardes** [comment]
Also seeing an error for this when visiting the profile I tried to highlight a work on from https://nurax-pg.curationexperts.com/users (other profile pages still work, though)
<img width="1356" alt="Screen Shot 2022-02-22 at 5 30 52 PM" src="https://user-images.githubusercontent.com/3440166/155230578-76260409-b995-4975-9e6d-8724ca0b32e5.png">

**Comment by rjkati** [comment]
Retested this in Windows/Chrome. Thumbnails do not display, but placeholder thumbnails are now generated.

When I highlight a work with a placeholder thumbnail, the user profile page loads as expected. When I highlight a work without a placeholder thumbnail, the user profile page displays an error message as described above.

**Comment by jlhardes** [comment]
Retested and generic thumbnail is always present now at least so error message no longer occurs. File derivatives are still not generating but that is not this issue.
