### ISSUE TITLE
Transferring ownership of work displays "NoMethodError in Hyrax::TransfersController#new" error message

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5456]
### Descriptive summary

On nurax-pg, when I attempt to transfer ownership of one of my works, I see a "NoMethodError in Hyrax::TransfersController#new" message

### Expected behavior

Clicking "transfer ownership of work" should open Transfer Ownership page

### Actual behavior

Clicking "transfer ownership of work" generates "NoMethodError in Hyrax::TransfersController#new" error message

### Steps to reproduce the behavior

1. Make sure that transferring ownership is enabled on nurax-pg
2. Navigate to Dashboard -> Works
3. In the Actions menu next to a work, select "Transfer Ownership of Work"
4. Observe error message
![hyraxtransferscontroller](https://user-images.githubusercontent.com/32644254/155219364-744e7e41-63d0-4d2e-98a5-f5bd52193c72.PNG)

**Comment by gamontoya** [comment]
Confirming that this is now working (koppie)

![transfer2022-09-14](https://user-images.githubusercontent.com/4314914/190229091-86320c10-7ed0-4362-b0c3-777f965aa29c.png)

**Comment by gamontoya** [comment]
@jlhardes This is **DONE**. Works as expected on nurax-pg.
