### ISSUE TITLE
Works deposited via proxy are always set to private visibility

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5457]
### Descriptive summary

On nurax-pg, when depositing a work as a proxy, the visibility of the work is set to private even if the visibility on deposit was set to public.

### Expected behavior

Works deposited via proxy should reflect the visibility settings selected during the deposit process.

### Actual behavior

Works deposited via proxy are set to private.

### Steps to reproduce the behavior

1. Make sure that proxy deposit is enabled on nurax-pg and that you have an account set up as a proxy for another account
2. Navigate to Dashboard -> Works
3. Click "Add new work" and select "Generic Work"
4. Fill out required metadata and add a file
5. Select "Public" visibility
6. Select another user in the "Proxy depositors" box.
7. Check the Deposit agreement box and click "Save".
8. Observe message "Unauthorized The page you have tried to access is private" message

**Comment by hackartisan** [comment]
It looks like visibility is not defined as an attribute on the resource. So when the postgres adapter saves it by pulling its attributes it simply doesn't come out and doesn't override the old value.
