### ISSUE TITLE
Works are not added to admin set collection page

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5469]
### Descriptive summary

On nurax-pg, works deposited to an admin set do not display on the admin set collection page

### Expected behavior

Works added to an admin set will appear in the "Works in this set" list on the admin set collection page.

### Actual behavior

Works added to an admin set do not appear in the "Works in this set" list on the admin set collection page.

### Steps to reproduce the behavior

1. On nurax-pg, as an admin user, navigate to Dashboard -> Works
2. Click "Add new work" and select "Generic Work"
3. Fill out the required metadata, and add a file. On the "Relationships" tab, note the admin set that the work will be deposited to.
4. Click "Save".
5. Navigate to Dashboard -> Collections
6. Click on the admin set to which you deposited the work in steps 3 & 4
7. Note that the "Works in this Set" list does not display your work. The "Total Items" count also has not incremented.

**Comment by elrayle** [comment]
I can no longer reproduce this issue.  It appears to be fixed.  I believe it was fixed by PR #5563.
