### ISSUE TITLE
Works in mediated workflow not listed as managed works for user with managing role

### ISSUE THREAD

**Issue by fritzfreiheit** [samvera/hyrax#5471]
### Descriptive summary

Works in mediated workflow not listed as managed works on on a user's Dashboard Works page for users with managing role in an admin set with one-step mediated deposit workflow. These works are listed in the Review Submissions page. This occurs in HEAD.

### Rationale

This is an expected behavior.

### Expected behavior

Users with managing role for an admin set with a one-step mediated workflow should see a list of managed works on their Managed Works tab on their dashboard Managed Works page.

### Actual behavior

The Dashboard Managed Works tab does not display for users with a managing role in an admin set with one-step mediated deposit that have one or more member works.

### Steps to reproduce the behavior

1. Ensure that an admin set with a one-step mediated workflow exists.
2. As a normal user, create a work and add the admin set with a one-step mediated workflow identified or created in step 1.
3. Grant a non-admin user managing status to the admin set with the one-step mediated workflow used in step 2.
4. Go to the Dashboard, then Works page of a non-admin user with managing status from step 3.
5. The Managed User tab should be visible. Go to that tab.
6. The work created in step 2 should be listed in this tab. (It should also be listed in the Review Submissions tab.)

### Related work

New work under review not showing up at "Review Submissions" on dashboard #5436

**Comment by dlpierce** [comment]
In my testing, when the managing user creates/owns the work it does not appear in the Managed Works tab, and if that's the only work then the tab is not displayed at all. If a different user with depositor status creates the work then it does appear.

**Comment by fritzfreiheit** [comment]
See: https://github.com/samvera/hyrax/issues/5485 (Non-public works should be viewable/reviewable by non-admin managing users)
