### ISSUE TITLE
Image viewer is not working in nurax-pg

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [samvera/hyrax#5474]
### Prerequisite

Issue #5480 should be resolved before exploring this issue.  There are several issues with files on a work show page.  When they are resolved, it is possible the viewer will work as expected.

### Descriptive summary

Cannot view images using image viewer, e.g. IIIF viewer.

### Steps to reproduce the behavior

1. Create work of image type and check if images can be viewed using image viewer.

### Related Work

Issue #5480 - image file in Items section of work show page is a link instead of a title
Issue #4788 - Work thumbnail fails to show in Dashboard -> Works list of works

**Comment by dunn** [comment]
is this related to https://github.com/samvera/hyrax/issues/5543 ?

**Comment by jlhardes** [comment]
#5504 - Generate derivatives for FileSets when Valkyrie mode is enabled might also be a related issue and has had some work done on it.

**Comment by gamontoya** [comment]
@rjkati This ticket is closed and in QA, but the image viewer isn't working on pg-nurax, soooooooo.

**Comment by gamontoya** [comment]
- Hyrax Version: 4.0.0
- Hyrax Revision: ff6bb7d626c923761443f62dcc489d3a3cdb6b30
- SHA: 8bbaacf7390b675a298d79bee29fcc81f4af6cb9

![yay](https://github.com/samvera/hyrax/assets/4314914/87eb5602-a2d1-4291-8ae8-6bdc241a2ff5)
