### ISSUE TITLE
Edit collection only shows title field for Hyrax::PcdmCollection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5494]
### Descriptive summary

Creating and editing a Hyrax::PcdmCollection only includes a Title field on the Description tab.   Should there be more fields?

### Rationale

A reasonable default set of collection fields should be available to the end user out of the box.

### Expected behavior

When editing a collection, expect to be able to set more than Title.  Exact fields TBD.  <--  @jlhardes 

### Actual behavior

When editing a collection, only presented with a Title field and no other metadata.

![image](https://user-images.githubusercontent.com/6855473/156822362-7720be12-757f-4dd9-8ca8-3e2ce08c50a7.png)

#### Prerequisite:
Create a collection first if none exist.

#### To Reproduce:
1. Dashboard -> Collections
2. beside any existing collection, Select Action: Edit collection

NOTE: Only title field is available on the Description tab.

### Related work

PR #5157 - Update PcdmCollection metadata to match existing ::Collection metadata

**Comment by jlhardes** [comment]
All descriptive metadata fields are now available to fill in when creating or editing a collection but they do not all show on the collection show page. Closing this issue and will create another issue or issues referencing PR #5157 to have collection descriptive metadata show and be configurable.
