### ISSUE TITLE
Generate derivatives for FileSets when Valkyrie mode is enabled

### ISSUE THREAD

**Issue by tpendragon** [samvera/hyrax#5504]
### Descriptive summary

The pub/sub and transaction architecture doesn't currently generate derivatives for Valkyrie resources, resulting in no thumbnails or manifests.

### Rationale

Valkyrie resources should be able to generate derivatives.

### Expected behavior

Derivatives generate.

### Actual behavior

Derivatives don't generate.

#### Prerequisites

Configure Hyrax:

1. Edit /config/initializers/hyrax.rb and set:
```
  config.collection_model = "Hyrax::PcdmCollection"
  config.query_index_from_valkyrie = true
  config.index_adapter = :solr_index
```
2. restart rails app

#### To reproduce

1. Navigate to: Dashboard -> Works 
2. Click button: Add new work
3. Select type: Monograph
4. File in required metadata and other required steps
5. Add an image file
6. Click button: Save

This forwards to the new work's show page.  Look at the list of items at the bottom. There is no thumbnail.

### Related work

Found as part of https://github.com/samvera/hyrax/issues/5480

**Comment by tpendragon** [comment]
Notes:

Most derivatives store locally - I think we can just use the logic in CreateDerivativesJob for all of those. The test app doesn't have ffmpeg, but has enough to run PDF and (maybe image) derivatives - so we should be able to run that and make sure the files exist on disk. Unfortunately that's not the case for ExtractedText - extracted text persists to a File node in Fedora. See:

https://github.com/samvera/hyrax/blob/f940a32cbc44f896d23eeab99a8b7231f3dbee2e/app/models/concerns/hyrax/file_set/derivatives.rb#L45-L47

The PersistDirectlyContainedOutputFileService creates a node in Fedora via ActiveFedora. If we want to maintain that we'll have to find a nice way to replace that logic. I think we can use the Wings storage adapter? I don't know if that'll work right with nurax-pg and a normal storage adapter.

I think my strategy is going to be to get everything but extracted text to work.

**Comment by jlhardes** [comment]
#4788 - Hyrax::Works do not show thumbnail in Dashboard -> Works might provide helpful info for this issue, even though it seems to be focused on the Monograph work type on nurax-dev that is Wings.

**Comment by gamontoya** [comment]
@rjkati I believe this is closeable. This is what I'm seeing on Koppie after editing my local `hyrax.rb`.

![koppie-edit](https://github.com/samvera/hyrax/assets/4314914/6c49cb47-b70b-44ec-b33c-0a847f494ad7)

**Comment by rjkati** [comment]
In the Valkyrie update meeting, we determined that thumbnails and derivatives should be displaying. Currently, thumbnails and derivatives are not displaying on koppie or nurax-pg. Softserv will spend time today digging through the nurax-pg code to troubleshoot #5594 and will look at this ticket during that investigation.

**Comment by gamontoya** [comment]
@rjkati For my purposes, are we expecting to see `image thumbnails` (not generic place holders) like I see on dev-nurax?

![dev-nurax](https://github.com/samvera/hyrax/assets/4314914/43031d3d-40ad-4c86-be35-4fc8a5ac5fa0)

**Comment by rjkati** [comment]
@gamontoya, yes that's correct. We should see image thumbnails on pg-nurax as well.

**Comment by gamontoya** [comment]
@rjkati Still not seeing thumbnails on pg-nurax. Can you confirm or should I only test on Koppie after updating hryax.rb?

**Comment by tpendragon** [comment]
Our understanding is that this is only a problem on nurax-pg, not locally. Whoever grabs this will probably have to connect with @dlpierce

**Comment by dlpierce** [comment]
Thumbnails should be working in koppie/nurax-pg, except that the thumbnails in the catalog view do not show unless the work is edited after ingest. I almost have a PR ready to trigger a work reindex to fix this.

**Comment by rjkati** [comment]
I'm now seeing thumbnails for images, but not PDFs 

![pdf_image](https://github.com/samvera/hyrax/assets/32644254/175de354-b249-4f0e-b16d-75425f819631)

Example: https://pg.nurax.samvera.org/concern/generic_works/8765b6ee-db0b-47b9-a5c7-e8efbc3dd4b9?locale=en

**Comment by dunn** [comment]
@rjkati is that only happening on nurax-pg?

**Comment by rjkati** [comment]
@dunn yes it's only happening on nurax-pg. I tested this morning locally using koppie and got thumbnails to display for PDFs.

![pdf_image_works](https://github.com/samvera/hyrax/assets/32644254/c9b2223f-ada8-48bc-8abb-e02ed229412a)

**Comment by rjkati** [comment]
@dlpierce for testing purposes, should we expect that there will be no thumbnails for PDFs on pg.nurax (maybe all the nuraxes?) until further notice? If so, I can make a note in the testing spreadsheet to verify thumbnails with images.

**Comment by dlpierce** [comment]
I changed the PDF policy on Nurax to make this work. There will also be a PR to address reindexing the work after its thumbnail has derivatives created.
