### ISSUE TITLE
Remove icons from the Works dashboard "actions" dropdown menu

### ISSUE THREAD

**Issue by sdellis** [samvera/hyrax#5506]
### Descriptive summary

The icons in the Works dashboard "actions" dropdown menu are inconsistent with the "actions" dropdown in the Collection dashboard. Given that the icons are not enhancing the accessibility in any way, they should be removed. This is only a UI change as it does not affect backend models.

### Related work

Ref #5490

**Comment by sdellis** [comment]
@jlhardes I know you already approved this on Slack, but for the record can you also 👍  the removal of the icons here? Thank you!

**Comment by jlhardes** [comment]
I am OK with this change to remove the icons from the Works Select menu in the Dashboard since there’s no accessibility aid to including the icons and we aren’t introducing any backwards-compatibility issues by taking out those icons. Thanks!
