### ISSUE TITLE
Click depositor name on result page of "Recently Uploaded" leads to error: "ArgumentError in Hyrax::Users#show"

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [samvera/hyrax#5517]
### Steps to reproduce the behavior

1. Home page click "Recently Uploaded"
2. On the result page click depositor name

### 
![image](https://user-images.githubusercontent.com/93392603/157691545-08b76eb8-1506-4778-b935-13dd9cd0c6bd.png)

**Comment by rjkati** [comment]
Retested and seems to be working now. Clicking on a depositor name in "Recently Uploaded" goes to the depositor's profile page, rather than an error message.
