### ISSUE TITLE
Work View shows all work types 

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#553]
<a href="https://github.com/julesies"><img src="https://avatars2.githubusercontent.com/u/4356335?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [julesies](https://github.com/julesies)**
_Friday Mar 10, 2017 at 15:55 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/3136_

----

This is maybe a feature request, but I wanted to make sure it's known. Sorry for noise, if so.

We are just now testing multiple work types in 7.3.0rc2. We have two Work, Dataset. I noticed on the work view, the top section "Relationships" is growing and it's really not meaningful if there are no relationships. If say we have 5 work types...would they all show? 

![screen shot 2017-03-10 at 9 05 02 am](https://cloud.githubusercontent.com/assets/4356335/23801980/e3836c96-057f-11e7-9d55-210a8ae80db8.png)

**Comment by mjgiarlo** [comment]
I'd like to enlist the help of @projecthydra-labs/hyrax-ui-ux-advisors @ggeisler here: should we hide relationships rows if there are no relationships of that type? See @julesies description & screenshot above for more context about why she's asking.

**Comment by newmanld** [comment]
+1 to hiding empty relationship rows.

**Comment by ggeisler** [comment]
@mjgiarlo Agree with hiding rows with no relationships.

**Comment by no-reply** [comment]
This seems to be fixed by Hyrax 2.1 (maybe 2.0 as well?)
