### ISSUE TITLE
Allow new Valkyrie works to add existing members

### ISSUE THREAD

**Issue by eliotjordan** [samvera/hyrax#5555]
### Descriptive summary

When creating a new Valkyrie work, allow users to attach existing works as children. This would happen in the form under the `Relationships` tab. Will need to add the `update_work_members` transaction step to the [create_valkyrie_work step args](https://github.com/samvera/hyrax/blob/7973127095981dbe8f931aeaa262dcced37f9a7c/app/controllers/concerns/hyrax/works_controller_behavior.rb#L184).

### Related work

https://github.com/samvera/hyrax/pull/5547

**Comment by elrayle** [comment]
I think this might be fixed.  Need verification.

**Comment by rjkati** [comment]
I tested this on nurax-pg and was able to add an existing work as a child via the Relationships tab.
