### ISSUE TITLE
Clicking "view all collections" on nurax-pg homepage returns no results

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5567]
### Descriptive summary

On the [nurax-pg homepage](https://nurax-pg.curationexperts.com/?locale=en), clicking the "View All Collections" button returns no results, even though the "Explore Collections" list displays multiple collections.

### Expected behavior
When collections appear in the "Explore Collections" list, they should appear in a "View All Collections" search.

### Actual behavior
No collections appear when clicking "View All Collections"

### Steps to reproduce the behavior

1. Navigate to https://nurax-pg.curationexperts.com/?locale=en
2. Click the "View All Collections" button in the "Explore Collections" tab.
3. Observe that no results have been returned.

**Comment by elrayle** [comment]
In some places, the search for collections uses generic_type and in others uses human_readable_type.  If the filter uses generic_type, then the list of collections are displayed.

Testing in SOLR:
* `human_readable_type_sim:Collection` returns collections in nurax-dev, but not nurax-pg
* `human_readable_type_tesim:Collection` returns collections in both
* `generic_type_sim` returns collections in both

To maintain backward compatibility, the solr document for Hyrax::PcdmCollections should include `human_readable_type_sim:Collection`.

**Comment by no-reply** [comment]
why'd we choose `human_readable_type` instead of `generic_type`?

the latter seems more fit for purpose, and i'm not following how the former is more backwards compatible.

**Comment by jlhardes** [comment]
This problem is still occurring on nurax-pg.

**Comment by rjkati** [comment]
This is still occurring on pg.nurax running Hyrax 4.0.0.rc2

**Comment by gamontoya** [comment]
@rjkati This can be closed. It's working fine now on nurax-pg `Hyrax Version: 4.0.0`
