### ISSUE TITLE
User profile page displays wrong count for collections and works

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5568]
### Descriptive summary

On nurax-pg, the depositor page displays the incorrect count for both works and collections. 

### Expected behavior
Works and Collections count should be accurate.

### Actual behavior
Works and collections count seem to be displayed together under the collection count.

### Steps to reproduce the behavior

1. Go to nurax-pg homepage https://nurax-pg.curationexperts.com/?locale=en
2. Click the "Recently Uploaded" tab
3. Click on the name of a depositor
4. Observe work and collections count in the user statistics box.

![userstats](https://user-images.githubusercontent.com/32644254/159509410-514a8d82-90c7-4e1d-b069-db926b533bb6.PNG)

Note that this user (test@testing.com) has created 22 works and 2 collections at the time of the writing of this ticket. The user statistics show that test@testing.com has created 24 collections, which suggests that the collection and work counts might be added together for display.

![workcount](https://user-images.githubusercontent.com/32644254/159509929-cbb8daf6-0508-4aa6-b3e0-28060028558d.PNG)
![collectioncount](https://user-images.githubusercontent.com/32644254/159509943-aedbf318-8a52-4572-82b5-0e05cb897c1d.PNG)

**Comment by elrayle** [comment]
NOTE: 
* Clicking `Works created` in the user's stats panel shows 0 works.  The filters are correct (i.e. Type -> Work, Depositor -> the user from the panel)
* Clicking `Collections created` in the user's stats panel correctly shows the user's collections only.
* While viewing the created collections, removing the collection filter shows all works and collections, as expected.

Seems like there are 2 problems happening...
* for sure, the count of items in the panel is including works and collections in the collection count and always 0 works
* likely, there is either something wrong with the query of solr or with the data in solr or both

**Comment by jlhardes** [comment]
Remaining work one [#3820](https://github.com/samvera/hyrax/issues/3820#issuecomment-880084599) - Replace calls to ActiveFedora::Base.where (removes 7 refs to ActiveFedora) might be needed for this issue

**Comment by gamontoya** [comment]
@rjkati This is closeable. It's working on nurax-pg `Hyrax Version: 4.0.0`
