### ISSUE TITLE
Works cannot be saved if embargo or lease is assigned (nurax-pg)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5572]
### Descriptive summary

Using Hyrax 3.3/Nurax-pg, a user cannot save a new work or save changes to an existing work if an embargo has been assigned. 

### Rationale

Users should be able to assign embargoes if they are enabled for a given Admin Set.

### Expected behavior

If a user can select embargo options, they can then populate them and save their changes to the work.

### Actual behavior

When an embargo is assigned to a work, clicking Save returns the following error: 
```Failed save on # undefined method `[]' for nil:NilClass```

<img width="903" alt="Screen Shot 2022-03-23 at 1 42 11 PM" src="https://user-images.githubusercontent.com/13855987/159762553-19b128a1-61fb-46c7-b1f9-ac2d71274e1b.png">

### Steps to reproduce the behavior

1. Create a new work or edit an existing work in an Admin Set that allows embargoes/leases (e.g. Default Admin Set)
2. Select any permitted embargo or lease option (e.g. Embargo > Restricted to Private until 3/30/2023; then open to Public)
3.  Make sure all Requirements show green checks under Save Work
4. Click Save Changes
5. See error message in banner above the work form 

### Related work

Prior work: #5460

**Comment by no-reply** [comment]
i think this should be closed by https://github.com/samvera/hyrax/pull/5803.

**Comment by jlhardes** [comment]
This is working when testing locally via koppie but I am noticing that the Works list on the dashboard does not show the "Embargo" label for the work under Visibility of Work. Instead I am seeing the current status due to the embargo being applied ("Private" at the moment).

**Comment by jlhardes** [comment]
This issue is fixed on nurax-pg. The Visibility badge problem is called out in #5845 - Manage Embargoes is not listing embargoed works so this issue can be closed.
