### ISSUE TITLE
Works in one-step workflow cannot be approved by a manager

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5573]
### Descriptive summary

Works which are in a one-step workflow do not display "review and approval" menu and cannot be approved by a manager account

### Expected behavior
Works which are in a one-step workflow should display the "review and approval" menu and be able to be approved by a manager or repo admin account.

### Actual behavior
Works in a one-step workflow display a "The work is not currently available because it has not yet completed the approval process" message to authorized manager accounts. The "review and approval" banner does not display.

### Steps to reproduce the behavior

1. Make sure that a non-admin account is added as a manager to an admin set using the one-step workflow and that at least one work has been deposited to that admin set
2. Log in as the non-admin user
3. Navigate to Dashboard -> Review Submissions
4. Click on the title of a work in the Under Review tab
5. Observe "The work is not currently available because it has not yet completed the approval process" message

**Comment by alishaevn** [comment]
even as a logged in admin user on koppie, I don't get the "review and approval" option. I do see that option logged in as an admin on dassie though.

https://github.com/samvera/hyrax/assets/29032869/602c2cfa-823c-45f8-b914-97616b9e50f4

**Comment by gamontoya** [comment]
![yay](https://github.com/samvera/hyrax/assets/4314914/b9eb44b1-d3b3-4f21-a7af-040c88462ec3)
