### ISSUE TITLE
Deleting an admin set with works generates error message

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5574]
### Descriptive summary

When I attempt to delete an admin set which contains works, I receive a "AbstractController::DoubleRenderError in Hyrax::Admin::AdminSetsController#destroy" error message

### Expected behavior
When I attempt to delete an admin set with works in it, I should receive an error message which is friendly to end-users.

### Actual behavior
When I attempt to delete an admin set with works in it, I receive a "AbstractController::DoubleRenderError in Hyrax::Admin::AdminSetsController#destroy" error message

### Steps to reproduce the behavior

1. Log into nurax-pg as an admin user
2. Navigate to this admin set: https://nurax-pg.curationexperts.com/admin/admin_sets/17142a22-fcb5-4ad4-b8a4-a6d13847a7ec?locale=en
3. Click the Delete button
4. Observe error message

![deleteadminset](https://user-images.githubusercontent.com/32644254/159786999-b5fa7775-95af-4dbb-b02f-a433b45333bb.PNG)

**Comment by elrayle** [comment]
Several observations:
* the description says this admin set has works, but the UI reports 0 works
* if an admin set has works, then the Delete button should be disabled
* if I create a new admin set and add works to it, the Delete button is disabled
* if I create a new admin set and delete it before adding any works, the delete succeeds
* if I create a new admin set, add works, move the works to a different admin set, and try to delete the admin set once it is empty, the delete succeeds
* if I try to delete the admin set mentioned in this issue, I get the described error

I was not able to identify what it is about the admin set in this issue that is causing the delete to fail.

**Comment by jlhardes** [comment]
I just tested again on nurax-dev and @elrayle's description holds. We can't recreate this issue because it is not possible to delete an admin set that contains works. Closing this issue.
