### ISSUE TITLE
Work sharing is not saved

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [samvera/hyrax#5576]
### Descriptive summary

After adding a sharing of a work, click the save button does not save the added sharing.

### Steps to reproduce the behavior

1. Go to work edit page
2. Go to the sharing tab, add a sharing access with a user.
3. Click save and you will see the added sharing is not saved and displayed.

**Comment by jlhardes** [comment]
Tested on nurax-pg and sharing is now saving. Closing issue as fixed.
