### ISSUE TITLE
A work can be added to another single-membership collection and at the same time removed from the first single-membership collection

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [samvera/hyrax#5582]
### Descriptive summary

1) When adding a work which belongs to a single-membership collection to second single-membership collection, it is automatically removed from the first single-membership collection while added to the second single-membership collection, where both situations are not allowed.

2) After clicking the "Savw" button on the work edit page under the "Relationships" tab, an error of "ArgumentError in Hyrax::GenericWorks#show" is thrown out:

![image](https://user-images.githubusercontent.com/93392603/160201119-ed92cb46-82ba-4d49-903f-199c71f60338.png)

### Steps to reproduce the behavior

1. Add a work to a single-membership collection
2. Go the work edit page, go to the "Relationships" tab
3. Add the work to another single-membership collection
4. Click "Save" shows the error mentioned above.
5. Go to work list page you will see the work has already been added to the second single-membership collection.

### Related work

https://github.com/samvera/hyrax/issues/5581

**Comment by marrus-sh** [comment]
I’m not able to reproduce this in current koppie; instead it gives an expected error of `Error: You have specified more than one of the same single-membership collection type (type: Single Membership Collection, collections: My 1 Collection and My 2 Collection)` and does not modify the work. Is this already fixed?

**Comment by gamontoya** [comment]
Koppie v4.0.0

This is working as expected.

![koppie](https://github.com/samvera/hyrax/assets/4314914/7843e92b-da85-4872-875d-d56e68676008)
