### ISSUE TITLE
Creating a new User Collection returns NoMethodError (Nurax-pg)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5584]
### Descriptive summary

This occurs in nurax-pg, Hyrax 3.3. When performing QA test C_1.2, creating a new User Collection results in an application error.  

### Rationale

Users should be able to create new instances of a collection type without errors.

### Expected behavior

A successful confirmation message should display.

### Actual behavior
Application error message is shown. The collection did seem to be created in the background, but there was no confirmation success.

### Steps to reproduce the behavior

1. Dashboard > Collections > New Collection
2. Select User Collection > Create Collection
3. Supply required metadata
4. Click Save
5. See application error:

```NoMethodError in Hyrax::Dashboard::Collections#edit
Showing /opt/nurax-pg/shared/bundle/ruby/2.7.0/bundler/gems/hyrax-e3ed472b049a/app/views/hyrax/dashboard/collections/_form_branding.html.erb where line #37 raised:

undefined method `banner_info' for #<Hyrax::Forms::PcdmCollectionForm:0x0000559ac76887a8>```

**Comment by jlhardes** [comment]
Closing this issue since these steps are now successful on nurax-pg.
