### ISSUE TITLE
Transferring a work fails with NoMethodError when feature is enabled or disabled (nurax-pg) 

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5585]
### Descriptive summary

Hyrax 3.3 on nurax-pg: when the Transfer Works feature is enabled, both admin and non-admin users can see the option to transfer a work. Clicking on this action returns an application error, however. 

When the Transfer Works feature is disabled, only admin users can see the action, but when clicking on it, receive a "you are not authorized to view this page" message.

### Rationale

To maintain existing Hyrax functionality, transferring works, if enabled, should occur without errors.

### Expected behavior

If transfers are enabled, all users can transfer their works without errors. 
If disabled, only admins should be able to transfer works, and this should also execute also without errors.

### Actual behavior

Works do not seem to be transferrable under any conditions.

### Steps to reproduce the behavior

Feature is enabled:
1. As an admin, go to Settings > Features and make sure Transfer Works is enabled
2. As an admin or non-admin user, go to Dashboard > Works > Your Works and select "Transfer ownership..." from the Actions menu for one of your works
3. See NoMethodError

<img width="696" alt="Screen Shot 2022-03-28 at 3 25 21 PM" src="https://user-images.githubusercontent.com/13855987/160471964-af2458a0-516c-4062-bf10-dc8791a0b16f.png">

When feature is disabled:
1. As an admin, go to Settings > Features and make sure Transfer Works is disabled
2. As an admin user, go to Dashboard > Works > Your Works and select "Transfer ownership..." from the Actions menu for one of your works
3. Same NoMethodError occurs

### Related work

Link to related tickets or prior related work here.

**Comment by eporter23** [comment]
This is probably a duplicate for #5456

**Comment by elrayle** [comment]
Closing duplicate.  See Issue #5456.
