### ISSUE TITLE
Deposit new work through collection does not populate collection assignment in Create Work form (nurax-pg)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5586]
### Descriptive summary

As part of QA testing in Nurax-pg: Hyrax 3.3 for Collection Sharing, a user with Deposit or higher access can use the Deposit New Work through this collection option to deposit directly into a collection they have access to. The Create Work form, however, is not auto-populating the collection assignment.   

### Rationale

Per current functionality, the "deposit new work through this collection" option should automate the correct collection relationship being assigned. Users should not have to go to the Relationships tab to manually add the collection.

### Expected behavior
The collection should automatically be populated in the Relationships tab of the Create Work form, and the collection relationship should be assigned upon save.

### Actual behavior
The Relationships tab shows no collection assignment. A user must know to check the Relationships tab, search for the correct collection name, and assign it before saving.

### Steps to reproduce the behavior

1. Log in as a user with at least deposit-level access to a shared Collection
2. Go to Dashboard > Collections > Managed Collections and select a collection listed there
3. Scroll down and click the Deposit new work through this collection button
4. In the Create Work form, click the Relationships tab
5. Observe that no Collection is populated

Nurax-pg (no collection assigned):
<img width="603" alt="Screen Shot 2022-03-29 at 11 01 24 AM" src="https://user-images.githubusercontent.com/13855987/160642234-39e9f411-e78a-4321-8900-fb220938fdff.png">

Nurax-dev equivalent steps (collection already assigned):

<img width="672" alt="Screen Shot 2022-03-29 at 10 42 38 AM" src="https://user-images.githubusercontent.com/13855987/160642060-aadd1bc5-8930-4f5e-814c-bc0f094be14e.png">

### Related work

Link to related tickets or prior related work here.

**Comment by alishaevn** [comment]
this was closed when the related pr was merged. reopening for qa.

**Comment by gamontoya** [comment]
@rjkati This ticket can be closed.

- QA Testing for Hyrax
- Hyrax Version: 4.0.0
- Hyrax Branch: refs/heads/main
- Hyrax Revision: [eaf5a1f95d1d3905fbb60f5f10ca3a52c630c0a7](https://github.com/samvera/hyrax/tree/eaf5a1f95d1d3905fbb60f5f10ca3a52c630c0a7)

![yay2](https://github.com/samvera/hyrax/assets/4314914/9f14bcf0-274d-4a6f-ab51-0903e1b09bc1)
