### ISSUE TITLE
Dashboard Statistics generates NoMethodError (nurax-pg) 

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5592]
### Descriptive summary

Hyrax 3.3 for nurax-pg: when logged as in administrator, trying to view the Statistics (reports) section of the dashboard returns an error.

### Rationale

For maintaining current Hyrax functionality, admin users should be able to access the Statistics section of the dashboard.

### Expected behavior
Admin user can see summary statistics and date range selection options

### Actual behavior
NoMethodError page is shown

### Steps to reproduce the behavior

1. Login as an admin-level user
2. Go to the Dashboard and look at the Activity section 
3. Click on Statistics in the left column
4. See error page

<img width="251" alt="Screen Shot 2022-03-31 at 1 23 30 PM" src="https://user-images.githubusercontent.com/13855987/161113973-a4c34b4d-0ae3-4739-89ae-8f7bdf08b013.png">

<img width="891" alt="Screen Shot 2022-03-31 at 1 24 13 PM" src="https://user-images.githubusercontent.com/13855987/161114098-62dc28e0-0d0b-4a3a-a957-d8a08b9692fe.png">

Equivalent page in nurax-dev:
<img width="795" alt="Screen Shot 2022-03-31 at 1 25 49 PM" src="https://user-images.githubusercontent.com/13855987/161114327-91a32043-dd82-4c53-9423-1c99ba12f9fb.png">

**Comment by jlhardes** [comment]
Remaining work on [#3820](https://github.com/samvera/hyrax/issues/3820#issuecomment-880084599) - Replace calls to ActiveFedora::Base.where (removes 7 refs to ActiveFedora) might be needed for this issue

**Comment by bkiahstroud** [comment]
The errors described in this ticket seems to ultimately trace back to [Hyrax::AbstractTypeRelation](https://github.com/samvera/hyrax/blob/24f0a4fb0c36fd9f27af197e7aac74cda4600d9f/app/search_builders/hyrax/abstract_type_relation.rb). This class explicitly inherits from [ActiveFedora::Relation](https://github.com/samvera/active_fedora/blob/99ac8d1e24bf0ee1673187ae6c0f3456ae9c04c0/lib/active_fedora/relation.rb).

The purpose of the `Hyrax::AbstractTypeRelation` class, as far as I can tell, is primarily scoping Solr queries. The only thing I'm not sure about is `DummyModel.delegated_attributes`; I'm not sure what that's used for, but either way it seems very ActiveFedora-specific. 

**I think this whole file could be refactored to use Valkyrie query services.**

An observation I had was that a lot of code that uses `AbstractTypeRelation` and its subclasses hasn't been touched in several years, so there might be a case for just removing this logic if it isn't needed anymore. I don't personally have enough context to say definitively though.

Any guidance on how to move forward is appreciated.

**Comment by dlpierce** [comment]
I agree, it could be refactored to use valkyrie. The WorkRelation subclass is used in a variety of places in Hyrax, so not something that can be retired. Creating a full valkyrie refactor that includes all of the features of AF::Relation is probably not needed if we can identify which methods are actually used. That seems to be `#search_in_batches`, `#find`, `#search_with_conditions`, `#find_each`, `#where` ?

WorkQueryService uses WorkRelation and has WorkResourceQueryService as a valkyrie replacement. Perhaps the other uses can be substituted similarly? Another thought is can some valkyrie custom queries be the replacement?

I think delegated_attributes is a list of methods that can be set by the model that should be listed and accessible in the same way as standard model attributes.

**Comment by crisr15** [comment]
This ticket is on hold until the GA4 work is complete, as it is currently not working in hyrax main.

**Comment by jlhardes** [comment]
Viewing Statistics as an admin from the Dashboard is working in Hyrax 5.0.0 on both https://dev.nurax.samvera.org/ and https://pg.nurax.samvera.org/. There are no errors and date range filters work as well.
