### ISSUE TITLE
Add this Collection to another collection Fails with NoMethodError in Hyrax::Dashboard::NestCollectionsController#create_relationship_within

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5595]
### Descriptive summary

On nurax-pg, with 2 nestable collections of the same nestable collection type, adding a collection as a subcollection to another collection fails with "NoMethodError in Hyrax::Dashboard::NestCollectionsController#create_relationship_within"

<img width="1356" alt="Screen Shot 2022-04-06 at 3 48 51 PM" src="https://user-images.githubusercontent.com/3440166/162058918-6f4f001a-3b4a-47ca-a1a0-2cbee6bf5d32.png">

### Steps to reproduce the behavior

* From Dashboard -> Collections create two collections of type "nesting only"
* From Dashboard -> Collections, click the title of one of the collections
* Click Add to collection button (beside Edit and Delete buttons)
* Verify the Add to collection button is disabled until a selection is made
* Select the other collection from the list of potential parents
* Click Add to collection (this is where error is encountered as shown in screenshot)

**Comment by gamontoya** [comment]
@cjcolvar I'm seeing the same reported behavior.

![5595](https://user-images.githubusercontent.com/4314914/189990250-ec645475-7b25-4833-b16d-6960f61ba9e5.png)

**Comment by jlhardes** [comment]
Verified this is working locally on koppie and this is also working on nurax-pg. Closing this issue!
