### ISSUE TITLE
Add New or Edit Work - Saving your work message appearing too soon

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5618]
### Descriptive summary

As soon as a new work is added or a work is being edited, the "Saving your work. This may take a few moments" message is displaying, even though the Save button hasn't been clicked (or can't be clicked because the Deposit Agreement isn't checked).

![Screen Shot 2022-05-11 at 9 25 59 AM](https://user-images.githubusercontent.com/3440166/167861149-24ad4cc1-7419-4c95-9f8f-b087755f141b.png)

### Expected behavior

The "Saving your work..." message does not appear until the Save button is actually clicked.

### Steps to reproduce the behavior

1. Add a new work or Edit a current work
2. See "Saving your work..." message showing below Save button

**Comment by marrus-sh** [comment]
In the old bootstrap, there was a `.hidden` class (i think that is the right name) which was used extensively in Hyrax. In Bootstrap 4, the HTML `hidden` attribute should be used instead. My guess is that this is a case of the former not getting switched over to the latter (and thus the message is displaying all the time).

**Comment by bwatson78** [comment]
Issue fixed by commit: [23af876](https://github.com/samvera/hyrax/commit/23af876b44726fd3f11f9ad972dca8911b61bac9)

**Comment by jlhardes** [comment]
The "Saving your work..." message now only appears on `bl7bootstrap4` when you click the Save button (when creating) or the Save changes button (when editing).
