### ISSUE TITLE
Search results facets not showing

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5620]
### Descriptive summary

Search results page does not provide any facets along left side for filtering results.

![Screen Shot 2022-05-11 at 1 22 35 PM](https://user-images.githubusercontent.com/3440166/167909863-2eee571e-440f-498c-bca4-dc7ff40a4801.png)

### Expected behavior

Search results in Hyrax should display "Limit your search" list of expandable/collapsible facets:

![Screen Shot 2022-05-11 at 1 25 44 PM](https://user-images.githubusercontent.com/3440166/167910133-2542a6f0-5393-4ea8-9f68-c19b42054432.png)

### Steps to reproduce the behavior

1. From home page in Hyrax running from `bl7bootstrap4` branch
2. Conduct a search that brings back results or just click the "Go" button in the search form without a search term. 
3. See search results page with no "Limit your search" facet options

**Comment by eporter23** [comment]
@jlhardes In Mac safari 15.4 I see the facets, but they are displaying in responsive mode.
<img width="1251" alt="Screen Shot 2022-05-13 at 10 19 07 AM" src="https://user-images.githubusercontent.com/13855987/168303975-9546c36c-e309-4a10-be09-35d26ba4ad58.png">

**Comment by CB987** [comment]
Same in Firefox: I see the Limit your Search, and hamburger menu, at the bottom  of the search results instead of at the left in a sidebar
![Screen Shot 2022-05-18 at 1 46 10 PM](https://user-images.githubusercontent.com/43180845/169108569-eab2cbb0-7557-4d3b-a5c9-c7d1f1fa28b1.png)
.

**Comment by CB987** [comment]
I have at least gotten the facets sidebar to the left of the searchbar. Now to work on expanding. 
![Screen Shot 2022-05-19 at 8 16 51 AM](https://user-images.githubusercontent.com/43180845/169291617-493366e2-fabd-4ebc-a4b2-1a1d63082e09.png)

**Comment by CB987** [comment]
#5656 is first steps towards solving this.

**Comment by bwatson78** [comment]
This should be resolved in the latest build.
