### ISSUE TITLE
View Collection Page list options styling

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5630]
### Descriptive summary

Hyrax 3 Blacklight 7/Bootstrap 4 work: when viewing the Admin/Dashboard view of a Collection, the options (List, Gallery, Masonry, etc.) to change the layout of the works list needs restyling.

### Rationale

Design continuity with current Hyrax 3x series

### Expected behavior
The view options should appear as a small set of buttons with a light background and no visible text label until a user hovers over the element. 
Sizing and margins for the thumbnail in the works list also need refinement for easier scanning.

<img width="256" alt="Screen Shot 2022-05-26 at 11 39 28 AM" src="https://user-images.githubusercontent.com/13855987/170524082-656c0028-e25f-4097-90a0-e6f7d682a67b.png">

<img width="176" alt="Screen Shot 2022-05-26 at 11 42 38 AM" src="https://user-images.githubusercontent.com/13855987/170524199-4b72844d-456a-4775-ad87-dc18e08edbb9.png">

### Actual behavior

Buttons appear with dark background, increased size, and text. The thumbnail is also oversized and butts up against the work title.
<img width="619" alt="Screen Shot 2022-05-13 at 2 51 42 PM" src="https://user-images.githubusercontent.com/13855987/168351087-3ffda82f-9ebc-4afa-a9da-cede66abb86f.png">

### Steps to reproduce the behavior

1. Go to Dashboard > Collections
2. Open a Collection with more than one work
3. See the list view options layout

### Related work

Link to related tickets or prior related work here.

**Comment by eporter23** [comment]
@jlhardes new blacklight 7/bootstrap css issue

**Comment by jlhardes** [comment]
Testing locally with `bl7boot4rails6` build, the background for the non-selected options is light but the selected option is still dark. Is there another place to update background color or is this the way it looks now? I am not sure if it is necessary for this to look exactly the way it did before so I am open to considering this issue done. @adamjarling or @mathewjordan do you have thoughts for this?

![Screen Shot 2022-06-13 at 3 45 49 PM](https://user-images.githubusercontent.com/3440166/173432818-bb34d8cb-b0b0-4c0e-a2b2-a61854a07c62.png)

**Comment by adamjarling** [comment]
@jlhardes I'll take a look

**Comment by jlhardes** [comment]
The View Collection Page list option buttons are updated in `bl7boot4rails6` local testing. The end user search results list option buttons are still showing dark backgrounds on the selected button but that can be a separate issue. Closing this issue.
