### ISSUE TITLE
Review and Approval menu doesn't expand

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5634]
### Descriptive summary

For a Work under review, Review and Approval menu does not expand.

### Expected behavior

Review and Approval menu should expand to offer options to request changes or add comments or approve.

### Actual behavior

<img width="1296" alt="reviewAndApproval" src="https://user-images.githubusercontent.com/3440166/168430977-0447619c-5aed-4c90-aaf8-5c49ffaf5b68.png">

### Steps to reproduce the behavior

1. Log in as an admin user, create a one-step deposit admin set (create new collection of type "Admin Set", under Workflow tab select "One-step mediated deposit workflow")
2. Log in as non-admin user and submit new work to the one-step workflow admin set - set to public
3. Log in as an admin user and go to Dashboard: Tasks: Review Submissions
4. Click on work title, see "Review and Approval"
5. Click on "Review and Approval" and nothing happens (should expand open)

**Comment by bwatson78** [comment]
Commit [07bee14](https://github.com/samvera/hyrax/commit/07bee14d53fe0ed51e94ba4514ce6a8eb7711761) fixes this issue.

**Comment by jlhardes** [comment]
Rebuild 'bl7bootstrap4` locally and see Review and Approval menu expanding now. Experiencing error "Ldp::Gone in Hyrax::WorkflowActionsController#update" when approving a Work and Review and Approval menu still shows even when Work is approved and labeled Deposited. Something isn't getting cleared out correctly but this particular issue is fixed. Will test again and open a new issue for new errors.
