### ISSUE TITLE
Notification badge number indicator not displaying well

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5640]
### Descriptive summary

When there are notifications, the number indicator doesn't have enough padding around it.

### Expected behavior

This is the number indicator as it appears on nurax-dev:

<img width="536" alt="Screen Shot 2022-05-14 at 11 56 24 AM" src="https://user-images.githubusercontent.com/3440166/168439428-08be427c-2cdb-4fb1-b13f-365e93c6a37d.png">

### Actual behavior

This is the number indicator as it appears on locally built `bl7bootstrap4` branch:

<img width="364" alt="Screen Shot 2022-05-14 at 12 03 23 PM" src="https://user-images.githubusercontent.com/3440166/168439687-e253eba9-a3cc-41f0-b3cd-1e9195df9eae.png">

### Steps to reproduce the behavior

1. Log in as admin user
2. Do an action that creates a notification, for example - Under Dashboard: Your Activity: Manage Proxies, add another user as a proxy
3. Click on home page and see notification badge number appear without enough padding for background color

**Comment by bwatson78** [comment]
Commit [0f75e2d](https://github.com/samvera/hyrax/commit/0f75e2d58dca16f73a489091a401e3414424e151) fixes this.

**Comment by jlhardes** [comment]
This is fixed in the `bl7bootstrap4` branch.
