### ISSUE TITLE
File Manager - Save changes not working

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5642]
### Descriptive summary

Save button on File Manager does not seem to be activating and changes are not saved.

### Expected behavior

Save button saves any changes made in File Manager

### Actual behavior

No changes are saved and viewing File Manager again shows files in same order with no updates

### Steps to reproduce the behavior

1. Log in and view a Work with multiple files that you can edit
2. Click File Manager from Work view
3. Reorder a file by dragging and dropping
4. Click Save button in Toolbar (nothing seems to happen or load/process)
5. View Work and see no files have changed order
6. Click File Manager again and files load in previous order and don't show any reordering

**Comment by jlhardes** [comment]
Just a note that I do wonder if this is an issue in `main` and not just this branch? I can't test on nurax-dev since it isn't fully functioning right now but I haven't had a chance to test locally off of a `main` build. If it is a problem there this could be something that is worked on outside of the Rails upgrade work.

**Comment by bwatson78** [comment]
@jlhardes I've narrowed it down to a jQuery method that hasn't worked since version 3.0, so that maybe a reason this may not be working anywhere.

**Comment by jlhardes** [comment]
If it isn't working outside of the branch, then I will remove the branch label and file it as a bug for the HMWG. It is off the Rails upgrade To Do list!

**Comment by jlhardes** [comment]
I just tried locally from `main` and the reorder is working for me there so I think this is something specific to the `bl7bootstrap4` branch.

**Comment by bwatson78** [comment]
I'm back on the case!
