### ISSUE TITLE
Logout does not function as expected (Blacklight 7 branch/docker environment)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5644]
### Descriptive summary

In the Hyrax 3.x Blacklight 7/Bootstrap 4 branch, running on a local docker instance, the application does not allow me to full log out and log back in as a different user. 

### Rationale

Users should be able to logout, especially for testing purposes, in order to see different application states for logged in or not-logged in sessions.

### Expected behavior

When I click on logout, the application should return me to the homepage, and I should not see my user name in the upper left corner. I should then see a green banner confirming the logout completed.

<img width="1436" alt="Screen Shot 2022-05-18 at 9 37 28 AM" src="https://user-images.githubusercontent.com/13855987/169052178-24c219bf-a515-4e90-9cf4-9aa6bc354812.png">

### Actual behavior

I am returned to the homepage, where a gray alert banner appears saying "user does not exist". My username also continues to display as active in the upper right corner.

<img width="932" alt="Screen Shot 2022-05-18 at 9 35 58 AM" src="https://user-images.githubusercontent.com/13855987/169051788-a8d56272-2ef2-4c85-abc0-64976306bd50.png">

### Steps to reproduce the behavior

1. Start a new session and login as an existing user (e.g. admin@example.com)
2.  Click on your username in the upper right corner of the interface, and select Logout from the dropdown. 
3. See the gray alert message noted above.

### Related work

Link to related tickets or prior related work here.

**Comment by eporter23** [comment]
@jlhardes another Blacklight 7 branch issue I've encountered while testing.

**Comment by marrus-sh** [comment]
@eporter23 I think this is a duplicate of #5354; we think it is a user session issue (maybe not related to the upgrade) but weren’t able to determine exact steps to reproduce.

**Comment by eporter23** [comment]
Thanks @marrus-sh, I will come this one but let me know if you need me to document more details about the conditions in which I encountered this.
