### ISSUE TITLE
Edit Collection: Discovery Tab Layout 

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5652]
### Descriptive summary

Hyrax 3.x: Blacklight 7/Bootstrap 4 upgrade branch testing

In the Edit Collection form > Discovery tab, the 3 radio button options  for visibility are difficult to read because they have lost their line breaks: should be listed vertically. 

General note: all of the Collection Edit tabs need layout refinements for tab styling, padding, margins, etc

### Rationale

Users should easily be able to scan the Visibility options.

### Expected behavior
Example from Nurax-dev:
<img width="977" alt="Screen Shot 2022-05-19 at 10 58 26 AM" src="https://user-images.githubusercontent.com/13855987/169327437-2e091e65-1a35-4750-8809-bad67031c77e.png">

### Actual behavior

<img width="892" alt="Screen Shot 2022-05-19 at 10 59 16 AM" src="https://user-images.githubusercontent.com/13855987/169327626-0271c493-8d74-4b81-ac8b-ee3d5ca7f18f.png">

### Steps to reproduce the behavior

1. Go to Dashboard > Collections
2. Open a Collection you have edit/Manage access to
3. Edit the Collection and select Discovery
4. Note the radio button layout

### Related work

Link to related tickets or prior related work here.

**Comment by eporter23** [comment]
@bwatson78 I'm still seeing the same behavior in Safari Mac and Chrome for the Edit Collection > Discovery tab radio buttons layout after rebuilding this afternoon.
<img width="1169" alt="Screen Shot 2022-05-26 at 4 35 45 PM" src="https://user-images.githubusercontent.com/13855987/170575867-772d5db6-95f7-4804-b31a-158f4f3ad2c7.png">

**Comment by bwatson78** [comment]
Sorry, got sidetracked with the blue top border. Commit [6cbe44c](https://github.com/samvera/hyrax/commit/6cbe44cf6e3000a3ef3c5d910455ded99c336fe9) fixes this.

**Comment by bwatson78** [comment]
![Screen Shot 2022-06-06 at 4 21 30 PM](https://user-images.githubusercontent.com/18330149/172242159-291260c6-5066-487f-8c1c-69360160379e.png)

**Comment by jlhardes** [comment]
This is fixed in local build of `bl7boot4rails6`!
