### ISSUE TITLE
Review and Approval form does not load when clicked from View Work page

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5653]
### Descriptive summary

In the Hyrax 3.x Blacklight 7 upgrade branch, when a work requires approval, the Review and Approval banner appears, but the form elements do not load when clicked.

### Rationale

The submitter and the approver need to use the form in order to complete the workflow. At present, it is not accessible.

### Expected behavior

A user can click on the orange banner to reveal a form.
<img width="1290" alt="Screen Shot 2022-05-20 at 9 16 25 AM" src="https://user-images.githubusercontent.com/13855987/169545664-6115085c-fbb7-4624-8ae3-11982af152c0.png">

### Actual behavior

The banner displays, but nothing happens when it is clicked.

<img width="644" alt="Screen Shot 2022-05-20 at 10 08 43 AM" src="https://user-images.githubusercontent.com/13855987/169545831-27752907-02d1-4ef4-87ec-e3c239aa5a4f.png">

### Steps to reproduce the behavior

1. Create a new work and deposit it into an Admin Set that requires a one-step approval
2. Go to the work that has been submitted3. 
3. See the orange Review and Approval banner and click on it 
4. Observe that the banner does not expand to reveal a form
### Related work

Link to related tickets or prior related work here.

**Comment by eporter23** [comment]
@jlhardes another Blacklight 7 upgrade issue.

**Comment by jlhardes** [comment]
I think this is a duplicate issue of #5634?

**Comment by eporter23** [comment]
Sorry, closing this one.
