### ISSUE TITLE
Margins/distribution of facet values and counts

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5662]
### Descriptive summary

Hyrax 3.x Blacklight 7/Bootstrap 4 upgrade branch
When using filters in Dashboard > Works or Collections, the counts shown in dropdowns aren’t evenly spaced relative to their labels, which makes them hard to read.

Similar behavior also occurs on main search Facets, when a facet is expanded.

### Rationale

The width of the label container should be consistent relative to positioning of the count for that label, so that it is easy for a user to scan the information. 

### Expected behavior

<img width="393" alt="Screen Shot 2022-05-26 at 2 17 43 PM" src="https://user-images.githubusercontent.com/13855987/170550895-2f2f1e29-2894-45fb-99a8-d2ea9e93e7f5.png">

<img width="279" alt="Screen Shot 2022-05-26 at 2 16 50 PM" src="https://user-images.githubusercontent.com/13855987/170550790-74ed2eb6-16b1-43c2-b19e-01d21ef4e421.png">

### Actual behavior

<img width="473" alt="Screen Shot 2022-05-26 at 2 15 33 PM" src="https://user-images.githubusercontent.com/13855987/170550627-7d82f1cd-61a0-40ea-abb1-9fb2ec16165d.png">

<img width="326" alt="Screen Shot 2022-05-26 at 2 15 49 PM" src="https://user-images.githubusercontent.com/13855987/170550646-2c874d19-b06f-4ab5-8eb4-c678a742c2fb.png">

### Steps to reproduce the behavior

1. Load the most recent Blacklight 7/Bootstrap 4 branch
2. Go to Dashboard > Collections and select a filter (e.g. Collection Type) to expand it.
3. See the alignment of the counts vs. labels. 

You can also observe this for Dashboard > Works and when using facets in the search results.

### Related work

Link to related tickets or prior related work here.

**Comment by bwatson78** [comment]
Resolved with commits 6b1be02 and ce23062.

**Comment by jlhardes** [comment]
This is fixed in local testing of `bl7boot4rails6` branch.
