### ISSUE TITLE
Collection relationships display twice on View Work page [Rails 6 testing]

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5668]
### Descriptive summary

Hyrax 3.4.1 main: if a work is part of a Collection, this relationship is displaying twice instead of once on the View Work page.

### Rationale

When a work is assigned to a collection, this relationship should only display once.

### Expected behavior

When a work is assigned to a given collection, that relationship should only display once from the Relations section of the View Work page. 

### Actual behavior

The collection relationship is displayed twice on the work detail page ([see Nurax example](https://nurax-dev.curationexperts.com/concern/generic_works/ht24wj68c?locale=en)). 
<img width="560" alt="Screen Shot 2022-06-08 at 2 14 23 PM" src="https://user-images.githubusercontent.com/13855987/172688110-f351405f-e673-478b-818a-d4b9b5c0b8d2.png">

It does not, however, display twice from Edit Work > Relationships > Collections.

### Steps to reproduce the behavior

1. Go to a work with no collections assigned
2. Edit the work, select the Relationships tab, and assign the work to a Collection. 
3. Save the changes to the work, and then view the Work. 
4. See the Collection listed twice in the Relations section. 

### Related work

Link to related tickets or prior related work here.

**Comment by bwatson78** [comment]
I am seeing this same behavior in an environment built off of main.
