### ISSUE TITLE
Add to Collection modal layout (Bootstrap 4)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5688]
### Descriptive summary

Hyrax 3.x branches using Bootstrap 4 - in some circumstances, the Add to Collection modal layout is distorted.

### Rationale

Design continuity and ease of use

### Expected behavior

From Nurax:
<img width="670" alt="Screen Shot 2022-06-14 at 2 41 13 PM" src="https://user-images.githubusercontent.com/13855987/173664871-03dd992f-6aad-4bb3-8e53-7b12060fb083.png">

### Actual behavior

<img width="674" alt="Screen Shot 2022-06-14 at 2 41 42 PM" src="https://user-images.githubusercontent.com/13855987/173664943-b2c0ac90-44a5-4daf-8d43-01a562a367da.png">

### Steps to reproduce the behavior

1. Make sure you have a work that is not in a collection, and a Collection that you have at least Deposit level access to.
2. Navigate to Works > Select the checkbox next to the work, and click Add to Collection
3. Note the modal layout issues

The drop-down issue may only occur when there are few collections to select from, because the user is presented with a dropdown instead of a lookup field. There are consistent issues with the header elements alignment even if the lookup is provided.

### Related work

Link to related tickets or prior related work here.

**Comment by eporter23** [comment]
Looks resolved in the latest build!

**Comment by jlhardes** [comment]
Testing on nurax-dev and locally in Hyrax 4 beta2 is showing this issue. Reopening to address for Hyrax 4 release.

![Screen Shot 2022-11-02 at 9 18 08 AM](https://user-images.githubusercontent.com/3440166/199500160-e076b4b1-05f0-461c-bbce-3e1ae80141e3.png)

**Comment by jlhardes** [comment]
This is fixed on nurax-dev!
