### ISSUE TITLE
Dashboard pages with white tabs background

### ISSUE THREAD

**Issue by adamjarling** [samvera/hyrax#5704]
### Descriptive summary

On a few pages (Dashboard > Manage Embargos; Dashboard > Manage Leases), there is white background color behind the tabs, which makes a little hard to distinguish.

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/3020266/174150871-e6eb80b3-4d9b-4c39-9a14-e7da141939ca.png">

### Expected behavior
Tabs background color is transparent

### Actual behavior
Tabs background color is white (same as tabs color)

**Comment by jlhardes** [comment]
Testing locally with `bl7boot4rails6` I am not seeing the tab background color as white, it does seem to be transparent (Chrome and Safari):

<img width="1480" alt="Screen Shot 2022-06-16 at 4 19 01 PM" src="https://user-images.githubusercontent.com/3440166/174156787-61a9f162-4cb0-4df8-b9e1-49f81dda7f8f.png">

I didn't rebuild but I did just grab the latest from that branch and then bring the instance up. @rjkati can you test how the tabs are looking for you?

**Comment by eporter23** [comment]
Also seeing some of this in the View Works tabs #5708 .

**Comment by eporter23** [comment]
Also seeing this in Admin Set creation and editing: #5713.

**Comment by eporter23** [comment]
Haven't created an issue for this yet, but this also occurs when editing Collection Types:
<img width="655" alt="Screen Shot 2022-06-17 at 12 52 24 PM" src="https://user-images.githubusercontent.com/13855987/174342614-bca46d96-cace-46cd-9eb8-3d407fcc664c.png">

**Comment by eporter23** [comment]
@jlhardes looks good to me now!
