### ISSUE TITLE
Dashboard > Works listing layout issues (Bootstrap 4)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5708]
### Descriptive summary

In Hyrax 3.x branches using Bootstrap 4, the Works listing needs some cleanup to be consistent with Collections listing.

### Rationale

Design continuity and ease of use

### Expected behavior

Tab styling should be consistent with Collections
Margins/padding between thumbnails and titles should be consistent with Collections

Nurax dev: Works listing
<img width="659" alt="Screen Shot 2022-06-17 at 10 23 22 AM" src="https://user-images.githubusercontent.com/13855987/174317412-e714df5e-975f-4276-a00f-c59826fbd492.png">

Bootstrap 4/Rails 6 branch: Collections listing
<img width="678" alt="Screen Shot 2022-06-17 at 10 22 47 AM" src="https://user-images.githubusercontent.com/13855987/174317314-13925053-7c4c-41e5-86fc-e239d0fdc123.png">

### Actual behavior

Tab styling and thumbnails

<img width="674" alt="Screen Shot 2022-06-17 at 10 22 19 AM" src="https://user-images.githubusercontent.com/13855987/174317212-32124e49-6164-4d74-873c-5d67208b9497.png">

### Steps to reproduce the behavior

1. Go to Dashboard > Works
2. View the tabs and works listing

### Related work

Link to related tickets or prior related work here.

**Comment by jlhardes** [comment]
These issues are fixed testing locally with `bl7boot4rails6` branch.
