### ISSUE TITLE
View Work > Citations menus 

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5709]
### Descriptive summary

Include what version of Hyrax relates to this issue (7.x, 6.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Rationale

Design continuity and ease of use

### Expected behavior

<img width="306" alt="Screen Shot 2022-06-17 at 10 28 11 AM" src="https://user-images.githubusercontent.com/13855987/174318324-d9db7920-6290-4559-963c-d87df2380304.png">

### Actual behavior

<img width="280" alt="Screen Shot 2022-06-17 at 10 26 38 AM" src="https://user-images.githubusercontent.com/13855987/174318116-4431680b-47dc-447c-a8de-25d0fd1cf240.png">

### Steps to reproduce the behavior

1. View any work
2. Look beneath the Universal Viewer and see the Citations menus

### Related work

Link to related tickets or prior related work here.

**Comment by rjkati** [comment]
Citations menus now appear side-by-side with padding in both Firefox and Chrome

![citationsmenu](https://user-images.githubusercontent.com/32644254/174358549-e77732ba-bdd1-47f5-9468-37fa18f3efef.PNG)
