### ISSUE TITLE
Dashboard sidebar hover/active states (Bootstrap 4)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5711]
### Descriptive summary

In Hyrax 3.x branches using Bootstrap 4, the active and hover indicators in the sidebar have poor contrast.

### Rationale

Design continuity, ease of use

### Expected behavior

Light gray background combined with black text
<img width="516" alt="Screen Shot 2022-06-17 at 11 11 25 AM" src="https://user-images.githubusercontent.com/13855987/174326555-a9fd25ba-7a0c-4a97-80a5-ad558dd65e2d.png">

### Actual behavior

Black text with no light gray background
<img width="420" alt="Screen Shot 2022-06-17 at 11 11 52 AM" src="https://user-images.githubusercontent.com/13855987/174326645-6afb1673-295a-44c8-900f-5f3480135776.png">

### Steps to reproduce the behavior

1. Login to the Dashboard
2. Hover and click on any of the options (especially expanding menus)

### Related work

Link to related tickets or prior related work here.

**Comment by bwatson78** [comment]
Commit [`8f110bc`](https://github.com/samvera/hyrax/commit/8f110bc56dba7e628bbdd95b652ceecbc5ba2796) fixes this task.

**Comment by eporter23** [comment]
@bwatson78 @jlhardes looks great! Closing this one.
