### ISSUE TITLE
Facets: "More" modal behavior (Bootstrap 4) 

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5714]
### Descriptive summary

In hyrax 3.x branches using Bootstrap 4, the option to see more values from a given facet does not behave as expected.
 
### Rationale

Design continuity and usability

### Expected behavior

"More" modal appears as a constrained overlay above the search results page

<img width="652" alt="Screen Shot 2022-06-17 at 1 34 08 PM" src="https://user-images.githubusercontent.com/13855987/174349534-4a260cb8-1ff4-4901-9390-31264b85f739.png">

### Actual behavior

"More" contents replace the entire content of the screen. You cannot "close" this and have to use the Back button to get back to the search results.

<img width="675" alt="Screen Shot 2022-06-17 at 1 35 02 PM" src="https://user-images.githubusercontent.com/13855987/174349639-e6e3ba78-a01e-4591-9d7e-4058250ae8e6.png">

### Steps to reproduce the behavior

1. Do an empty search (blank search box > Go) or a search that produces many results
2. Click on a facet that contains more than the default number of visible values, and click More 
3. Observe the behavior that occurs

### Related work

Link to related tickets or prior related work here.

**Comment by abelemlih** [comment]
@jlhardes  @eporter23 PRs #5729 and #5731 fix the facet modals for both the catalog and the admin dashboard, let me know if you encounter any other issues during QA.

**Comment by eporter23** [comment]
Looks great @abelemlih and @jlhardes! Closing.

**Comment by jlhardes** [comment]
The facet modals look great to me in both the catalog and the admin dashboard on `bl7boot4rails6`.
