### ISSUE TITLE
Settings > Pages and Content Blocks: form buttons (Bootstrap 4)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5724]
### Descriptive summary

Hyrax 3.x branches using Bootstrap 4: in the Settings > Pages and Settings Content Blocks forms, the Save button needs better contrast for legibility. A similar fix was applied for the Admin Sets edit forms: #5713

### Rationale

Legibility of button text for usability

### Expected behavior

Button text has strong contrast against background
<img width="1178" alt="Screen Shot 2022-06-22 at 1 54 18 PM" src="https://user-images.githubusercontent.com/13855987/175104481-af80f484-5d83-4ef2-998e-cd6ede8b3854.png">

### Actual behavior
<img width="671" alt="Screen Shot 2022-06-22 at 1 55 15 PM" src="https://user-images.githubusercontent.com/13855987/175104604-6cfbaece-078d-4e36-9eea-7565c83af22f.png">

<img width="673" alt="Screen Shot 2022-06-22 at 1 55 20 PM" src="https://user-images.githubusercontent.com/13855987/175104627-6d20b023-c70f-4d85-a0b7-7c7e168b8711.png">

### Steps to reproduce the behavior

1. Login as an admin user
2. Go to Settings > Pages or Settings > Content Blocks and look at the Save buttons in the forms.

### Related work

Link to related tickets or prior related work here.

**Comment by bwatson78** [comment]
Commit [`87409ad`](https://github.com/samvera/hyrax/commit/87409ad00918919b802dfaa847e2aeed0ee038dd) fixed this issue
![Screen Shot 2022-06-22 at 3 14 54 PM](https://user-images.githubusercontent.com/18330149/175119721-b5dae11f-8f0c-4038-81ed-cd377656acf5.png)
.

**Comment by jlhardes** [comment]
I am seeing the same thing. Content Blocks still needs an update to the Save Changes button.

**Comment by eporter23** [comment]
This is resolved now.
