### ISSUE TITLE
Works view page - Items Actions - Download not working

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5794]
### Descriptive summary

The Download option on the drop-down menu for Items on work view page is not working. Selecting Download in drop-down menu gives rise to ActiveFedora::ObjectNotFoundError in Hyrax::DownloadsController#show.

### Expected behavior

File should download 

### Actual behavior

New tab opens with error message:

![Screen Shot 2022-08-12 at 9 52 16 AM](https://user-images.githubusercontent.com/3440166/184367744-86f64c65-098b-4b90-b609-f310ae1f2656.png)

### Steps to reproduce the behavior

1. Log in to user dashboard, click work name to display work view page.
2. In the section of "Items", find the dropdown menu "Select an action" and select Download from the drop-down menu and click.
3. You will see an error like ActiveFedora::ObjectNotFoundError in Hyrax::DownloadsController#show

### Related work

#5136  (epic with history of previous work and testing of Works)
#5138 (epic for loading a file and being able to download it from a Work)
#5575 Issue for Edit and Versions options in Items Actions drop-down menu
#5795 Issue for Delta option in Items Actions drop-down menu

**Comment by alishaevn** [comment]
this ticket was auto closed when the attached pr was merged. reopening so that it can be qa'd.

cc: @dlpierce

**Comment by gamontoya** [comment]
@rjkati This ticket can be closed. Actions --> Download is working
