### ISSUE TITLE
Works view page - Items Actions - Delete not working

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5795]
### Descriptive summary

The Delete option on the drop-down menu for Items on work view page is not working. Selecting Delete in drop-down menu gives rise to ArgumentError in Hyrax::GenericWorks#show.

### Expected behavior

Selecting delete from Items Actions drop-down menu should remove the file from the Work and reload the Work view page.

### Actual behavior

Following error loads:

![Screen Shot 2022-08-12 at 9 59 32 AM](https://user-images.githubusercontent.com/3440166/184372222-21a1b48d-cb8d-4f39-a2a9-48b85727f8ad.png)

### Steps to reproduce the behavior

1. Log in to user dashboard, click work name to display work view page.
2. In the section of "Items", find the dropdown menu "Select an action" and select Delete from the drop-down menu and click OK at prompt to confirm delete action.
3. You will see an error like ArgumentError in Hyrax::GenericWorks#show

### Related work

#5136 (epic with history of previous work and testing of Works)
#5794 Issue for Download option in Items Actions menu
#5575 Issue for Edit and Versions options in Items Actions menu

**Comment by acklose** [comment]
@jlhardes This is working now in Nurax PG. I followed the steps to delete two generic works. The inteface gave a message "Batch delete complete" after the action was done.

<img width="965" alt="Nurax-PB_BatchDelete_2022-09-15" src="https://user-images.githubusercontent.com/26173627/190508699-72bcf370-984f-4be5-bf93-ec40578f47e6.png">

**Comment by jlhardes** [comment]
@acklose that test you ran on nurax-pg is testing deleting the entire work from the Works list on the Dashboard. This issue is about deleting a single file from within a Work. When viewing a Work, the files are listed under a section on the Work view page called Items and each file listed there has a drop-down of of actions. Delete is the action from that drop-down that this issue is addressing.

**Comment by gamontoya** [comment]
@jlhardes This is **DONE**. Confirming that it works on nurax-pg.
