### ISSUE TITLE
File Details page not accessible

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5796]
### Descriptive summary

Trying to reach File Details page from Items section on Work view results in the Hyrax home page or Log in page loading with the message "You are not authorized to access this page." regardless of being logged in or not.

### Expected behavior

For publicly available work (or work that can be accessed when logged in), users should be able to click on Item Title link and see File Details page.

### Actual behavior

When logged in, user is directed to Hyrax home page with alert message showing "You are not authorized to access this page.":

![Screen Shot 2022-08-12 at 10 29 48 AM](https://user-images.githubusercontent.com/3440166/184377263-71c06544-5aa5-4fce-a0a9-1a7ac97843aa.png)

### Steps to reproduce the behavior

1. From Hyrax home page, click Recently Uploaded tab and click on Work title from list (can be logged in or not)
2. This is publicly available item on nurax-pg with file attached: https://nurax-pg.curationexperts.com/concern/images/523b0cc8-6176-4d68-aa1e-9f6bd667ffd2?locale=en
3. Under Items section of Work view, click Title link for file in list. 
4. Be redirected to Home page or Log in page with alert message displaying: "You are not authorized to access this page."

### Related work

#5136 (epic with history of previous work and testing of Works)

**Comment by gamontoya** [comment]
@rjkati This ticket can be closed. I can not replicate the reported error on nurax-pg `Hyrax Version: 4.0.0`
