### ISSUE TITLE
Show all collection descriptive metadata

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5798]
### Descriptive summary

Descriptive metadata fields for collections are not all showing in public view on valkyrized Hyrax. It might be that only fields that are set to be indexed appear on the show page.

### Rationale

All descriptive metadata for collections should appear if it is filled in. Descriptive metadata fields on collection are the same as on Works by default and while this may not be how collection metadata often works, it seems the best way to manage descriptive metadata for application development purposes.

### Expected behavior

All metadata fields that can be edited on Description tab of Collection will show on public view of collection (show page).

### Actual behavior

Only Title, Description, Resource type, Creator, Keyword, Date Created, Subject, and Related URL are showing. 

### Steps to reproduce the behavior

1. As a logged in user, create a new User Collection
2. On Description tab, fill in metadata on all fields 
3. Click Save changes
4. Click Cancel to view Collection in dashboard (see only fields listed above)
5. Click Public view of Collection and see only fields listed above

### Related work

PR [#5157](https://github.com/samvera/hyrax/pull/5157) - Update PcdmCollection metadata to match existing ::Collection metadata
Issue #5494 - Edit collection only shows title field for Hyrax::PcdmCollection (closed)
Issue #5799 - Enable Geonames functionality for Location field in Collections

**Comment by rjkati** [comment]
Verified that collection descriptive metadata now displays in public view on nurax-pg

![collection_metadata](https://github.com/samvera/hyrax/assets/32644254/99f388d3-85e0-4fce-97a6-50471d617a27)
