### ISSUE TITLE
Enable Geonames functionality for Location field in Collections

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5799]
### Descriptive summary

Geonames is not connected to Location field in Description tab on Collections yet so Location metadata cannot be saved.

### Expected behavior

Location should function in collection editing on valkyrized hyrax.

![55257372-ec633f80-521c-11e9-83b9-4cd1da1b522d](https://user-images.githubusercontent.com/3440166/184966729-1af19629-347e-433c-9cd7-6e4cfdd92126.png)

### Actual behavior

Location field is not initially showing in Description tab and when additional form field is added, is not offering results from Geonames and no value can be saved.

### Steps to reproduce the behavior

1. As a logged in user, create a new User Collection
2. On Description tab, click Additional Fields and scroll down to Location
3. See there is no form field showing for Location
4. Click Add another Location and form field shows
5. Try searching for a location and no results are offered and no value can be saved in form field.

### Related work

PR https://github.com/samvera/hyrax/pull/5157 - Update PcdmCollection metadata to match existing ::Collection metadata
Issue https://github.com/samvera/hyrax/issues/5494 - Edit collection only shows title field for Hyrax::PcdmCollection (closed)
Issue #5798 - Show all collection descriptive metadata
Issue #3725 - Enable GeoNames functionality for Location field in collections (closed from non-valkyrized Hyrax)

**Comment by jessicahilt** [comment]
We're going to check configuration.

**Comment by eliotjordan** [comment]
This worked for me after setting a valid [geonames service username](https://www.geonames.org/login):

```ruby
config.geonames_username = 'username'
```

https://github.com/samvera/hyrax/blob/main/.koppie/config/initializers/hyrax.rb#L107

![Screenshot 2023-08-21 at 4 28 44 PM](https://github.com/samvera/hyrax/assets/784196/e4b98994-a707-4c64-b450-e411093df3f0)

**Comment by no-reply** [comment]
@eliotjordan wondering if it would be convenient to make this settable (as a default) with an environment variable?

otherwise, we probably just need to configure https://github.com/samvera-labs/nurax to get this ready for QA?

**Comment by eliotjordan** [comment]
@no-reply An ENV var is a good idea. I’ll work up a PR for it and add it to Nurax. As far as setting the value of that variable for QA, there needs to be geonames username that can be referenced (or created) and this value should be set in the cloud environment (AWS?). The geonames username is not something we want to commit to a public repo.

**Comment by dlpierce** [comment]
I added a preexisting geonames to nurax pg recently, although not in ENV.
