### ISSUE TITLE
Enable Geonames functionality for Location field in Works

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5800]
### Descriptive summary

Geonames is not connected to Location field in the Edit Work form yet so Location metadata cannot be saved.

### Expected behavior

Location should function in work editing on valkyrized hyrax.

![55257372-ec633f80-521c-11e9-83b9-4cd1da1b522d](https://user-images.githubusercontent.com/3440166/184971688-826530bc-02f1-491d-bc38-2c2d67233c61.png)

### Actual behavior

Location field is not offering results from Geonames in Edit Work form and no value can be saved.

### Steps to reproduce the behavior

1. As a logged in user, create a new Work
2. On the Descriptions tab of the Edit Work form, click Additional Fields and scroll to the Location field.
3. Try searching for a location and no results are offered and no value can be saved in form field.

### Related work

PR https://github.com/samvera/hyrax/pull/5157 - Update PcdmCollection metadata to match existing ::Collection metadata (discussing what is needed for collections metadata)

**Comment by jessicahilt** [comment]
We're going to check configuration.

**Comment by tpendragon** [comment]
We think this works in Nurax, but not in Nurax PG

**Comment by eliotjordan** [comment]
This worked for me after setting a valid [geonames service username](https://www.geonames.org/login):

```ruby
config.geonames_username = 'username'
```

https://github.com/samvera/hyrax/blob/main/.koppie/config/initializers/hyrax.rb#L107

![Screenshot 2023-08-21 at 4 29 56 PM](https://github.com/samvera/hyrax/assets/784196/7ac01b08-279a-47ce-91b6-68525bba15be)

**Comment by eliotjordan** [comment]
Closed by https://github.com/samvera/hyrax/pull/6159

Tested in nurax-pg.
