### ISSUE TITLE
FileSet visibility parameter is ignored on file_set attach

### ISSUE THREAD

**Issue by jeremyf** [samvera/hyrax#5813]
This is a problem discovered in 3.4.1 of Hyrax during a Bulkrax implementation.
In the Hyrax UI you cannot set a file set's visibility during initial creation;
it's stamped from the work or defaulted.  However, in Bulkrax we need to
specify the visibility.

Related to samvera-labs/bulkrax#639

**Comment by cjcolvar** [comment]
FWIW I think this very stale closed PR has work relevant to this issue: https://github.com/samvera/hyrax/pull/5022

**Comment by jeremyf** [comment]
Reading Note: I'm investigating if this is isolated to Bulkrax.

**Comment by jeremyf** [comment]
We think we've resolved this as a bulkrax related bug.
