### ISSUE TITLE
Cannot edit Image (work) - NoMethodError in Hyrax::Images#edit 

### ISSUE THREAD

**Issue by acklose** [samvera/hyrax#5842]
### Descriptive summary

Nurax-pg: When clicking the "Edit" button on an image work, leads to an error message.

### Actual behavior
    
<img width="961" alt="PG_ImageEditError" src="https://user-images.githubusercontent.com/26173627/188757024-31b9151a-0f0c-48ca-85ba-689c4e18839c.png">

### Steps to reproduce the behavior

1. Create Image (work).
2. View Image (work).
3. Click "Edit" button.

**Comment by jlhardes** [comment]
@acklose can you try this again on nurax-pg? I just tried as a regular user and an admin user and I am not getting any errors. I wonder if the code update helped?

**Comment by acklose** [comment]
@jlhardes Yes, that resolved the issue. I created a new image work and was able to edit it in Nurax-PG.
