### ISSUE TITLE
Cannot remove embargo from work

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5844]
### Descriptive summary

When testing locally using koppie and after a work has an embargo assigned, trying to deactivate the embargo results in an error message.

### Expected behavior

A Deactivation successful message should appear and you should be able to verify that the embargo has been removed from the Work and the Work can be accessed.

### Actual behavior

The following error message is shown when trying to deactivate an embargo on a work: Faraday::ConnectionFailed in Hyrax::PermissionsController#confirm

![Screen Shot 2022-09-08 at 11 38 35 AM](https://user-images.githubusercontent.com/3440166/189167165-71d634be-6ec7-472b-953d-4966a5109e93.png)

### Steps to reproduce the behavior

1. Navigate to a Work which contains an embargo
2. Click the "Edit" button 
3. In the "Save Work" box on the right side, click the "Embargo Management Page" link in the Visibility section
4. Click the "Deactivate Embargo" button
5. Error message appears (see screenshot)

### Related work

#5572 Works cannot be saved if embargo or lease is assigned (nurax-pg) - in progress and available to test locally only but allows works to be saved with an embargo

**Comment by jlhardes** [comment]
Testing on koppie shows that the error screen isn't occurring anymore but the embargo is still not being removed. I see the green message that says it was successful but the Embargo badge is never changed to anything else. Additionally, the work title is not showing in the Embargo Management Page or in the interim screen when trying to Deactivate. I'm not sure if that is connected to the embargo not actually being removed, but maybe? The title of this work is supposed to be "Julie test embargo 1":

![Screen Shot 2022-09-15 at 4 20 37 PM](https://user-images.githubusercontent.com/3440166/190504659-74de0ad0-532c-4fb0-a4ad-34e5aa6dd39f.png)

![Screen Shot 2022-09-15 at 4 20 52 PM](https://user-images.githubusercontent.com/3440166/190504755-cec07af7-ef2b-4d9d-a523-b889fddb8ac9.png)

**Comment by gamontoya** [comment]
Seeing the same behavior Julie notes on Koppie.

![embargo](https://user-images.githubusercontent.com/4314914/190528943-f2d5f021-123a-466c-b3ef-4e77c9dcb2d4.png)

**Comment by eporter23** [comment]
I deactivated the Embargo on this work: https://nurax-pg.curationexperts.com/concern/generic_works/90bcd2bb-c040-44f1-a795-bc4f7afcba35/edit?locale=en - the embargo appears to have been removed, but it does not show up on the Deactivated Embargoes list in Manage Embargoes. 

<img width="797" alt="Screen Shot 2023-01-23 at 1 43 04 PM" src="https://user-images.githubusercontent.com/13855987/214123027-b228411f-87d2-4820-996a-74fa099d03a5.png">

**Comment by eporter23** [comment]
I created a new work and embargoed it, and tried to remove the embargo. I see a prompt to reset permissions to Private and proceed. No errors occur, but the work remains embargoed after several attempts. https://nurax-pg.curationexperts.com/concern/generic_works/9bc3f926-28c9-4165-bc71-0bf4adc7358f?locale=en

**Comment by gamontoya** [comment]
I can still replicate this issue on `Koppie v4.0.0.rc3`

![embargo](https://github.com/samvera/hyrax/assets/4314914/0943a07e-8817-4ca5-92d9-46f85e0e72fc)

**Comment by alishaevn** [comment]
this ticket only refers to embargoes, but it appear leases also aren't working. it's out of scope, but the work has begun on #6111.

**Comment by rjkati** [comment]
Confirmed that deactivating embargoes now works on pg.nurax
