### ISSUE TITLE
Manage Embargoes is not listing embargoed works

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5845]
### Descriptive summary

When testing locally using koppie and after a work has an embargo assigned, the Manage Embargoes section is not listing any works in All Active Embargoes. This is occurring whether the work was created by another user or the admin user trying to view the list of works in Manage Embargoes. Also note that works saved with an embargo currently do not show the "Embargo" badge under Visibility of Work. Instead they seem to be showing the visibility status applied due to the embargo ("Private", for example).

### Expected behavior

As an admin user, Manage Embargoes should show all works with active embargoes.

### Actual behavior

Works with active embargoes are not listed under Manage Embargoes.

### Steps to reproduce the behavior

1. Testing locally using koppie, log in as an admin user
2. Click "Add a new work" and fill in required descriptive metadata in the Descriptions tab
3. Attach a file to the work in the Files tab
4. Under Visibility, select "Embargo", Restrict to “Private” until a future date of your choosing (dd/mm/yyyy format) then open to “public”
5. Check Deposit agreement box
6. Click the "Save" button 
7. (Note that the Visibility of Work in the dashboard shows as "Private" instead of "Embargo" for this work)
8. In the dashboard, click Manage Embargoes on the left-side menu
9. See the All Active Embargoes tab does not list the work that was just created with an embargo

### Related work

#5572 Works cannot be saved if embargo or lease is assigned (nurax-pg) - in progress and available to test locally only, allows works to be saved with an embargo, Visibility of Work badge not showing as "Embargo" yet

#5844 Cannot remove embargo from work

**Comment by no-reply** [comment]
my initial guess is that this is an indexing issue (that we aren't indexing embargoes properly). i can try to write a failing test.

**Comment by jlhardes** [comment]
This is working locally on Koppie but is not deployed to nurax-pg yet.

**Comment by jlhardes** [comment]
This is now fixed on nurax-pg!
