### ISSUE TITLE
Managers of admin sets cannot view embargoed works 

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5848]
### Descriptive summary

When testing Hyrax 4.0.0.beta1 locally using Koppie, manager accounts cannot view embargoed works deposited in the admin set that they manage.

### Rationale

Managers of admin sets should be able to view all works deposited in the admin set

### Expected behavior

Managers of admin sets should see work show page and files for embargoed works

### Actual behavior
When a manager navigates to an embargoed work within their managed admin set, they see an "Unauthorized" message

### Steps to reproduce the behavior

Prerequisite: Make sure you have created two non-admin regular user accounts.

1. As an administrator, create an admin set and set one user account as a manager.
2. Log in as the regular user and deposit a work with an embargo.
3. Log in as the manager account from step 1 and attempt to view the embargoed work which you deposited in step 2

**Comment by alishaevn** [comment]
**(testing to see if the work done for #5844 fixed this problem too)**
<hr>

alpha: admin user
beta: regular user
gamma: regular user

as alpha I created an admin set and made beta to be a manager. I then logged out and back in as gamma. I created an embargoed work, but was unable to add it to the admin set. the admin set didn't even show up.

I logged back in as alpha and saw that the collection was private. I tried to set the admin set to public, but that isn't an option. I did a search in the samvera slack and discovered that admin sets can only be seen by other admins by default. (ref: [here](https://samvera.slack.com/archives/C3QESH5FG/p1506356456000477) and [here](https://samvera.slack.com/archives/C0F9JQJDQ/p1506357835000146)) instead, on the "participants" tab of the edit screen I clicked "allow all registered users to deposit". logged back in as gamma and was able to add an embargoed work to the admin set I created.

I logged in as beta and when I viewed the managed collections page, it showed that the admin set had 0 items. clicking the name of the admin set however took me to the dashboard view and that said there was 1 item. under the "works in this set" heading however, it said "The collection is either empty or does not contain items to which you have access."

logged back in as alpha, I was able to see the work that was created by gamma.

this is still an issue.

**Comment by dunn** [comment]
looks like `edit_access_person_ssim` on an adminset isn't honored when the permissions on the object are queried directly
```
[10] pry(main)> manager.can? :edit, work
[...]
  Valkyrie::Persistence::Postgres::ORM::Resource Load (0.2ms)  SELECT "orm_resources".* FROM "orm_resources" WHERE "orm_resources"."id" IN ($1, $2)  [["id", "77c67bad-5b5a-4dc8-870f-49debbdd93b1"], ["id", "8f04a7c2-14d5-4e67-bccf-c6fef533d887"]]
[CANCAN] Checking edit permissions for user: manager@example.com with groups: ["public", "registered"]
[CANCAN] edit_groups: []
[CANCAN] edit_users: ["basic_user@example.com"]
[CANCAN] decision: false
=> false
```

**Comment by gamontoya** [comment]
These steps that Alisha added were vital to this working:

`admin sets can only be seen by other admins by default--instead, on the "participants" tab of the edit screen I clicked "allow all registered users to deposit". logged back in as gamma and was able to add an embargoed work to the admin set I created.`
