### ISSUE TITLE
Visibility filter > Clipped text in drop-down menu - Dashboard

### ISSUE THREAD

**Issue by acklose** [samvera/hyrax#5854]
### Descriptive summary
In Hyrax 4.0.0beta1 and Valkyrized Hyrax, the  Visibility filter (both in "Works" & "Collections" in Dashboard) has clipped text in the drop-down. Screen grabs attached with clipped text circled in red).

### Rationale
Text is only partially visible.

**Steps to  `#replicate**`
Works view:
1. Go to Dashboard
2.  Click on Works (under REPOSITORY CONTENTS on left side)
3. Click on filter for Visibility to display drop-down. The clipped text is in the drop-down menu.

Collections view:
1. Go to Dashboard
2.  Click on Collections (under REPOSITORY CONTENTS on left side)
3. Click on filter for Visibility to display drop-down. The clipped text is in the drop-down menu.

<img width="945" alt="NuraxPG_Visibility_drop-down" src="https://user-images.githubusercontent.com/26173627/189720523-ae09655a-3d17-43f2-b2dc-3f3c5c762c2b.png">
<img width="937" alt="Hyrax_PG_Collections_Visibility" src="https://user-images.githubusercontent.com/26173627/189723558-b6eb1aee-f87b-46d2-8b7d-828dcee20b51.png">

**Comment by rjkati** [comment]
This can no longer be replicated on nurax-dev or nurax-pg (hyrax 4.0.0.beta2)
