### ISSUE TITLE
Rights statement no visible on show page

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5860]
### Descriptive summary

For both generic works and image works, the Rights Statement field is not visible in the record's show page. However, one can view and edit the Rights Metadata with the Edit forms. This is currently only an issue in Valkyrized Hyrax on Nurax-PG. This is not an issue in Nurax-Dev.

### Expected behavior

Rights Statement is shown as part of Work metadata on work view page when a value is saved in that field

### Actual behavior

Rights statement is not shown on work view page when there is a value saved in that field

### Steps to reproduce the behavior

1. On nurax-pg or koppie, create a new Work
2. On Descriptions tab, select a Rights Statement
3. Add required information and save the work
4. Review the public view of the Work and see that Rights Statement does not show
5. Return to the work in Dashboard, Edit the work, and see that Rights Statement field is there with metadata that was saved

### Related work

https://github.com/samvera/hyrax/issues/886 Right statement not showing up on show page - previous work that was resolved

**Comment by gamontoya** [comment]
This is working on Koppie now.

![rights](https://user-images.githubusercontent.com/4314914/190711974-e2a38da0-b28c-425f-b394-5c16b92c13cc.png)

**Comment by gamontoya** [comment]
@jlhardes This is DONE. It's working correctly on nurax-pg

![copyState](https://user-images.githubusercontent.com/4314914/190812166-bdb553cd-44f3-460e-a75e-35ee8d117e5a.png)
