### ISSUE TITLE
Show bibliographic_citation value

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5887]
### Descriptive summary

Bibliographic_citation is available as a metadata field on Works and values can be stored in that field but nothing shows on the Work view page for this field. All other descriptive metadata fields except for Alternative Title will show on the Work view page and bibliographic citation definitely needs to show if there is a value.

### Rationale

Many publishers mandate that a full bibliographic citation be included in the metadata for any preprints or postprints of scholarly publications that are made available in institutional repositories.

### Expected behavior

Any value or values stored in Bibliographic  citation field on Work display in the work view page.

### Actual behavior

No Bibliographic citation field with values displays with descriptive metadata

### Steps to reproduce the behavior

1. Log in to nurax-dev (or local app)
2. Under Works, click Add New Work
3. Fill in required metadata, then click Additional fields
4. Fill in Abstract field (to compare another non-required field)
5. Scroll down and fill in Bibliographic citation field
6. Click deposit agreement checkbox, then click Save
7. See in work view page that Abstract field shows with value but Bibliographic citation does not

### Related work

https://github.com/samvera/hyrax/issues/4632 Add bibliographic_citation to the form

**Comment by rjkati** [comment]
This issue is still present in Hyrax 4.0.0.beta1 on nurax-dev. The forms on nurax-pg do not include the Bibliographic Citation field, so this issue cannot be tested on nurax-pg at this time.

**Comment by rjkati** [comment]
Confirmed that value for bibliographic field displays on nurax-dev (Hyrax 4.0.0.beta2)

![bib_cite](https://user-images.githubusercontent.com/32644254/221026773-54ac3d3f-2364-4f03-bc21-2e8b5f5348f4.PNG)
