### ISSUE TITLE
Rights value of 'All rights reserved' uses Europeana RR-R URI that is no longer supported

### ISSUE THREAD

**Issue by wickr** [samvera/hyrax#589]
### Descriptive summary

Europeana no longer supports the Rights Reserved - Restricted Access statement used in Hyrax as 'All rights reserved." http://www.europeana.eu/portal/rights/rr-r.html  (gives 'Forbidden' error)

https://github.com/projecthydra-labs/hyrax/blob/master/lib/generators/hyrax/templates/config/authorities/licenses.yml

Looks like they actually dropped support in 2014 (last paragraph here: http://pro.europeana.eu/blogpost/europeana-digital-objects-to-have-valid-rights-statement-by-july )

(Oregon Digital recently switched to an equivalent form at opaquenamespace.org: http://opaquenamespace.org/ns/rights/rr-r  as a temporary solution, until we can fully evaluate how rightsstatements.org figures in. The main factor for this was having a URI with a label that was fetchable. I'm not advocating Hyrax or anyone else use this.) 

A likely replacement is In Copyright: http://rightsstatements.org/vocab/InC/1.0/

**Comment by jcoyne** [comment]
@wickr What changes do you think Hyrax should make?

Cc @anarchivist

**Comment by tpendragon** [comment]
Gotta love those stable URIs

**Comment by anarchivist** [comment]
I'll doublecheck, but I think InC is a good replacement. The previous text was as follows:

> **Rights Reserved - Restricted Access**
>
> This item is protected by copyright and/or related rights. This item is only accessible through registration or some other form of controlled access and subject to the licensing conditions set by the organization giving access to it.
>
> Unless expressly stated otherwise in the licensing conditions, you are free to make any of the acts permitted by your national copyright and related rights act, including browsing, printing and making a copy for your own personal purposes.
>
> All other acts of reproduction and communication to the public are subject to the licensing conditions attached to the work.

**Comment by anarchivist** [comment]
I'll also note that "Rights Reserved - Paid Access" (<http://europeana.eu/rights/rr-p.html>) was also removed ([ref](http://pro.europeana.eu/files/Europeana_Professional/IPR/rightsstatements-org-factsheet.pdf)):

> The existing Rights Reserved - Paid Access can no longer be supported by Europeana. Europeana will get into contact with all data partners who currently make use of the Rights Reserved - Paid Access statement to discuss the how to manage the transition from the old rights statement to a new one.

**Comment by wickr** [comment]
@jcoyne I think Hyrax should change to In Copyright unless there's a better suggestion. That's what Europeana switched to as well.

In Copyright isn't a license like Creative Commons, but it does give the status of the work.

**Comment by mjgiarlo** [comment]
More thoughts on the above, @projecthydra-labs/hyrax-code-reviewers?

**Comment by vantuyls** [comment]
unless there are objections or other comments, i think we should follow @wickr's comment above and follow what Europeana did with their switch for consistency.

**Comment by jlhardes** [comment]
I agree with @wickr and @vantuyls - In Copyright from rightsstatement.org seems like the best option.

**Comment by mjgiarlo** [comment]
We suggest marking the Europeana RR-P license in Hyrax as `inactive`. This will prevent users from selecting this license going forward, but will not invalidate current data or cause a data migration. Users can now use the Rights Statement field to more clearly assert users' rights to a work.

**Comment by wickr** [comment]
Closed by #1517
