### ISSUE TITLE
deactivating multiple leases returns "NoMethodError in Hyrax::LeasesController#update"

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#5909]
### Descriptive summary

When deactivating multiple leases in Hyrax 4.0.0.beta2, Hyrax returns a "NoMethodError in Hyrax::LeasesController#update" page, rather than a success message

### Expected behavior
After clicking "Deactivate Leases for Selected", success message should display and leases should be deactivated.

### Actual behavior

"NoMethodError in Hyrax::LeasesController#update" error displays and leases are not deactivated.

![lease_error](https://user-images.githubusercontent.com/32644254/200613160-bcb1d268-6bb6-41a5-9ac0-70a26bbfabe3.PNG)

### Steps to reproduce the behavior

1. As a repo-admin, navigate to Dashboard -> Manage Leases
2. Check the boxes next to multiple works and/or files
3. Click "Deactivate Leases for Selected"
4. Observe error message.

**Comment by blancoj** [comment]
I could not duplicate it and I went on a zoom with @rjkati and she could not duplicate it on nurax.  Perhaps this has been fixed by another issue?

**Comment by rjkati** [comment]
Looks like this was fixed by https://github.com/samvera/hyrax/pull/5917
