### ISSUE TITLE
Unify page layout in work new/edit form for all ui languages (4.0.0.beta2)

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#5923]
### Descriptive summary

Different page layout in work new/edit form with the "Save Work" block moving if some ui languages are selected. 
```
QA Testing for Hyrax
Hyrax Version: 4.0.0.beta2
Hyrax Branch: main
Hyrax Revision: [6c0e57f601de61621d72893188afaff86d25f2fd](https://github.com/samvera/hyrax/tree/6c0e57f601de61621d72893188afaff86d25f2fd)
```
### Rationale

The "Save Work" `<div  id="savewidget" ...>` in the work new/edit form should be placed on the right side of the form for all languages.  

### Expected behavior
The "Save Work" `<div  id="savewidget" ...>` in the work new/edit form should be placed on the right side of the form for all languages.  
![image](https://user-images.githubusercontent.com/30596226/204907383-fcd31558-cf3a-4322-8ecc-a4a37c010416.png)

### Actual behavior
The "Save Work" `<div  id="savewidget" ...>` in the work new/edit form should be placed on the right side of the form for en, es, it, and pt-BR locales, only. For de, fr, and jp locales it it placed below the "Edit work" div 
![image](https://user-images.githubusercontent.com/30596226/204907480-6098590e-5fe6-41c8-9ce0-75030cd77711.png)

### Steps to reproduce the behavior

1. https://nurax-dev.curationexperts.com/concern/images/m326m2061/edit?locale=de
2. change the locale via the language selector in the top menu.   

### Related work

Link to related tickets or prior related work here.

**Comment by jmfrenzel** [comment]
Reproduced on 
* Chromium Version 107.0.5304.121  
* Firefox Nightly 108.0a1 (2022-10-28) (64-bit)
* Firefox 107.1  (64-bit)

**Comment by rjkati** [comment]
This is working on dev.nurax running hyrax 4.0.0.beta2
