### ISSUE TITLE
Review submissions page failing with URI Too Long

### ISSUE THREAD

**Issue by bbpennel** [samvera/hyrax#5926]
### Descriptive summary

We are experiencing an error in our hyrax 3 based repository when navigating to the Review Submissions page in the admin dashboard. It appears that the page is producing a solr request that is too large. We see the following error in our logs:

```
FATAL: RSolr::Error::Http (RSolr::Error::Http - 414 Request-URI Too Long
Error: reason: URI Too Long

URI: http://localhost:8983/solr/blacklight-core/select?wt=json&q=%7B%21terms+f%3Did%7D12579t73p%2Cd791sh974%2C6q182m58b%2Cpr76f527f%2Cwh246s128%2Ckp78gh79g%2C3r074t92z%2Cpn89d6567%2Ck930bz70q%2Cww72bb48n%2C3f462540k%2Csb397991j%2C9306sz28s%2Ccn69m4128%2C6m311q84f%2C0z708w40c%2Czc77sr65r%2Ccv43nz36c%2C6108vb24b%2Cwh246t74g
...
2Cq237ht74g%2Crn3013269%2Csb397b26f%2Cfb494b35n%2Ccn69m606j%2Csj139387f%2Ctd96k4269%2C794080336%2C1v53k001w&qt=standard

Backtrace: /net/deploy/ir/test/ruby/2.7.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:220:in `rescue in execute'
/net/deploy/ir/test/ruby/2.7.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:208:in `execute'
/net/deploy/ir/test/ruby/2.7.0/gems/rsolr-2.5.0/lib/rsolr/client.rb:203:in `send_and_receive'
(eval):2:in `get'
/net/deploy/ir/test/ruby/2.7.0/gems/hyrax-3.4.2/app/services/hyrax/solr_service.rb:52:in `get'
/net/deploy/ir/test/ruby/2.7.0/gems/hyrax-3.4.2/app/services/hyrax/solr_service.rb:40:in `get'
/net/deploy/ir/test/ruby/2.7.0/gems/hyrax-3.4.2/app/services/hyrax/solr_query_service.rb:31:in `get'
/net/deploy/ir/test/ruby/2.7.0/gems/hyrax-3.4.2/app/services/hyrax/solr_query_service.rb:37:in `solr_documents'
/net/deploy/ir/test/ruby/2.7.0/gems/hyrax-3.4.2/app/services/hyrax/workflow/actionable_objects.rb:37:in `each'
/net/deploy/ir/test/ruby/2.7.0/gems/hyrax-3.4.2/app/controllers/hyrax/admin/workflows_controller.rb:19:in `reject'
/net/deploy/ir/test/ruby/2.7.0/gems/hyrax-3.4.2/app/controllers/hyrax/admin/workflows_controller.rb:19:in `index'):
```

### Rationale

There has been similar issues where switching over to using POST requests when submitting large numbers of ids to solr, which appears to be happening within the workflows_controller when rendering this page. To resolve the other issues, it looks like the default blacklight http_method was switched to POST:

https://github.com/samvera/hyrax/blob/main/lib/generators/hyrax/templates/catalog_controller.rb#L22

But it does not appear to impact this page.

@labradford is resolving the issue locally with the following change:
https://github.com/scientist-softserv/palni-palci/pull/340

It seems valuable to incorporate a similar resolution back into hyrax.

### Expected behavior

Review submissions page should load normally.

### Actual behavior

It returns an error page.

### Steps to reproduce the behavior

Visit the Review Submissions page in a hyrax instances with a large number of works in workflows.

**Comment by cjcolvar** [comment]
This is unfortunate that the `get` request is hard-coded.  FWIW ActiveFedora gives a choice to the caller through a `:method` option (see https://github.com/samvera/active_fedora/blob/main/lib/active_fedora/solr_service.rb#L54).  In Avalon we took this a step further and made the default method be configurable in the solr config (and defaulting to post instead of get) (see https://github.com/avalonmediasystem/avalon/blob/main/config/initializers/policy_aware_modification.rb#L43-L45).

**Comment by bbpennel** [comment]
Since ActiveFedora is on its way out for hyrax (or at least that's my uninformed understanding), it seems like if possible it would be best to configure this either via blacklight or with a hyrax specific config option. 

For the former, I'm not seeing a good way to use the [blacklight http_method from CatalogController](https://github.com/samvera/hyrax/blob/main/.dassie/app/controllers/catalog_controller.rb#L28) for this since it seems like the `configure_blacklight` details are scoped to that controller. There is a concept of a [default blacklight configuration](https://github.com/projectblacklight/blacklight/blob/v7.33.0/app/models/concerns/blacklight/configurable.rb#L46-L52) which can be overridden, and since it is a class method it could be used from anywhere. So my impression is if we set the http_method in the default_configuration to `post` in an initializer it would be used by all blacklight configurations unless overridden, and then we could have the SolrService use the same value when the method isn't otherwise specified.

Another option could be to introduce a `solr_default_method` property to `Hyrax.config` in the hyrax.rb initializer which defaults to `post`. Any places where we set blacklight's `http_method` would be set to the hyrax.config value, and SolrService would use it by default as well. This approach feels less likely to have unintended side effects with blacklight to me, and doesn't increase application interdependence with blacklight or activefedora as much, but does require a new config option.

@cjcolvar or others, do you have any opinion on the approach to take? I could probably work on this soon if there is a consensus.

**Comment by dlpierce** [comment]
Yes, I also prefer adding to `Hyrax.config`.

**Comment by bbpennel** [comment]
Okay, I can probably work on this early next week. Thank you both for the feedback

**Comment by bbpennel** [comment]
I've opened a PR to implement the Hyrax.config.solr_default_method property we discussed here. It should be ready for review.
