### ISSUE TITLE
Link Text/Alt URL missing when adding banner to a Collection

### ISSUE THREAD

**Issue by gamontoya** [samvera/hyrax#5930]
### Descriptive summary

Hyrax v4.0.0.beta2

The Link Text/Alt URL boxes are missing when adding a banner to a Collection, at the `Choose File` option. The boxes only appear after user clicks on save.

### Steps to reproduce the behavior

1. Edit a collection
2. Click Branding tab
3. Click Choose File button in Logo section and select one of your logo images

![banner](https://user-images.githubusercontent.com/4314914/206824287-5ef14456-a022-428c-9d85-e44a5a21032f.png)

**Comment by rjkati** [comment]
Verified that alt-text and link URL are present at file selection for logo now in Hyrax 4.0.0.beta2, as described in reproduction steps.
