### ISSUE TITLE
Add New Collection: Radio buttons lay over type name

### ISSUE THREAD

**Issue by gamontoya** [samvera/hyrax#5932]
### Descriptive summary

**Hyrax v4.0.0.beta2**

- localhost
- nurax-dev

When selecting `Add New Collection`, the radio buttons align to the center and therefore lay over the collection type names instead of lining up to the left of the names.

### Steps to reproduce the behavior

1. Click on `Collections` in the sidebar of the Dashboard
3. Click on `Add New Collection` on the right
4. Dialogue box displays showing collection types 
5. Note layout of the radio buttons

![collection](https://user-images.githubusercontent.com/4314914/207153993-8bda07fe-bfc0-4158-87ee-572cf487d4da.png)

**Comment by rjkati** [comment]
This has been fixed in Hyrax 4.0.0.beta2. I verified that the changes did not affect the work modal.
![collection_radio_buttons](https://user-images.githubusercontent.com/32644254/221945822-f09c47cc-1225-4e45-ab2d-b305d00331d5.PNG)
