### ISSUE TITLE
Google Analytics implementation should support loading clients from JSON

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#60]
One used to have to provide 5 or 6 pieces of information, including a P12 file, to enable the GA feature. Google Analytics now provides you a JSON file that wraps up the P12 secret key and the other bits of information, all in a single file, and Hyrax should support this because it's easier for users.

See: https://github.com/tpitale/legato/issues/124

**Comment by jcoyne** [comment]
> If you download the JSON file instead of the P12 file, you can replace the key line OpenSSL::PKCS12 … with key = OpenSSL::PKey::RSA.new(private_key) where private_key comes from the JSON private key value.

From https://github.com/tpitale/legato/wiki/OAuth2-and-Google#application-code

**Comment by no-reply** [comment]
this seems likely to be meaningless in the context of roadmapped analytics work. I'm closing it pending some concrete requirement in that context.
