### ISSUE TITLE
Pagination breaks depositing works into a collection

### ISSUE THREAD

**Issue by bkiahstroud** [samvera/hyrax#6006]
### Descriptive summary

Version: [hyrax-v3.5.0](https://github.com/samvera/hyrax/releases/tag/hyrax-v3.5.0)

As an admin, when I attempt to deposit a work into an existing collection, I see the following message: 

> You do not have access to any existing collections. You may create a new collection.

This behavior ONLY happens on pages 2+ of works in the admin dashboard. Selecting a work from the first page of results will succeed. 

### Screenshots 

<details>

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/32469930/232638044-15f70f8e-aff5-4738-a3a8-10ef0b8d3621.png">

</details>

### Rationale

🐛🥾

### Expected behavior

When I attempt to add any work(s) from pages 2+, they should deposit into the collection successfully. 

### Actual behavior

When I attempt to add any work(s) from pages 2+, I see a message saying I don't have access, even when I am supposed to.  

### Steps to reproduce the behavior

1. Spin up the .dassie Docker app locally ([instructions](https://github.com/samvera/hyrax/blob/main/CONTAINERS.md#hyrax-engine-development)) 
2. Login as admin@example.com
3. Create a Collection with the title `Test Collection` 
4. Create 15 Generic Works<sup>1</sup> 
5. Navigate to Dashboard > Collections > `Test Collection` 
6. Click `Add existing works to this collection` 
7. In the pagination menu at the bottom left of the page, click `Next` 
8. Check the `Select` checkbox next to any work 
9. Click the `Add to collection` button at the top of the list 
10. A modal appears with a message saying you don't have access 

<sup>1</sup> Running the script below in a rails console might be helpful 

<details><summary>Create many works quickly</summary>

```ruby
15.times do |i|
  GenericWork.create!(title: ["Work #{i}"], depositor: 'admin@example.com', creator: ['me'], rights_statement: ['http://rightsstatements.org/vocab/CNE/1.0/'])
end
```

</details>

### Related work

**Notes from initial investigation ([bkiahstroud](https://github.com/bkiahstroud))**

The URL (`/dashboard/my/works/page/2`) stood out to me as odd... typically, instead of seeing `/page/2` used for pagination, I've seen it like `?page=2`. 

I think the `page` parameter itself may be related to the root cause of the issue. Removing that param using a debugger, it appeared as though I had access like normal. 

---

This bug was originally reported by / investigated for PALNI/PALCI's [Hyku for Consortia](https://hykucommons.org/) Hyku project (Hyrax version: `v3.4.2`)

**Comment by jlhardes** [comment]
I could not recreate this problem in Hyrax 5.0.0 on https://dev.nurax.samvera.org/. I was able to select works from the second page of my works list and add them to the selected collection without any errors. I did this twice and it worked both times.

**Comment by dolsysmith** [comment]
We're on Hyrax 3.6. I understand that the bug seems to have been fixed in Hyrax 5.x, but I'm wondering if there were any patches or fixes discovered for 3.x

My [initial research](https://github.com/gwu-libraries/scholarspace-hyrax/issues/591) suggests that the bug is caused by an incorrect Solr `start` parameter.
