### ISSUE TITLE
feature flipper toggle returns "ArgumentError in Hyrax::Admin::StrategiesController#update" message

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6007]
### Descriptive summary

In Hyrax 4.0.0.rc1, toggling one of the feature flippers returns a "ArgumentError in Hyrax::Admin::StrategiesController#update" message. When I click the back button in my browser, the flipper reflects my intended action and the functionality works as intended.

### Expected behavior
Toggling a feature flipper should not generate an error message

### Actual behavior
Toggling a feature flipper generates an error message

### Steps to reproduce the behavior

1. Log into Hyrax 4.0.0.rc1 as an admin user and go to your Dashboard
2. In the configuration section, click "Features"
3. Click the feature flipper next to "Proxy deposit" and observe error message.
4. Click the browser back button and observe that the feature flipper now reflects the intended action.

![featureflipper](https://user-images.githubusercontent.com/32644254/232822749-2bc6e473-2748-4344-9d85-41cb32f6c744.PNG)

**Comment by dlpierce** [comment]
Should be fixed by #6003

**Comment by rjkati** [comment]
confirmed fixed on dev.nurax in hyrax 4.0.0.rc1
