### ISSUE TITLE
Metadata fields not displaying in UV

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#6008]
### Descriptive summary

Testing hyrax 4.0.0.rc1 locally (dassie), metadata fields do not display in the "More information" menu in the universal viewer. Required fields Title, Creator, and Rights Statement are not showing. Also added Description, Abstract, Subject, Keywords, and Date Created. One field that does show is Description.

### Expected behavior

Descriptive metadata fields that show below the viewer should also show in the More Information menu inside the viewer.

### Steps to reproduce the behavior

1. Create a Generic Work with required metadata (Title, Creator, Rights Statement) and attach an image file (so the viewer will load)
2. Save work then view the work and open More Information in the viewer. See that Title, Creator, and Rights Statement do not show in More Information in the viewer.
3. Edit the work and add metadata to additional fields: Description, Abstract, Subject, Keywords, Date Created
4. Save work then view the work and open More Information in the viewer. See Description is there but no other fields.
5. View all descriptive metadata below the viewer on the Work View page.

### Related work

Reported initially as a problem on dev.nurax - https://github.com/samvera-labs/nurax/issues/5

**Comment by rjkati** [comment]
metadata now displays in UV in Hyrax 4.0.0.rc2
