### ISSUE TITLE
inappropriate confirmation screen message after saving non-permissions-related edits to an existing work

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#606]
### Descriptive summary

As a depositor of a work, when I revisit a previously submitted item to make some edits to metadata (eg., add a subject, modify the title) and then click "Save", I am presented with a page displaying a message that is not specifically relevant to the current action.  

### Rationale

This error should be addressed because it is confusing to the user to read a message that indicates some change is happening that actually is not happening, or that some other change is happening that the user does not intend.

### Expected behavior

When saving descriptive metadata edits to an existing work, as a depositor, I would expect the changes to be applied on Save. I would not expect a screen for prompting confirmation of metadata edits before the changes are applied. I would expect to see a Flash message that says, "Your edits have been saved."

### Actual behavior

On Save after descriptive metadata edits are made, the application erroneously indicates a change in access level is about to be made. See screenshot.

![screenshot 2017-03-19 17 57 19](https://cloud.githubusercontent.com/assets/1801076/24116680/c99feac4-0d64-11e7-9202-dcf7c23022b8.png)

### Steps to reproduce the behavior

1. Edit the title, author, subject, etc. of an existing work.
2. Then click "Save"
3. See the erroneous message

**Comment by hannahfrost** [comment]
I also got this screen after saving file order changes in the File Manager

**Comment by mjgiarlo** [comment]
Can anyone confirm this is still the behavior? I've never seen this.

**Comment by vantuyls** [comment]
Two attempts at reproduction do not give this result. Hyrax behaves as expected at this point.
