### ISSUE TITLE
cannot remove lease from work

### ISSUE THREAD

**Issue by alishaevn** [samvera/hyrax#6126]
### Descriptive summary
ref:
- #5844 

I'll fill more of this out later. while doing the work for #5844, @sephirothkod and I realized that leases aren't working either. since the two features are opposite sides of the same coin, we decided to fix them as well. this ticket was created to track the lease work separately from embargoes.

### Steps to reproduce the behavior in User Interface (UI)

1. Do this
2. Then do this...
3. Include note here if not testable in UI

### Actual behavior (include screenshots if available)

Include what version of Hyrax relates to this issue (3.x, 4.x, main branch, etc.) if appropriate, and any relevant error messages/tracebacks if you're reporting a bug.

### Acceptance Criteria/Expected Behavior

- [ ] Create checkbox list of what done looks like...

### Rationale (for feature request only)

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Related work

Link to related issues or prior related work here.

**Comment by rjkati** [comment]
Confirmed that removing leases is working on pg.nurax
