### ISSUE TITLE
drop `engine_cart` from the project

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#6175]
remove `engine_cart` infrastructure from the project altogether and update any documentation that still suggests using that stack.

**Comment by no-reply** [comment]
this is blocked by #6174 and a follow-up dropping Ruby 2.7 support

**Comment by tpendragon** [comment]
## Success Criteria

EngineCart is no longer in the Gemfile and there's no reference to it in the project or its supporting wiki.

**Comment by no-reply** [comment]
this was unblocked when #6174 was merged

**Comment by hackartisan** [comment]
Reopening with the checklist that was in the PR:

- [ ]  Remove from wiki page: https://github.com/samvera/hyrax/wiki/Development-setup-using-Engine-Cart-and-Solr---Fedora-wrapper
- [ ]  Modify wiki page: https://github.com/samvera/hyrax/wiki/Hyrax-Development-Guide

**Comment by eliotjordan** [comment]
Wiki updated and engine_cart references removed.
