### ISSUE TITLE
Edit file permissions not working

### ISSUE THREAD

**Issue by jillpe** [samvera/hyrax#6177]
# Summary
When editing the visibility of a work's file through the 'select an action' drop-down menu in the Items section of the works show page, it does not save the visibility you select. 

Example: https://pg.nurax.samvera.org/concern/images/b5e61fb4-ad62-4ed9-b59b-298d805bd0d6?locale=en

This was the result of testing W_1.17 in the Hyrax QA Testing: https://docs.google.com/spreadsheets/d/1_eGSAtwWwR-0XUQo0PFtCtWbJ34YPres/edit#gid=1419227219

**Comment by tpendragon** [comment]
## Proposed Success Criteria

In Koppie when editing the visibility of a work it should persist those changes. Write a test which ensures that a Monograph's visibility can be edited.

## Places to Look

Check the valkyrie update branch in the resource controller and the visibility portions of the change set.

**Comment by no-reply** [comment]
@tpendragon i think this problem as described is scoped to FileSet visibility, not Works.

i think for Works this is tested at the controller layer at https://github.com/samvera/hyrax/blob/4d3ddb981ab34d7c231f131771190cc168e3e39b/spec/controllers/concerns/hyrax/works_controller_behavior_spec.rb#L109-L136

**Comment by tpendragon** [comment]
@no-reply Updated text.

**Comment by rjkati** [comment]
Confirmed on pg.nurax. I can now set the visibility of individual filesets. Logged out users cannot download restricted filesets.
