### ISSUE TITLE
"File Manager" reordering files bug

### ISSUE THREAD

**Issue by jillpe** [samvera/hyrax#6178]
# Summary
This is a result of testing W_1.19 in the Hyrax testing guide: https://docs.google.com/spreadsheets/d/1_eGSAtwWwR-0XUQo0PFtCtWbJ34YPres/edit#gid=1419227219

Upon access of the "File Manager" button on a work with several files, the files do not display and are therefore, not able to be moved around. See screenshot below:
<img width="1100" alt="Screen Shot 2023-08-23 at 2 06 25 PM" src="https://github.com/samvera/hyrax/assets/84697174/564a1f54-4d76-4ba2-8b44-f29a8161cf68">

Example Work:https://pg.nurax.samvera.org/concern/images/b5e61fb4-ad62-4ed9-b59b-298d805bd0d6?locale=en

**Comment by tpendragon** [comment]
## Proposed Success Criteria

In Koppie when I go to the file manager for a work with two files I should be able to see the files that are uploaded, rearrange them, and save the new order.

The other buttons are not in scope - radio buttons and label editing is broken in Hyrax main.

**Comment by tpendragon** [comment]
Closed as a dup of #6166
