### ISSUE TITLE
Adding a file larger than 500 MB to a work does NOT error

### ISSUE THREAD

**Issue by jillpe** [samvera/hyrax#6179]
# Summary
This resulted from testing W_1.26 on the Hyrax QA Guide: https://docs.google.com/spreadsheets/d/1_eGSAtwWwR-0XUQo0PFtCtWbJ34YPres/edit#gid=1419227219

When creating a work and adding a file that is larger than 500 MB, there is no error message that alerts the user. Although, the work never saves/goes through, the user is able to click save work without being alerted the file is too large.

**Comment by no-reply** [comment]
is this a duplicate of #6069 ?

**Comment by rjkati** [comment]
Yes this is a duplicate of #6069. An interim solution was implemented in #6079, which adds a note about the upload limits. This note is present on pg.nurax.

**Comment by rjkati** [comment]
duplicate of #6069
