### ISSUE TITLE
Ensure `spec/services/hyrax/multiple_membership_checker_spec.rb` passes on `.koppie`

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#6196]
`spec/services/hyrax/multiple_membership_checker_spec.rb` is failing on koppie builds. there may be a number of reasons for this:

  1. the test setup uses ActiveFedora, and should be refactored to use Valkyrie;
  2. the tests themselves test behavior that only applies to ActiveFedora, and should be turned off by adding the `:active_fedora` rspec metadata;
  3. the unit under test depends on ActiveFedora and needs to be rewritten to use Valkyrie throughout;
  4. some combination of the above.

----

```sh
docker-compose -f docker-compose-koppie.yml build
docker-compose -f docker-compose-koppie.yml up
docker-compose -f docker-compose-koppie.yml exec -w /app/samvera/hyrax-engine app sh -c "bundle exec rspec spec/services/hyrax/multiple_membership_checker_spec.rb"
```

**Comment by eliotjordan** [comment]
Resolving this involves fixing `Hyrax::CollectionType`

**Comment by eliotjordan** [comment]
@no-reply I wrote that note as pointer for whoever takes this ticket as to where to start. My knowledge of Wings is limited, but it seems that the CollectionType model should inherit from Hyrax::Resource:

https://github.com/samvera/hyrax/blob/main/app/models/hyrax/collection_type.rb#L3

I tried that and then spent 30 minutes getting lost down an attribute rabbit hole. 🐰  Same with FileSet in other tickets.

**Comment by no-reply** [comment]
> seems that the CollectionType model should inherit from Hyrax::Resource

**Comment by eliotjordan** [comment]
🤷  Just trying to help with limited knowledge.

**Comment by no-reply** [comment]
maybe it might help to pair on one or two of these? they're mostly boilerplate work, but it can be hard to quickly analyze what's needed without context.

**Comment by no-reply** [comment]
my guess looking at this test is that  the use of `create(:collection_lw)` and `create(:work)` are the main problems. these are going to try to build and persist AF models, and that won't work in the koppie environment.

**Comment by no-reply** [comment]
@eliotjordan i'm going to do a very brief session at 12:30 PDT to work through this.
