### ISSUE TITLE
Ensure `spec/presenters/hyrax/work_show_presenter_spec.rb` passes on `.koppie`

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#6198]
`spec/presenters/hyrax/work_show_presenter_spec.rb` is failing on koppie builds. there may be a number of reasons for this:

  1. the test setup uses ActiveFedora, and should be refactored to use Valkyrie;
  2. the tests themselves test behavior that only applies to ActiveFedora, and should be turned off by adding the `:active_fedora` rspec metadata;
  3. the unit under test depends on ActiveFedora and needs to be rewritten to use Valkyrie throughout;
      * if this involves adding a switch for AF / Valkyrie behavior, ensure both branches are covered by adding another test
  5. some combination of the above.

at a glance, i think this is a combination of at leaste 1 and 3.

----

```sh
docker-compose -f docker-compose-koppie.yml build
docker-compose -f docker-compose-koppie.yml up
docker-compose -f docker-compose-koppie.yml exec -w /app/samvera/hyrax-engine app sh -c "bundle install"
docker-compose -f docker-compose-koppie.yml exec -w /app/samvera/hyrax-engine app sh -c "bundle exec rspec spec/presenters/hyrax/work_show_presenter_spec.rb"
```

**Comment by hackartisan** [comment]
closed by #6225
