### ISSUE TITLE
Using a single use link generates argument error in valkyrie

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6204]
### Descriptive summary

When I attempt to use a single use link to a fileset, I get an `ArgumentError in Hyrax::SingleUseLinksViewerController#download` page instead of the file.

This works as expected on dev.nurax, but not pg.nurax

### Steps to reproduce the behavior in User Interface (UI)

1. Deposit a work with institution, embargoed or private visibility.
2. On the work show page for the work which you deposited in step 1, scroll down to the Items section and click on the file name
3. Click the `Create Single-Use Link` button
4. Click `Copy` under the `Single-Use Links` header
5. Go to a different browser and paste the single use link
6. Observe error message

### Actual behavior (include screenshots if available)

Using a single-use link generates an error

![single-use_link_error](https://github.com/samvera/hyrax/assets/32644254/6bfac5e1-5301-4e27-87b4-715065f1b6c4)

### Acceptance Criteria/Expected Behavior

Using a single-use link should download the file associated with the link.

**Comment by tpendragon** [comment]
The related test might be reflected in https://github.com/samvera/hyrax/issues/6195

**Comment by rjkati** [comment]
I can now generate a single use link to a file and successfully download the file associated with that link on pg.nurax.
