### ISSUE TITLE
Review submissions shows works you are not authorized to approve

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#621]
When I go have granted myself the "one_step_mediated_deposit - approving" role (and no others) and I go to http://localhost:3000/admin/workflows?locale=en

I see works that need approval, however when I click on them I get the unauthorized message.

This is because the document has the following solr field:

```
"actionable_workflow_roles_ssim"=>["one_step_mediated_deposit-depositing", "one_step_mediated_deposit-approving"]
```

**Comment by jeremyf** [comment]
I'm not familiar with how the SOLR query is used in abilities. My gut says that it relates to entity level permissions not being found. I'm looking into this.

**Comment by jeremyf** [comment]
@jcoyne And this is where I realize…I have no idea how permissions happen in this application. I see it is in the Ability class, but wow!

**Comment by jcoyne** [comment]
@jeremyf the bigger questions is, should a deposited work that is waiting for review have `one_step_mediated_deposit-depositing` as one of the roles that can do something

**Comment by jeremyf** [comment]
I can't duplicate.

**Comment by mjgiarlo** [comment]
@jcoyne Do you suspect this is now close-able?
