### ISSUE TITLE
New version of file cannot be downloaded

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6211]
### Descriptive summary

When I upload a new version of a file on pg.nurax, the upload process completes in the UI, but the new version of the file cannot be downloaded.

### Steps to reproduce the behavior in User Interface (UI)

1. Deposit a new work on pg.nurax or navigate to a work which you've previously deposited
2. On the work show page for your deposited work, scroll down to the Items list and click on the file name
3. Click the `Edit This File Set` button
4. Click the `Versions` tab
5. Click the green `Choose New Version File` button
6. Select a new file and click `Open`
7. Click the `Upload New Version` button.
8. Observe that the user activity log on the file set page has been updated to reflect your action.
9. Click the Download link and observe that the original file is downloaded, rather than the revised version.

### Actual behavior (include screenshots if available)

User activity section on the fileset page reflects that a new version has been uploaded, but download button downloads the original version.

### Acceptance Criteria/Expected Behavior

After uploading the new version of a file, the user activity section on the fileset page should reflect that a new version has been uploaded and the download button should download the new version.

**Comment by tpendragon** [comment]
@marrus-sh is going to add a link to a PR that added some versioning things to the valkyrie branch of this code to help guide implementation.

**Comment by tpendragon** [comment]
There might be missing API in Valkyrie for this - we just need to know what that API should be and we can get it added.

**Comment by tpendragon** [comment]
We'll have to repeat QA of versioning features right after implementing this.

**Comment by marrus-sh** [comment]
Here is the PR where I previously worked on versioning in a Valkyrie context: https://github.com/samvera/hyrax/pull/5886

Ultimately versioning support is provided by the file adapter, which needs `supports?(:versions)` and an implementation of a `find_versions` method. The fallback in Valkyrie if no versions are available is `resource.file_identifier`.

It’s surprising to me that №8 in the steps to reproduce works successfully in PG nurax. Does the nurax PG adapter actually support versioning, or is this effectively a no‐op despite being logged? I think getting some tests to ensure that uploading a new version actually does something on the postgres backend would be a good place to start.

**Comment by tpendragon** [comment]
It's our feeling that a variety of the versioning stuff in Hyrax w/ Valkyrie just silently fails.

There's stuff for reading versioning and stuff for saving versioning - a lot of that is currently missing regardless of which storage adapter you're using. Don't know if Wings has saving versions - it has support for reading versions.

Right now it's expected that the storage adapter has a `#supports` method for versioning and there are some extra queries the storage adapter should support as well.

We think we can look at `lib/wings/storage.rb`. Some options are `supports?(:version)` and `find_version`.

**Comment by tpendragon** [comment]
We've disabled versioning in nurax-pg, we're going to close this ticket and run QA after closing #6234 and if versioning is still broken then we'll open a new ticket.
