### ISSUE TITLE
Video and audio does not play in browser

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6227]
### Descriptive summary

On pg.nurax, video and audio files do not play in the browser. When I attempt to play either file in Chrome, the player does not show any information for the audio or video and the play button cannot be clicked. When I attempt to play the video file in Firefox, I received a "No video with supported format and MIME type found" message. The audio player does not load the audio track information in Firefox

I can replicate the issue locally on Koppie. Video and audio play as expected on dev.nurax.

### Steps to reproduce the behavior in User Interface (UI)

1. Go to: https://pg.nurax.samvera.org/concern/generic_works/4e402c5d-9b66-4ac7-be49-f7915378d198?locale=en
2. Scroll to the Items section
3. Click on the title of the video file
4. Observe that the player does not load
5. Go back to the Item list and click on the audio file
6. Observe that the player does not load

### Actual behavior (include screenshots if available)

Both audio and video players display but do not load information about the media or allow user to play media.

**Chrome**

![no_audio_chrome](https://github.com/samvera/hyrax/assets/32644254/d195155f-1f22-413f-8e67-b7bfcdf7fb40)

![no_video_chrome](https://github.com/samvera/hyrax/assets/32644254/c3d5a09b-de49-4d46-867f-88b2c9829997)

**Firefox**
![no_audio_ff](https://github.com/samvera/hyrax/assets/32644254/5bd709b3-537a-4a72-ac5b-6a934dbdbcd6)

![no_video_ff](https://github.com/samvera/hyrax/assets/32644254/77f6af96-8dd3-4699-90c8-2ab479be780f)

### Acceptance Criteria/Expected Behavior

Video and audio player should load information about the media and play respective media.

### Related work

#5780 seems to be the same issue from Hyrax 4, which is now resolved on dev.nurax, but there aren't any notes in the ticket about the resolution.

**Comment by hackartisan** [comment]
network tab shows 404 for the resources. trying to view one of them directly in the browser results in an error page showing an `ArgumentError: No PCDM use is recognized for webm`

**Comment by hackartisan** [comment]
currently blocked by #6294

**Comment by rjkati** [comment]
video and audio now plays in the default players in the browser
