### ISSUE TITLE
NoMethodError when editing a location value

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6277]
### Descriptive summary

On pg.nurax, when I edit a work which contains a value in the `Location` field, I receive a `NoMethodError in Hyrax::GenericWorks#edit` message

### Steps to reproduce the behavior in User Interface (UI)

1. Go to a work which you have deposited or have permission to edit
2. Click Edit
3. Click Additional Fields
4. Add a value in the Location field
5. Click Save changes
6. Click Edit on the work show page
7. Observe error message

### Actual behavior (include screenshots if available)

Editing a work which contains a value in the Location field produces a NoMethodError message

![nomethodlocation](https://github.com/samvera/hyrax/assets/32644254/95c35854-5c46-4d0f-946a-42495b272b2b)

Examples (need admin access to edit): 

- https://pg.nurax.samvera.org/concern/generic_works/3935be5f-98a3-404f-8e30-65b2a8295b91?locale=en
- https://pg.nurax.samvera.org/concern/generic_works/98f5577d-2eb9-420e-bfeb-f6c38f3e785a?locale=en

### Acceptance Criteria/Expected Behavior

When I click Edit on the work show page, I should be able to edit the work.

### Related work

Link to related issues or prior related work here.
#5800

**Comment by sdellis** [comment]
The error occurs here: https://github.com/samvera/hyrax/blob/881f8b3982e7af56d0f40cb6a4104b1bb7624e21/app/inputs/controlled_vocabulary_input.rb#L47

One issue here is that the :based_near multi-value attribute has the order/index saved as the first element of the array, which throws the no method when it tries to access the `.node?` method. However, the second value in the array also throws the same error.

```
:based_near=>
  [[:"0", #<Valkyrie::ID:0x00007efe6ff73838 @id="https://sws.geonames.org/6255148/">],
   [:"1", #<Valkyrie::ID:0x00007efe6ff73090 @id="https://sws.geonames.org/5102922/">]],
```

**Comment by dlpierce** [comment]
It's expecting a Hyrax::ControlledVocabularies::Location which is an ActiveTriples::Resource. Seems to me it should be an RDF object, and then the input updated to be compatible with both styles.

**Comment by hackartisan** [comment]
We think that the issue is: 

* ActiveFedora models saved based_near as a sort of nested resource: https://github.com/samvera/hyrax/blob/ae9b1bf04eaf00dca6df5db86d6da51db4a83ef5/app/models/concerns/hyrax/basic_metadata.rb#L36
* the valkyrie schema saves it as a string: https://github.com/samvera/hyrax/blob/ae9b1bf04eaf00dca6df5db86d6da51db4a83ef5/config/metadata/basic_metadata.yaml#L17-L18

Do we need to reopen and implement https://github.com/samvera/hyrax/issues/3662?

**Comment by hackartisan** [comment]
- There may have been an implementation that didn't use geonames, i.e. so the user could just type something in. Maybe it falls back to this behavior if QA isn't in there?

Decision:
- We think the lookup happens at index time. We could update the code to pull from the index?
- On the changeset you could do def location value and from there do the lookup. Do the lookup every time we load the form.

Leave a comment about the trade off of this impelmentation, mention that once we're past wings we can rewrite it to use nested resources if desired, with a small resource that stores the label and uri.

**Comment by sdellis** [comment]
One approach I'm trying is to [intercept the `based_near` param in the controller and transform it into the same structure Dassie expects](https://github.com/samvera/hyrax/blob/6277-location-value/app/controllers/concerns/hyrax/works_controller_behavior.rb#L186-L213). I'm able to remove the "hidden_field" key/value, but cannot figure out how to remove the index key in the ActionController::Parameters hash as it would no longer be a Parameter object if converted to an array.

**Comment by hackartisan** [comment]
Once the form works, display of the field will need to be validated.

**Comment by rjkati** [comment]
Confirmed that I can now edit a work which contains a value in the location field on pg.nurax. 

For future testing, note that works created on pg.nurax before the fix was deployed can be edited but not saved. Works created after the fix was deployed can be both edited and saved.
