### ISSUE TITLE
Koppie specs: spec.views.hyrax.base._form_metadata uninitialized constant Hyrax::GenericWorkForm

### ISSUE THREAD

**Issue by dlpierce** [samvera/hyrax#6307]
### Descriptive summary

`spec/views/hyrax/base/_form_metadata.html.erb_spec.rb` fails in koppie with:

```
Failure/Error: Hyrax::GenericWorkForm.new(work, ability, controller)

NameError:
  uninitialized constant Hyrax::GenericWorkForm
./spec/views/hyrax/base/_form_metadata.html.erb_spec.rb:9
```

ref #6137

**Comment by rjkati** [comment]
I can create a generic work on pg.nurax, but attempting to view the json gives an error. I will open a new issue for the json
