### ISSUE TITLE
In Valkyrie/Fedora some predicates in the Fedora interface are "http://example.com/predicate/"

### ISSUE THREAD

**Issue by dlpierce** [samvera/hyrax#6332]
### Descriptive summary

Properties stored using the fedora metadata adapter have the predicate `http://example.com/predicate/`

### Steps to reproduce the behavior in User Interface (UI)

1. Load sirenia (koppie with fedora metadata/storage adapters)
2. Create a monograph
3. Examine fedora rest interface for the monograph

### Actual behavior (include screenshots if available)

![Screenshot_20230928_113338](https://github.com/samvera/hyrax/assets/105335/e43e9ed0-1893-4202-8b22-db65020dc834)

### Acceptance Criteria/Expected Behavior

- [x] Appropriate predicates are displayed for each property

### Rationale (for feature request only)

Fedora data should more closely match data created by a ActiveFedora backed hyrax

### Related work

#6331

**Comment by jlhardes** [comment]
The properties used on a Monograph work in Sirenia no longer include `http://example.com/predicate/` and are either mapped as expected for a work in Hyrax or using `http://hyrax-example.com/predicate` so I think the changes have taken effect.
