### ISSUE TITLE
In Valkyrie/Fedora, work cannot be saved with Public visibility

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#6337]
### Descriptive summary

When creating a new work or editing a work, you can select Public as visibility but it will not save as Public.

### Steps to reproduce the behavior in User Interface (UI)

1. Running locally with Valkyrie/Fedora, log in to dashboard as admin user
2. Create a new Generic Work
3. Add required metadata and a file
4. Select Public as Visibility and save
5. Work will save and visibility will be set to Private
6. Click Edit to edit work
7. See that Visibility is set to Private. Select Public and save.
8. Work is still set to Private (and fileset is as well)
9. Can also try editing fileset: select Edit under Actions drop-down menu
10. Select Permissions tab
11. Select Public and Save
12. Receive error message: "There was a problem processing your request."

### Actual behavior (include screenshots if available)

Regardless of actions taken, work will not save as Public. Only time an error message seems to be thrown is when trying to change the Visibility under Permissions on a Fileset. Not enough info to know what has gone wrong (no stack trace) but some kind of error has been caught.

I also tried setting Visibility to Embargo and that will set. I then canceled embargo and the work set back to Private visibility. Tried to change to Public and received error message: "Failed save on # undefined method `<' for nil:NilClass" (but still not a stack trace)

**Comment by jlhardes** [comment]
More testing shows the following problem for non-admin users. They can create works but cannot save them as Public visibility and additionally they cannot view or edit them after creating them.

1. Running locally with Valkyrie/Fedora, log in to Dashboard as non-admin user
2. Create a new Generic Work
3. Add required metadata and a file
4. Select Public as Visibility and save
5. Work will save with a message that you are unauthorized to view the page
6. Return to Dashboard > Works
7. See the work listed as a work that you own but the Actions drop-down does not offer you a way to edit and clicking into the work itself shows the "Unauthorized" message again.

**Comment by jlhardes** [comment]
There does seem to be one particular set of actions that will show an error message (not a stack trace but a pretty error):

1. Running locally with Valkyrie/Fedora, log in to dashboard as admin user
2. Edit a work that is set to Private visibility
3. Select "Institution" as the Visibility and click Save
4. The following error message shows above the Edit form: "Failed save on # undefined method `<' for nil:NilClass"

**Comment by rjkati** [comment]
Both admin and regular users can now save works as public visibility in sirenia. However, when I attempt to change the fileset visibility to "institution" or "private", while the work visibility is "public", I get an error message ("there was a problem processing your request"). I'll open a new ticket for this.
