### ISSUE TITLE
In Valkyrie/Fedora, filesets cannot be saved with a different visibility than works

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6349]
### Descriptive summary

When editing a fileset, you cannot change the visibility setting to a different visibility than the work

### Steps to reproduce the behavior in User Interface (UI)

1. Running locally with Valkyrie/Fedora, log in to dashboard as admin user or regular user
2. Create a new Generic Work
3. Add required metadata and a file
4. Select Public as Visibility and save
5. On the work show page, scroll to the Items list and click the fileset title
6. Click Edit this File Set
7. Click the Permissions tab
8. Select Institution visibility
9. Observe error message "There was a problem processing your request"

### Actual behavior (include screenshots if available)

When attempting to save a fileset with a different visibility than the work, I get an error message "There was a problem processing your request"

### Acceptance Criteria/Expected Behavior

Filesets should be able to have different visibility settings than the work.

### Related work

#6337

**Comment by abelemlih** [comment]
@rjkati the reproduction steps of this ticket are inconsistent. I followed the steps outlined above, and got the same error mentioned during my first attempt at changing the fileset's visibility. When I attempted the change a second time, it processed successfully.

For reference, after the first successful change, I am now able to create new works and change their filesets' visibility without any issues.

**Comment by rjkati** [comment]
I rebuilt my local build with the latest version of `main` and I'm now able to change the fileset visibility independently of the work without an error. @jlhardes could you please test and report back? If you also can't reproduce this, then I think we can close this ticket.

**Comment by jlhardes** [comment]
@rjkati I rebuilt as well and cannot reproduce the error from the instructions on this issue. I can update the fileset visibility independently from work visibility between Public and Private, at least.
