### ISSUE TITLE
Unable to restore previous version of a fileset on pg.nurax

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6352]
### Descriptive summary

On pg.nurax, I am unable to restore a previous version of a file

### Steps to reproduce the behavior in User Interface (UI)

1. On pg.nurax, navigate to a work for which you have edit access (or deposit a new work)
2. Scroll to the item view and click on the title of the file
3. Click "edit this file set"
4. Click "versions"
5. Click "Choose New version file", select a file, and click "Upload New Version"
6. Click "versions"
7. In the "Restore Previous Version" section, click the radio button next to the previous version and click "Save revision"
8. Open the work's show page in an incognito/private window and observe that the previous version of the file does not display.

### Actual behavior (include screenshots if available)

Restoring a previous version of a file does not restore the previous version. Rather, the new version displays.

### Related work

#6234

**Comment by rjkati** [comment]
On further testing, it looks like restore works as expected as long as the files are of the same type. It seems that if you upload a PDF, replace it with an image, and then try to restore the PDF, the behavior in the instructions above displays.

**Comment by dlpierce** [comment]
Currently the revert action only affects the storage adapter. It does not rerun characterization, derivatives, etc. Further, even after rerunning those processes, Riiif is caching the old image.

**Comment by rjkati** [comment]
I can upload a new version, and the new version displays as both the new thumbnail and in the UV (provided that I navigate the expected browser cache issues)

I can also restore the previous version and the previous version displays as expected.
