### ISSUE TITLE
File Details - User Activity table has accessibility issue when empty

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#6353]
### Descriptive summary

If the User Activity/Date table on the File Details page has no data, then the table with table headers is in place but there are no table rows or cells of data and that presents an accessibility problem. (WCAG Level A - https://www.w3.org/TR/wai-aria-1.1/#mustContain, https://www.w3.org/WAI/WCAG21/Techniques/html/H43)

### Steps to reproduce the behavior in User Interface (UI)

1. View the following File Details examples:
- dev.nurax - https://dev.nurax.samvera.org/concern/parent/q524jn995/file_sets/ht24wj737
- pg.nurax - https://pg.nurax.samvera.org/concern/parent/63c05cfe-29be-43aa-965d-b7941ebbf62d/file_sets/6b31ada9-ef95-424d-ac1f-f6d1ed39f2df
2. Inspect or View source on the User Activity table and see there is an empty <tbody> after the <tr><th> table row with table headers.

dev.nurax example screenshot:
![Screenshot 2023-10-09 at 3 34 19 PM](https://github.com/samvera/hyrax/assets/3440166/c9662203-f613-4f0c-a1d8-392bf9b2c4e6)

### Acceptance Criteria/Expected Behavior

- [ ] Option: do not include table at all if there is no user activity to show
- [x] Option: include data table row by default that says there is no user activity of note 
- [ ] Option: list the initial file upload to the work as a user activity data table row

**Comment by christhepianist** [comment]
Tested and confirmed.

**Comment by christhepianist** [comment]
Tested and confirmed in dev, but PG still shows the error.![Image](https://github.com/user-attachments/assets/7b38a432-9877-4841-bc8f-0a91c91b03ec)

**Comment by christhepianist** [comment]
Tested and confirmed in both dev.nurax and pg.nurax. One of the servers must have been out of sync with the other when I first checked.
