### ISSUE TITLE
Unable to view list of works created by particular user

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#6359]
### Descriptive summary

Viewing a depositor's profile and trying to see the list of works created by that depositor is returning 0 results

### Steps to reproduce the behavior in User Interface (UI)

1. Navigate to the home page (no need to be logged in at all)
2. Click on the "Recently Uploaded" tab
3. Click on a depositor's name
4. Click on "Works created" link
5. 0 works returned in search results

Happening on pg.nurax and locally testing with Sirenia.

**Comment by rjkati** [comment]
Works created by a specific user now display on pg.nurax
![pg_depositor_results](https://github.com/samvera/hyrax/assets/32644254/80407836-4f9a-4dcc-b4bd-798fb67999cb)
