### ISSUE TITLE
editing a work changes administrative set assignment on pg.nurax

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6424]
### Descriptive summary

On pg.nurax, editing a work changes the administrative set assignment. This does not happen on dev.nurax

### Steps to reproduce the behavior in User Interface (UI)

1. Go to Dashboard -> Works -> Add New Work
2. Select `Generic Work`
3. Fill out the required fields and add a file
4. On the `Relationships` tab, choose an admin set that is **not** `Managers of admin sets cannot view embargoed works (GAM)` and make note of the admin set that you chose.
5. Click `Save` and note that the admin set assignment in the `Relations` section reflects your choice from Step 4
6. Click `Edit` and add another value to a required field
7. Click `Save changes`
8. Note that the admin set assignment in the `Relations` section no longer reflects your choice from Step 4 (it usually changes to `Managers of admin sets cannot view embargoed works (GAM)` for me)

### Actual behavior (include screenshots if available)

Editing a work on pg.nurax changes the admin set assignment

### Acceptance Criteria/Expected Behavior

admin set assignment should persist between edits

**Comment by rjkati** [comment]
Upon further testing, it seems like this is an issue if the `Assign admin set` feature flipper is enabled. If the `Assign admin set` feature flipper is disabled, the work is placed in the Default admin set and that assignment persists after editing.

**Comment by dlpierce** [comment]
Confirmed locally. Upon editing the work the selected admin set on the relationships tab is the default admin set.
