### ISSUE TITLE
Cannot edit permissions in batch edit

### ISSUE THREAD

**Issue by hackartisan** [samvera/hyrax#652]
### Descriptive summary

In sufia 7.3, [this commit](https://github.com/projecthydra/sufia/commit/c838900cf5614cf6041f6880ff5d8c79fbf99f67#diff-e973de65fffd505468ff5c1f560b6d67R68) introduced a check for `allows_access_grant?` on an admin set's workflow. However, in batch edit there's no admin set. This means you can no longer edit permissions as a batch operation.

### Expected behavior

This previous functionality should be available, perhaps by consulting the admin set to which each object belongs and applying it to all that are allowed.

### Actual behavior

The UI works, and it looks like it saves, but when you actually reload the 'share' tab of the form after saving the new permission disappears.

### Steps to reproduce the behavior

1. Create a test app with a default admin set and default workflow loaded (ensure `access_grant_enabled: true`)
1. Create an object and two users
1. Batch edit the object, add the other user with edit permissions
1. Save, then reload the form to see the permissions do not save.

**Comment by hackmastera** [comment]
@jcoyne It looks to me that permissions checking generally happens in the actor stack. Is that correct? If so, it would seem a bit out of place to have this logic in sanitize_params.

How does this functionality interact with abilities? And if it doesn't, should it?

**Comment by julesies** [comment]
Batch edit permissions seem to need a lot of attn in general, so I added the label. @no-reply not sure if this is a candidate for closing?

**Comment by rjkati** [comment]
This seems to have been fixed in Hyrax 3.0.2. I selected two works, clicked "edit selected" and added a second user as an editor. After save, the new user is present on the "share" tab of both works. @jlhardes

**Comment by jlhardes** [comment]
This issue is no longer occurring so it is closed.
