### ISSUE TITLE
BUG: In Koppie, a collection type can be deleted when it has collections associated to it.

### ISSUE THREAD

**Issue by bwatson78** [samvera/hyrax#6611]
### Descriptive summary

BUG: In Koppie, a collection type can be deleted when it has collections associated to it.

### Steps to reproduce the behavior in User Interface (UI)

1. Log in as admin in the Koppie environment.
2. Visit `Dashboard` (click on user email in upper right corner).
3. Choose `Settings` and then `Collection Types` on the left side of the screen.
4. Click `Create new collection type` on the upper right corner of the screen.
5. Fill in `Type name` with anything and `Save`.
6. Select `Collections` on the left side of the window and then choose `Add New Collection`.
7. For `Select type of collection`, choose the collection type you just created and click `Create collection`.
8. After that collection persists,  go back to Collection Types (`Settings` -> `Collection Types`).
9. Find the collection type you created and click `Delete`; confirm deletion in the pop-up.
10. Click on `Collections` on the left sidebar--this should result in a 500 error.

### Actual behavior (include screenshots if available)

Main Branch

![image](https://github.com/samvera/hyrax/assets/18330149/4d5f1850-1ac2-48c7-b943-05cb08e3bee9)

### Acceptance Criteria/Expected Behavior

- [ ] A modal that communicates that the collection type cannot be deleted because it is associated with persisted collections should open, effectively blocking the deletion of the collection type.

### Rationale (for feature request only)

If a user does delete a collection type with associated collections, this will stop the collections index page from loading after that has processed.

**Comment by rjkati** [comment]
This is also present on pg.nurax. After deleting the collection type in step 9, I can successfully navigate to the `Collections` page, but get the error in the screenshot when I attempt to view a collection of the deleted collection type.
