### ISSUE TITLE
bug in WorkShowPresenter#representative_presenter in inconsistent data state

### ISSUE THREAD

**Issue by jrochkind** [samvera/hyrax#663]
This bug was identified in our app based on sufia@73eaac881de5 and curation_concerns@608b02916cd7, but the some of the relevant code seems to be unchanged in hyrax, so _may_ still exist. 

I haven't completely gotten to the bottom of it, let me know if filing this issue without _full_ diagnosis is not helpful and I would be better to just not file.

In our live app, a GenericWork somehow got into the situation where it had a `representative_id` that was not contained in `ordered_members` or  `members`. 

This caused an apparent infinite loop, I think at calling [WorkShowPresenter#represetative_presenter](https://github.com/projecthydra-labs/hyrax/blob/a3245fb01b39bb40600cadb4743cba5e2f976c0d/app/presenters/hyrax/work_show_presenter.rb#L51-L62)

We are going to add some validations to our local app to prevent a GenericWork from being saved in this state. But to me it's also a bug that this bad data state triggers an infinite loop, and seemed like the presenter-related code should be fixed to not do this too. 

At first I thought the problem was only in the "memoization" code on `representative_presenter`. Since it uses `||=`, nil is not considered a memoized value, and if `member_presenters([representative_id]).first` returns nil, this method will be called over and over again without memoization. 

I think this is a bug, however, fixing this did not fix the problem. In our case, `member_presenters([representative_id]).first` _is_ returning a presenter rather than nil. I'm not sure why -- perhaps even though the id is not in `member_ids` or `ordered_member_ids`, it's still somewhere else in the graph, or it's enough that it's in `work.representative_id` to return a presenter -- but not a presenter that actually works.  

It does return a presenter, but one that triggers an infinite loop when called in some other way. The presenter it returns is a `CurationConcerns::WorkShowPresenter`, I'm not sure if that's appropriate or a bug already. Probably a bug already, because the [caller then calls](https://github.com/projecthydra-labs/hyrax/blob/a3245fb01b39bb40600cadb4743cba5e2f976c0d/app/presenters/hyrax/work_show_presenter.rb#L56-L57) `representative_presenter` again on that thing returned, and I think that's what ends up being an infinite loop. 

Figuring out what's going on would require me to get into the definition of `member_presenters`, which has changed between the sufia version we have and hyrax -- at least where it is located has changed -- I haven't quite figured out where it comes from in hyrax and how it gets mixed in at it's identified call location.  It likely involves the PresenterFactory somehow. 

At this point, I'm afraid I'm bailing on diagnosing upstream for now, and am just going to fix it locally in our app -- with a validation that should keep this kind of data from occurring (we're still not sure how it did, but a validation will hopefully at least give us a stack trace when something tries), as well as a check on our local presenter #represenative_presenter that simply returns `nil` if the `representative_id` is not in `ordered_member_ids` and `member_ids`, since we know that causes an infinite loop, although we still aren't sure why. 

Sorry I wasn't able to get to the bottom of this, I felt that it might be useful to share what I have figured out with the community, in case someone else runs into this problem and/or wants to take it further. But let me know if this is just annoying and it would have been better for me to just keep it to myself.

**Comment by jrochkind** [comment]
Actually, the presenter (with only solrdoc access) doesn't seem to have access to a list of members/member_ids, ordered_members/ordered_member_ids. 

So not quite sure how I can even fix this locally, or if I can. Other than an override of the entire `representative_presenter` with a copy-paste, that checks to see if the presenter returned is a `CurationConcerns::WorkShowPresenter` rather than a `Sufia::FileSetPresenter` as expected, and bails if it is.  This is a really indirect hacky workaround way of checking for the error condition (checking by symptom, not actually fixing the problem somewhere else in the stack which I haven't found), and involves a copy-paste override of a method that I'd rather not override because I don't know if it will change in future versions. 

So I may give up on fixing the problem locally, and just rely on the validator to keep data from getting into this state.

**Comment by no-reply** [comment]
@jlhardes i think we should close this. i think it was fixed by 547c5415fec61e71c21992d99dc697d904eab6bd
