### ISSUE TITLE
Differentiate Single and Batch upload forms (titles?)

### ISSUE THREAD

**Issue by jrochkind** [samvera/hyrax#670]
Our local users in Sufia 7.2 had suggested that the "New Work" and "Batch Create" forms were too similar, and they were getting confused about which one they were on, and could use some differentiation. 

I _think_ the issue remains in Hyrax. 

The most straightforward and easy way to try to address this would be giving the forms different header titles. Right now they both use the same i18n key, which resolve to "Add New Work".

In our local app I made a modification to allow controller-specific i18n overrides for the page title in the relevant form. I wanted to submit this upstream here, but the relevant view has been refactored just enough that I can't just copy and paste, and I"m not sure if people will like my design anyway; I got to move on to other things, but figured I'd share my work here in case anyone wants it, here's how we did this in sufia 7.3:

https://github.com/chemheritage/chf-sufia/pull/415

**Comment by jcoyne** [comment]
In Hyrax the forms are titled: "Add New Work" and "Add New Works by Batch". Can we close this?

**Comment by jcoyne** [comment]
However, we're doing this in a hackier way than @jrochkind has. Our translation is `"Add New %{curation_concern_type}"` and the `curation_concern_type` is `"Works by Batch"`.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> In Hyrax the forms are titled: "Add New Work" and "Add New Works by Batch". Can we close this?

I defer to @jrochkind here.

**Comment by no-reply** [comment]
I'm bumping this to backlog. If this is an urgent issue, could someone chime in and we can restart the design discussion?

@jrochkind @samvera/hyrax-ui-ux-advisors
