### ISSUE TITLE
Unable to remove first Location field

### ISSUE THREAD

**Issue by bbpennel** [samvera/hyrax#6719]
### Descriptive summary

On either the new work or editing form, if the user adds a Location, there is no way to remove the first location added.

### Steps to reproduce the behavior in User Interface (UI)

On nurax:
1. Log in and select to create a new work
2. Fill in required fields
3. Expand the Additional Fields section
4. Go to the "Location" field and input anything ("Canada" for example) and select a value from the dropdown
5. Value will be added, and there is not a means to remove it.

If you then save the work and then Edit it, there is still no UI options for removing this location. After locations after the first one get a "Remove" button.

This at least affects hyrax 4 and 5, I have not tested with 3 but suspect it is an issue there too.

### Actual behavior (include screenshots if available)

The first Location value is displayed in the form without a remove button, while any subsequent values have remove buttons.

<img width="917" alt="Screen Shot 2024-02-26 at 11 14 03 AM" src="https://github.com/samvera/hyrax/assets/969810/c0eafd6f-23a1-41a3-bf95-70c762be3e4e">

### Acceptance Criteria/Expected Behavior

First value should be removable, both for new and existing works.

### Rationale (for feature request only)
Adding a location to a work should not be an irreversible action. Fixing an incorrect location later should be possible through the UI.

**Comment by rjkati** [comment]
I can remove the first location value from a new work on dev.nurax (Hyrax 5.0.0) using the `remove` link. It is also now possible to remove the first location value if it is the only value in the location field.
![location_remove](https://github.com/samvera/hyrax/assets/32644254/831a4c3c-956b-4615-9747-5d435da10556)
