### ISSUE TITLE
Searching by different keywords returns same number of search results

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6724]
### Descriptive summary

Whenever I search by keyword, I get approximately the same number of search results regardless of the keyword.

### Steps to reproduce the behavior in User Interface (UI)

1. Go to pg.nurax as a logged out user
2. In the search box, search for `test`
3. Note that there are 113 results (as of the writing of this ticket)
4. Click Start Over and search for `davis`
5. Note that there are 112 results (as of the writing of this ticket)
6. I've tried searching on other keywords and always get a similar number of search results, regardless of keyword.

### Actual behavior (include screenshots if available)

Searching by keyword returns the same number of search results regardless of the keyword used.

### Acceptance Criteria/Expected Behavior

Searching by keyword should return only results relevant to that keyword.

**Comment by dlpierce** [comment]
Ugh. Once again, joining on the FileSet models is the cause of this. I think I have a real solution, but I would love to know why our existing catalog controller spec isn't catching this.

**Comment by rjkati** [comment]
Tested on pg.nurax and search results are filtering based on keyword now.
