### ISSUE TITLE
Should certain Work Types be available for per admin set?

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#674]
Given admin sets:
  * theses for architecture
  * theses for other schools
  * articles

We only want the Thesis work type to go into the first two admin sets.

**Comment by newmanld** [comment]
Given admin sets:
 I do not want to be required to create a separate admin set for each work type, 
but I do want to be able to indicate which work types are allowed - one, some or all --  for each admin set.

**Comment by ggeisler** [comment]
Discussion in this and tickets #678 and #675 are related and seem to ask whether the selection of admin set for a work should:

* show a default admin set choice based on work type
* limit the other available admin set choices based on work type

Obviously both of those would involve configuration. I think they would be reasonably straightforward to add from the UI point of view but we need discussion from a technical implementation and product point of view. @jcoyne @mjgiarlo @hannahfrost

**Comment by hannahfrost** [comment]
@ggeisler @jcoyne @newmanld 👍 optional configuring certain work types per admin set.

**Comment by jeremyf** [comment]
Based on conversations with @bess @mark-dce @newmanld @hackmastera I believe a requirement for many people will be the following:

* Repository Administrators need to be able choose what Work Types can be created within a given Admin Set
* Repository Administrators need to be able to assign a workflow for a given Work Type within a given Admin Set

The use case is as follows:

As a Repository Administrator, I only want a default admin set, but within that admin set, I want each Work Type to have its own unique workflow.

**Comment by vantuyls** [comment]
@jeremyf that sounds like what i'd expect to see re: work types/admin sets

**Comment by hannahfrost** [comment]
@jeremyf I can get behind that use case. But that means de-coupling workflows from admin sets, correct? What are the ramifications of that?

**Comment by newmanld** [comment]
Do we need a wiki page for use cases?

Is it perhaps not de-coupling workflows from admin sets, but allowing admin sets to bring together choices on work types, participants, workflows (and workflow roles) - and potentially display sets?

Does an admin set need to support more than one workflow?  (For example, my use case did not extend to being able to assign a different workflow for each work type within a single admin set,  but to be able to allow a particular work type (or work types) within a given admin set and that set’s workflow.)

Where do groups fit in?  How do we use our identity management systems to tie ‘all registered users’ or groups of users by status, to a default admin set, for the use case of a self-submission repository where all users (or all ‘faculty’ users) should have rights to at least the default admin set without requiring a repository manager to explicitly assign each user as a participant with a workflow role? (@jeremyf this was the group issue that I think you volunteered to document at LDCX)

**Comment by jeremyf** [comment]
@hannahfrost The ramifications will be:

We need a UI for saying which Work Types are available for an AdminSet.
We need a UI for choosing which Workflow is active for a Work Type within the AdminSet.
When a work type is created, we need to change the actor that assigns its workflow (from AdminSet based decision to AdminSet & Work Type)

There are then considerations for AdminSet roles and how those cascade to Admin Set & WorkType workflow roles.

@newmanld Ah yes, groups…it's coming back to me. We (@laritakr and I) are working through a Group Adapter at Notre Dame to wrangle together the wild and wooly group behavior. This would provide a point for you to implement the UC group logic. That work is being scheduled and vetted.

**Comment by hannahfrost** [comment]
@jeremyf Got it. Thanks.

**Comment by julesies** [comment]
@vantuyls and all, trying to catch up on these discussions and I wanted to see if the outcome here is solving something we talked about a while ago. What we'd really like to do is have a work type like "Senior Honors Thesis" where upon submission, the only place it can submit to is: "Honors Thesis Admin Set". And where there is a review workflow kicked off. So in this case, we do not want the student to have to select any Admin Set, but it is selected for them as designated by the work type and workflow. There a lot of reasons we don't want to have students selecting Admin Sets, which I could elaborate on. 
Is that how others see this working? @hannahfrost

**Comment by newmanld** [comment]
@julesies  - your description fits one of our use cases, where we would like certain users (unless they are acting as a proxy for someone else) to be limited to a specific admin set, and have a work type uniquely authorized for that admin set.

And when there is only one admin set available to users (when not acting as someone else’s proxy), not give them a choice – make the choice for them.

**Comment by julesies** [comment]
@newmanld we are planning that all users can submit to the "default" admin set. So a user like a Senior Theses submitter, would actually have at least 2 admin sets that they should be able to submit to. That is why I was hoping a student submitter would never have to chose an admin set but that by just selecting the work type "Honors Thesis" they would never **have** to go the sharing and relationships tabs. Mostly I'm worried about 1-time users like students having a good experience.

**Comment by newmanld** [comment]
@julesies – That’s completely consistent with what we want to do, and I agree with the goal of presenting no choice of admin set to the user if the UI can make the choice for the user (based on other selections by that user such as work type).

I’m not sure what use cases we have committed to having Admin Sets in Hyrax address.  Given a use case, I’m not sure that the choice of work type will always be the only determinant of what admin set is applicable.  It could be a choice of collection, or it could simply be based on the user’s status (their departmental membership, faculty/staff/student, etc.?)  I think this relates to #675 and #678.

**Comment by ggeisler** [comment]
Below are some mockups that I think might address the use cases brought up in the comments above. The mockups suggest:

* changing the title of the Administrative Sets > Workflow tab to "Work Types"
* moving the renamed tab to be between Participants and Release and Visibility (minor issue I don't feel too strongly about, but seems slightly more appropriate there to me)
* redesigning the content of the Work Types page to enable selection of work types valid for the admin set and, for each work type, selection of the workflow to be used for that work type

Combined with the proposal in #695 to show but disable the Admin Set menu choice for users depositing a work when there is only one Admin Set available for the work being deposited, I _think_ this might address all of the concerns raised in #695, #678, and this ticket (thought it is also very possible that I've overlooked or misunderstood some of those concerns!).

### Default state of Work Types tab
As an admin configuring a new (or editing an existing) admin set, when I get to the Work Types tab I would see all configured work types listed and selected by default:

![default](https://cloud.githubusercontent.com/assets/101482/25147125/3edf5cca-242b-11e7-945f-e551e3bc7e82.png)

### Assigning a workflow to a work type
For each selected work type, I can see the default workflow is assigned, but I can change that assignment (below I have clicked Change for the Thesis work type to reveal the workflow selection options):
![edit-workflow](https://cloud.githubusercontent.com/assets/101482/25147158/65100318-242b-11e7-8e31-c55e1a46caad.png)

### Disabling a work type
If I don't want a given work type to be deposited to this admin set, I can uncheck that work type. The workflow selection for an unchecked work type is disabled:

![disabled](https://cloud.githubusercontent.com/assets/101482/25147203/8c979d88-242b-11e7-82f4-87808c322ce7.png)

**Comment by newmanld** [comment]
@ggeisler I think this has a lot of promise. 

 I assume that the choices of work type that a depositor sees - before they get to the individual or batch work create form -  would then be limited to the work types authorized by that depositor's participant status in admin sets (unless all work types are authorized for all admin sets).  

The choice of work type by the depositor could determine the choice of admin set - relates I think to some of the discussion in #675 and #695.  But, if a work type is included in more than one admin set (maybe due to differences in desired workflow or visibility), and a participant is a depositor in more than one of those admin sets, then they would still have a choice of admin set. 

Given all the discussion re Admin Sets, I hope others will also comment.

**Comment by ggeisler** [comment]
@newmanld:

> I assume that the choices of work type that a depositor sees - before they get to the individual or batch work create form - would then be limited to the work types authorized by that depositor's participant status in admin sets (unless all work types are authorized for all admin sets).

Yep, I believe so.

> The choice of work type by the depositor could determine the choice of admin set - relates I think to some of the discussion in #675 and #695. But, if a work type is included in more than one admin set (maybe due to differences in desired workflow or visibility), and a participant is a depositor in more than one of those admin sets, then they would still have a choice of admin set.

Yep. Which is what we want, I think? If I, as as depositor, have ability to deposit my image work in more than one admin set, presumably I know which is the appropriate one. The potential downside is if I'm a one-time or very occasional user, maybe I don't pay proper attention to the admin set selection and just hit Save and get the current admin set selection without explicitly choosing. But hopefully many one-time or very occasional users will be restricted to a single admin set (e.g., the default set or the "Thesis" admin set) and thus won't be in this situation (because the admin set selection will be disabled for them).

**Comment by julesies** [comment]
I wonder if it would be a good and informative exercise for institutions to mock up their repository under these set up? Kind of like when the PCDM group was modeling real examples to see if their base model worked on real examples?

**Comment by metageeky** [comment]
Here's a use case that I'm not sure how it would work in this mockups. 

> The general goal is to prevent ever having to have users of any role select which AdminSet to place a work into. For certain roles, WorkType X is only offered as an option. Generic users don't get it. Any work added to WorkType X goes in an AdminSet with different permissions/workflows. The key is that we want the assigning of admin sets to be automatic without requiring the user to select one or the other. 

I'm assuming that you would do this in the mockups by turning off WorkType X in one AdminSet and then making it the only one active WorkType in the other AdminSet? That would work but is a bit of a backwards to manage it. I'd almost expect there to be a similar interface where you can define which AdminSets each WorkType can belong to.

Related to this, if a WorkType has multiple AdminSets it can be placed into, can you define a default one for that WorkType? 

We'll also need to consider how any of this decisions interact with the current setting option of whether AdminSets can be selected.

**Comment by julesies** [comment]
@mjgiarlo has there been any more conversation about this ticket? We are now setting up our Hyrax repo and this is an issue we are trying to figure out. Would be interested in figuring out how to get this done and where we might participate.

**Comment by mjgiarlo** [comment]
@julesies Negative. We can consider this for the 2.x series roadmap, of course, especially if y'all or others are inclined to take a hack at it. It may benefit from a conversation -- the above conversation is so long that the issue may be hard for someone to pick up and act on.

**Comment by julesies** [comment]
Just documenting here another reason this is a problem (which we found in testing nurax). If there are any admin sets with restricted visibility and release and that admin set is the last one created (thus the default dropdown admin set), the depositor doesn't realized that and is prevented from entering the visibility and embargo settings they want/need (if that does meet the vis requirements of the particular admin set). You can try a deposit at https://demo.curationexperts.com where there are many admin sets with various settings. In addition, if any admin set with mediated workflow is accidentally chosen, the work goes into the queue.

**Comment by no-reply** [comment]
I think some larger scale admin set discussion is appropriate, but let's close this one out and re-raise this in SIGAHR, if appropriate.
