### ISSUE TITLE
Should admin set widget be on the form? Should it have a different label?

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#675]
<img width="783" alt="screen shot 2017-03-29 at 1 42 32 pm" src="https://cloud.githubusercontent.com/assets/92044/24475694/a55f3f2a-1485-11e7-868a-d9f3bdfd1dcf.png">

@ggeisler @hannahfrost

**Comment by newmanld** [comment]
Having the choice of administrative set on the relationships tab makes it considered by the depositor after selecting work type, and after entering metadata.  May deserve an earlier placement?

**Comment by newmanld** [comment]
See also #678

**Comment by ggeisler** [comment]
@jcoyne For the label, I'd suggest just "Administrative set". The tab title indicates that the goal of the page is to set relationships so I don't think the label has to explicitly instruct the user. That will keep the label shorter and more consistent in style with labels in the other tabs (and form labels generally, where the label just describes the form element and doesn't include verbs - general rule though there are can be reasons to not follow it).

I understand your concern @newmanld but I think one could have the same concern if we put the Relationships tab first or second (why should the depositor have to consider the work's relationships before defining the work itself?) so unless I'm overlooking something I'd suggest sticking with the current tab order.

**Comment by newmanld** [comment]
@ggeisler - If other relationships on the relationships tab make more sense to decide after defining the work, do Admin Sets belong on the relationships tab?

**Comment by newmanld** [comment]
See #674 - if a choice of admin set limits a choice of work types (an option for admin sets, not a required implementation?), then it seems that the choice of admin set would need to be presented to the user before the choice of work types?

**Comment by ggeisler** [comment]
@newmanld Not sure if I'm misunderstanding something, but I believe that by the time the user is on the Add New Work page they have already selected the type of work they want to add. 

So the choice of admin set doesn't limit the allowable work type; rather, if we were to implement @vantuyls suggestion in #678 then I believe the work type the user is currently adding would limit the admin set choices they had to choose from when making the admin set assignment.

**Comment by newmanld** [comment]
A use case may help to clarify why I am asking about work types.  @vantuyls - your use cases may be different?
   As a repository manager 
       I need to create an admin set that supports the theses (eTD) work type, and only this work type.  I want to authorize individuals from our Graduate School as submitters for this admin set, and no other individuals.
      I need all other admin sets to support a choice of all other work types, excluding theses.

If the work type is selected first, then users who are not authorized for theses would see this work type but then not be able to complete the submission, because no admin set would apply?  Or would some other logic prevent this from happening?

Is this use case outside of the scope and purpose of admin sets?

**Comment by ggeisler** [comment]
I'm not the right person to answer this, but I wonder if this following is reasonable:

- we know the current user is a member of the Graduate School (there is a graduate_school group)
- we only show the theses work type in the Add New Work selection list if the user is in the graduate_school group
- the administrator associates only the theses work type with the eTD admin set

If this is all technically possible and we decide it makes sense to add the supporting features, then I think the resulting user experience would be fine and support your specific use case, @newmanld.

**Comment by hannahfrost** [comment]
@ggeisler and I have some ideas about improving the Add New Work tabs. Will add a separate ticket about that shortly, @jcoyne @newmanld @vantuyls. It will be a start.

The flow around constrained/specified work types per admin set could get a little tricky if a user is associated with multiple admin sets (one for theses, one for research data, etc.). I think we need to collect a bunch o' use cases and discuss on a call.

**Comment by newmanld** [comment]
+1 to collecting the use cases and discussing.

**Comment by jeremyf** [comment]
This relates to #674

**Comment by mjgiarlo** [comment]
Tagging @projecthydra-labs/hyrax-ui-ux-advisors too

**Comment by no-reply** [comment]
Closing this pending a more serious reconsideration of the deposit form.
