### ISSUE TITLE
Collections dashboard page includes roles not inside required context

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6776]
### Descriptive summary

On dev.nurax.samvera.org (Hyrax 5.0.1), the `All Collections` and `Your Collections` links have role elements that only make sense in the context of other roles and therefore do not meet WCAG AA requirements

### Steps to reproduce the behavior in User Interface (UI)

1. In Chrome, download the Site Improve browser extension
2. Go to https://dev.nurax.samvera.org/dashboard/my/collections?locale=en and run the Site Improve browser extension

![roles_collections_page](https://github.com/samvera/hyrax/assets/32644254/b14b9034-40bd-4ae4-9823-892bff1f77b3)

**Comment by aahurford** [comment]
tested and confirmed in pg

**Comment by christhepianist** [comment]
Confirmed that this is no longer an issue.
