### ISSUE TITLE
Pages page includes roles not inside required context

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6787]
### Descriptive summary

On dev.nurax.samvera.org (Hyrax 5.0.1), the `About`, `Help`, `Deposit Agreement` and `Terms of Use` tabs on the `Pages` page have role elements that only make sense in the context of other roles and therefore do not meet WCAG AA requirements

### Steps to reproduce the behavior in User Interface (UI)

1. In Chrome, download the Site Improve browser extension
2. As an admin user, go to https://dev.nurax.samvera.org/pages/edit?locale=en and run the Site Improve browser extension

![pages_role_list](https://github.com/samvera/hyrax/assets/32644254/1af8f02b-4490-4564-9088-8a87205048e4)

### Related Work
#6776

**Comment by aahurford** [comment]
tested and confirmed on pg

**Comment by christhepianist** [comment]
Tested and confirmed that this is no longer an issue.
