### ISSUE TITLE
Hidden element has focusable content on Collection edit page

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6798]
### Descriptive summary

On dev.nurax.samvera.org (Hyrax 5.0.1), the thumbnails in the `Works` list on the `Edit Collection` page have an attribute `aria-hidden="true"` and contain focusable elements and do not meet WCAG AA requirements

### Steps to reproduce the behavior in User Interface (UI)

1. In Chrome, download the Site Improve browser extension
2. As an admin user, go to https://dev.nurax.samvera.org/dashboard/collections/bc386j44x?locale=en and run the Site Improve browser extension

![hidden_element_focus](https://github.com/samvera/hyrax/assets/32644254/9f5af626-2d16-4765-be66-f8917f3b7398)

**Comment by nhomenda** [comment]
Tested and confirmed this behavior no longer occurs on https://dev.nurax.samvera.org/dashboard/collections/bc386j44x?locale=en
