### ISSUE TITLE
Links are not clearly identifiable

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6805]
### Descriptive summary

On dev.nurax.samvera.org (Hyrax 5.0.1), the `Add New Work` and `Contact form` links are not clearly identifiable as links and do not meet WCAG AA requirements

### Steps to reproduce the behavior in User Interface (UI)

1. In Chrome, download the Site Improve browser extension
2. Make sure that batch upload functionality is enabled
3. Go to https://dev.nurax.samvera.org/batch_uploads/new?locale=en&payload_concern=GenericWork and run the Site Improve browser extension
![batch_add_link_color](https://github.com/samvera/hyrax/assets/32644254/234a83f7-87e1-493a-9b3e-c6c226b0326c)

**Comment by rjkati** [comment]
This issue is also present on the following pages:

- [Add new work (files tab)](https://dev.nurax.samvera.org/concern/generic_works/new?locale=en#files) - `contact form` link
- [Add new work (descriptions tab)](https://dev.nurax.samvera.org/concern/generic_works/new?locale=en) - `batch upload` link
- [Edit work (files tab)](https://dev.nurax.samvera.org/concern/generic_works/70795791z/edit?locale=en#files) - `contact form` and `SHERPA/RoMEO` link if public visibility selected
- [Edit work (description tab)](https://dev.nurax.samvera.org/concern/generic_works/70795791z/edit?locale=en) - `GeoNames web service` and `SHERPA/RoMEO` link if public visibility selected
- [Edit work (relationships tab)](https://dev.nurax.samvera.org/concern/generic_works/70795791z/edit?locale=en#relationships) - `SHERPA/RoMEO` link if public visibility selected
- [Edit work (sharing tab)](https://dev.nurax.samvera.org/concern/generic_works/70795791z/edit?locale=en#share) - `SHERPA/RoMEO` link if public visibility selected
- [Edit file (permissions tab)](https://dev.nurax.samvera.org/concern/file_sets/p2676v71k/edit?locale=en#permissions_display) - `SHERPA/RoMEO` link

If it is preferable to create individual tickets for each instance of this issue, please comment here.

**Comment by christhepianist** [comment]
Tested and confirmed that this is no longer an issue.
