### ISSUE TITLE
Make viewing the "Workflow Roles" page configurable

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyrax#681]
### Descriptive summary

For most instances of Hyrax, the Workflow Roles page is not needed or relevant. We should make it possible to flip on the inclusion of this page in the dashboard menu for those cases where it is needed.

### Rationale

When an admin set is created, the roles and workflow are configured. Given that, the page visible on the dashboard, Tasks > Workflow > Roles is superfluous.

But we know that there are some users of Hyrax who need that screen for more advanced workflow/role configuration, so we don't want to get rid of the page. Instead we should make it possible to flip on its visibility in the dashboard menu. 

Therefore, let's add a toggle switch on the Configuration > Settings page. The feature should be called "Workflow Roles page" and its associate description is "Show page for special workflow role configuration". By default this menu item should not be available.

**Comment by mjgiarlo** [comment]
@hannahfrost How high should the priority of this be?

**Comment by jeremyf** [comment]
@laritakr and I are following up on this requirement, though we'll need to talk it through.

A key consideration is that the workflow roles are arbitrary (we could have "Professor", "Reviewer", "Skipper", and "Editor" all mixed in as custom workflow roles). The permission template participants are a hard and fast "Manager", "Depositor", "Viewer".

My understanding of the "Depositor" participant is that they can deposit something into the admin set. For the workflow, if they have the "Depositing" role, it is scoped only to the work that they deposited. We want to avoid giving the "Depositing" role for an item in a workflow to all participants that are "Depositor"s into the admin set.

**Comment by mjgiarlo** [comment]
@jeremyf Good call! Thanks for digging into this.

**Comment by rjkati** [comment]
In Hyrax 3.0.2, the "Workflow Roles" page appears for repository administrators. There is not a configuration option in "Settings" to toggle the visibility of the page. @jlhardes

**Comment by jlhardes** [comment]
If there is a way to create custom roles, it doesn't seem to be available through the Hyrax dashboard interface. I would be interested to know if this is still something that is possible to do and how it is done.

A new admin set and a new collection only have the choices of Manager, Depositor, Viewer for roles and the workflow roles that are shown on that Workflow Roles page are approving, depositing, and managing. The "approving" role is on each admin set and collection regardless of the workflow being one-step mediated or default but I think the approving role is only used in the one-step mediated workflow process (and I think those who are given Manage permissions are in the workflow roles of approving and managing for admin sets with that workflow).

I think this Workflow Roles page is a useful view of roles across collections and admin sets. I think it is worth leaving in place for admin users to see. I am closing this issue and leaving the Workflow Roles page in place without a configuration toggle for visibility.
