### ISSUE TITLE
Instructions for creating hyrax in an existing appliction

### ISSUE THREAD

**Issue by cam156** [samvera/hyrax#682]
### Descriptive summary

within  hyrax master the readme there are no instructions for installing hyrax within an existing application

We figured out that you needed to run `rails generate hyrax:install`  and  `rails db:migrate`

**Comment by jcoyne** [comment]
@cam156 that sounds right. Can you add that to the Readme?

**Comment by no-reply** [comment]
I don't know if this works or is required. Closing unless someone would like to volunteer to test and update.
