### ISSUE TITLE
unsupported ARIA attributes in expanded Your Activity and Settings menus

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6840]
### Descriptive summary

On dev.nurax.samvera.org (Hyrax 5.0.1), the `Your Activity` and `Settings` menus contain unsupported ARIA attributes when expanded.

### Steps to reproduce the behavior in User Interface (UI)

1. In Chrome, download the Site Improve browser extension
2. Go to https://dev.nurax.samvera.org/dashboard?locale=en, expand the `Your Activity` menu and run the Site Improve browser extension
![aria-menu](https://github.com/samvera/hyrax/assets/32644254/d4b68690-d76d-4481-996f-895e73868fbe)

**Comment by aahurford** [comment]
tested and confirmed

**Comment by christhepianist** [comment]
Confirmed that this is no longer an issue.
