### ISSUE TITLE
  BUG: Updating a Collection's visibility through the UI, if created in a Hyrax v5.x/Fedora v6.5/Valkyrie v3.3/Pair-Tree'ed application, doesn't persist to Fedora

### ISSUE THREAD

**Issue by bwatson78** [samvera/hyrax#6864]
### Descriptive summary

BUG: Updating a Collection's visibility through the UI, if created in a Hyrax v5.x/Fedora v6.5/Valkyrie v3.3/Pair-Tree'ed application, doesn't persist to Fedora

### Steps to reproduce the behavior in User Interface (UI)

1. Start a Docker instance of Sirenia
2. Log in as a user capable of creating a collection object
3. Venture to Dashboard, click on Collections, and then Add a new Collection
4. Choose a User Collection, and then fill in all required fields
5. Save the Collection and wait for that object's edit page to load with a positive persistence message displaying
6. Click on the Discovery tab and change the visibility to public
7. Save and observe that the visibility doesn't reflect the desired option
8. Open a rails console, pull the Valkyrie object by id, and observe that the visibility hasn't been changed.
9. Open the Fedora UI, locate the object, and observe that it has also not been updated.

### Acceptance Criteria/Expected Behavior

- [ ] Changing the visibility in the UI should reflect in the show page, Valkyrie object, and Fedora UI page.

### Related work

https://github.com/samvera/hyrax/issues/6349

**Comment by rjkati** [comment]
This behavior also applies to works. When I attempt to change the visibility of a work via the UI, I get a `Failed save on # undefined method 'split' for nil:NilClass` error and the visibility of the work and files do not update.

![undefinedmethod](https://github.com/user-attachments/assets/5c0c3ef6-c12f-4d62-a3bb-0f23ce55cbe2)

I'm not sure if a new ticket for works is needed given that the behavior in the UI is similar to Collections, but I'm happy to create one if that's better for folks.

**Comment by rjkati** [comment]
In Hyrax 5.0.1 using sirenia, I'm able to change the visibility of a collection successfully in the UI, but my edit access is removed if I create the collection as a non-admin user. Since I can't replicate the visibility issue described in this ticket for collections, I'll close this ticket and open two new ones for the edit access issue and work issue described above.
