### ISSUE TITLE
Updating a work visibility in sirenia generates Failed save on # undefined method `split' for nil:NilClass message in sirenia

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6874]
### Descriptive summary

In Hyrax 5.0.1 running Sirenia, when I attempt to update the visibility of a work, I receive a `Failed save on # undefined method `split' for nil:NilClass` message and the visibility does not update.

### Steps to reproduce the behavior in User Interface (UI)

1. Run a local build of Sirenia using Docker
2. Log in and navigate to `Dashboard` -> `Works`
3. Click on the title of a work that you've already deposited (or deposit a new one if you don't have any works)
4. Click Edit
5. Select a different visibility setting (I went from `Public` to `Institution`) and click `Save Changes`
6. Observe message `Failed save on # undefined method `split' for nil:NilClass`
7. Go back to `Dashboard` -> `Works` and observe that visibility has not updated

![undefinedmethod](https://github.com/user-attachments/assets/a6e1d5d4-2e0f-4238-8b49-54d654a149fa)

### Actual behavior (include screenshots if available)

Attempting to change the visibility of a work generates `Failed save on # undefined method `split' for nil:NilClass` message and does not update the visibility.

### Acceptance Criteria/Expected Behavior

Attempting to change the visibility of a work should update the visibility accordingly

### Rationale (for feature request only)

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Related work

#6864

**Comment by rjkati** [comment]
This issue does not occur on dev.nurax or pg.nurax

**Comment by bwatson78** [comment]
I will refocus on making this change on the Valkyrie level, unless @dlpierce is already working on this.

**Comment by bwatson78** [comment]
PR in Valkyrie (https://github.com/samvera/valkyrie/pull/960, already merged) will fix this issue.

**Comment by rjkati** [comment]
This works while running the `valkyrie-fedora-fix` branch locally. I can change the visibility of a work without getting an error message
