### ISSUE TITLE
Creating, modifying or deleting a collection type in Sirenia takes a really long time

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6888]
### Descriptive summary

When I attempt to create, modify or delete a collection type in Sirenia, the action takes a really long time to complete.

### Steps to reproduce the behavior in User Interface (UI)

1. Log into your local build of Sirenia as an admin
2. Navigate to Dashboard -> Collection Types
3. Try to do an action on the Collection Types page

Note that each task completes as expected, it just takes forever to do so.

### Actual behavior (include screenshots if available)

All testing occurred in my local build of Sirenia using Hyrax 5.0.1 in Google Chrome on Windows

- Loading the collection types page: 35 seconds
- Creating a new collection type: 7 minutes, 8 seconds
- Modifying a collection type (I disabled Sharing on the Settings tab): 6 minutes, 17 seconds
- Deleting a collection type: 1 minute, 43 seconds

For each task, Docker displays this message while running the task, in case it is helpful:
![sirenia_collectiontypes](https://github.com/user-attachments/assets/0b6da4a6-9e7f-492f-8eae-4ef3d2fa0fbc)

**Comment by eporter23** [comment]
@rjkati - I tested some of this in our deployed Emory application also, so it's probably a little faster than the docker image, but still quite slow.
Loading the collection types page: 40 sec
Create a new Collection Type: 2 min 49 seconds
Modify the new Collection Type (added a badge color): 58 seconds
Delete the new Collection Type: 44 seconds

**Comment by dlpierce** [comment]
I've noticed a similar pattern in the logs while running sirenia specs, so this likely has a large impact on rspec run time and performance in general.

**Comment by cjcolvar** [comment]
I think I found the source of the problem and have a PR to resolve it: #6925
