### ISSUE TITLE
Select an Action in Items list on Work view page does not minimum size requirements for interactive elements

### ISSUE THREAD

**Issue by rjkati** [samvera/hyrax#6932]
### Descriptive summary

On dev.nurax.samvera.org (Hyrax 5.0.1), the selection options in the `Select an Action` drop down menu of the `Items` list on a work page do not meet WCAG AA minimum size requirements for interactive elements

### Steps to reproduce the behavior in User Interface (UI)

1. In Chrome, download the Site Improve browser extension
2. Navigate to a work for which you have edit permissions
3. In the Items list, click the `Select an action` menu next to a file to open it. The issue will not display if the menu is inactive.
4. Run the Site Improve browser extension

![interactive_element_min_size](https://github.com/user-attachments/assets/6797188c-a950-49ab-99f0-b3428340504e)

**Comment by aahurford** [comment]
Tested, no longer a AA issue, although my options in this menu appear differently:

![Image](https://github.com/user-attachments/assets/4a4674c5-7906-4b5f-870b-0e643f290acd)
