### ISSUE TITLE
Add itemtype to _tag and _rights partials for work show pages.

### ISSUE THREAD

**Issue by straleyb** [samvera/hyrax#808]
This is more of a discussion point, but we were talking here at OSU and came upon the discussion of itemtypes on the show pages for works. Most of them have itemtypes as well as some other attributes in the html, but a few of them do not, notably _tag and _rights. We were going to make the customizations here on our own, but thought about pushing it into Hyrax instead. We would be using the uris https://schema.org/keywords for tag and https://schema.org/license for rights respectively. Would this change be accepted. Im unaware of any side effects it might have or possible use cases for this. 

Here is one of the tickets we have in Scholars-Archive about it. 

https://github.com/osulp/Scholars-Archive/issues/306

**Comment by mjgiarlo** [comment]
Thanks for the issue, @straleyb; this is a welcome contribution. :)

I'm in favor of mapping these terms to schema.org properties. I'm cool with keywords for tag. I wonder if license mightn't be a better fit for the new "license" property. It'd be great to find another property to hook up to rights statements.

Calling all @projecthydra-labs/hyrax-metadataists! What say you about the above?

**Comment by cmh2166** [comment]
+1 tag => schema:keywords

agree license (not rights statement) should => schema:license

option for rightsStatement: roll our own (extend schema) referencing dcterms:rights (see http://journal.code4lib.org/articles/6400 section on extending schema.org, exactly this case).

**Comment by rjkati** [comment]
Closed as part of older ticket review. If this work is still needed, please reopen this ticket.
