### ISSUE TITLE
CC4.0 license configuration

### ISSUE THREAD

**Issue by straleyb** [samvera/hyrax#810]
This is a ticket which poses the idea that the configuration for Licenses be updated to include the CC4.0 licenses and URIs. To keep the licenses updated, this seems like a fairly logical step for updating the configuration. 

I see that work has been done to toggle licenses on and off. What our hopeful goal is, is to keep the CC3.0 licenses active for the items that have those licenses already, but for any new works being ingested only allow them to use the CC 4.0 licenses. 

Is this already working the way I described? I would also like to know if the community backs this change here in Hyrax and if so, we can move forward with making this change.

**Comment by mjgiarlo** [comment]
@straleyb I support updating the CC licenses to 4.0, and marking the 3.0 ones to `active: false` (which accomplishes the "keeps them active for items that have them already but does't allow them to be selected anew" requirement, AFAIK). See here: https://github.com/projecthydra-labs/hyrax/blob/master/lib/generators/hyrax/templates/config/authorities/licenses.yml

Thoughts on this, @projecthydra-labs/hyrax-metadataists ?

**Comment by ruthtillman** [comment]
@mjgiarlo Currently dealing with this exact issue in a less elegant way so yes please. Allowing us to maintain 3.0 ones while + only offering new would be aces.

The only concern I might see would be things which were initially put up under an older license which we'd have to add in, we had to add an additional 3.0 license for a journal which did its author licenses that way, but if we could add new licenses and mark them as `active: false` so that they could only be accessed through batch ingest vs. any kind of deposit...that would be perfect.

**Comment by noraegloff** [comment]
Bumping this issue - @samvera/hyrax-metadataists still support updating CC licenses to 4.0  while maintaining support for grandfathered-in CC 3.0 licenses for existing items.

**Comment by no-reply** [comment]
i think all that is needed for this is a configuration update. would anyone be willing to take on adding the cc 4.0 licenses to https://github.com/projecthydra-labs/hyrax/blob/master/lib/generators/hyrax/templates/config/authorities/licenses.yml

**Comment by rjkati** [comment]
Hyrax 3.0.2 still shows CC 3.0 licenses, not CC 4.0. @jlhardes

**Comment by jlhardes** [comment]
The licenses.yml linked above does include CC4.0 licenses and they are set as `active: true` and CC3.0 are listed and set as `active: false` but we are still not seeing CC4.0 licenses available. Does something else need to happen for this to take effect?

**Comment by jlhardes** [comment]
CC 4.0 licenses are available in the License drop-down list on all work types on https://pg.nurax.samvera.org but https://dev.nurax.samvera.org is not offering CC 4.0 options yet for any work types. It looks like the code work might be done but implementation is more than just updating the code?

**Comment by rjkati** [comment]
We confirmed that the display issues on dev.nurax are due to an outdated config file, but the work has been completed.
