### ISSUE TITLE
New, Edit, Show pages for Collections needs admin sidebar

### ISSUE THREAD

**Issue by ggeisler** [samvera/hyrax#818]
It looks like only the Collections index page currently uses the admin sidebar. The new, edit, and show pages, when a user is looking at their own collection, should also have an admin sidebar:

### New:
![new_collection____hyrax](https://cloud.githubusercontent.com/assets/101482/25288816/e840dc4c-267b-11e7-833d-0b4acfe4f5fa.png)

### Edit:
![edit_collection_research_datasets____hyrax](https://cloud.githubusercontent.com/assets/101482/25288859/0b6728fc-267c-11e7-966b-9de91881e5fc.png)

### Show:
![research_datasets____hyrax](https://cloud.githubusercontent.com/assets/101482/25288841/fdf144c8-267b-11e7-9848-db2d23f05df9.png)

**Comment by jcoyne** [comment]
The show page would probably want to be a new route to indicate it is being viewed in the context of the dashboard.  I don't think we'd split the new and edit, just change their layout.

**Comment by julesies** [comment]
Works in Hyrax 2.1
