### ISSUE TITLE
Add panel heading with work count to Works index page

### ISSUE THREAD

**Issue by ggeisler** [samvera/hyrax#823]
The "All Works" and "Your Works" tabs of the Works index page would be improved if they provided a prominent indication of the number of works the user or repository owns. This was specified in the [mockups for the Works pages](https://github.com/projecthydra-labs/hyku/issues/447) but while other aspects of those mockups were implemented this doesn't appear to have been.

I suggest adding a `<div class="panel-heading">` (see the show page for an Admin Set for an example) with a `<p>` containing the string with the works count. For example:

`<p>You have <strong>18 works</strong> in the repository</p>` for the Your Works tab and  `<p<strong>18 works</strong> in the repository</p>` for the All Works tab. (Though I'd use a span with a class that is styled in CSS to wrap the "18 works" to make is bold rather than the `strong` tag.)

So it would look something like this:

![works](https://cloud.githubusercontent.com/assets/101482/25297697/5e183d66-26a4-11e7-85e5-711747d4ccea.png)

**Comment by julesies** [comment]
This is working since 2.1
