### ISSUE TITLE
All Works table needs checkboxes so admin can perform bulk actions

### ISSUE THREAD

**Issue by ggeisler** [samvera/hyrax#824]
The "Your Works tab of the Works index page has checkboxes in the first column so the user can select multiple works and perform actions on them in bulk:

![works](https://cloud.githubusercontent.com/assets/101482/25298037/9b63f924-26a6-11e7-8ed6-53e8ef5ef7ed.png)

The "All Works" does not include the same checkboxes, but I believe it should:

![works](https://cloud.githubusercontent.com/assets/101482/25298048/b8ed072e-26a6-11e7-985a-413c62e7146e.png)

Only repository administrators or repository managers should see the "All Works" tab (at least, I assume that is the policy we are currently using) and those roles have edit access on all repository works. So I think we want to enable a user who can access the All Works tab to perform bulk actions on those works. Thus we need the same checkboxes as on the Your Works tab.

**Comment by no-reply** [comment]
This issue was closed somewhere along the way.
