### ISSUE TITLE
AdminSet allows for duplicate 'title' 

### ISSUE THREAD

**Issue by revgum** [samvera/hyrax#848]
An administrator is currently able to create an AdminSet having the same title as another one in the system. Technically this makes sense, but from a practical standpoint it would lead to confusion on the UI for choosing which AdminSet to associate a new work to. 

I think it would be worthwhile to enforce uniqueness on the AdminSet.title.

**Comment by hannahfrost** [comment]
:+1:

**Comment by mjgiarlo** [comment]
Thoughts on this, @projecthydra-labs/hyrax-code-reviewers @projecthydra-labs/hyrax-ui-ux-advisors ?

**Comment by escowles** [comment]
👍  to requiring AdminSet titles to be unique to avoid confusion when choosing them from a menu

**Comment by jeremyf** [comment]
Does Fedora allow for enforcing this? Because uniqueness validation is best served by the persistence layer - traditionally database constraints.

Reference: https://robots.thoughtbot.com/the-perils-of-uniqueness-validations

**Comment by no-reply** [comment]
At present, I think this is a won't-fix. We can't reliably ensure title uniqueness, short of making titles IDs. 

Administrators have recourse to (re)name admin sets as they please, and I think that may be the best we can offer here without significant effort.
