### ISSUE TITLE
checksum/fixity confusion

### ISSUE THREAD

**Issue by jrochkind** [samvera/hyrax#867]
Our Sufia 7.3 app appears to be showing an MD5 checksum in admin fileset show page. 

Not sure yet exactly where this comes from, not sure if a newly generated app would do the same. 

Fedora -- at least by default -- uses SHA1 for fixity checking and 'modeshape' storage on disk. I don't believe we've changed our Fedora defaults. 

It would make more sense for the admin checksum to match the checksum fedora is using for it's thing. Avoids developer confusion and confusion over fixity checking and developing restoration processes. 

@jcoyne suggested this might be good for a tech call; I'm not participating in tech calls at the moment, so I'll leave that to @jcoyne or @hackmastera .

**Comment by mjgiarlo** [comment]
Copied from Slack:

@mjgiarlo :speech_balloon: 
> I'm guessing the MD5 checksum is the one generated by FITS. the long story short version: FITS gives you a bunch of information about your files that you might care about for curation or preservation of those files over time. we index that information and make it searchable. you could use it, for instance, to find soon-to-be-obsolete file formats, and remediate/update them.
>
> One of the bits of information provided by FITS is the MD5 checksum *before* it went into Fedora, so that when you get it out of Fedora, you could verify Fedora itself didn't muck up your file.
>
> Perhaps the characterization metadata UX could be better, to make clearer where that data comes from and what its intent is? A little question mark/info badge with a tooltip could work there to explain what's what.

Thoughts from @projecthydra-labs/hyrax-ui-ux-advisors pls?

**Comment by jrochkind** [comment]
it would be awfully convenient to me if the “characterization metadata” at least also had the fedora fixity checksum, even if both are necessary. 

If hte point is showing checksum pre-fedora-ingestion as distinct from fedora checksum, I think it would be even BETTER if consistent checksum algorithm were used in both places. Then it would be super obvious if the checksum had changed in fedora ingest (a corruption there). 

Right now... I guess you've got to manually calculate md5 of the thing in fedora, and make sure it still matches the recorded pre-ingest md5 checksum?

**Comment by newmanld** [comment]
There's also some information on the filesets show page described as "Audit Status".    I assume that once audits are turned on this will be an audit of the Fedora, not the FITS, checksum?  If so another reason to report the Fedora checksum on this page, as well as the FITS checksum if that gives us information about ingest.  

I agree with @jrochkind that the algorithm should be the same, so that if the checksum reported by FITS does not match the checksum reported by Fedora on ingest, we know.  

From http://fedorarepository.org/fedora-and-digital-preservation: 
>Fixity2
>A range of digest algorithms (MD5, SHA-256, etc.) can be configured for calculating, storing, and recalculating checksums
>A default algorithm can be configured
>An algorithm can be specified on resource creation
>An algorithm can be changed after resource creation
>A SHA-1 checksum is calculated and stored on file ingest
>If a SHA-1 checksum is provided with an ingest request, it will be compared with the calculated value on ingest. A mismatch will cancel the ingest
>The SHA-1 checksum can be recalculated and compared with the stored value at any time
>Audit
>Preservation metadata, modeled using the RDF-based PREMIS and PROV-O ontologies, may optionally be generated by repository events and stored in the repository; these are also accessible via external triplestores for enhanced querying.

I'm interested in not just resolving the confusion but making sure we are using the information that the checksums tell us.  It would be helpful to:
* Create configuration instructions for running Audit and confirming that the results of an audit are displayed on the fileset show page.
* Offer reporting options that allow repository administrators to comprehensively find mismatched checksums upon ingest and to discover checksums that an Audit flags as not passing.

Looks like Fedora provides the underpinning but we could push this further in our GUI for admins?

**Comment by jrochkind** [comment]
@newmanld I've been trying to figure out what the built-in audit service stuff actually does, i should write that up and share it. 

But yes, it's the fedora checksum that the fedora fixity service (which the built in stuff uses) is checking. 

The built-in stuff is not really suitable for _our_ needs in several ways, I'm going to try to make PR's if I can to improve it, but it's a bunch of different classes factored differnetly than I would.

**Comment by mjgiarlo** [comment]
Brief response: in Hyrax `master` (for 2.x), we've renamed all the "audit" stuff to "fixity" to make its intent clearer.

**Comment by jrochkind** [comment]
Not directly related to this particular issue except as background, my write-up on what I discovered the existing fixity checking service code does, vs what we at least at CHF would need or prefer. 

https://bibwild.wordpress.com/2017/05/01/exploring-and-planning-with-sufiahyraxfedora-fixity-validation/

**Comment by newmanld** [comment]
@jrochkind - this is solid work in the write-up you shared.  I need to find time to re-read but think I agree with most if not all of your questions and points.  Bigger context than this original issue about which checksum to display - but worth some development.

**Comment by no-reply** [comment]
Is this fixed by: https://github.com/samvera/hyrax/issues/867#issuecomment-298361442

or do we have more work here?
