### ISSUE TITLE
Check for `destroy` permissions before showing 'delete' buttons / actions in views

### ISSUE THREAD

**Issue by hackmastera** [samvera/hyrax#868]
### Affects versions

Hyrax head, Sufia 7.3

### Rationale

An app changing destroy permissions currently has to override views for them to impact the UI

### Expected behavior

I should be able to limit deletion in my app just by changing my ability file

### Actual behavior

Hyrax views assume anyone who can edit can also delete; do not check for `destroy` ability.

### Related work
 
Here are the views overrides I created in my app:

Work show page: https://github.com/chemheritage/chf-sufia/commit/62e79eaa69fe9b5a246306ddf70b1389affef32b
File show page: https://github.com/chemheritage/chf-sufia/commit/994fcfc1df97290093f13ab1a5ed5004aa06f313
'my works' list action: https://github.com/chemheritage/chf-sufia/commit/50fe4287ca5aada7123d0c9e53901dd511334c68
'batch edit' delete button: https://github.com/chemheritage/chf-sufia/commit/069bad139070c346331ec858ffcbd78ce1e065bc

**Comment by julesies** [comment]
@no-reply not sure if this is still an issue.

**Comment by mcdowney** [comment]
Closing as no longer relevant
