### ISSUE TITLE
i18n refactor and testing

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#876]
NOTE: This issue is suitable for someone new to the community.

### Descriptive summary

Refactor to remove unused translations and add missing translations.

### Rationale

gem i18n-tasks provides a command line that checks for...
* missing translations (those in code but not in locale file) using `i18n-tasks missing`
* unused translations (those in locale file but not in code) using `i18n-tasks unused`

These can be used to identify potential translations to add or remove.  Unused translations can be added as exceptions to [config/i18n-tasks.yml](https://github.com/projecthydra-labs/hyrax/blob/i18n_testing/config/i18n-tasks.yml) if they should be retained even though they are unused.

The gem also provides a spec test that validates that the missing translations and unused translations lists are empty.  This can be used to confirm that new issues with i18n are not introduced in the future.

### Expected Behavior

`i18n-tasks missing` returns empty array indicating there are no missing translations
`i18n-tasks unused` returns empty array indicating there are no unused translations

### Actual Behavior

`i18n-tasks missing` returns 31
`i18n-tasks unused` returns 152

NOTE: Some of the missing may actually be coming from other gems.  Additional investigation required.  Also, some of the unused need investigation before removing.

### Additional Information

Initial setup of i18n-tasks in branch [i18n-testing](https://github.com/projecthydra-labs/hyrax/tree/i18n_testing)

[Documentation for i18n-tasks gem](https://github.com/glebm/i18n-tasks)

**Comment by jcoyne** [comment]
I don't think this gem works very well. I spot checked the `i18n-tasks missing` and it was able to resolve all of them. When I deleted the `i18n-tasks unused` ones, the test suite gave me missing translation errors.

**Comment by elrayle** [comment]
The configuration file has a lot more options in it than I initially setup.  It would be part of this issue to explore the missing and unused to determine if they are the result of incorrect configuration or actual missing and unused.
