### ISSUE TITLE
Work analytics page should have real title tag

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#883]
### Descriptive summary

Hyrax 2.0.0.alpha

Work analytics show page should have the Work Title (or a truncated version thereof) in the <title> tag of the page.

### Rationale

This is best practices for website things. 

### Expected behavior
Work title appears in the title tag in the HTML

### Actual behavior
Work title does not appear in the title tag in the HTML

### Steps to reproduce the behavior

1. go to a work
1. select Analytics button
3. see that the title tag says: Work Stat // Hyrax

### Related work
#885

**Comment by julesies** [comment]
closed per https://github.com/samvera/hyrax/pull/2709
