### ISSUE TITLE
Right statement not showing up on show page

### ISSUE THREAD

**Issue by straleyb** [samvera/hyrax#886]
One of the pieces of metadata that may be quite important for a user to look at is the right statement. Currently, the rights statement is not showing up in the show page. 

One question would be, does hyrax have a usecase for showing rights  statements, would it be useful to the user? I have a fix locally which includes adding 

```
<%= presenter.attribute_to_html(:rights_statement) %>
```
to the `attribute_rows.html.erb` file then adding

```
attribute :rights_statement, Solr::Array, solr_name('rights_statement')
```
to metadata.rb in app/models/concerns/hyrax/solr_document

Then adding the `:rights_statement` symbol to the list of delegated methods in the `WorkShowPresenter`

I think this would fix it in a way that would allow people to see the rights statement in the show page.

**Comment by mjgiarlo** [comment]
Yes, this is a bug. Would welcome a fix!

**Comment by acklose** [comment]
@jlhardes This issue is occurring in Valkyrized Hyrax in Nurax PG. It is not a problem in Hyrax-Dev.

**Comment by jlhardes** [comment]
This issue is re-occurring or has been re-introduced in Valkyrized Hyrax (nurax-pg) so I am reopening to have this issue history available if it is helpful. It is not occurring in Hyrax 4.0.0beta1 on nurax-dev.

**Comment by jlhardes** [comment]
Nevermind, this issue is fixed and closed. I will create a new issue for this problem in Valkyrized Hyrax and connect this closed issue there for the history.
