### ISSUE TITLE
Inconsistent terms

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyrax#911]
<img width="267" alt="screen shot 2017-05-05 at 1 43 44 pm" src="https://cloud.githubusercontent.com/assets/92044/25759623/ecd34394-3198-11e7-989f-a94f5f02e924.png">

@ggeisler is it "mine" or "yours" ?

**Comment by ggeisler** [comment]
We inherited the use of "My" but I'd like to see "Your" in the breadcrumb and anywhere else "my" is still used.

**Comment by mjgiarlo** [comment]
@ggeisler Do you prefer `Your Dashboard /  Your Works / ...` to `Dashboard / Works / ...`? I'm questioning how much we want to stick with possessives in these contexts.

**Comment by ggeisler** [comment]
@mjgiarlo I don't have any strong attachment to the "Your" approach, but if we drop the possessives we'll need a strategy for disambiguation in instances like these:

![works](https://cloud.githubusercontent.com/assets/101482/26069889/68aa6e50-3957-11e7-85ea-5f20d33239bf.png)
---
![works 2](https://cloud.githubusercontent.com/assets/101482/26069892/6d174986-3957-11e7-989f-3abcced13dde.png)

**Comment by elrayle** [comment]
* I suggest that we do not include possessives in breadcrumbs, but do include them in tabs.
* I suggest that we do include possessives in the left menu when they are distinguishing my personal activity vs. sitewide activity the admin might see.  This is similar to the use of Dashboard as the title when admin user and Your Dashboard when a non-admin.
* I suggest that all occurrences of My be changed to Your (based on discussion in this issue)

I am working on an actionable issue and would like to get a final word on this.  Take a look at Issue #2598.

**Comment by elrayle** [comment]
This issue has been superseded by breadcrumb refactor issues.

Closed: #2818, #2819, #2820, #2829, #2848
Open: #2892 

A review is beginning to compare the refactors to date with the [overall design of the breadcrumb refactor](https://docs.google.com/spreadsheets/d/1Bppr6IRWljrNmEFpVm3vnMlSnuFJs29DES-YDMV_rOs).  Issues will be added for any that do not comply.
