### ISSUE TITLE
Possible duplicate templates?

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#913]
So we have both:

https://github.com/projecthydra-labs/hyrax/blob/master/app/views/hyrax/base/_attributes.html.erb

and 

https://github.com/projecthydra-labs/hyrax/blob/master/app/views/hyrax/base/_metadata.html.erb

which share an awful lot of code. Do we still need both? If so, might it make sense to extract common bits into a new partial so we have fewer places to update code?

@projecthydra-labs/hyrax-code-reviewers

**Comment by jcoyne** [comment]
Yes, I think we can remove the former.  I only see it used by `app/views/hyrax/single_use_links_viewer/show.html.erb`

**Comment by no-reply** [comment]
Closing this, as these now have substantive differences. The shared code seems to be in `attribute_rows`.
