### ISSUE TITLE
In the review panel, if you hit submit without choosing an action, you get an app error

### ISSUE THREAD

**Issue by jenlindner** [samvera/hyrax#934]
From Advanced Hydra Camp, Hyrax 2 I think. I'll review which branch/release this occurs in.

<img width="1184" alt="error" src="https://cloud.githubusercontent.com/assets/186452/25909545/218e5eec-3573-11e7-9799-b02a2101d2b9.png">

**Comment by mjgiarlo** [comment]
Thanks for taking this on, @jenlindner!

**Comment by mjgiarlo** [comment]
@jenlindner Do you still have time to work on this? Checking in to see how things are going.

**Comment by mjgiarlo** [comment]
@jenlindner Ping re: :point_up: ?

**Comment by jenlindner** [comment]
I'm so sorry. No, things really got away from this month.

**Comment by mcdowney** [comment]
Closing; this looks like it's fixed--"Comment only" is now the default and it doesn't appear possible to select a blank action.
