### ISSUE TITLE
Workflow widget is acting erratically

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#943]
### Descriptive summary

Working on the master branch, there appears to be some buggy behavior in the workflow widget.

### Expected behavior

1. The widget should stay in the correct location on the page.
2. The widget should show all of the options.
3. The widget should not throw an exception error.

### Actual behavior

1. The widget occasionally dropped into the page footer area rather than below the work. This happens fairly frequently. "Inspect" brings it back into the expected location.
![screen shot 2017-05-11 at 11 04 55 am](https://cloud.githubusercontent.com/assets/17851674/25958176/f89e20d2-363d-11e7-94f0-22734eec76dd.png)

2. The widget sometimes didn't include the option to approve. 
![screen shot 2017-05-11 at 11 05 08 am](https://cloud.githubusercontent.com/assets/17851674/25958188/0323e99c-363e-11e7-9441-2412e2f6db81.png)

3. When using the widget from above, with the missing approve option, to request another review, I received an exception error, so these two are likely related. 
[Backtrace ](https://gist.github.com/laritakr/a7793b39fa67307c4a45d50d397d68fa)
PowerConverter::ConversionError at /concern/workflow_actions/6395w7085
Unable to convert false to 'sipity_action' (scope: #<Sipity::Workflow id: 2, name: "one_step_mediated_deposit", label: "One-step mediated deposit workflow", description: "A single-step workflow for mediated deposit in whi...", created_at: "2017-05-10 18:22:09", updated_at: "2017-05-10 18:24:17", permission_template_id: 1, active: true, allows_access_grant: false>). 

### Steps to reproduce the behavior

The behavior is erratic. I have not yet been able to define a specific series of steps to replicate the issue.

**Comment by mjgiarlo** [comment]
This issue could use more analysis. Thanks for starting to troubleshoot this one, @laritakr

**Comment by mjgiarlo** [comment]
New design will fix this when implemented. Thanks!
