### ISSUE TITLE
non-enabled Terms Component doesn't trigger error telling you to enable terms comonent

### ISSUE THREAD

**Issue by hackartisan** [samvera/hyrax#946]
### Descriptive summary

Admin Statistics pane gives error `ActionView::Template::Error (undefined method `[]' for nil:NilClass):` gist: ActionView::Template::Error (undefined method `[]' for nil:NilClass):

### Rationale

There's error handling intended to catch this mistake, but it doesn't actually kick in because json does exist (but is empty).

### Expected behavior

A missing solr config should log or error the helpful error message.

Is the code supposed to handle empty json gracefully to account for a legitimately empty query? if so then more than just adding a check for `empty?` is required.

### Actual behavior

Error gisted above

### Steps to reproduce the behavior

(I think this would reproduce; haven't tested this method)
1. Remove https://github.com/projecthydra-labs/hyrax/blob/master/solr/config/solrconfig.xml#L190-L199 
1. restart solr
1. visit administration dashboard > statistics

**Comment by rjkati** [comment]
Closing as part of older ticket review. Please re-open if this is still an issue.
