### ISSUE TITLE
Need user-facing label replacement for "Deposited"?

### ISSUE THREAD

**Issue by ggeisler** [samvera/hyrax#947]
Some of us are concerned that the term "Deposited", as used to convey the status of a Work, might be too ambiguous (does that mean submitted the repository? submitted and approved?), especially as we expand the UI with more features and expose the status of works in more places. In particular, the meaning might not be clear to first-time or occasional users.

Potential alternatives:

* ***published*** - conveys that the work has both been submitted and approved, but could cause confusion if the work in question is a pre-print publication (_published_ in repository terms but intentionally _not published_ in journal publication terms)

* ***accepted***

* other ideas?

I'm adding this ticket to Hyrax but I suppose it could be a Hyku ticket instead, if the term "deposited" makes more sense for the more limited scope of Hyrax.

Note also that this topic has previously been discussed a bit in the latter part of this ticket: https://github.com/projecthydra-labs/hyrax/issues/225

**Comment by mjgiarlo** [comment]
What say you, @projecthydra-labs/hyrax-code-reviewers @projecthydra-labs/hyrax-ui-ux-advisors ?

**Comment by jcoyne** [comment]
I'm in favor of "accepted"

**Comment by hannahfrost** [comment]
"Accepted" would be used for all works deposited, regardless of workflow? It makes sense in the context of a mediated workflow (along the lines of "approved"), less so outside that context.

I favor "published". 

"Submitted" is another option, but I still favor "published"

**Comment by hannahfrost** [comment]
Note that we already use "published" for filtering works on the Works page
![screenshot 2017-05-25 07 02 05](https://cloud.githubusercontent.com/assets/1801076/26453320/332cf4e6-4118-11e7-9553-5f6c7ac7d23a.png)

**Comment by no-reply** [comment]
cc: @samvera/hyrax-repo-managers 

any interest in following up on this?

**Comment by julesies** [comment]
There is not a great word for this. I would personally just like to not have a word.
