### ISSUE TITLE
As an Admin Set Manager, I should be able to view and act upon works in Admin Sets I manage in a new "Managed Works" tab

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#965]
I am a Manager of one or more Admin Sets, and I am *not* a Repository Admin. When I click over to `/dashboard/my/works`, I expect to see two tabs: `Managed Works` and `Your Works`. The former tab is a new tab that shows me all works deposited to the Admin Sets I manage. I expect to see all works that have been submitted, regardless of what workflow the works are in, or whether or not they are suppressed.

The design of this tab should follow the design of the `All Works` tab, with the same filters, pagination, and search controls.

To repeat: the Repository Admin should never see this tab. Every user should see one, or at most two, tabs on the `/dashboard/my/works` page.

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars1.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Friday May 12, 2017 at 16:28 GMT_

----

@hannahfrost this seems just like projecthydra-labs/hyrax#855, but "as an admin set manager" instead of "as a repository administrator". Is that correct?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/jcoyne"><img src="https://avatars1.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Friday May 12, 2017 at 16:32 GMT_

----

@hannahfrost is there some reason this is in hyku and not hyrax? 

Additionally, should an "admin set manager" get the "All works" tab on this page? https://github.com/projecthydra-labs/hyku/issues/447#issuecomment-276233397 just like the repository manager has?   Is "All works" going to be confusing?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/hannahfrost"><img src="https://avatars2.githubusercontent.com/u/1801076?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hannahfrost](https://github.com/hannahfrost)**
_Friday May 12, 2017 at 17:03 GMT_

----

@ggeisler See @jcoyne 's comment above. The question is what should appear on an admin set Manager's Works page? This Manager may not be able to see All Works in the repository, and may not have any works of their own to see. Do they get a different tab?

**Comment by mjgiarlo** [comment]
<a href="https://github.com/ggeisler"><img src="https://avatars2.githubusercontent.com/u/101482?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ggeisler](https://github.com/ggeisler)**
_Friday May 12, 2017 at 17:14 GMT_

----

@hannahfrost @jcoyne Yeah, I see the issue. Maybe a third tab is the right approach?

* All Works - for repository manager - everything in the repository
* Managed Works - all works the user can manage by virtue of being an admin set manager for one or more admin sets
* Your Works - works deposited by or shared with the user

**Comment by mjgiarlo** [comment]
@jcoyne @hannahfrost @ggeisler How much design do you think is needed for this ticket? Is @ggeisler's comment above sufficient to make this actionable?

**Comment by hannahfrost** [comment]
@mjgiarlo @jcoyne @ggeisler I believe this to be actionable without further discussion.

**Comment by ggeisler** [comment]
One addendum to my previous comment where I listed three tabs:

> - All Works - for repository manager - everything in the repository
> - Managed Works - all works the user can manage by virtue of being an admin set manager for one or more admin sets
> - Your Works - works deposited by or shared with the user

In case it wasn't clear from that comment, I believe a given user should never see more than two of the three tabs:

- If user is a _Repository manager_ (or other user with ability to manage **all works** in the repo): All Works and Your Works tabs
- If user is _Admin set manager_ (a user that is manager or one or more admin sets): Managed Works and Your Works tabs
- If _normal user_: just Your Works tab

**Comment by hannahfrost** [comment]
@ggeisler That makes sense. I am going to move this to the Ready column

**Comment by mjgiarlo** [comment]
I may have mistakenly added extra baggage to this ticket. I *think* we have two related needs:

1. As an Admin Set Manager, I should be able to view works in the Admin Sets I manage independent of the works that I have deposited. I believe what @ggeisler wrote above works :100: for this.
1. As a Repository Manager *and* an Admin Set Manager, I should be able to view works in the Admin Sets I manage independent of the works that I have deposited *and* I should be able to pick out those works from the list of All Works relatively easily. I believe this is already accommodated via the "Collection" filter here:

![screenshot from 2017-05-31 12-26-47](https://cloud.githubusercontent.com/assets/131982/26649923/919b148e-45fc-11e7-89ee-aee792c71231.png)

@hannahfrost @jcoyne @ggeisler Thus:

1. I'm back to thinking this issue is now ready, and should focus on (1) above. Sorry that I confused things.
2. Should we re-label the "Collection" filter above to "Administrative Set" since this list includes AdminSets and we're in the dashboard side of the UI?

**Comment by mjgiarlo** [comment]
# Original Description

<a href="https://github.com/hannahfrost"><img src="https://avatars2.githubusercontent.com/u/1801076?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hannahfrost](https://github.com/hannahfrost)**
_Friday May 12, 2017 at 16:24 GMT_
_Originally opened as https://github.com/projecthydra-labs/hyku/issues/1111_

----

### Expected behavior

I am a Manager of the default admin set. When I am on the dashboard, I expect to see any works deposited to that admin set listed on the Works page, under the Repository Contents. 

I expect to see works that have been submitted after the time I was granted the role of Manager

I expect to see works that have been submitted, regardless of whether they are in active or not in active workflow.

### Actual behavior

My works page is blank.

![screenshot 2017-05-12 09 20 55](https://cloud.githubusercontent.com/assets/1801076/26007306/c0299472-36f4-11e7-9a7a-a8089bdb15f2.png)

Related to https://github.com/projecthydra-labs/hyrax/issues/853

**Comment by mjgiarlo** [comment]
I updated the acceptance criteria of this issue. (See issue description.) It's now ready to be picket up. Thanks, @jcoyne.

**Comment by hannahfrost** [comment]
@vantuyls Can you confirm that this ticket is still independently needed and useful, and that the need hasn't been subsumed into some other ticket somewhere?

**Comment by vantuyls** [comment]
I don't see a related issue elsewhere. this is functionality we currently see in Collection Extensions work - @elrayle does the implementation of Managed Works come out of CE work or are you leveraging previous work for that?

**Comment by mjgiarlo** [comment]
This work may be done as part of https://github.com/samvera/hyrax/issues/1705

If someone has cycles, this could be tested in nurax. Cc: @hannahfrost @aaron-collier @jcoyne

**Comment by hannahfrost** [comment]
I tested this in nurax just now and confirmed that this change has been implemented. Closing the ticket. Thanks, all!
