### ISSUE TITLE
Edit Admin Set - allows duplicate participants

### ISSUE THREAD

**Issue by dazza-codes** [samvera/hyrax#988]
### Descriptive summary

Hyrax master branch.

### Rationale

When editing an AdminSet to add a participant, the admin-user who created the AdminSet is already a 'manager' (by default, it seems).  When adding the same admin-user as a 'manager' participant, hyrax complies and then lists all the managers with duplicate entries for this admin-user.

### Expected behavior

The participant types (manager, depositor, viewer etc.) are assumed to be a set of hyrax users, not a list of users.  This means the set of managers should have no duplicate entries, all entries are unique and the order of the set is not important (no manager is more or less equal than any other).

### Actual behavior

The participant types seem to behave like a list of hyrax users, allowing duplicate entries.

### Steps to reproduce the behavior

1. Login as an admin user
2. Go to the Admin-Set GUI and add a new AdminSet
3. Go to the participants tab on the new AdminSet and add a new manager participant, using the current admin-user account
4. Once the participant is added, the GUI displays duplicate entries in the Managers table, screen shot attached.

![screenshot from 2017-05-17 09-36-00](https://cloud.githubusercontent.com/assets/240623/26166302/ed32a5f2-3ae7-11e7-8b22-69a7c95117bf.png)

**Comment by darrenleeweber** [comment]
The AdminSet object does not appear to have duplicate data in it, i.e.

**Comment by mjgiarlo** [comment]
@darrenleeweber Check the `Hyrax::PermissionTemplate` that belongs to the AdminSet.

**Comment by darrenleeweber** [comment]
Sorry, I've wiped out my hyrax app and associated Solr/FCrepo data before I saw this request for more info.

**Comment by rjkati** [comment]
This seems to be resolved in Hyrax 3.0.2. I created a new admin set with my admin account and observed that my admin account was added as a manager participant automatically. When I tried to add my admin account as a manager of the admin set, my account only appears once in the manager participant list. @jlhardes

**Comment by jlhardes** [comment]
This issue is no longer occurring so it is closed.
