### ISSUE TITLE
Automatically request review after saving an object when changes requested

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#995]
@jcoyne told me to write this. This could take one step but is currently requiring two.

**Comment by hackmastera** [comment]
Saving an object doesn't seem to me like it necessarily implies that you're done with it.

No great stake in this, just not entirely sure the two should always be conflated.

**Comment by mjgiarlo** [comment]
@hackmastera I am marking this as feedback needed.

Comments, @projecthydra-labs/hyrax-code-reviewers @projecthydra-labs/hyrax-ui-ux-advisors ?
